### PR TITLE
Fix bug in retrieving exponential correction parameters in auto detection mode of Reflectometry Reduction  One Auto algorithm

### LINKED ISSUE #38204: ReflectometryReductionOneAuto fails to look up exponential algorithm parameters
**Describe the bug**

Algorithm `ReflectometryReductionOneAuto` tries to apply an algorithmic correction if no transmission run has been supplied (see https://docs.mantidproject.org/nightly/algorithms/ReflectometryReductionOne-v2.html#transmission-correction). The algorithm to use is looked up from the instrument parameter file. For an exponential correction the values for parameters C0 and C1 are also provided via the parameter file, however the float values are not successfully retrieved because the code uses `getStringParameter` to look them up rather than `getParameterAsString`. This causes the correction to be skipped, and for some reason the error that should be being logged doesn't appear in the messages pane, so this all goes unnoticed by the user.

**To Reproduce**

1) Open the ISIS Reflectometry GUI
1) Change the instrument to `SURF`
1) Enter run number `138942` and angle `0.65` into a row of the run table on the right hand side
1) Click the process button
1) The row should reduce and produce an `IvsQ_binned_138942` workspace
1) Open the workspace history (`Show History` from the right click menu). Expand the history to check the parameter values for `ReflectometryReductionOne`. Look for the values of the `CorrectionAlgorithm`, `C0` and `C1` parameters - these will be `None`, `0`, and `0` respectively, as per this screenshot:

CorrectionAlg

**Expected behavior**

The `ReflectometryReductionOne` parameter values should be as follows:

- `CorrectionAlgorithm` = `ExponentialCorrection`
- `C0` and `C1` = should contain the same values as given in the SURF parameter file

And the correction should be applied.

Would be good to check while we're here that all corrections are being correctly picked up and applied when using auto-detect. The INTER IDF is an example of a polynomial correction.

**Platform/Version (please complete the following information):**
 - Mantid Version: since at least 4.2, if not earlier

### PR DESCRIPTION
**Pull request by adriazalvarez**
### Description of work
The issue is explained in #38204 : parameters for exponential correction were not being correctly retrieved when in autodetect mode, as the instrument parameters were being retrieved as string, but in the case of the exponential parameters, these are better retrieved as numbers. On the other hand, the polynomial parameters have the flexibility of being input as a double list or string with comma separated values for the parameters. 

Additional changes: 
- I have re-set the value of the correction parameters in the calling algorithm `ReflectometryReductionOneAuto`. 
- I have added two tests to check that the correction parameters are being properly called in `AutoDetect` mode both for exponential corrections and polynomial corrections. 

#### Summary of work

Fixes #38204 

### To test:
- Follow testing instructions on #38204 and make sure that the parameters are properly set by looking at the history. 

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

File: Framework/Reflectometry/src/ReflectometryReductionOneAuto3.cpp [hunk 1]
```diff
@@ -587,17 +586,22 @@ void ReflectometryReductionOneAuto3::populateAlgorithmicCorrectionProperties(con
           throw std::runtime_error("Could not find parameter 'polystring' in "
                                    "parameter file. Cannot apply polynomial "
                                    "correction.");
+        setProperty("Polynomial", polyVec[0]);
```
Comment (rbauststfc) [inline Framework/Reflectometry/src/ReflectometryReductionOneAuto3.cpp:589]: Sorry if I'm missing something obvious with this, but I was wondering what's the reason for setting the value on the `ReflectometryReductionOneAuto` property? I notice the same thing is being done on lines 602 and 603 as well.

**Review by rbauststfc — COMMENTED** [review]
I've tested the changes using both an INTER (polynomial correction) and SURF (exponential correction) example and both are working really well - the correct algorithm is selected and the parameters are looked up successfully from the parameter file. 

Just a small thing I noticed (sorry, I couldn't seem to add a comment on the specific line because it's outside the changes in the PR) - the error message on line 610 refers to polynomial correction, but I think the error could technically have been thrown for either correction. It looks like this wasn't made more generic when the exponential correction was added in, so could we update this while we're here?

It's really great to have some tests added to cover this functionality. I've just included a comment to think about how we might make these robust against any future changes in instrument parameter file settings.

File: Framework/Reflectometry/src/ReflectometryReductionOneAuto3.cpp (hunk 1 above)
Comment (adriazalvarez) [reply Framework/Reflectometry/src/ReflectometryReductionOneAuto3.cpp]: I though it could be easier for tracking history (since you can set those parameters on the 'auto' algorithm). Also to support the unit tests. I have change it to made it like you suggest.

File: Framework/Reflectometry/test/ReflectometryReductionOneAuto3Test.h [hunk 2]
```diff
@@ -687,8 +687,39 @@ class ReflectometryReductionOneAuto3Test : public CxxTest::TestSuite {
...
+    alg.setProperty("InputWorkspace", inter);
+    alg.setProperty("CorrectionAlgorithm", "AutoDetect");
+    alg.execute();
+
+    TS_ASSERT_EQUALS(alg.getPropertyValue("Polynomial"), polStringInter);
+  }
+
+  void test_autodetect_on_surf_instrument_sets_exponential_correction() {
+    // SURF instrument has exponential corrections
+    LoadEmptyInstrument loadInstAlg;
```
[the remark this answers is not in the document]
Comment (adriazalvarez) [reply Framework/Reflectometry/test/ReflectometryReductionOneAuto3Test.h]: Thanks for letting me know about this. 
I have added two `Refl_Parameters_[ExponentialCorrection|PolynomialCorrection].xml` files.  
As we discussed on Friday, adding the files was not without consequence, as the instrument cache does not reset and it affects other tests that require the artificial 'REFL' instrument. 
I have implemented the solution we discussed, adding a clear cache method on teardown. But the test would also be fine if we just append the two new test at the end of the test suite file (as test are running in top-down order) to reduce some overhead. 
Let me know what you prefer.

**Comment by adriazalvarez** [comment]
Thanks for the careful review and the useful tips. 
I have change the throw error message to refer to `Algorithmic correction` instead of just `Polynomial correction`.

File: Framework/Reflectometry/test/ReflectometryReductionOneAuto3Test.h [hunk 3]
```diff
@@ -8,6 +8,7 @@
 
 #include <cxxtest/TestSuite.h>
 
+#include "MantidDataHandling/LoadEmptyInstrument.h"
```
Comment (rbauststfc) [inline Framework/Reflectometry/test/ReflectometryReductionOneAuto3Test.h:11]: Is this import needed now that we're using the test parameter files?

File: Framework/Reflectometry/test/ReflectometryReductionOneAuto3Test.h (hunk 2 above)
[the remark this answers is not in the document]
Comment (rbauststfc) [reply Framework/Reflectometry/test/ReflectometryReductionOneAuto3Test.h]: Thanks, I guess that makes sense that it would work if we re-ordered the tests. My feeling is that clearing the cache is still a good solution, though, even though it has additional overhead. That way we're not relying on the order of the tests being maintained in future (i.e. it won't matter if someone adds a new test at the end of the file), and it also means that the tests will be robust if they are ever run out of their normal order.

**Review by rbauststfc — COMMENTED** [review]
Thanks very much for investigating using a test parameter file in the unit tests, it's great to have that working and it should hopefully help to make the test more robust over the long-term. It looks like there's an import in the unit test file that's left over from before the recent changes that I think we could remove, but otherwise all the code changes are looking really good!

I think the CI failures are unrelated to your changes, there seem to be failures on a few PRs, so I'll flag to the Dev Ops team just in case.

**Review by rbauststfc — APPROVED** [review]
Thanks very much Adrian for your hard work getting the test parameter file to work in the unit tests. All the code changes are looking good, the fix is working well and all review comments have been addressed, so this looks good to go in. 👍
