### PR TITLE
13932 fix loose coupling of reflmainviewpresenter

### LINKED ISSUE #13932: Loose coupling broken on ReflMainViewPresenter
Hard coupling between user interface and controlling/presenter code introduced. See [here](https://github.com/mantidproject/mantid/blob/master/MantidQt/CustomInterfaces/src/ReflMainViewPresenter.cpp#L301:L304). The Presenter has been locked into the View because QFileDialog is very specific to Qt. This would make it practically impossible for a test harness to test this IPython notebook functionality. 

To Fix this. The **View** should have an abstract method something like `requestNotebookPath` (pure virtual), which would probably return a std::string (or poco filepath) for the location. The concrete implementation of the view should coordinate calls to the QFileDialog to achieve this. 

Once this is in place, you can prove that you have achieved abstraction by writing a unit test case for this functionality.

I'm setting this to high-priority since this UI will be subject to change shortly and I don't want other developers put of from adding tests because they're confused about how to get the presenter under test.

### PR DESCRIPTION
**Pull request by matthew-d-jones**
Fixes #13932 
Problem and solution explained fully in [issue](#13932).

For Tester:
Please review code.
I suggest loading "INTER_NR_test2.tbl" as described in the [documentation](http://docs.mantidproject.org/nightly/interfaces/ISIS_Reflectometry.html).
Select the "Output Notebook" checkbox next to the "Process" button before processing. Check that you are prompted for a save location for the notebook at this point.

### CODE REVIEW

File: MantidQt/CustomInterfaces/src/ReflMainViewPresenter.cpp [hunk 1]
```diff
@@ -295,16 +295,15 @@ namespace MantidQt
...
-      std::unique_ptr<ReflGenerateNotebook> notebook(new ReflGenerateNotebook(
-        m_wsName, m_model, m_view->getProcessInstrument(), COL_RUNS, COL_TRANSMISSION, COL_OPTIONS, COL_ANGLE,
-        COL_QMIN, COL_QMAX, COL_DQQ, COL_SCALE, COL_GROUP));
-      QString qfilename = QFileDialog::getSaveFileName(0, "Save notebook file", QDir::currentPath(),
-                                                       "IPython Notebook files (*.ipynb);;All files (*.*)",
-                                                       new QString("IPython Notebook files (*.ipynb)"));
-      std::string filename = qfilename.toStdString();
+
+      std::string filename = m_view->requestNotebookPath();
       if (filename == "") {
```
Comment (OwenArnold) [inline MantidQt/CustomInterfaces/src/ReflMainViewPresenter.cpp]: I would have said to call filename.empty(), but what you've done is fine.

File: MantidQt/CustomInterfaces/test/ReflMainViewPresenterTest.h [hunk 2]
```diff
@@ -579,6 +609,52 @@ class ReflMainViewPresenterTest : public CxxTest::TestSuite {
...
+    EXPECT_CALL(mockView, getEnableNotebook())
+      .Times(1)
+      .WillRepeatedly(Return(true));
+    EXPECT_CALL(mockView, requestNotebookPath())
+      .Times(1);
+    presenter.notify(IReflPresenter::ProcessFlag);
+
+    // Tidy up
+    AnalysisDataService::Instance().remove("TestWorkspace");
+    AnalysisDataService::Instance().remove("IvsQ_12345");
```
Comment (OwenArnold) [inline MantidQt/CustomInterfaces/test/ReflMainViewPresenterTest.h]: In future tests, and in your development work in general. Try very hard not to put things in the ADS. 

It was probably unavoidable in this case, but should be considered if possible next time round.

File: MantidQt/CustomInterfaces/test/ReflMainViewPresenterTest.h [hunk 3]
```diff
@@ -136,6 +137,8 @@ class ReflMainViewPresenterTest : public CxxTest::TestSuite {
 
     TS_ASSERT(AnalysisDataService::Instance().doesExist("TestWorkspace"));
     AnalysisDataService::Instance().remove("TestWorkspace");
+
+    TS_ASSERT(Mock::VerifyAndClearExpectations(&mockView));
```
Comment (OwenArnold) [inline MantidQt/CustomInterfaces/test/ReflMainViewPresenterTest.h]: Excellent, thanks for retrofitting.
