### PR TITLE
Indirect FQFit Column Heading value is wrong

### LINKED ISSUE #26035: Indirect FQFit Column value in result workspace is wrong
**Original reporter:** Spencer

### Expected behavior
The column heading value after an FQFit should be 0 if trying to place text as an x value, not `8e+307`.

### Actual behavior
`8e+307` is in the column heading instead of `0`.

### Steps to reproduce the behavior
1.`Interfaces`->`Indirect`->`Data Analysis`->`FQFit` tab
2. Load data
3. Select `TeixeiraWater` fit type.
4. Click `Run`
5. Open the `iris26176_graphite002_conv_1L_s0_to_17_Result_HWHM_FofQFit_TeixeiraWater` workspace
6. The column heading value should be 0:
image

**Data Files**
[iris26176_graphite002_conv_1L_s0_to_17_Result.zip](https://github.com/mantidproject/mantid/files/3335213/iris26176_graphite002_conv_1L_s0_to_17_Result.zip)

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR fixes a bug where the column heading value after an FQFit is `8e+307` instead of being `0`.

No release notes required as this is a minor bug.

**To test:**
1.`Interfaces`->`Indirect`->`Data Analysis`->`FQFit` tab
2. Load data
3. Select `TeixeiraWater` fit type.
4. Click `Run`
5. Open the `iris26176_graphite002_conv_1L_s0_to_17_Result_HWHM_FofQFit_TeixeiraWater` workspace
6. The column heading value should be 0:
image

**Data Files**
[iris26176_graphite002_conv_1L_s0_to_17_Result.zip](https://github.com/mantidproject/mantid/files/3335213/iris26176_graphite002_conv_1L_s0_to_17_Result.zip)

Fixes #26035

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/scientific_interfaces/Indirect/JumpFitModel.cpp [hunk 1]
```diff
@@ -364,6 +364,8 @@ std::string JumpFitModel::singleFitOutputName(std::size_t index,
 
 std::string JumpFitModel::getResultXAxisUnit() const { return ""; }
 
+std::string JumpFitModel::getResultLogValue() const { return "SourceName"; }
```
Comment (DTasev) [inline qt/scientific_interfaces/Indirect/JumpFitModel.cpp]: `SourceName` was previously referred to as LogName, I am confused as to why it is now returned as the LogValue

**Review by dtasev — CHANGES_REQUESTED** [review]
Just a question to clarify, works well locally

File: qt/scientific_interfaces/Indirect/JumpFitModel.cpp (hunk 1 above)
Comment (robertapplin) [reply qt/scientific_interfaces/Indirect/JumpFitModel.cpp]: Good question, I think the surrounding code in QENSFitSequential uses `LogValue` instead of `LogName` in order to stay consistent with the `LogValue` property seen in the `PlotPeakByLogValue` algorithm. It might make more sense to change all of these to `LogName`, do you think it might be worth doing this?

Comment (robertapplin) [reply qt/scientific_interfaces/Indirect/JumpFitModel.cpp]: @DTasev It seems `PlotPeakByLogValue` and its `LogValue` property is used within the `FitPropertyBrowser`. I think I should avoid changing this, instead I will just change the QENSFitSequential algorithm and the IndirectFittingModel mentions of `LogValue` to `LogName`

Comment (DTasev) [reply qt/scientific_interfaces/Indirect/JumpFitModel.cpp]: I see, I think this change makes it a bit easier to understand

**Review by dtasev — APPROVED** [review]
I think this is ready after the tests pass :+1:
