### PR TITLE
Error when deleting a workspace group in MantidPlot.

### LINKED ISSUE #22225: Error when deleting a workspace group in MantidPlot
### Expected behavior
Delete workspace groups in MantidPlot without problem

### Actual behavior
Deleting an open group in the workspace dock widget may result in an unhandled exception popup.

### Steps to reproduce the behavior
* Create/load a large workspace group (15 - 20 items)
* Open / unfold the group in the dock widget
* Delete the group while it's still open

### Platforms affected
All

### PR DESCRIPTION
**Pull request by mantid-roman**
The error is due to a race condition. The change eliminates one by retrieving all group members in a single call guarded by a mutex.

**To test:**

See the bug description.

Fixes #22225

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/widgets/common/src/WorkspacePresenter/WorkspaceTreeWidget.cpp [hunk 1]
```diff
@@ -733,9 +733,8 @@ void WorkspaceTreeWidget::populateChildData(QTreeWidgetItem *item) {
   Workspace_sptr workspace = userData.value<Workspace_sptr>();
 
   if (auto group = boost::dynamic_pointer_cast<WorkspaceGroup>(workspace)) {
-    const size_t nmembers = group->getNumberOfEntries();
-    for (size_t i = 0; i < nmembers; ++i) {
-      auto ws = group->getItem(i);
+    auto members = group->getAllItems();
+    for (auto ws : members) {
```
Comment (martyngigg) [inline qt/widgets/common/src/WorkspacePresenter/WorkspaceTreeWidget.cpp]: We should use `const auto &ws` to save another `shared_ptr` copy.

**Review by martyngigg — CHANGES_REQUESTED** [review]

**Review by martyngigg — DISMISSED** [review]

**Review by martyngigg — CHANGES_REQUESTED** [review]
@mantid-roman The reflectometry doc tests seem to be consistently failing here. Could you take a look?

**Review by martyngigg — APPROVED** [review]
It turns out the confusion was over IDF changes that are not in this branch.
This is all good.
