### PR TITLE
Make PaalmanPingsMonteCarloAbsorption work for elastic datasets

### LINKED ISSUE #28914: Allow PaalmanPingMonteCarloAbsorption to run on elastic instruments
The PaalmanPingsMonteCarloAbsorption algorithm is intended to allow elastic (diffraction) datasets to be processed but at the moment it fails because of a bug in this piece of code which results in the algorithm requiring an EFixed parameter even for a diffraction instrument:
```
        self._sample_unit = self._sample_ws.getAxis(0).getUnit().unitID()
        if self._sample_unit == 'dSpacing':
            self._emode = 'Elastic'
        else:
            self._emode = str(self._sample_ws.getEMode())
        if self._emode == 'Indirect' or 'Direct':
            self._efixed = self._get_efixed()
```
The final if statement should instead be if self._emode == 'Indirect' or if self._emode == 'Direct' so that it evaluates to false for a diffraction instrument. At the moment the string constant 'Direct' isn't compared to self._efixed and is always evaluated as true. This was a problem in the original CalculateMonteCarloAbsorption algorithm as well.

There is also a more minor problem that the "No Efixed parameter found" error is suppressed when running with an elastic dataset and a cylinder shape. You instead get a "RuntimeError: '<=' not supported between instances of 'NoneType' and 'NoneType'" error that comes from some of the validation checks in validateInputs. These don't work because _setup has exited early and so self_container_radius is empty.

### PR DESCRIPTION
**Pull request by DannyHindson**
**Description of work.**

The PaalmanPingsMonteCarloAbsorption algorithm and the indirect UI that runs this algorithm both had small problems that prevented running with elastic (diffraction\SANS) workspaces. This PR resolves those problems. The motivation for adjusting the indirect UI in this way is that it will allow some diffraction\SANS users to evaluate the indirect abs correction UI with a view to perhaps cloning or implementing something similar in their own reduction UIs in future

**To test:**

Run this script that creates some elastic workspaces. The ConvertUnits algorithm sets the EMode of the workspace it processes according to the value supplied in its EMode parameter - and that parameter has a default value of elastic):
```
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

# load example data (TOF)
data_s = CreateSampleWorkspace(WorkspaceType='Histogram', Function='Powder Diffraction',BinWidth=10)
data_s = ConvertUnits(data_s, Target="Wavelength")

data_c = CreateSampleWorkspace(WorkspaceType='Histogram', Function='Flat background',BinWidth=10)
data_c = ConvertUnits(data_c, Target="Wavelength")

abscor_sampleandcontainer = PaalmanPingsMonteCarloAbsorption(SampleWorkspace=data_s, 
                                                             ContainerWorkspace=data_c,
                                                             BeamHeight=1.0,
                                                             BeamWidth=0.8,
                                                             Shape='Cylinder',
                                                             Height=4.0,
                                                             SampleRadius=2.0,
                                                             SampleChemicalFormula='Ni',
                                                             ContainerRadius=2.3,
                                                             ContainerChemicalFormula='Al',
                                                             EventsPerPoint=100)
```

Then open up the Interfaces, Indirect, Corrections UI and go to the Calculate Monte Carlo Absorption tab. On the settings button uncheck the "Restrict allowed input files" setting. Back on the Calculate Monte Carlo tab, check the "Use Container" check box and select the data_s and data_c workspaces (created by the script above) for the sample and container inputs respectively. Set Events to 100. Set the Chemical Formula to Ni in both the Sample Details and Container Details sections. Leave Sample Shape as flat plate and set all of the dimensions to 1mm instead of the default 0mm. Click on the Run button to run a calculation (PaalmanPingsMonteCarloAbsorption algorithm is run) on this tab and check it completes successfully.

Fixes #28914 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DannyHindson** [comment]
@AnthonyLim23 - just wanted to let you know there's a small change to one of the Indirect units in this PR:
qt/scientific_interfaces/Indirect/AbsorptionCorrections.cpp

This is a further small change to the Indirect, Corrections UI to allow it to run on elastic datasets. There was some interest in me doing this from the instrument scientists following my presentation last week eg Steve King on SANS. Given this Indirect UI is pretty generic they would like to have a look at it with a view to possibly cloning it or creating a tab in their own reduction UI.

File: qt/scientific_interfaces/Indirect/AbsorptionCorrections.cpp [hunk 1]
```diff
@@ -486,7 +490,8 @@ void AbsorptionCorrections::convertSpectrumAxes(
 void AbsorptionCorrections::convertSpectrumAxes(
     const MatrixWorkspace_sptr &correction,
     const MatrixWorkspace_sptr &sample) {
-  if (correction && sample && getEMode(sample) == "Indirect") {
+  if (correction && sample &&
+      sample->getEMode() == DeltaEMode::Type::Indirect) {
```
Comment (Mantid-Matthew) [inline qt/scientific_interfaces/Indirect/AbsorptionCorrections.cpp:494]: Just to double check is this check supposed to be just Indirect or should it include Direct as well?

File: Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/PaalmanPingsMonteCarloAbsorptionTest.py [hunk 2]
```diff
@@ -22,12 +22,14 @@ def setUpClass(cls):
         Load('irs26173_graphite002_red.nxs', OutputWorkspace='container_ws')
         Load('osi104367_elf.nxs', OutputWorkspace='indirect_elastic_ws')
         Load('ILL_IN16B_FWS_Reduced.nxs', OutputWorkspace='indirect_fws_ws')
+        Load('HRP38692a', OutputWorkspace='elastic_ws')
```
Comment (Mantid-Matthew) [inline Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/PaalmanPingsMonteCarloAbsorptionTest.py:25]: Would it be possible to add a test on some direct data here as well. As there seems to be multiple places in the code where Direct has been added later as a seperate case and it would be nice to have some surity it works.

**Comment by Mantid-Matthew** [comment]
When I try and run the script above I get the following error

```
RuntimeError: '<=' not supported between instances of 'NoneType' and 'NoneType'
  at line 595 in 'C:/Users/tgz88916/Documents/Mantid2/mantid/Framework/PythonInterface/plugins/algorithms\WorkflowAlgorithms\PaalmanPingsMonteCarloAbsorption.py'
  File "<string>", line 13, in <module>
  File "c:\users\tgz88916\documents\mantid2\mantid\framework\pythoninterface\mantid\simpleapi.py", line 1136, in algorithm_wrapper
    algm.execute()
```

when I try to run the algorithm from the algorithm executer diolag antid crashes to desktop instead.

File: qt/scientific_interfaces/Indirect/AbsorptionCorrections.cpp (hunk 1 above)
Comment (DannyHindson) [reply qt/scientific_interfaces/Indirect/AbsorptionCorrections.cpp:494]: Well I made the change mainly because the IndirectTab::getEMode function was incorrectly identifying elastic workspaces as Indirect. So I've swapped over to using ExperimentInfo::getEMode() instead. This means the code no longer throws an error trying to convert the spectrum axis on elastic workspaces.

I think the fact that this UI converts the spectrum axis into ElasticQ as a final step for all Indirect workspaces is a bit unnecessary\aggressive so I'm tempted to leave it as it is rather than apply this final step to Direct also. Without this the units on the spectrum axis in the absorption correction result would match the units on the original (uncorrected) workspace - which may well be ElasticQ but could be something else.

Comment (DannyHindson) [reply qt/scientific_interfaces/Indirect/AbsorptionCorrections.cpp:494]: Well I made the change mainly because the IndirectTab::getEMode function was incorrectly identifying elastic workspaces as Indirect. So I've swapped over to using ExperimentInfo::getEMode() instead. This means the code no longer throws an error trying to convert the spectrum axis on elastic workspaces.

I think the fact that this UI converts the spectrum axis into ElasticQ as a final step for all Indirect workspaces is a bit unnecessary\aggressive so I'm tempted to leave it as it is rather than apply this final step to Direct also. Without this the units on the spectrum axis in the absorption correction result would match the units on the original (uncorrected) workspace - which may well be ElasticQ but could be something else.

**Comment by DannyHindson** [comment]
I've just pushed a commit to add in a Direct instrument test - which failed initially (!) so have made an adjustment to the algorithm to fix this.
The error you found when running the script is what I get when running the script on the current master code (it's caused by the EFixed parameter being required for elastic workspaces but the validation code doesn't report this v nicely). 
Part of the purpose of this PR is to remove that check for elastic workspaces and also to report the "missing efixed" error more nicely for inelastic - if you're getting the error from the new code then let me know.

**Comment by Mantid-Matthew** [comment]
I must have built the wrong branch becuase the script now works for me. When I attempt to run the algorithm from the GUI using the above instructions I get the following error however.

```
PaalmanPingsMonteCarloAbsorption started
Error in execution of algorithm PaalmanPingsMonteCarloAbsorption
Sample::getEnvironment - No sample enviroment has been defined.
  at line 329 in 'C:/Users/tgz88916/Documents/Mantid2/mantid/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/PaalmanPingsMonteCarloAbsorption.py'
  caused by line 485 in 'C:/Users/tgz88916/Documents/Mantid2/mantid/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/PaalmanPingsMonteCarloAbsorption.py'
Got error from algorithm "PaalmanPingsMonteCarloAbsorption"
Stopping batch algorithm because of execution error
```

**Comment by DannyHindson** [comment]
I think my instructions for running the UI test weren't precise enough. You need to specify a non-zero "Container Front Thickness" and "Container Back Thickness" for the test to run in addition to making the sample dimensions non-zero. If I leave these two at zero I get the same error as you.

**Review by Matthew-Andrew — APPROVED** [review]
This works for me. It would be nice to produce more useful error messages when some inputs are incorrect but this is beyond the scope of this PR.
