### PR TITLE
EnggGUI:: Vanadium curves now plotting for both banks after calibration

### LINKED ISSUE #16151: Engg GUI: Vanadium curves not being plotted for north or south bank
### Expected behavior
After the completion of calibration, there should be vanadium curves being plotted for each bank separately. 

### Actual behavior
Currently curves are being plotted for one of the bank, it is possible that `Bank 1` is being plotted which is then overwritten with `Bank 2`. 

### Steps to reproduce the behavior

Run `Calibration` on `Engineering Diffraction Analysis` GUI

### Platforms affected
All.

### PR DESCRIPTION
**Pull request by shahrozahmed1**
**Description of work.**

After calibration has completed on the Engineering Diffraction GUI, the vanadium curves should now be plotted for each bank separately. 

**To test:**

Go to: `Interfaces/Diffraction/Engineering Diffraction/Settings`
Go to the `Calibration` directory listed

Either:
- Delete the existing files which would only generate vanadium curves for one bank
- Change the calibration directory 

Files to delete should look something like this: `ENGINX_precalculated_vanadium_run00236516_bank_curves.nxs` & `ENGINX_precalculated_vanadium_run00236516_integration.nxs`
_(NOTE: Deleting these files or changing the calibration directory will force the GUI to run `EnggVanadiumCorrection` and produce the valid files)_

Go to: `Interfaces/Diffraction/Engineering Diffraction/Calibration`
Run Calibration with the default settings
Upon completion 

Check that there are now two plots produced for Vanadium Curves; one for each bank
Check that valid bank title given to each plot produced
Check that `Difc Zero` Peaks also still being plotted

Fixes #16151
_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: MantidQt/CustomInterfaces/inc/MantidQtCustomInterfaces/EnggDiffraction/EnggDiffractionViewQtGUI.h [hunk 1]
```diff
@@ -212,9 +212,7 @@ class MANTIDQT_CUSTOMINTERFACES_DLL EnggDiffractionViewQtGUI
                            const std::string &spectrum,
                            const std::string &type) override;
 
-  void plotVanCurvesCalibOutput() override;
-
-  void plotDifcZeroCalibOutput(const std::string &pyCode) override;
+  void plotCalibOutput(const std::string &pyCode) override;
```
Comment (FedeMPouzols) [inline MantidQt/CustomInterfaces/inc/MantidQtCustomInterfaces/EnggDiffraction/EnggDiffractionViewQtGUI.h]: Note that along these lines we could go further and just have one method to run any plotting/non-plotting Python code in the view. The only reason to have this in the view is that the PythonRunner is part of the view (Mantid Qt sub window), but other than that all the preparation of the code can be done in the presenter.
But that would be for next rounds of refactoring.

**Comment by FedeMPouzols** [comment]
@shahrozahmed1: the builds fail on all platform as the mock methods haven't been updated for the mock view of the unit tests. I built it locally and from the functional point of view it seems to work well though.

**Comment by FedeMPouzols** [comment]
This fixes an  issue in the calibration plots that was found during a demo/early beta testing session with the Engg interface. 

- Code: looks good, together with the bug fix, the python script code has been moved to presenter which is always good.
- Functional testing: works for me also on debian. I followed the testing instructions and I also tried different sequences of cropped/normal calibrations. This works well now.
  - The calibration difc/tzero plots are produced correctly, and the plots for the "cropped" banks are labeled correctly.
  - Now you get the vanadium fit curves for all the banks, 

:shipit:
