### PR TITLE
Fix cppcheck 1.87 warnings in WorkflowAlgorithms

### LINKED ISSUE #22912: Fix cppcheck 1.87 warnings
The newest version of cppcheck throws some warnings that need care.
[cppcheck1-84_report.txt](https://github.com/mantidproject/mantid/files/2191751/cppcheck1-84_report.txt)

### PR DESCRIPTION
**Pull request by soininen**
This PR fixes most `cppcheck` 1.87 warnings in the WorkflowAlgorithms module.

**To test:**

Code review.

Fixes #22912.

*This does not require release notes* because this is an internal change.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/WorkflowAlgorithms/src/EQSANSLoad.cpp [hunk 1]
```diff
@@ -737,7 +737,7 @@ void EQSANSLoad::exec() {
   // Modify TOF
   const bool correct_for_flight_path = getProperty("CorrectForFlightPath");
   double wl_min = 0.0;
```
Comment (TTitcombe) [inline Framework/WorkflowAlgorithms/src/EQSANSLoad.cpp]:
```suggestion
  double wl_min;
```
Is there any reason we can't do the same to wl_min and wl_combined_max?

**Review by TTitcombe — CHANGES_REQUESTED** [review]

File: Framework/WorkflowAlgorithms/src/EQSANSLoad.cpp (hunk 1 above)
Comment (soininen) [reply Framework/WorkflowAlgorithms/src/EQSANSLoad.cpp]: Because it is possible that the initial value for `wl_min` may be used at line 834 and `wl_combined_max` at line 835. `cppcheck` seems to do pretty throughout work here.

Comment (soininen) [reply Framework/WorkflowAlgorithms/src/EQSANSLoad.cpp]: Just to reiterate, it is not possible to remove the initialization from `wl_min` and `wl_combined_max`.

**Review by TTitcombe — APPROVED** [review]
