### PR TITLE
Include time spent in Algorithm::execute in reported time.

### LINKED ISSUE #20445: Algorithm timer shows incorrect runtime
When running an algorithm, the log outputs notices that look like this:
```
AlgorithmName started
AlgorithmName successful, Duration 0.01 seconds
```
The duration here can be extremely misleading.  For example:
```python
import time
start = time.time()
ws = CreateWorkspace(DataX=range(1000000), DataY=range(1000000), NSpec=1000)
print "%.2f sec" % (time.time() - start)
```
Output:
```
6.63 sec
```
Log:
```
CreateWorkspace started
CreateWorkspace successful, Duration 0.07 seconds
```
This happens because the timer is only measuring the `exec` of the algorithm, but there is considerable overhead (separate issue, see #20443) that occurs prior to that. Additionally, the "Algorithm started" message appears long before `exec` is called, so you will actually see the "started" notice, a long delay, followed by a claim of a short duration.

Since the overhead of calling an Algorithm can be so much heavier than the execution of the Algorithm itself, the duration of `exec` alone probably isn't very useful information and we should begin measuring the runtime much sooner.

In any case, a user would expect the timer to start when the "Algorithm started" notice is issued at the latest.

### LINKED ISSUE #21626: Incomplete Algorithm time reporting.
`Algorithm` does not include property validation and other setup code in the reported time. This can lead to large confusing discrepancies between observed and logged time.

### PR DESCRIPTION
**Pull request by SimonHeybrock**
See issue description. Also add debug output regarding time within execute.

**To test:**

Code review.

Fixes #21626.
Fixes #20445.

**Release Notes** 

Updated.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/API/src/Algorithm.cpp [hunk 1]
```diff
@@ -460,6 +461,7 @@ bool Algorithm::execute() {
     logAlgorithmInfo();
 
   // Check all properties for validity
+  float timingInit = timer.elapsed();
```
Comment (OwenArnold) [inline Framework/API/src/Algorithm.cpp]: I find the API for `Timer::elapsed` to be counter intuitive. Reading the code I initially thought that each time point you assign was a total offset since `time` is constructed, however the reset argument defaults to true. Thus your code gives the correct behaviour. I think an improvement to readability for future maintainers would be to explicitly pass the flag indicating that the timer is reset as part of the `elapsed` call.

File: Framework/API/src/Algorithm.cpp [hunk 2]
```diff
@@ -584,6 +592,13 @@ bool Algorithm::execute() {
       setExecuted(true);
 
       // Log that execution has completed.
+      getLogger().debug() << "Time to validate properties: "
```
Comment (martyngigg) [inline Framework/API/src/Algorithm.cpp]: We've observed in the past that there is quite a difference in performance with the loggers if you build the string up externally, either with a `stringstream` or just a `string` and `to_string` and then pass it to getLogger().debug(message_str) in one shot. Is that worth doing here?

**Review by OwenArnold — CHANGES_REQUESTED** [review]
Works. One minor code change requested.

File: Framework/API/src/Algorithm.cpp (hunk 1 above)
Comment (martyngigg) [reply Framework/API/src/Algorithm.cpp]: :+1:

File: Framework/API/src/Algorithm.cpp [hunk 3]
```diff
@@ -584,6 +591,16 @@ bool Algorithm::execute() {
       setExecuted(true);
 
       // Log that execution has completed.
+      getLogger().debug() << "Time to validate properties: " +
```
Comment (martyngigg) [inline Framework/API/src/Algorithm.cpp]: I'd meant something more like:
```
std::string dbgMsg = "Time to validate properties: ";
dbgMsg.append(std::to_string(timingPropertyValidation)).append(" seconds\n");

+ similar append lines for other info...

# and finally send it to the debug log stream in one shot. The stream api flushes each time it encouters a "\n" so
# this will just send the whole lot out once.
getLogger().debug(dbgMsg); 
```

**Review by OwenArnold — APPROVED** [review]

**Comment by OwenArnold** [comment]
Do not merge until Martn's review is complete and tests all pass.

File: Framework/API/src/Algorithm.cpp [hunk 4]
```diff
@@ -584,6 +591,14 @@ bool Algorithm::execute() {
       setExecuted(true);
 
       // Log that execution has completed.
+      getLogger().debug("Time to validate properties: " +
```
Comment (martyngigg) [inline Framework/API/src/Algorithm.cpp]: :+1:

**Review by martyngigg — APPROVED** [review]
Looks good to me too.
