### PR TITLE
Muon analysis Group/pair selection

### LINKED ISSUE #19938: Muon analysis first all groups is wrong
In muon analysis load some data (e.g. musr 62260). Go to settings tab and make sure multiple fitting is selected. Then go to the data analysis tab. 

All groups should be selected, however the list will only include one of the groups.

### PR DESCRIPTION
**Pull request by AnthonyLim23**
In muon analysis the "all groups" selection in the multiple fitting did not select all of the groups when it initially loaded. Furthermore, the groups and pairs were found not to be passed correctly to the data analysis tab. This PR solves both problems. 

1. Load some data into muon analysis. Make sure that a group is plotted.
2. Go to the Grouping Options tab
3. Add a group (including the detector numbers) and some pairs. 
4. Go to the settings tab and make sure multiple fitting is selected. 
5. Go to the data analysis tab. The selected groups should include all of the groups (and the ones added from step 3). 
6. Change the selection in Groups/Pairs to fit to all pairs. It should list all of the pairs (including the ones added in 3). 
7. Go back to the Grouping Options tab and add another pair. 
8. In the data analysis tab the new pair should show up when all pairs is selected. 

Fixes #19938 

**Release Notes** 
Not in the release notes as it was not reported by a user. 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: MantidQt/CustomInterfaces/src/Muon/MuonAnalysis.cpp [hunk 1]
```diff
@@ -1528,7 +1528,14 @@ void MuonAnalysis::updateFrontAndCombo(bool updateIndexAndPlot) {
   if (currentI >= m_uiForm.frontGroupGroupPairComboBox->count()) {
     currentI = 0;
   }
-  m_uiForm.fitBrowser->setAvailableGroups(groupsAndPairs);
+  auto tmp = m_groupingHelper.parseGroupingTable().groupNames;
+  auto names = m_groupingHelper.parseGroupingTable().pairNames;
+  names.insert(std::end(names), std::begin(tmp), std::end(tmp));
```
Comment (DavidFair) [inline MantidQt/CustomInterfaces/src/Muon/MuonAnalysis.cpp]: Since we don't reuse `tmp` can we move the elements instead of copying them: [link](https://stackoverflow.com/a/10720242)

File: MantidQt/CustomInterfaces/src/Muon/MuonAnalysis.cpp [hunk 2]
```diff
@@ -1528,7 +1528,14 @@ void MuonAnalysis::updateFrontAndCombo(bool updateIndexAndPlot) {
...
+  QStringList GroupsAndPairsNames;
+  for (auto name : names) {
```
Comment (DavidFair) [inline MantidQt/CustomInterfaces/src/Muon/MuonAnalysis.cpp]: `const auto &name` to avoid temporary copies

File: MantidQt/CustomInterfaces/src/Muon/MuonAnalysis.cpp [hunk 3]
```diff
@@ -1885,7 +1892,14 @@ void MuonAnalysis::selectMultiPeak(const QString &wsName,
...
                    std::back_inserter(groupsAndPairs), &QString::fromStdString);
-    m_uiForm.fitBrowser->setAvailableGroups(groupsAndPairs);
+    auto tmp = m_groupingHelper.parseGroupingTable().groupNames;
+    auto names = m_groupingHelper.parseGroupingTable().pairNames;
+    names.insert(std::end(names), std::begin(tmp), std::end(tmp));
+    QStringList GroupsAndPairsNames;
+    for (auto name : names) {
+      GroupsAndPairsNames << QString::fromStdString(name);
+    }
+    m_uiForm.fitBrowser->setAvailableGroups(GroupsAndPairsNames);
```
Comment (DavidFair) [inline MantidQt/CustomInterfaces/src/Muon/MuonAnalysis.cpp]: This block of code is duplicated from above - can we move it into a separate function and call it twice instead?

**Review by DavidFair — CHANGES_REQUESTED** [review]

File: MantidQt/CustomInterfaces/src/Muon/MuonAnalysis.cpp (hunk 1 above)
Comment (AnthonyLim23) [inline MantidQt/CustomInterfaces/src/Muon/MuonAnalysis.cpp]: changing it to 

```
auto names = m_groupingHelper.parseGroupingTable().pairNames;
	names.insert(std::end(names), std::make_move_iterator(m_groupingHelper.parseGroupingTable().groupNames.begin()), std::make_move_iterator(m_groupingHelper.parseGroupingTable().groupNames.end()));
	QStringList GroupsAndPairsNames;
```

causes an error. I think we do want a copy, as the group names should still contain the names.

Comment (AnthonyLim23) [inline MantidQt/CustomInterfaces/src/Muon/MuonAnalysis.cpp]: I have added a tmp to store the vector in, this stops it from crashing

Comment (DavidFair) [inline MantidQt/CustomInterfaces/src/Muon/MuonAnalysis.cpp]: I was thinking of something along the lines of:
``` c++
auto tmp = m_groupingHelper.parseGroupingTable().groupNames;
auto names = ....;
names.insert(std::end(names), std::make_move_iterator(tmp.begin()), std::make_move_iterator(tmp.end()));
```

Comment (DavidFair) [inline MantidQt/CustomInterfaces/src/Muon/MuonAnalysis.cpp]: Oh you've already done it - sigh Github....

**Comment by DavidFair** [comment]
Noticed a bug during testing:
Select `All Groups` under data analysis
Go to grouping options add a new group
Go back to data analysis
Notice how `All Pairs` is now selected instead of `All Groups`

**Comment by AnthonyLim23** [comment]
Thats a feature. I have assumed that adding a group or pair does not mean that a user wants to change the selection in the fitting

**Comment by DavidFair** [comment]
Yes but thats the problem - it is changing the selection in the fitting window

**Comment by DavidFair** [comment]
We have determined the pair / group selection changing is an existing issue not related to the changes in this PR. Issue #19986 has been created and I'm happy to :shipit: this.

**Review by DavidFair — APPROVED** [review]
