### PR TITLE
Fix Fitting crash Enginx gui

### LINKED ISSUE #25157: Crashing and Freezing in Fitting tab in ENGINX when run with peaks that it fails to fit
Attempting to fit peaks that lead to the `EnggFitPeaks` algorithm failing appears to cause mantid to crash or freeze when the error message is produced.

### PR DESCRIPTION
**Pull request by LowriJenkins**
**Description of work.**
Removed `userError` from `EnggDiffractionFittingPresenter.cpp` as it caused a crash due to being called from a different thread.

**To test:**
Load this [file](https://github.com/mantidproject/mantid/files/2962693/test.zip) in the fitting window, add `23112.8405` to peaks, and then click fit. An error message should appear in the logger, but mantid should not crash.

Fixes #25157 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/scientific_interfaces/EnggDiffraction/EnggDiffFittingPresenter.cpp [hunk 1]
```diff
@@ -501,8 +501,8 @@ void EnggDiffFittingPresenter::doFitting(const std::vector<RunLabel> &runLabels,
     } catch (const std::runtime_error &exc) {
       g_log.error() << "Could not run the algorithm EnggFitPeaks successfully."
                     << exc.what();
-      m_view->userError("Could not run the algorithm EnggFitPeaks successfully",
-                        exc.what());
+      // A userError should be used for this message once the threading has been
```
Comment (TTitcombe) [inline qt/scientific_interfaces/EnggDiffraction/EnggDiffFittingPresenter.cpp]: Is there an issue to track this?
Given how little the engineering gui is updated there is a danger that this comment will remain far longer than any of us

**Review by TTitcombe — CHANGES_REQUESTED** [review]
Clear message is posted into the logger upon error, rather than crashing mantid :tada: 
Just a small question about issue tracking

File: qt/scientific_interfaces/EnggDiffraction/EnggDiffFittingPresenter.cpp (hunk 1 above)
Comment (SamJenkins1) [reply qt/scientific_interfaces/EnggDiffraction/EnggDiffFittingPresenter.cpp]: There is now https://github.com/mantidproject/mantid/issues/25186

**Review by TTitcombe — APPROVED** [review]
