### PR TITLE
Fixed copy elision warnings from using std::move in EnabledWhenProperty

### LINKED ISSUE #19428: Warnings with Xcode 8.2+
### Expected behavior

Mantid builds without compiler errors or warnings

### Actual behavior

Warnings generated with Xcode 8.2+

```
/Users/svh/Documents/MantidProject/mantid/Framework/Kernel/src/EnabledWhenProperty.cpp:41:11: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
          std::move(std::make_shared<EnabledWhenProperty>(conditionOne)),
          ^
/Users/svh/Documents/MantidProject/mantid/Framework/Kernel/src/EnabledWhenProperty.cpp:41:11: note: remove std::move call here
          std::move(std::make_shared<EnabledWhenProperty>(conditionOne)),
          ^~~~~~~~~~                                                   ~
/Users/svh/Documents/MantidProject/mantid/Framework/Kernel/src/EnabledWhenProperty.cpp:42:11: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
          std::move(std::make_shared<EnabledWhenProperty>(conditionTwo)),
          ^
/Users/svh/Documents/MantidProject/mantid/Framework/Kernel/src/EnabledWhenProperty.cpp:42:11: note: remove std::move call here
          std::move(std::make_shared<EnabledWhenProperty>(conditionTwo)),
          ^~~~~~~~~~                                                   ~
2 warnings generated.
[119/127] Building CXX object Framework/Kernel/CMakeFiles/Kernel.dir/src/VisibleWhenProperty.cpp.o
/Users/svh/Documents/MantidProject/mantid/Framework/Kernel/src/VisibleWhenProperty.cpp:33:11: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
          std::move(std::make_shared<VisibleWhenProperty>(conditionOne)),
          ^
/Users/svh/Documents/MantidProject/mantid/Framework/Kernel/src/VisibleWhenProperty.cpp:33:11: note: remove std::move call here
          std::move(std::make_shared<VisibleWhenProperty>(conditionOne)),
          ^~~~~~~~~~                                                   ~
/Users/svh/Documents/MantidProject/mantid/Framework/Kernel/src/VisibleWhenProperty.cpp:34:11: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
          std::move(std::make_shared<VisibleWhenProperty>(conditionTwo)),
          ^
/Users/svh/Documents/MantidProject/mantid/Framework/Kernel/src/VisibleWhenProperty.cpp:34:11: note: remove std::move call here
          std::move(std::make_shared<VisibleWhenProperty>(conditionTwo)),
          ^~~~~~~~~~                                                   ~
2 warnings generated.
```

### Steps to reproduce the behavior

Build with Xcode 8.2+

### Platforms affected

MacOS 10.11+

These appear to have been introduced in #19264.

### PR DESCRIPTION
**Pull request by DavidFair**
Description of work.
This PR fixes an issue where we were using a std::move which prevents the compiler using elision as a native optimization. This was detected by LLVM (through XCode)

**To test:**
Build against Clang or Xcode. Ensure warning is resolved

Fixes #19428 .

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Kernel/src/EnabledWhenProperty.cpp [hunk 1]
```diff
@@ -37,10 +37,9 @@ EnabledWhenProperty::EnabledWhenProperty(
     : // This method allows the Python interface to easily construct these
       // objects
       // Copy the object then forward onto our move constructor
-      EnabledWhenProperty(
-          std::move(std::make_shared<EnabledWhenProperty>(conditionOne)),
-          std::move(std::make_shared<EnabledWhenProperty>(conditionTwo)),
-          logicOperator) {}
+      EnabledWhenProperty(std::make_shared<EnabledWhenProperty>(conditionOne),
+                          std::make_shared<EnabledWhenProperty>(conditionTwo),
```
Comment (quantumsteve) [inline Framework/Kernel/src/EnabledWhenProperty.cpp]: Historically we have used `boost::shared_ptr` because of its compatibility with `boost::python`.  Should these parameters (and related functions/classes) be changed to use `boost::shared_ptr`?

File: Framework/Kernel/src/VisibleWhenProperty.cpp [hunk 2]
```diff
@@ -29,10 +29,9 @@ VisibleWhenProperty::VisibleWhenProperty(
     const VisibleWhenProperty &conditionTwo, eLogicOperator logicOperator)
     : // For the python interface to be able to easily copy objects in
       // Make a deep copy and turn into a shared pointer and forward on
-      VisibleWhenProperty(
-          std::move(std::make_shared<VisibleWhenProperty>(conditionOne)),
-          std::move(std::make_shared<VisibleWhenProperty>(conditionTwo)),
-          logicOperator) {}
+      VisibleWhenProperty(std::make_shared<VisibleWhenProperty>(conditionOne),
+                          std::make_shared<VisibleWhenProperty>(conditionTwo),
+                          logicOperator) {}
```
Comment (quantumsteve) [inline Framework/Kernel/src/VisibleWhenProperty.cpp]: same question as above.

File: Framework/Kernel/src/EnabledWhenProperty.cpp (hunk 1 above)
Comment (DavidFair) [inline Framework/Kernel/src/EnabledWhenProperty.cpp]: In this case because we aren't using `MatrixWorkspace_sptr` and associated typedefs I opted to use `std::shared_ptr` so we don't need to refactor it at a later date if we use the boost version. 

`boost::python` handles this correctly and the previous PR added some unit tests to check the properties behave correctly just in case

File: Framework/Kernel/src/VisibleWhenProperty.cpp (hunk 2 above)
Comment (DavidFair) [inline Framework/Kernel/src/VisibleWhenProperty.cpp]: ^

**Review by quantumsteve — APPROVED** [review]
The `std::shared_ptr` question is beyond the scope of this pull request.

@DavidFair Thank you for addressing the clang warnings

:shipit:

**Comment by martyngigg** [comment]
It looks like we need [Boost 1.63](https://github.com/boostorg/python/issues/29) to be able to use `std::shared_ptr` with boost without having to register our own types.

**Comment by DavidFair** [comment]
I've just recalled why this does not affect us:
Currently we get `boost` to create an `EnabledWhenProperty` or `VisibleWhenProperty` object directly. The constructors which take existing `WhenProperty objects` handle the shared pointers internally (although from C++ you are also able to pass a shared pointer as well if you want to manage them) to track the two conditions we are combining

**Comment by martyngigg** [comment]
I'm confident that the changes have not caused the unit test failure on MSVC.
