### PR TITLE
Indirect Reduction - Fix error when loading Reduction from invalid facility

### LINKED ISSUE #25290: Indirect - Opening Data Reduction causes uncaught exception when HFIR is the selected facility
### Expected behavior
No error. Perhaps when the data reduction interface is opened and a relevent facility hasn't been selected then the facility should be changed to a relevant one?

### Actual behavior
Opening Data Reduction when the faility has been set to `HFIR` causes:
image

### Steps to reproduce the behavior
1. Set  `HFIR` as default facility
2. Open Indirect->Data Reduction
Error!

### Platforms affected
All I assume

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR fixes a bug causing an error when trying to load the Reduction interface when a non-compatible facility is selected.

**To test:**
1. Set  `HFIR` as default facility
2. Open `Interfaces`->`Indirect`->`Data Reduction`
There should be no error, but a message box telling you to change the facility/instrument.
3. Select the `ISIS` facility and the `TOSCA` instrument
4. Go to `S(Q,w)` tab
5. Load the data below
6. Q-Low, Q_width, Q-High should be 0.5, 0.05 and 1.8
6. E-Low, E_width, E-High should be -0.5, 0.005 and 0.5
7. Click `Run` and a message should appear telling you to choose a valid instrument which has an EFixed.

**Data Files**
[irs26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/3002359/irs26176_graphite002_red.zip)

Fixes #25290

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/scientific_interfaces/Indirect/ISISCalibration.cpp [hunk 1]
```diff
@@ -365,20 +371,23 @@ void ISISCalibration::setDefaultInstDetails() {
   try {
     setDefaultInstDetails(getInstrumentDetails());
   } catch (std::exception const &ex) {
-    g_log.warning(ex.what());
+    showMessageBox(ex.what());
```
Comment (TTitcombe) [inline qt/scientific_interfaces/Indirect/ISISCalibration.cpp]: Does showMessageBox also post to the logger? I would recommend always having a persistent log of errors in case a user closes a box too early

**Comment by TTitcombe** [comment]
Q Low, Q width, and Q High are 0.0 when I load the data

**Comment by robertapplin** [comment]
@TTitcombe My bad, the description was meant to say set QLow, QWidth and QHeight as 0.5, 0.05 and 1.8

**Review by TTitcombe — APPROVED** [review]
Code changes good. Release notes updated. Clear error message displayed when running the data, as intended :+1:
