### PR TITLE
Normalize the data

### LINKED ISSUE #34995: Manual Testing Step scan analysis
You have been assigned manual testing. The hope is to catch as many problems with the code before release, so it would be great if you can take some time to give a serious test to your assigned area. Thank you!!

The general guide to manual testing:

* The tests must be performed on the installer versions of the final release candidate. Not on local compiled code.
* Serious errors involving loss of functionality, crashes etc. should be raised
as issues with the current release as a milestone and an email sent to the project manager immediately.
* Minor and cosmetic issues should be raised as issues against the forthcoming
releases.
* First try things that should work, then try to break Mantid, e.g. entering invalid values, unexpected characters etc.
* Don't spend more than a few hours on the testing as fatigue will kick in.
* If you find errors in the documentation, please correct them.
* Comment against this ticket the OS environment you are testing against.
* Close the this issue once you are done.

### Specific Notes:

See http://www.mantidproject.org/Step_Scan_Interface

### PR DESCRIPTION
**Pull request by AndreiSavici**
Re #34995. Issue found that data is not normalized

**Description of work.**

**To test:**
Start StepScan interface. Load /SNS/HYS/IPTS-14344/nexus/HYS_111669.nxs.h5. Plot the data. Change normalization. See that the numbers on the y axis change.

Fixes #34995. 

*This does not require release notes* because **bug introduced in this release**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by jmborr — DISMISSED** [review]
Already tested it

File: qt/scientific_interfaces/General/StepScan.cpp [hunk 1]
```diff
@@ -598,7 +598,8 @@ void StepScan::generateCurve(const QString &var) {
 
     MatrixWorkspace_sptr top = AnalysisDataService::Instance().retrieveWS<MatrixWorkspace>(m_plotWSName);
     MatrixWorkspace_sptr bottom = norm->getProperty("OutputWorkspace");
-    top = top / bottom;
+    top /= bottom;
+    AnalysisDataService::Instance().addOrReplace(m_plotWSName, top);
```
Comment (jmborr) [inline qt/scientific_interfaces/General/StepScan.cpp:602]: why is this needed? I thought the `/=` would preserve the pointer 🤔

Comment (AndreiSavici) [reply qt/scientific_interfaces/General/StepScan.cpp:602]: It seems like `top = top / bottom;` creates a new workspace, which it does not put it back in AnalysisDataService

**Comment by jmborr** [comment]
@AndreiSavici if you've verified the interface is working, then let me know and I'll hit the Approve button

**Review by jmborr — APPROVED** [review]
