### PR TITLE
Fix for Alf view not loading data bug

### LINKED ISSUE #34085: ALF View is not loading data
ALF view is not loading the data into the GUI correctly. The calculation looks correct and the data looks the same when opened for the ADS

The GUI should show something similar to (just look for the correct colour plot I am not sure the number is correct as it doesnt match instrument view)

image

Open ALF view
Enter 80510, press enter
The instrument image should update - but it doesnt

To get it to work you need to press the "reset" button on the d-spacing. We should automatically do it when data is loaded https://github.com/mantidproject/mantid/blob/main/qt/widgets/instrumentview/src/BaseCustomInstrumentPresenter.cpp#L50

### PR DESCRIPTION
**Pull request by SilkeSchomann**
**Description of work.**
Update the maximum range of the integration widget when initializing after data was loaded successfully. This ensures that the instrument image is updated after loading data as it would otherwise remain empty.

**To test:**
Follow steps from original issue and check that the instrument image is updated as soon as the d-spacing bar is displayed (usually takes a few seconds).

Fixes #34085 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
@AnthonyLim23 Could you pick this up for review?

**Comment by AnthonyLim23** [comment]
I can do a non-conda test, which should be ok for testing this

**Review by AnthonyLim23 — APPROVED** [review]
The full workflow now works like it used to :shipit:

File: qt/widgets/instrumentview/src/InstrumentWidget.cpp [hunk 1]
```diff
@@ -763,6 +763,10 @@ void InstrumentWidget::updateIntegrationWidget(bool init) {
     } else {
       m_xIntegration->setRange(0, 0);
     }
+  } else {
```
Comment (martyngigg) [inline qt/widgets/instrumentview/src/InstrumentWidget.cpp:766]: I'm just looking at the comment in the `init` `if` above. Have we tried replacing workspace here? The comment above suggests there may be an issue if `setRange` (called by `setWholeRange`) is called if `init` is True?

Comment (SilkeSchomann) [reply qt/widgets/instrumentview/src/InstrumentWidget.cpp:766]: Yes, the workspace is replaced after loading data for the first time. The first time `updateIntegrationWidget` is called `minRange` and `maxRange` are 0. After loading data successfully `updateIntegrationWidget` is called again (with `init` set to True) with the new values for `minRange` and `maxRange`. The instrument viewer has already been initialized by that time.
