### PR TITLE
Workbench reduce logging for help

### LINKED ISSUE #25369: Reduce the logging for help in the workbench
### Expected behavior
Opening a few help pages should not spam the Massages window (by default)

### Actual behavior
We get messages like this for every help page opened.
```
Offline help is not available in this version of Workbench.
Opening online help page:
https://docs.mantidproject.org/algorithms/PowderILLParameterScan-v1.html
```

The first message should not be warning level, probably information, and should ideally only be output once per Mantid session.
The second should probably be a debug message.

### Steps to reproduce the behavior

1. Open the workbench, and open an algorithm dialog
1. Click the ? button

### Platforms affected
All

### PR DESCRIPTION
**Pull request by ghost**
**Description of work.**
The logging level of messages outputted when opening online help pages has been reduced (notice to debug). 

The message `Offline help is not available in this version of Workbench` has been reduced to information level and will only be shown once per session.

**To test:**
- Open an algorithm run dialog and click the **?** help button.
- A message at information level should read: `Offline help is not available in this version of Workbench` and a message at debug level should notify what webpage is being opened.
- Clicking the help button again should still re-direct to the online help and log (at debug level) what webpage is being opened, but should **not** log the information level message above.

Fixes #25369 .

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/widgets/common/src/InterfaceManager.cpp [hunk 1]
```diff
@@ -230,8 +233,11 @@ void InterfaceManager::registerHelpWindowFactory(
 
 MantidHelpInterface *InterfaceManager::createHelpWindow() const {
   if (m_helpViewer == nullptr) {
-    g_log.warning(
-        "Offline help is not available in this version of Workbench.");
+    if (!offlineHelpMsgDisplayed) {
+      g_log.information(
```
Comment (TTitcombe) [inline qt/widgets/common/src/InterfaceManager.cpp]: Just to confirm: Your PR test says notice level. Did you intend for this to be information?

Comment (hsautessella) [reply qt/widgets/common/src/InterfaceManager.cpp]: Sorry, the PR is wrong, it's meant to be information as suggested by Nick in the issue. I'll update the PR

**Review by TTitcombe — APPROVED** [review]
Works as intended during testing :+1: I only see the offlineHelpMessage once
