### PR TITLE
Fix bad background colour in Matrix View.

### LINKED ISSUE #21821: Fix Monitor Background Colour in the MantidPlot Matrix View
PR  #21668 causes the MatrixView to shade the cells containing monitor data with a black colour, the same colour as the text within them. The data table view should be modified to shade the cells with a lighter colour whilst keeping the tooltips visible.

## Platforms
Linux only.

### PR DESCRIPTION
**Pull request by edwardb96**
Fixes #21821 
Uses a hard-coded colour value instead of the tooltip colour for the background of the monitor rows in the matrix data view.

**To test:**
Ensure that the monitor cells in the Matrix Data View are readable on both Linux and Windows.

Fixes #21821 . 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by Mantid-Matthew** [comment]
This works fine on linux just building on windows

**Review by josephframsay — APPROVED** [review]
Monitors look good on Windows

File: MantidPlot/src/Mantid/MantidMatrixModel.cpp [hunk 1]
```diff
@@ -44,8 +44,7 @@ void MantidMatrixModel::setup(const Mantid::API::MatrixWorkspace *ws, int rows,
   m_colNumCorr = 1;
   m_endRow = m_rows - 1;
   m_startRow = start >= 0 ? start : 0;
-  m_mon_color =
-      QApplication::palette().color(QPalette::Active, QPalette::ToolTipBase);
+  m_mon_color = QColor(255, 253, 209);
```
Comment (AndreiSavici) [inline MantidPlot/src/Mantid/MantidMatrixModel.cpp]: Can't we do better than hardcoded numbers?

Comment (edwardb96) [reply MantidPlot/src/Mantid/MantidMatrixModel.cpp]: I don't think there's a simple way to pass the original colour from [here](https://github.com/mantidproject/mantid/blob/master/MantidPlot/src/ApplicationWindow.cpp#L11561-L11585) to where we are now.

Comment (AndreiSavici) [reply MantidPlot/src/Mantid/MantidMatrixModel.cpp]: I would get the color of whatever is the background and change the color of the text in the cell to have ```
text_hue=(bg_hue+180)%360;
text_saturation=(bg_saturation+128)%256;
text_value=(bg_value+128)%256;
```
This idea is from https://doc.qt.io/archives/qq/qq26-adaptivecoloring.html
