### PR TITLE
Fix Center argument for SetSample 

### LINKED ISSUE #16890: SetSample interprets Centre argument incorrectly
Found while reviewing the code for [SetSample](https://github.com/mantidproject/mantid/blob/d473e4adbb6bcfecc4b04a2cd876ebe8aa4fd208/Framework/DataHandling/src/SetSample.cpp#L343).

The cylinder XML wants the position of the base but the conversion above is doing something strange. It is the same for the [annulus](https://github.com/mantidproject/mantid/blob/d473e4adbb6bcfecc4b04a2cd876ebe8aa4fd208/Framework/DataHandling/src/SetSample.cpp#L386).

### PR DESCRIPTION
**Pull request by martyngigg**
These fixes properly place the centre of cylinder and annulus at the user-requested location. The XML requires the centre of the bottom base and the translation was done incorrectly previously.

**To test:**

Best done by code review as you can't really see the shapes easily.

Fixes #16890 

[RELEASE NOTES](https://github.com/mantidproject/mantid/commit/108894065445c04d4a0f28fd54299d7235dbb0cb)

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AntonPiccardoSelg** [comment]
* Performed code review: Looks fine to me.
* The unit tests reflect the change of the centre position. Hence this change operates as expected and is sufficiently tested. 

Happy to :shipit:

File: Framework/DataHandling/src/SetSample.cpp [hunk 1]
```diff
@@ -323,87 +371,42 @@ SetSample::createFlatPlateXML(const Kernel::PropertyManager &args) const {
...
   double height = args.getProperty("Height");
-  double innerRadius = args.getProperty("InnerRadius");
-  double outerRadius = args.getProperty("OuterRadius");
-  std::vector<double> center = args.getProperty("Center");
-  // Expected to be a long so that the mapping from Python is simple
+  double innerRadius = hollow ? args.getProperty("InnerRadius") : 0.0;
+  double outerRadius =
+      hollow ? args.getProperty("OuterRadius") : args.getProperty("Radius");
+  std::vector<double> centre = args.getProperty("Center");
   long axisIdx = getAxisIndex(args);
```
Comment (quantumsteve) [inline Framework/DataHandling/src/SetSample.cpp]: Is `long` the best type for an axis index that can only be 0,1 or 2? How disruptive would a change to `uint8_t`, `uint32_t` or an enum class be?

Comment (martyngigg) [inline Framework/DataHandling/src/SetSample.cpp]: @quantumsteve No it's not ideal. It's a `long` because the mapping from Python creates a `long` from a Python integer and this avoids then having to do much work checking and converting things. I see the problem as the inflexibility of the `PropertyWithValue` classes really.
