### PR TITLE
Take intersection of context menu options when selecting multiple workspaces

### LINKED ISSUE #40401: Error when plotting multiple workspaces and one of them is unsupported (TableWorkspace)
**Original reporter:** ISIS Emma Perry

**Describe the bug**
Select multiple workspaces (one of them is a TableWorkspace and the others are data you would normally plot).
Right click and click `plot->superplot`

```
Traceback (most recent call last):
  File "C:\MantidInstall\bin\Lib\site-packages\workbench\plugins\workspacewidget.py", line 123, in _do_superplot
    superplot_from_names(names, plot_kwargs=None)
  File "C:\MantidInstall\bin\Lib\site-packages\mantidqt\plotting\functions.py", line 112, in superplot_from_names
    plot(names, plot_kwargs=plot_kwargs, wksp_indices=[], superplot=True)
  File "C:\MantidInstall\bin\Lib\site-packages\mantid\plots\plotfunctions.py", line 50, in inner_func
    return func(workspaces, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\MantidInstall\bin\Lib\site-packages\mantid\plots\plotfunctions.py", line 154, in plot
    _validate_plot_inputs(workspaces, spectrum_nums, wksp_indices, tiled, overplot)
  File "C:\MantidInstall\bin\Lib\site-packages\mantid\plots\plotfunctions.py", line 459, in _validate_plot_inputs
    raise_if_not_sequence(workspaces, "workspaces", MatrixWorkspace)
  File "C:\MantidInstall\bin\Lib\site-packages\mantid\plots\plotfunctions.py", line 327, in raise_if_not_sequence
    list(map(raise_if_not_type, value))
  File "C:\MantidInstall\bin\Lib\site-packages\mantid\plots\plotfunctions.py", line 323, in raise_if_not_type
    raise ValueError(f"{x} has unexpected type: '{x.__class__.__name__}'")
ValueError: iris108139_graphite002_iqt_Iqt_seq_1S_0_Parameters has unexpected type: 'TableWorkspace'
```

Can run through this example workflow to get similar workspaces as the user
https://docs.mantidproject.org/nightly/interfaces/inelastic/Inelastic%20Data%20Processor.html#i-q-t-example-workflow

**Expected behavior**
The plotting options should not be enabled.

**Screenshots**
From the user:

Image

**Platform/Version (please complete the following information):**
 - OS: [e.g. Windows, RHEL 7, Ubuntu, macOS]
 - OS Version:
 - Mantid Version 6.14.0

**Additional context**
https://github.com/ISISNeutronMuon/mantid-isis-support/issues/283

### PR DESCRIPTION
**Pull request by jhaigh0**
### Description of work

Previously, when selecting multiple workspaces and right-clicking, the context menu shown would be for the workspace which the mouse was over. However when selecting an option, all workspace names would be passed to that process. This could lead to problems like the one reported by a user in the original issue.

In this PR the system for generating the context menu is reworked so that only the actions which are available for all selected workspaces are added. This should stop any similar bugs.

Closes #40401

### To test:
Create a few different kinds of workspaces e.g
 - Some normal matrix workspace data
 - A matrix workspace without an instrument (can use `RemoveInstrumentGeometry`)
 - A table workspace
 - An MD workspace
 - A workspace group

Select different combinations of these and check that the options present in the context menu make sense (are the ones which are shared between them individually)
Also select multiple workspaces of the same type and check that everything is displayed normally, plus any other tests you can think of.

---

### Reviewer

**Your comments will be used as part of the gatekeeper process.** Comment clearly on what you have checked and tested during your review. Provide an audit trail for any changes requested.

As per the [review guidelines](http://developer.mantidproject.org/ReviewingAPullRequest.html):

- Is the code of an acceptable quality? ([Code standards](http://developer.mantidproject.org/Standards/)/[GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html))
- Has a thorough functional test been performed? Do the changes handle unexpected input/situations?
- Are appropriately scoped unit and/or system tests provided?
- Do the release notes conform to the [guidelines](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html) and describe the changes appropriately?
- Has the relevant (user and developer) documentation been added/updated?
- If the PR author isn’t in the `mantid-developers` or `mantid-contributors` teams, add a review comment `rerun ci` to authorize/rerun the CI

### Gatekeeper

As per the [gatekeeping guidelines](https://developer.mantidproject.org/Gatekeeping.html):

- Has a thorough first line review been conducted, including functional testing?
- At a high-level, is the code quality sufficient?
- Are the base, milestone and labels correct?

### CODE REVIEW

**Comment by jhaigh0** [comment]
@coderabbitai full review

File: qt/widgets/common/src/WorkspacePresenter/WorkspaceTreeWidgetSimple.cpp [hunk 1]
```diff
@@ -235,64 +229,152 @@ void WorkspaceTreeWidgetSimple::onShowNewInstrumentViewClicked() {
...
+    }
+  }
+
+  std::vector<QAction *> combinedActions = intersectionOfActions(actionVecs);
+  std::vector<QAction *> combinedPlotMenuActions = intersectionOfActions(plotMenuActionVecs);
+  std::vector<QAction *> combined3DPlotMenuActions = intersectionOfActions(plotMenu3DActionVecs);
+
+  const auto it = std::find(combinedActions.cbegin(), combinedActions.cend(), m_showInstrument);
+  if (it != combinedActions.cend()) {
+    const auto showInstrumentViewCheck = [](MatrixWorkspace_const_sptr workspace) {
```
Comment (adriazalvarez) [inline qt/widgets/common/src/WorkspacePresenter/WorkspaceTreeWidgetSimple.cpp]:
```suggestion
    const auto showInstrumentViewCheck = [](const MatrixWorkspace_const_sptr &workspace) {
```

File: qt/widgets/common/src/WorkspacePresenter/WorkspaceTreeWidgetSimple.cpp [hunk 2]
```diff
@@ -235,64 +229,152 @@ void WorkspaceTreeWidgetSimple::onShowNewInstrumentViewClicked() {
...
+      return workspace->getInstrument() && !workspace->getInstrument()->getName().empty() &&
+             workspace->getAxis(1)->isSpectra();
+    };
+    const bool enabled =
+        std::all_of(workspaces.cbegin(), workspaces.cend(), [&showInstrumentViewCheck](Workspace_sptr ws) {
```
Comment (adriazalvarez) [inline qt/widgets/common/src/WorkspacePresenter/WorkspaceTreeWidgetSimple.cpp]:
```suggestion
        std::all_of(workspaces.cbegin(), workspaces.cend(), [&showInstrumentViewCheck](const Workspace_sptr &ws) {
```

File: qt/widgets/common/src/WorkspacePresenter/WorkspaceTreeWidgetSimple.cpp [hunk 3]
```diff
@@ -235,64 +229,152 @@ void WorkspaceTreeWidgetSimple::onShowNewInstrumentViewClicked() {
...
+          if (auto matrixWS = std::dynamic_pointer_cast<MatrixWorkspace>(ws)) {
```
Comment (adriazalvarez) [inline qt/widgets/common/src/WorkspacePresenter/WorkspaceTreeWidgetSimple.cpp]:
```suggestion
          if (const auto matrixWS = std::dynamic_pointer_cast<MatrixWorkspace>(ws)) {
```

File: qt/widgets/common/src/WorkspacePresenter/WorkspaceTreeWidgetSimple.cpp [hunk 4]
```diff
@@ -362,34 +447,31 @@ void WorkspaceTreeWidgetSimple::addGeneralWorkspaceActions(QMenu *menu) const {
...
-    plotSubMenu->addAction(m_plotSpectrum);
-    plotSubMenu->addAction(m_overplotSpectrum);
-    plotSubMenu->addAction(m_plotSpectrumWithErrs);
-    plotSubMenu->addAction(m_overplotSpectrumWithErrs);
-    plotSubMenu->addAction(m_plotAdvanced);
-    plotSubMenu->addAction(m_superplot);
-    plotSubMenu->addAction(m_superplotWithErrs);
-    plotSubMenu->addSeparator();
-    plotSubMenu->addAction(m_plotColorfill);
+    plotMenu.plotActions.push_back(m_plotSpectrum);
```
Comment (adriazalvarez) [inline qt/widgets/common/src/WorkspacePresenter/WorkspaceTreeWidgetSimple.cpp]: Could it be better here (and in similar menu creation functions) to create the action vector using an initializer list?
```std::vector<QAction*> plActions = {m_plotSpectrum,...}```

File: qt/widgets/common/src/WorkspacePresenter/WorkspaceTreeWidgetSimple.cpp [hunk 5]
```diff
@@ -235,64 +229,152 @@ void WorkspaceTreeWidgetSimple::onShowNewInstrumentViewClicked() {
...
 
   // Add for all types
   addGeneralWorkspaceActions(menu);
 
   return menu;
 }
 
-void WorkspaceTreeWidgetSimple::addMatrixWorkspaceActions(QMenu *menu, const Mantid::API::MatrixWorkspace &workspace) {
+std::vector<QAction *>
+WorkspaceTreeWidgetSimple::intersectionOfActions(std::vector<std::vector<QAction *>> actionVecs) {
```
Comment (adriazalvarez) [inline qt/widgets/common/src/WorkspacePresenter/WorkspaceTreeWidgetSimple.cpp]: can this be passed by const ref?

File: qt/widgets/common/inc/MantidQtWidgets/Common/WorkspacePresenter/WorkspaceTreeWidgetSimple.h [hunk 6]
```diff
@@ -20,6 +20,12 @@ class Workspace;
 }
 
 namespace MantidQt::MantidWidgets {
+
+struct plotMenuActions {
+  std::vector<QAction *> plotActions = {};
```
Comment (adriazalvarez) [inline qt/widgets/common/inc/MantidQtWidgets/Common/WorkspacePresenter/WorkspaceTreeWidgetSimple.h]: perhaps ``std::vector<QAction *>`` could be made an alias, what you think?

File: qt/widgets/common/src/WorkspacePresenter/WorkspaceTreeWidgetSimple.cpp (hunk 1 above)
Comment (adriazalvarez) [inline qt/widgets/common/src/WorkspacePresenter/WorkspaceTreeWidgetSimple.cpp]: can this lambda just be plug in on L284?

**Review by adriazalvarez — CHANGES_REQUESTED** [review]
Thanks for implementing this. I've been trying with a few different combinations, everything seems to be working well, and the bug is not present. 
I have added some comments in the code, but here are a few general suggestions: 

- Release notes are missing. 
- Since we are in this part of the code, could be add a small paragraph on the context menu docs with the dynamic behaviour of the context menu (**workspacetreewidget.rst**)
- Is it feasable to use cpp implementations of sets (std::sets) or function like std::set_intersection to find the intersections? Perhaps would simplify the code.

File: qt/widgets/common/inc/MantidQtWidgets/Common/WorkspacePresenter/WorkspaceTreeWidgetSimple.h (hunk 6 above)
Comment (jhaigh0) [reply qt/widgets/common/inc/MantidQtWidgets/Common/WorkspacePresenter/WorkspaceTreeWidgetSimple.h]: Yes I think that's a good idea

File: qt/widgets/common/src/WorkspacePresenter/WorkspaceTreeWidgetSimple.cpp (hunk 1 above)
Comment (jhaigh0) [reply qt/widgets/common/src/WorkspacePresenter/WorkspaceTreeWidgetSimple.cpp]: I just did this for readability, it got too confusing when it was all one statement I think.

**Comment by jhaigh0** [comment]
> Is it feasable to use cpp implementations of sets (std::sets) or function like std::set_intersection to find the intersections? Perhaps would simplify the code.

This is what I tried first. The main problem is that we want to preserve the order which the actions are listed in which isn't great for sets and also `std::set_intersection` wanted the vectors to be sorted first. The other is that there can be multiple separators in the list (so you'll lose on if you at them all to a set).
In the end, taking the largest list and filtering it seemed the best solution for this case.

File: qt/widgets/common/src/WorkspacePresenter/WorkspaceTreeWidgetSimple.cpp (hunk 5 above)
Comment (jhaigh0) [reply qt/widgets/common/src/WorkspacePresenter/WorkspaceTreeWidgetSimple.cpp]: Ah I've remembered why this can't be, because it gets sorted.

File: docs/source/release/v6.15.0/Workbench/Bugfixes/40401.rst [hunk 7]
```diff
@@ -0,0 +1 @@
+- Fixed a bug where selecting multiple workspaces and right-clicking would open a context menu appropriate for one, but not necessarily all, of the workspaces. This could lead to errors (such as trying to plot a TableWorkspaces). The context menu should now only contain actions support by all selected workspaces.
```
Comment (adriazalvarez) [inline docs/source/release/v6.15.0/Workbench/Bugfixes/40401.rst]:
```suggestion
- Fixed a bug where selecting multiple workspaces and right-clicking would open a context menu appropriate for one, but not necessarily all, of the workspaces. This could lead to errors (such as trying to plot a TableWorkspaces). The context menu now only displays actions that are compatible to all selected workspaces.
```

**Review by adriazalvarez — CHANGES_REQUESTED** [review]

**Review by adriazalvarez — APPROVED** [review]
Thanks for the changes
