### PR TITLE
Disable ConvFit plot guess checkbox if no resolution file loaded

### LINKED ISSUE #28990: ConvFit Plot Guess crash
**Original reporter:** Mona Sarter

### Expected behavior
Ticking Plot Guess should be disabled if a resolution file hasn't been loaded yet.
### Actual behavior
If a sample has been loaded, but a resolution hasn't then ticking Plot Guess hard crashes Mantid
### Steps to reproduce the behavior
Open Workbench, Indirect Data Analysis interface
Go to the ConvFit tab
Load a sample file from #26631
Tick Plot Guess below the plot.
HARD CRASH
### Platforms affected
All Workbench

### PR DESCRIPTION
**Pull request by StephenSmith25**
**Description of work.**
This PR disables the plot guess checkbox within the ConvFit tab if no resolution file has been loaded. This prevents a hard crash.

**To test:**
- Data to test the GUI is in #26631.
- Open the IDA GUI
- Go to the ConvFit tab
- Load Data
- Plot guess should be disabled
- Load resolution file
- Plot guess should be enabled

Fixes #28990  

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/scientific_interfaces/Indirect/IndirectFitPlotModel.cpp [hunk 1]
```diff
@@ -276,8 +277,21 @@ bool IndirectFitPlotModel::canCalculateGuess() const {
...
+  return getWorkspace() && !isEmptyModel && resolutionLoaded;
+}
+
+bool IndirectFitPlotModel::isResolutionLoaded() const {
+  const auto model = dynamic_cast<ConvFitModel *>(m_fittingModel);
+  if (model) {
+    if (m_fittingModel->getResolutionsForFit().size() != 0) {
+      return true;
+    } else {
+      return false;
```
Comment (ConorMFinn) [inline qt/scientific_interfaces/Indirect/IndirectFitPlotModel.cpp:291]: This looks like it could just be:
```suggestion
    return m_fittingModel->getResolutionsForFit().size() != 0;
```

File: qt/scientific_interfaces/Indirect/IndirectFitPlotModel.cpp [hunk 2]
```diff
@@ -276,8 +277,21 @@ bool IndirectFitPlotModel::canCalculateGuess() const {
...
+    }
+  }
+  return true;
```
Comment (ConorMFinn) [inline qt/scientific_interfaces/Indirect/IndirectFitPlotModel.cpp:294]: Is the resolution guarenteed to be loaded if there is no model?

**Review by cailafinn — CHANGES_REQUESTED** [review]
Just a couple of code comments, mostly on style. 

May be part of a different issue, but I noticed while testing that loading an inappropriate file causes mantid to hard crash. For example, I loaded `/ExternalData/Testing/Data/UnitTest/TSC14007_graphite002_red.nxs` as a sample and mantid crashed.

File: qt/scientific_interfaces/Indirect/IndirectFitPlotModel.cpp (hunk 1 above)
Comment (StephenSmith25) [reply qt/scientific_interfaces/Indirect/IndirectFitPlotModel.cpp:291]: Yep good point, thanks!

File: qt/scientific_interfaces/Indirect/IndirectFitPlotModel.cpp (hunk 2 above)
Comment (StephenSmith25) [reply qt/scientific_interfaces/Indirect/IndirectFitPlotModel.cpp:294]: > 
> 
> Is the resolution guarenteed to be loaded if there is no model?


So if the cast fails it means its a different fit model (used by the other tabs), which don't require a resolution file. Granted this is a bit ambiguous, but it needs to return true for the sake of the comparisons its makes above. But currently can’t think of a better function name.

Comment (ConorMFinn) [reply qt/scientific_interfaces/Indirect/IndirectFitPlotModel.cpp:294]: That makes sense, thanks. Could you add a comment before L294 clarifying why it returns true? Without some context it looks a little counterintuitive.

**Comment by StephenSmith25** [comment]
> 
> 
> Just a couple of code comments, mostly on style.
> 
> May be part of a different issue, but I noticed while testing that loading an inappropriate file causes mantid to hard crash. For example, I loaded `/ExternalData/Testing/Data/UnitTest/TSC14007_graphite002_red.nxs` as a sample and mantid crashed.

I think this sounds like a different issue and related to that particular file, which I’m guessing must be missing some required information. I can look into that in a separate issue as it should just be rejecting unsuitable files.

**Comment by SpencerHowells** [comment]
@StephenSmith25 @ConorMFinn The offending file has a run number TSC14007. Is TSC short for instrument TOSCA? if so it is not a QENS instrument so should not be using ConvFit.

**Comment by SpencerHowells** [comment]
@StephenSmith25 @ConorMFinn I’ve checked & it is indeed TOSCA so needs an issue to solve. I use info in the instrument definitions in Facilities.xml to test for appropriate instruments. We could add the technique Quasielastic to IRIS & OSIRIS & test for that. It could be useful in many other places.

**Review by cailafinn — APPROVED** [review]
Changes for this PR work well. Plot guess crash now avoided. Code looks good. Nice work 👍
