### PR TITLE
Load other facilities.xml if one fails

### LINKED ISSUE #26830: Mantid fails without warning if Facilities.xml is corrupt
### Expected behavior
Mantid should show a warning if it cannot start because Facilities.xml is not parsable.

### Actual behavior
Mantid silently closes without any indication of what the problem was. You don't even see the splash screen.

### Steps to reproduce the behavior
On Windows:
- Edit `$APPDATA$/Roaming/mantidproject/mantid/instrument/Facilities.xml` and add some random text at the top
- Open an installed MantidPlot or Workbench using the shortcut on the desktop.
- Mantid silently closes with no indication of what went wrong.
- If you run `C:\MantidInstall\bin\launch_mantidplot.bat` from a terminal instead you see the error: 
` RuntimeError: Unable to parse file: in "$APPDATA$\Roaming\mantidproject\mantid\instrument\Facilities.xml"`

### Platforms affected
I noticed this on Windows 10 where my Facilities.xml had somehow become corrupt

### PR DESCRIPTION
**Pull request by NickDraper**
read the first commit descriiton

On Windows:

1. Edit your user.properties file to include ``` UpdateInstrumentDefinitions.OnStartup = 1```
1. Edit $APPDATA$/Roaming/mantidproject/mantid/instrument/Facilities.xml and add some random text at the top

Before the fix
1. Open an installed MantidPlot or Workbench using the shortcut on the desktop.
1. Mantid silently closes with no indication of what went wrong.
1. if you run C:\MantidInstall\bin\launch_mantidplot.bat from a terminal instead you see the error:
```
RuntimeError: Unable to parse file: in "$APPDATA$\Roaming\mantidproject\mantid\instrument\Facilities.xml"
```

After
1. Start mantdplot wor workbench, that start up fine, you might see helpful log messages (on the command line, not the messages window).
1. Mantid will immediately start downloading and replacing the corrupted file.

Take the line out of your user.properties file

Fixes #26830

in the framework.rst release notes

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Kernel/src/ConfigService.cpp [hunk 1]
```diff
@@ -1802,37 +1810,59 @@ void ConfigServiceImpl::updateFacilities(const std::string &fName) {
...
+      g_log.error() << "Failed to load the facilities.xml file at " << fileName
+                    << "\nIt might be corrupt.  " << ex.what()
+                    << "\nWill try to load another version.\n";
+      attemptIndex++;
+      // move on to the next file index if available
+      if (attemptIndex == fileNames.size()) {
+        // Throw an exception as we have run out of files to try
+        throw std::runtime_error(
+            "No more Facilities.xml files can be found, Mantid will not be "
+            "able to start, Sorry.  Try reinstalling Mantid.");
```
Comment (ConorMFinn) [inline Framework/Kernel/src/ConfigService.cpp]: Since this error seems to be swallowed by the error reporter, it may be worth explicitly sending this message to the log.

**Review by cailafinn — CHANGES_REQUESTED** [review]
A couple of things about code comments and about the last message not being included if all of the files are corrupted/don't work.

**Review by cailafinn — DISMISSED** [review]
Code looks good and gives much more useful output. Approved.

File: Framework/Kernel/src/ConfigService.cpp [hunk 2]
```diff
@@ -1802,37 +1810,64 @@ void ConfigServiceImpl::updateFacilities(const std::string &fName) {
 
   // Try to find the file. If it does not exist we will crash, and cannot read
   // the Facilities file
-  std::string fileName = getFacilityFilename(fName);
+  const auto fileNames = getFacilityFilenames(fName);
+  size_t attemptIndex = 0;
+  bool success = false;
+  while ((!success) && (attemptIndex < fileNames.size())) {
+    std::string fileName = fileNames[attemptIndex];
```
Comment (martyngigg) [inline Framework/Kernel/src/ConfigService.cpp]:
```suggestion
    const auto& fileName = fileNames[attemptIndex];
```

File: Framework/Kernel/src/ConfigService.cpp [hunk 3]
```diff
@@ -1802,37 +1810,64 @@ void ConfigServiceImpl::updateFacilities(const std::string &fName) {
...
+      }
 
-  // Get pointer to root element
-  Poco::XML::Element *pRootElem = pDoc->documentElement();
-  if (!pRootElem->hasChildNodes()) {
-    throw std::runtime_error("No root element in Facilities.xml file");
-  }
+      Poco::AutoPtr<Poco::XML::NodeList> pNL_facility =
+          pRootElem->getElementsByTagName("facility");
+      size_t n = pNL_facility->length();
```
Comment (martyngigg) [inline Framework/Kernel/src/ConfigService.cpp]:
```suggestion
      const size_t n = pNL_facility->length();
```

File: Framework/Kernel/src/ConfigService.cpp [hunk 4]
```diff
@@ -1802,37 +1810,64 @@ void ConfigServiceImpl::updateFacilities(const std::string &fName) {
...
+      if (!pRootElem->hasChildNodes()) {
+        throw std::runtime_error("No root element in Facilities.xml file");
+      }
 
-  // Get pointer to root element
-  Poco::XML::Element *pRootElem = pDoc->documentElement();
-  if (!pRootElem->hasChildNodes()) {
-    throw std::runtime_error("No root element in Facilities.xml file");
-  }
+      Poco::AutoPtr<Poco::XML::NodeList> pNL_facility =
```
Comment (martyngigg) [inline Framework/Kernel/src/ConfigService.cpp]:
```suggestion
      const Poco::AutoPtr<Poco::XML::NodeList> pNL_facility =
```

File: Framework/Kernel/src/ConfigService.cpp [hunk 5]
```diff
@@ -1802,37 +1810,64 @@ void ConfigServiceImpl::updateFacilities(const std::string &fName) {
...
+          pRootElem->getElementsByTagName("facility");
+      size_t n = pNL_facility->length();
 
-  Poco::AutoPtr<Poco::XML::NodeList> pNL_facility =
-      pRootElem->getElementsByTagName("facility");
-  size_t n = pNL_facility->length();
+      for (unsigned long i = 0; i < n; ++i) {
+        auto *elem = dynamic_cast<Poco::XML::Element *>(pNL_facility->item(i));
```
Comment (martyngigg) [inline Framework/Kernel/src/ConfigService.cpp]:
```suggestion
        const auto *elem = dynamic_cast<Poco::XML::Element *>(pNL_facility->item(i));
```

File: Framework/Kernel/src/ConfigService.cpp [hunk 6]
```diff
@@ -1802,37 +1810,64 @@ void ConfigServiceImpl::updateFacilities(const std::string &fName) {
...
+        if (elem) {
+          m_facilities.push_back(new FacilityInfo(elem));
```
Comment (martyngigg) [inline Framework/Kernel/src/ConfigService.cpp]:
```suggestion
          m_facilities.emplace_back(new FacilityInfo(elem));
```

**Review by martyngigg — CHANGES_REQUESTED** [review]
While we are changing this code, that we are unlikely to touch again for a while can we modernize things a bit? `emplace_back` over `push_back` with temporaries and `const` where we can to encourage its use elsewhere.

**Review by martyngigg — APPROVED** [review]
This looks good to me now.
