### PR TITLE
Fix for diffraction focussing crash when run on a group workspace from an algorithm dialogue 

### LINKED ISSUE #39680: Mantid workbench crashes when DiffractionFocussing is run on a group workspace
**Original reporter:** [gabriel.perez@stfc.ac.uk](mailto:gabriel.perez@stfc.ac.uk)

**Describe the bug**
When trying to apply the algorithm "DiffractionFocussing" to a group of four Workspaces, Mantid crashed. It's worth noting that each individual workspace contained 3007 spectra.

**To Reproduce**

1. Click Load->File and Browse for 4 files. ex: POLARIS00098531.nxs-POLARIS00098534.nxs
2. Run `DiffractionFocussing` algorithm on the group workspace loaded from the above
3. Give a name for `OutputWorkspace` and click `Run`

**Expected behavior**
No crashes

**Platform/Version (please complete the following information):**
 - OS: [Windows 11 Enterprise]
 - OS Version:
 - Mantid Version [6.13.0, 6.12.0]

### PR DESCRIPTION
**Pull request by jhaigh0**
### Description of work

The `validateInputs` method of `DiffractionFocussing2` did not consider that `InputWorkspace` could be a workspace group.
In general this is quite confusing because the input workspace property is of the type `MatrixWorkspace`.
Mantid has an exception in the workspace property to allow a group to be passed to such a property. When running the algorithm from python (or C++) this isn't a problem, `Algorithm`'s `executeInternal` method checks for workspace groups, and if they're found, runs the algorithm on each of the child workspaces from the group.
However, when running from a dialogue, the `AlgorithmDialogue` class makes an early call to `validateInputs` before the algorithm has been executed. At this point `InputWorkspace` will still be a workspace group, which can lead to problems if `validateInputs` doesn't consider this possibility.

I'd like to change `Algorithm` to wrap `validateInputs` similarly to how `execute` works when checking for groups. I'll wirte this up in a separate issue. (https://github.com/mantidproject/mantid/issues/39801)

Closes #39680

### To test:

Follow instructions from the issue, you will get an error if you don't provide `GroupingFileName` or `GroupingWorkspace`, but no crash.

---

### Reviewer

**Your comments will be used as part of the gatekeeper process.** Comment clearly on what you have checked and tested during your review. Provide an audit trail for any changes requested.

As per the [review guidelines](http://developer.mantidproject.org/ReviewingAPullRequest.html):

- Is the code of an acceptable quality? ([Code standards](http://developer.mantidproject.org/Standards/)/[GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html))
- Has a thorough functional test been performed? Do the changes handle unexpected input/situations?
- Are appropriately scoped unit and/or system tests provided?
- Do the release notes conform to the [guidelines](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html) and describe the changes appropriately?
- Has the relevant (user and developer) documentation been added/updated?

### Gatekeeper

As per the [gatekeeping guidelines](https://developer.mantidproject.org/Gatekeeping.html):

- Has a thorough first line review been conducted, including functional testing?
- At a high-level, is the code quality sufficient?
- Are the base, milestone and labels correct?

### CODE REVIEW

File: Framework/Algorithms/src/DiffractionFocussing2.cpp [hunk 1]
```diff
@@ -90,15 +92,22 @@ std::map<std::string, std::string> DiffractionFocussing2::validateInputs() {
 
   // validate input workspace
   API::MatrixWorkspace_const_sptr inputWS = getProperty("InputWorkspace");
```
Comment (cailafinn) [inline Framework/Algorithms/src/DiffractionFocussing2.cpp:94]: Could this be simplified by making this an assignment to `API::Workspace_const_sptr`, using the `isGroup()` in the if statements, then dynamically casting `inputWS` to either a `MatrixWorkspace` or  `WorkspaceGroup`? I think that way would avoid recasting the properties.

File: Framework/Algorithms/src/DiffractionFocussing2.cpp [hunk 2]
```diff
@@ -156,6 +165,20 @@ std::map<std::string, std::string> DiffractionFocussing2::validateInputs() {
   return issues;
 }
 
+void DiffractionFocussing2::validateInputWorkspaceUnit(API::MatrixWorkspace_const_sptr inputWS,
+                                                       std::map<std::string, std::string> &issues) {
+  // Validate UnitID (spacing)
+  const std::string unitid = inputWS->getAxis(0)->unit()->unitID();
+  if (unitid == "TOF") {
+    g_log.error(
+        "Support for TOF data in DiffractionFocussing is deprecated (on 29/04/21) - use GroupDetectors instead)");
```
Comment (cailafinn) [inline Framework/Algorithms/src/DiffractionFocussing2.cpp]: Is this a "working" deprecation or will it break the processing?

**Review by cailafinn — CHANGES_REQUESTED** [review]
Just a couple of questions on the code changes. 

Functionally tested and all working well. Crash no longer occurs when validating a workspace group.

File: Framework/Algorithms/src/DiffractionFocussing2.cpp (hunk 1 above)
Comment (jhaigh0) [reply Framework/Algorithms/src/DiffractionFocussing2.cpp:94]: That is a good idea, I'll give it a try.

File: Framework/Algorithms/src/DiffractionFocussing2.cpp (hunk 2 above)
Comment (jhaigh0) [reply Framework/Algorithms/src/DiffractionFocussing2.cpp]: I'm not sure myself, but we can ask @RichardWaiteSTFC since he added the warning (https://github.com/mantidproject/mantid/commit/8e08c9a0abf91acf15e8e6021da238b0978b9f42)

Comment (RichardWaiteSTFC) [reply Framework/Algorithms/src/DiffractionFocussing2.cpp]: It works but it is not advised because a Bragg peak at a given d-spacing will be observed at different TOF in each detector. The correct way to do it would be to convert the data to d-spacing, focus then convert to TOF. Also there are other algorithms that can sum data in TOF (where bin edges are the same in each detector - e.g. `SumSpectra`)

Comment (RichardWaiteSTFC) [reply Framework/Algorithms/src/DiffractionFocussing2.cpp]: I would also like to be able to focus data in wavelength (for vanadium purposes) - but maybe a separate PR/issue!

Comment (cailafinn) [reply Framework/Algorithms/src/DiffractionFocussing2.cpp]: Given that it would produce bad output, would it make sense to have this add to the `issues` map and stop the alg running, rather than just printing an error to the log?

Comment (RichardWaiteSTFC) [reply Framework/Algorithms/src/DiffractionFocussing2.cpp]: I guess putting it in the input validation stops you doing it - but I think after enough warning was given that was the plan. Because it has been possible for so long, it was thought possible (likely?) someone somewhere was using it!

Comment (RichardWaiteSTFC) [reply Framework/Algorithms/src/DiffractionFocussing2.cpp]: It has probably been enough time now!

File: Framework/Algorithms/src/DiffractionFocussing2.cpp (hunk 1 above)
Comment (jhaigh0) [reply Framework/Algorithms/src/DiffractionFocussing2.cpp:94]: Unfortunately this doesn't work because when you get a typed property it tries to cast the property to the type you're assign the value to. So in this case the `IntputWorkspace` property is a `PropertyWithValue<MatrixWorkspace_sptr>` and then you do `API::Workspace_sptr inputWS = getProperty("InputWorkspace");` it attempts to cast the property to a `PropertyWithValue<Workspace_sptr>` which fails and raises an exception. [Here](https://github.com/mantidproject/mantid/blob/main/Framework/API/src/Workspace.cpp#L96)
This is why you have to do this awkward sequence when getting the group workspace out of the property (you can't just go `API:WorkspaceGroup_sptr groupWS = getProperty("IntputWorkspace")`)

File: Framework/Algorithms/src/DiffractionFocussing2.cpp (hunk 2 above)
Comment (jhaigh0) [reply Framework/Algorithms/src/DiffractionFocussing2.cpp]: Would you like me to do it in this PR or is this something for a separate PR

Comment (cailafinn) [reply Framework/Algorithms/src/DiffractionFocussing2.cpp]: This PR is probably the most sensible IMO. We're already changing that code a bit

**Review by cailafinn — DISMISSED** [review]
This looks good to me now. Thanks for investigating that change.

**Review by SilkeSchomann — APPROVED** [review]
I've tested the functionality again after the latest changes and it still work as expected, so happy to approve again.
