### PR TITLE
Indirect IqtFit - Prevent a crash with Plot Current Preview

### LINKED ISSUE #24611: Indirect IqtFit Plot Current Preview crash
**Original reporter:** @SamJenkins1 

### Expected behavior
There should be no crash

### Actual behavior
Clicking `Plot Current Preview` resulted in a crash

### Steps to reproduce the behavior
1.`Interfaces`->`Indirect`->`Data Analysis`->`IqtFit` interface
2. Load the data below
3. Set the number of exponentials to 2.
4. Slide the the EndX slider slightly to the left
5. Click Run and wait
6. Delete all of the output workspaces (not the input one)
7. Click `Plot Current Preview`, crash!

**Data Files**
[irs26176_graphite002_iqt.zip](https://github.com/mantidproject/mantid/files/2802302/irs26176_graphite002_iqt.zip)

### Platforms affected
All

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR prevents a crash in Indirect Data Analysis IqtFit interface when clicking Plot Current Preview after deleting the result data of a fit.

**To test:**
1.`Interfaces`->`Indirect`->`Data Analysis`->`IqtFit` interface
2. Load the data below
3. Set the number of exponentials to 2.
4. Select a `Flat Background`
4. Slide the the EndX slider slightly to the left
5. Click Run and wait
6. Delete all of the output workspaces (not the input one)
7. Click `Plot Current Preview`, there should be no crash - just a plot of the input data.

**Data Files**
[irs26176_graphite002_iqt.zip](https://github.com/mantidproject/mantid/files/2802302/irs26176_graphite002_iqt.zip)

Fixes #24611 

I think no release notes are required as the users do not know about this bug.

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by TTitcombe — DISMISSED** [review]
Code changes small but clean and readable
Works as expected in testing (no crash :+1: )
No need for documentation update

File: qt/scientific_interfaces/Indirect/IndirectSqw.cpp [hunk 1]
```diff
@@ -17,6 +17,10 @@ using MantidQt::API::BatchAlgorithmRunner;
 
 namespace {
 
+bool doesExistInADS(std::string const &workspaceName) {
```
Comment (gvardany) [inline qt/scientific_interfaces/Indirect/IndirectSqw.cpp]: I don't see the point in creating a one-line wrapper around a one-line call.

**Review by gvardany — CHANGES_REQUESTED** [review]
Just a small comment.

File: qt/scientific_interfaces/Indirect/IndirectSqw.cpp (hunk 1 above)
Comment (robertapplin) [reply qt/scientific_interfaces/Indirect/IndirectSqw.cpp]: The only reason is I find it to be more readable. However I am happy to change this if you'd like?

**Comment by robertapplin** [comment]
@gvardany this should be ready to go now 👍

**Review by gvardany — APPROVED** [review]
