### PR TITLE
StartX and EndX columns in Data Analysis tabs are automatically formatted to a precision of six digits

### LINKED ISSUE #35714: StartX and EndX columns should be automatically formatted to a precision of six digits
In the indirect data analysis GUI StartX and EndX columns the user can enter letters or numbers with more than six digits of precision. User input should be limited to numbers and any numerical values should be automatically formatted to a precision of six digits.

**To Reproduce**
1- Go to Interfaces > Indirect > Data Analysis
2- Go to the Conv Fit tab
3- Click Add Workspace
4- With the combo boxes set to File
5- Click browse and load the irs26176_graphite002_red.nxs file from the sample data
6- Click browse and load the resolution file irs26173_graphite002_res.nxs from the sample data
7- Click Add and close the dialogue.
8- Try to enter a letter or a number with a precision of 6 in the StartX and EndX columns

**Expected behavior**

User input should be limited to numbers and any numerical values should be automatically formatted to a precision of six digits

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: Windows
 - OS Version: 10 Professional 
 - Mantid Version 6.7.0

### PR DESCRIPTION
**Pull request by adriazalvarez**
### Description of work
As described in #35714, currently when any data is input in columns StartX and EndX of any of the data analysis tabs, the cell does not validate whether the data is correct. For example, you could input a special character ($£"$), it will be internally converted to 0 but not updated in the cell. This PR fixes that behaviour. 
Currently, there is no function in the data analysis view that can edit or change individual cells, it is all updated at once. In this PR I have added a function to just update individually the data in a single numeric cell. 
Also, if the input value format is wrong, the cell is automatically converted to the last valid value of Start/EndX stored by the model. 
Finally, both columns are reformatted with a numeric precision of 6 digits.  

#### Summary of work

Fixes #35714 . 

### To test:
1- Go to Interfaces > Indirect > Data Analysis
2- Go to the Conv Fit tab
3- Click Add Workspace
4- With the combo boxes set to File
5- Click browse and load the irs26176_graphite002_red.nxs file from the sample data
6- Click browse and load the resolution file irs26173_graphite002_res.nxs from the sample data
7- Click Add and close the dialogue.
8- Try to enter any keyboard character in the StartX and EndX columns. It should be formatted to a valid (within fitting range)number with a precision of 6.

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by robertapplin — CHANGES_REQUESTED** [review]
Code changes look neat and it fixes the problem - the numbers are to 6 dp

May I suggest that we use one of the in-built Qt classes to handle the validation for us? For example there is this useful `QRegExpValidator` class we can use to prevent unexpected characters being entered into the table cells. This will offload a lot of responsibility re validation from our code.

We might need to create and set an `ItemDelegate` for the relevent columns, a bit like what is done here https://github.com/mantidproject/mantid/blob/294cf71bb3c4840846cefb59a3e51b5264781000/qt/widgets/common/src/FitScriptGeneratorDataTable.cpp#L104
but with our own ItemDelegate class which inherits from `QStyledItemDelegate`.

I think we could override the `createEditor` method of the `QStyledItemDelegate` class and implement a QLineEdit where we set a QRegExpValidator validator. Sorry if that was explained poorly, let me know if you need any clarification

**Comment by adriazalvarez** [comment]
The latest commit reflects the changes suggested. Adding an item delegate class to validate the input.

File: qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataView.cpp [hunk 1]
```diff
@@ -49,7 +53,26 @@ class ExcludeRegionDelegate : public QItemDelegate {
...
+  QWidget *createEditor(QWidget *parent, const QStyleOptionViewItem &, const QModelIndex &) const override {
+
+    auto lineEdit = std::make_unique<QLineEdit>(parent);
+    auto validator = std::make_unique<QDoubleValidator>(parent);
+
+    validator->setDecimals(6);
+    validator->setNotation(QDoubleValidator::StandardNotation);
+    lineEdit->setValidator(validator.release());
+
+    return lineEdit.release();
```
Comment (robertapplin) [inline qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataView.cpp:68]: Nice thought to use unique_ptrs - you are right to think it is almost always better to use these instead of raw pointers. The main reason being that with raw pointers you need to remember to free the memory when you go out-of-scope, and with unique_ptrs you don't

Having said this, QObjects are a bit of an exception to this rule, and it is preferable to use raw pointers for them. The reason for this is because QObjects are owned by the QApplication, and so we do not want the lifetime of the QObjects to be managed by anything other than the QApplication itself, or a parent widget. In this case, it is preferable to do something like this:
```suggestion
    auto lineEdit = new QLineEdit(parent);
    auto validator = new QDoubleValidator(parent);

    validator->setDecimals(6);
    validator->setNotation(QDoubleValidator::StandardNotation);
    lineEdit->setValidator(validator);

    return lineEdit;
```

File: qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataView.cpp [hunk 2]
```diff
@@ -23,6 +25,8 @@ const QString REAL_RANGE = "(" + REAL_NUMBER + COMMA + REAL_NUMBER + ")";
 const QString MASK_LIST = "(" + REAL_RANGE + "(" + COMMA + REAL_RANGE + ")*" + ")|" + EMPTY;
 } // namespace Regexes
 
+QString makeNumber(double d) { return QString::number(d, 'f', 6); }
```
Comment (robertapplin) [inline qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataView.cpp:28]: Can you create a constant variable at the top of the file for `6` as it is used in two places that I can see in this file?

File: qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataView.cpp [hunk 3]
```diff
@@ -88,8 +111,14 @@ void IndirectFitDataView::setHorizontalHeaders(const QStringList &headers) {
 
   auto header = m_uiForm->tbFitData->horizontalHeader();
   header->setSectionResizeMode(0, QHeaderView::Stretch);
+
+  m_uiForm->tbFitData->setItemDelegateForColumn(headers.indexOf("StartX"),
+                                                std::make_unique<NumericInputDelegate>().release());
+  m_uiForm->tbFitData->setItemDelegateForColumn(headers.indexOf("EndX"),
+                                                std::make_unique<NumericInputDelegate>().release());
```
Comment (robertapplin) [inline qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataView.cpp:118]: I think we can use the `startXColumn()` and `endXColumn()` methods to get the index of the "StartX" and "EndX" columns

**Review by robertapplin — COMMENTED** [review]
Thanks for the changes, its looking really good. Just had a few more suggestions before I approve

File: qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataView.cpp (hunk 1 above)
Comment (robertapplin) [reply qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataView.cpp]: Yes that is right, `release` will remove the ownership responsibility of the unique pointer (basically the same as defining a raw pointer in the first place). The lifetime of the widgets is then most likely managed by their parent widget

File: qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataView.cpp [hunk 4]
```diff
@@ -88,8 +113,11 @@ void IndirectFitDataView::setHorizontalHeaders(const QStringList &headers) {
 
   auto header = m_uiForm->tbFitData->horizontalHeader();
   header->setSectionResizeMode(0, QHeaderView::Stretch);
-  m_uiForm->tbFitData->setItemDelegateForColumn(headers.size() - 1,
-                                                std::make_unique<ExcludeRegionDelegate>().release());
+
+  m_uiForm->tbFitData->setItemDelegateForColumn(startXColumn(), std::make_unique<NumericInputDelegate>().release());
+  m_uiForm->tbFitData->setItemDelegateForColumn(endXColumn(), std::make_unique<NumericInputDelegate>().release());
+  m_uiForm->tbFitData->setItemDelegateForColumn(excludeColumn(), std::make_unique<ExcludeRegionDelegate>().release());
```
Comment (robertapplin) [inline qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataView.cpp:119]: Further to the point above, I think it will be more efficient to create a raw pointer rather than a unique pointer, and then releasing the unique pointer

**Review by robertapplin — CHANGES_REQUESTED** [review]
Thanks for the changes, its looking really good. I've noticed that the changes have worked for the MSDFit and IQtFit tabs, but the "EndX" does not work for ConvFit and FQFit. The StartX works for them though! It might be something to do with the ConvFit and FQFit having their own FitDataPresenter's (?)

File: qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataView.cpp (hunk 4 above)
Comment (robertapplin) [reply qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataView.cpp]: Ah, I see what you mean. I think maybe we could refactor the `startXColumn`, `endXColumn` and `excludeColumn` functions. Maybe have a private function that does
```
auto labels = m_uiForm->tbFitData->horizontalHeaderLabels();
return labels.indexOf(columnName);
```
and then each of the `startXColumn`, `endXColumn` and `excludeColumn`  functions would call `return columnIndexOf("StartX")` where we change "StartX" for each of the different column names. Then we could call these functions as before, and remove the overridden functions in the FqFitView and ConvFitView. If that makes sense?

Comment (adriazalvarez) [reply qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataView.cpp]: Thanks for the suggestion. I agree all the startX,etc.. functions can be refactored into one single one. 
The QTableWidget does not have any function to retrieve the horizontal header labels. The way to do it is a bit involved (basically iterating over all column headers). 
Since the headers string list is passed upon construction, I have stored the list as a private data member of the class, and then added a public function to retrieve the index position. 
Let me know what you think.

File: qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataView.h [hunk 5]
```diff
@@ -49,6 +46,7 @@ public slots:
   void setCell(std::unique_ptr<QTableWidgetItem> cell, size_t row, size_t column);
 
 private:
+  QStringList HeaderLabels;
```
Comment (robertapplin) [inline qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataView.h:49]: Sorry to be nitpicky! We tend to prefix member variables with `m_`  https://developer.mantidproject.org/Standards/CPPStandards.html#naming-conventions

For example:
https://github.com/mantidproject/mantid/blob/51c7731b65bae4a20f9baf88dae59cba8518b1f5/qt/widgets/common/inc/MantidQtWidgets/Common/Hint.h#L21

Comment (adriazalvarez) [reply qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataView.h]: No, it's ok. Sorry for giving you extra work. 
I though that m_ prefix applied only to public members. I'll fix it.

**Review by robertapplin — CHANGES_REQUESTED** [review]
Really great work with this - it is far improved to what it used to be. I should have realised earlier, but this also needs a release note!

**Review by robertapplin — APPROVED** [review]
