### PR TITLE
Fix Crash When Running Multiple Reductions in the Preview Tab

### LINKED ISSUE #34865: Refl Preview Crashes When Loading Multiple Times
Hitting load multiple times causes a crash when it goes to check the algorithm validator. 

Since the only way to get this to trigger is from abusing the GUI, I'm just going to disable the widgets while the loading is happening. 

Part of #34745

### PR DESCRIPTION
**Pull request by cailafinn**
**Description of work.**
Add some notifying calls between the job runner and the preview view to disable the tab while the reduction is running, which was causing some race-based segfaults if the load button was spammed. 

The cause of the segfaults appeared to be when two reductions were started very close together. When the second one finished, the other tried to access a validator that the first one had already cleared, so was trying to deref null pointers. 

**To test:**
1. Open the ISIS Reflectometry interface
2. Go to the Preview tab
3. Enter run `INTER45455_inst` and click Load (This data is available on this Epic and must be in your user search path: #31069)
4. Put an angle of 0 and try to click load a bunch. The button should be disabled while processing. The algo should error, but not crash.
5. Now put an angle in and click load a lot again. The line plot should be filled in and it shouldn't crash. 
6. Now draw a square on the inst viewer and move your drawn area as many times as you can in the shortest time to try and force reductions to overlap. The tab should disable itself while the reduction is running and prohibit you from doing this. 

Fixes #34865 

*This does not require release notes* because **this tab isn't user facing yet.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by sf1919** [comment]
Have set the linux & systems test to run separately - https://builds.mantidproject.org/job/pull_requests-conda-linux/2281/

**For any reviewer/gatekeeper:**
The link in the checks list won't pick up on this re-set test so it will stay as pending. Provided the job in the link above passes please review as normal.

File: qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewPresenter.cpp [hunk 1]
```diff
@@ -74,16 +74,17 @@ void PreviewPresenter::notifyAutoreductionPaused() { updateWidgetEnabledState();
...
   }
 }
 
 /** Notification received when the user has requested to load a workspace. If it already exists in the ADS
  * then we use that and continue to plot it; otherwise we start an async load.
  */
 void PreviewPresenter::notifyLoadWorkspaceRequested() {
+  m_view->disableMainWidget();
   auto const name = m_view->getWorkspaceName();
   try {
```
Comment (rbauststfc) [inline qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewPresenter.cpp:89]: If I try to load `POLREF37125` (which is not a matrix workspace and therefore throws an error) the tab stays disabled and I can't attempt to load a different run. I'm not sure if it's anything to do with not re-enabling the view as part of this try/catch, or if the issue is elsewhere.

Similarly, when testing with `INTER45455_inst`, if `ReflectometryISISSumBanks` throws an error then the tab doesn't seem to be re-enabled.

**Review by rbauststfc — CHANGES_REQUESTED** [review]
This does a great job of preventing the crashes and the code changes look good to me 👍

I just noticed a couple of things around re-enabling the tab when there are errors and keeping the Update button disabled when the angle value hasn't changed.

**Review by rbauststfc — DISMISSED** [review]
I've resolved the conflicts and added a few changes to address the things I raised in my first review. I'm going to approve this, but @gemmaguest it would probably be good for you to gatekeeper this one to check the changes I've made.

**Review by gemmaguest — DISMISSED** [review]
I've tested this quite thoroughly and on the whole it is looking really good. 

One problem though - it looks like it has introduced a bug where ROIs can no longer be deleted! Whenever I click to select an ROI (in either the instrument viewer or sliceviewer) the reduction gets re-run, even if I didn't actually change the ROI. I suspect that because of that it is somehow "forgetting" that the ROI is selected ready for editing?

**Comment by ConorMFinn** [comment]
> One problem though - it looks like it has introduced a bug where ROIs can no longer be deleted! Whenever I click to select an ROI (in either the instrument viewer or sliceviewer) the reduction gets re-run, even if I didn't actually change the ROI. I suspect that because of that it is somehow "forgetting" that the ROI is selected ready for editing?

Yep, that's the reason. I actually found this before I went off for Xmas and started looking into fixing it but forgot to re-draft the PR! Sorry!

**Review by rbauststfc — COMMENTED** [review]
The recent code changes have fixed the issue with deleting ROIs. 👍

I'm not sure if I'm testing incorrectly, but it looks to me like a reduction is now only run when the first ROI added to the slice viewer is created and/or moved? Adding extra background or transmission ROIs doesn't look to me like it's triggering a re-run of the reduction any more?

**Comment by ConorMFinn** [comment]
> I'm not sure if I'm testing incorrectly, but it looks to me like a reduction is now only run when the first ROI added to the slice viewer is created and/or moved? Adding extra background or transmission ROIs doesn't look to me like it's triggering a re-run of the reduction any more?

Good catch on this. Turns out there were some logic errors in what I'd written that helped to reveal a few other problems I hadn't noticed before (such as the model starting off with `std::optional`s without a value on initialisation but having a value but empty vectors when all the regions of that type are deleted. I've now added the additional logic to make that comparison work properly.

File: qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewPresenter.cpp [hunk 2]
```diff
@@ -204,7 +217,25 @@ void PreviewPresenter::notifyRegionChanged() {
...
+}
+} // namespace
+
+bool PreviewPresenter::isRegionSelectionChanged() {
+  return isRegionChanged(m_model->getSelectedRegion(ROIType::Signal),
+                         m_regionSelector->getRegion(roiTypeToString(ROIType::Signal))) ||
+         isRegionChanged(m_model->getSelectedRegion(ROIType::Background),
+                         m_regionSelector->getRegion(roiTypeToString(ROIType::Background))) ||
+         isRegionChanged(m_model->getSelectedRegion(ROIType::Transmission),
+                         m_regionSelector->getRegion(roiTypeToString(ROIType::Transmission)));
```
Comment (rbauststfc) [inline qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewPresenter.cpp:238]: Just a suggestion on style in case you agree - I was wondering if the below alternative might help cut down some of the duplication in `PreviewPresenter::isRegionSelectionChanged`, although at the expense of a bit more boilerplate (I haven't checked the below, so apologies if it doesn't work!):

```
bool PreviewPresenter::isRegionSelectionChanged() {
  return isRegionChanged(ROIType::Signal) ||
         isRegionChanged(ROIType::Background) ||
         isRegionChanged(ROIType::Transmission);
}

bool PreviewPresenter::isRegionChanged(ROIType roiType) {
  auto oldValue = m_model->getSelectedRegion(roiType);
  auto newValue = m_regionSelector->getRegion(roiTypeToString(roiType));
  return !(!oldValue.has_value() && newValue.empty()) && oldValue != newValue;
}
```

Also, I'm trying to decide, is `!(!modelValue.has_value() && viewValue.empty())` equivalent to `(modelValue.has_value() || !viewValue.empty())` - i.e. either the old or new ROI has to have a value?

**Review by rbauststfc — COMMENTED** [review]
The new logic looks like it's working really well. I see what you mean about the tricky boolean logic, great job figuring that out! 👍

I'm happy to approve as is, but I had a couple of thoughts on style that I thought I'd run by you first, just in case you agree.

**Review by rbauststfc — APPROVED** [review]
The tab seems to be working well, the crashes have all been sorted and the code changes look good 👍👍

**Comment by rbauststfc** [comment]
@gemmaguest I think this one would be good for you to gatekeeper if possible, as the "change requested" status is left over from your last review.
