### PR TITLE
Fix spurious transmission error with workspace groups

### LINKED ISSUE #23471: ReflectometryReductionOneAuto2 Throws error for singular transmission runs being passed, expecting groups.
### Expected behavior
To not throw: 
"Property "FIRSTTRANSMISSIONRUN" is not set to a valid value: "Workspace OFFSPEC44937_1 is not of the correct type"."

### Actual behavior
It throws:
"Property "FIRSTTRANSMISSIONRUN" is not set to a valid value: "Workspace OFFSPEC44937_1 is not of the correct type"."

### Steps to reproduce the behavior
Run this:
```python
OFFSPEC44956 = LoadISISNexus(Filename="OFFSPEC44956")
OFFSPEC44937 = LoadISISNexus(Filename="OFFSPEC44937")
ReflectometryReductionOneAuto(InputWorkspace='OFFSPEC44956', ThetaIn=0.7, 
  MomentumTransferStep=0.03, MomentumTransferMax=0.1, 
  OutputWorkspaceBinned='IvsQ_binned', OutputWorkspace='IvsQ', OutputWorkspaceWavelength='IvsLam',
  FirstTransmissionRun="OFFSPEC44937", AnalysisMode="MultiDetectorAnalysis",
  ProcessingInstructions="401-411")
```

### Platforms affected
All

Tips:
The actual error is decided at line: 443 in PropertyManager.cpp in the isValid() method.
The isValid() method calls the WorkspaceProperty.tcc file at line 201, furthermore look at line 246 for the actual decision that causes the error, it seems to be expecting a group when we only need a MatrixWorkspace.

### LINKED ISSUE #29411: Correct RROA docs regarding handing of workspace groups
PR #23341 changed ReflectometryReductionOneAuto's handling of workspace groups when doing transmission correction to always use the first workspace in the transmission group for the correction. Previously it sometimes did a sum of all the workspaces in the transmission group for some scenarios. The documentation [here](https://docs.mantidproject.org/nightly/algorithms/ReflectometryReductionOneAuto-v3.html#workspace-groups) has not been updated to reflect this change. Actually I think it was updated but mis-reads slightly in the third paragraph under Polarisation Analysis, where it talks about summing the first workspace (and this seems to duplicate the first paragraph).

There is also an unused variable left over from the change [here](https://github.com/mantidproject/mantid/blob/master/Framework/Reflectometry/src/ReflectometryReductionOneAuto3.cpp#L850), and the comment for that function also needs updating.

### PR DESCRIPTION
**Pull request by gemmaguest**
**Report to:** Max at ISIS

**Description of work.**
- This PR fixes some spurious error messages that are issued when you run ReflectometryReductionOneAuto on a workspace group, with transmission corrections enabled. The problem was related to running the same child algorithm multiple times. Now, a new child algorithm is created each time.
- To do this some refactoring was required. Other tidying has also been done to simplify the `processGroups` function and reduce duplicated code
- The documentation regarding processing groups has also been updated because it was out of date.

**To test:**

Run the script in the linked issue and ensure that no red warning messages are displayed in the log.

Fixes #23471 and fixes #29411 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Reflectometry/src/ReflectometryReductionOneAuto3.cpp [hunk 1]
```diff
@@ -842,144 +853,163 @@ bool ReflectometryReductionOneAuto3::processGroups() {
...
+
+  // Execute child algorithm over each group member and collate the output
+  // workspace names and output properties
+  std::vector<std::string> IvsQBinnedGroup, IvsQGroup, IvsLamGroup;
+  OutputProperties outputProperties;
+  for (size_t i = 0; i < group->size(); ++i) {
+    auto inputName = group->getItem(i)->getName();
+    auto outputNames = getOutputNamesForGroupMember(inputName, runNumber, i);
+    auto alg = createAlgorithmForWorkspaceInGroup(inputName, outputNames);
+    alg->execute();
```
Comment (DavidFair) [inline Framework/Reflectometry/src/ReflectometryReductionOneAuto3.cpp:940]: By default algorithms do not rethrow an exception and instead catch it on the callers behalf silently. It might be worth adding in `createAlgorithmForWorkspaceInGroup`:

`alg->setRethrows(true);`

So that if something does go awry this parent alg will stop and unwind with the exception

File: Framework/Reflectometry/src/ReflectometryReductionOneAuto3.cpp [hunk 2]
```diff
@@ -842,144 +853,163 @@ bool ReflectometryReductionOneAuto3::processGroups() {
...
-  setOutputWorkspaces(output, IvsLamGroup, IvsQBinnedGroup, IvsQGroup);
+/** Process groups. Groups are processed differently depending on transmission
+ * runs and polarization analysis.
+ */
+bool ReflectometryReductionOneAuto3::processGroups() {
+  // this algorithm effectively behaves as MultiPeriodGroupAlgorithm
+  m_usingBaseProcessGroups = true;
 
+  // Get our input workspace group
+  auto group = AnalysisDataService::Instance().retrieveWS<WorkspaceGroup>(
```
Comment (DavidFair) [inline Framework/Reflectometry/src/ReflectometryReductionOneAuto3.cpp:927]: This adds another ~40 LOC to this method bringing it up to ~90 lines for the single method, making it difficult to keep track of all the way through. Could we further chunk down the two big loops....

File: Framework/Reflectometry/src/ReflectometryReductionOneAuto3.cpp [hunk 3]
```diff
@@ -842,144 +853,163 @@ bool ReflectometryReductionOneAuto3::processGroups() {
...
+      getPropertyValue("InputWorkspace"));
+  // Get the run number for use in constructing default names
+  std::string runNumber = getRunNumberForWorkspaceGroup(group);
+
+  // Execute child algorithm over each group member and collate the output
+  // workspace names and output properties
+  std::vector<std::string> IvsQBinnedGroup, IvsQGroup, IvsLamGroup;
+  OutputProperties outputProperties;
+  for (size_t i = 0; i < group->size(); ++i) {
```
Comment (DavidFair) [inline Framework/Reflectometry/src/ReflectometryReductionOneAuto3.cpp:936]: ...Into something like, `void execOnGroupMembers(...)` for this loop and....

File: Framework/Reflectometry/src/ReflectometryReductionOneAuto3.cpp [hunk 4]
```diff
@@ -842,144 +853,163 @@ bool ReflectometryReductionOneAuto3::processGroups() {
...
-    const std::string IvsQName = outputNames.iVsQ;
-    const std::string IvsQBinnedName = outputNames.iVsQBinned;
-    const std::string IvsLamName = outputIvsLamNames[i];
-
-    // Find the spectrum processing instructions for ws index 0
+  // Now we've overwritten the IvsLam workspaces, we'll need to recalculate the
+  // IvsQ ones
+  auto correctedIvsLamWorkspaces =
+      workspaceNamesInGroup(outputGroupNames.iVsLam);
+  for (size_t i = 0; i < correctedIvsLamWorkspaces.size(); ++i) {
```
Comment (DavidFair) [inline Framework/Reflectometry/src/ReflectometryReductionOneAuto3.cpp:982]: ... `void recalculateGroupIvsq(...)` since it appears that it's mostly member access in both loops anyway

File: docs/source/algorithms/ReflectometryReductionOneAuto-v3.rst [hunk 5]
```diff
@@ -95,30 +95,29 @@ workspace in Q, :literal:`OutputWorkspaceBinned`, is not represented but it is h
...
+If :literal:`PolarizationAnalysis` is set to false the reduction stops. If it
+is set to true, the reduction continues and polarization corrections will be
+applied to the workspace that was output in wavelength. This uses the method
+and values specified in the parameters file to run
+:ref:`algm-PolarizationCorrectionFredrikze` or
+:ref:`algm-PolarizationCorrectionWildes` as appropriate.
 
 The result will be a new workspace in wavelength, which will override the
-previous one, that will be used as input to
+previous one. This will then be used as in input to re-run
```
Comment (DavidFair) [inline docs/source/algorithms/ReflectometryReductionOneAuto-v3.rst:114]: `as an input`?

**Review by DavidFair — COMMENTED** [review]
Some minor clarity points

File: Framework/Reflectometry/src/ReflectometryReductionOneAuto3.cpp (hunk 1 above)
Comment (gemmaguest) [reply Framework/Reflectometry/src/ReflectometryReductionOneAuto3.cpp:940]: That's already being set in that function (it doesn't show in the diffs because it was always there)

File: Framework/Reflectometry/src/ReflectometryReductionOneAuto3.cpp (hunk 2 above)
Comment (gemmaguest) [reply Framework/Reflectometry/src/ReflectometryReductionOneAuto3.cpp:927]: Well it was originally 166 LOC so I've already removed a lot! But yes it could be refactored further.

**Comment by gemmaguest** [comment]
Converted back to draft because I've broken some tests

**Review by DavidFair — APPROVED** [review]
Thanks, although the diff is a bit painful `processGroups` is significantly easier to follow in the file especially with the new comments

I've retested this locally and it still works without warnings, so lets :shipit:
