### PR TITLE
Parameter Estimation for ConvFit

### LINKED ISSUE #36346: ConvFit Parameter estimates do not update
**Original reporter:** Spencer

**Describe the bug**
The parameter estimates on the ConvFit tab of the Data Analysis interface do not get updated whenever a change is made to the plotted data.

There doesn't seem to be an implementation for the ConvFit parameter estimation
https://github.com/mantidproject/mantid/blob/b4d62261bb0a1d51ae72641ac5a24c5bd4329ca2/qt/scientific_interfaces/Indirect/IndirectDataAnalysisConvFitTab.cpp#L64

The code for parameter estimation is confusing, and it appears the IqtFit tab may use a different method to that used by ConvFit, MSDFit and FqFit. As part of this issue, it would be good to investigate this part of the code and see if it can be simplified. The MSDFit and FQFit tab also have duplicate code, which we want to try avoid.

**To Reproduce**
Load a sample and resolution file into ConvFit from the sample dataset
Add 2 Lorentzians
See that the estimated parameters are whole numbers 
These numbers do not change when you cycle through the different spectra

**Expected behavior**
The parameter values should update when changing spectra.

### PR DESCRIPTION
**Pull request by robertapplin**
### Description of work
This PR ensures a parameter estimate is provided on the ConvFit tab of the Data Analysis interface for the "Amplitude" parameter. This parameter is estimated using the maximum value in the spectrum.

Fixes #36346

### To test:
Load a sample and resolution file into ConvFit from the sample dataset
Add 2 Lorentzians
See that the estimated Amplitude parameters are **not** whole numbers
These Amplitude parameters should change when you cycle through the different spectra

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

File: qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/ConvFunctionModel.cpp [hunk 1]
```diff
@@ -11,12 +11,34 @@
...
+using namespace MantidQt::CustomInterfaces::IDA;
+
+auto const lorentzian = [](Mantid::MantidVec const &x, Mantid::MantidVec const &y) {
+  (void)x;
+  return std::unordered_map<std::string, double>{{"Amplitude", y[1]}};
+};
+
+auto const sqeFunction = [](Mantid::MantidVec const &x, Mantid::MantidVec const &y) {
+  (void)x;
+  return std::unordered_map<std::string, double>{{"Height", y[1]}};
```
Comment (RichardWaiteSTFC) [inline qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/ConvFunctionModel.cpp:26]: Fit functions that are derived from `IPeakFunction` have `setHeight` methods etc. that could avoid some of this hard-coding of the parameter names, but I note the SQE function are not peak functions - maybe they could be at some point in the future? note they would also need getters and setters for fwhm and centre.

File: qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/ConvFunctionModel.cpp [hunk 2]
```diff
@@ -247,14 +272,27 @@ void ConvFunctionModel::removeBackground() {
...
-            const std::pair<double, double>) -> DataForParameterEstimation { return DataForParameterEstimation{}; };
+  return [](const Mantid::MantidVec &x, const Mantid::MantidVec &y,
+            const std::pair<double, double> &range) -> DataForParameterEstimation {
+    (void)range;
+
+    auto const maxElement = std::max_element(y.cbegin(), y.cend());
+    if (maxElement == y.cend())
+      return DataForParameterEstimation{{}, {}};
+
+    auto const maxElementIndex = std::distance(y.cbegin(), maxElement);
```
Comment (RichardWaiteSTFC) [inline qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/ConvFunctionModel.cpp:283]: You might also want to consider subtracting the minimum non-zero y-value as an estimate for the background - this may not be very reasonable, it depends on the form of the background of course, but it's probably better than nothing! Don't mind though if you want to get this merged as it seems to be a big improvement.

File: qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/ConvFunctionModel.cpp [hunk 3]
```diff
@@ -247,14 +272,27 @@ void ConvFunctionModel::removeBackground() {
...
 
 EstimationDataSelector ConvFunctionModel::getEstimationDataSelector() const {
-  return [](const Mantid::MantidVec &, const Mantid::MantidVec &,
-            const std::pair<double, double>) -> DataForParameterEstimation { return DataForParameterEstimation{}; };
+  return [](const Mantid::MantidVec &x, const Mantid::MantidVec &y,
+            const std::pair<double, double> &range) -> DataForParameterEstimation {
+    (void)range;
+
+    auto const maxElement = std::max_element(y.cbegin(), y.cend());
+    if (maxElement == y.cend())
```
Comment (RichardWaiteSTFC) [inline qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/ConvFunctionModel.cpp:280]: Will this handle the case where `y` has zero length?

File: qt/scientific_interfaces/Inelastic/Analysis/IDAFunctionParameterEstimation.cpp [hunk 4]
```diff
@@ -57,30 +57,40 @@ void IDAFunctionParameterEstimation::addParameterEstimationFunction(std::string
...
 }
 
-void IDAFunctionParameterEstimation::estimateSingleFunctionParameters(
-    Mantid::API::IFunction_sptr &function, const DataForParameterEstimation &estimationData,
-    std::optional<Mantid::API::CompositeFunction_sptr> composite, std::optional<std::size_t> functionIndex) {
-  if (function) {
-    auto const parameterEstimatorName = nameForParameterEstimator(function, composite, functionIndex);
+void IDAFunctionParameterEstimation::estimateFunctionParameters(
+    Mantid::API::IFunction_sptr const &function, const DataForParameterEstimation &estimationData,
+    std::optional<Mantid::API::CompositeFunction_sptr> parentComposite, std::optional<std::size_t> functionIndex) {
```
Comment (RichardWaiteSTFC) [inline qt/scientific_interfaces/Inelastic/Analysis/IDAFunctionParameterEstimation.cpp:82]: It doesn't look from a quick grep that these optional arguments are ever used - is that correct?

**Review by RichardWaiteSTFC — COMMENTED** [review]
Code looks good, just a couple of questions and some suggestions/comments for the future.
Unfortunately updating conda has broken everything for me, so I can't do the functional testing sorry!

File: qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/ConvFunctionModel.cpp (hunk 1 above)
Comment (SpencerHowells) [reply qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/ConvFunctionModel.cpp:26]: SQE functions have a Lorentzian peak in their equations

File: qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/ConvFunctionModel.cpp (hunk 2 above)
Comment (SpencerHowells) [reply qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/ConvFunctionModel.cpp:283]: Not suitable. A wide Lorentzian does not go to zero at large energies and can be confused with background

Comment (RichardWaiteSTFC) [reply qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/ConvFunctionModel.cpp:283]: Fair enough, thanks for clarifying @SpencerHowells

File: qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/ConvFunctionModel.cpp (hunk 3 above)
Comment (robertapplin) [reply qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/ConvFunctionModel.cpp:280]: Yes this should be handled ok

File: qt/scientific_interfaces/Inelastic/Analysis/IDAFunctionParameterEstimation.cpp (hunk 4 above)
Comment (robertapplin) [reply qt/scientific_interfaces/Inelastic/Analysis/IDAFunctionParameterEstimation.cpp:82]: They are sometimes used from inside itself:

https://github.com/mantidproject/mantid/blob/2202b8e144192f4aa799d0ceb5dcce212e031cf7/qt/scientific_interfaces/Inelastic/Analysis/IDAFunctionParameterEstimation.cpp#L90

File: qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/ConvFunctionModel.cpp (hunk 1 above)
Comment (SpencerHowells) [reply qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/ConvFunctionModel.cpp:26]: The peak width is a function of Q (spectrum) and fitting parameters such as Diffusion Coeff , tau, beta

**Review by RichardWaiteSTFC — APPROVED** [review]
Got conda working so was able to test this, instructions work as expected so approving. Thanks @robertapplin!
