### PR TITLE
Load data as group option for DataSelector

### LINKED ISSUE #36410: Group Workspace with single entry is saved then loaded as single workspace
**Original reporter:** Spencer

**Describe the bug**
If you save a workspace group containing only 1 workspace to a nexus file, when you load the file back in it will no longer be a workspace group and instead it will be a single matrix workspace.

This is causing issues in the Indirect Corrections interface. The Apply Absorption Corrections tab takes a `_Corrections` group workspace containing corrections, and them to a sample file. The corrections group workspace is generated by either the "Calculate Paalman Pings" tab, or the "Calculate Monte Carlo Absorption" tab. However, clicking "Save result" on either of these tabs will save the group workspace corrections, but this is then loaded in as a single workspace when loaded on the Apply Absorption Corrections - causing the process to fail.

**To Reproduce**
Go into Tab 2 Calculate PP ( or Calc MC abs) and run for sample alone.
It will create a Group called *Corrections with single ws *corrections_ass.
Save Result
Go to Apply and use workspace for *red file & *corrections (the group) and it runs Ok.
Now for corrections try to read the Group file. It crashes.

**Potential solutions**
One solution might be to make sure that group workspaces containing one workspace get saved and loaded back in the same as they were saved.

**Platform/Version (please complete the following information):**
 - OS: Found on Windows

### PR DESCRIPTION
**Pull request by robertapplin**
### Description of work
The NeXus file format does not allow you to specify if a workspace was part of a workspace group at the point of saving the workspace in Mantid. As a consequence, when saving a WorkspaceGroup that only contains one entry, there is no information saved to say that this workspace should be loaded into a WorkspaceGroup when loaded back into Mantid. This was causing issues in the Indirect Corrections interface which expects a WorkspaceGroup for the *_Corrections* file.

To fix this issue, I decided it would be a bad idea to mess around with the NeXus file format by adding an attribute to indicate when a WorkspaceGroup is saved. I believe the "WorkspaceGroup" concept found in Mantid is not a concept which translates to NeXus files, so adding an attribute to our files along this line might bastardise the format.

The solution I went for was to add an option to the `DataSelector` widget which indicates that you should always expect a WorkspaceGroup to be loaded into this particular data selector. This means that if a single workspace entry is loaded, this entry will be placed inside a WorkspaceGroup and then the WorkspaceGroup is returned for processing. If the data is already loaded as a WorkspaceGroup, then no additional steps are taken.

Fixes #36410

### To test:
Open Indirect Corrections
Go to Tab 2 Calculate PP
Load `ExternalData/Testing/Data/UnitTest/iris26176_graphite002_red.nxs` as sample.
Select thickness as 0.1, and set the chemical formula as `C`
Click `Run`. It will create a Group called *Corrections with single ws inside
Save the group workspace to a file ending in *_Corrections*
Go to Apply Absorption Corrections tab
Load same sample as before
Load the corrections file you just saved in the Corrections field
Then click `Run`
It should run successfully and the preview plot should update with a blue line.

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

File: Framework/API/src/AnalysisDataService.cpp [hunk 1]
```diff
@@ -166,6 +167,22 @@ void AnalysisDataServiceImpl::remove(const std::string &name) {
...
+ * Make a new WorkspaceGroup and place the named member inside of it if the member is not already a WorkspaceGroup.
+ * @param name The name of a workspace to place into a new WorkspaceGroup.
+ * @return The created or existing WorkspaceGroup
+ */
+WorkspaceGroup_sptr AnalysisDataServiceImpl::makeGroup(std::string const &name) {
+  if (auto const workspace = retrieveWS<WorkspaceGroup>(name)) {
+    return workspace;
+  }
+  auto wsGroup = std::make_shared<Mantid::API::WorkspaceGroup>();
+  wsGroup->addWorkspace(remove(name));
```
Comment (adriazalvarez) [inline Framework/API/src/AnalysisDataService.cpp:183]: Sorry if I missed something. But I don't understand well why is necessary to call the remove func, and to change remove to retrieve the shared pointer?

**Review by adriazalvarez — COMMENTED** [review]
I have followed test instructions, the crash in apply absorption correction is no longer there. 
All changes seem fine. I have added a question on the code. 

Just a comment, while the changes in load function apply to DataSelector classes, when you load the corrected files from the workspace widget or using python ( as in https://docs.mantidproject.org/nightly/algorithms/ApplyPaalmanPingsCorrection-v1.html), it still doesn't load as group. I guess is hard to change that, so maybe it'll be better to  change the apply absorption load functions to be able to handle single workspaces, what do you think?

**Comment by robertapplin** [comment]
> @robertapplin @adriazalvarez Not happy with that. Using a group is part of checking that user does not do stupid things. Eg, using the *ass ws when there is a container.

Ok, in that case would you both be happy with the current implementation described in the description of this PR?

@adriazalvarez I've noticed that when I do the following, I can get the same problem you are seeing:
1. Run Apply Absorption corrections from the tab
2. Do `Show history` on the corrected workspace
3. Click `Script to Clipboard` 
4. Paste script into python editor and run it
5. I get the same error as you

I believe I can fix this problem, whilst still avoiding changing the Corrections workspace Property type in the `ApplyPaalmanPingsCorrection` algorithm (it will remain as WorkspaceGroup). Would you be happy with this as a compromise solution?

**Comment by SpencerHowells** [comment]
@robertapplin @adriazalvarez I'm happy with the current implemation and a compromise. BTW, I detest running scripts with programs like this - you need to see what is happening.

**Comment by adriazalvarez** [comment]
@robertapplin @SpencerHowells 

Thanks for the proposed solution. I'm ok with it.

File: Framework/API/src/AnalysisDataService.cpp (hunk 1 above)
Comment (robertapplin) [reply Framework/API/src/AnalysisDataService.cpp]: I think I returned the shared pointer from `remove` because it is convenient to remove an item from a data structure and get it at the same time, a bit like the `pop` method for a python dictionary. I'm open to other suggestions

Comment (adriazalvarez) [reply Framework/API/src/AnalysisDataService.cpp]: So, the workspace is removed from the ads, but not really deleted? Where does it live?

Comment (robertapplin) [reply Framework/API/src/AnalysisDataService.cpp]: Yes, so the workspace remains in memory but is removed from the ADS. You can think of the ADS as a container such as a dictionary. When you pop an item from the dictionary it is removed from the dictionary, but still exists in memory if it is assigned to another variable.

File: qt/widgets/common/src/DataSelector.cpp [hunk 2]
```diff
@@ -228,6 +229,16 @@ void DataSelector::autoLoadFile(const QString &filepath) {
  */
 void DataSelector::handleAutoLoadComplete(bool error) {
   if (!error) {
+    auto &ads = AnalysisDataService::Instance();
+    auto workspaceName = getWsNameFromFiles().toStdString();
+
+    if (m_alwaysLoadAsGroup && !ads.retrieveWS<WorkspaceGroup>(workspaceName)) {
```
Comment (adriazalvarez) [inline qt/widgets/common/src/DataSelector.cpp:235]: Can this segment of code be a separate function?

**Review by adriazalvarez — CHANGES_REQUESTED** [review]

**Review by adriazalvarez — APPROVED** [review]
Thanks for the changes. It looks good to me. 
The interface works as expected.
