### PR TITLE
Ensure proton charge returned consistently across datasets with period data

### LINKED ISSUE #39312: NormaliseByCurrent doesn't work for summed workspaces
**Describe the bug**
Compared to `6.12` when you run `NormaliseByCurrent` on Nightly on a workspace produced by adding two *event* workspaces (using `Plus`) it does not normalise the workspaces. (Histo workspaces work fine).

**To Reproduce**

Run the following script on the data here: `\\Olympic\Babylon5\Public\duc\sum_norm_bug.zip`

```python
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt

Load(Filename='/archive/NDXMARI/Instrument/data/cycle_25_1/MAR30565.nxs', OutputWorkspace='MAR30565')
Load(Filename='/archive/NDXMARI/Instrument/data/cycle_25_1/MAR30566.nxs', OutputWorkspace='MAR30566')
Plus(LHSWorkspace='MAR30565', RHSWorkspace='MAR30566', OutputWorkspace='MAR30565sum')
NormaliseByCurrent(InputWorkspace='MAR30565sum', OutputWorkspace='MAR30565sum')
NormaliseByCurrent(InputWorkspace='MAR30565', OutputWorkspace='MAR30565')
NormaliseByCurrent(InputWorkspace='MAR30566', OutputWorkspace='MAR30566')

Rebin(InputWorkspace='MAR30565', OutputWorkspace='MAR30565s', Params='3200,1,3500', PreserveEvents=False)
SumSpectra(InputWorkspace='MAR30565s', OutputWorkspace='MAR30565s', IncludeMonitors=False)
Rebin(InputWorkspace='MAR30566', OutputWorkspace='MAR30566s', Params='3200,1,3500', PreserveEvents=False)
SumSpectra(InputWorkspace='MAR30566s', OutputWorkspace='MAR30566s', IncludeMonitors=False)

Rebin(InputWorkspace='MAR30565sum', OutputWorkspace='MAR30565sums', Params='3200,1,3500', PreserveEvents=False)
SumSpectra(InputWorkspace='MAR30565sums', OutputWorkspace='MAR30565sums', IncludeMonitors=False)


MAR30565sums = mtd['MAR30565sums']
MAR30566s = mtd['MAR30566s']
MAR30565s = mtd['MAR30565s']

fig, axes = plt.subplots(dpi=96.0, edgecolor='#ffffff', num='MAR30565s, MAR30566s, MAR30565sums', subplot_kw={'projection': 'mantid'})
axes.plot(MAR30565s, color='#1f77b4', label='MAR30565s: spec 4', wkspIndex=0)
axes.plot(MAR30566s, color='#ff7f0e', label='MAR30566s: spec 4', wkspIndex=0)
axes.plot(MAR30565sums, color='#2ca02c', label='MAR30565sums: spec 4', wkspIndex=0)
axes.tick_params(axis='x', which='major', **{'gridOn': False, 'tick1On': True, 'tick2On': False, 'label1On': True, 'label2On': False, 'size': 6, 'tickdir': 'out', 'width': 1})
axes.tick_params(axis='y', which='major', **{'gridOn': False, 'tick1On': True, 'tick2On': False, 'label1On': True, 'label2On': False, 'size': 6, 'tickdir': 'out', 'width': 1})
axes.set_title('MAR30565s, MAR30566s, MAR30565sums')
axes.set_xlabel('Time-of-flight ($\\mu s$)')
axes.set_ylabel('Counts (microAmp.hour $\\mu s$)$^{-1}$')
legend = axes.legend(fontsize=8.0).set_draggable(True).legend

fig.show()
```

Image

Running the above script on `6.12` produces the left figure (desired result), running it on nightly (from 9th May) produces the left figure (where the summed run is just under twice the height of each run - the runs were not of equal duration).

**Expected behavior**
Behaviour of `NormaliseByCurrent` on summed event workspaces to be the same in 6.12 and nightly.

**Screenshots**
See above.

**Platform/Version (please complete the following information):**
 - OS: Rocky Linux 8 (DAaaS)
 - OS Version:
 - Mantid Version: `6.12.20250509.1257`

**Additional context**

### PR DESCRIPTION
**Pull request by MialLewis**
#### Summary of work

A bug was introduced in #39029. For any dataset that has period data, the log `proton_charge_by_period` is used to return the proton charge for the current period.

When runs are added. the `proton_charge_by_period` log is not summed; An erroneous proton charge is therefore subsequently returned.

To resolve this, this PR enables the elementwise addition of the `proton_charge_by_period` log during run addition.

Using a bool property was causing warnings to be raised during workspace save, as bool properties are not supported. The unfiltered flag has therefore been changed to an int.

Also, the check that flags for period data filtering has been moved outside of ` if (!workspace->run().hasProperty(workspace->run().getProtonChargeLogName()))` to account for datasets that come pre-loaded with this log (vesuvio).

This PR fixes a number of the more prelevant issues, but leaves some inconsistencies. An issue to fix these issues in an upcoming has been raised:
https://github.com/mantidproject/mantid/issues/39336

Some release notes have been added which I owed to other PRs.

### To test:

Run the following script:
```
from mantid.simpleapi import *

ws_mar1 = Load(Filename='MAR30565.nxs')
ws_mar2 = Load(Filename='MAR30566.nxs')
wssum_mar = Plus(LHSWorkspace=ws_mar1, RHSWorkspace=ws_mar2)
print(ws_mar1.getRun().getProtonCharge())
print(ws_mar2.getRun().getProtonCharge())
print(wssum_mar.getRun().getProtonCharge())

ws_ves1 = Load(Filename='VESUVIO00054091.nxs')
ws_ves2 = Load(Filename='VESUVIO00054092.nxs')
wssum_ves = Plus(LHSWorkspace=ws_ves1[0], RHSWorkspace=ws_ves2[0])
print(ws_ves1[0].getRun().getProtonCharge())
print(ws_ves2[0].getRun().getProtonCharge())
print(wssum_ves.getRun().getProtonCharge())

ws_pref1 = Load(Filename='POLREF00045018.nxs')
ws_pref2 = Load(Filename='POLREF00045019.nxs')
wssum_pref = Plus(LHSWorkspace=ws_pref1[0], RHSWorkspace=ws_pref2[0])
print(ws_pref1[0].getRun().getProtonCharge())
print(ws_pref2[0].getRun().getProtonCharge())
print(wssum_pref.getRun().getProtonCharge())
```

Expected Output:
```
386.2809143066406
250.0518341064453
636.3327484130859

15.014394760131836
15.013330459594727
30.027725219726562

19.597339630126953
19.55563735961914
39.152976989746094

```

Previous Output:
```
386.2809143066406
250.0518341064453
386.2809143066406

90.05866241455078
90.05770111083984
180.11636352539062

19.597339630126953
19.55563735961914
19.597339630126953
```

Fixes #39312

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by sf1919** [comment]
Does this fix #39312 ?

**Comment by mducle** [comment]
@sf1919 - Yes, we checked and it also gives the correct proton charge for summed multi-period datafiles.

**Comment by MialLewis** [comment]
I've found some inconsistencies, will have to revisit.

File: Framework/API/src/Run.cpp [hunk 1]
```diff
@@ -26,12 +28,49 @@ using namespace Kernel;
...
+auto addPeriodSeries = [](Property *left, const Property *right) {
+  auto *leftAP = dynamic_cast<ArrayProperty<double> *>(left);
+  const auto *rightAP = dynamic_cast<const ArrayProperty<double> *>(right);
+  if (!leftAP || !rightAP) {
+    throw std::runtime_error("Expected ArrayProperty<double> for both inputs.");
+  }
+  const auto &leftVec = leftAP->operator()();
+  const auto &rightVec = rightAP->operator()();
+  if (leftVec.size() != rightVec.size()) {
+    return;
```
Comment (mducle) [inline Framework/API/src/Run.cpp:42]: So I just tried to add two files with different periods (specifically, `POLREF00045024.nxs` with 2 periods and `POLREF00045025.nxs` with 1 period) and it runs fine - but it gives:

```
print(mtd['POLREF00045024_1'].run().getProperty('proton_charge_by_period').value)
print(mtd['POLREF00045025'].run().getProperty('proton_charge_by_period').value)
print(mtd['POLREF00045024sum_1'].run().getProperty('proton_charge_by_period').value)

[19.65224075 19.65121078]
[39.23700333]
[19.65224075 19.65121078]
```

whereas using `POLREF00045023.nxs` instead of `POLREF00045025.nxs` gives:

```
print(mtd['POLREF00045023_1'].run().getProperty('proton_charge_by_period').value)
print(mtd['POLREF00045024_1'].run().getProperty('proton_charge_by_period').value)
print(mtd['POLREF00045024sum_1'].run().getProperty('proton_charge_by_period').value)

[19.64065933 19.64307785]
[19.65224075 19.65121078]
[39.29290009 39.29428864]
```

But I guess this might be something to either: 1) fix after the release, or 2) give an error here since I'm not sure how valid adding datasets with different periods is...

Comment (MialLewis) [reply Framework/API/src/Run.cpp:42]: I'm going to get this fix in. I've raised an issue to further resolve the remaining inconsistencies in the next release:

https://github.com/mantidproject/mantid/issues/39336

**Review by sf1919 — APPROVED** [review]
I'm approving this and merging it in. It is passed all its tests and we need it to be available in the nightly for manual testing.
