### PR TITLE
Optimize the addTies function by implementing a single sort operation after all ties are added

### LINKED ISSUE #38962: sortTies is a bottleneck when adding ties to a multi-domain function
**Describe the bug**

In PR #38515 a `MultiDomainFunction` is used to share peak parameters across adjacent pixels.

However the execution time for the algorithm `IntegratePeaks1DProfile`  has increased by an order of magnitude (or more!) - the bottleneck is due to `sortTies` being run for each tie added. The actual fit is very quick.

https://github.com/mantidproject/mantid/blob/13795d0b40e8f01d39b1819a54ae20bca6cec137/Framework/API/src/IFunction.cpp#L1600

**To Reproduce**
(1) Run this script in debug with a breakpoint at the line above
```
from mantid.simpleapi import *
from mantid.api import MultiDomainFunction, FunctionFactory
from mantid.fitfunctions import FunctionWrapper
                          

comp_func = CompositeFunction(Gaussian(Height=1, Sigma=0.3, PeakCentre=3), FunctionWrapper("FlatBackground"), NumDeriv=True)
ws = CreateSampleWorkspace(OutputWorkspace='ws', Function='User Defined', UserDefinedFunction=str(comp_func), XUnit='DeltaE', 
                           XMax=7, BinWidth=0.1, NumBanks=1, BankPixelWidth=2)

func = MultiDomainFunction()        
md_fit_kwargs = {}
for ispec in range(ws.getNumberHistograms()):
    func.add(comp_func.function)
    func.setDomainIndex(ispec,ispec)
    key_suffix = f"_{ispec}" if ispec > 0 else ""
    md_fit_kwargs["InputWorkspace" + key_suffix] = ws.name()
    md_fit_kwargs["StartX" + key_suffix] = 0.1
    md_fit_kwargs["EndX" + key_suffix] = 6.8
    md_fit_kwargs["WorkspaceIndex" + key_suffix] = ispec

add_ties = True
if add_ties:
    ties = []
    for idom in range(1, ws.getNumberHistograms()):
        for ifunc in range(func[0].nFunctions()):
            for ipar in range(func[0][ifunc].nParams()):
                par = func[0][ifunc].getParamName(ipar)
                ties.append(f"f{idom}.f{ifunc}.{par}=f0.f{ifunc}.{par}")
    func_str = f"{str(func)};ties=({','.join(ties)})"
else:
    func_str = str(func)
    
out = Fit(Function=func_str, Output='ws', StoreInADS=True, CreateOutput=True, OutputCompositeMembers=True,
          **md_fit_kwargs)
```

You will see `sortTies` gets called for every tie

(2) Increase the number of spectra
```
ws = CreateSampleWorkspace(OutputWorkspace='ws', Function='User Defined', UserDefinedFunction=str(comp_func), XUnit='DeltaE', 
                           XMax=7, BinWidth=0.1, NumBanks=25, BankPixelWidth=2)
```

Observe that it takes a lot longer - if you set this too high (e.g. `NumBanks=100` Mantid will hang)

**Expected behavior**
Would call `sortTies` once after all ties added?

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: [e.g. Windows, RHEL 7, Ubuntu, macOS]
 - OS Version:
 - Mantid Version [e.g. 6.0.0]

**Additional context**

### PR DESCRIPTION
**Pull request by MohamedAlmaki**
### Description of work
This PR optimises the `addTies` function in the interface of all fitting functions `IFunction`. Previously, the function sorted the ties each time a new tie was added. This PR changes the behaviour by sorting all ties after they're completely added, and if sorting fails, it reverses all changes. This implementation has created a significant performance boost, as shown in the graph below comparing old and new implementations. I know there's duplicate code in the implementation, but when I tried to refactor the function, it became more complicated, so I went back to this simpler version with minimal changes. Since this is core code used throughout the codebase, keeping changes small is safer. I've also added a unit test that covers all cases. 

image

Fixes #38962

### To test:
1- Run this script
```
from mantid.simpleapi import *
from mantid.api import MultiDomainFunction, FunctionFactory
from mantid.fitfunctions import FunctionWrapper
                          

comp_func = CompositeFunction(Gaussian(Height=1, Sigma=0.3, PeakCentre=3), FunctionWrapper("FlatBackground"), NumDeriv=True)
ws = CreateSampleWorkspace(OutputWorkspace='ws', Function='User Defined', UserDefinedFunction=str(comp_func), XUnit='DeltaE', 
                           XMax=7, BinWidth=0.1, NumBanks=1, BankPixelWidth=2)

func = MultiDomainFunction()        
md_fit_kwargs = {}
for ispec in range(ws.getNumberHistograms()):
    func.add(comp_func.function)
    func.setDomainIndex(ispec,ispec)
    key_suffix = f"_{ispec}" if ispec > 0 else ""
    md_fit_kwargs["InputWorkspace" + key_suffix] = ws.name()
    md_fit_kwargs["StartX" + key_suffix] = 0.1
    md_fit_kwargs["EndX" + key_suffix] = 6.8
    md_fit_kwargs["WorkspaceIndex" + key_suffix] = ispec

add_ties = True
if add_ties:
    ties = []
    for idom in range(1, ws.getNumberHistograms()):
        for ifunc in range(func[0].nFunctions()):
            for ipar in range(func[0][ifunc].nParams()):
                par = func[0][ifunc].getParamName(ipar)
                ties.append(f"f{idom}.f{ifunc}.{par}=f0.f{ifunc}.{par}")
    func_str = f"{str(func)};ties=({','.join(ties)})"
else:
    func_str = str(func)
    
out = Fit(Function=func_str, Output='ws', StoreInADS=True, CreateOutput=True, OutputCompositeMembers=True,
          **md_fit_kwargs)
```

2- Increase the number of spectra and check the performance of the script compared to an older version of Mantid 
```
ws = CreateSampleWorkspace(OutputWorkspace='ws', Function='User Defined', UserDefinedFunction=str(comp_func), XUnit='DeltaE', 
                           XMax=7, BinWidth=0.1, NumBanks=25, BankPixelWidth=2)
```
3- You should notice a significant performance improvement compared with the previous version
4- Test the fitting engine by following the Mantid basic course (especially adding ties and constraints section): https://docs.mantidproject.org/nightly/tutorials/mantid_basic_course/fitting_data/index.html#fitting-data

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

File: Framework/API/src/IFunction.cpp [hunk 1]
```diff
@@ -230,18 +230,65 @@ void IFunction::tie(const std::string &parName, const std::string &expr, bool is
...
   list.parse(ties);
   list.toList();
   for (const auto &t : list) {
     if (t.name() == "=" && t.size() >= 2) {
       size_t n = t.size() - 1;
-      const std::string value = t[n].str();
+      const std::string expr = t[n].str();
       for (size_t i = n; i != 0;) {
         --i;
-        this->tie(t[i].name(), value, isDefault);
```
Comment (RichardWaiteSTFC) [inline Framework/API/src/IFunction.cpp:242]: As you say in the PR description, there seems to be some duplicated code here from `IFunction::tie` and `IFunction::addTie` - I get the logic of making minimal changes to those functions to this important code, but did you consider adding an optional bool flag e.g. `doSortTies` to `addTie` that defaults to true and could be called in `addTies` with `doSort=false`? Or if thatdoesn't work a function `addTieUnsafe` or equivalent that can be called in `addTie` before the sorting here
https://github.com/mantidproject/mantid/blob/f5748f14cbadd2d28983369d1c655338864ea7ed/Framework/API/src/IFunction.cpp#L341-L343
If you tried the above and it didn't work, it might be worth documenting in a comment in case anyone later tries to refactor?

**Review by RichardWaiteSTFC — COMMENTED** [review]
Great work, step (2) took ~1 s on this branch vs ~40s on main. I have checked ties (custom and to function) and constraints are working as usual.

Don't notice any speedup of `IntegratePeaks1DProfile` using this test code

```
ws=Load(Filename="SXD23767.raw")
peaks=FindSXPeaksConvolve(InputWorkspace=ws, PeaksWorkspace="peaks", ThresholdIoverSigma=50)
DeleteTableRows(TableWorkspace='peaks', Rows='5-60')

profile_kwargs = {
            "GetNBinsFromBackToBackParams": True,
            "CostFunction": "RSq",
            "IntegrateIfOnEdge": True,
            "LorentzCorrection": False,
            "IOverSigmaThreshold": 2,
            "NRows": 7,
            "NCols": 7,
            "NRowsEdge": 1,
            "NColsEdge": 1,
            "outputFile": r"C:\Users\xhg73778\Desktop\peaks_1Dprofile_test.pdf"
        }
int_peaks=IntegratePeaks1DProfile(Inputworkspace=ws, PeaksWorkspace=peaks, OutputWorkspace="intpeaks1dprof", **profile_kwargs)
```
Not sure why though - will check on debug

**Comment by RichardWaiteSTFC** [comment]
Also forgot to say, thanks for the tests, very thorough!

File: Framework/API/src/IFunction.cpp (hunk 1 above)
Comment (MohamedAlmaki) [reply Framework/API/src/IFunction.cpp:242]: I will check on my side, too.

I was hesitant to change things because I spent a lot of time trying to implement this as a separate function, which was the wrong direction. But yeah, that sounds reasonably safe, I will just add an unsafe private function.

Comment (MohamedAlmaki) [reply Framework/API/src/IFunction.cpp:242]: I have tested the algorithm on this branch and it takes around ~25 seconds to finish, unlike in the latest mantid version, where it takes around 1 minute to finishh, so that is a 4x improvement

Also, I will push the refactored code shortly

**Review by RichardWaiteSTFC — APPROVED** [review]
Thanks for the changes to remove duplication. I can confirm that the PR description code is much quicker now (and is behaving correctly wrt to ties) and also I see a significant speedup in `IntegratePeaks1DProfile`. I have also played around in the fit property browser and ties (adding, removing, invalid etc.) seem to be working OK to me. Thanks for this!
