### PR TITLE
Fix performance regression caused by changes to IndexInfo

### LINKED ISSUE #19339: Performance regression caused by changes to IndexInfo
See, e.g., `ConvertSpectrumAxis` and `DiffractionFocussing2` here: http://builds.mantidproject.org/view/All/job/master_performancetests2/Master_branch_performance_tests/.

Caused by https://github.com/mantidproject/mantid/pull/19186.

Some slowdown was expected, but this is too much -> investigate.

### PR DESCRIPTION
**Pull request by SimonHeybrock**
See title and issue. Probably this can be done in a nicer way, but since `IndexInfo` is still in early development I suspect there will be further changes in the near future so I kept things simple for now.

**To test:**

Code review.

Fixes #19339 (probably, though further improvements might be necessary at some point).

No release notes, issue introduced after last release.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Indexing/src/SpectrumNumberTranslator.cpp [hunk 1]
```diff
@@ -125,5 +160,12 @@ void SpectrumNumberTranslator::checkUniqueSpectrumNumbers() const {
                            "numbers contained duplicate entries.");
 }
 
+void SpectrumNumberTranslator::setupMaps() const {
```
Comment (LamarMoore) [inline Framework/Indexing/src/SpectrumNumberTranslator.cpp]: Better name?

**Review by LamarMoore — COMMENTED** [review]
Code looks good just a couple minor comments. I will test the speed before and after your changes for the algorithms listed in the issue.

File: Framework/Indexing/src/SpectrumNumberTranslator.cpp [hunk 2]
```diff
@@ -57,12 +91,12 @@ SpectrumNumberTranslator::makeIndexSet(SpectrumNumber min,
   static_cast<void>(m_spectrumNumberToPartition.at(min));
   static_cast<void>(m_spectrumNumberToPartition.at(max));
 
-  // The order of spectrum numbers can be arbitrary so we need to iterate.
+  std::call_once(m_mapSetup, &SpectrumNumberTranslator::setupMaps, this);
   std::vector<size_t> indices;
```
Comment (SimonHeybrock) [inline Framework/Indexing/src/SpectrumNumberTranslator.cpp]: Maybe, but I would usually wait for profiling results. Since this method is not yet in widespread use, I prefer keeping things simple.

**Comment by LamarMoore** [comment]
:shipit:
