### PR TITLE
Crystal field peaks fit fails

### LINKED ISSUE #16495: Fitting a CrystalFieldPeaks function to a TableWorkspace fails.
### Expected behavior

This script should run without error:
```
tab = CreateEmptyTableWorkspace()
tab.addColumn('double', 'Energy')
tab.addColumn('double', 'Intensity')
tab.addRow([0., 2.74937])
tab.addRow([29.3261, 0.7204])
tab.addRow([44.3412, 0.4298])
fun = 'name=CrystalFieldPeaks,Ion=Ce,Temperature=25.0,Symmetry=C2v,B20=0.4,B22=4,B40=-0.03,B42=-0.1,B44=-0.1'
fun += ',ties=(IntensityScaling=1,B60=0,B62=0,B64=0,B66=0,BmolX=0,BmolY=0,BmolZ=0,BextX=0,BextY=0,BextZ=0)'
Fit(fun, tab, Output='fit', DataColumn='Energy', DataColumn_1='Intensity')
```

### Actual behavior

But it gives a runtime error: `Property with given name already exists search object DATACOLUMN`

### Steps to reproduce the behavior

Run the script above.

### Platforms affected

All.

### PR DESCRIPTION
**Pull request by mantid-roman**
It was failing due to a bug in GeneralDomainCreator which is used in CrystalFieldPeaks function at the moment. The bug is fixed.

**To test:**

Run the script from the issue description.

Fixes #16495.

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
Looks OK :shipit:

File: Framework/CurveFitting/src/GeneralDomainCreator.cpp [hunk 1]
```diff
@@ -59,18 +59,19 @@ GeneralDomainCreator::GeneralDomainCreator(
...
+  if (addProp) {
+    for (auto &propName : m_domainColumnNames) {
+      declareProperty(new Kernel::PropertyWithValue<std::string>(propName, ""),
+                      "A name of a domain column.");
+    }
+    for (auto &propName : m_dataColumnNames) {
+      declareProperty(new Kernel::PropertyWithValue<std::string>(propName, ""),
+                      "A name of a fitting data column.");
+    }
+    for (auto &propName : m_weightsColumnNames) {
```
Comment (FedeMPouzols) [inline Framework/CurveFitting/src/GeneralDomainCreator.cpp]: I think these could be `const auto &...`?
