### PR TITLE
Fix Indirect Sqw crash

### LINKED ISSUE #34461: Loading data into s(Q,w) tab of indirect data reduction interface with no default instrument causes crash
**Describe the bug**
Loading data into the s(q,w) tab of indirect data reduction interface with no default instrument causes mantid to crash. This error should be handled.

It looks like mantid is trying to find the instrument file related to the default instrument. If there is none it tries to load a non existent `_Defintion` file. 

**To Reproduce**
1) Ensure no default instrument facility is set in `settings`
2) Navigate `Interfaces` tab > `Indirect` > `data reduction`.
3) In the indirect data reduction interface select the `S(Q,w)` tab.
4) Using browse, load the `irs26176_graphite002_red` file
5) Observe crash.

**Expected behavior**
The error should be handled

**Platform/Version (please complete the following information):**
Windows

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR ensures that we check to see if an instrument workspace is loaded before trying to retrieve particular components from that instrument. It also ensures that an error is caught if the facility or instrument isn't set before loading data on the S(Q,w) tab.

This area could do with some refactoring. In particular, there is a widely used function in indirect which throws runtime_errors, and these errors are often uncaught. 

https://github.com/mantidproject/mantid/blob/46c31940880ccc5c5665166915a658bcb9c4552b/qt/scientific_interfaces/Indirect/IndirectDataReductionTab.cpp#L100

I have opened a maintenance issue (#34488) to look into this because too much can go wrong if it goes into `release-next`, and I see it causing no obvious issues at the moment.

**To test:**
1) Ensure no default instrument facility is set in `settings`
2) Navigate `Interfaces` tab > `Indirect` > `data reduction`.
3) In the indirect data reduction interface select the `S(Q,w)` tab.
4) Using browse, load the `irs26176_graphite002_red` file
5) A message box should pop up telling you to set the facility and/or instrument. No crash!

Fixes #34461

No tests have been added because this area doesn't have test files yet, and is still under heavy refactoring.

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/scientific_interfaces/Indirect/IndirectDataReduction.cpp [hunk 1]
```diff
@@ -174,37 +176,39 @@ MatrixWorkspace_sptr IndirectDataReduction::instrumentWorkspace() {
...
-      auto const parameterFilename = idfDirectory + instrumentName + "_Definition" + dateRange + ".xml";
-      auto loadAlg = AlgorithmManager::Instance().create("LoadEmptyInstrument");
-      loadAlg->setChild(true);
-      loadAlg->setLogging(false);
-      loadAlg->initialize();
-      loadAlg->setProperty("Filename", parameterFilename);
-      loadAlg->setProperty("OutputWorkspace", "__IDR_Inst");
-      loadAlg->execute();
-      MatrixWorkspace_sptr instWorkspace = loadAlg->getProperty("OutputWorkspace");
+      if (!instrumentName.empty()) {
```
Comment (MialLewis) [inline qt/scientific_interfaces/Indirect/IndirectDataReduction.cpp:183]: It looks like nothing in this function aside from the first line is executed unless `!instrumentName.empty()`, perhaps it would be better to add this condition to the main `if` statement, and that `if` statement into an early return?

**Review by MialLewis — CHANGES_REQUESTED** [review]
Bug fix works, and code looks ok though agree with refactor suggestions. One minor comment to consider.

File: qt/scientific_interfaces/Indirect/IndirectDataReduction.cpp (hunk 1 above)
Comment (robertapplin) [reply qt/scientific_interfaces/Indirect/IndirectDataReduction.cpp]: Ah yes, that would be much better - thanks!

**Review by MialLewis — APPROVED** [review]
