### PR TITLE
Fix sliceviewer crash 

### LINKED ISSUE #26235: Sliceviewer crashes with Matrix workspaces
### Actual behavior
The sliceviewer crashes the workbench when trying to open the sliceviewer on a "normal" matrix workspace.

It seems to start ok for MDWorkspaces. and it seems to be ok on linux.

### Steps to reproduce the behavior
1. open workbench
1. Load a worspace
1. right click and select sliceviewer
1. The window will appear white for a couple of seconds and then crash out to the error reporter.

The following file definately crashes, but it seems to be consistent for any matrix workspace.
SXD23767.raw (can be found in the training data)

### Platforms affected
Windows 8 and 10, and ubuntu.

### PR DESCRIPTION
**Pull request by ghost**
### **This should be tested by someone on Windows or Ubuntu 18**

**Description of work.**
A crash when opening Slice Viewer was being caused by a C++ `vector` being de-referenced before being passed through the `boost::python` API, this was causing a segfault. This only seemed to be occuring on Windows and Ubuntu 18.

The python API function `MatrixWorkspace::getSignalCoord` has been re-written to create a numpy array on the C++ side rather than a vector and pass this directly back to the Python. This also avoids copying a vector into a numpy array.

**To test:**
- Running Ubuntu 18 or Windows, open Workbench
- Load a workspace, right-click it and open Slice Viewer.
- It shouldn't crash. Make sure the workspace is plotted correctly.

Fixes #26235 . 

*This does not require release notes* because **slice viewer not yet released**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by LamarMoore — CHANGES_REQUESTED** [review]
Sliceviewer didn't crash when I loaded GEM focussed data from the Doc test however, trying to do anything with the Sliceviewer was painfully slow. Trying to resize the window caused the workbench to freeze.  Not sure how to move forward with approvals @NickDraper. A number of builds are also failing.

**Comment by NickDraper** [comment]
> Sliceviewer didn't crash when I loaded GEM focussed data from the Doc test however, trying to do anything with the Sliceviewer was painfully slow. Trying to resize the window caused the workbench to freeze. Not sure how to move forward with approvals @NickDraper. A number of builds are also failing.

@LamarMoore What was it slow compared to?  Mantidplot sliceviewer, or workbench sliceviewer before this fix?
If it is slower because of this fix then that needs attention in this PR.  If it is not as fast as we want, but not due to this PR when approve this PR.

**Comment by rosswhitfield** [comment]
This looks good but is definitely slower by about a factor of 3. Not great for the user experience.

My test script
```python
from mantid.simpleapi import *
import time
import numpy as np
ws=CreateSampleWorkspace()
x=np.linspace(7000,12500,640)
y=np.linspace(50,100,480)
X,Y = np.meshgrid(x,y)
xy = np.vstack((X.ravel(),Y.ravel())).T
t0=time.time()
s=ws.getSignalAtCoord(xy, mantid.api.MDNormalization.NoNormalization)
t1=time.time()
print(t1-t0)
```

Master is ~0.085sec
This branch is ~0.27sec

**Comment by robertapplin** [comment]
This might also fix #26116 .

**Comment by hsautessella** [comment]
The latest commit should hopefully improve performance. Maybe it's because I'm using a Windows Debug build but my benchmarks seem far slower than yours: 
```
Master:
    Time taken: 3.025 +/- 0.00871207227495

Previous PR state (commit a340610):
    Time taken: 3.30529999733 +/- 0.0075033903486
    
Using latest commit (commit 1b54d8d):
    Time taken: 2.89719998837 +/- 0.00823989584094
```

**Review by rosswhitfield — DISMISSED** [review]
The performance is now comparable to master.

**Review by LamarMoore — DISMISSED** [review]

**Comment by hsautessella** [comment]
Before this gets merged I have one more optimization to push

**Comment by hsautessella** [comment]
Sorry for pushing after the previous approvals, I'd just found another optimization that gave a ~20% speedup. Provided the tests pass, this should be ready to go

**Comment by LamarMoore** [comment]
@hsautessella Can you kill the previous builds?

**Comment by martyngigg** [comment]
Can we just hold off on merging. I think we might have created a memory leak but I need to check...

**Comment by martyngigg** [comment]
It looks like we need to tell the `PyObject` to delete the memory we have allocated: https://stackoverflow.com/questions/52731884/pyarray-simplenewfromdata

File: Framework/PythonInterface/core/src/Converters/WrapWithNDArray.cpp [hunk 1]
```diff
@@ -17,6 +17,20 @@
...
+namespace {
+
+/**
+  Destructor for a capsule object being passed to Python. This helps release
+  memory of arrays passed to Python.
+  See: https://stackoverflow.com/questions/52731884/pyarray-simplenewfromdata
+*/
+void capsule_cleanup(PyObject *capsule) {
+  void *memory = PyCapsule_GetPointer(capsule, NULL);
+  delete[] memory;
```
Comment (AndreiSavici) [inline Framework/PythonInterface/core/src/Converters/WrapWithNDArray.cpp]: This might help you write a "clean" cleanup method :)
https://stackoverflow.com/questions/39305286/destroying-a-pycapsule-object?rq=1

**Comment by AndreiSavici** [comment]
I am not able to reproduce the original issue on master (running Ububtu 18.04, python3), so I cannot test if this is a fix

**Review by martyngigg — APPROVED** [review]
I think this has been through enough eyes. For me it fixes the segfault and is now ~30% faster than the original code.
