### PR TITLE
Fix bad_alloc in spectrum viewer when a workspace contains inf values

### LINKED ISSUE #19569: Using spectrum viewer with a workspace with a single inf value results in bad_alloc
### Expected behavior
Spectrum viewer should be able to handle special values such as `nan`s and `infs`.

### Actual behavior
A workspace with a single `inf` created by the following script:
```python
import numpy

ws = LoadEmptyInstrument(InstrumentName='IN4')
ws.dataY(1)[0] = numpy.inf
```
will result in `bad_alloc` when the mouse pointer hits the single `inf` bin in spectrum viewer.

### Platforms affected

All

### PR DESCRIPTION
**Pull request by soininen**
This PR fixes a bug in spectrum viewer which caused `bad_alloc` if a workspace contained `inf` values. The problem seems to stem from QwtPlots inability to handle infinities in axis scaling.

**To test:**

Before applying these changes, viewing the workspace created by the following script would crash spectrum viewer:
```python
import numpy

ws = LoadEmptyInstrument(InstrumentName='IN4')
ws.dataY(1)[0] = numpy.inf
```

Please also test that other arbitrary combinations of special values do not crash the viewer after applying the changes.

Fixes #19569.

*Release notes were updated accordingly.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: MantidQt/SpectrumViewer/src/GraphDisplay.cpp [hunk 1]
```diff
@@ -131,15 +131,33 @@ void GraphDisplay::clear() {
  */
 void GraphDisplay::setRangeScale(double rangeScale) {
   m_rangeScale = rangeScale;
+  auto validateMinMax = [](double &min, double &max) {
+    if (std::isinf(min)) {
+      min = std::copysign(std::numeric_limits<double>::max(), min);
```
Comment (quantumsteve) [inline MantidQt/SpectrumViewer/src/GraphDisplay.cpp]: missing `#include <cmath>`

**Review by quantumsteve — CHANGES_REQUESTED** [review]
Code changes work as described and avoid an exception being thrown. I added a few notes about potential improvements.

**Review by quantumsteve — APPROVED** [review]

**Comment by quantumsteve** [comment]
:shipit:
