### PR TITLE
PDFFourierTransform2: Allow setting minimum limit on output

### LINKED ISSUE #39975: RMin not respected in PDFFourierTransform
**Describe the bug**

**To Reproduce**
(1) Run this script with this file
[s_of_q_minus_one_merged.nxs.txt](https://github.com/user-attachments/files/19755787/s_of_q_minus_one_merged.nxs.txt)

```
# import mantid algorithms, numpy and matplotlib

from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np


ws_sqm1_merged = LoadNexus(r"C:/Users/xhg73778/Documents/POLARIS/s_of_q_minus_one_merged.nxs")

ws_gr_merged = PDFFourierTransform(InputWorkspace=ws_sqm1_merged, SofQType='S(Q)-1', PDFType='g(r)', 
                                   DeltaR=None, RMin=1, RMax=None, Filter=True)          
```

**Expected behavior**
`RMin` would be respected

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: [e.g. Windows, RHEL 7, Ubuntu, macOS]
 - OS Version:
 - Mantid Version [e.g. 6.0.0]

**Additional context**

### PR DESCRIPTION
**Pull request by samtygier-stfc**
### Description of work

For forwards mode allow setting Rmin
For backwards mode allow setting Qmin

Uses both outMax and outMin when creating output workspace and bin edges

`r_lims` param to POLARIS `generate_ts_pdf()` gets passed through to `PDFFourierTransform` already.

Closes #39975 

### To test:

Use the file from #39975
```
ws_sqm1_merged = LoadNexus("/home/sam/mantid-data/POLARIS/s_of_q_minus_one_merged.nxs")

ws_gr =       PDFFourierTransform(InputWorkspace=ws_sqm1_merged, SofQType='S(Q)-1', PDFType='g(r)', DeltaR=0.05, RMin=None, RMax=None, Filter=True)
ws_gr_rmin = PDFFourierTransform(InputWorkspace=ws_sqm1_merged, SofQType='S(Q)-1', PDFType='g(r)', DeltaR=0.05, RMin=0.5,  RMax=None, Filter=True)
ws_gr_rmin_max = PDFFourierTransform(InputWorkspace=ws_sqm1_merged, SofQType='S(Q)-1', PDFType='g(r)', DeltaR=0.05, RMin=2,  RMax=10, Filter=True)

fig, axes = plt.subplots(1, 1, subplot_kw={'projection': 'mantid'})

axes.plot(ws_gr, color='red', marker='x', label='ws_gr', wkspIndex=0)
axes.plot(ws_gr_rmin, color='blue', marker='+', label='ws_gr_rmin', wkspIndex=0)
axes.plot(ws_gr_rmin_max, color='green', marker='o', label='ws_gr_rmin_max', wkspIndex=0)
plt.legend()
plt.show()
```
The script plots with 3 different limits in R. If you zoom in to the plot the 3 outputs have the same curve, but are truncated to the limits.

image

---

### Reviewer

**Your comments will be used as part of the gatekeeper process.** Comment clearly on what you have checked and tested during your review. Provide an audit trail for any changes requested.

As per the [review guidelines](http://developer.mantidproject.org/ReviewingAPullRequest.html):

- Is the code of an acceptable quality? ([Code standards](http://developer.mantidproject.org/Standards/)/[GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html))
- Has a thorough functional test been performed? Do the changes handle unexpected input/situations?
- Are appropriately scoped unit and/or system tests provided?
- Do the release notes conform to the [guidelines](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html) and describe the changes appropriately?
- Has the relevant (user and developer) documentation been added/updated?
- If the PR author isn’t in the `mantid-developers` or `mantid-contributors` teams, add a review comment `rerun ci` to authorize/rerun the CI

### Gatekeeper

As per the [gatekeeping guidelines](https://developer.mantidproject.org/Gatekeeping.html):

- Has a thorough first line review been conducted, including functional testing?
- At a high-level, is the code quality sufficient?
- Are the base, milestone and labels correct?

### CODE REVIEW

File: Framework/Algorithms/src/PDFFourierTransform2.cpp [hunk 1]
```diff
@@ -455,11 +454,15 @@ void PDFFourierTransform2::exec() {
...
     inMax = getProperty("Rmax");
     outDelta = getProperty("DeltaQ");
+    outMin = getProperty("Qmin");
     outMax = getProperty("Qmax");
     if (isEmpty(outMax)) {
       outMax = 40;
     }
   }
+  if (isEmpty(outMin)) {
+    outMin = 0;
```
Comment (RichardWaiteSTFC) [inline Framework/Algorithms/src/PDFFourierTransform2.cpp:464]: Feels like this should be explicitly 0 in the default value when the property is declared (same for `outMax`) - do you know of a reason why it was done this way?

File: docs/source/release/v6.15.0/Diffraction/Powder/New_features/39975.rst [hunk 2]
```diff
@@ -0,0 +1 @@
+- Implement minimum range limit for :ref:`algm-PDFFourierTransform` algorithm, e.g. Rmin in forwards mode and Qmin in backwards mode.
```
Comment (RichardWaiteSTFC) [inline docs/source/release/v6.15.0/Diffraction/Powder/New_features/39975.rst]: Minor suggestion
```suggestion
- Implement minimum range limit for :ref:`algm-PDFFourierTransform` algorithm, e.g. ``Rmin`` for ``Direction="Forward"``  and ``Qmin`` for ``Direction="Backward"``.
```

**Review by RichardWaiteSTFC — CHANGES_REQUESTED** [review]
Thanks for this - just some minor suggestions!

File: Framework/Algorithms/src/PDFFourierTransform2.cpp (hunk 1 above)
Comment (samtygier-stfc) [reply Framework/Algorithms/src/PDFFourierTransform2.cpp:464]: I don't think we can set a default for `outMin` because it could either be coming from `Qmin` or `Rmin` (the other gets used for inMin).

We could have `Qmin` and `Rmin` default to zero. Currently if `inMin` gets used in `determineMinIndex`, if it is empty or less than `X.front()` it get set to `X.front()`. Assuming the X values of the input are never less than 0, then this should be ok.

Comment (RichardWaiteSTFC) [reply Framework/Algorithms/src/PDFFourierTransform2.cpp:464]: OK, but it sounds like a default `RMin`/`QMin` would be slightly mis-leading anyway because it would never actually use `0` for real data.

Comment (samtygier-stfc) [reply Framework/Algorithms/src/PDFFourierTransform2.cpp:464]: ok. I have pushed again, with just the doc change

**Review by RichardWaiteSTFC — APPROVED** [review]
Looks good and change covered by unit tests for both directions thanks!
I also see cropped spectrum matching well - so bin edges are being handled correctly
image
So happy to approve!

**Comment by sf1919** [comment]
@mantidproject/gatekeepers Please review
