### PR TITLE
Indirect - ConvFit FABADA FixTie is not working

### LINKED ISSUE #23544: Indirect - FABADA Flat Background A0 Tie not working in ConvFit
### Expected behavior
When you `Fix` A0 (under Flat Background) in the FitPropertyBrowser, the value should remain fixed after minimization using FABADA.

### Actual behavior
A0 doesn't stay fixed

### Steps to reproduce the behavior
1. `Interfaces`->`Indirect`->`Data Analysis` -> `ConvFit` Tab
2. Load in the files below
3. In the Function browser:
- `One Lorentzian` for Fit Type
- `Delta Function` should be ticked
- `FlatBackground` as the background
- `Tie` Delta.Centre to Lor.PeakCentre (this tests tie)
- `Fix` FlatBgd.A0=0, it appears as Tie=0 (this tests Fix)
- `Constrain` both bounds for Delta.Height 0.0 to 0.01 (this tests constrain)
- `FABADA` for minimizer
4. Set `Fit Spectra` string to 0 in order to speed up the process
5. Click `Run` and wait a while
6. The FlatBgd.A0 Tie doesn't remain fixed 

**Files**
[irs26173_graphite002_res.zip](https://github.com/mantidproject/mantid/files/2424131/irs26173_graphite002_res.zip)
[irs26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2424132/irs26176_graphite002_red.zip)

### Platforms affected
All

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR solves a problem where a fix (tie) on a parameter when using the FABADA minimizer does not remain fixed.

**To test:**
1. `Interfaces`->`Indirect`->`Data Analysis` -> `ConvFit` Tab
2. Load in the files below
3. In the Function browser:
- `One Lorentzian` for Fit Type
- `Delta Function` should be ticked
- `FlatBackground` as the background
- `Tie` Delta.Centre to Lor.PeakCentre (this tests tie)
- `Fix` FlatBgd.A0=0, it appears as Tie=0 (this tests Fix)
- `Constrain` both bounds for Delta.Height 0.0 to 0.01 (this tests constrain)
- `FABADA` for minimizer
- `Max Iterations` should be around 4000
4. Set `Fit Spectra` string to 0 in order to speed up the process
5. Click `Run` and wait a while
6. The FlatBgd.A0 Tie should remain fixed at zero!

**Files**
[irs26173_graphite002_res.zip](https://github.com/mantidproject/mantid/files/2424131/irs26173_graphite002_res.zip)
[irs26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2424132/irs26176_graphite002_red.zip)

Fixes #23544 

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by LowriJenkins — CHANGES_REQUESTED** [review]
Following the test you've left leads to a failure with this error in the log
 ```Logic Error in execution of algorithm Fit
Too few iterations to perform the Simulated Annealing and/or the posterior chain plus 350 iterations for the burn-in period. Increase MaxIterations property
Error in Fit ChildAlgorithm
Error in execution of algorithm PlotPeakByLogValue:
Fit child algorithm failed: __ConvolutionFitSequential_ws1
Error in execution of algorithm ConvolutionFitSequential
Fit child algorithm failed: __ConvolutionFitSequential_ws1
```

**Review by LowriJenkins — DISMISSED** [review]

File: Framework/CurveFitting/src/FuncMinimizers/FABADAMinimizer.cpp [hunk 1]
```diff
@@ -467,6 +467,10 @@ void FABADAMinimizer::tieApplication(const size_t &parameterIndex,
     m_fitFunction->setParameter(parameterIndex, newValue);
   }
 
+  // Apply fix to the parameter if it is fixed
+  if (m_fitFunction->isFixed(parameterIndex))
+    applyFix(parameterIndex, newParameters);
```
Comment (mantid-roman) [inline Framework/CurveFitting/src/FuncMinimizers/FABADAMinimizer.cpp]: Why cannot a fixed parameter be skipped?

**Comment by SpencerHowells** [comment]
@mantid-roman @robertapplin I discovered that when using the gui if I set a parameter as Fixed it sets it as a Tie but carries on fitting it.

File: Framework/CurveFitting/src/FuncMinimizers/FABADAMinimizer.cpp (hunk 1 above)
Comment (robertapplin) [reply Framework/CurveFitting/src/FuncMinimizers/FABADAMinimizer.cpp]: I think I agree, skipping fixed parameters may be a better way of doing this! 👍

**Review by mantid-roman — APPROVED** [review]
