### PR TITLE
Remove completed Algorithms from AlgorithmManager managed algorithms

### LINKED ISSUE #28093: AlgorithmManager: Only retain running algorithms
The key `algorithms.retained` in the ConfigService is used to control how many `AlgorithmProxy` objects are retained by the `AlgorithmManager`. This behaviour is no longer required and the `AlgorithmManager` should only need to retain a handle to running algorithms for cases such as backgound LiveData algorithms.

The first step in this issue is to only have `AlgorithmManager` retain running algorithms. A bonus step would be to remove the need for the `AlgorithmProxy` class completely but this can be treated as a second-order issue.

### LINKED ISSUE #28143: Crash on loading file and running script executing lots of algs v.fast
**Original reporter:** 
very similar to: refs #27594 

### Expected behavior
Should be able to run a script and load a file at the same time
### Actual behavior
Workbench and plot crash
### Steps to reproduce the behavior
run this script (should take around 13 seconds, increase the for loop if you need longer!)
while its running load a file such as HRP39182.RAW or GEM40979.raw (should be anything!)
(in MantidPlot you may need to get the load dialog ready before starting the script)
[Append_spectra_issues.zip](https://github.com/mantidproject/mantid/files/4266956/Append_spectra_issues.zip)
### Platforms affected
Workbench and Plot Nightly before 5.0 release 4.2.20200225.1733

### PR DESCRIPTION
**Pull request by NickDraper**
**Description of work.**

Removes any finished algorithms from the AlgorithmManager list on the creation of a new algorithm.

**To test:**
1. Start several tabs
1. in each run some code a bit like this
   ``` python
   for i in range(600):
      Pause(0.1)
   ```
1. while running the tabs, run an algorithm from the Algorithm toolbox as well
1. Run StartLiveData as well
1. Just get lots of things running at the same time ...  We are testing we do not have any multithreading issues
1. #28143 has a good test case of a script that runs lots of algs v.fast, try to load another file while the script is running. At the moment the load alg can fall off the end of the retained algs list while it is running and then is v prone to crashes.

Fixes #28093
Fixes #28143 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/API/src/AlgorithmManager.cpp [hunk 1]
```diff
@@ -253,6 +246,28 @@ void AlgorithmManagerImpl::cancelAll() {
   }
 }
 
+/// Removes all of the finished algorithms
+/// this does not lock the mutex as the locking is already assumed to be in
+/// place
+size_t AlgorithmManagerImpl::removeFinishedAlgorithms() {
+  std::vector<IAlgorithm_const_sptr> theCompletedInstances;
+  std::copy_if(
```
Comment (DavidFair) [inline Framework/API/src/AlgorithmManager.cpp]: Since we don't keep the elements this entire block can be replaced with

```
  size_t sizeBefore = m_managed_algs.size();

  m_managed_algs.erase(std::remove_if(
      m_managed_algs.begin(), m_managed_algs.end(), [](const auto &algorithm) {
        return (algorithm->executionState() == ExecutionState::Finished);
      }));
  size_t sizeAfter = m_managed_algs.size();

  return sizeBefore - sizeAfter;
```

File: Framework/API/src/AlgorithmProxy.cpp [hunk 2]
```diff
@@ -108,21 +109,31 @@ bool AlgorithmProxy::executeAsyncImpl(const Poco::Void &dummy) {
     throw;
   }
   stopped();
-  return m_isExecuted;
+  return (resultState() == ResultState::Success);
```
Comment (DavidFair) [inline Framework/API/src/AlgorithmProxy.cpp]: Should this should return `ExecutionState == Finished`?

File: Framework/API/src/AlgorithmProxy.cpp [hunk 3]
```diff
@@ -108,21 +109,31 @@ bool AlgorithmProxy::executeAsyncImpl(const Poco::Void &dummy) {
...
+  return m_executionState;
+}
+
+/// Gets the current result State
+ResultState AlgorithmProxy::resultState() const { return m_resultState; }
+
 /// True if the algorithm is running.
 bool AlgorithmProxy::isRunning() const {
-  return m_alg ? m_alg->isRunning() : false;
+  return m_alg ? (m_alg->executionState() == ExecutionState::Running) : false;
```
Comment (DavidFair) [inline Framework/API/src/AlgorithmProxy.cpp]: ^ Esp as this returns if we are running

File: Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/SimpleShapeMonteCarloAbsorptionTest.py [hunk 4]
```diff
@@ -13,15 +13,16 @@
 
 
 class SimpleShapeMonteCarloAbsorptionTest(unittest.TestCase):
-    def setUp(self):
-        red_ws = Load('irs26176_graphite002_red.nxs')
-        red_ws = ConvertUnits(
-            InputWorkspace=red_ws,
+    @classmethod
+    def setUpClass(self):
+        __red_ws = Load('irs26176_graphite002_red.nxs')
```
Comment (DavidFair) [inline Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/SimpleShapeMonteCarloAbsorptionTest.py]: Is there a reason were using anonymous naming here, this is usually indicative of a code smell?

File: MantidPlot/CMakeLists.txt [hunk 5]
```diff
@@ -823,6 +823,10 @@ target_include_directories(MantidPlot PRIVATE
 target_compile_options( MantidPlot PRIVATE
   $<$<AND:$<CXX_COMPILER_ID:GNU>,$<VERSION_GREATER_EQUAL:$<CXX_COMPILER_VERSION>,8.0>>:-Wno-cast-function-type> )
 
+set (BOOST_LIBRARIES_MANTIDPLOT ${Boost_LIBRARIES})
+find_package(BoostPython REQUIRED)
```
Comment (DavidFair) [inline MantidPlot/CMakeLists.txt]: I've noticed a number of CMakelists.txt are doing this in Mantid, including our Framework/PythonInterface.

As it's required for the entire project at this point could you move this to `/CMakeLists.txt` with our other mandatory deps, I'll create a maintenance issue to clean up this find_package everywhere else.

After we can drop everything here....

File: MantidPlot/CMakeLists.txt [hunk 6]
```diff
@@ -835,7 +839,7 @@ target_link_libraries(MantidPlot
                       MantidQtWidgetsInstrumentViewQt4
                       MantidQtWidgetsSliceViewerQt4
                       MantidQtWidgetsSpectrumViewerQt4
-                      ${Boost_LIBRARIES}
+                      ${BOOST_LIBRARIES_MANTIDPLOT}
```
Comment (DavidFair) [inline MantidPlot/CMakeLists.txt]: And turn this into `${Boost_LIBRARIES}`

**Review by DavidFair — CHANGES_REQUESTED** [review]

File: Framework/API/inc/MantidAPI/IAlgorithm.h [hunk 7]
```diff
@@ -28,6 +28,11 @@ namespace API {
  */
 using AlgorithmID = void *;
 
+/// The current state of the algorithm object
+enum class ExecutionState { Uninitialized, Initialized, Running, Finished };
+/// The validity of the results of the algorithm object
+enum class ResultState { NotFinished, Failed, Success };
```
[the remark this answers is not in the document]
Comment (NickDraper) [reply Framework/API/inc/MantidAPI/IAlgorithm.h]: Yes, but one is the state of the algorithm, and the other is the state of the results from that algorithm.  I agree that if it is uninitialised it will always be not finished, but it can also be not finished if the algorithm has been initialised, or is running but not complete yet.  It comes down to the question someone is asking of the algorithm.  Sometimes you want the detaild state of the algorithm, and sometimes you just want to see what the state of the result iss.

File: Framework/API/inc/MantidAPI/Algorithm.h [hunk 8]
```diff
@@ -454,14 +461,14 @@ class MANTID_API_DLL Algorithm : public IAlgorithm,
   mutable std::unique_ptr<Poco::NObserver<Algorithm, ProgressNotification>>
       m_progressObserver;
 
-  bool m_isInitialized;         ///< Algorithm has been initialized flag
-  bool m_isExecuted;            ///< Algorithm is executed flag
+  std::atomic<ExecutionState> m_executionState; ///< the current execution state
+  std::atomic<ResultState> m_resultState;       ///< the current result State
+  bool m_isExecuted;                            ///< Algorithm is executed flag
```
[the remark this answers is not in the document]
Comment (NickDraper) [reply Framework/API/inc/MantidAPI/Algorithm.h]: Done as part of the review of the preceding PR, now merged into this one.

File: Framework/API/src/Algorithm.cpp [hunk 9]
```diff
@@ -114,24 +115,37 @@ Algorithm::~Algorithm() {}
 //===================================
 //=============================================================================================
 
+/// Gets the current execution state
+ExecutionState Algorithm::executionState() const { return m_executionState; }
+
+/// Sets the current execution state
+void Algorithm::setExecutionState(const ExecutionState state) {
+  m_executionState = state;
```
[the remark this answers is not in the document]
Comment (NickDraper) [reply Framework/API/src/Algorithm.cpp]: Hmm.  I see what you are getting at, but in some ways this feels like a side effect.  This is not a solid state model in that it is possible to externally move back a state from running to say initialised, but you should not really do that, and the base algorithm class does not do that.
I left the methods as protected in case someone in a specialized algorithm needs to control something in more detail, but I can't think of an example at the moment that would need it.
I feel if you are fiddling with the state within your algorithm expecting you to set the ResultState as well is not too much to ask.

File: Framework/API/src/Algorithm.cpp [hunk 10]
```diff
@@ -114,24 +115,37 @@ Algorithm::~Algorithm() {}
...
-/** Set the executed flag to the specified state
-// Public in Gaudi - don't know why and will leave here unless we find a reason
-otherwise
-//     Also don't know reason for different return type and argument.
-@param state :: New executed state
-*/
-void Algorithm::setExecuted(bool state) { m_isExecuted = state; }
+bool Algorithm::isExecuted() const {
+  return ((executionState() == ExecutionState::Finished) &&
+          (resultState() == ResultState::Success));
```
[the remark this answers is not in the document]
Comment (NickDraper) [reply Framework/API/src/Algorithm.cpp]: So this is associated with the answer above, we check both states as both states define the algorithm.

I see your example about the booleans, but that is how they work at the moment, so thaat is Executed is really isExecutedSuccessfully.  The whole reason for improving the state reporting was to enable us to determine when an algorithm has finished but failed.  However the impact of changing what those methods mean would be very large and out of the scope of this work.

File: Framework/API/src/AlgorithmManager.cpp [hunk 11]
```diff
@@ -82,6 +82,11 @@ IAlgorithm_sptr AlgorithmManagerImpl::create(const std::string &algName,
...
       alg = unmanagedAlg;
 
+    auto count = removeFinishedAlgorithms();
+    g_log.debug()
+        << count
+        << " Finished algorithms removed from the managed algorithms list. "
+        << m_managed_algs.size() << " remaining.\n";
     // If this takes us beyond the maximum size, then remove the oldest one(s)
     while (m_managed_algs.size() >=
            static_cast<std::deque<IAlgorithm_sptr>::size_type>(m_max_no_algs)) {
```
[the remark this answers is not in the document]
Comment (NickDraper) [reply Framework/API/src/AlgorithmManager.cpp]: I agree I'll remove it

File: Framework/API/src/AlgorithmProxy.cpp (hunk 2 above)
Comment (NickDraper) [reply Framework/API/src/AlgorithmProxy.cpp]: Done as part of the review of the preceding PR, now merged into this one.

File: Framework/API/src/AlgorithmManager.cpp (hunk 1 above)
Comment (NickDraper) [reply Framework/API/src/AlgorithmManager.cpp]: Yes, I'll change that

File: Framework/API/src/AlgorithmProxy.cpp (hunk 3 above)
Comment (NickDraper) [reply Framework/API/src/AlgorithmProxy.cpp]: Done as part of the review of the preceding PR, now merged into this one.

Comment (NickDraper) [reply Framework/API/src/AlgorithmProxy.cpp]: And the whole class is being removed in the next PR that this is blocking

File: Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/SimpleShapeMonteCarloAbsorptionTest.py (hunk 4 above)
Comment (NickDraper) [reply Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/SimpleShapeMonteCarloAbsorptionTest.py]: Nope I'll fix that

File: Framework/API/src/AlgorithmManager.cpp (hunk 1 above)
Comment (NickDraper) [reply Framework/API/src/AlgorithmManager.cpp]: Actually I'm going to revert to the previous one as the suggested code caused about 600 unit tests to segfault.

File: MantidPlot/CMakeLists.txt (hunk 5 above)
Comment (NickDraper) [reply MantidPlot/CMakeLists.txt]: So I tried this and got a collection of linker errors, let's make dealing with this something for another PR

File: MantidPlot/CMakeLists.txt (hunk 6 above)
Comment (NickDraper) [reply MantidPlot/CMakeLists.txt]: as above

File: Framework/API/src/AlgorithmManager.cpp (hunk 1 above)
Comment (DavidFair) [reply Framework/API/src/AlgorithmManager.cpp]: Okay, they must be holding onto iterators that are invalidated by the erase operation, but not when we copy

File: MantidPlot/CMakeLists.txt (hunk 5 above)
Comment (martyngigg) [reply MantidPlot/CMakeLists.txt]: BoostPython is still only required by a subset of libraries: The PythonInterface ones, `MantidPlot` and `mantidqt`. If we move it can we make sure we still keep the linking to only those libraries that are currently using it? I think what we'll find is that `find_package(BoostPython REQUIRED)` clears and overwrites `Boost_LIBRARIES` so that's where the linker errors come from. We'll need to find the standard boost libraries, cache the value, call `find_package(BoostPython REQUIRED)`, set a new `BoostPython_LIBRARIES` variable to its result and then restore `Boost_LIBRARIES`

Comment (DavidFair) [reply MantidPlot/CMakeLists.txt]: >If we move it can we make sure we still keep the linking to only those libraries that are currently using it?

My naive assumption is yes, provided we don't add it as a global library and do it on a target by target basis we will only link it to the targets that need it.

An advantage of this a single `find_package` is avoiding people getting it wrong (such as forgetting to restore `Boost_LIBRARIES`) and constantly re-searching for it.

> I think what we'll find is that find_package(BoostPython REQUIRED) clears and overwrites Boost_LIBRARIES so that's where the linker errors come from. 

Ahh, I was scratching my head on this one. I've opened #28431 to do this work in a future maintenance period. But I think it's fine as in for this PR

**Review by DavidFair — APPROVED** [review]
This works correctly, fixes some subtitles with how many algorithms we can having running at once and simplifies the code

I also kept an eye on the memory usage and we aren't leaking memory and as each Algorithm object is fairly lightweight so I can't see the fact we no longer have a cap causing problems. Obviously with the caveat that if people run say two Event* algs they run the real risk of the actual algs running out of memory
