### PR TITLE
Fixed crash in indirect data analysis

### LINKED ISSUE #35427: Indirect/Direct Data Analysis remove data from table not working correctly
**Original reporter:** Unkown user via error reporter

**Describe the bug**
In the "Direct/Indirect Data Analysis" interfaces (this applies to all tabs), using the "Remove" button will remove too many **rows** if multiple **columns** are selected. It will attempt to remove as many rows as the number of selected cells. For example, if there are 10 rows in the table, and the user has selected 11 cells, as in the screenshot example below, it will try to remove 11 rows and crash.

**To Reproduce**
1. Open the Indirect Data Analysis interface
2. Go to the ConvFit tab, for example
3. Click the "Add Workspace" button
4. Choose some data by clicknig the browse buttons
5. Tick the "All Spectra" box and Click "Add"
6. Select some cells in the table, but not just a single column, e.g. see the screenshot below
7. Click "Remove", it will remove too many items, and will crash if it tries to remove more items than exist in the table.

**Expected behavior**
It should only remove **rows** that are selected. For example, in the screenshot below it should only remove WS indices 0-4.

**Screenshots**
image

**Platform/Version (please complete the following information):**
 - OS: Probably all
 - Mantid Version 6.6.0 and probably older

### PR DESCRIPTION
**Pull request by AnthonyLim23**
This fixes a bug that caused the indirect data analysis interfaces to crash when multiple cells were selected, such that the total number of selected cells exceeded the number of rows.

I have not included a unit test because it involves significant amounts of Qt. Since the function takes a `QModelIndexList` we would need to create `QModelIndex`'s. However, these need a `QAbstractModel`. Which in turn needs several virtual functions. 

**To test:**
Open indirect -> data analysis
Go to the conv fit tab (any tab will work if you have data)
Click Add Workspace
Select some data for the workspace and resolution
For workspace indices, just load (any) 6 spectra

Select the `Resolution` cells for two of the spectra (just 2 cells will be highlighted)
Click Remove, those 2 rows should be gone (check by looking at the WS index)

Highlight the `Resolution` and `WS Index` cells for 3 spectra (6 highlighted cells in total)
Click Remove - this used to crash
One row should be left (the one you did not highlight)

Fixes #35427 

In release notes

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by MialLewis — DISMISSED** [review]
Code looks good, bug is fixed. I'll take your word that a unit test would be a disproportionate amount of work!

File: qt/scientific_interfaces/Indirect/IndirectFitDataPresenter.h [hunk 1]
```diff
@@ -39,6 +39,8 @@ class MANTIDQT_INDIRECT_DLL IndirectFitDataPresenter : public QObject, public An
   void setStartX(double startX, WorkspaceID workspaceID, WorkspaceIndex spectrum);
   void setEndX(double startX, WorkspaceID workspaceID);
   void setEndX(double startX, WorkspaceID workspaceID, WorkspaceIndex spectrum);
+  std::map<int, QModelIndex> getUniqueIndices(const QModelIndexList &selectedIndices);
```
Comment (thomashampson) [inline qt/scientific_interfaces/Indirect/IndirectFitDataPresenter.h:42]: Function can be private if it's not accessed by the test class any more.

**Review by thomashampson — CHANGES_REQUESTED** [review]

**Review by thomashampson — APPROVED** [review]
