### PR TITLE
Correct error on peak intensity in IntegrateEllipsoids

### LINKED ISSUE #27446: Error estimates on integrated values (integrate ellipsoids)
### Expected behavior
When integrating a single-crystal peak it is possible to estimate the background from a shell at larger radius.

### Actual behavior
There was concern that the process of removing a background didn't evaluate the error on the integrated count correctly (this has been fixed for spherical integration - though I can't find the issue) but may not have been done correctly. 

This might be related to removing the top 1% of counts in the background implemented in #13509 - the error calculated here should be checked. In addition such an option used on data from an instrument with low background (e.g. WISH, ISIS) may lead to an underestimation of the background.

### Steps to reproduce the behavior
Need to talk to Pas to ask for some calibration data to refine to check the errors are correct (i.e. that get a reasonable R-value from refinement).

### PR DESCRIPTION
**Pull request by RichardWaiteSTFC**
**Description of work.**
Previously IntegrateEllipsoids calculated the error on the integrated intensity assuming that for each event the associated error was sqrt(counts). In general this is not true (e.g. normalised to a monitor) and this has been corrected. This fix also applies to IntegrateEllipsoidsTwoStep algorithm.

The ratio of integrated intensity/error was compared to another peak integration IntegratePeaksMD by hard-coding a spherical integration region of the same radius (and same background shell radii). The calculated error now agrees with the error from IntegratePeaksMD.

image

**To test:**

(1) Integrate a PeaksWorkspace using IntegreateEllipsoids and IntegrateEllipspodsTwoStep - is there an error? Can follow script here https://docs.mantidproject.org/nightly/algorithms/IntegrateEllipsoids-v1.html

Fixes #27446 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by martyngigg — CHANGES_REQUESTED** [review]
Before commenting on the file changes I wonder if we could tidy up the commits a bit? There are a few commits that just seem to be testing out things and probably don't belong in the history. The issue with having commits like these is that they disrupt the change log of particular files when viewing them and it can then be hard to know, when looking back, if a particular set of testing changes was fully reverted. 

In this case I think we can squash a large amount of them together so we can have just the commits with *real* changes in them.

File: Framework/MDAlgorithms/src/Integrate3DEvents.cpp [hunk 1]
```diff
@@ -607,12 +614,16 @@ double Integrate3DEvents::numInEllipsoidBkg(
   auto endIndex = eventVec.size();
   if (useOnePercentBackgroundCorrection) {
     // Remove top 1% of background
-    std::sort(eventVec.begin(), eventVec.end());
+    std::sort(eventVec.begin(), eventVec.end(),
+              [](std::pair<double, double> a, std::pair<double, double> b) {
```
Comment (martyngigg) [inline Framework/MDAlgorithms/src/Integrate3DEvents.cpp]: Good use of lambda. Minor style point: I would expect this to have each parameter as `const std::pair<double, double> &a, const std::pair<double, double> &b` to avoid copying the pair as it sorts and calls the lambda.

File: Framework/MDAlgorithms/test/Integrate3DEventsTest.h [hunk 2]
```diff
@@ -39,8 +39,10 @@ class Integrate3DEventsTest : public CxxTest::TestSuite {
     V3D peak_1(10, 0, 0);
```
Comment (martyngigg) [inline Framework/MDAlgorithms/test/Integrate3DEventsTest.h]: Is it possible to add some test assertions that the errors are now as expected. This will help avoid future regressions in the code.

**Review by martyngigg — CHANGES_REQUESTED** [review]
Generally good and fixes the issue with the error calculation. Just a couple of comments.

File: Framework/MDAlgorithms/test/Integrate3DEventsTest.h [hunk 3]
```diff
@@ -527,7 +540,10 @@ class Integrate3DEventsTest : public CxxTest::TestSuite {
     for (double i = lower; i < upper; i += step) {
       for (double j = lower; j < upper; j += step) {
         for (double k = lower; k < upper; k += step) {
-          event_Qs.emplace_back(counts + d(gen), V3D(i, j, k));
+          double cts = counts + d(gen);
+          event_Qs.emplace_back(
+              std::make_pair(cts, cts),
+              V3D(i, j, k)); // is it right to add 1. error here?
```
Comment (martyngigg) [inline Framework/MDAlgorithms/test/Integrate3DEventsTest.h]: Could you help me understand this comment? It feels like a question to be answered and then remove from the code?

**Review by martyngigg — DISMISSED** [review]
This looks good now :+1:

**Comment by martyngigg** [comment]
Just some Doxygen warnings to take care of.

**Review by martyngigg — APPROVED** [review]
