### PR TITLE
Fix a bounding box bug in the instrument viewer

### LINKED ISSUE #30832: Setting the bounding box in the instrument viewer does not work
### Expected behavior
When setting the bounding box of a shape manually in the instrument viewer, the new shape should take this new bounding box.
### Actual behavior
When setting the ``top`` or ``bottom`` field, both take the same value and the shape becomes a line.

### Steps to reproduce the behavior
- Open the instrument viewer on some data
- Go to the ``Draw`` tab
- Draw a shape (not a sector)
- In the editable fields on the left, change the value of  ``top`` or ``bottom``
- Validate and hover over the instrument view to update it

### PR DESCRIPTION
**Pull request by MathieuTillet**
**Description of work.**
This fixes the bug that prevented the user from setting the ``top`` and ``bottom`` value of the bounding box of a shape in the instrument viewer.
Note that the user still cannot set these values for the sector shape, due to how it is designed.

**To test:**
- Open the instrument viewer on some data
- Go to the ``Draw`` tab
- Draw a shape (not a sector)
- In the editable fields on the left, change the value of ``top`` or ``bottom``
- Validate and hover over the instrument view to update it, and check that the shape has been correctly changed, along with the bounding box.

- Change the value of top to be less than bottom (and so on), and check that the values are swapped instantly so they stay coherent with their respective label.
- Also check the view is updated on finishing the edition of the field, and no longer requires hovering above the instrument view for that.

Fixes #30832 #30816 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/widgets/instrumentview/src/InstrumentWidgetMaskTab.cpp [hunk 1]
```diff
@@ -625,9 +625,9 @@ void InstrumentWidgetMaskTab::shapeChanged() {
       false; // this prevents resetting shape properties by doubleChanged(...)
   RectF rect = m_instrWidget->getSurface()->getCurrentBoundingRect();
   m_doubleManager->setValue(m_left, rect.x0());
-  m_doubleManager->setValue(m_top, rect.y1());
+  m_doubleManager->setValue(m_top, rect.y0());
   m_doubleManager->setValue(m_right, rect.x1());
-  m_doubleManager->setValue(m_bottom, rect.y0());
+  m_doubleManager->setValue(m_bottom, rect.y1());
```
Comment (thomashampson) [inline qt/widgets/instrumentview/src/InstrumentWidgetMaskTab.cpp:630]: This resolves the problem, but there is another issue that can be resolved here too. Currently the "top", "bottom", "left" and "right" labels are only correct if I draw a square starting with the bottom left corner and drag up to the right. Drawing a square in any other direction results in either the "top" and "bottom" or "left" and "right" being switchted. The same is true if I move one of the corners through the shape so that the left side becomes the right, for example. The following suggestion fixes that:
```
  m_doubleManager->setValue(m_left, std::min(rect.x0(), rect.x1()));
  m_doubleManager->setValue(m_top, std::max(rect.y0(), rect.y1()));
  m_doubleManager->setValue(m_right, std::max(rect.x0(), rect.x1()));
  m_doubleManager->setValue(m_bottom, std::min(rect.y0(), rect.y1()));
```

But this only works properly if the code around line 735 is changed from this:
```
QRectF rect(
        QPointF(m_doubleManager->value(m_left), m_doubleManager->value(m_top)),
        QPointF(m_doubleManager->value(m_right),
m_doubleManager->value(m_bottom)));
```
to this:
```
    double x0 = std::min(m_doubleManager->value(m_left),
                         m_doubleManager->value(m_right));
    double x1 = std::max(m_doubleManager->value(m_left),
                         m_doubleManager->value(m_right));
    double y0 = std::min(m_doubleManager->value(m_top),
                         m_doubleManager->value(m_bottom));
    double y1 = std::max(m_doubleManager->value(m_top),
                         m_doubleManager->value(m_bottom));
    QRectF rect(QPointF(x0, y0), QPointF(x1, y1));
```
Then the values of top, bottom, left and right always reflect the rectangle on screen. Give it a go and you'll see what I mean.

**Review by thomashampson — CHANGES_REQUESTED** [review]

File: qt/widgets/instrumentview/src/InstrumentWidgetMaskTab.cpp (hunk 1 above)
Comment (MathieuTillet) [reply qt/widgets/instrumentview/src/InstrumentWidgetMaskTab.cpp:630]: I see what you mean, and it would be clearer for the user indeed, but with this code, if the user set the field value of say ``left`` to a greater value than ``right``, then ``right`` and ``left`` will be at the same new value. Do you think this is the most intuitive way, or should the values be swapped instead in this case ?

Comment (thomashampson) [reply qt/widgets/instrumentview/src/InstrumentWidgetMaskTab.cpp:630]: Hmm. If you type a value of `left` greater than `right` and press the Enter key, then it sets them as the same value. I didn't test this before.

If you enter the value and then click somehwere else (and don't hit Enter), then it does as you suggest, it swaps them over - which I think is a good solution.

**Comment by MathieuTillet** [comment]
This solves the original bug and implements the swap between top/bottom and left/right, working correctly this time.

File: qt/widgets/instrumentview/src/InstrumentWidgetMaskTab.cpp [hunk 2]
```diff
@@ -754,10 +764,9 @@ void InstrumentWidgetMaskTab::doubleChanged(QtProperty *prop) {
         m_instrWidget->getSurface()->setCurrentPoint(name, p);
       }
     }
-    // when the user validates the edit of the field, the view is immediatly
-    // updated this way
-    m_instrWidget->updateInstrumentView();
   }
+  // when the user validates the field's edit, the view is immediatly updated
+  m_instrWidget->updateInstrumentView();
```
Comment (thomashampson) [inline qt/widgets/instrumentview/src/InstrumentWidgetMaskTab.cpp:769]: Good idea to move this.

**Review by thomashampson — APPROVED** [review]
Working well now!
