### PR TITLE
Algorithm::doCallProcessGroup() now handles history where previously it's called alogorithms did

### LINKED ISSUE #23304: Project Recovery Doesn't work with renamed group workspaces
### Expected behavior

Renamed workspace group should be reloaded properly with project recovery

### Actual behavior

Project recovery throws an error

### Steps to reproduce the behavior

Run 
```
CreateMDWorkspace(Dimensions=3, Extents='-10,10,-10,10,-10,10', Names='A,B,C', Units='U,U,U', OutputWorkspace='ws_0')  
CreateMDWorkspace(Dimensions=3, Extents='-10,10,-10,10,-10,10', Names='A,B,C', Units='U,U,U', OutputWorkspace='ws_1')  
CreateMDWorkspace(Dimensions=3, Extents='-10,10,-10,10,-10,10', Names='A,B,C', Units='U,U,U', OutputWorkspace='ws_2')  
CreateMDWorkspace(Dimensions=3, Extents='-10,10,-10,10,-10,10', Names='A,B,C', Units='U,U,U', OutputWorkspace='ws_3') 
GroupWorkspaces(InputWorkspaces='ws_0,ws_1,ws_2,ws_3', OutputWorkspace='ws')
RenameWorkspace(InputWorkspace='ws', OutputWorkspace='renamed')
```
* Wait for recovery to save
* Crash Mantid with `Segfault`
* Restart Mantid
* When offered Project Recovery, select Yes

### Platforms affected

All

### PR DESCRIPTION
**Pull request by Pasarus**
**Description of work.**
Changed it so that WorkspaceGroups when passed to an algorithm will depart the history using that WorkspaceGroup instead of the base Workspaces inside the algorithm each time the algorithm is called.

**To test:**
```python
CreateMDWorkspace(Dimensions=3, Extents='-10,10,-10,10,-10,10', Names='A,B,C', Units='U,U,U', OutputWorkspace='ws_0')  
CreateMDWorkspace(Dimensions=3, Extents='-10,10,-10,10,-10,10', Names='A,B,C', Units='U,U,U', OutputWorkspace='ws_1')  
CreateMDWorkspace(Dimensions=3, Extents='-10,10,-10,10,-10,10', Names='A,B,C', Units='U,U,U', OutputWorkspace='ws_2')  
CreateMDWorkspace(Dimensions=3, Extents='-10,10,-10,10,-10,10', Names='A,B,C', Units='U,U,U', OutputWorkspace='ws_3') 
GroupWorkspaces(InputWorkspaces='ws_0,ws_1,ws_2,ws_3', OutputWorkspace='ws')
RenameWorkspace(InputWorkspace='ws', OutputWorkspace='renamed')
```
- Then check the history of renamed_1, _2, _3, _4 and the workspace History should be exactly the same as the script where the input is ws and not ws_0, _1, _2, _3 respectively.

Fixes #23304 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by vreimund — CHANGES_REQUESTED** [review]
This is a really cool change in my opinion.
There seem to be only one line to be removed since copied.
The release notes may read too technical, maybe re-formulate what happens (full group history saved for all items belonging to the group)

It is important to say that with this change, the history of a single work-space within a group will contain the full history of the group (all work-spaces). Thus, replaying the history is now generally possible.

I think the change introduced here is really nice and offers new possibilities for the users, but the existing behavior is not wrong.

It looks like all work-spaces within a group now have the same history. Seems to be some overhead. It would be better (**from a user point of view only**) to have the group history stored for the group workspace (history cannot be selected there, does not exist) and to keep the individual history of each item.

Running the example gives:
MASTER
For i = 1, 2, 3, 4

History of renamed_i is:

CreateMDWorkspace(Dimensions=3, Extents='-10,10,-10,10,-10,10', Names='A,B,C', Units='U,U,U', OutputWorkspace='ws_0')
CreateMDWorkspace(Dimensions=3, Extents='-10,10,-10,10,-10,10', Names='A,B,C', Units='U,U,U', OutputWorkspace='ws_1')
CreateMDWorkspace(Dimensions=3, Extents='-10,10,-10,10,-10,10', Names='A,B,C', Units='U,U,U', OutputWorkspace='ws_2')
CreateMDWorkspace(Dimensions=3, Extents='-10,10,-10,10,-10,10', Names='A,B,C', Units='U,U,U', OutputWorkspace='ws_3')
GroupWorkspaces(InputWorkspaces='ws_0,ws_1,ws_2,ws_3', OutputWorkspace='ws')
**RenameWorkspace(InputWorkspace='ws_(i-1)', OutputWorkspace='renamed_i')**

CHANGE
For i = 1, 2, 3, 4

History of renamed_i is originally executed script:

CreateMDWorkspace(Dimensions=3, Extents='-10,10,-10,10,-10,10', Names='A,B,C', Units='U,U,U', OutputWorkspace='ws_0')
CreateMDWorkspace(Dimensions=3, Extents='-10,10,-10,10,-10,10', Names='A,B,C', Units='U,U,U', OutputWorkspace='ws_1')
CreateMDWorkspace(Dimensions=3, Extents='-10,10,-10,10,-10,10', Names='A,B,C', Units='U,U,U', OutputWorkspace='ws_2')
CreateMDWorkspace(Dimensions=3, Extents='-10,10,-10,10,-10,10', Names='A,B,C', Units='U,U,U', OutputWorkspace='ws_3')
GroupWorkspaces(InputWorkspaces='ws_0,ws_1,ws_2,ws_3', OutputWorkspace='ws')
**RenameWorkspace(InputWorkspace='ws', OutputWorkspace='renamed')**

**Comment by Pasarus** [comment]
With regards to all workspaces in the same group having the same history i.e. having the history of every other workspace used to create that group in it's current state, that was achieved with a previous Pull request of mine #23464. This Pull request aims to remove the individual calls as it can sometimes lead to inaccuracies in the recovery/replaying process i.e. with RenameWorkspace it wouldn't rename the group itself etc. This is an issue in that it would then pass that group to another algorithm and cause a failure. I agree that this is a good change, and it would make more sense for it to be in the a WorkspaceGroup's history however after discussions with @martyngigg and @NickDraper on the topic it is something that was debated at length and we came out with our current history saving structure, so with regards to it I've aimed to make the history more complete. Let me just work on the fixes you suggested :+1:

File: Framework/Algorithms/src/RenameWorkspace.cpp [hunk 1]
```diff
@@ -175,6 +180,8 @@ bool RenameWorkspace::processGroups() {
             this->name(), this->version());
         alg->setPropertyValue("InputWorkspace", names[i]);
         alg->setPropertyValue("OutputWorkspace", wsName);
+        alg->setChild(true);
+        alg->enableHistoryRecordingForChild(false);
```
[the remark this answers is not in the document]
Comment (Pasarus) [reply Framework/Algorithms/src/RenameWorkspace.cpp]: Yes I do, however it is a bit out of the scope of this PR in my opinion, plus it depends on how they call the child algorithms on the groups I think I tested this with ReflectometryReductionOneAuto as well and the history was still complete I believe. It would have to be on an algorithm by algorithm basis.

**Review by vreimund — DISMISSED** [review]

File: Framework/Algorithms/src/RenameWorkspace.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (reimundILL) [reply Framework/Algorithms/src/RenameWorkspace.cpp]: I agree.

File: Framework/API/src/Algorithm.cpp [hunk 2]
```diff
@@ -1369,6 +1369,38 @@ bool Algorithm::doCallProcessGroups(
...
+      // We need to find the workspaces to add the history to.
+      if (outputWorkspaces.size() == 0 && inputWorkspaces.size() == 0) {
+        for (auto ws : m_groupWorkspaces) {
+          outputWorkspaces.emplace_back(ws);
+        }
+      } else if (outputWorkspaces.size() == 0) {
+        outputWorkspaces = inputWorkspaces;
+      }
+
+      for (auto outputWorkspace : outputWorkspaces) {
```
Comment (soininen) [inline Framework/API/src/Algorithm.cpp]: Avoid unnecessary copying of `shared_ptr`:
```suggestion
      for (const auto &outputWorkspace : outputWorkspaces) {
```

File: Framework/API/src/Algorithm.cpp [hunk 3]
```diff
@@ -1369,6 +1369,38 @@ bool Algorithm::doCallProcessGroups(
...
+                                                     ++g_execCount);
+
+    if (trackingHistory() && m_history) {
+
+      std::vector<Workspace_sptr> inputWorkspaces, outputWorkspaces;
+      findWorkspaceProperties(inputWorkspaces, outputWorkspaces);
+
+      // We need to find the workspaces to add the history to.
+      if (outputWorkspaces.size() == 0 && inputWorkspaces.size() == 0) {
+        for (auto ws : m_groupWorkspaces) {
```
Comment (soininen) [inline Framework/API/src/Algorithm.cpp]: `const auto &`?

In fact, the `for` loop could be replaced by
```
outputWorkspaces.insert(outputWorkspaces.end(), m_groupWorkspaces.begin(), m_groupWorkspaces.end());
```

**Review by soininen — CHANGES_REQUESTED** [review]
Just a few suggestions for avoiding some copy operations.

File: Framework/API/src/Algorithm.cpp (hunk 3 above)
Comment (Pasarus) [reply Framework/API/src/Algorithm.cpp]: :+1:

File: Framework/API/src/Algorithm.cpp (hunk 2 above)
Comment (Pasarus) [reply Framework/API/src/Algorithm.cpp]: :+1:

**Review by soininen — APPROVED** [review]
