### PR TITLE
Fix FileFinder crashes with specific characters

### LINKED ISSUE #20093: MWRunFiles widget - '.' character results in an uncaught exception
### Expected behavior
There should be no exception prompt until the user runs the algorithm with invalid field entries.

### Actual behaviour
The MWRunFiles widget generates an exception when a sole '.' character is entered into it.

### Steps to reproduce the behaviour
1. Access any interface with an MWRunFiles widget (e.g. all Indirect > Data Analysis and Indirect > Data Reduction interfaces).
2. Enter a '.' into the widget.
3. Press enter or click out of the widget.

### Platforms affected

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR fixes two cases where there would be a crash in the FileFinder widget:
1. Providing a single `.` character would cause a crash
2. Using a non-ASCII character in the FileFinder such as the `£` symbol would cause a crash.

The FileFinder now ensures that the string provided is all ASCII characters, and will also return early if the filename is empty (which is the case when providing a single `.` character).

**To test:**
1. Go to an interface with a FileFinder widget (e.g. Indirect Data Reduction)
2. In `Input Runs` type `.` and click enter. There should be no crash.
3. In `Input Runs` type a string containing a non-ASCII character such as `£` and click enter. There should be no crash again.

Fixes #20093

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by SpencerHowells** [comment]
@robertapplin I have also had problems with a space in a directory name. In particular on Widows there is a default 'My PC' folder! I cannot remember where this occured & it might not be in an interface.

**Review by RichardWaiteSTFC — DISMISSED** [review]
Looks good, nice fix! It no longer crashed with '.' character. I was unable to  recreate the exception on master using a char > 127 (e.g. £) - however on master I get a rather unhelpful hint ("Unable to find file path") whereas now I get the message about non-ASCII characters. Also I tried the Indirect Data Reduction interface file browser with path containing a space and it worked fine.

File: qt/widgets/common/src/FindFilesWorker.cpp [hunk 1]
```diff
@@ -122,6 +123,30 @@ void FindFilesWorker::run() {
   finishSearching(result);
 }
 
+/**
+ * Validate that the search text is not empty and contains no unsupported
+ * characters.
+ *
+ * @return a boolean indicating whether the search text is valid or not.
+ */
+bool FindFilesWorker::validateSearchText() {
```
Comment (martyngigg) [inline qt/widgets/common/src/FindFilesWorker.cpp:132]: Can I ask how this manifests as a crash? It also feels like this should ask the `FileFinder` or `FileProperty` itself if the input is valid? If I imagine writing a different view then I would likely want to use the same model validation code.

Also, is it just ascii characters we want? Most modern linuxes will use `UTF-8` for file paths and Windows UTF-16. How exactly does the crash with chars like `&` manifest itself?

File: qt/widgets/common/src/FindFilesWorker.cpp [hunk 2]
```diff
@@ -122,6 +123,30 @@ void FindFilesWorker::run() {
...
+
+  if (m_parameters.searchText.empty()) {
+    error = "No files specified.";
+  } else if (!isASCII(m_parameters.searchText)) {
+    error = "An unsupported non-ASCII character was found in the search text.";
+  }
+
+  if (!error.empty()) {
+    std::vector<std::string> filenames;
+    finishSearching(createFindFilesSearchResult(
```
Comment (martyngigg) [inline qt/widgets/common/src/FindFilesWorker.cpp:143]: Shuold we be doing the full search as part of the validation of the input?

**Review by martyngigg — CHANGES_REQUESTED** [review]

File: qt/widgets/common/src/FindFilesWorker.cpp (hunk 1 above)
Comment (RichardWaiteSTFC) [reply qt/widgets/common/src/FindFilesWorker.cpp:132]: A single full-stop '.' it gives a hard (sad mantid) crash on master - but interestingly I only saw this on the indirect data reduction interface (though I didn't try other indirect interfaces) but not on all the Load algorithms and the Eng Diff UI file browser worked - I assumed they use a different file-finder?

Comment (robertapplin) [reply qt/widgets/common/src/FindFilesWorker.cpp:132]: The single full-stop only causes a crash in Indirect because the FileFinder returns that the '.' file is valid and has been found. The indirect data reduction interface checks to see if its valid using `filefinder->isValid()` and attempts to load the file immediately after enter is pressed, whereas I assume other interfaces will perform the load later on.

Comment (robertapplin) [reply qt/widgets/common/src/FindFilesWorker.cpp:132]: Perhaps we want more than just ASCII characters? However when converting a QString from QLineEdit::text() to std::string it appeared that all characters other than ASCII characters where not being converted properly. i.e. QString(`£`) was converted to std::string(`Â£`), and this `Â` character caused the following error for me (in Debug mode) 

image

File: qt/widgets/common/src/FindFilesWorker.cpp (hunk 2 above)
Comment (robertapplin) [reply qt/widgets/common/src/FindFilesWorker.cpp:143]: I don't think this is doing a full search, just creating a 'search result' containing an error message. This should be doing the same as was previously being done on line 61

File: qt/widgets/common/src/FindFilesWorker.cpp (hunk 1 above)
Comment (robertapplin) [reply qt/widgets/common/src/FindFilesWorker.cpp:132]: Ahh, maybe the above problem only happens because I am in debug mode?

File: qt/widgets/common/src/FindFilesWorker.cpp (hunk 2 above)
Comment (martyngigg) [reply qt/widgets/common/src/FindFilesWorker.cpp:143]: Ah sorry, my misunderstanding from reading the function name.

File: qt/widgets/common/src/FindFilesWorker.cpp (hunk 1 above)
Comment (martyngigg) [reply qt/widgets/common/src/FindFilesWorker.cpp:132]: Ah yes you are correct that the framework only understand ascii but I'm curious as `std::string` is capable of holding the data do we know where this assertion is coming from?

Even though this pops up only in debug it's definitely a problem we need to solve. The Debug mode is basically saying something is wrong but Release mode will be doing something defined but most likey not what we want and gives these crashes.

Comment (robertapplin) [reply qt/widgets/common/src/FindFilesWorker.cpp:132]: The assertion comes from the StringTokenizer on this line
https://github.com/mantidproject/mantid/blob/920de5ba6d08be16d933107ef57e6d4c5e189cef/Framework/Kernel/src/StringTokenizer.cpp#L17

Comment (martyngigg) [reply qt/widgets/common/src/FindFilesWorker.cpp:132]: Ah okay. So I agree we need a check like this but what we're saying is that this is validation on what we are doing at the model level as we happen to be tokenizing it so I think the checking code live there and not in the widget.  What's the call stack before this?

**Comment by SpencerHowells** [comment]
@martyngigg @robertapplin I spent hours trying to track down these problems. It was made more complicated by: different facility/instrument; different OS; using interface or scripting! For 2 of them this is what happens:
- on Widows if you have a folder /My PC/ the interface accepts it but then the alg treats the space as a delimiter & makes it 2 entries which it then doesn't like. Seen with ILL reduction.
-  if the folder contains a floating point number again the interface is ok but the algo then treats the text after that decimal point as the extension which it doesn't like. Seen with ISIS reduction.
I have instructed MolSci scientists & users to avoid spaces, decimal points & non-alphanumeric characters in file paths.

File: qt/widgets/common/src/FindFilesWorker.cpp (hunk 1 above)
Comment (robertapplin) [reply qt/widgets/common/src/FindFilesWorker.cpp:132]:
```
MantidKernel.dll!std::find_if_not<std::_String_iterator<std::_String_val<std::_Simple_types<char>>>,int (__cdecl*)(int)>(std::_String_iterator<std::_String_val<std::_Simple_types<char>>> _First, const std::_String_iterator<std::_String_val<std::_Simple_types<char>>> _Last, int(*)(int) _Pred) Line 419
	at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\algorithm(419)
MantidKernel.dll!`anonymous namespace'::trimTokenFromStart(std::string & s) Line 17
	at C:\Users\mlc47243\Documents\mantid-development\mantid-4\mantid\Framework\Kernel\src\StringTokenizer.cpp(17)
MantidKernel.dll!`anonymous namespace'::trimToken(std::string & s) Line 28
	at C:\Users\mlc47243\Documents\mantid-development\mantid-4\mantid\Framework\Kernel\src\StringTokenizer.cpp(28)
MantidKernel.dll!`anonymous-namespace'::splitIgnoringWhitespaceEmptyTokens::__l2::<lambda>(std::_String_const_iterator<std::_String_val<std::_Simple_types<char>>> first, std::_String_const_iterator<std::_String_val<std::_Simple_types<char>>> second) Line 106
	at C:\Users\mlc47243\Documents\mantid-development\mantid-4\mantid\Framework\Kernel\src\StringTokenizer.cpp(106)
MantidKernel.dll!`anonymous namespace'::for_each_token<std::_String_const_iterator<std::_String_val<std::_Simple_types<char>>>,std::_String_const_iterator<std::_String_val<std::_Simple_types<char>>>,void <lambda>(std::_String_const_iterator<std::_String_val<std::_Simple_types<char>>>, std::_String_const_iterator<std::_String_val<std::_Simple_types<char>>>)>(std::_String_const_iterator<std::_String_val<std::_Simple_types<char>>> first, std::_String_const_iterator<std::_String_val<std::_Simple_types<char>>> last, std::_String_const_iterator<std::_String_val<std::_Simple_types<char>>> s_first, std::_String_const_iterator<std::_String_val<std::_Simple_types<char>>> s_last, `anonymous-namespace'::splitIgnoringWhitespaceEmptyTokens::__l2::void <lambda>(std::_String_const_iterator<std::_String_val<std::_Simple_types<char>>>, std::_String_const_iterator<std::_String_val<std::_Simple_types<char>>>) binary_op) Line 52
	at C:\Users\mlc47243\Documents\mantid-development\mantid-4\mantid\Framework\Kernel\src\StringTokenizer.cpp(52)
MantidKernel.dll!`anonymous namespace'::splitIgnoringWhitespaceEmptyTokens(const std::string & str, const std::string & delims) Line 110
	at C:\Users\mlc47243\Documents\mantid-development\mantid-4\mantid\Framework\Kernel\src\StringTokenizer.cpp(110)
MantidKernel.dll!Mantid::Kernel::StringTokenizer::StringTokenizer(const std::string & str, const std::string & separators, unsigned int options) Line 149
	at C:\Users\mlc47243\Documents\mantid-development\mantid-4\mantid\Framework\Kernel\src\StringTokenizer.cpp(149)
MantidAPI.dll!Mantid::API::FileFinderImpl::findRuns(const std::string & hintstr, const std::vector<std::string,std::allocator<std::string>> & exts, const bool useExtsOnly) Line 561
	at C:\Users\mlc47243\Documents\mantid-development\mantid-4\mantid\Framework\API\src\FileFinder.cpp(561)
MantidQtWidgetsCommonQt5.dll!MantidQt::API::FindFilesWorker::run() Line 82
	at C:\Users\mlc47243\Documents\mantid-development\mantid-4\mantid\qt\widgets\common\src\FindFilesWorker.cpp(82)
Qt5Cored.dll!QThreadPoolThread::run() Line 101
	at c:\users\qt\work\qt\qtbase\src\corelib\thread\qthreadpool.cpp(101)
Qt5Cored.dll!QThreadPrivate::start(void * arg) Line 378
	at c:\users\qt\work\qt\qtbase\src\corelib\thread\qthread_win.cpp(378)
```

Comment (robertapplin) [reply qt/widgets/common/src/FindFilesWorker.cpp:132]: I see, so the `isASCII` check should go somewhere in the StringTokenizer, and if the check fails I can throw an exception and catch it in the FindFilesWorker - which will then stop running and display the error?

**Comment by robertapplin** [comment]
Thanks @SpencerHowells for spotting this, I have created a separate issue to investigate these delimiter problems #30913

File: qt/widgets/common/src/FindFilesWorker.cpp (hunk 1 above)
Comment (martyngigg) [reply qt/widgets/common/src/FindFilesWorker.cpp:132]: Nearly. I think `FileFinder` is the best place for adding some type of `isValidRunsInput` method that the widget can call the way you have now where it calls isascii directly. It would at this point just contain your ascii check but could also be used by other areas that want to check the validity of input into the findRuns function.

**Comment by robertapplin** [comment]
Thank you both, it should be ready for another look

File: Framework/API/src/FileFinder.cpp [hunk 3]
```diff
@@ -533,6 +543,20 @@ void FileFinderImpl::getUniqueExtensions(
...
 }
 
+/**
+ * Performs validation on the search text entered into the File Finder. It will
+ * throw an exception if a problem is found. This error would then be caught and
+ * displayed to a user.
+ * @param searchText :: The text to validate.
+ * @throw std::invalid_argument if the searchText is invalid
+ */
+void FileFinderImpl::validateRuns(const std::string &searchText) const {
```
Comment (martyngigg) [inline Framework/API/src/FileFinder.cpp:553]: Thanks for this. Could I ask why we prefer an exception rather than say returning a `std::string` containing any possible error message? Using an exception indicates that it's not expected that the text might be incorrect but here both answers of is valid or not are valid answers and not exceptional states.

**Review by martyngigg — CHANGES_REQUESTED** [review]
Thanks for making this change. Can we add a unit test for it in `FileFinderTest`?

File: Framework/API/src/FileFinder.cpp (hunk 3 above)
Comment (robertapplin) [reply Framework/API/src/FileFinder.cpp:553]: I used a `throw` here because the `findRuns` method doesn't have a convenient way to return an error message. Instead it throws whenever there is a problem and the `FindFilesWorker` creates the error message stuff. I am not sure how to change this without making a large change to `findRuns`

**Comment by robertapplin** [comment]
> Thanks for making this change. Can we add a unit test for it in `FileFinderTest`?

I tried to add a test for non-ASCII characters previously but I was getting this test failure https://builds.mantidproject.org/job/pull_requests-ubuntu/42903/ (a similar error happened on rhel and windows). Any ideas if this can be fixed?

File: Framework/API/src/FileFinder.cpp (hunk 3 above)
Comment (martyngigg) [reply Framework/API/src/FileFinder.cpp:553]: Ah I see - I didn't spot that below. In this case I would then have `findRuns` throw if this function returns it's not valid rather than forcing the user of the validation to use an exception if all they want to do is check that the string is valid input.

**Comment by martyngigg** [comment]
> > Thanks for making this change. Can we add a unit test for it in `FileFinderTest`?
> 
> I tried to add a test for non-ASCII characters previously but I was getting this test failure https://builds.mantidproject.org/job/pull_requests-ubuntu/42903/ (a similar error happened on rhel and OSX). Any ideas if this can be fixed?

Ah interesting. That's the Python parser that is creating the test .cpp files saying that is not valid so it can't parse it. 🤔 
We might need to update the parser. Let me have a think.

File: Framework/API/src/FileFinder.cpp (hunk 3 above)
Comment (robertapplin) [reply Framework/API/src/FileFinder.cpp:553]: Ok sounds good 👍

File: Framework/API/src/FileFinder.cpp [hunk 4]
```diff
@@ -545,16 +545,18 @@ void FileFinderImpl::getUniqueExtensions(
...
- * displayed to a user.
+ * return a vector of error messages if problems are found.
  * @param searchText :: The text to validate.
- * @throw std::invalid_argument if the searchText is invalid
+ * @return A vector of error messages.
  */
-void FileFinderImpl::validateRuns(const std::string &searchText) const {
+std::vector<std::string>
+FileFinderImpl::validateRuns(const std::string &searchText) const {
+  std::vector<std::string> errors;
```
Comment (martyngigg) [inline Framework/API/src/FileFinder.cpp:554]: Quick Q. Any reason we can't just return a string here? It also has an `.empty` method..

**Comment by robertapplin** [comment]
I squashed some of the commit history in this PR to make the rebase easier.

**Comment by martyngigg** [comment]
@robertapplin Sorry for not getting back to you with this. For the case with the `£` that did not parse, how did you enter the character? I tried by using "shift-3" and it parses for me locally.

**Comment by robertapplin** [comment]
> @robertapplin Sorry for not getting back to you with this. For the case with the `£` that did not parse, how did you enter the character? I tried by using "shift-3" and it parses for me locally.

No problem. I also did shift-3 , it parses fine for me in a release build (i.e. no error message appears), but not for a debug build 
image

**Comment by martyngigg** [comment]
Ah I had been looking at the unit test but it's odd that the debug build raises that. It indicates an issue with the underlying code though.

Can you get a trace from it?

File: qt/widgets/common/src/FindFilesWorker.cpp (hunk 1 above)
Comment (robertapplin) [reply qt/widgets/common/src/FindFilesWorker.cpp]: Yes, the stack trace for the error should be in this thread @martyngigg

**Comment by martyngigg** [comment]
Thanks. I think I'm slightly confused. I thought we added the input check so it would end up avoiding doing the split that failed on non-ascii input?

**Comment by robertapplin** [comment]
Sorry the confusion might be my fault, I no longer get the above error when typing shift-3 into the run box as the `isASCII` check prevents this. I thought you were asking about the original problem, but now I think you were actually asking about the unit test

The `£` (shift-3) symbol used in the unit test also parses and runs ok for me locally. Its just on the build server that it fails. Is this what you were asking in your original question?

**Comment by martyngigg** [comment]
> The `£` (shift-3) symbol used in the unit test also parses and runs ok for me locally. Its just on the build server that it fails. Is this what you were asking in your original question?

Ah okay, my apologies for the misunderstanding. Do you know what system it fell over on?

**Comment by robertapplin** [comment]
> Ah okay, my apologies for the misunderstanding. Do you know what system it fell over on?
Yes I believe the parser error appeared on ubuntu, rhel and OSX . I don't think it fell over on windows

**Comment by martyngigg** [comment]
> > Ah okay, my apologies for the misunderstanding. Do you know what system it fell over on?
> 
> Yes I believe the parser error appeared on ubuntu, rhel and OSX . I don't think it fell over on windows

I think I see what has happened here now - it must be a character encoding issue. On my Ubuntu box I reset to your commit with the `£` in it and it indeed failed to parse. On linux (Git bash might have this) there is a `file` command that can tell you what type of file it is (or at least have a guess). Running `file` on the unit test gives:

```sh
> file qt/widgets/common/test/FindFilesWorkerTest.h
qt/widgets/common/test/FindFilesWorkerTest.h: C++ source, ISO-8859 text
```

so the character encoding is `ISO-8859` and not `UTF-8`. This explains why the other machines couldn't parse it. It very closely matches `Windows-1252` (https://en.wikipedia.org/wiki/Windows-1252) and so your editor most likely has used that encoding.

I copied the unit test header to a separate file (`iso-8859.txt`) and deleted every character but the `£` and then created a second file, `utf-8.txt` and wrote a `£` from the keyboard: 

```python
In [2]: f = open('iso-8859.txt','r')

In [3]: f.read()
Out[3]: '\xa3\n'

In [4]: iso = f

In [5]: utf8 = open('utf-8.txt')

In [6]: utf8.read()
Out[6]: '\xc2\xa3\n'
```

You can see that the first is a single-byte encoding that can't be understood by the standard utf-8 encoding. Could you check your encoding and change it to `utf-8` (https://stackoverflow.com/a/2633313) ?

**Comment by robertapplin** [comment]
My encoding was this:
```
$ file qt/widgets/common/test/FindFilesWorkerTest.h
qt/widgets/common/test/FindFilesWorkerTest.h: C++ source, ASCII text, with CRLF line terminators
```
I have changed it to UTF-8 Encoding so would this fix the issue?

File: Testing/Tools/cxxtest/python/cxxtest/cxxtest_parser.py [hunk 5]
```diff
@@ -35,7 +35,7 @@ def scanInputFiles(files, _options):
 
 def scanInputFile(fileName):
     '''Scan single input file for test suites'''
-    file = open(fileName)
+    file = open(fileName, encoding='utf-8')
```
Comment (martyngigg) [inline Testing/Tools/cxxtest/python/cxxtest/cxxtest_parser.py:38]: Confirmed that this seems to solve issues with the CentOS 7 CI build that was defaulting to `ascii`.

**Review by martyngigg — APPROVED** [review]
I think this is good to go now.
