### PR TITLE
Fix bug in PolarizationCorrectionWildes matrix definitions

### LINKED ISSUE #34940: Labelling of Wildes output workspaces is inverted
**Original reporter:** Andrew at ISIS

Using algorithm `PolarizationCorrectionWildes` outputs a group of workspaces with each individual workspace labelled `_++`, `_+-`, `_-+` or `_--` accordingly. Andrew noticed that these labels are being incorrectly inverted, i.e. the workspace labelled `_--` is actually the `_++` workspace, based on the corrected values.

We believe that the issue is in the definition of the `P1m` and `P2m` matrices in method `fourInputsCorrectedAndErrors`. As part of setting these up, `diag` and `off` variables are defined as below and then used to construct the matrices:

```
  const auto diag3 = (p1 - 1.) / (2. * p1 - 1.);
  const auto off3 = p1 / (2. * p1 - 1);
```

However, these definitions appear to be the wrong way round when compared to the Wildes paper (this is clearest to see when you look at the 2006 version of the paper). They should instead be defined as:

```
  const auto diag3 = p1 / (2. * p1 - 1);
  const auto off3 = (p1 - 1.) / (2. * p1 - 1.);
```

Andrew has confirmed that because the values in both of the P matrices have been swapped, the final values in the output matrix/vector are correct but in the wrong order and this is what causes the incorrect labelling.

We should correct the relevant calculations - note that this need to be done in both methods `fourInputsCorrectedAndErrors` and `analyzerlessCorrections`. This will fix the labelling, however it will mean that any scripts that ignored the labelling and relied simply on the ordering of the output workspace group to determine which workspace is which will no longer work. According to our documentation and the Wildes paper, the expected output order would be `++`, `+-`, `-+`, `--` (which is what we unintentionally output now). Andrew would prefer for the current order to be retained, but we should confirm this is OK with ILL as we believe they may be using this algorithm in their workflow. To change the output order once the labelling is fixed would likely just involve re-arranging the order defined in method `groupOutput`.

While looking at this, it would be good to check the mappings of input workspaces to flipper configurations in methods `checkConsistentX` and `checkConsistentNumberHistograms` (which look like they're just used for
logging informative error messages), as they don't match the input workspace mappings in `mapInputsToDirections`.

### PR DESCRIPTION
**Pull request by rbauststfc**
**Description of work.**

**Report to:** Andrew at ISIS

Fixes the bug described in the attached issue and changes the order of the output workspace group so that it matches what is described in the algorithm's documentation. This PR also fixes a few bugs in the unit tests so that they are providing the required coverage. I've also added a couple of new tests to cover the output workspace group order and to test for cross-polarized ideal efficiencies, which should help ensure that we would spot this error if it were ever re-introduced.

**To test:**

_Note, you may want to run through the following on a version of Mantid without the changes first to provide a benchmark for testing these changes._

1) Ask Rachel for the necessary test efficiencies workspace, as we haven't confirmed that it can be made public. Load this workspace into Mantid.
1) In the ISIS Reflectometry GUI, select POLREF as the instrument on the Runs tab.
1) On the Experiment Settings tab, tick the `Polarization Corrections` checkbox and select the loaded efficiencies workspace from the `Polarization Efficiencies` drop-down. Some other settings will be required here that Rachel can provide with the test efficiencies workspace.
1) On the Runs tab, enter `31835` in the first row (not group) of the runs table (in the right hand panel). Click the process button.
1) Expand the `IvsLam_31835` workspace that is output to the ADS. It should contain two workspaces, the first should have `_++` as the suffix and the second should have suffix `_--`. This will be the reverse order than you would have seen prior to the change. Inspecting the data using `Show Data`, you should also see that the values in the `_++` workspace are the values that you would previously have seen in the `_--` output workspace, and vice versa.

Fixes #34940. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Algorithms/test/PolarizationCorrectionWildesTest.h [hunk 1]
```diff
@@ -422,11 +373,11 @@ class PolarizationCorrectionWildesTest : public CxxTest::TestSuite {
         // first and then I01 is solved using all I00, I10 and I11. This
         // results in slightly larger errors estimates for I01 and thus for
         // the final corrected expected intensities.
-        TS_ASSERT_DELTA(ppE[k], expectedError[0], 1e-6)
+        TS_ASSERT_DELTA(ppE[k], expectedError[0], 1e-5)
         TS_ASSERT_LESS_THAN(ppE[k], expectedError[0])
         TS_ASSERT_DELTA(pmE[k], expectedError[1], 1e-2)
         TS_ASSERT_LESS_THAN(pmE[k], expectedError[1])
-        TS_ASSERT_DELTA(mpE[k], expectedError[2], 1e-7)
+        TS_ASSERT_DELTA(mpE[k], expectedError[2], 1e-2)
```
Comment (sf1919) [inline Framework/Algorithms/test/PolarizationCorrectionWildesTest.h:380]: This seems like a large change in accuracy. Is there a reason for this?

Comment (rbauststfc) [reply Framework/Algorithms/test/PolarizationCorrectionWildesTest.h:380]: So there's actually a comment in the test just above this that says the calculation being used in the test is slightly different to the one in the algorithm. I had a quick look but felt it would take a bit of time to figure out what was going on in the code vs the paper. I should have written on the PR, but I've asked the scientists to do a thorough review of the algorithm once this fix has been merged, including checking the error calculations, and then we'll know if there are any further issues. If there aren't then we can still add an issue to improve the unit tests here so that we're testing the errors more accurately.

Comment (sf1919) [reply Framework/Algorithms/test/PolarizationCorrectionWildesTest.h:380]: Thanks - that makes a lot of sense.

**Review by sf1919 — APPROVED** [review]
I have tested this by comparing the outputs of an older version of Mantid and this PR branch and the changes work as expected. Its good to have tests to avoid this accidental switch in future. Thank you for explaining about the change of accuracy I saw in one of the tests - I feel the approach is sensible under the circumstances.

LGTM
