### PR TITLE
Fix bug in Integration algorithm when using IncludePartialBins

### LINKED ISSUE #32591: Fix partial bins option in Integration when running on a points dataset
I've been thinking of calling the Integration algorithm as a child algorithm from the DiscusMultipleScatteringCorrection algorithm. The histogram I'm wanting to integrate over consists of points (as opposed to bin edges) and the integration limits are sometimes either equal or close together such that there isn't a point in between them. I've tried using the IncludePartialBins option for this but at the moment the Integration algorithm gives the wrong answer. For example if the integration limits are the same the algorithm should return zero whereas at the moment it returns the integral between the two surrounding points.

This script shows the problem is present for both bin edge and point data. It specifically happens when the equal limits don't equal a bin edge. The point histogram is internally converted to a histogram by the Integration algorithm so it's "internal" bin edges are [-0.5, 0.5, 1.5, 2.5, 3.5]:

```
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

X_edges = [0., 1., 2., 3., 4.]
Y=[1., 1., 1., 1.]
test_edges = CreateWorkspace(X_edges,Y)
int_edges = Integration(test_edges,0.6,0.6)
int_edges_partial = Integration(test_edges,0.6,0.6,IncludePartialBins=True) # returns 1

X_pts=[0., 1., 2., 3.]
test_pts = CreateWorkspace(X_pts,Y)
int_pts = Integration(test_pts,0.6,0.6)
int_pts_partial = Integration(test_pts,0.6,0.6,IncludePartialBins=True) # returns 1
```

### PR DESCRIPTION
**Pull request by DannyHindson**
**Description of work.**

When Integration is run with IncludePartialBins=True and integration limits that are either equal or close together the algorithm was returning the wrong answer. The partial bins logic wasn't working when the RangeLower and RangeUpper values were in between consecutive values in the x data

**To test:**

Run the script attached to the linked issue and observe that the algorithm now returns 0 in the calls with IncludePartialBins where the integration limits are the same

Fixes #32591. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Algorithms/test/IntegrationTest.h [hunk 1]
```diff
@@ -146,15 +146,31 @@ class IntegrationTest : public CxxTest::TestSuite {
...
+
+  void testRangeWithPartialBinsAndLimitsInSameBin() {
+    Workspace2D_sptr input;
+    TS_ASSERT_THROWS_NOTHING(
+        input = std::dynamic_pointer_cast<Workspace2D>(AnalysisDataService::Instance().retrieve("testSpace")))
+    input->setDistribution(true);
+    assertRangeWithPartialBins(input, 0.1, 0.5, {4., 6., 8.}, {1.265, 1.549, 1.788});
+  }
+
+  void testRangeWithPartialBinsAndEqualLimits() {
```
Comment (RichardWaiteSTFC) [inline Framework/Algorithms/test/IntegrationTest.h:168]: New tests look good, but is it also worthwhile having a test that asserts integration on a points and histogram data set that are equivalent give the same answer? It doesn't look like we have a test that does this but I may have missed it.

**Review by RichardWaiteSTFC — CHANGES_REQUESTED** [review]
Works well - have tested on edge and points data and the bug is fixed.
Is it possible to update the docs for this algorithm - it says there 
`if the ranges given do not coincide with a bin boundary then the first bin boundary within the range is used.`
However, this only applies to `IncludePartialBins=False` is that correct?

**Comment by DannyHindson** [comment]
> Works well - have tested on edge and points data and the bug is fixed. Is it possible to update the docs for this algorithm - it says there `if the ranges given do not coincide with a bin boundary then the first bin boundary within the range is used.` However, this only applies to `IncludePartialBins=False` is that correct?

Yes you're correct. I'll update. I think the comment was intended to emphasise the point that the algorithm doesn't do any rebinning but it's not accurate. If IncludePartialBins=True and the limits sit inside a bin then the algorithm calculates an extra fractional contribution.

**Review by RichardWaiteSTFC — DISMISSED** [review]
Thanks for fixing this and for clarifying the documentation, I agree changes to `setDistribution(true)` are beyond the scope of this PR.

File: Framework/Algorithms/src/Integration.cpp [hunk 2]
```diff
@@ -278,19 +279,35 @@ void Integration::exec() {
...
+          if (!is_distrib) {
+            fraction /= (lower_bin - prev_bin);
+          }
+          const MantidVec::size_type val_index = distmin - 1;
+          sumY += Y[val_index] * fraction;
+          const double eval = E[val_index];
+          sumE += eval * eval * fraction * fraction;
+          if (rebinned_input) {
+            sumF += Fmin * fraction;
+          }
```
Comment (DavidFair) [inline Framework/Algorithms/src/Integration.cpp:296]: Can we chunk this method and the other one into private methods. The `exec` of this file is starting to weigh in at 200+ LOC with the various nested if-else blocks

File: Framework/Algorithms/src/Integration.cpp [hunk 3]
```diff
@@ -278,19 +279,35 @@ void Integration::exec() {
...
+          double fraction = (upperLimit - upper_bin);
+          if (!is_distrib) {
+            fraction /= (next_bin - upper_bin);
+          }
+          sumY += Y[distmax] * fraction;
+          const double eval = E[distmax];
+          sumE += eval * eval * fraction * fraction;
+          if (rebinned_input) {
+            sumF += Fmax * fraction;
+          }
```
Comment (DavidFair) [inline Framework/Algorithms/src/Integration.cpp:310]: Same with this too

**Review by DavidFair — CHANGES_REQUESTED** [review]
Some minor readability nits, otherwise I'm happy to merge this

File: Framework/Algorithms/src/Integration.cpp (hunk 2 above)
Comment (DannyHindson) [reply Framework/Algorithms/src/Integration.cpp:296]: Just pulling out this ~10 lines into a private method will involve passing these 7 variables as parameters: lowit, lowerLimit, is_distrib, distmin, Y[], E[], Fmin and also returning 3 variables sumY, sumE and sumF. This feels like a slightly ugly bit to pull out.
Having had a look at the exec, perhaps the content of the parallel for loop could be pulled as some kind of IntegrateSpectrum method?

Comment (DavidFair) [reply Framework/Algorithms/src/Integration.cpp:296]: Yeah that would help significantly too
This isn't a PR blocker, so if it's way too much work I can be swayed against

Comment (DannyHindson) [reply Framework/Algorithms/src/Integration.cpp]: I've just pushed a commit with an IntegrateSpectrum method. See what you think. I can always revert to the previous commit if this is getting too big a change but seems OK?

File: Framework/Algorithms/inc/MantidAlgorithms/Integration.h [hunk 4]
```diff
@@ -69,6 +69,9 @@ class MANTID_ALGORITHMS_DLL Integration : public API::Algorithm {
   /// Create the outputworkspace
   API::MatrixWorkspace_sptr getOutputWorkspace(API::MatrixWorkspace_sptr inWS, const int minSpec, const int maxSpec);
   std::map<std::string, std::string> validateInputs() override;
+  void integrateSpectrum(const API::ISpectrum &inSpec, API::ISpectrum &outSpec, const std::vector<double> *Fin,
```
Comment (DavidFair) [inline Framework/Algorithms/inc/MantidAlgorithms/Integration.h:72]: LGTM, my only nits with this are:
- Can allocate a vector on the stack and pass in by ref and just check for .empty as the sentinel
- Clang-tidy will complain about `const` scalar types which are passed by copy, can we drop const from double and bool?

Comment (DannyHindson) [reply Framework/Algorithms/inc/MantidAlgorithms/Integration.h:72]: No problem about removing the `const`s. Re your first point, I could do this for Fin but I think I have to leave Fout as a pointer because I need to update the data inside rebinned_output->dataF(). So seemed more symmetrical to leave Fin and Fout as pointers? Knew you'd like a bit of raw pointer action...

Comment (DavidFair) [reply Framework/Algorithms/inc/MantidAlgorithms/Integration.h:72]: That sounds good to me, we'll stick with the raw pointer squad so we can get this out of the way for the weekend :laughing:

**Review by DavidFair — DISMISSED** [review]
LGTM I'll :shipit: once the tests pass

**Comment by DavidFair** [comment]
It looks like you're missing the header for `API::ISpectrum` which is why it's falling over outside of MSVC

**Review by RichardWaiteSTFC — APPROVED** [review]
All builds passing now!

**Review by DavidFair — APPROVED** [review]
Thanks all :+1:
