### PR TITLE
Multi-dataset interface: fix a bug in plotting the function guess.

### LINKED ISSUE #17256: Multi-dataset fit interface gives error with some uninitialised functions.
### Expected behavior

No errors.

### Actual behavior

If a function is added that cannot be used with the default parameters/attributes the interface gives an unexpected error message and may crash Mantid.

### Steps to reproduce the behavior

1. Open the Multi-dataset interface.
2. Add Resolution function (category General).

Unexpected exception message.

### Platforms affected

All.

### PR DESCRIPTION
**Pull request by mantid-roman**
Catch any std exception from the guess function call and log the message.

**To test:**

- Add a Resolution function to Multi-dataset interface.
- No "Unexpected exception" dialog should show.
- A warning about using uninitialised TabulatedFunction should be seen in the log window.
- Set some data to the function by setting either Filename or Workspace attribute.
- The warning shouldn't show any more.

Fixes #17256.

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AntonPiccardoSelg** [comment]
* Code looks good.
* Following the described steps above does not crash Mantid but rather produces a log warning as mentioned in the description
* Once a workspace is set for the Resolution function, the warning disappears (again  as described)

Happy to :shipit:

File: MantidQt/CustomInterfaces/src/MultiDatasetFit/MultiDatasetFit.cpp [hunk 1]
```diff
@@ -713,5 +714,11 @@ void MultiDatasetFit::updateGuessFunction(const QString &, const QString &) {
   m_plotController->updateGuessFunction(*m_functionBrowser->getFunction());
 }
 
+/// Log a warning
+/// @param msg :: A warning message to log.
+void MultiDatasetFit::logWarning(const std::string &msg) {
+  g_log.warning() << msg << std::endl;
```
Comment (FedeMPouzols) [inline MantidQt/CustomInterfaces/src/MultiDatasetFit/MultiDatasetFit.cpp]: Not that it makes any real difference, bit forma consistency `\n` would be preferred. Also, the message can be passed as a parameter rather than using the stream operators.
