### PR TITLE
Check axis type before table transposition Refs #23155

### LINKED ISSUE #23155: Indirect Crashes in F(Q)
**Original reporter:** Sanghamitra

### Expected behavior

Mantid should not allow "Fit Single Spectrum" when there is, if there is only a single spectrum loaded.

### Actual behavior

Mantid allows change to single spectrum fit and causes a hard crash

### Steps to reproduce the behavior

* Open Indirect > Data Analysis > F(Q)
* Load the data below
* Click the 'Fit Single Spectrum Button'

[IN16B_125878_QLd_Result.nxs.zip](https://github.com/mantidproject/mantid/files/2249669/IN16B_125878_QLd_Result.nxs.zip)

### Platforms affected

All

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR adds a check on the y-axis type (i.e. Text or Numeric) of the input workspace(s) and correctly extracts the axis values/labels into the parameters table and the result workspace.

**To test:**
- Open Indirect > Data Analysis > F(Q)
- Enter the provided test data
- Select 'Chudley Elliot' in the 'Fit Type' drop-down menu
- Click the 'Fit Single Spectrum Button'
- Ensure the fit completes successfully
- Open the *_Parameters workspace and ensure that the axis-1 column contains f1.f1.FWHM

**Test Files**
[IN16B_125878_QLd_Result.nxs.zip](https://github.com/mantidproject/mantid/files/2249669/IN16B_125878_QLd_Result.nxs.zip)

Fixes #23155 

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/WorkflowAlgorithms/src/ProcessIndirectFitParameters.cpp [hunk 1]
```diff
@@ -82,6 +89,14 @@ std::vector<T> getColumnValues(Column const &column, std::size_t startRow,
   return values;
 }
 
+std::vector<double> getNumericColumnValuesOrIndices(Column const &column,
+                                                    std::size_t startRow,
+                                                    std::size_t endRow) {
+  if (column.isNumber())
+    return getColumnValues<double>(column, startRow, endRow);
+  return getIncrementingSequence(0.0, endRow - startRow + 1);
```
Comment (brandonhewer) [inline Framework/WorkflowAlgorithms/src/ProcessIndirectFitParameters.cpp]: If startRow > endRow this will produce undefined behaviour.

You could do:
auto const length = startRow >= endRow ? 1 + startRow - endRow : 0;

Then pass length to getIncrementingSequence

File: Framework/CurveFitting/src/Algorithms/QENSFitSequential.cpp [hunk 2]
```diff
@@ -278,6 +279,36 @@ createGroup(const std::vector<MatrixWorkspace_sptr> &workspaces) {
...
+    ITableWorkspace_sptr parameterWorkspace, const std::string &xAxisUnit,
+    const std::vector<std::string> &parameterNames) {
+  auto pifp =
+      AlgorithmManager::Instance().create("ProcessIndirectFitParameters");
+  pifp->setAlwaysStoreInADS(false);
+  pifp->setProperty("InputWorkspace", parameterWorkspace);
+  pifp->setProperty("ColumnX", "axis-1");
+  pifp->setProperty("XAxisUnit", xAxisUnit);
+  pifp->setProperty("ParameterNames", parameterNames);
+  return pifp;
```
Comment (brandonhewer) [inline Framework/CurveFitting/src/Algorithms/QENSFitSequential.cpp]: As is this isn't created as a child, it will be included in the History as a parent history (causing issues for project recovery).

File: Framework/CurveFitting/src/Algorithms/QENSFitSimultaneous.cpp [hunk 3]
```diff
@@ -164,10 +165,24 @@ WorkspaceGroup_sptr makeGroup(Workspace_sptr workspace) {
...
+    ITableWorkspace_sptr parameterWorkspace, const std::string &xAxisUnit,
+    const std::vector<std::string> &parameterNames) {
+  auto pifp =
+      AlgorithmManager::Instance().create("ProcessIndirectFitParameters");
+  pifp->setAlwaysStoreInADS(false);
+  pifp->setProperty("InputWorkspace", parameterWorkspace);
+  pifp->setProperty("ColumnX", "axis-1");
+  pifp->setProperty("XAxisUnit", xAxisUnit);
+  pifp->setProperty("ParameterNames", parameterNames);
+  return pifp;
```
Comment (brandonhewer) [inline Framework/CurveFitting/src/Algorithms/QENSFitSimultaneous.cpp]: Same issue with the history as mentioned above.

File: Framework/CurveFitting/src/Algorithms/QENSFitSimultaneous.cpp [hunk 4]
```diff
@@ -164,10 +165,24 @@ WorkspaceGroup_sptr makeGroup(Workspace_sptr workspace) {
...
+}
+
 ITableWorkspace_sptr transposeFitTable(ITableWorkspace_sptr table,
-                                       IFunction_sptr function) {
+                                       IFunction_sptr function,
+                                       const std::string &yAxisType) {
```
Comment (brandonhewer) [inline Framework/CurveFitting/src/Algorithms/QENSFitSimultaneous.cpp]: In  the transposeFitTable method, the function parameter never needs to be a shared_ptr, cannot be null and should not be changed. It should preferably be passed by const reference.

**Review by brandonhewer — DISMISSED** [review]
The code quality is good overall -- the main issues that may arise relate to project recovery.

**Review by ewancook — APPROVED** [review]
Changes made work and the previous reviewer (Brandon) was happy with them, albeit unable to approve before he left
