### PR TITLE
Fix bug with saving WISH data to Isaw format

### LINKED ISSUE #23510: WISH peaks can't be saved to ISAW format.
**Original reporter:** Fabio Orlandi

### Expected behavior
WISH should be able to save to the ISAW peaks format.

### Actual behavior
```
Error in execution of algorithm SaveIsawPeaks:
Detector module of type WISHpanel not supported in ISAWPeaks. Cannot save peaks file
```
### Steps to reproduce the behavior
Try to save any peaks workspace from WISH using `SaveIsawPeaks`

### Platforms affected
All]

### PR DESCRIPTION
**Pull request by samueljackson92**
**Description of work.**
Fix bug where WISH peak workspaces are not saved to the Isaw `.peaks` file format.

**Report to:** Fabio Orlandi

**To test:**
 - Check that saving a peaks workspace with the WISH instrument attached.
 - Code review.

Fixes #23510 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by LowriJenkins — CHANGES_REQUESTED** [review]
Saving the file out appears to work, but attempting to load the file back in using `LoadISawPeaks` appears to get stuck and fail, this may be a problem in `LoadISawPeaks`, but perhaps the file is not being saved out correctly?

**Comment by samueljackson92** [comment]
@SamJenkins1 what is the error output when running LoadIsawPeaks?

**Comment by samueljackson92** [comment]
@SamJenkins1 Ok I shall investigate further.

**Comment by samueljackson92** [comment]
@SamJenkins1 The issue you saw was because the algorithm generates a dummy peak which is not attached to a valid detector. `LoadIsawPeaks` wasn't handling that very well. Now it will give a error & not crash.

**Comment by samueljackson92** [comment]
@SamJenkins1 The issue you saw was because the algorithm generates a dummy peak which is not attached to a valid detector. LoadIsawPeaks wasn't handling that very well. Now it will give a error & not crash.

**Comment by samueljackson92** [comment]
@SamJenkins1 That is the behaviour I was expecting. You're saving a file with peaks that are not attached to any detector. When loading the file back in there is no way for the algorithm to find a detector because it never had one associated with it.

There's probably more we could do here it make this nicer, but that is not really related to this issue.

**Review by LowriJenkins — APPROVED** [review]

File: Framework/Crystal/src/SaveIsawPeaks.cpp [hunk 1]
```diff
@@ -127,7 +127,7 @@ void SaveIsawPeaks::exec() {
     throw std::runtime_error(
         "No instrument in PeaksWorkspace. Cannot save peaks file.");
 
-  if (bankPart != "bank" && bankPart != "WISH" && bankPart != "?") {
+  if (bankPart != "bank" && bankPart != "WISHpanel" && bankPart != "?") {
```
Comment (martyngigg) [inline Framework/Crystal/src/SaveIsawPeaks.cpp]: I'm not suggesting we change it here but would is possible to make this more general in some way and not have to update the code for each instrument that we want to support?
