### PR TITLE
Fix run status log for aborted runs

### LINKED ISSUE #17924: Set run status correctly for aborted runs
*Reported by James Lord, Mantid 3.8*

#### Expected behaviour
If a run is aborted and then restarted, the `running` log should be set to false at all times during the aborted run.

#### Actual behaviour
`running` is false between the abort and the second start, but is left as true before the abort - despite the data from this aborted run not being in the file.

#### Steps to reproduce the behaviour
Look at `EMU00066122`: (section of event log below)

| Time (sec)       | Time (actual)           | Event |
| :-------------: |:-------------:|:-----:|
| -57      | 10:01:47 | BEGIN |
| -9      | 10:02:35 | ABORT      |
| 0 | 10:02:44 | BEGIN      |

The `running` sample log, which is generated by `LogParser`, is true from time -57 to time -9, false from time -9 to time 0 and then true from time 0 onwards. It should be false at all times before time 0, i.e. when the ABORT is seen at time -9 this makes anything before it count as "not running".

This has relevance when filtering log data by the running status, e.g. in the Sample Logs dialog. See #17877.

### PR DESCRIPTION
**Pull request by tom-perkins**
Correct the generation of the `running` log on loading a file: if the run was aborted and then restarted, the `running` log should only show that it was running after the restart. At all times before the restart, `running` should be false. (This is important for filtering other logs by `running`, and was requested by scientists).

Add tests for old and new style logs, and also did some maintenance on the other tests in `LogParserTest`.

**To test:**

Use any datafile where the run was aborted, then restarted. For example, try `EMU00066122.nxs`, which can be found at `\\olympic\babylon5\Scratch\TomPerkins\test_tsp_filtering`:

```python
tuple = Load('EMU00066122')
ws = tuple[0]
run = ws.run()
log = run.getProperty("running")
for i in range(log.size()):
    print log.nthTime(i), log.nthValue(i)
```
Before the fix, `running` would be `True` from the start time (10:01:47) until the run was aborted at 10:02:35.
After the fix, at all times before the abort, `running` should be `False`.

Fixes #17924.

[Release notes](https://github.com/mantidproject/mantid/blob/6de56f59dafe1c8ba1aea8bcc3b2e31af2d72924/docs/source/release/v3.9.0/framework.rst#bug-fixes) have been updated.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by PranavBahuguna** [comment]
The code itself seems fine, no issues there.

On running the tests as described, I can confirm that all times before 10:02:35 (where abort took place) now have a value of false, as expected.

Everything seems fine to me :shipit:

File: Framework/Kernel/inc/MantidKernel/LogParser.h [hunk 1]
```diff
@@ -100,7 +100,7 @@ class MANTID_KERNEL_DLL LogParser {
       Kernel::TimeSeriesProperty<bool> *status);
 
   /// Available commands.
-  enum commands { NONE = 0, BEGIN, END, CHANGE_PERIOD };
+  enum class commands { NONE = 0, BEGIN, END, CHANGE_PERIOD, ABORT };
```
Comment (martyngigg) [inline Framework/Kernel/inc/MantidKernel/LogParser.h]: Nice introduction of enum class.

File: Framework/Kernel/test/LogParserTest.h [hunk 2]
```diff
@@ -45,41 +46,37 @@ class LogParserTest : public CxxTest::TestSuite {
   void testGood() {
     mkICP();
     mkGood();
-    Property *icp_log =
-        LogParser::createLogProperty(icp_file.path(), "icpevent");
-    LogParser lp(icp_log);
-    Property *p1 = lp.createLogProperty(log_num_good.path(), "good");
+    const auto &icp_log = std::unique_ptr<Property>(
```
Comment (martyngigg) [inline Framework/Kernel/test/LogParserTest.h]: :+1: for `unique_ptr`
