### PR TITLE
Fix Crash in SaveGSS Algorithm when Using Group Workspaces

### LINKED ISSUE #27592: SaveGSS has unhandles exception when working with group workspaces.
### Expected behavior
`SaveGSS` should handle any exception raised by having a group workspace as one of the inputs, or stop group workspaces from being one of the inputs at all
### Actual behavior
If a group workspcae is first on the list of input workspaces in `SaveGSS` it will return an error when initializing the algorithm. the same exception is raised when trying to run the algorithm with a group workspace.
### Steps to reproduce the behavior
1. Open workbench
2. load a group workspace (`GEM63437_foccused` from the tutorial)
3. initialize `SaveGSS`

Alternatively:
1. Open Workbench
2. load multiple workspaces and then group them together
3. Execute `SaveGSS` with the group workspace as the `InputWorkspace`.

### Platforms affected
Found on windows

### PR DESCRIPTION
**Pull request by cailafinn**
When a Group workspace was loaded into the dialog for the algorithm, it
would cause an unhandled exception due to a null pointer. There is now a
check to ensure that a group workspace is not used.

**To test:**
1. Load some workspaces and put them into a group. 
2. Launch the `SaveGSS` algorithm from the algorithm manager (this issue was not present when running the algorithm in the script interpreter).
3. Select the Group Workspace and attempt to run the algorithm. 
4. No error reporter should appear. 

Fixes #27592

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/DataHandling/src/SaveGSS.cpp [hunk 1]
```diff
@@ -715,7 +715,11 @@ std::map<std::string, std::string> SaveGSS::validateInputs() {
   std::map<std::string, std::string> result;
 
   API::MatrixWorkspace_const_sptr input_ws = getProperty("InputWorkspace");
-
+  if (!input_ws) {
+    result.emplace("InputWorkspace",
```
Comment (Harrietbrown) [inline Framework/DataHandling/src/SaveGSS.cpp]: Is there an reason to use `emplace` instead of `results["InputWorkspace"]= "The input workspace cannot be a GroupWorkspace."`?

**Review by Harrietbrown — CHANGES_REQUESTED** [review]
I noticed another small issue that you might as well fix here. The FileProperty doesn't have a file extention associated with it. It should have the same file extentions that `LoadGSS` has.

**Review by Harrietbrown — APPROVED** [review]
Very good. Also good to get SaveGSS adding the file extention as well.
