### PR TITLE
Processing nested components in NexusGeometrySave

### LINKED ISSUE #26717: Processing nested components
Follow up from  #26644. See removed system test, this consistently fails when processing instruments containing eightpacks (groups of tubes)!

I believe that the logic between `ComponentInfoBankHelpers::isSaveableBank` and `NexusGeometrySave::saveInstrument` is to blame. Instruments that contain eight-packs include `Bilby` -> `BILBY_Definition.xml`.

* Create unit test showing faulty behaviour for eight-packs.
* Fix unit test ensuring that we EITHER save the eight-pack or its parent as a NXDetector, but not both!
* Ultimately get system test working too

### PR DESCRIPTION
**Pull request by TakudzwaMakoni**
**Description of work.**

isSaveableBank will skip writing an NXdetector group for a compatible component where the direct ancestor can also be an NXdetector, previously causing H5 group exception and system test failure.

**To test:**

Fixes #26717. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/DataHandling/test/SaveNexusGeometryTest.h [hunk 1]
```diff
@@ -162,7 +164,7 @@ class SaveNexusGeometryTest : public CxxTest::TestSuite {
         Mantid::API::AnalysisDataService::Instance().remove("testWS"));
   }
 
-  void test_characterise_eight_pack_bug() {
+  void test_characterise_eight_pack_bug_fix() {
```
Comment (OwenArnold) [inline Framework/DataHandling/test/SaveNexusGeometryTest.h]: Remove `characterise` from name now.

File: Framework/Geometry/src/Instrument/ComponentInfoBankHelpers.cpp [hunk 2]
```diff
@@ -66,8 +66,14 @@ bool isSaveableBank(const ComponentInfo &compInfo, const size_t idx) {
     if (parentType != Beamline::ComponentType::Rectangular &&
         parentType != Beamline::ComponentType::Structured &&
         parentType != Beamline::ComponentType::Grid) {
-      // if component at index is not a tube then identify it as a bank
+      // check if component is sub-assembly of tube, if so returns false
```
Comment (OwenArnold) [inline Framework/Geometry/src/Instrument/ComponentInfoBankHelpers.cpp]: "a sub-assembly" of a tube? an eight-pack is a super assembly comprising tubes.

File: Framework/Geometry/src/Instrument/ComponentInfoBankHelpers.cpp [hunk 3]
```diff
@@ -66,8 +66,14 @@ bool isSaveableBank(const ComponentInfo &compInfo, const size_t idx) {
...
       if (childType != Beamline::ComponentType::OutlineComposite) {
+        size_t idxBelow = idx - 1;
```
Comment (OwenArnold) [inline Framework/Geometry/src/Instrument/ComponentInfoBankHelpers.cpp]: idxBelow defined like this only guarantees that the component is not a parent, it could still be either a child OR sibling.

**Review by OwenArnold — CHANGES_REQUESTED** [review]
Im not sure I understand your fix.

Also, did you rule out the `DetectorModules` if so, for what reason?

File: Framework/Geometry/src/Instrument/ComponentInfoBankHelpers.cpp (hunk 2 above)
Comment (TakudzwaMakoni) [reply Framework/Geometry/src/Instrument/ComponentInfoBankHelpers.cpp]: that correct, i meant to say that

File: Framework/Geometry/src/Instrument/ComponentInfoBankHelpers.cpp [hunk 4]
```diff
@@ -66,7 +66,7 @@ bool isSaveableBank(const ComponentInfo &compInfo, const size_t idx) {
     if (parentType != Beamline::ComponentType::Rectangular &&
         parentType != Beamline::ComponentType::Structured &&
         parentType != Beamline::ComponentType::Grid) {
-      // if component at index is not a tube then identify it as a bank
+      // check if component is assembly, if so returns false
```
Comment (OwenArnold) [inline Framework/Geometry/src/Instrument/ComponentInfoBankHelpers.cpp]: I don't understand your comment. It's completely legitimate for an assembly to be saved as a `NXdetector` isn't it?

File: Framework/Geometry/src/Instrument/ComponentInfoBankHelpers.cpp [hunk 5]
```diff
@@ -75,6 +75,26 @@ bool isSaveableBank(const ComponentInfo &compInfo, const size_t idx) {
...
+ * @param possibleAncestor : the queried ancestor.
+ * @param current : the queried descendant.
+ */
+bool isAncestorOf(const ComponentInfo &compInfo, const size_t possibleAncestor,
+                  const size_t current) {
+  size_t next = current;
+  do {
+    if (compInfo.parent(next) == possibleAncestor)
+      return true;
+    next = compInfo.parent(next);
```
Comment (OwenArnold) [inline Framework/Geometry/src/Instrument/ComponentInfoBankHelpers.cpp]: I think this might contain a bug. Say we have a chain of ancestors

`1 -> 4 ->6-> 9 -> 15` where `15` is root. 

We input `1` as `current` and `9` as `possibleAncestor`

```
next = 1
4 == 9 //test
next = 4

4 == 9 // test
next = 6

6 == 9
next = 6
```
This is OK. But what happens when I set `possibleAncestor` to `4` and `current` to `4`. Returns false, but should be true.

Also. duplicate calls to `compInfo.parent(next)` seem uncessary.

**Please write for bug and then fix test**

File: Framework/Geometry/test/ComponentInfoBankHelpersTest.h [hunk 6]
```diff
@@ -175,6 +175,46 @@ class ComponentInfoBankHelpersTest : public CxxTest::TestSuite {
     TS_ASSERT_THROWS(offsetFromAncestor(compInfo, ancestorIndex, currentIndex),
                      std::invalid_argument &);
   }
+
+  void test_isAncestorOf_finds_ancestor() {
+
+    auto instrument = ComponentCreationHelper::createMinimalInstrument(
+        V3D(0, 0, -10), V3D(0, 0, 0), V3D(0, 0, 10));
```
Comment (OwenArnold) [inline Framework/Geometry/test/ComponentInfoBankHelpersTest.h]: ```/* inline comments */``` for arguments for your test helpers please

File: Framework/Geometry/test/ComponentInfoBankHelpersTest.h [hunk 7]
```diff
@@ -175,6 +175,46 @@ class ComponentInfoBankHelpersTest : public CxxTest::TestSuite {
...
+
+    // instrument cache to be used with call offsetFromAncestor
+    const auto &compInfo = (*wrappers.first);
+
+    // the source is the child of the root
+    TS_ASSERT(isAncestorOf(compInfo, compInfo.root(), compInfo.source()));
+  }
+
+  void
+  test_isAncestorOf_returns_false_with_child_sibling_or_relative_proposed_as_ancestor() {
```
Comment (OwenArnold) [inline Framework/Geometry/test/ComponentInfoBankHelpersTest.h]: you should have a comment somewhere about the fact that the root is not counted! in fact would definitely want that stated by the doxygen for `isAncestorOf`

File: Framework/NexusGeometry/src/NexusGeometrySave.cpp [hunk 8]
```diff
@@ -785,11 +786,25 @@ void saveInstrument(const Geometry::ComponentInfo &compInfo,
...
   // save NXdetectors
-  for (size_t index = compInfo.root() - 1; index > detInfo.size(); --index) {
+  std::list<size_t> nxDetectorCandidates;
+  for (size_t index = compInfo.root() - 1; index >= detInfo.size(); --index) {
     if (Geometry::ComponentInfoBankHelpers::isSaveableBank(compInfo, index)) {
+      nxDetectorCandidates.push_back(index);
+    }
+  }
+
+  for (std::list<size_t>::iterator index = nxDetectorCandidates.begin();
```
Comment (OwenArnold) [inline Framework/NexusGeometry/src/NexusGeometrySave.cpp]: Can you please combine these loops. 

1. Determine if potentially saveable, (passes `isSaveableBank`) 
2. Then check ancestors using `std::find` would be better.
3. Append to container once has been saved.

Can all be done in one loop.

**Review by OwenArnold — CHANGES_REQUESTED** [review]
Good start. I think you understand how this should work.

File: Framework/NexusGeometry/src/NexusGeometrySave.cpp [hunk 9]
```diff
@@ -34,6 +34,26 @@ namespace Mantid {
...
 namespace NexusGeometrySave {
 
+inline H5::Group safeCreateGroup(const H5::Group &parentGroup,
+                                 const std::string &childGroupName) {
+  H5std_string parentGroupName = H5_OBJ_NAME(parentGroup);
+  H5std_string intendedPath = parentGroupName + "/" + childGroupName;
+  for (hsize_t i = 0; i < parentGroup.getNumObjs(); ++i) {
+    if (parentGroup.getObjTypeByIdx(i) == GROUP_TYPE) {
+      H5std_string child = parentGroup.getObjnameByIdx(i);
+      H5std_string currentPath = parentGroupName + "/" + child;
```
Comment (OwenArnold) [inline Framework/NexusGeometry/src/NexusGeometrySave.cpp]: You shouldn't do this full path comparison. I don't understand why it is needed. I think your implementation is buggy anyway. Just compare the name directly.

File: Framework/NexusGeometry/src/NexusGeometrySave.cpp [hunk 10]
```diff
@@ -34,6 +34,26 @@ namespace Mantid {
 namespace NexusGeometry {
 namespace NexusGeometrySave {
 
+inline H5::Group safeCreateGroup(const H5::Group &parentGroup,
```
Comment (OwenArnold) [inline Framework/NexusGeometry/src/NexusGeometrySave.cpp]: Good attempt at naming, but I wouldn't call something `safe...` if it did throw. Maybe `try...` instead?
* Why is this inline?
* Can you doxygen comments in place explaining that this throws.

File: Testing/SystemTests/tests/analysis/SaveNexusTest.py [hunk 11]
```diff
@@ -0,0 +1,124 @@
...
+from __future__ import (absolute_import, division, print_function)
+from mantid.simpleapi import *
+from mantid.api import FrameworkManager
+import os
+import glob
+
+EXPECTED_EXT = '.expected'
+
+# files blacklisted due to containing duplicate named components in instrument.
+file_blacklist = [("HET_Definition_old.xml","duplicate monitor names"), ("MAPS_Definition.xml","duplicate bank names"),
```
Comment (OwenArnold) [inline Testing/SystemTests/tests/analysis/SaveNexusTest.py]: Good. Rather than copy-paste the messages (since they tend to repeat) could you define them somewhere. Or another approach do something like this...
```python
duplicate_monitor_names = [file1.xml, file2.xml, file5.xml] 
duplicate_bank_names = [file1.xml, file2.xml, file5.xml] 
black_list = duplicate_monitor_names + duplicate_bank_names
```

**Review by OwenArnold — CHANGES_REQUESTED** [review]

File: Framework/Geometry/src/Instrument/ComponentInfoBankHelpers.cpp (hunk 4 above)
Comment (TakudzwaMakoni) [reply Framework/Geometry/src/Instrument/ComponentInfoBankHelpers.cpp]: i think this comment was above an earlier codeblock now deleted. removed

File: Framework/NexusGeometry/src/NexusGeometrySave.cpp (hunk 10 above)
Comment (TakudzwaMakoni) [reply Framework/NexusGeometry/src/NexusGeometrySave.cpp]: im using inline since i call it multiple times, and i figured it was sufficiently small a function? added doxygen

File: Framework/NexusGeometry/src/NexusGeometrySave.cpp (hunk 9 above)
Comment (TakudzwaMakoni) [reply Framework/NexusGeometry/src/NexusGeometrySave.cpp]: refactored

File: Testing/SystemTests/tests/analysis/SaveNexusTest.py (hunk 11 above)
Comment (TakudzwaMakoni) [reply Testing/SystemTests/tests/analysis/SaveNexusTest.py]: done

File: Framework/DataHandling/test/SaveNexusGeometryTest.h [hunk 12]
```diff
@@ -186,6 +186,32 @@ class SaveNexusGeometryTest : public CxxTest::TestSuite {
...
+    ScopedFileHandle fileResource("duplicate_names_test.hdf5");
+    auto destinationFile = fileResource.fullPath();
+
+    Mantid::DataHandling::LoadEmptyInstrument loader;
+    loader.setChild(true);
+    loader.initialize();
+    loader.setProperty("Filename", "HET_Definition_old.xml");
+    loader.setPropertyValue("OutputWorkspace", "dummy");
+    loader.execute();
+    Mantid::API::MatrixWorkspace_sptr ws =
```
[the remark this answers is not in the document]
Comment (TakudzwaMakoni) [reply Framework/DataHandling/test/SaveNexusGeometryTest.h]: removed

File: Framework/DataHandling/test/LoadEmptyInstrumentTest.h [hunk 13]
```diff
@@ -12,6 +12,7 @@
 #include "MantidAPI/AnalysisDataService.h"
 #include "MantidAPI/SpectrumInfo.h"
 #include "MantidDataHandling/LoadEmptyInstrument.h"
+#include "MantidDataHandling/SaveNexusGeometry.h"
```
[the remark this answers is not in the document]
Comment (TakudzwaMakoni) [reply Framework/DataHandling/test/LoadEmptyInstrumentTest.h]: removed

File: Framework/Geometry/src/Instrument/ComponentInfoBankHelpers.cpp (hunk 5 above)
Comment (TakudzwaMakoni) [reply Framework/Geometry/src/Instrument/ComponentInfoBankHelpers.cpp]: refactored

Comment (TakudzwaMakoni) [reply Framework/Geometry/src/Instrument/ComponentInfoBankHelpers.cpp]: test added

File: Framework/Geometry/test/ComponentInfoBankHelpersTest.h (hunk 6 above)
Comment (TakudzwaMakoni) [reply Framework/Geometry/test/ComponentInfoBankHelpersTest.h]: done

File: Framework/Geometry/test/ComponentInfoBankHelpersTest.h (hunk 7 above)
Comment (TakudzwaMakoni) [reply Framework/Geometry/test/ComponentInfoBankHelpersTest.h]: done

File: Framework/NexusGeometry/src/NexusGeometrySave.cpp (hunk 8 above)
Comment (TakudzwaMakoni) [reply Framework/NexusGeometry/src/NexusGeometrySave.cpp]: done

File: Framework/Geometry/test/ComponentInfoBankHelpersTest.h [hunk 14]
```diff
@@ -175,6 +175,122 @@ class ComponentInfoBankHelpersTest : public CxxTest::TestSuite {
...
+    auto instrument = ComponentCreationHelper::createTestInstrumentRectangular2(
+        1 /*number of banks*/, 2 /*pixels*/);
+    auto wrappers = InstrumentVisitor::makeWrappers(*instrument);
+
+    // instrument cache to be used with call offsetFromAncestor
+    const auto &compInfo = (*wrappers.first);
+
+    size_t bank = 6;                                 // index of bank
+    auto pixels = compInfo.detectorsInSubtree(bank); // 4 detectors of bank
+    TS_ASSERT(isSaveableBank(compInfo, bank)); // assert bank is NXdetector
```
Comment (OwenArnold) [inline Framework/Geometry/test/ComponentInfoBankHelpersTest.h]: Do not check `isSaveableBank` in this test we don't confuse the two independent functions.

**Review by OwenArnold — CHANGES_REQUESTED** [review]
Pretty good. 

Some improvements to improve quality further.

File: Framework/Geometry/src/Instrument/ComponentInfoBankHelpers.cpp [hunk 15]
```diff
@@ -33,8 +33,8 @@ bool isDetectorFixedInBank(const ComponentInfo &compInfo,
   return false;
 }
 
-/*
-* Function: isSaveableBank. Returns true if the index in the Instrument cache is
+/** Function: isSaveableBank. Returns true if the index in the Instrument cache
```
[the remark this answers is not in the document]
Comment (TakudzwaMakoni) [reply Framework/Geometry/src/Instrument/ComponentInfoBankHelpers.cpp]: fixed

File: Framework/Geometry/src/Instrument/ComponentInfoBankHelpers.cpp [hunk 16]
```diff
@@ -66,7 +66,7 @@ bool isSaveableBank(const ComponentInfo &compInfo, const size_t idx) {
     if (parentType != Beamline::ComponentType::Rectangular &&
         parentType != Beamline::ComponentType::Structured &&
         parentType != Beamline::ComponentType::Grid) {
-      // if component at index is not a tube then identify it as a bank
+      // check if component type mathces tube
```
[the remark this answers is not in the document]
Comment (TakudzwaMakoni) [reply Framework/Geometry/src/Instrument/ComponentInfoBankHelpers.cpp]: done

File: Framework/Geometry/test/ComponentInfoBankHelpersTest.h (hunk 14 above)
Comment (TakudzwaMakoni) [reply Framework/Geometry/test/ComponentInfoBankHelpersTest.h]: removed

File: Testing/SystemTests/tests/analysis/SaveNexusTest.py [hunk 17]
```diff
@@ -0,0 +1,137 @@
...
+
+
+class LoadAndSaveLotsOfInstruments(object):
+    def __getDataFileList__(self):
+        # get a list of directories to look in
+        direc = config['instrumentDefinition.directory']
+        print("Looking for instrument definition files in: %s" % direc)
+        cwd = os.getcwd()
+        os.chdir(direc)
+        myFiles = glob.glob("*Definition*.xml")
```
[the remark this answers is not in the document]
Comment (TakudzwaMakoni) [reply Testing/SystemTests/tests/analysis/SaveNexusTest.py]: renamed

File: Testing/SystemTests/tests/analysis/SaveNexusTest.py [hunk 18]
```diff
@@ -0,0 +1,137 @@
...
+        valid_files.sort()
+        for filename in valid_files:
+            files.append(os.path.join(direc, filename))
+        files.sort()
+        return files
+
+    def __removeFiles__(self, files):
+        for ws in files:
+            try:
+                path = os.path.join(os.path.expanduser("~"), ws)
```
[the remark this answers is not in the document]
Comment (TakudzwaMakoni) [reply Testing/SystemTests/tests/analysis/SaveNexusTest.py]: done

File: Testing/SystemTests/tests/analysis/SaveNexusTest.py [hunk 19]
```diff
@@ -0,0 +1,137 @@
...
+        """Do all of the real work of loading and saving the file"""
+        print("----------------------------------------")
+        print("Loading '%s'" % filename)
+        wksp = LoadEmptyInstrument(filename)
+        save_file_name = "system_test_save.nxs"
+        save_path = os.path.join(os.path.expanduser("~"), save_file_name)
+        comp_info = wksp.componentInfo()
+        if not (comp_info.hasSource()):
+            print("Instrument definition has no source. Skipping test.")
+        elif not all([i == 0 for i in comp_info.position(comp_info.sample())]):
```
[the remark this answers is not in the document]
Comment (TakudzwaMakoni) [reply Testing/SystemTests/tests/analysis/SaveNexusTest.py]: fixed

File: Testing/SystemTests/tests/analysis/SaveNexusTest.py [hunk 20]
```diff
@@ -0,0 +1,137 @@
...
+            print("Sample in instrument definition not at origin. Skipping test.")
+        else:
+            print("saving '%s'" % filename)
+            SaveNexusGeometry(wksp, save_path)
+            if wksp is None:
```
[the remark this answers is not in the document]
Comment (TakudzwaMakoni) [reply Testing/SystemTests/tests/analysis/SaveNexusTest.py]: removed

File: Testing/SystemTests/tests/analysis/SaveNexusTest.py [hunk 21]
```diff
@@ -0,0 +1,137 @@
...
+                return False
+
+            # TODO standard tests
```
[the remark this answers is not in the document]
Comment (TakudzwaMakoni) [reply Testing/SystemTests/tests/analysis/SaveNexusTest.py]: removed

File: Testing/SystemTests/tests/analysis/SaveNexusTest.py [hunk 22]
```diff
@@ -0,0 +1,137 @@
...
+            if wksp.getNumberHistograms() <= 0:
```
[the remark this answers is not in the document]
Comment (TakudzwaMakoni) [reply Testing/SystemTests/tests/analysis/SaveNexusTest.py]: removed

File: Testing/SystemTests/tests/analysis/SaveNexusTest.py [hunk 23]
```diff
@@ -0,0 +1,137 @@
...
+                del wksp
+                return False
+            if wksp.getMemorySize() <= 0:
```
[the remark this answers is not in the document]
Comment (TakudzwaMakoni) [reply Testing/SystemTests/tests/analysis/SaveNexusTest.py]: removed

File: Testing/SystemTests/tests/analysis/SaveNexusTest.py [hunk 24]
```diff
@@ -0,0 +1,137 @@
...
+                path = os.path.join(os.path.expanduser("~"), ws)
+                os.remove(path)
+            except:
+                pass
+
+    def __loadSaveAndTest__(self, filename):
+        """Do all of the real work of loading and saving the file"""
+        print("----------------------------------------")
+        print("Loading '%s'" % filename)
+        wksp = LoadEmptyInstrument(filename)
```
[the remark this answers is not in the document]
Comment (TakudzwaMakoni) [reply Testing/SystemTests/tests/analysis/SaveNexusTest.py]: done

File: Framework/Geometry/src/Instrument/ComponentInfoBankHelpers.cpp (hunk 15 above)
[the remark this answers is not in the document]
Comment (TakudzwaMakoni) [reply Framework/Geometry/src/Instrument/ComponentInfoBankHelpers.cpp]: added a test to NexusGeoetrySaveTest

**Review by OwenArnold — DISMISSED** [review]

**Review by martyngigg — APPROVED** [review]
