### PR TITLE
Indirect - Bayes - Move Run button for disabling while processing

### LINKED ISSUE #23827: Indirect - Bayes Interface - Move the run button and disable buttons
**Original reporter:** Spencer

### Expected behavior
The Run button should be above the output options.
The run button and plot options should be disabled while running and plotting.

### Steps to reproduce the behavior
1.`Interfaces`->`Indirect`->`Bayes`

### Platforms affected
All

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR moves the run button above the output options on the Indirect Bayes interface.
This PR ensures the run, plot and save options are disabled while running and plotting is taking place.
This PR also tidies up some of the code previously used to disable buttons in other interfaces.

**To test:**
1. `Interfaces`->`Indirect`->`Bayes`
2. Load the data below
3. Click `Run` and ensure the run, plot and save options are disabled
4. Click `Plot` and ensure the run, plot and save options are disabled

- For the third interface `Stretch`, clicking `Plot` should result in an error message. This is a good way of checking that all the buttons are re-enabled even after an error.

**Data Files**

**ResNorm**
[irs26173_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2491289/irs26173_graphite002_red.zip)
[irs26173_graphite002_res.zip](https://github.com/mantidproject/mantid/files/2491290/irs26173_graphite002_res.zip)

**Quasi**
[irs26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2491291/irs26176_graphite002_red.zip)
[irs26173_graphite002_res.zip](https://github.com/mantidproject/mantid/files/2491292/irs26173_graphite002_res.zip)

**Stretch**
[irs26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2491291/irs26176_graphite002_red.zip)
[irs26173_graphite002_res.zip](https://github.com/mantidproject/mantid/files/2491292/irs26173_graphite002_res.zip)

Fixes #23827 

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by LowriJenkins — COMMENTED** [review]
I've Reviewed as much of this as I can, The code is fine and ResNorm works fine, however the other tabs use algorithms that don't run on linux so I am unable to review them.

**Comment by SpencerHowells** [comment]
@robertapplin @SamJenkins1 Forgot to remind you that the other tabs use Fortran code which is only distributed for Windows.

**Review by mantid-roman — CHANGES_REQUESTED** [review]
If a default save directory is set Run doesn't work in Quasi and Stretch.

**Comment by robertapplin** [comment]
@mantid-roman Thanks for spotting this. It should work fine now.

**Comment by mantid-roman** [comment]
@robertapplin It works now. One last question: the plot on Stretch page doesn't show the fit or diff lines after a fit, is it by design or a bug?

**Comment by robertapplin** [comment]
@mantid-roman  That is strange, I believe this is a bug - I will create a new issue for this. Seeing as the Bayes interface tends to be unmanaged, this problem may have been around for a while.

**Review by mantid-roman — DISMISSED** [review]

File: qt/scientific_interfaces/Indirect/Quasi.cpp [hunk 1]
```diff
@@ -449,61 +429,97 @@ void Quasi::saveClicked() {
...
       AnalysisDataService::Instance().retrieveWS<MatrixWorkspace>(resultName);
-  int numSpectra = (int)resultWS->getNumberHistograms();
+  int const numSpectra = (int)resultWS->getNumberHistograms();
   IndirectTab::checkADSForPlotSaveWorkspace(resultName, true);
-  QString QresultWS = QString::fromStdString(resultName);
-  auto paramNames = {"Amplitude", "FWHM", "Beta"};
-  for (std::string paramName : paramNames) {
+  QString const QresultWS = QString::fromStdString(resultName);
+  auto const paramNames = {"Amplitude", "FWHM", "Beta"};
+  for (std::string const paramName : paramNames) {
```
Comment (soininen) [inline qt/scientific_interfaces/Indirect/Quasi.cpp]:
```suggestion
  for (std::string const &paramName : paramNames) {
```

**Review by soininen — CHANGES_REQUESTED** [review]

**Review by soininen — APPROVED** [review]
