### PR TITLE
Fix issues found during unscripted testing (Reflectometry)

### LINKED ISSUE #16227: Fix issues found during unscripted testing (Reflectometry)
We've found the following issues during unscripted testing:

Old Reflectometry GUI:
- RB Search does not seem to be working anymore (it does not work in Release 3.6 either but it does work in Release 3.5)
- ~~Runs are not transferred from the Search section to the Process section (does not seem to work in Release 3.5 either)~~.
- Individual plots show up instead of overlaying single plot when 'Plot' button is clicked. (Worked for 3.6 so I believe it's to do with recent changes)

Reflectometry (Polref) GUI:
- Can't load a TBL file with two transmission runs separated by commas.
- Strange behaviour found when clearing repeatedly a table

### PR DESCRIPTION
**Pull request by raquelalvarezbanos**
A PR to fix some issues found during unscripted testing:

Old Reflectometry GUI:
- RB Search does not seem to be working anymore (it does not work in Release 3.6 either but it does work in Release 3.5)
- Individual plots show up instead of overlaying single plot when 'Plot' button is clicked. (Worked for 3.6 so I believe it's to do with recent changes)

Reflectometry (Polref) GUI:
- Can't load a TBL file with two transmission runs separated by commas.
- Strange behaviour found when clearing a table repeatedly

**To test:**

See above and make sure the issues are fixed.

Fixes #16227.

Does not need to be in the release notes, issues were discovered during unscripted testing.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by MattKing06** [comment]
After testing these last remaining issues with the reflectometry interfaces I think it's fine to :shipit: now

File: MantidQt/CustomInterfaces/src/Reflectometry/GenericDataProcessorPresenter.cpp [hunk 1]
```diff
@@ -1195,7 +1195,7 @@ void GenericDataProcessorPresenter::clearSelected() {
       m_model->setData(m_model->index(*row, i), "");
     }
     // 'Group' column
-    m_model->setData(m_model->index(*row, m_columns - 2), getUnusedGroup());
+    m_model->setData(m_model->index(*row, m_columns - 2), getUnusedGroup(ignore));
```
Comment (FedeMPouzols) [inline MantidQt/CustomInterfaces/src/Reflectometry/GenericDataProcessorPresenter.cpp]: As this was an issue in the generic stuff, would there be a way to regression-test this?

**Comment by FedeMPouzols** [comment]
Small changes to fix a few small issues in the reflectometry interfaces.
