### PR TITLE
Fix ManageUserDirectories lifetime management when pressing escape 

### LINKED ISSUE #29559: Crash after Escape and re-open the Manage User Directories dialog
Mantid crashes if you press Escape on the Manage User Directories dialog and then re-open it.

### Steps to reproduce the behavior
- Go to File -> Manage User Directories
- Press Esc
- Go to File -> Manage User Directories
- Mantid crashes

### Platforms affected
Windows, Ubuntu, possibly all.
Seen in v5.0.0 and nightly in both MantidPlot and MantidWorkbench

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

Replaces lifetime management mechanism for global version of ManageUserDirectories so that all routes out of the dialog end up deleting the static pointer. The fix is in the first commit and the remaining commits perform some code cleanup/modernization and add some basic unit tests using the QtTest framework.

**To test:**

Follow the instructions in the related issue and workbench should no longer crash.

Play with adding/removing directories and ensure that clicking cancel does not save the config but clicking okay does. The dialog on raising again should be populated with the previous values. Also check the user properties file contains the new values.

Fixes #29559 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/widgets/common/src/ManageUserDirectories.cpp [hunk 1]
```diff
@@ -9,30 +9,79 @@
...
+const QString EXTENSIONS{"pbExt"};
+} // namespace ButtonPrefix
+
+namespace ConfigKeys {
+const std::string DATASEARCH_DIRS{"datasearch.directories"};
+const std::string PYTHONSCRIPTS_DIRS{"pythonscripts.directories"};
+const std::string USERPYTHONPLUGINS_DIRS{"user.python.plugins.directories"};
+const std::string DATASEARCH_ARCHIVE{"datasearch.searcharchive"};
+const std::string DEFAULT_FACILITY{"default.facility"};
+const std::string DEFAULTSAVE_DIR{"defaultsave.directory"};
```
Comment (robertapplin) [inline qt/widgets/common/src/ManageUserDirectories.cpp:31]: Would it be better if these sorts of variables were `static`?

File: qt/widgets/common/src/ManageUserDirectories.cpp [hunk 2]
```diff
@@ -125,13 +159,18 @@ void ManageUserDirectories::loadProperties() {
   }
 
   // default save directory
-  QString saveDir = QString::fromStdString(
-                        Mantid::Kernel::ConfigService::Instance().getString(
-                            "defaultsave.directory"))
-                        .trimmed();
+  QString saveDir =
```
Comment (robertapplin) [inline qt/widgets/common/src/ManageUserDirectories.cpp:162]: Can this be `const auto`?

File: qt/widgets/common/src/ManageUserDirectories.cpp [hunk 3]
```diff
@@ -252,26 +276,33 @@ void ManageUserDirectories::addDirectory() {
...
 }
 
+/// Browse to find a new directory. The start directory
+/// is the last directory accessed by the application. The
+/// directory is added to the list based on the object sender
 void ManageUserDirectories::browseToDirectory() {
   QSettings settings;
-  QString lastDirectory =
-      settings.value("ManageUserSettings/last_directory", "").toString();
+  const QString lastDirectory =
```
Comment (robertapplin) [inline qt/widgets/common/src/ManageUserDirectories.cpp:284]: `auto` instead of `QString` like in your above changes?

File: qt/widgets/common/src/ManageUserDirectories.cpp [hunk 4]
```diff
@@ -252,26 +276,33 @@ void ManageUserDirectories::addDirectory() {
...
+      settings.value(QSettingsKeys::LastDirectory, "").toString();
 
-  QString newDir = QFileDialog::getExistingDirectory(
+  const QString newDir = QFileDialog::getExistingDirectory(
```
Comment (robertapplin) [inline qt/widgets/common/src/ManageUserDirectories.cpp:287]: `auto` here too

File: qt/widgets/common/src/ManageUserDirectories.cpp [hunk 5]
```diff
@@ -297,35 +330,21 @@ void ManageUserDirectories::moveDown() {
...
   const QString newDir = QFileDialog::getExistingDirectory(
       this, tr("Select New Default Save Directory"), lastDirectory,
       QFileDialog::ShowDirsOnly);
 
-  if (newDir != "") {
-    QString path = newDir + QDir::separator();
-    path.replace('\\', '/');
-    settings.setValue("ManageUserSettings/last_directory", path);
+  if (!newDir.isEmpty()) {
+    const QString path = newDir + QDir::separator();
```
Comment (robertapplin) [inline qt/widgets/common/src/ManageUserDirectories.cpp:346]: Could `auto` be used here too?

**Review by robertapplin — CHANGES_REQUESTED** [review]
Changes look good, and some very nice unit tests! It all is working as expected. I just have a few (picky) comments

File: qt/widgets/common/src/ManageUserDirectories.cpp (hunk 2 above)
Comment (martyngigg) [reply qt/widgets/common/src/ManageUserDirectories.cpp:162]: Thanks! I think I got bored of changing from QString->auto. I'll get them updated.

File: qt/widgets/common/src/ManageUserDirectories.cpp (hunk 1 above)
Comment (martyngigg) [reply qt/widgets/common/src/ManageUserDirectories.cpp:31]: It doesn't make too much difference lifetime wise but I could move up the anonymous namespace so they are not visible outside of this code unit. I'll do that.

**Comment by martyngigg** [comment]
Thanks, Rob. I've made those changes now.

**Comment by robertapplin** [comment]
> Thanks, Rob. I've made those changes now.

Thanks Martyn, looks good 👍 There seems to be a clang format problem.

**Comment by martyngigg** [comment]
Cheers. Should be fixed now.

**Review by robertapplin — APPROVED** [review]
