### PR TITLE
Fix default dimension names from CreateMD being incompatible with MaskMD

### LINKED ISSUE #14368: Default dimension names from CreateMD incompatible with MaskMD algorithm
The default dimension names in workspaces created with CreateMD (and in various other places) are of the form '[H,0,0]'. This then causes an error (probably due to commas) when specifying the dimension name and range for a mask in the MaskMD algorithm.
Either default names should be changed, or MaskMD changed so that names of this form do not cause an error.

This issue is related to a general review of masks: #12689.

### PR DESCRIPTION
**Pull request by matthew-d-jones**
Fixes #14368

A three dimensional workspace created with CreateMD has the dimension names "[H,0,0]", "[0,K,0]", "[0,0,L]" and "DeltaE". Specifying dimensions to mask with MaskMD is done by passing a list of dimension names. This list is split on commas, therefore entering Dimensions="[H,0,0], [0,K,0],[0,0,L],DeltaE" results in getProperty returning a list of 10 dimension names and MaskMD throws an error.

Ideally this would be solved by changing ArrayProperty and allowing an algorithm to use a setting to allow "sub-lists" in brackets. An issue has been created to do this #14413. In the meantime MaskMD has been changed to get the list string with getPropertyValue and carry out it's own parsing for dimension names.

Unit tests cover the changes.

**For Tester:**

Please review the code.
The following code can be used to test the changes. Previously this code would return an error claiming that too many dimension names were specified. Now it should run successfully.

``` python

input_runs = list()
psi = list()
gs = list()
gl = list()
for i in range(1, 5):
    current_ws = CreateSimulationWorkspace(Instrument='MAR', BinParams=[-3,1,3], UnitX='DeltaE', OutputWorkspace='input_ws_' + str(i))
    input_runs.append(current_ws.name())
    psi.append(float(5 * i))
    gl.append(0.0)
    gs.append(0.0)

# Convert and merge
new_merged = CreateMD(input_runs, Emode='Direct', Alatt=[1.4165, 1.4165,1.4165], Angdeg=[ 90, 90, 90], u=[1, 0, 0,], v=[0,1,0], Psi=psi, Gl=gl, Gs=gs, EFix=3.0)

# Show dimensionality and dimension names
ndims = new_merged.getNumDims()
for i in range(ndims):
    dim = new_merged.getDimension(i)
    print dim.getName()

MaskMD(new_merged, Dimensions="[H,0,0],[0,K,0],[0,0,L],DeltaE", Extents=[-1,1,-1,1,-1,1,-1,1])

```

### CODE REVIEW

File: Framework/MDAlgorithms/src/MaskMD.cpp [hunk 1]
```diff
@@ -4,14 +4,106 @@
...
+ * Split the input string on commas and trim leading and trailing whitespace
+ * from the results
+ */
+std::vector<std::string> splitByCommas(const std::string &names_string) {
+  std::vector<std::string> names_split_by_commas;
+  boost::split(names_split_by_commas, names_string, boost::is_any_of(","));
+
+  // Remove leading/trailing whitespace from potential dimension name
+  for (auto &name : names_split_by_commas) {
+    boost::trim(name);
```
Comment (picatess) [inline Framework/MDAlgorithms/src/MaskMD.cpp]: Nice

**Comment by picatess** [comment]
* Code Review: Code looks good and well tested.
* Followed test instructions and seems to work without issues
