### PR TITLE
Fix Cppcheck warnings

### LINKED ISSUE #20946: Fix cppcheck warnings
New cppcheck version found several problems in our code ( for example http://builds.mantidproject.org/job/master_cppcheck/1261/cppcheckResult/)

### PR DESCRIPTION
**Pull request by AndreiSavici**
**To test:**
Code review and builds should pass

Fixes #20946. 

**Release Notes** 

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Algorithms/src/RemovePromptPulse.cpp [hunk 1]
```diff
@@ -63,15 +63,7 @@ double getMedian(const API::Run &run, const std::string &name) {
 }
 
 void getTofRange(MatrixWorkspace_const_sptr wksp, double &tmin, double &tmax) {
-  DataObjects::EventWorkspace_const_sptr eventWksp =
```
Comment (peterfpeterson) [inline Framework/Algorithms/src/RemovePromptPulse.cpp]: The old implementation has a mistake in it, but the new one ignores the fact that `EventWorkspace` can have events outside of the binned range. That is what this was supposed to handle. I think changing line 69 to
```
const bool isEvent = bool(eventWksp);
```
would fix it.

File: Framework/DataHandling/src/LoadRawHelper.cpp [hunk 2]
```diff
@@ -1309,30 +1309,23 @@ bool LoadRawHelper::isAscii(const std::string &filename) {
  *  @return true if Exclude Monitors option is selected,otherwise false
  */
 bool LoadRawHelper::isExcludeMonitors(const std::string &monitorOption) {
-  bool bExclude;
```
Comment (peterfpeterson) [inline Framework/DataHandling/src/LoadRawHelper.cpp]: New code is much better

**Review by quantumsteve — APPROVED** [review]

**Review by peterfpeterson — CHANGES_REQUESTED** [review]

File: Framework/Algorithms/src/RemovePromptPulse.cpp [hunk 3]
```diff
@@ -63,7 +63,13 @@ double getMedian(const API::Run &run, const std::string &name) {
 }
 
 void getTofRange(MatrixWorkspace_const_sptr wksp, double &tmin, double &tmax) {
-  wksp->getXMinMax(tmin, tmax);
+  DataObjects::EventWorkspace_const_sptr eventWksp =
+    boost::dynamic_pointer_cast<const DataObjects::EventWorkspace>(wksp);
+  if (eventWksp == nullptr) {
```
Comment (peterfpeterson) [inline Framework/Algorithms/src/RemovePromptPulse.cpp]: You want to switch the body of the `if`/`else`

**Review by peterfpeterson — CHANGES_REQUESTED** [review]

**Review by peterfpeterson — APPROVED** [review]

**Review by peterfpeterson — APPROVED** [review]
