### PR TITLE
Stop PSIBackground crash with groups

### LINKED ISSUE #28713: PSI background subtraction crash
Trying to do a PSI background subtraction on a group workspace causes the algorithm to crash.

We should either not allow a group workspace to be selected or make part of the validation check that it is not a group workspace

### PR DESCRIPTION
**Pull request by AnthonyLim23**
When using a group workspace in PSIBackgroundSubtraction, Mantid would crash. This fixes it.

**To test:**
1. Open Muon Analysis
2. Load PSI data
3. Use the PSIBackgroundSubtraction alg with the grouped workspace as the input
4. It wont crash

If you want it to work with counts data, you will need to set the first good data and time zero to 0. 

Fixes #28713. 

---
This is not in the release notes as this is a new algorithm for this release
#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Muon/test/PSIBackgroundSubtractionTest.h [hunk 1]
```diff
@@ -98,6 +98,25 @@ class PSIBackgroundSubtractionTest : public CxxTest::TestSuite {
...
+    PSIBackgroundSubtraction alg;
+    auto ws = createCountsTestWorkspace(2, 100);
+    IAlgorithm_sptr groupingAlg =
+        AlgorithmManager::Instance().createUnmanaged("GroupWorkspaces");
+    groupingAlg->initialize();
+    groupingAlg->setProperty("InputWorkspaces", ws);
+    groupingAlg->setPropertyValue("OutputWorkspace", "group");
+    groupingAlg->execute();
+
+    WorkspaceGroup_sptr group = groupingAlg->getProperty("OutputWorkspace");
```
Comment (AnthonyLim23) [inline Framework/Muon/test/PSIBackgroundSubtractionTest.h:110]:
```suggestion
    std::string group = groupingAlg->getProperty("OutputWorkspace");
```

**Review by StephenSmith25 — APPROVED** [review]
Prevents the crash, good work 👍
