### PR TITLE
This fixes `ResampleX` for `PreserveEvents=False`

### LINKED ISSUE #22158: ResampleX fails to create Histogram from input EventWorkspace with PreserveEvents=False
ResampleX  fails to make Workspace2D from EventWorkspace if PreserveEvents=False due to incorrect BinEdges

### Expected behavior
ResampleX to return Workspace2D from EventWorkspace input with PreserveEvents=False

### Actual behavior
Fails to setup the correct BinEdges for the Histogram:
```
ResampleX-[Notice] ResampleX started
ResampleX-[Error] ResampleX: Histogram: size mismatch of BinEdges: (16000 != 16001)
ResampleX-[Error] Error in execution of algorithm ResampleX:
ResampleX-[Error] ResampleX: error (see log)
```

### Steps to reproduce the behavior
Run this script to see it succeed with PreserveEvents=True and then fail with PreserveEvents=False

```
from mantid.simpleapi import *

wksp='wksp'
binning = "0.05,16000,3.5"
lambdaMin, lambdaBinning, lambdaMax = [ float(x) for x in binning.split(',') ]
lambdaDelta = (lambdaMax - lambdaMin) / lambdaBinning

print(lambdaMin, lambdaDelta, lambdaMax)
CreateSampleWorkspace(OutputWorkspace=wksp,
                      WorkspaceType='Event',
                      Xmin=lambdaMin,
                      Xmax=lambdaMax,
                      BinWidth=lambdaBinning,
                      XUnit='Wavelength')


ResampleX(InputWorkspace=wksp,
          OutputWorkspace=wksp,
          XMin=[lambdaMin],
          XMax=[lambdaMax],
          NumberBins=int(lambdaBinning),
          PreserveEvents=True)

print("-"*35)
print("PreserveEvents == True => Success!")
print("-"*35)

ResampleX(InputWorkspace=wksp,
          OutputWorkspace=wksp,
          XMin=[lambdaMin],
          XMax=[lambdaMax],
          NumberBins=int(lambdaBinning),
          PreserveEvents=False)
print("-"*35)
print("PreserveEvents == False => Success!")
print("-"*35)
```

### Platforms affected
Distributor ID:	RedHatEnterpriseWorkstation
Release:	7.4

### PR DESCRIPTION
**Pull request by nvaytet**
**Description of work.**

Done by adding a `+1` to the number of bins in `ResampleX.cpp`.
In addition, tests actually executing the `ResampleX` algorithm were added to `ResampleXTest.h`.
These also illustrate the fact that the algorithm now works with `PreserveEvents=False`.
Some tests were also added to test the algorithm on a Workspace2D instead of just the EventWorkspace.
However, this only works if the workspace does not contain distribution data.
This issue has been reported in #22562.
Finally, a slightly more informative error message is thrown by the `VectorHelper::rebin` function.

**To test:**

```
from mantid.simpleapi import *

wksp='wksp'
binning = "0.05,16000,3.5"
lambdaMin, lambdaBinning, lambdaMax = [ float(x) for x in binning.split(',') ]
lambdaDelta = (lambdaMax - lambdaMin) / lambdaBinning

print(lambdaMin, lambdaDelta, lambdaMax)
CreateSampleWorkspace(OutputWorkspace=wksp,
                      WorkspaceType='Event',
                      Xmin=lambdaMin,
                      Xmax=lambdaMax,
                      BinWidth=lambdaDelta,
                      XUnit='Wavelength')


ResampleX(InputWorkspace=wksp,
          OutputWorkspace=wksp,
          XMin=[lambdaMin],
          XMax=[lambdaMax],
          NumberBins=int(lambdaBinning),
          PreserveEvents=True)

print("-"*35)
print("EventWorkspace: PreserveEvents == True => Success!")
print("-"*35)

ResampleX(InputWorkspace=wksp,
          OutputWorkspace=wksp,
          XMin=[lambdaMin],
          XMax=[lambdaMax],
          NumberBins=int(lambdaBinning),
          PreserveEvents=False)
print("-"*35)
print("EventWorkspace: PreserveEvents == False => Success!")
print("-"*35)
```

See also new tests in `AlgorithmsTest`.

Fixes #22158 

Does this update require release notes?
- [ ] Yes
- [x] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Algorithms/test/ResampleXTest.h [hunk 1]
```diff
@@ -161,6 +170,258 @@ class ResampleXTest : public CxxTest::TestSuite {
...
+    TS_ASSERT_DELTA(Y1[2], 4.0, tolerance);
+
+    TS_ASSERT_EQUALS(E1.size(), 50);
+    TS_ASSERT_DELTA(E1[0], sqrt(4.0), tolerance);
+    TS_ASSERT_DELTA(E1[1], sqrt(4.0), tolerance);
+
+    // Check the second workspace index (from 0 to 150)
+    auto &X2 = outWS->x(1);
+    auto &Y2 = outWS->y(1);
+    auto &E2 = outWS->e(1);
```
Comment (SimonHeybrock) [inline Framework/Algorithms/test/ResampleXTest.h]: Personally I would usually attempt to test as much of the data as possible, i.e., either make the workspace smaller (just 2 spectra with 2 bins each), or write the asserts in a loop, maybe.

File: Framework/Algorithms/test/ResampleXTest.h [hunk 2]
```diff
@@ -161,6 +170,258 @@ class ResampleXTest : public CxxTest::TestSuite {
     // Remove workspace from the data service.
     AnalysisDataService::Instance().remove(outWSName);
   }
+
+  // Set-up a generic function for running tests for EventWorkspace
+  void do_testResampleXEventWorkspace(EventType eventType, bool inPlace,
+                                      bool PreserveEvents,
+                                      bool expectOutputEvent) {
```
Comment (SimonHeybrock) [inline Framework/Algorithms/test/ResampleXTest.h]: I don't see why `expectOutputEvent` is a separate flag? Isn't it always the same as `PreserveEvents`?

File: Framework/Algorithms/test/ResampleXTest.h [hunk 3]
```diff
@@ -161,6 +170,258 @@ class ResampleXTest : public CxxTest::TestSuite {
...
+  void testWorkspace2D_InPlace_NoDistribution() {
+    do_testResampleXWorkspace2D(true, false);
+  }
+
+  void testWorkspace2D_NotInPlace_NoDistribution() {
+    do_testResampleXWorkspace2D(false, false);
+  }
+
+  void xtestWorkspace2D_InPlace_WithDistribution() {
+    do_testResampleXWorkspace2D(true, true);
```
Comment (SimonHeybrock) [inline Framework/Algorithms/test/ResampleXTest.h]: If you disable a test, you should definitely put a comment explaining why it is disabled, referencing the issue you created.

File: Framework/Algorithms/test/ResampleXTest.h [hunk 4]
```diff
@@ -161,6 +170,258 @@ class ResampleXTest : public CxxTest::TestSuite {
...
+  }
+
+  void xtestWorkspace2D_NotInPlace_WithDistribution() {
+    do_testResampleXWorkspace2D(false, true);
+  }
+
+private:
+  // Function to create 2D Workspace, copied from RebinTest.h
```
Comment (SimonHeybrock) [inline Framework/Algorithms/test/ResampleXTest.h]: Do not copy code. Either extract it to a common place, or use the following to create the same workspace using the new workspace factor functions from `DataObjects/WorkspaceCreation.h`:

```cpp
auto ws = create<Workspace2D>(ylen, Histogram(BinEdges(xlen, HistogramData::LinearGenerator(0.5, 0.75)), Counts(xlen - 1, 3.0));
```

**Review by SimonHeybrock — CHANGES_REQUESTED** [review]
Looks good, a couple of small comments:

File: Framework/Algorithms/test/ResampleXTest.h [hunk 5]
```diff
@@ -171,158 +174,159 @@ class ResampleXTest : public CxxTest::TestSuite {
...
+    double countVal = 3.0;
+
+    Workspace2D_sptr ws = create<Workspace2D>(
+        ylen, Histogram(BinEdges(xlen + 1,
+                                 HistogramData::LinearGenerator(0.5, deltax)),
+                        Counts(xlen, countVal)));
+    ws->setDistribution(withDistribution);
+    AnalysisDataService::Instance().add(inName, ws);
+
+    // Check the size of the input workspace
```
Comment (SimonHeybrock) [inline Framework/Algorithms/test/ResampleXTest.h]: This is a test of `create`, so it should not be in this file (tests for this exist already in `WorkspaceCreationTest.h`). In general, avoid testing setup code, it just adds noise and makes the test hard to read.

File: Framework/Algorithms/test/ResampleXTest.h [hunk 6]
```diff
@@ -393,35 +403,21 @@ class ResampleXTest : public CxxTest::TestSuite {
     do_testResampleXWorkspace2D(true, false);
   }
 
-  void testWorkspace2D_NotInPlace_NoDistribution() {
+  void xtestWorkspace2D_NotInPlace_NoDistribution() {
```
Comment (SimonHeybrock) [inline Framework/Algorithms/test/ResampleXTest.h]: Why disabled now?

**Review by SimonHeybrock — APPROVED** [review]
