### PR TITLE
Fix `PDCalibration` with workspace indices

### LINKED ISSUE #36123: `PDCalibration` is not fitting peaks when using `StartWorkspaceIndex` and `StopWorkspaceIndex`
**Describe the bug**

`PDCalibration` is largely a wrapper of `FitPeaks`, which has the option to specify start/stop workspace indices to only fit peaks within specific spectra but not others.  Recent work in PR #35837 exposed these properties to users of `PDCalibration`.  

For unknown  reasons, when used in this way `PDCalibration` is failing to fit all peaks in the indicated spectrum.

**To Reproduce**

1. Load neutron data converted to d-spacing, and load peaks from a CIF file
2. To run correctly on one spectrum, use the `ExtractSpectra` algorithm with a single workspace ID.
3. Pass the output workspace from `ExtractSpectra` to `PDCalibration` and observe the fit peaks -- it should contain all peaks.
4. Now run `PDCalibration` with the original dataset indicating `StartWorkspaceIndex` and `StopWorkspaceIndex` equal to the index used before.
5. Observe the fit peaks.  For some reason, not all are being fit.

**Expected behavior**

It is expected that all of the peaks at this workspace index should be fit.  There should be no difference in output when using the workspace indices, compared to extracting the spectrum first.

**Screenshots**

The below screenshots pertain to data from run number 58882 on SNAP at ORNL.  The data is grouped using the "Column" grouping scheme for SNAPLite, diffraction focused, and finally put into `PDCalibration`.  The below are for group 2.

### fitted peaks using an extracted spectra
image

All peaks in the group are fit.

### fitted peaks using workspace indices
image

Only the low d-space peaks are fit.

**Platform/Version (please complete the following information):**
 - OS: Red Hat Enterprise Linux Workstation 7.9 (on ORNL analysis cluster)
 - OS Version: Red Hat Enterprise Linux Workstation 7.9
 - Mantid Version 6.8

**Additional context**

This showing up as part of the diffraction calibration process used in SNAPRed, for reducing data collected on SNAP at ORNL.

The issue is not with `FitPeaks`.  Below is the result of running `FitPeaks` with the same input data (but in d-spacing):

Screenshot from 2023-09-18 14-06-42

See [EWM 2437](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20%28Change%20Management%29#action=com.ibm.team.workitem.viewWorkItem&id=2437)

### PR DESCRIPTION
**Pull request by rboston628**
### Description of work

`PDCalibration` is largely a wrapper of `FitPeaks`.  Work was done in PR #35837  to expose the `StartWorkspaceIndex` and `StopWorkspaceIndex` properties of `FitPeaks` to `PDCalibration`.

`FitPeaks` also requires initial guesses and ranges for the peaks, which can be passed in one of two ways, as lists or as workspaces.  This was not written to work intuitively with the start/stop workspace index option, requiring some novel methods of matching indices.  The way that workspace indices were handled, and peak center/window workspaces were handled, led to some contradicting behavior.

According to the documentation, the peak center property should behave as follows:

> One of only one of the following will be taken: 
> 1. A MatrixWorkspace
>       -  Number of spectra shall be the same as the number of spectra of the workspace containing peaks to fit for. Or the number of spectra is the same as the number of spectra of the input workspace.
>        - X value is the index of the peak.
>        - Y value is the position of the peaks to fit.
>        - Peak centers are stored in m_peakCenterWorkspace.
>        - Spectra can be a subset of all spectra because FitPeaks can work on partial spectra.
>  2. An array of double as the positions of the peaks to fit.
>        - Peak centers are stored in m_peakCenters
> Peaks’ positions must be given in ascending order.

That the number of spectra shall be the same as the number of spectra of the input workspace, suggests the workspace indices in the peak center workspace should correspond to the same spectra as the workspace index in the input workspace.

As it was, even if `FitPeaks` was set to match workspace indices 2,3,4 (for example), then the peak center/window workspaces were still expected to define their lists at workspace indices 0,1,2.  Since those spectra have different peak locations in TOF, this meant the guesses pulled were bad, and peaks not fit.  This was causing an error inside `PDCalibration`.

This fixes the issue, so that the workspace indices for the peak centers and windows correspond to the workspace indices for the spectra in the input workspace.

### Purpose of work

In the diffraction calibration process used with SNAP at ORNL, it is desired to first diffraction focus the data, the run `PDCalibration` on one focuses spectrum at a time, as this allows exploiting the fact the `DIFC` value will be constant on all detectors within a focus group.  This requires being able to run `PDCalibration` a single spectrum at a time, which required prior work in PR #35837.  However, as `PDCalibration` passes the guesses for peak centers and windows as a workspace, that was causing errors with access by workspace index.

With `FitPeaks`, it should now be possible after this work to create one workspace, once, with peak center/window references matching all spectra in the input workspace, then fit peaks on each individual spectrum without having to build a new set of peak center/window input workspaces for each spectrum.

### Summary of work

When accessing peak centers or windows from a workspace, instead of something like
``` cpp
std::size_t peakwsindex = wsindex - m_startWorkspaceIndex;
const auto &peakCenterX = m_peakCenterWorkspace->x(peakwsindex);
```
(which was causing failures) this instead uses
``` cpp
const auto &peakCenterX = m_peakCenterWorkspace->x(wsindex);
```
where `wsindex` is the workspace index within the input WS and is between `m_startWorkspaceIndex` and `m_stopWorkspaceIndex`.

The output workspace is still treated the same, so that indices range from 0 to *N*, where *N* is the number of spectra.  Even if these spectra correspond to different workspace indices in the input workspace.

### Further detail of work

In addition to the changes mentioned above:

Inside `FitPeaks.cpp`:
- Added `m_numSpectraToFit` to avoid having to recalculate this quantity many times.
- Updated some documentation to better clarify the use of workspace indices.
- Updated some error messages to be more informative or clear.
- Fixed the way workspace indices are handled to require less casting between `size_t` and `int64`.
- Wherever it came up, changed `size_t` to `std::size_t`.
- Fixed `m_numPeaksToFit` to work with ragged peak center workspaces.
- **major refactor** the function `getExpectedPeakPositions` was called from inside a for loop over workspace indices.  This function used branching logic to determine how to find the expected peak positions, but the same method is always used for every spectrum.  Instead, this function has been replaced by a member `std::function` called `m_getExpectedPeakPositions` which is set once during the input processing, to avoid this branching.  Likewise with the function `getPeakFitWindow`.  This simplifies the flow of the program somewhat.

Inside `FitPeaksTest.h`
- Added loggers to identify the test, for easier debugging
- Set `FitPeaks` to rethrow errors, ensure nothing thrown at execution
- The test data workspaces use points rather than edges, so that the number of centers can be better compared to the number of window edges
- Added test to see what happens with a partial spectrum fit, when not including the zero spectrum in list to fit.  This test would have failed before the change, as it would have compared the data at spectrum 2 to the peak windows defined for spectrum 0.

### To test:

Check that the new unit tests run.

Check that docs build:
``` bash
cmake -DDCS_SCREENSHOTS=on .
ninja docs-html
```

Run the docs tests:
``` bash
ninja docs-doctest
```

Within the SNS analysis cluster, run the script that I will post in the comments below.  Check the fitted workspace of `PDCalibration`, overlapped with the TOF data, to ensure the peaks were fit.  They should be so sharp you need safety goggles.

Fixes #36123

Related to [EWM 2437](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20%28Change%20Management%29#action=com.ibm.team.workitem.viewWorkItem&id=2437) at ORNL

Release notes and improved documentation have been added to explain the workspace indices.

---

### Reviewer ###

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review ####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

#### Functional Tests ####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper ###

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by rboston628** [comment]
Build this branch on the SNS analysis cluster an run the below script.  The result should illustrate the fit.  Note the previous step of pixel calibration is not being run, so the input DIFC values might be slightly off, leading to slight variations in the plotted windows.

``` python
# script to implement new CC group functionality and test different diff calibration approaches
from mantid.simpleapi import *
from mantid.api import ITableWorkspace

import matplotlib.pyplot as plt
import numpy as np
import json
import time
from datetime import datetime, date
import os
import importlib
sys.path.append('/SNS/SNAP/shared/Malcolm/code/SimpleCalibrationScripts/')
import SNAPTools as snp
importlib.reload(snp)

diagnose = True# switch on get diagnostics during execution

#Set up calibration here:

#Classic DAC:
run = 58882
rawdatafile = '/SNS/SNAP/IPTS-28913/shared/lite/SNAP_58882.lite.nxs.h5'
calibrantCif = '/SNS/SNAP/shared/Calibration/CalibrantSamples/Silicon_NIST_640d.cif'
stateFolder = '/SNS/SNAP/shared/Calibration/Powder/04bd2c53f6bf6754/'
isLite = True

rawInputWS = f'z_TOF_{run}_raw'
inputWSdsp = f'_DSP_{run}_input'
inputWStof = f'_TOF_{run}_input'
diffractionfocusedWSdsp = f'_DSP_{run}_diffoc'
diffractionfocusedWStof = f'_TOF_{run}_diffoc'

#_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
#  the below data was taken from previous calculations,
#  and is hard-coded here to avoid recalculating a lot
#  of things.
#  these come from the state/group parameters
TOFParams = (2742.6, -0.001, 13713.0)
DSPParams = (0.7098143427826137, -0.001, 2.107952352737433)
# these are peak centers and windows for group 2, taken from focus group and CIF
peaks = [
    0.53261122, 
    0.62718599, 
    0.64011902, 
    0.70713279, 
    0.72582674, 
    0.76057473,
    0.82830971, 
    0.85880979, 
    0.91810628, 
    0.96017853, 
    1.04530998, 
    1.10871867,
    1.24609221,
    1.3578975, 
    1.637686,
    1.92035706
]
peakBoundaries = [
    0.52840666, 0.53726268, 
    0.62223484, 0.63297243, 
    0.63506577, 0.64607414,
    0.70155052, 0.71401803,
    0.7200969,  0.73298859, 
    0.75457058, 0.76827066,
    0.82177084, 0.83711938, 
    0.85203014, 0.86815047, 
    0.91085854, 0.92852555,
    0.95259866, 0.97139451, 
    1.03705806, 1.05819383, 
    1.09996618, 1.12286993,
    1.23625526, 1.26296473, 
    1.34717794, 1.37687541, 
    1.62475773, 1.661249,
    1.90742879, 1.94392005
]
# the peak (min,center,max) for group 2 in TOF
peaksTOF = [
	(3283.83,3309.96,3338.87),
	(3866.94,3897.7,3933.66),
	(3946.67,3978.08,4015.09),
	(4359.85,4394.54,4437.33),
	(4475.11,4510.72,4555.22),
	(4689.35,4726.66,4774.49),
	(5106.97,5147.61,5202.35),
	(5295.02,5337.15,5395.2),
	(5660.61,5705.66,5770.41),
	(5920.01,5967.12,6036.82),
	(6444.89,6496.17,6576.24),
	(6835.84,6890.23,6978.18),
	(7682.82,7743.95,7848.81),
	(8372.16,8438.78,8556.72),
	(10097.2,10177.5,10324),
	(11853.9,11934.2,12080.7),
]
#_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/

# load the needed data
if mtd.doesExist(rawInputWS):
    print('Nexus data already loaded')
else:
    LoadEventNexus(
        Filename=rawdatafile,
        OutputWorkspace=rawInputWS,
        Precount='1', 
        FilterByTofMin = TOFParams[0],
        FilterByTofMax = TOFParams[2],
        LoadMonitors=False,
        BlockList='Phase*,Speed*,BL*:Chop:*,chopper*TDC',
    )

def convertUnitsAndRebin(inputWS, outputWS, target="dSpacing"):
    """
    Convert units to target (either TOF or dSpacing) and then rebin logarithmically.
    If 'converting' from and to the same units, will only rebin.
    """
    ConvertUnits(
        InputWorkspace=inputWS,
        OutputWorkspace=outputWS,
        Target=target,
    )

    if target == "dSpacing":
        rebinParams = DSPParams
    elif target == "TOF":
        rebinParams = TOFParams
    else:
        rebinParams = ()
        
    Rebin(
        InputWorkspace=outputWS,
        Params=rebinParams,
        OutputWorkspace=outputWS,
        BinningMode = "Logarithmic",
    )

 
# rebin data, conver to d-spacing for diffraction focusing
convertUnitsAndRebin(rawInputWS, inputWStof, "TOF")
convertUnitsAndRebin(inputWStof, inputWSdsp, "dSpacing")

# load the focus group
focusWSname = f'FocGroup_Column'
groupingFile = f'/SNS/SNAP/shared/Calibration/Powder/PixelGroupingDefinitions/SNAP{focusWSname}'
focusWSname = focusWSname + '_lite'
groupingFile = groupingFile + '.lite.nxs'
LoadNexusProcessed(
    Filename=groupingFile,
    OutputWorkspace=focusWSname,
)


# diffraction focus the data
DiffractionFocussing(
    InputWorkspace=inputWSdsp,
    GroupingWorkspace=focusWSname,
    OutputWorkspace=diffractionfocusedWSdsp,
)

# convert to TOF focused data
convertUnitsAndRebin(diffractionfocusedWSdsp, diffractionfocusedWStof, "TOF")   

subGroup = 2

#run PDCalibration on single spectrum
pdcalibratedWorkspace = f'DIFCpd_{subGroup}_full'
PDCalibration(
    InputWorkspace=diffractionfocusedWStof,
    TofBinning=TOFParams,
    PeakFunction='Gaussian',
    BackgroundType='Linear',
    PeakPositions=peaks,
    PeakWindow=peakBoundaries,
    CalibrationParameters='DIFC',
    HighBackground=True,
    OutputCalibrationTable=pdcalibratedWorkspace,
    DiagnosticWorkspaces=f'_PDCal_diag_{subGroup}',
    # PreviousCalibrationTable="DIFCprev",
    StartWorkspaceIndex = int(subGroup-1),
    StopWorkspaceIndex = int(subGroup-1), 
)

# plot overlay of TOF spectrum, the fit peaks, and the input centers/windows in TOF
tableName = 'peakProperties1'
fig, ax = plt.subplots(subplot_kw={'projection':'mantid'})
ax.plot(mtd['_TOF_58882_diffoc'], wkspIndex=1)
ax.plot(mtd['_PDCal_diag_2_fitted'], wkspIndex=1, color="orange")
ax.vlines([p[1] for p in peaksTOF], ymin=1e3, ymax=1e4, color='green')
ax.vlines([p[0] for p in peaksTOF], ymin=1e3, ymax=1e4, color='blue')
ax.vlines([p[2] for p in peaksTOF], ymin=1e3, ymax=1e4, color='blue')
ax.legend() # show the legend
fig.show()

```
Also double check that the output calibration table, `DIFCpf_2_full` has a constant DIFC defined for all detector IDs.

**Comment by rboston628** [comment]
Running the script, you should see something like the following:
image

**Comment by sf1919** [comment]
We plan to create the packages for release on Friday evening for final testing. Is there any chance this will get in before then?

**Comment by mguthriem** [comment]
I have run the script above on the analysis cluster and observed that `PDCalibration` correctly only operates on the single-spectrum specified by `Start/StopWorkspaceIndex`. The resultant DIFCs for the corresponding spectrum are updated by the subsequent `CombineDiffCal` while the other spectra are not affected.

I noticed that the output mask has masked all spectra that were not fitted. Having thought about that a little, I think that's probably OK. A script that calls `PDCalibration` multiple times (e.g. separately for every pixel in an instrument) will have to independently manage the resultant mask output. 

Probably what it would have to do is construct its own 'master mask' that only persists instances where `PDCalibration` masks the specific spectrum it is working on.

File: Framework/Algorithms/src/PDCalibration.cpp [hunk 1]
```diff
@@ -1167,12 +1167,8 @@ std::set<detid_t> PDCalibration::detIdsForTable() {
...
 
   // get the indices to loop over
-  std::size_t startIndex = 0;
-  if (!isDefault("StartWorkspaceIndex"))
-    startIndex = static_cast<std::size_t>(m_startWorkspaceIndex);
-  std::size_t stopIndex = m_uncalibratedWS->getNumberHistograms();
-  if (!isDefault("StopWorkspaceIndex"))
-    stopIndex = static_cast<std::size_t>(m_stopWorkspaceIndex);
+  std::size_t startIndex = static_cast<std::size_t>(m_startWorkspaceIndex);
+  std::size_t stopIndex = static_cast<std::size_t>(m_stopWorkspaceIndex);
```
Comment (peterfpeterson) [inline Framework/Algorithms/src/PDCalibration.cpp:1171]: I think you need to put back the `!isDefault` otherwise this forces the user to specify the optional `StopWorkspaceIndex` parameter. The default value for `StartWorkspaceIndex` is already zero so that one is ok to drop.

File: docs/source/algorithms/FitPeaks-v1.rst [hunk 2]
```diff
@@ -137,23 +138,18 @@ There are two input parameters that are associated with fitting window.
...
-
-* Peak positions are different among spectra.
-
-  - Peak windown information will be retrieved from **m_peakWindowWorkspace**
+The fit windows must correspond to a peak center.  For each peak center, the window list must
+have a lower and upper bound, meaning each window list must be twice as long as the corresponding center list.
 
+If the windows are specified using FitWindowBoundaryList, then the same set of windows will
+be used on all spectra to be fit in the workspace.
+In this case window information will be retried from **m_peakWindowVector**.
```
Comment (peterfpeterson) [inline docs/source/algorithms/FitPeaks-v1.rst:149]: Use the parameter names given to the user in the docs rather than the member variable names. Most people don't want to dig into the source code.

**Review by peterfpeterson — CHANGES_REQUESTED** [review]
The extra code cleaning is helpful too

File: Framework/Algorithms/src/PDCalibration.cpp (hunk 1 above)
Comment (rboston628) [reply Framework/Algorithms/src/PDCalibration.cpp:1171]: When `m_starWorkspaceIndex` is initialixed in L466, it is set to either the user input value, or to the last index in the input workspace.  So by the time it is called here, it will have a valid value.  I can add it anyway for extra safety

File: docs/source/algorithms/FitPeaks-v1.rst (hunk 2 above)
Comment (rboston628) [reply docs/source/algorithms/FitPeaks-v1.rst:149]: Good call

File: Framework/Algorithms/src/PDCalibration.cpp (hunk 1 above)
Comment (peterfpeterson) [reply Framework/Algorithms/src/PDCalibration.cpp:1171]: `m_stopWorkspaceIndex` is set correctly there too

**Review by peterfpeterson — APPROVED** [review]

**Comment by rboston628** [comment]
I did make a refactor in `FitPeaks` and some changes to the docs, so I re-ran the following tests:
 - unit tests all pass
 - docs build passes
 - the same script runs in workbench and produces the expected output
