### PR TITLE
Indirect IqtFit - Prevent plotting of one spectra

### LINKED ISSUE #24151: I(Q,T) Fit Throws Unhandled Exception When Plotting
**Original reporter:** nobody

This is labelled as high-priority as we want to make this interface stable for the upcoming "pseudo-release".

### Expected behavior

`Plot output` function should not be available after fitting just one spectrum

### Actual behavior

`Plot output` is available after fitting just one spectrum, clicking it causes an unhandled exception, which makes the GUI unstable.

### Steps to reproduce the behavior

* Follow the `I(Q,T)` section of (the tests)[http://developer.mantidproject.org/Testing/IndirectInelastic/IndirectInelasticAcceptanceTests.html] 
* Follow steps 1 -6 of the `Data analysis I(Q, T) Fit` section of the same, but additionally change `Fit spectra` to String and set this to 3
* After the fitting finishes click `Plot result`

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
**A.** This PR ensures that you cannot attempt a plot of a workspace that has only one data point to be plotted.
**B.** This PR also makes sure the `Fit Single Spectrum` button is disabled when fitting a single spectrum for instance in ConvFit.

**To test:**
**A.**
1. Go to `Interfaces` > `Indirect` > `Data Analysis`
2. Go to the I(Q, T) tab
3. Load the irs26176_graphite002_red.nxs file from the sample data
4. Load the resolution file irs26173_graphite002_res.nxs from the sample data
5. Click Run, a new workspace with the suffix _iqt should appear

6. Go to the I(Q, T) Fit tab
7. Load the _iqt workspace 
8. Set Exponential to 1
9. Set EndX to 0.14
10. Change `Fit spectra` to String and set this to 3
11. Click Run

`Plot` in the output options should be disabled as there is only one data point to be plotted.

**B.**
1. Go to the ConvFit tab
2. Load the data below
3. Select `TeixeiraWater` as Fit Type
4. Click `Fit Single Spectrum` and make sure it is disabled while fitting and then re-enabled

**Data Files**
[irs26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2634132/irs26176_graphite002_red.zip)
[irs26173_graphite002_res.zip](https://github.com/mantidproject/mantid/files/2634133/irs26173_graphite002_res.zip)

Fixes #24151

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/scientific_interfaces/Indirect/Iqt.cpp [hunk 1]
```diff
@@ -340,8 +353,8 @@ bool Iqt::validate() {
   uiv.checkDataSelectorIsValid("Sample", m_uiForm.dsInput);
   uiv.checkDataSelectorIsValid("Resolution", m_uiForm.dsResolution);
 
-  const auto eLow = m_dblManager->value(m_properties["ELow"]);
-  const auto eHigh = m_dblManager->value(m_properties["EHigh"]);
+  auto const eLow = m_dblManager->value(m_properties["ELow"]);
```
Comment (DTasev) [inline qt/scientific_interfaces/Indirect/Iqt.cpp]: `const auto` seems to be used more in the Mantid codebase, but `auto const` seems to be used everywhere in this file - I'm torn on whether it's worth changing it

**Review by dtasev — CHANGES_REQUESTED** [review]
Some code feedback, will be testing locally soon

File: qt/scientific_interfaces/Indirect/Iqt.cpp [hunk 2]
```diff
@@ -280,17 +280,23 @@ void Iqt::errorsClicked() {
 
 bool Iqt::isErrorsEnabled() { return m_uiForm.cbCalculateErrors->isChecked(); }
 
-double Iqt::getXMinValue(MatrixWorkspace_const_sptr workspace,
+/** 
+ * Gets the first x value which corresponds to a y value below 1
```
Comment (DTasev) [inline qt/scientific_interfaces/Indirect/Iqt.cpp]: Could this say why we need this as well? Why do we need the first X value? Is it used for plotting or cropping or in some other way?

**Comment by DTasev** [comment]
Just tested locally and the changes work fine - previously they would just make an empty plot or show the error dialogue, so it is much better to just have the option disabled. Also works when `Fit Spectra` is set to `Range`, but the range is `1-1` or `0-0`, etc.

File: qt/scientific_interfaces/Indirect/Iqt.cpp [hunk 3]
```diff
@@ -239,34 +246,50 @@ void Iqt::algorithmComplete(bool error) {
...
 }
 
 bool Iqt::isErrorsEnabled() { return m_uiForm.cbCalculateErrors->isChecked(); }
 
+double Iqt::getXMinValue(MatrixWorkspace_const_sptr workspace,
+                         std::size_t const &index) {
+  auto const firstSpectraYData = workspace->dataY(index);
+  auto const positionIter =
+      std::find_if(firstSpectraYData.begin(), firstSpectraYData.end(),
+                   [&](double const &value) { return value < 1.0; });
```
[the remark this answers is not in the document]
Comment (robertapplin) [reply qt/scientific_interfaces/Indirect/Iqt.cpp]: I agree, this could be clearer

File: qt/scientific_interfaces/Indirect/Iqt.cpp (hunk 1 above)
Comment (robertapplin) [reply qt/scientific_interfaces/Indirect/Iqt.cpp]: I prefer to use east `const` because you can reliable use it in any situation, whereas there are cases where west `const` can't be used, and you must use east `const` instead. For instance when you have a const member function of a class but the return type is not const - then you have no choice but to use east `const`.

File: qt/scientific_interfaces/Indirect/Iqt.cpp [hunk 4]
```diff
@@ -239,34 +246,50 @@ void Iqt::algorithmComplete(bool error) {
...
+  m_batchAlgoRunner->executeBatchAsync();
+}
 
 void Iqt::errorsClicked() {
   m_uiForm.spIterations->setEnabled(isErrorsEnabled());
 }
 
 bool Iqt::isErrorsEnabled() { return m_uiForm.cbCalculateErrors->isChecked(); }
 
+double Iqt::getXMinValue(MatrixWorkspace_const_sptr workspace,
```
[the remark this answers is not in the document]
Comment (robertapplin) [reply qt/scientific_interfaces/Indirect/Iqt.cpp]: A test suite doesn't exist. Unfortunately this file is not utilizing an MVP pattern making it hard to create good quality tests.

File: qt/scientific_interfaces/Indirect/test/IndirectFitPlotPresenterTest.h [hunk 5]
```diff
@@ -121,6 +121,8 @@ class MockIndirectFitPlotView : public IIndirectFitPlotView {
   MOCK_METHOD1(enableSpectrumSelection, void(bool enable));
   MOCK_METHOD1(enableFitRangeSelection, void(bool enable));
 
+  MOCK_METHOD1(setFitSingleSpectrumText, void(QString const &text));
```
[the remark this answers is not in the document]
Comment (robertapplin) [reply qt/scientific_interfaces/Indirect/test/IndirectFitPlotPresenterTest.h]: Again, this would be difficult predominately due to the fact that this and the surrounding dependencies are not in an MVP style

File: qt/scientific_interfaces/Indirect/Iqt.cpp (hunk 1 above)
Comment (DTasev) [reply qt/scientific_interfaces/Indirect/Iqt.cpp]: I see your point. My only concern is that most of the codebase uses west const and Indirect classes seem to be one of the few that stray from that

Comment (robertapplin) [reply qt/scientific_interfaces/Indirect/Iqt.cpp]: I understand your concern. Would you be ok with me just taking this advice forward for the future - changing these east const's in the Indirect interfaces would take a lot of time?

Comment (DTasev) [reply qt/scientific_interfaces/Indirect/Iqt.cpp]: Of course, that is fine with me

**Review by dtasev — DISMISSED** [review]

File: qt/scientific_interfaces/Indirect/Elwin.cpp [hunk 6]
```diff
@@ -19,8 +19,18 @@ using namespace MantidQt::API;
...
 namespace {
 Mantid::Kernel::Logger g_log("Elwin");
+
+MatrixWorkspace_sptr getADSMatrixWorkspace(std::string const &workspaceName) {
+  return AnalysisDataService::Instance().retrieveWS<MatrixWorkspace>(
+      workspaceName);
+}
+
+bool isWorkspacePlottable(MatrixWorkspace_sptr workspace) {
+  return workspace->blocksize() > 1 ? true : false;
```
Comment (soininen) [inline qt/scientific_interfaces/Indirect/Elwin.cpp]: It is enough to `return workspace->blocksize() > 1;`

By the way, `blocksize` can be a costly operation (please check). It may be advantageous to `return workspace->y(0).size() > 1;`.

File: qt/scientific_interfaces/Indirect/IndirectFitAnalysisTab.cpp [hunk 7]
```diff
@@ -29,6 +29,32 @@ using namespace Mantid::API;
...
+MatrixWorkspace_sptr convertToMatrixWorkspace(Workspace_sptr workspace) {
+  return boost::dynamic_pointer_cast<MatrixWorkspace>(workspace);
+}
+
+std::size_t numberOfColumns(Workspace_sptr workspace) {
+  return convertToMatrixWorkspace(workspace)->blocksize();
+}
+
+bool isWorkspacePlottable(Workspace_sptr workspace) {
+  return numberOfColumns(workspace) > 1 ? true : false;
```
Comment (soininen) [inline qt/scientific_interfaces/Indirect/IndirectFitAnalysisTab.cpp]: `return numberOfColumns(workspace) > 1` should suffice, no?

**Review by soininen — CHANGES_REQUESTED** [review]

**Review by soininen — APPROVED** [review]
