### PR TITLE
Fix load md for legacy files

### LINKED ISSUE #14203: ChangeOfBasisMatrix not being set for MDHistoWorkspace with nonorthogonal axes
Today I opened a MDHistoWorkspace with hexagonal coordinates in the VSI and the axes were not displayed correctly. The ChangeOfBasisMatrix was set to the identity matrix. Working backwards, the issue occurs at [L145-146 of vtkDataSetToNonOrthogonalDataSet.cpp](https://github.com/mantidproject/mantid/blob/master/Vates/VatesAPI/src/vtkDataSetToNonOrthogonalDataSet.cpp#L145) where m_coordType is set to `none` and an exception is thrown on the next line.

This appears to be a side effect of pull request #13917, which made significant changes to `MDHistoWorkspace::getSpecialCoordinateSystem()`. 

@AndreiSavici checked that this appears to only occur on older MDHistoWorkspaces and NOT ones generated by during the same session. 

A unit test should also be added to verify that the ChangeOfBasisMatrix is set correctly.

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
Fixes #14203
# For Testing
- Code reivew
- Make sure that the new unit tests pass
- Load a legacy file with non-ortho axes into the VSI (e.g. symm.nxs)
  - Confirm that it is displayed with non-ortho axes

### CODE REVIEW

File: Vates/VatesAPI/test/MDHWNexusLoadingPresenterTest.h [hunk 1]
```diff
@@ -12,186 +23,319 @@
...
+  // wrong format for this functionality.
+  static std::string getUnhandledFile() {
+    std::string temp =
+        Mantid::API::FileFinder::Instance().getFullPath("CNCS_7860_event.nxs");
     return temp;
   }
 
+  vtkDataSet *doExecute(std::string filename, bool performAsserts = true) {
+    // Setup view
+    MockMDLoadingView *view = new MockMDLoadingView;
```
Comment (quantumsteve) [inline Vates/VatesAPI/test/MDHWNexusLoadingPresenterTest.h]: Which object owns `view`? In particular, It isn't clear to me where this object (and similar ones later in this file) is deleted.

`MDHWNexusLoadingPresenter`'s constructor passes it to its base class ( `MDHWLoadingPresenter`)'s constructor where it is stored in the member variable `m_view`. Since it isn't deleted in the destructor of  `MDHWLoadingPresenter`, I'm assuming the presenter doesn't take ownership. Should it be deleted inside the test?

**Comment by quantumsteve** [comment]
@picatess, Thank you for addressing this issue and providing the ability to load previously generated MDWorkspaces that don't contain an MDFrame information. I tried loading the file where I noticed this issue and it worked well. 

I have a few questions about ownership of various pointers in the tests. Once those are addressed, I believe it is ready to merge.

File: Framework/MDAlgorithms/src/LoadMD.cpp [hunk 2]
```diff
@@ -602,6 +618,108 @@ CoordTransform *LoadMD::loadAffineMatrix(std::string entry_name) {
   return transform;
 }
 
+/**
+ * Set MDFrames for workspaces from legacy files
+ * @param ws:: poitner to the workspace which needs to be corrected
+ */
+void LoadMD::setMDFrameOnWorkspaceFromLegacyFile(API::IMDWorkspace_sptr ws) {
+
+  g_log.notice()
```
Comment (quantumsteve) [inline Framework/MDAlgorithms/src/LoadMD.cpp]: I think a lower logging level (information?) would be better.

**Comment by picatess** [comment]
@quantumsteve : That is a good question. I think this is something which is very obfuscated in the code. But I think it should be correct in this case. 

1. The view issue: Although the view is held by `MDHWLoadingPresenter`, it is destroyed in `MDHWNexusLoadingPresenter`: see (here)[https://github.com/mantidproject/mantid/blob/master/Vates/VatesAPI/src/MDHWInMemoryLoadingPresenter.cpp#L141]

2. The chain is `vtkMD0DFactory` -> `vtkMDHistoLineFactory` -> `vtkMDHistoQuadFactory`->`vtkMDHistoHexFactory`->`vtkMDHistoHex4DFactory` is in fact chain of smart pointers up to the `vtkMDHistoHex4DFactor`. The smart pointers are created (here)[https://github.com/mantidproject/mantid/blob/master/Vates/VatesAPI/src/vtkDataSetFactory.cpp#L26]. As for the last element (`vtkMDHistoHex4DFactory`), I don't see that the presenter takes ownership, hence I delete it in the test.

Now I think the situation is ok in the tests, at least what I touched.  One thing worth discussing (independently of this ticket) is how we handle resources in the plugins and the api, e.g. (vtkMDHWSource)[https://github.com/mantidproject/mantid/blob/master/Vates/ParaviewPlugins/ParaViewSources/MDHWSource/vtkMDHWSource.cxx#L191:L206] is the same as one of the tests, but it doesn't delete the `factory` variable. I cannot see in the (presenter)[https://github.com/mantidproject/mantid/blob/master/Vates/VatesAPI/src/MDHWNexusLoadingPresenter.cpp#L75;L92] that the `factory` is being owned (same as above). It might be worth going through the code and review all the memory which is allocated by `new` on the VSI/API side of things and check if RAII is being used.
