### PR TITLE
Engineering GUI save Nexus file with all the other output after a focus

### LINKED ISSUE #22352: Engineering GUI - Focus saves focused nexus file in the wrong place
In the ED GUI, after a focus all files except the `.nxs` file are saved in the User focus directory (on Windows `C:\EnginX_Mantid\User\<rb_number>\Focus`. The `.nxs` file is saved in the MantidInstall directory. This is confusing and annoying - `EnggDiffractionPresenter` should be changed to save the Nexus file in the same directory as everything else

### PR DESCRIPTION
**Pull request by josephframsay**
Previously, when running a focus from the ED GUI, the focused `.nxs` file wasn't saved in the output directory, it was saved in the MantidInstall directory. This PR makes the file easier to find by including it with all the other focus output.

**To test:**

Run a focus. To do this, go to the GUI (Interfaces -> Diffraction -> Engineering Diffraction).

You'll need to run a calibration first - go to the Calibration tab, and under **Make new calibration**, enter 236516 in **Vanadium #** and 241391 in **Calibration Sample #**. Click **Calibrate** (this might take a while!).

Now go to the Focus tab, and select [this file](https://github.com/mantidproject/mantid/files/1964232/ENGINX00281188.zip). Pick whichever banks you want to focus, and click **Focus**. This also might take a while. Go to your output directory (on Windows `C:\EnginX_Mantid\User\<rb_number>\Focus`, on Linux `~/EnginX_Mantid/User/<rb_number>/Focus`) and make sure that there is a new Nexus file there for each bank that you selected to focus. Make sure these look sensible by opening them up in MantidPlot.

Fixes #22352 
Once this is closed go and tick off the relevant item in #21022

**Release Notes** 
[Here](https://github.com/mantidproject/mantid/commit/1d04cc903e9db4732fc3ebec3be50a34c1d01973)

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/scientific_interfaces/EnggDiffraction/EnggDiffractionPresenter.h [hunk 1]
```diff
@@ -238,15 +237,20 @@ protected slots:
...
-  void saveOpenGenie(std::string inputWorkspace, std::string bank,
-                     std::string runNo);
+  void saveGSS(const std::string &inputWorkspace, const std::string &bank,
+               const std::string &runNo);
+  void saveFocusedXYE(const std::string &inputWorkspace,
+                      const std::string &bank, const std::string &runNo);
+  void saveNexus(const std::string &inputWorkspace, const std::string &bank,
+                 const std::string &runNumber);
+  void saveOpenGenie(const std::string &inputWorkspace, const std::string &bank,
+                     const std::string &runNo);
```
Comment (samueljackson92) [inline qt/scientific_interfaces/EnggDiffraction/EnggDiffractionPresenter.h]: If you're finding yourself having to pass the same info around a lot (i.e. theses three params `inputWorkspace`, `bank`, `runNumber`), do you think it would be nicer to use a `struct` to create a new concept? `FocusingOutputData` or something (think of a better name)?

**Review by samueljackson92 — COMMENTED** [review]
Mostly good. One comment:

File: qt/scientific_interfaces/EnggDiffraction/EnggDiffractionPresenter.h (hunk 1 above)
Comment (josephframsay) [reply qt/scientific_interfaces/EnggDiffraction/EnggDiffractionPresenter.h]: I agree it's nicer to replace `bank` and `runNumber` with `RunLabel`, which already exists all over the GUI. I've decided to leave `inputWorkspace` on its own as, to me at least, it makes more sense to keep the data and its 'filename' separate

**Review by samueljackson92 — APPROVED** [review]
