### PR TITLE
Fix crystallography convention for LoadMD

### LINKED ISSUE #17518: Crystallography convention changes sign of 4th dimension
### Expected behavior
Positive Temperature with Crystallography convention
### Actual behavior
Negative Temperature
### Steps to reproduce the behavior
Run Xiaoping's script with Crystallography convention set

### PR DESCRIPTION
**Pull request by VickieLynch**
Description of work:
Only change first 3 dimensions in LoadMD when file is loaded with the opposite convention.

Change: Assume the Q dimensions are those that have names starting with `[` such as `[H,0.5H,0]`, or `Q_` such as `Q_sample_x`. The change in sign should apply only to those

**To test:**
https://www.dropbox.com/s/12uaprzg8w8ua1o/TOPAZ_20575_VT_HKL_Cubic_Cell.nxs?dl=0
LoadMD 4D file that was saved in Crystallography Convention from Dropbox and use Crystallography convention unchecked during load.  Check in SliceViewer that temperature is positive.

Fixes #17518

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [x] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by VickieLynch** [comment]
Check that Dimensions are Q before changing sign (from Andrei)

File: Framework/MDAlgorithms/src/LoadMD.cpp [hunk 1]
```diff
@@ -236,11 +237,22 @@ void LoadMD::exec() {
                         << m_QConvention << '\n';
 
     if (pref_QConvention != m_QConvention) {
+      std::vector<double> scaling(m_numDims);
+      for (size_t d = 0; d < m_numDims; d++) {
+        std::string dimd = ws->getDimension(d)->getName();
+        std::string dim2 = dimd.substr(0, 2);
+        dimd = dimd.substr(0, 1);
+
+        if (dim2 == "Q_" || dimd == "[")
```
Comment (AndreiSavici) [inline Framework/MDAlgorithms/src/LoadMD.cpp]: I would add a comment line here why you are doing this

**Comment by AndreiSavici** [comment]
I've created a workspace in crystallographic convention using 
```
CreateMDWorkspace(Dimensions=5, Extents='-1,1,-1,1,-1,1,0,5,-1,20', Names='[x],[y,z],deltaE,Temp,Q_lab', Units='a,b,c,d,e', OutputWorkspace='md')
FakeMDEventData(InputWorkspace='md', UniformParams='100', PeakParams='10000,0.1,0.1,0.5,2,-0.2,0.1')
```
I saved the file, restarted mantid in inelastic convention. Dimensions starting with `[` or `Q_` changed sign. The peak moved as expected

**Comment by AndreiSavici** [comment]
Looks OK now. :shipit:

File: Framework/MDAlgorithms/src/LoadMD.cpp [hunk 2]
```diff
@@ -26,6 +26,7 @@
 #include "MantidKernel/ConfigService.h"
 #include <nexus/NeXusException.hpp>
 #include <boost/algorithm/string.hpp>
+#include <boost/range/algorithm/remove_if.hpp>
```
Comment (quantumsteve) [inline Framework/MDAlgorithms/src/LoadMD.cpp]: Is this `#include` necessary?

File: Framework/MDAlgorithms/src/LoadMD.cpp [hunk 3]
```diff
@@ -345,11 +360,25 @@ void LoadMD::loadHisto() {
...
+      dimd = dimd.substr(0, 1);
+
+      // Assume the Q dimensions are those that have names starting with [
+      // such as [H,0.5H,0], or Q_ such as Q_sample_x.
+      // The change in sign should apply only to those.
+      if (dim2 == "Q_" || dimd == "[")
+        scaling[d] = -1.0;
+      else
+        scaling[d] = 1.0;
+    }
```
Comment (quantumsteve) [inline Framework/MDAlgorithms/src/LoadMD.cpp]: Instead of repeating this code, can we move it into a separate function that is called twice?

File: Framework/MDAlgorithms/src/LoadMD.cpp [hunk 4]
```diff
@@ -236,11 +237,25 @@ void LoadMD::exec() {
...
+      std::vector<double> scaling(m_numDims);
+      for (size_t d = 0; d < m_numDims; d++) {
+        std::string dimd = ws->getDimension(d)->getName();
+        std::string dim2 = dimd.substr(0, 2);
+        dimd = dimd.substr(0, 1);
+
+        // Assume the Q dimensions are those that have names starting with [
+        // such as [H,0.5H,0], or Q_ such as Q_sample_x.
+        // The change in sign should apply only to those.
+        if (dim2 == "Q_" || dimd == "[")
```
Comment (quantumsteve) [inline Framework/MDAlgorithms/src/LoadMD.cpp]: Would a regex be a better option? One can make stricter checks and more easily add additional patterns in the future. The current solution may be "good enough" and something that can, if necessary, be changed later.

File: Framework/MDAlgorithms/src/LoadMD.cpp [hunk 5]
```diff
@@ -767,6 +772,27 @@ void LoadMD::checkForRequiredLegacyFixup(API::IMDWorkspace_sptr ws) {
...
 }
+
+/**
+ * Find scaling for Q dimensions
+ */
+std::vector<double> LoadMD::qDimensions(API::IMDWorkspace_sptr ws) {
+  std::vector<double> scaling(m_numDims);
+  for (size_t d = 0; d < m_numDims; d++) {
+    std::string dimd = ws->getDimension(d)->getName();
+    ;
```
Comment (quantumsteve) [inline Framework/MDAlgorithms/src/LoadMD.cpp]: I'll delete the extra semicolon after merging.
