### PR TITLE
Fix various bugs with multilayer plot serialisation

### LINKED ISSUE #16960: Fix issues with MultiLayer serialisation
This issue is a sub issue of #15602.

There are several known serialisation issues with MultiLayer windows. 

- [x] 1D plot with a single spectrum plotted appears on original monitor (yet was positioned on second).
- [x] 1D plot with resized window appears back at the expanded size, but the bottom of the plot is cut off.
- [x] 1D plot with an arrow makes the arrow disappear when reloaded.
- [x] Waterfall plot and styling retained, but the options on the top of the plot are lost.
- [x] 2D plot with log colour axis is not retained when the plot is reloaded
- [x] 2D plot with custom colour map does not restore the custom colour map.
- [x] 2D plot if colour bar is hidden it will reappear after being loaded.
- [x] 2D plot with arrow is reloaded, but is in wrong location

### PR DESCRIPTION
**Pull request by samueljackson92**
**This should only be merged after #16846**

This ticket is part of the work in #15602 .

This fixes a bunch of different bugs noted when performing unscripted testing on serialising 1D and 2D plot windows.

**To test:**

The following observed issues should now be fixed:
- 1D plot with a single spectrum plotted appears on original monitor (yet was positioned on second).
- 1D plot with resized window appears back at the expanded size, but the bottom of the plot is cut off.
- 1D plot with an arrow makes the arrow disappear when reloaded.
- Waterfall plot and styling retained, but the option buttons at the top of the plot are lost.
- 2D plot with log colour axis is not retained when the plot is reloaded
- 2D plot with custom colour map does not restore the custom colour map.
- 2D plot if colour bar/axis is hidden it will reappear after being loaded.
- 2D plot with arrow/line marker is reloaded, but is in wrong location.

Come talk to me/slack me if you are having trouble reproducing any of the above the issues.

Fixes #16960 .

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: MantidPlot/src/Graph3D.cpp [hunk 1]
```diff
@@ -2483,120 +2494,437 @@ Graph3D::~Graph3D() {
...
+  QString zColName = formula.mid(pos + 1, posX - pos - 1);
+
+  int xCol = w->colIndex(xColName);
+  int yCol = w->colIndex(yColName);
+  int zCol = w->colIndex(zColName);
+
+  loadData(w, xCol, yCol, zCol, params.xStart, params.xStop, params.yStart,
+           params.yStop, params.zStart, params.zStop);
+
+  QString label = caption;
```
Comment (AntonPiccardoSelg) [inline MantidPlot/src/Graph3D.cpp]: Here and above (and further above) there are several opportunities for `auto`.

File: MantidPlot/src/Graph3D.cpp [hunk 2]
```diff
@@ -2483,120 +2494,437 @@ Graph3D::~Graph3D() {
...
+    setName(labl);
+    setTitle("Workspace " + matrix->name());
+    app->customPlot3D(this);
+    customPlotStyle(style);
+    int resCol = matrix->numCols() / 200;
+    int resRow = matrix->numRows() / 200;
+    setResolution(qMax(resCol, resRow));
+
+    double zMin = 1e300;
+    double zMax = -1e300;
```
Comment (AntonPiccardoSelg) [inline MantidPlot/src/Graph3D.cpp]: It might be worth using [`numeric_limits`](http://en.cppreference.com/w/cpp/types/numeric_limits) instead of hard-coded values

File: MantidPlot/src/MultiLayer.cpp [hunk 3]
```diff
@@ -1725,74 +1725,113 @@ void WaterfallFillDialog::setFillMode() {
...
+    app->restoreWindowGeometry(
+        app, multiLayer, QString::fromStdString(tsv.lineAsString("geometry")));
   }
 
   if (tsv.hasSection("graph")) {
-    std::vector<std::string> graphSections = tsv.sections("graph");
-    for (auto it = graphSections.begin(); it != graphSections.end(); ++it) {
-      const std::string graphLines = *it;
+    auto graphSections = tsv.sections("graph");
+    for (auto it = graphSections.cbegin(); it != graphSections.cend(); ++it) {
```
Comment (AntonPiccardoSelg) [inline MantidPlot/src/MultiLayer.cpp]: You could use  `for (const auto& graphSection ; graphSections) {...`

File: MantidPlot/src/Spectrogram.cpp [hunk 4]
```diff
@@ -1033,28 +1033,39 @@ void Spectrogram::loadFromProject(const std::string &lines) {
...
+
+      int mode;
+      Mantid::Kernel::Strings::convert<int>(modeStr, mode);
+      QColor c1(QString::fromStdString(minColStr));
+      QColor c2(QString::fromStdString(maxColStr));
+
+      QwtLinearColorMap colorMap(c1, c2);
+      colorMap.setMode((QwtLinearColorMap::Mode)mode);
+
+      for (auto it = stopVec.begin(); it != stopVec.end(); ++it) {
```
Comment (AntonPiccardoSelg) [inline MantidPlot/src/Spectrogram.cpp]: You could use a range-based for-loop

File: MantidPlot/src/WindowFactory.h [hunk 5]
```diff
@@ -0,0 +1,192 @@
...
+  /// A typedef for the map of registered classes
+  typedef Mantid::Kernel::CaseInsensitiveMap<std::unique_ptr<AbstractFactory>>
+      FactoryMap;
+  /// The map holding the registered class names and their instantiators
+  FactoryMap _map;
+};
+
+/// Forward declaration of a specialisation of SingletonHolder for
+/// AlgorithmFactoryImpl (needed for dllexport/dllimport) and a typedef for it.
+#ifdef _WIN32
```
Comment (AntonPiccardoSelg) [inline MantidPlot/src/WindowFactory.h]: The text is not correct. As you have mentioned. It is not being exported. It is also not AlgorithmFactoryImpl.

File: MantidPlot/src/WindowFactory.h [hunk 6]
```diff
@@ -0,0 +1,192 @@
...
+// this breaks new namespace declaraion rules; need to find a better fix
+template class Mantid::Kernel::SingletonHolder<WindowFactoryImpl>;
+#endif /* _WIN32 */
+
+typedef Mantid::Kernel::SingletonHolder<WindowFactoryImpl> WindowFactory;
```
Comment (AntonPiccardoSelg) [inline MantidPlot/src/WindowFactory.h]: Why do we make the WindowFactory available as a Singleton? Just interested if there is a framework reason.

**Comment by samueljackson92** [comment]
@AntonPiccardoSelg Again, much of this code is not new, just old stuff moved around. However, I shall make some amendments based on your suggestions.

**Comment by AntonPiccardoSelg** [comment]
@samueljackson92  Elements which did not seem to be fixed:
* 1D plot with an arrow makes the arrow disappear when reloaded
* 2D plot with arrow/line marker is reloaded, but is in wrong location.
* 2D plot if colour bar/axis is hidden it will reappear after being loaded
* 2D plot with log colour axis is not retained when the plot is reloaded

I tested this on Ubuntu14.04

**Comment by AntonPiccardoSelg** [comment]
First: Sorry for the huge delay with this test. I forgot all about it. 

Ok most things seem to be solved, but there are still some things which seem to be slightly odd:
1. The bottom is still cut off:
screen_2_d_after_saving

2. In the case of 1D data, with a waterfall plot the options are still missing. You can see this on the screenshots when you look at the plot with the color on it.

Before saving:
on_d_before_saving

After saving:
screen_one_d_after_saving

**Comment by samueljackson92** [comment]
@AntonPiccardoSelg Have another go now. Both should hopefully be fixed. Please try with both docked and floating windows, just to make sure.

**Comment by AntonPiccardoSelg** [comment]
Issues are fixed. It works both for docked and floating windows. Happy to :shipit:
