### PR TITLE
Fix time slicing for VSI

### LINKED ISSUE #15295: Fix bug in vtkMDHexFactory which causes 3D slices of higher dimensional workspaces to not contain any points
vtkMDHexFactory expects zero thickness slices to contain data, due to the strange implementation of MDPlanes before #15209. Previous to that PR it would actually return a slice 2 bins thick if the two MDPlanes defining the slice coincide with a bin boundary and 1 bin thick otherwise.

Defining the higher bound plane (the one with the -ve normal) as lying on the next highest bin boundary would solve the problem. NB, efficiency is important as the slicing procedure is repeated many times, for example to create a movie when the 4th dimension is time.

### PR DESCRIPTION
**Pull request by matthew-d-jones**
Fixes #15295 

Fix is to create time slices which are centred on bin centres and are one bin thick.

**To Test:**

.deb is at `smb://olympic/babylon5/Scratch/Matthew%20Jones/15335`

You can use the following script to make a 4D workspace.

``` python
ws_mdew = CreateMDWorkspace(Dimensions='4', Extents='-2,2,-2,2,-2,2,-2,2', Names='h,k,l,t',
                                                 Units='rlu,rlu,rlu,s', SplitInto='15')
for peak_pos in np.linspace(-1.875, 1.875, 16):
    FakeMDEventData(ws_mdew, PeakParams='1000,0,0,'+str(peak_pos)+','+str(peak_pos)+',0.005')

ws_mdew = SliceMD(ws_mdew,AlignedDim0='h,-2,2,16',AlignedDim1='k,-2,2,15',AlignedDim2='l,-2,2,15',AlignedDim3='t,-2,2,15')
```

### CODE REVIEW

File: Vates/VatesAPI/src/vtkMDHexFactory.cpp [hunk 1]
```diff
@@ -268,6 +266,44 @@ vtkMDHexFactory::create(ProgressAction &progressUpdating) const {
 }
 
 /*
+ * Get the next highest bin boundary
+ */
+coord_t
+vtkMDHexFactory::getNextBinBoundary(IMDEventWorkspace_sptr imdws) const {
+  auto t_dim = imdws->getTDimension();
+  coord_t bin_width = t_dim->getBinWidth();
+  coord_t dim_min = t_dim->getMinimum();
```
Comment (picatess) [inline Vates/VatesAPI/src/vtkMDHexFactory.cpp]: why not `auto`?

File: Vates/VatesAPI/src/vtkMDHexFactory.cpp [hunk 2]
```diff
@@ -268,6 +266,44 @@ vtkMDHexFactory::create(ProgressAction &progressUpdating) const {
...
+
+/*
+ * Get the previous bin boundary, or the current one if m_time is on a boundary
+ */
+coord_t
+vtkMDHexFactory::getPreviousBinBoundary(IMDEventWorkspace_sptr imdws) const {
+  auto t_dim = imdws->getTDimension();
+  coord_t bin_width = t_dim->getBinWidth();
+  coord_t dim_min = t_dim->getMinimum();
+  return roundDown(coord_t(m_time) - dim_min, bin_width) + dim_min;
```
Comment (picatess) [inline Vates/VatesAPI/src/vtkMDHexFactory.cpp]: I think `static_cast<coord_t>(m_time)` is preferred over c-style casts. Also you can use `auto` up there.

File: Vates/VatesAPI/src/vtkMDHexFactory.cpp [hunk 3]
```diff
@@ -268,6 +266,44 @@ vtkMDHexFactory::create(ProgressAction &progressUpdating) const {
...
+}
+
+/*
+ * Round down to next multiple of factor
+ * Where "down" means towards -ve infinity
+ */
+coord_t roundDown(const coord_t num_to_round, const coord_t factor) {
+  return std::floor(num_to_round / factor) * factor;
+}
+
```
Comment (picatess) [inline Vates/VatesAPI/src/vtkMDHexFactory.cpp]: The functions are nice. I wonder if these functions can be used anywhere else. We might want to make them furhter available (maybe templated)

**Comment by picatess** [comment]
* Performed code review: Except for some minor things, all looks good
* Functional testing seems fine: I could see that with the implementation we don't have the effect of the first bin being 1 bin thick and the others 2 bins, but rather that all bins are 1bin thick.
Happy to merge
