### PR TITLE
Fix unrolling consecutive workflow algorithms in workspace history

### LINKED ISSUE #26826: Algorithm History - Unroll does not expand copy to clipboard
**Original reporter:** ISIS/Rob - Contact @DavidFair 

### Expected behavior
Running an algorithm with children, and unrolling the algorithm history should copy all child algorithms (without the parent) to the clipboard

### Actual behavior
Clicking unroll will expand it in the GUI, but script to clipboard will only copy the parent, not it's children. I'm unsure if this also affects script to file.

### Steps to reproduce the behavior
TODO - The user demonstrated this, but I'm waiting to receive some essential files to replicate this in the SANS GUI.
An alternative algorithm which uses children could be used in the interim.

### Platforms affected
All

### PR DESCRIPTION
**Pull request by PhilColebrooke**
**Description of work.**
This PR fixes an issue where ticking the box to unroll two consecutive workflow algorithms in workspace history would only actually unroll the first algorithm when the script is copied to file or clipboard. Now all algorithms unroll correctly.

**To test:**
Use either Plot or Workbench
1. Create a workspace history with multiple workflow algorithms (skip this step if you have your own way of doing this):

    - Download the ISIS sample data.
    - Interfaces -> SANS -> ISIS SANS.
    - Click Load User File and select SampleData-ISIS\loqdemo\MaskFile.txt
    - Click Load Batch File and select SampleData-ISIS\loqdemo\batch_mode_reduction.csv
    - Click Process All.
2. Right-click the workspace and select Show History.
3. In the history window, click the box in the Unroll column for both workflow algorithms.
4. Click Script to Clipboard and paste the script into the script editor.
5. Check that both algorithms are unrolled correctly.

Fixes #26826 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by gemmaguest — CHANGES_REQUESTED** [review]
This works as described :+1:

I have some suggestions on coding style. I'm also a bit unsure on why the hidden copies are needed but it's probably easier to talk about that in person so I'll try to grab you tomorrow.

**Comment by gemmaguest** [comment]
Following our discussion offline, I'm a bit concerned by the existing complexity in the `AlgHistoryTreeWidget` where it constructs the indices [here](https://github.com/mantidproject/mantid/blob/master/qt/widgets/common/src/AlgorithmHistoryWindow.cpp#L665). It seems it is trying to construct an absolute index to conform to the fact that `HistoryView` deals with a linear list of histories. `HistoryView` is actually the model here, so it feels like this logic should be moved there.

I think the whole thing could be simplified if `HistoryView` was changed to store the tree hierarchy rather than a linear list - in fact, perhaps all we need to store are the locations of the items we want to unroll. This would require a bit of thought, though. We could perhaps use the `RowLocation` class from the [JobTreeView]( https://developer.mantidproject.org/BatchWidget/API/JobTreeView.html), where we have similar issues.

@PhilColebrooke let me know when you're ready to look at this again and we can chat further.

**Comment by PhilColebrooke** [comment]
I've made the requested changes and created an issue for making the class less dodgy #27576

File: qt/widgets/common/src/AlgorithmHistoryWindow.cpp [hunk 1]
```diff
@@ -696,6 +736,28 @@ void AlgHistoryTreeWidget::uncheckAllChildren(QTreeWidgetItem *item,
...
 
+void AlgHistoryTreeWidget::removeHiddenChildren(QTreeWidgetItem *item) {
+  if (auto parent = item->parent()) {
+    int index{parent->indexOfChild(item)};
+
+    for (int i = 0; i < item->childCount(); i++) {
+      if (item->child(i)->checkState(1) == Qt::Checked) {
+        removeHiddenChildren(item->child(i));
+      }
+      delete parent->child(index + 1);
```
Comment (gemmaguest) [inline qt/widgets/common/src/AlgorithmHistoryWindow.cpp]: I find the logic difficult to follow here. It looks like it's deleting memory but not removing it from the child list? And it always deletes at the same location?

File: qt/widgets/common/src/AlgorithmHistoryWindow.cpp [hunk 2]
```diff
@@ -696,6 +736,28 @@ void AlgHistoryTreeWidget::uncheckAllChildren(QTreeWidgetItem *item,
   }
 }
 
+void AlgHistoryTreeWidget::removeHiddenChildren(QTreeWidgetItem *item) {
+  if (auto parent = item->parent()) {
+    int index{parent->indexOfChild(item)};
+
+    for (int i = 0; i < item->childCount(); i++) {
```
Comment (gemmaguest) [inline qt/widgets/common/src/AlgorithmHistoryWindow.cpp]: You still have the post-increment operator here

File: qt/widgets/common/src/AlgorithmHistoryWindow.cpp [hunk 3]
```diff
@@ -696,6 +736,28 @@ void AlgHistoryTreeWidget::uncheckAllChildren(QTreeWidgetItem *item,
...
+      if (item->child(i)->checkState(1) == Qt::Checked) {
+        removeHiddenChildren(item->child(i));
+      }
+      delete parent->child(index + 1);
+    }
+  } else {
+    int index{indexOfTopLevelItem(item)};
+
+    for (int i = 0; i < item->childCount(); ++i) {
+      if (item->child(i)->checkState(index) == Qt::Checked) {
```
Comment (gemmaguest) [inline qt/widgets/common/src/AlgorithmHistoryWindow.cpp]: Why is this `checkState(index)` when above it is `checkState(1)`?

File: qt/widgets/common/src/AlgorithmHistoryWindow.cpp [hunk 4]
```diff
@@ -642,16 +642,53 @@ void AlgHistoryTreeWidget::itemChecked(QTreeWidgetItem *item, int index) {
...
+
+  // The HistoryView class holds a flat list of all the algorithms in the
+  // history, as well as the children of any algorithms that have been unrolled.
+  // This function passes to that class the indices of the algorithms that have
+  // been checked so that they can be unrolled. In order for the index of an
+  // algorithm in this class to be the same as the index of that algorithm in
+  // HistoryView, when an algorithm is unrolled a copy of its children is made,
+  // added to the tree after the algorithm, and hidden.
+  for (auto it = itemsChecked.rbegin(); it != itemsChecked.rend(); ++it) {
+    auto item{*it};
```
Comment (gemmaguest) [inline qt/widgets/common/src/AlgorithmHistoryWindow.cpp]: Could this local variable have a different name, e.g. `currentItem`, to distinguish it from the input `item`?

**Review by gemmaguest — CHANGES_REQUESTED** [review]
Thanks for the tidying and comments. I think the `itemChecked` function is a lot clearer now. I'm still having a bit of trouble following `removeHiddenChildren`, though (see inline comments). I'm also getting an unexpected exception occasionally:
```
HistoryView::unroll() - Index out of range
```
I can't reliably reproduce it but it happens quite frequently in the SANS example if I get click-happy and do lots of on/off toggling of both the parent and child level items.

File: qt/widgets/common/src/AlgorithmHistoryWindow.cpp (hunk 1 above)
Comment (PhilColebrooke) [reply qt/widgets/common/src/AlgorithmHistoryWindow.cpp]: I'm back on this PR now. The QT docs say that using 'delete' is a safe way to remove an item from a tree widget:
image

The reason it's always at the same location is because when you remove an item, all of the subsequent items "move up" in the list if that makes sense. So each item being deleted ends up at the same index.

File: qt/widgets/common/src/AlgorithmHistoryWindow.cpp (hunk 3 above)
Comment (PhilColebrooke) [reply qt/widgets/common/src/AlgorithmHistoryWindow.cpp]: That was a mistake, it should be `checkState(1)` because it is referring to the columns in the tree widget and the second column is the one with the check boxes. I've fixed this now.

**Review by gemmaguest — CHANGES_REQUESTED** [review]
Thanks for the changes. Code looks great now and the out of range bug is gone :+1:

Just one minor change: could you remove the emoji from the commit message in #2084997? If you're not sure how to re-word an old commit let me know. Maybe I'm old fashioned but I've seen so much trouble from non-Ascii characters cropping up in unexpected places that I'd like to keep them out of our git history.

I'd also suggest removing the comment about it being "as per requested changes", which isn't that helpful in the context of the git history - either include a summary of the specific changes, or if it's minor style improvements just a comment saying that is fine.

**Comment by gemmaguest** [comment]
I think I've found another bug:
- Set instrument to `INTER` and run this script:
```
ReflectometryISISLoadAndProcess(InputRunList='13460',ThetaIn=0.5,FirstTransmissionRunList='13463',SecondTransmissionRunList='13464')
ReflectometryISISLoadAndProcess(InputRunList='13462',ThetaIn=2.3,FirstTransmissionRunList='13463',SecondTransmissionRunList='13464')
Stitch1DMany(InputWorkspaces='IvsQ_13460, IvsQ_13462',OutputWorkspace='IvsQ_13460_13462',Params='-0.047640977777016841')
```
- Show history for `IvsQ_13460_13462` and select the items for unrolling as per the image below. Copy the script to clipboard.
- The resulting script has unrolled an additional child item in the first top-level history item, and has not unrolled the second top-level item.

image

**Comment by PhilColebrooke** [comment]
So I've basically completely redone this PR, sorry for all the time spent reviewing 😅

The whole inserting hidden children into the tree widget thing is gone now, I realised I would need to make it way more complicated to account for all possible scenarios. Now I've just written a function that finds the correct index for an item by recursively counting all preceding items, including child algorithms when an algorithm has been unrolled. In my opinion it's a more elegant solution so hooray?

**Review by gemmaguest — APPROVED** [review]
The new solution is much cleaner and easier to understand :+1:

Works well in both the SANS and reflectometry examples regardless of how click-happy I am and with various combinations of top-level and child algorithms unrolled :+1:

I'm going to resist being picky about postincrement, but please do note that it's good to get into the habit of using [preincrement](http://llvm.org/docs/CodingStandards.html#prefer-preincrement) unless you have a reason not to.
