### PR TITLE
Indirect Iqt - Asymmetric energy range

### LINKED ISSUE #25551: Indirect Iqt - Allow Asymmetric energy range
### Expected behavior
The energy range in Iqt should be allowed to be asymmetric.

### Actual behavior
The energy range is currently only allowing a symmetric range about zero.

### Steps to reproduce the behavior
1.`Interfaces`->`Indirect`->`Data Analysis`->`Iqt` tab
2. Load the data below
3. Drag one of the energy sliders on the preview plot. The energy range is currently updated to be symmetric.

### Platforms affected
All

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR ensures that the Iqt tab of Indirect Data Analysis allows an asymmetric energy range. It also gives the option to change the spectrum displayed in the preview plot using a spin box.

**To test:**
1. `Interfaces`->`Indirect`->`Data Analysis`->`Iqt` tab
2. Load the data below
4. Untick `Symmetric Energy Range`
3. Attempt to change the energy range to that seen in the image below:
image
4. Click `Run`. If the run is successful, a workspace ending in `_iqt` should be produced.

**Spectrum Spin Box Test**
1. Make sure the data below is loaded.
2. Attempt to change the plotted spectrum using the `Spectrum` spin box. It should be able to go between 0 and 17.

**Data Files**
Sample:
[iris26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/3085500/iris26176_graphite002_red.zip)
Resolution:
[iris26173_graphite002_res.zip](https://github.com/mantidproject/mantid/files/3085501/iris26173_graphite002_res.zip)

Fixes #25551

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/scientific_interfaces/Indirect/Iqt.cpp [hunk 1]
```diff
@@ -457,22 +463,21 @@ void Iqt::updatePropertyValues(QtProperty *prop, double val) {
...
   if (prop == m_properties["EHigh"]) {
-    // If the user enters a negative value for EHigh assume they did not mean to
-    // add a -
     if (val < 0) {
       val = -val;
       m_dblManager->setValue(m_properties["EHigh"], val);
     }
 
-    m_dblManager->setValue(m_properties["ELow"], -val);
+    if (m_uiForm.ckSymmetricEnergy->isChecked())
```
Comment (TTitcombe) [inline qt/scientific_interfaces/Indirect/Iqt.cpp]: We could maybe add a small unit test to check that setValue is only called on ELow when SymmetricEnergy isChecked?

**Review by TTitcombe — COMMENTED** [review]
Works as described during testing, just a couple of small comments:
1. If you uncheck symmetric range, move the min/max, then re-check symmetric range, would it be useful behaviour to have the ranges snap back to being symmetric? Currently the remain asymmetric until you move one of them. I could imagine some users thinking the button ensures symmetry, rather than just allowing asymmetry to happen
2. A small point about a possible unit test

File: qt/scientific_interfaces/Indirect/Iqt.cpp (hunk 1 above)
Comment (robertapplin) [reply qt/scientific_interfaces/Indirect/Iqt.cpp]: Currently this file isn't unit tested as it does not use an MVP pattern. I think it would be best to leave the unit tests for when the code has been refactored (hopefully in the near future)

Comment (TTitcombe) [reply qt/scientific_interfaces/Indirect/Iqt.cpp]: Do we have a master list of tests which need to be added and at what point they can be added?

Comment (robertapplin) [reply qt/scientific_interfaces/Indirect/Iqt.cpp]: There is no list of required tests. All of the Indirect interfaces (excluding MSDFit, IqtFit, ConvFit and JumpFit) would ideally be re-written and tested.

**Review by TTitcombe — APPROVED** [review]
Good code changes. Works as expected during testing
