### PR TITLE
Fix uninitialized member variables - Coverity 

### LINKED ISSUE #17580: Fix Coverity uninitialized variables
Fix the several uninitialized variables which have entered the project and a potential null pointer deference in `graph.cpp`

### PR DESCRIPTION
**Pull request by DavidFair**
Description of work.
This PR should fix several uninitialized member variables, a possible null pointer deference and any existing reorder warnings.
**To test:**
All tests should pass

Fixes #17580 .

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
:shipit:

File: Framework/DataHandling/src/LoadGSS.cpp [hunk 1]
```diff
@@ -447,7 +447,8 @@ API::MatrixWorkspace_sptr LoadGSS::loadGSASFile(const std::string &filename,
                            detectorIDs, totalflightpaths, twothetas);
 
   // Clean up
-  delete prog;
+  if (prog)
+    delete prog;
```
Comment (SimonHeybrock) [inline Framework/DataHandling/src/LoadGSS.cpp]: Did this really generate a warning? Deleting a `nullptr` is perfectly fine according to the standard.

Comment (DavidFair) [inline Framework/DataHandling/src/LoadGSS.cpp]: Visual C++ threw an exception at the time so I added the check without realising the standard guaranteed this behaviour. 
I can't seem to replicate the issues I was having without the check so I think something funky was going on with my compilation. Either way I have removed it - thanks for the heads up.
