### PR TITLE
Indirect JumpFit - Scale

### LINKED ISSUE #18269: Indirect JumpFit - modifying input
### Expected behavior
The input workspace should not be changed by the interface
Because the JumpFit model fits to HWHM and input data is in FWHM there must be a scale of 0.5 somewhere in the routine
The preview plot should also display the HWHM
### Actual behavior
When data is loaded into the JumpFit interface the input is scaled by 0.5, this is never reverted

### Steps to reproduce the behavior
Create 2 copies of an input file, load one file into Interfaces>Indirect>DataAnalysis>JumpFit a few times, compare copies, the one loaded into JumpFit should have a smaller scale in the y-axis
### Platforms affected
Windows 7 probably all

### PR DESCRIPTION
**Pull request by louisemccann**
The Indirect JumpFit Interface scales FWHM to HWHM. A separate HWHM workspace is now created when data is loaded into the interface to prevent the original data being modified.

**To test:**

Input Files: 
[irs26176_graphite002_conv_1LFixF_s0_to_9_Result.zip](https://github.com/mantidproject/mantid/files/729154/irs26176_graphite002_conv_1LFixF_s0_to_9_Result.zip)

Load data into Mantid as a workspace.
Open Interfaces>Indirect>DataAnalysis>JumpFit
Load and re-load the workspace into the interface a few times (a quick way to do this is to switch between `File` and `Workspace` for the sample input)
Ensure the original input workspace is not modified.
Check `_HWHM` workspace is a 0.5 scale of the original input workspace.
The plot preview pane should also display the `_HWHM` workspace.

Fixes #18269.

[Release Notes](https://github.com/mantidproject/mantid/commit/1bf5f249ea6ec75116a617ecc91cac0a57ca7f7d)

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: MantidQt/CustomInterfaces/src/Indirect/JumpFit.cpp [hunk 1]
```diff
@@ -226,12 +226,12 @@ void JumpFit::handleSampleInputReady(const QString &filename) {
   IAlgorithm_sptr scaleAlg = AlgorithmManager::Instance().create("Scale");
   scaleAlg->initialize();
   scaleAlg->setProperty("InputWorkspace", filename.toStdString());
-  scaleAlg->setProperty("OutputWorkspace", filename.toStdString());
+  scaleAlg->setProperty("OutputWorkspace", filename.toStdString() + "_HWHM");
```
Comment (gemmaguest) [inline MantidQt/CustomInterfaces/src/Indirect/JumpFit.cpp]: It would be good for maintainability if the output name with the "_HWHM" suffix was defined in only one place. Perhaps it could be cached as a class member, or returned by a utility function?

**Review by gemmaguest — DISMISSED** [review]
There appears to be a bug where the Save Result button does not do anything. Other than that, everything seems to work as expected.

**Comment by gemmaguest** [comment]
Thanks for the updates, this looks good and works as described. Please :shipit: when checks pass.
