### PR TITLE
U correction not correctly applied to viewport

### LINKED ISSUE #18869: U correction makes half of WISH's detectors disappear
Pascal has noted that this is broken. On further investigation it appears it was also broken in 3.8.

### Expected behavior
Applying a U correction of `min = 0, max = 6.28` should cause the front & backscattering detectors to be flipped.

### Actual behavior
Applying a U correction of `min = 0, max = 6.28` causes half of WISH's detectors to disappear.

### Steps to reproduce the behavior
 - Load WISH file
 - Open instrument view
 - Display settings -> U correction
 - Enter values `min = 0, max = 6.28`
 - Apply
 - Observe bug

### Platforms affected
All

### PR DESCRIPTION
**Pull request by samueljackson92**
This correctly applies the U correction to the viewport when viewing a rotation surface in the instrument view.

**To test:**
 - Follow issue steps to reproduce bug. Apply fix and retest to confirm it is resolved.
 - Code review

Fixes #18869.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: MantidQt/MantidWidgets/src/InstrumentView/RotationSurface.cpp [hunk 1]
```diff
@@ -86,102 +86,111 @@ void RotationSurface::init() {
...
+          // Make some blank, empty thing that won't draw
+          m_unwrappedDetectors[i] = UnwrappedDetector();
+        } else {
+          // A real detector.
+          m_instrActor->getColor(id).getUB3(&color[0]);
+
+          // Position, relative to origin
+          // Mantid::Kernel::V3D pos = det->getPos() -
+          // m_pos;
+          Mantid::Kernel::V3D pos = m_instrActor->getDetPos(i) - m_pos;
```
Comment (OwenArnold) [inline MantidQt/MantidWidgets/src/InstrumentView/RotationSurface.cpp]: @samueljackson92 you should talk to @SimonHeybrock and @mantid-roman about these changes.

File: MantidQt/MantidWidgets/src/InstrumentView/RotationSurface.cpp [hunk 2]
```diff
@@ -86,102 +86,111 @@ void RotationSurface::init() {
...
+}
+
+/** Calculate UV offsets to the view rect
+ *
+ * @return a std::pair containing the u & v offsets for the view rect
+ */
+std::pair<double, double> RotationSurface::calculateViewRectOffsets() {
+  const auto dU = fabs(m_u_max - m_u_min);
+  const auto dV = fabs(m_v_max - m_v_min);
+  auto du = dU * 0.05;
```
Comment (OwenArnold) [inline MantidQt/MantidWidgets/src/InstrumentView/RotationSurface.cpp]: What are these hard-coded values?

File: MantidQt/MantidWidgets/src/InstrumentView/RotationSurface.cpp (hunk 1 above)
Comment (AntonPiccardoSelg) [inline MantidQt/MantidWidgets/src/InstrumentView/RotationSurface.cpp]: This part of the code is actually unchanged. Are the detector changes already available in this part of the code? Also, as I understand it, there is a chance that we could have a patch release (with these changes). Wouldn't that mean that for the patch we would have to pull in all changes required to make the new `detectorInfo` work in the instrument view?

**Comment by AntonPiccardoSelg** [comment]
##  Code Review:
  * Code is mainly refactored and fine.
  * I agree with Owen: the numbers should be (maybe `static const`) variables with a meaningfull name here. I understand that this PR is critical and I don't think that this should hold up a merge (especially since this has actually not been changed in this PR).

## Functional Testing:

Before the fix:
image


After the fix:

image

The fix seems to have worked. I applied the U correction and both detector banks were visible, therefore please :shipit:

**Comment by peterfpeterson** [comment]
This needs release notes.

File: MantidQt/MantidWidgets/src/InstrumentView/RotationSurface.cpp (hunk 1 above)
Comment (SimonHeybrock) [inline MantidQt/MantidWidgets/src/InstrumentView/RotationSurface.cpp]: Yes, those bits have been available for quite some time now.

Comment (samueljackson92) [inline MantidQt/MantidWidgets/src/InstrumentView/RotationSurface.cpp]: As @AntonPiccardoSelg points out the code is really unchanged. Those changes are only to whitespace. Whitespace changes are also a separate commit so could be dropped easily.

File: MantidQt/MantidWidgets/src/InstrumentView/RotationSurface.cpp (hunk 2 above)
Comment (samueljackson92) [inline MantidQt/MantidWidgets/src/InstrumentView/RotationSurface.cpp]: As above, this is how the code was already, so I'm not sure.

File: MantidQt/MantidWidgets/src/InstrumentView/RotationSurface.cpp (hunk 1 above)
Comment (SimonHeybrock) [inline MantidQt/MantidWidgets/src/InstrumentView/RotationSurface.cpp]: @mantid-roman has an open PR that modifies this section of code. Maybe you can undo the whitespace changes to avoid merge conflicts.

**Comment by NickDraper** [comment]
Final change was rst only, cancelled build to save resources
