### PR TITLE
Indirect - Diffraction Reduction - Ensuring GSS Saving works in all modes

### LINKED ISSUE #20560: Indirect - Diffraction - GSS Saving option
The GSS saving option, in the IndirectDiffractionReduction interface, when checked, results in the following error:

Algorithm property given value of incorrect type.
Stopping queue execution.
Got error from algorithm "SaveGSS"
Stopping batch algorithm because of execution error

### PR DESCRIPTION
**Pull request by brandonhewer**
Currently, GSS Saving produces an "Invalid algorithm property" property when used to save the output of OSIRIS diffonly diffraction reduction (OSIRISDiffractionReduction algorithm). This PR ensures that GSS Saving works across all Indirect Diffraction Reduction modes.

**To test:**
1. Navigate to Interfaces > Indirect > Diffraction.
2. For each of the following Instrument, Mode, Run Numbers, Vanadium Runs combination, run the algorithm, check the checkbox labelled 'GSS' in the Save Options and subsequently press 'Save', ensuring the output files from the reduction are saved as \.gss files:
    1. IRIS Instrument
        - Mode: Diffspec
        - Run Numbers: 26176, 26177
        - Vanadium Runs: 26178, 26179
    2. IRIS Instrument
        - Mode: Diffonly
        - Run Numbers: 26176, 26177
    3. OSIRIS Instrument (Requires Calibration File - See Below)
        - Mode: Diffspec
        - Run Numbers: 119977-119988
        - Vanadium Runs: 119963-119974
    3. OSIRIS Instrument
        - Mode: Diffonly
        - Run Numbers: 119977-119988
        - Vanadium Runs: 119963-119974

**OSIRIS Calibration File**
[osiris_041_RES10.zip](https://github.com/mantidproject/mantid/files/1341394/osiris_041_RES10.zip)

Fixes #20560. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/scientific_interfaces/Indirect/IndirectDiffractionReduction.cpp [hunk 1]
```diff
@@ -229,73 +229,49 @@ void IndirectDiffractionReduction::plotResults() {
...
-
-          // Save GSS
-          std::string gssFilename = wsName + ".gss";
-          IAlgorithm_sptr saveGSS =
-              AlgorithmManager::Instance().create("SaveGSS");
-          saveGSS->initialize();
-          saveGSS->setProperty("Filename", gssFilename);
-          m_batchAlgoRunner->addAlgorithm(saveGSS, inputFromConvUnitsProps);
+        if (instName == "OSIRIS" && mode == "diffonly") {
+          m_batchAlgoRunner->addAlgorithm(saveGSSAlgorithm(wsName + ".gss"),
```
Comment (martyngigg) [inline qt/scientific_interfaces/Indirect/IndirectDiffractionReduction.cpp]: As far as I can see these two statements look identical. Is that correct?

**Review by martyngigg — CHANGES_REQUESTED** [review]

**Review by martyngigg — APPROVED** [review]
This is good to go now.
