### PR TITLE
Fix Print Crash in pqHelpWindow

### LINKED ISSUE #34966: Crash when printing from "Help interfaces"
**Describe the bug**
When printing from a help interface, mantid crashes. This is not a regression.

**To Reproduce**
1) From workbench, use the `Help` drop down menu to open `Mantid Help`. 
2) Click the `Print...` button.
3) Click `Print`
4) Observe crash

**Expected behavior**
No crash

**Platform/Version (please complete the following information):**
Confirmed Windows + Linux

### PR DESCRIPTION
**Pull request by MialLewis**
**Description of work.**

Creates `QPrinter` object on the heap so it does not go out of scope causing an access violation.

**To test:**

1) From workbench, use the `Help` drop down menu to open `Mantid Help`. 
2) Click the `Print...` button.
3) Click `Print`
4) Observe open of dialog, and successful print.

Fixes #34966
#33262 probably fixed by qt update, revealed by this PR.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by MialLewis** [comment]
@gemmaguest worth this small fix going in 6.6?

File: qt/widgets/common/src/pqHelpWindow.cxx [hunk 1]
```diff
@@ -369,15 +369,15 @@ void pqHelpWindow::showLinkedPage(const QUrl &url) { this->showPage(url, true);
 
 //-----------------------------------------------------------------------------
 void pqHelpWindow::printPage() {
-  QPrinter printer;
-  QPrintDialog dialog(&printer, this);
+  auto *printer = new QPrinter();
```
Comment (martyngigg) [inline qt/widgets/common/src/pqHelpWindow.cxx:372]: Nice catch!

Does this create a memory leak or does the dialog take ownership?

Comment (MialLewis) [reply qt/widgets/common/src/pqHelpWindow.cxx:372]: Likely to be a memory leak, unless a `QPrinter` is smart enough to destruct once printing is completed - I can't find any documentation to this regard.

I'm not sure how we can fix this otherwise - the `QPrinter` is still needed after this function returns.

Comment (martyngigg) [reply qt/widgets/common/src/pqHelpWindow.cxx:372]: 🤔 
https://doc.qt.io/qt-5/qwebenginepage.html#print says that "It is the users responsibility to ensure the printer remains valid until resultCallback has been called". I wonder if we can do:

```c++
m_browser->page()->print(printer, [printer](bool) {printer->deleteLater();});
```
? I think this will allow the callback to complete and then delete the QPrinter on the next trip around the Qt event loop.

We don't use the webkit any more now that we are on Qt 5.15 so that code is obselete now and thankfully we don't need to worry about it.

Comment (MialLewis) [reply qt/widgets/common/src/pqHelpWindow.cxx:372]: Sounds promising - I will implement and test

**Comment by MialLewis** [comment]
I've removed obsolete reference to `USE_QTWEBKIT` and older `qt` versions.

`QPrinter` does not have a `deleteLater` function, but simply calling the destructor seems to work (observing the allocated memory).

**Review by martyngigg — APPROVED** [review]
This looks good. Confirmed that the printer button no longer crashes!

**Comment by gemmaguest** [comment]
> @gemmaguest worth this small fix going in 6.6?

I think now that it involves quite a bit of code removal as well I'd prefer to leave this for 6.7
