### PR TITLE
Fix parsing serialization string in StepScan interface with LiveData

### LINKED ISSUE #18184: StepScan analysis not working with live data
For people at SNS, set your facility to SNS, instrument to `SEQUOIA`, start `Step Scan Analysis`  interface and click start. You will get an error message like: 
screenshot from 2016-12-02 16-22-21

The step scan analysis interface still works with live streams in Mantid 3.5.2, but not is any version after that

### PR DESCRIPTION
**Pull request by AndreiSavici**
StepScan interface used to parse a string to get the parameters to pass to `StartLiveData`. Unfortunately, the format of the string changed in PR #14156 to a json. Live data was not working with the step scan interface since this changed in Mantid 3.6.

**To test:**
Code review. If you are at SNS, set your instrument to SEQUOIA, start the `StepScanAnalysis` interface, click on live data, then start. Even if there is no scan running, the interface should not crash.

Fixes #18184  

**Release Notes** 
*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/scientific_interfaces/General/StepScan.cpp [hunk 1]
```diff
@@ -544,9 +546,13 @@ bool StepScan::runStepScanAlgLive(std::string stepScanProperties) {
...
-  stepScanProperties.erase(0, stepScanProperties.find_first_of('(') + 1);
-  stepScanProperties.erase(stepScanProperties.find_last_of(')'));
-  std::replace(stepScanProperties.begin(), stepScanProperties.end(), ',', ';');
+  Json::Value root;
+  Json::Reader reader;
+  bool parsingSuccessful = reader.parse(stepScanProperties.c_str(), root);
+  if (!parsingSuccessful) {
+    throw std::runtime_error("Parsing parameters failed for StepScan.");
+  }
+  std::string ssp = root.get("properties", "").toStyledString();
```
Comment (quantumsteve) [inline qt/scientific_interfaces/General/StepScan.cpp]: Is getting the default value always an error? Should we check?
Similarly, would it be clearer to use operator[](const std::string &) and check for a null value?

**Review by quantumsteve — CHANGES_REQUESTED** [review]
Changes look reasonable, and I'll trust you on the functionality.

Comments should be addressed before this is merged.

File: qt/scientific_interfaces/General/StepScan.cpp [hunk 2]
```diff
@@ -548,11 +548,16 @@ bool StepScan::runStepScanAlgLive(std::string stepScanProperties) {
...
   Json::Reader reader;
-  bool parsingSuccessful = reader.parse(stepScanProperties.c_str(), root);
+
+  bool parsingSuccessful = reader.parse(stepScanProperties, root);
   if (!parsingSuccessful) {
     throw std::runtime_error("Parsing parameters failed for StepScan.");
   }
-  std::string ssp = root.get("properties", "").toStyledString();
+  Json::Value &prop = root["properties"];
+  if (prop.type() == Json::nullValue) {
```
Comment (quantumsteve) [inline qt/scientific_interfaces/General/StepScan.cpp]: This can be reduced to `prop.isNull()`. 

Looks like it can soon be simplified even further.
https://github.com/open-source-parsers/jsoncpp/pull/695/files

**Review by quantumsteve — APPROVED** [review]

**Comment by martyngigg** [comment]
Test failure is unrelated.
