### PR TITLE
Fix crash on inelastic symmetrise interface

### LINKED ISSUE #38743: Crash in Symmetrise Interface
There is a crash in symmetrise interface when changing the reflect type from `PositiveToNegative` to `NegativeToPositive` when there is not any workspace or file selected in the input. This was properly validated in a previous version of Mantid, so I'm putting it in v6.12 release as it is a regression. 

Image

**Describe the bug**

**To Reproduce**
1. Open Data Processor -> Symmetrise interface
2. Change the Reflect type property without adding any input. 
3. Crash

**Expected behavior**

**Screenshots**

**Platform/Version (please complete the following information):**
I tested on the Mantid version used for 6.12 manual testing on Windows Conda. 

**Additional context**

### PR DESCRIPTION
**Pull request by GuiMacielPereira**
### Description of work
Issue #38743. 
Crash was happening because validating function was not generating an error string when the workspace name is empty.

#### Summary of work

I added an error string so that validating function behaves accordingly (read my commit message).

Fixes #38743 . 

### To test:
Follow the instructions on the original issue.
Additionally:
- Without adding any data, click `Run`. This should pop up the same warning (was previously causing the same crash)
- Browse to a data file to add data
- Delete worksapce in the ADS
- Change reflection type and you should see a different error about the workspace not found.

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

File: qt/widgets/common/inc/MantidQtWidgets/Common/UserInputValidator.h [hunk 1]
```diff
@@ -138,8 +138,8 @@ bool IUserInputValidator::checkWorkspaceType(QString const &workspaceName, QStri
       addErrorMessage("The " + inputType.toStdString() + " workspace is not a " + validType.toStdString() + ".",
                       silent);
       return false;
-    } else
-      return true;
+    }
+    return true;
```
Comment (rbauststfc) [inline qt/widgets/common/inc/MantidQtWidgets/Common/UserInputValidator.h:142]: Good call to remove the unnecessary `else` here. 👍

Looking at this method, I find the nested return statements make it a little harder to see at a glance what it's doing. While we're here, I'm wondering if it would benefit from refactoring into the same form as the `UserInputValidator::checkWorkspaceExists` method, so something like:

```
template <typename T>
bool IUserInputValidator::checkWorkspaceType(QString const &workspaceName, QString const &inputType, QString const &validType, bool silent) {
  if (!checkWorkspaceExists(workspaceName, silent)) {
    return false;
  }
  
  
  if (!MantidWidgets::WorkspaceUtils::getADSWorkspace<T>(workspaceName.toStdString())) {
    addErrorMessage("The " + inputType.toStdString() + " workspace is not a " + validType.toStdString() + ".", silent);
    return false;
  }

  return true;
}
```

**Review by rbauststfc — COMMENTED** [review]
The code change for the fix looks really good, and it's great that you've also taken the opportunity to improve the existing code in `UserInputValidator.h`. With that in mind, I had a further thought in case you felt it might be worthwhile doing as part of this PR, so I've added a comment below. I've held off functional testing for now until we decide if it's worth going ahead with that change or not.

**Review by rbauststfc — APPROVED** [review]
Thanks for the refactor of `checkWorkspaceType`. The code is all looking good and I've now tested the fix, which is working really well. 👍
