### PR TITLE
Fixed bin edges as vertical axis in CreateWorkspace

### LINKED ISSUE #19525: CreateWorkspace doesn't accept bin edges as VerticalAxisValues
### Expected behavior
[`CreateWorkspace`](http://docs.mantidproject.org/nightly/algorithms/CreateWorkspace-v1.html) should accept NSpec+1 numeric values as *VerticalAxisValues* property to create a bin edges vertical axis.

### Actual behavior
The algorithm throws an exception with error message 'Number of y-axis labels must match number of histograms.'

### PR DESCRIPTION
**Pull request by soininen**
This PR fixes a check in [`CreateWorkspace`](http://docs.mantidproject.org/nightly/algorithms/CreateWorkspace-v1.html) which would reject bin edges as vertical axis.

**To test:**

The following script should fail before these changes are applied:
```python
import numpy

ys = numpy.array([1.0])
xs = numpy.array([0.0])
vertAxis = "0.1, 0.2"
ws = CreateWorkspace(DataX=xs, DataY=ys, VerticalAxisUnit='MomentumTransfer', VerticalAxisValues=vertAxis)
```

Fixes #19525.

*Release notes were updated accordingly.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Algorithms/src/CreateWorkspace.cpp [hunk 1]
```diff
@@ -106,9 +106,12 @@ void CreateWorkspace::exec() {
   const std::string vUnit = getProperty("VerticalAxisUnit");
   const std::vector<std::string> vAxis = getProperty("VerticalAxisValues");
 
-  if ((vUnit != "SpectraNumber") && (static_cast<int>(vAxis.size()) != nSpec)) {
-    throw std::invalid_argument(
-        "Number of y-axis labels must match number of histograms.");
+  const int vAxisSize = static_cast<int>(vAxis.size());
+  if (vUnit != "SpectraNumber" &&
```
Comment (DTasev) [inline Framework/Algorithms/src/CreateWorkspace.cpp]: A comment here explaining what it does would be nice, from a brief look it's very hard to interpret what the many nested conditions do. Maybe a refactoring of the condition would be better

**Review by dtasev — CHANGES_REQUESTED** [review]

**Comment by DTasev** [comment]
I've tested it locally and had a play with adding different number of spectra, bins, increasing x and y, and found no issues. Apart from a minor comment it looks good

**Review by dtasev — APPROVED** [review]

**Comment by DTasev** [comment]
Tested locally with example, everything worked as described. Had a play and I think everything looks alright, I'm happy to :shipit:
