### PR TITLE
Fix sequential fitting bug to update parameters and do plot

### LINKED ISSUE #26333: Workbench Fit Parameters are not updating, and no Fit is plotted
### Expected behavior
The Fit curve and difference for the selected spectrum should be plotted, and the parameters in the FitPropertyBrowser should be updated when changing between the workspace indices.

Changing between the workspace indices should also display the Fit and difference curves for the selected spectrum.

### Actual behavior
No fit is plotted. The parameters are not updated.

### Steps to reproduce the behavior
1. Workbench
2. Load the data below
3. Right click the workspace and plot the first index
4. Click `Fit`
5. Select `Lorentzian` and `Flat Background`
6. `Fit`->`Sequential Fit`->`Ok`
No fits plotted, and parameters won't update.

**Data**
[irs26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/3391843/irs26176_graphite002_red.zip)

### Platforms affected
All

### PR DESCRIPTION
**Pull request by alicerussell1**
**Description of work.**
This PR fixes the bug in sequential fitting so that when a sequential fit is done the function parameters are updated and a plot is done.

**To test:**
Follow instructions in #26333 to do a sequential fit. 
The parameters should update to match those in the workspace.
A plot of this function should also be done.

Fixes #26333 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/widgets/common/src/SequentialFitDialog.cpp [hunk 1]
```diff
@@ -373,7 +372,61 @@ void SequentialFitDialog::functionChanged() { populateParameters(); }
...
+  m_fitBrowser->sequentialFitFinished();
+}
+
+/// Set the parameters to the fit outcome.
+/// if more than one entry in the gui the parameters used are first entry with
+/// same name as fit property browser if one entry will try and use row that
+/// corresponds to ws index in fit browser, if not found defaults to first row.
+void SequentialFitDialog::getFitResults() {
+  auto wsName = m_outputName;
+  if (Mantid::API::AnalysisDataService::Instance().doesExist(wsName)) {
```
Comment (DavidFair) [inline qt/widgets/common/src/SequentialFitDialog.cpp]: Can we change this to
```
if (!Mantid::API::ADS::Instance().doesExist(wsName)){
    // Possibly emit a warning if this should never happen?
    return;
```

As this reduces the nesting of everything else below by one layer

File: qt/widgets/common/src/SequentialFitDialog.cpp [hunk 2]
```diff
@@ -373,7 +372,61 @@ void SequentialFitDialog::functionChanged() { populateParameters(); }
...
+    Mantid::API::ITableWorkspace_sptr ws =
+        boost::dynamic_pointer_cast<Mantid::API::ITableWorkspace>(
+            Mantid::API::AnalysisDataService::Instance().retrieve(wsName));
```
Comment (DavidFair) [inline qt/widgets/common/src/SequentialFitDialog.cpp]: This dynamic cast is unchecked, could it ever fail in the future?

File: qt/widgets/common/src/SequentialFitDialog.cpp [hunk 3]
```diff
@@ -373,7 +372,61 @@ void SequentialFitDialog::functionChanged() { populateParameters(); }
...
+
+    auto columnNames = ws->getColumnNames();
+
+    int rowNo = 0;
+    if (rowCount() > 1) {
+      // contains ws names
+      auto firstColumn = ws->getColumn(0);
+      for (size_t i = 0; i < ws->rowCount(); ++i) {
+        if (firstColumn->cell<std::string>(i) == m_fitBrowser->workspaceName())
+          rowNo = static_cast<int>(i);
```
Comment (DavidFair) [inline qt/widgets/common/src/SequentialFitDialog.cpp]: Is it worth breaking after we find this, or are would there be multiple cells with the workspace name and were looking for the very last?

File: qt/widgets/common/src/SequentialFitDialog.cpp [hunk 4]
```diff
@@ -373,7 +372,61 @@ void SequentialFitDialog::functionChanged() { populateParameters(); }
...
+      }
+    } else {
+      // contains log names or axis-1
+      if (m_fitBrowser->workspaceIndex() < ws->rowCount()) {
+        rowNo = m_fitBrowser->workspaceIndex();
+      }
+    }
+
+    Mantid::API::TableRow row = ws->getRow(rowNo);
+    for (size_t col = 1; col < columnNames.size() - 1; col += 2) {
```
Comment (DavidFair) [inline qt/widgets/common/src/SequentialFitDialog.cpp]: Could we add a comment explaining why we start at 1, and increment by 2?

**Review by DavidFair — CHANGES_REQUESTED** [review]
Some minor nitpicks

File: qt/widgets/common/src/SequentialFitDialog.cpp (hunk 2 above)
Comment (alicerussell1) [reply qt/widgets/common/src/SequentialFitDialog.cpp]: It shouldn't happen as the workspace is made during the fit but I'll add a check in just in case someone changes the way the sequential fit algorithm works

File: qt/widgets/common/src/SequentialFitDialog.cpp (hunk 3 above)
Comment (alicerussell1) [reply qt/widgets/common/src/SequentialFitDialog.cpp]: Good spot, I'll add this in. There could be multiple cells with the same name but we want the first.

File: qt/widgets/common/src/SequentialFitDialog.cpp [hunk 5]
```diff
@@ -373,7 +372,64 @@ void SequentialFitDialog::functionChanged() { populateParameters(); }
...
+    return;
+  }
+  auto columnNames = ws->getColumnNames();
+
+  size_t rowNo = 0;
+  if (rowCount() > 1) {
+    // first column contains ws names
+    auto firstColumn = ws->getColumn(0);
+    for (size_t i = 0; i < ws->rowCount(); ++i) {
+      if (firstColumn->cell<std::string>(i) == m_fitBrowser->workspaceName())
```
Comment (DavidFair) [inline qt/widgets/common/src/SequentialFitDialog.cpp]: I think there is a bug here, as the if does not have braces
Currently you break on the first iteration of the for loop

**Review by DavidFair — CHANGES_REQUESTED** [review]

File: qt/widgets/common/src/SequentialFitDialog.cpp (hunk 5 above)
Comment (alicerussell1) [reply qt/widgets/common/src/SequentialFitDialog.cpp]: Ah good catch - I've added the brackets in so it should be correct now

**Review by DavidFair — APPROVED** [review]
Fitting now appears and parameters update correctly
