### PR TITLE
Tie bug that stopped parameters being untied

### LINKED ISSUE #20552: Tie bug
When 2 of the same function are added to fit property browser and then a fit is done. Then tie on the parameters to a function. Do another fit. The untie the parameter and it will crash

### PR DESCRIPTION
**Pull request by AnthonyLim23**
This fixes a bug in Mantid that stopped parameters being untied correctly. 

**To test:**
0. Add 2 of the same function to the fit property browser 
1. Do a fit is done. 
2. Then tie one of the parameters to a function. 
3. Do another fit. 
4. Then untie the parameter (it use to crash here)

Also check that fixes etc still work correctly. 

Fixes #20552. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/widgets/common/src/FitPropertyBrowser.cpp [hunk 1]
```diff
@@ -2076,11 +2076,46 @@ void FitPropertyBrowser::deleteTie() {
...
+			  {
+				  fnNames << QString::fromStdString(
+					  m_compositeFunction->parameterName(i));
+			  }
+		  }
+	  }
+	  if (fnNames.empty() || iPar < 0) {
+		  QMessageBox::information(this, "Mantid - information",
+			  "Cannot find a parameter with this tie");
+		  return;
```
Comment (edwardb96) [inline qt/widgets/common/src/FitPropertyBrowser.cpp]: Consider converting this to an `if`-`else` to make it easier to read.

File: qt/widgets/common/src/FitPropertyBrowser.cpp [hunk 2]
```diff
@@ -2076,11 +2076,46 @@ void FitPropertyBrowser::deleteTie() {
...
+			  {
+				  iPar = (int)i;
+			  }
+			  else // Otherwise add it to the list of potential 'tyees'
+			  {
+				  fnNames << QString::fromStdString(
+					  m_compositeFunction->parameterName(i));
+			  }
+		  }
+	  }
```
Comment (edwardb96) [inline qt/widgets/common/src/FitPropertyBrowser.cpp]: Could this loop be extracted into it's own function `findTyees` which returns a (QStringList, int) pair?

File: qt/widgets/common/src/PropertyHandler.cpp [hunk 3]
```diff
@@ -1079,23 +1080,49 @@ void PropertyHandler::fix(const QString &parName) {
...
+void PropertyHandler::removeTie(QtProperty *prop, std::string globalName) {
+	QString parName = m_ties.key(prop, "");
+	if (parName.isEmpty())
+		return;
+
+	QtProperty *parProp = getParameterProperty(parName);
+	if (parProp) {
+		m_browser->m_changeSlotsEnabled = false;
+		auto tom = parName.toStdString();
+		auto &cfun = *m_browser->compositeFunction();
```
Comment (edwardb96) [inline qt/widgets/common/src/PropertyHandler.cpp]: Again do we need the abbreviation on `parProp` and `cfun`? What does `tom` mean, I can't see it being used?
The same applies to `PropertyHandler::removeTie` below.

File: qt/widgets/common/src/PropertyHandler.cpp [hunk 4]
```diff
@@ -1079,23 +1080,49 @@ void PropertyHandler::fix(const QString &parName) {
...
-    m_ties.remove(parName);
-    m_browser->m_changeSlotsEnabled = true;
-    parProp->setEnabled(true);
-  }
+	QString parName = m_ties.key(prop, "");
+	if (parName.isEmpty())
+		return;
+
+	QtProperty *parProp = getParameterProperty(parName);
+	if (parProp) {
```
Comment (edwardb96) [inline qt/widgets/common/src/PropertyHandler.cpp]: `parProp != nullptr` is more explicit and probably easier to read.

File: qt/widgets/common/src/PropertyHandler.cpp [hunk 5]
```diff
@@ -1079,23 +1080,49 @@ void PropertyHandler::fix(const QString &parName) {
...
- * Remove the tie.
- * @param prop :: The tie property to remove
- */
+* Remove the tie.
+* @param prop :: The tie property to remove
+* @param globalName :: Name of the parameter in compoite function
+* (e.g. f1.omega)
+*/
+void PropertyHandler::removeTie(QtProperty *prop, std::string globalName) {
+	QString parName = m_ties.key(prop, "");
```
Comment (edwardb96) [inline qt/widgets/common/src/PropertyHandler.cpp]: The indentation level seems to jump around from 2 to 4 to 8 in these changes, along with the brace positioning. Not sure why the clang-format check hasn't caught this?

**Review by edwardb96 — CHANGES_REQUESTED** [review]
This fix works fine on my machine. 👍 
I've highlighted a number of style issues, mainly centred around abbreviated naming, which I'm not sure we need in this case.

File: qt/widgets/common/src/FitPropertyBrowser.cpp [hunk 6]
```diff
@@ -2076,11 +2076,46 @@ void FitPropertyBrowser::deleteTie() {
...
     return;
-
-  if (ci->property()->propertyName() != "Tie") {
-    h->removeTie(ci->property()->propertyName());
-  } else {
-    h->removeTie(ci->property());
+  // get name from composite function
+  if (ci->property()->propertyName() == "Tie") {
+	  auto ties = h->getTies();
+	  QString QparName = ties.key(ci->property(), "");
```
[the remark this answers is not in the document]
Comment (AnthonyLim23) [reply qt/widgets/common/src/FitPropertyBrowser.cpp]: It is capital here because it is a QString and the Q is to signify that

File: qt/widgets/common/src/FitPropertyBrowser.cpp [hunk 7]
```diff
@@ -2076,11 +2076,46 @@ void FitPropertyBrowser::deleteTie() {
...
+	  std::string parName = QparName.toStdString();
+	  QStringList fnNames;
+
+	  int iPar = -1;
```
[the remark this answers is not in the document]
Comment (AnthonyLim23) [reply qt/widgets/common/src/FitPropertyBrowser.cpp]: Not entirely sure myself, I used some code above as a template

**Comment by AnthonyLim23** [comment]
Look at some of the comments, particularly the refactoring (making functions), I think that they should become a new issue and the whole file should be refactored.

**Comment by NickDraper** [comment]
@edwardb96 Could you take another look at the responses on this PR

**Comment by edwardb96** [comment]
@NickDraper @AnthonyLim23 was going to make some of the suggested edits tomorrow and then move the larger tasks to a separate issue.

**Comment by AnthonyLim23** [comment]
@edwardb96 do you think that what is left is just refactoring?

File: qt/widgets/common/src/FitPropertyBrowser.cpp [hunk 8]
```diff
@@ -2079,40 +2079,39 @@ void FitPropertyBrowser::deleteTie() {
...
 	  auto ties = h->getTies();
-	  QString QparName = ties.key(ci->property(), "");
-	  std::string parName = QparName.toStdString();
-	  QStringList fnNames;
-
-	  int iPar = -1;
+	  QString qParName = ties.key(ci->property(), "");
+	  std::string parName = qParName.toStdString();
+	  QStringList functionNames;
+	  // ithParameter = -1 => not found
```
Comment (edwardb96) [inline qt/widgets/common/src/FitPropertyBrowser.cpp]: Consider converting this into an actual statement `constexpr auto notFound = -1`

**Review by edwardb96 — CHANGES_REQUESTED** [review]
Good work 👍. Renaming is refactoring. But yes, the changes that are left are more global affecting the file as a whole rather than just the additions made in this PR.

Just one comment that could be code.

File: qt/widgets/common/src/PropertyHandler.cpp (hunk 5 above)
Comment (edwardb96) [reply qt/widgets/common/src/PropertyHandler.cpp]: @martyngigg Do you know why the clang-format checks aren't catching this?

**Comment by AnthonyLim23** [comment]
@martyngigg  no idea why clang is passing

File: qt/widgets/common/src/PropertyHandler.cpp (hunk 5 above)
Comment (martyngigg) [reply qt/widgets/common/src/PropertyHandler.cpp]: @edwardb96 Nice catch. It looks like the clang-format job was missing looking at the `qt/widgets` directory so we've got a whole bunch of files that are not formatted correctly in there now.

File: qt/widgets/common/src/FitPropertyBrowser.cpp (hunk 8 above)
Comment (AnthonyLim23) [reply qt/widgets/common/src/FitPropertyBrowser.cpp]: notFound could be confusing. notFound=1 would suggest that the statement is true (i.e. not found) and in reality it is the first parameter.

File: qt/widgets/common/src/PropertyHandler.cpp (hunk 5 above)
Comment (edwardb96) [reply qt/widgets/common/src/PropertyHandler.cpp]: Ok, thanks

File: qt/widgets/common/src/FitPropertyBrowser.cpp (hunk 8 above)
Comment (edwardb96) [reply qt/widgets/common/src/FitPropertyBrowser.cpp]: I see that there is more to this than I thought.

One could make the case that:
- At the time when you set `ithParameter` to `notFound` you haven't yet found it, so the statement that you haven't found it is true anyway. 
- Or that at least naming it `notFound` is less confusing than `-1`.
- Or it could be called `sentinel` instead. 

But it's a minor issue which should be caught by #20654 regardless. So probably not worth holding up the PR for.

**Review by edwardb96 — APPROVED** [review]

**Review by mantid-roman — CHANGES_REQUESTED** [review]
It works if you right-click on `Tie` but still crashes if you click and Remove Tie from the parameter name.

**Comment by AnthonyLim23** [comment]
I will look into it once I have fixed the bug I am working on.

**Review by mantid-roman — APPROVED** [review]

**Comment by mantid-roman** [comment]
It works now

**Comment by martyngigg** [comment]
The Ubuntu build failure is unrelated.
