### PR TITLE
Bug fix for contour plotting issue when using a WorkspaceGroup

### LINKED ISSUE #19419: Fix contour plot when using WorkspaceGroups
Applying contour plots to WorkspaceGroups results in shifted contour lines. The issue is that value-generating function for contour plots expects point data but we pass in histogram data.

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
Fixes #19419

**Context**
When using the `Plot Contour from Group` functionality, the contour was displayed with an offset. The reason was a mismatched index for histogram data in `MantidMatrixFunction`. `MantidMatrixFunction::indexX(size_t row, double xValue)` was extended to handle point data and Matrix data correctly.

Note that there is still an offset which is "correct" and is a result of the sampling which is being used when displaying `MantidMatrix`-based workspaces. The sampling was increase by a factor of 7 which produces visually nice contour lines on a 21 inch screen.

**To test:**

You can create a Group Workspace with the script below
```python
base = CreateSampleWorkspace(Function='One Peak', NumBanks=1, BankPixelWidth=1)

wsNames = []
for t in range (10,40,10):
    wsName = "temp" + str(t)
    wsNames.append(wsName)
    CloneWorkspace(InputWorkspace=base, OutputWorkspace=wsName)
    #MultiplyRange(base,75,99,t/100.0,OutputWorkspace=wsName)
    AddSampleLog(wsName,"Temp",str(t),"Number","Kelvin")
TestGroup = GroupWorkspaces(wsNames)
TestGroup = Rebin(TestGroup, "0, 4000, 20000")
```
Confirm that when using `Plot Contour from Group` we don't get something which is significantly offset.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: MantidPlot/src/Mantid/MantidMatrixFunction.cpp [hunk 1]
```diff
@@ -162,15 +161,19 @@ MantidMatrixFunction::getHistogramX(int row) const {
...
  * 2. Point Data:
  * Y:   6      6       16        6         6
  * X: 2000    4000    8000    12000     16000
  *
- * The algorithm will determine that the index of X which is closest to 6500 is 2,
- * and the Y index with the correct data is 2 as well since there is a one-to-one
+ * The algorithm will determine that the index of X which is closest to 6500 is
+ *2,
+ * and the Y index with the correct data is 2 as well since there is a
+ *one-to-one
```
Comment (KarlPalmen) [inline MantidPlot/src/Mantid/MantidMatrixFunction.cpp]: The comments are now much less tidy.

Comment (AntonPiccardoSelg) [inline MantidPlot/src/Mantid/MantidMatrixFunction.cpp]: Yes, that is consequence of clang formatting. I could try to work around that, but since this will need to be merged with your work, we can do this in one go.

**Comment by NickDraper** [comment]
Solved the issues it was addressing, I found another issue with contour plotting, but it is nothing to do with this.

:shipit:
