### PR TITLE
Python fit function attribute error

### LINKED ISSUE #19989: Python fit function attribute error.
### Expected behavior

A fit function defined in python can override the default `setAttributeValue` method to, for example, store an attribute value in a variable. A call to `getAttributeValue` should return the new value.

### Actual behavior

If `setAttributeValue` is defined by following instructions from the online tutorial mantid crashes. Removing the call to the super class's `setAttributeValue` method stops crashing but then `getAttributeValue` doesn't return the new value.

### Steps to reproduce the behavior

Run the script. It will print out: `Attribute wasn't set properly: 0.05 != 1.1`

```
class fitefunc(IFunction1D):

    def init(self):
        self.declareAttribute("BinWidth", 0.05)

    def setAttributeValue(self, name, value):
        if name == "BinWidth":
            self._binW = value

        #super(fitefunc, self).setAttributeValue(name, value)

    # Define the fit function
    def function1D(self, xvals):
        binW = self.getAttributeValue('BinWidth')
        if binW != self._binW:
            print("Attribute wasn't set propertly: %s != %s" % (binW, self._binW))
        return np.ones(len(xvals))
    
FunctionFactory.subscribe(fitefunc)

f = FunctionFactory.createFunction('fitefunc')
f.setAttributeValue('BinWidth', 1.1)
f.function1D([1, 2, 3])
```

Uncomment the call to `super(...` to see the crash.

### Platforms affected

All

### PR DESCRIPTION
**Pull request by mantid-roman**
Store the new attribute value after calling user defined python method 'setAttributeValue`. 

**To test:**

Use the script from the issue description.

Fixes #19989.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/PythonInterface/mantid/api/src/FitFunctions/IFunctionAdapter.cpp [hunk 1]
```diff
@@ -167,6 +167,7 @@ void IFunctionAdapter::setAttribute(const std::string &attName,
     object value = object(handle<>(getAttributeValue(*this, attr)));
     callMethod<void, std::string, object>(getSelf(), "setAttributeValue",
                                           attName, value);
+    storeAttributeValue(attName, attr);
```
Comment (jmborr) [inline Framework/PythonInterface/mantid/api/src/FitFunctions/IFunctionAdapter.cpp]: Line 172 below `IFunction::setAttribute` is an alias for ``IFunction::storeAttributeValue`, so what is the rationale for the duplicate?

Comment (mantid-roman) [inline Framework/PythonInterface/mantid/api/src/FitFunctions/IFunctionAdapter.cpp]: `IFunction::setAttribute` is virtual with the default implementation that just stores the new value. Subclasses may choose to override it to, for example, change the number of parameters (see `Polynomial').

**Review by jmborr — APPROVED** [review]
EvaluateFunction, Fit, and the Fit wizard work as expected.

:shipit:
