### PR TITLE
Fixed SetSample not setting sample material number density

### LINKED ISSUE #25498: SetSample not properly setting SampleNumberDensity
### Expected behavior
if the sample number density is set in the material dictionary in SetSample, it should be used
### Actual behavior
the sample density provided in the material dictionary is ignored.
### Steps to reproduce the behavior
create a workspace and run ```SetSample("ws",Geometry={"Shape":"Cylinder",'Height': 4.0,  'Radius': 1.0, 'Center': [0.,0.,0.], 'Axis':1}, Material={"ChemicalFormula":"V","SampleNumberDensity":"0.1" })```
open the sample material view
the sample number density will not be 0.1

### PR DESCRIPTION
**Pull request by LowriJenkins**
**Description of work.**
if the sample number density was passed in as a string to `setsample`, it was accepted but ignored, this fixes it so that its properly passes through to `setSampleMaterial`

**To test:**
run the following script
```
CreateSampleWorkspace(OutputWorkspace='ws')
SetSample(InputWorkspace='ws', Geometry='{"Axis":1,"Center":[0,0,0],"Height":4,"Radius":1,"Shape":"Cylinder"}', Material='{"ChemicalFormula":"V","SampleNumberDensity":"0.1"}')
```
then check the sample material, it should have a number density of 0.1, not 0.07

Fixes #25498 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by martyngigg — CHANGES_REQUESTED** [review]

File: Framework/Kernel/src/IPropertyManager.cpp [hunk 1]
```diff
@@ -6,6 +6,7 @@
 // SPDX - License - Identifier: GPL - 3.0 +
 #include "MantidKernel/IPropertyManager.h"
 #include "MantidKernel/IPropertySettings.h"
+#include "MantidKernel/Logger.h"
```
Comment (martyngigg) [inline Framework/Kernel/src/IPropertyManager.cpp]: Could remove the include and logger definition below now that we are not using them?

File: Framework/Kernel/test/PropertyManagerTest.h [hunk 2]
```diff
@@ -440,6 +440,34 @@ class PropertyManagerTest : public CxxTest::TestSuite {
     TS_ASSERT_EQUALS(mgr.propertyCount(), 0);
   }
 
+  void testUpdatePropertyValues() {
```
Comment (martyngigg) [inline Framework/Kernel/test/PropertyManagerTest.h]: Good to see more tests :)

**Review by martyngigg — CHANGES_REQUESTED** [review]
Just a clean up of unused code and this is good to go :+1:

File: Framework/Kernel/src/IPropertyManager.cpp (hunk 1 above)
Comment (SamJenkins1) [reply Framework/Kernel/src/IPropertyManager.cpp]: Removed it now

**Review by martyngigg — DISMISSED** [review]
:+1:

File: Framework/Kernel/inc/MantidKernel/PropertyWithValue.tcc [hunk 3]
```diff
@@ -399,12 +399,13 @@ void PropertyWithValue<TYPE>::replaceValidator(IValidator_sptr newValidator) {
...
-  if (!prop) {
-    return "Could not set value: properties have different type.";
-  }
-  m_value = prop->m_value;
-  return "";
+  
+  if (auto prop = dynamic_cast<const PropertyWithValue<TYPE> *>(&right)) {
+    m_value = prop->m_value;
+    return "";
+  }else{
```
Comment (gvardany) [inline Framework/Kernel/inc/MantidKernel/PropertyWithValue.tcc]: This does not look clang-formatted; I suppose it's skipped because of the `.tcc` extension. Can you have a look?

Comment (SamJenkins1) [reply Framework/Kernel/inc/MantidKernel/PropertyWithValue.tcc]: the only difference in the file appears to be a space either side of the else, I'll add it now

Comment (gvardany) [reply Framework/Kernel/inc/MantidKernel/PropertyWithValue.tcc]: yes, that's what I spotted; but I was worried why it wasn't caught in the previous run of clang-format.

Comment (SamJenkins1) [reply Framework/Kernel/inc/MantidKernel/PropertyWithValue.tcc]: I did the clang formatting locally this time rather than applying a patch, I imagine your likely right about it be because it was a .tcc file that the patch didn't cover it

Comment (martyngigg) [reply Framework/Kernel/inc/MantidKernel/PropertyWithValue.tcc]: @gvardany Good catch. I think the job must not be searching for `.tcc` files. We should fix that.

**Review by martyngigg — APPROVED** [review]
