### PR TITLE
Indirect Reduction - Load detailed balance from Sample logs

### LINKED ISSUE #25647: Indirect Reduction - Load Detailed Balance automatically from Sample Logs
### Expected behavior
It would be helpful if the detailed balance stored in the sample logs was automatically loaded into the Energy Transfer interface automatically when a run number has been loaded.

### Actual behavior
It's value is currently defaulted to 300k.

### Steps to reproduce the behavior
1. `Interfaces`->`Indirect`->`Data Reduction`->ISISEnergy Transfer
2. Instrument `IRIS`, Analyser `graphite`, Reflection `002`
3. Run number `60000` and press enter.
4. The detailed balance should change to be `245.253K`
5. Change Run number to `26176`. A default detailed balance of `300K` should be set

### Platforms affected
All

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR ensures the Detailed Balance on ISISEnergyTransfer is automatically loaded into the interface from the Sample Logs of the first raw file. If the relevant sample log cannot be found, a default value of `300K` is used instead.

**To test:**
1. `Interfaces`->`Indirect`->`Data Reduction`->ISISEnergy Transfer
2. Instrument `IRIS`, Analyser `graphite`, Reflection `002`
3. Run number `60000` and press enter.
4. The detailed balance should change to be `245.253K`
5. Change Run number to `26176`. A default detailed balance of `300K` should be set

Fixes #25647

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/scientific_interfaces/Indirect/ISISEnergyTransfer.cpp [hunk 1]
```diff
@@ -92,6 +98,54 @@ void ungroupWorkspace(std::string const &workspaceName) {
...
+    return defaultValue;
+  }
+}
+
+double getSampleLog(std::string const &workspaceName,
+                    std::vector<std::string> const &logNames,
+                    double const &defaultValue) {
+  double value(defaultValue);
+  for (auto const &logName : logNames) {
+    value = getSampleLog(workspaceName, logName, defaultValue);
```
Comment (TTitcombe) [inline qt/scientific_interfaces/Indirect/ISISEnergyTransfer.cpp]: You're creating an instance of the ADS and retrieving the same workspace for every log name in the vector. It would be more efficient to run `getADSMatrixWorkspace` in this method, and then loop through the vector of logs

File: qt/scientific_interfaces/Indirect/ISISEnergyTransfer.cpp [hunk 2]
```diff
@@ -92,6 +98,54 @@ void ungroupWorkspace(std::string const &workspaceName) {
...
+  deleteWorkspace(workspaceName);
+  return value;
+}
+
+double loadSampleLog(std::string const &filename,
+                     std::vector<std::string> const &logNames,
+                     double const &defaultValue) {
+  auto const temporaryWorkspace("__sample_log_subject");
+  auto loader = loadAlgorithm(filename, temporaryWorkspace);
+  loader->execute();
```
Comment (TTitcombe) [inline qt/scientific_interfaces/Indirect/ISISEnergyTransfer.cpp]: Similarly, can you not get the outputworkspace property from the loader, and get sample log from this workspace, rather than create an ADS instance and retrieve the workspace

**Review by TTitcombe — CHANGES_REQUESTED** [review]
Just a couple of questions about method efficiency

File: qt/scientific_interfaces/Indirect/ISISEnergyTransfer.cpp (hunk 1 above)
Comment (robertapplin) [reply qt/scientific_interfaces/Indirect/ISISEnergyTransfer.cpp]: Good spot 👍

File: qt/scientific_interfaces/Indirect/ISISEnergyTransfer.cpp (hunk 2 above)
Comment (robertapplin) [reply qt/scientific_interfaces/Indirect/ISISEnergyTransfer.cpp]: `loader->getProperty("OutputWorkspace")` will only return the name of the output workspace in this case because the algorithm is not a child. I could make the load algorithm a child, however I believe it is better suited being in the anonymous namespace.

**Review by TTitcombe — APPROVED** [review]
