### PR TITLE
Allow detector grouping in PDCalibration and fix bug in FitPeaks

### LINKED ISSUE #28940: Testing PDCalibrate for Engin-X
CalibratePD is an existing cpp algorithm to fit peaks in TOF to extract DIFA, DIFC and ZERO for each pixel.
Such functionality is duplicated to some extent in the EnggCalibrate.py and EngCalibrateFull.py but using the CalibratePD would have several advantages
(1) Reduce duplication
(2) Run more quickly (cpp vs python)
(3) CalibratePD is more flexible - support multiple peak types and background subtraction etc.
(4) CalibratePD outputs a calibration table that is in a format compatible with unit conversion algorithms such as AlignDetectors

WISH scientists have also expressed an interest in attempting this for the low-angle bank in particular using some C60 data (25587).

### PR DESCRIPTION
**Pull request by RichardWaiteSTFC**
**Description of work.**
PDCalibration  now works for ISIS instruments where multiple detectors contribute to a single spectrum and it performs a check for monitor/unused spectra. The calibration table now has a row for each detector that contributes to a valid spectrum - which can be used as input to AlignDetectors. The diffractometer constants (difa,difc,tzero) determined for each spectrum are stored in the rows of all contributing detectors. 
PDCalibration calls FitPeaks, in the course of testing a bug in FitPeaks was discovered: it was evaluating the function in the output workspace on bin edges if the input was a histo workspace. This resulted in an out-of-range error if the fit tried to evaluate the last x values (i.e. the final bin edge). 

**To test:**
(1) Run the below script without error

```
Load(Filename=r'\\isis.cclrc.ac.uk\inst$\ndxenginx\instrument\data\cycle_12_4\ENGINX00193749.nxs', 
     OutputWorkspace='193749')

dvalues = (2.705702376, 1.91322,1.6316,1.56214,1.35285,1.24146, 
    1.21003,1.1046,0.95661,0.855618)
               
PDCalibration(InputWorkspace='193749',
               TofBinning=[10000,6,45000],
               PeakPositions=dvalues,
               PeakWindow = 0.05, # d-spacing around which to look for peak
               MinimumPeakHeight = 1,
               PeakFunction = 'Gaussian',
               CalibrationParameters =  'DIFC+TZERO',
               OutputCalibrationTable='cal',
               DiagnosticWorkspaces = 'diag')
               
# convert units         
AlignDetectors(InputWorkspace='193749', OutputWorkspace='193749_AlignDetectors_d', CalibrationWorkspace='cal')
ConvertUnits(InputWorkspace='193749', OutputWorkspace='193749_ConvertUnits_d', Target='dSpacing')
```

(2) In the sliceviewer compare the calibrated data converted to d-spacing with `AlignDetector `with that converted with `ConvertUnits` (using the uncalibrated detector positions). The claibration should have made the peak centres of different spectra agree better (see screenshot)
image

Fixes #28940

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by RichardWaiteSTFC** [comment]
@peterfpeterson do you think this will break anything (that hasn't picked up in the automated testing)?

**Comment by peterfpeterson** [comment]
I think this PR is, generically, good to go. It looks like it:
* fixes a bug in calibrating with histograms (using bin centers for density and histogram correctly now)
* fixes a bug by using spectra rather than detectors and mapping back correctly
* adds a feature for allowing calibration with summed pixels. All contributing pixels get the same calibration constants

Am I right on this last point?

**Comment by RichardWaiteSTFC** [comment]
> I think this PR is, generically, good to go. It looks like it:
> 
> * fixes a bug in calibrating with histograms (using bin centers for density and histogram correctly now)
> * fixes a bug by using spectra rather than detectors and mapping back correctly
> * adds a feature for allowing calibration with summed pixels. All contributing pixels get the same calibration constants
> 
> Am I right on this last point?

Thanks for looking at this - all points are correct

File: Framework/Algorithms/src/PDCalibration.cpp [hunk 1]
```diff
@@ -544,22 +542,29 @@ void PDCalibration::exec() {
...
       continue;
     }
 
     // object to hold the information about the peak positions, detid, and wksp
     // index
     PDCalibration::FittedPeaks peaks(m_uncalibratedWS, wkspIndex);
-    auto toTof = getDSpacingToTof(peaks.detid);
+    auto toTof = getDSpacingToTof(
+        *peaks.detid
+             .begin()); // doesn't matter which one - all have same difc etc.
```
Comment (DannyHindson) [inline Framework/Algorithms/src/PDCalibration.cpp:567]: Is it true that all the detectors associated with a peak with all have the same diffractometer constants? Seems like it's more likely they'll all be different?

**Review by DannyHindson — COMMENTED** [review]
I've had an initial look at this. The test dataset (193749) only has a single detector per spectrum. Do you have a focussed dataset I could use to run it? Tried to focus one myself now but the algorithm wasn't getting past the "check chi-square" step
I've added a couple of detail level comments as well.

File: Framework/Algorithms/src/FitPeaks.cpp [hunk 2]
```diff
@@ -1343,9 +1339,12 @@ void FitPeaks::calculateFittedPeaks(
       // copy over the values
       size_t istart = static_cast<size_t>(start_x_iter - vec_x.begin());
       size_t istop = static_cast<size_t>(stop_x_iter - vec_x.begin());
-      for (size_t yindex = istart; yindex < istop; ++yindex)
+
+      // xvals are bin edges so only loop to istop - 1
```
[the remark this answers is not in the document]
Comment (RichardWaiteSTFC) [reply Framework/Algorithms/src/FitPeaks.cpp:1343]: Yes sorry that comment is no longer valid

File: Framework/Algorithms/src/PDCalibration.cpp (hunk 1 above)
Comment (RichardWaiteSTFC) [reply Framework/Algorithms/src/PDCalibration.cpp:567]: In principle they have different difc as they are in different positions, but by virtue of the fact you are summing over them by specifying the grouping there can only be one set of constant refined (this was the solution approved by WISH people a while back). happy to discuss.

Comment (DannyHindson) [reply Framework/Algorithms/src/PDCalibration.cpp:567]: Thinking about this a bit more... 
It seems like the spectrum may correspond to an entire bank with quite a long list of detectors. So feels like you probably should be taking the average difa, difc, tzero because the differences might be non-trivial across an entire bank?
There's some code in AlignDetectors in a class called ConversionFactors which does this already that you could copy.

Comment (RichardWaiteSTFC) [reply Framework/Algorithms/src/PDCalibration.cpp:567]: Yes I see what you mean, using an average will always give you a better estimate for the TOF peak centres.  In normal circumstances I don't think it would matter as the algorithm is intended for calibrating the whole instrument rather than focussed/grouped data with very different difc, however the Engineering diffraction workflow at ISIS is one instance where it would make a bigger difference.

Comment (peterfpeterson) [reply Framework/Algorithms/src/PDCalibration.cpp:567]: I think giving the grouped pixels all the same DIFC is the only reasonable thing to do. In principle, one can write an algorithm to do something more intelligent using the "common" DIFC as a starting point (smoothing between neighbouring groups, use cross-correlation on pixels within a group, etc).

File: Framework/Algorithms/src/FitPeaks.cpp [hunk 3]
```diff
@@ -1069,11 +1069,12 @@ void FitPeaks::fitSpectrumPeaks(
...
 
-    // set the peak parameters from last good fit - override peak center
-    for (size_t i = 0; i < lastGoodPeakParameters.size(); ++i)
-      peakfunction->setParameter(i, lastGoodPeakParameters[i]);
     double expected_peak_pos = expected_peak_centers[peak_index];
     peakfunction->setCentre(expected_peak_pos);
+    // set matrix workspace so reads necessary params from .xml file after
+    // center set
+    peakfunction->setMatrixWorkspace(m_inputMatrixWS, wi, 0.0, 0.0);
+    peakfunction->clearTies(); // let S,A,B of B2B exp be refined
```
Comment (peterfpeterson) [inline Framework/Algorithms/src/FitPeaks.cpp]: I'm not sure you are preserving functionality here. Before this changeset the previous peak that was fit was used as the starting value for the next set. The purpose was that "near-ish" peaks in the same pixel tend to have the same basic shape. I haven't looked at the rest of the context to see if that still happens without the old 1072-1074

Comment (RichardWaiteSTFC) [reply Framework/Algorithms/src/FitPeaks.cpp]: This comment might be outdated, so sorry in advance if this has already been corrected. So my understanding was before my change the starting parameters to fit the next peak in the spectrum was initialised with those from the last peak fitted in that spectrum (the loop is over expected peaks in that spectrum). The centre was overwritten with the expected centre, so in principle it was just the height and width that was changed. Now we know the height of adjacent peaks at different d-spacing is not related (depends on the structure factor) and the width should be proportional to the d-spacing (TOF diffractometers have roughly constant delta d/d resolution at a given two theta) - i.e. it will be different too. Obviously for some peak shapes the width and height are estimated later so this is not a problem  - but that was not the case for the back to back exponential peaks. My change allows the last successful fit to a peak of the same nominal d-spacing in a different spectrum to be used as an initial guess. The chunking means that each thread loops over a contiguous set of workspace indices - which albeit are not forced to be at a similar position but often are - regardless the A,B and S will likely be similar as they are functions of the d-spacing (in GSAS). Obviously in the first loop when successful peak parameters haven't been found the peak starts from the default parameters - which is you have got a refinement in a parameters.xml file will be pretty good for the back to back exponentials (and the gaussian peaks have a width estimated anyway). The A,B ties for the back to back exponential are removed as of course not every instrument will have a Parameters.xml file and the starting values from the initialisation are not the best (I should really change them). Does the above sound reasonable?

**Review by DannyHindson — CHANGES_REQUESTED** [review]
I've done all the tests and gives the expected results. Just one typo and a couple of documentation things:
1) I think the FitPeaks algorithm documentation needs a small edit to remove the comment about using moments to estimate the peak width
2) In the release notes I think it's worth mentioning that you've fixed a bug in PDCalibration relating to the way the algorithm does sequential fits to obtain DIFC, DIFA, TZERO + FitPeaks now also supports histogram workspaces

**Review by DannyHindson — APPROVED** [review]
Looks good now thanks. Please can you fix the merge conflict?
I see the RHEL7 job has failed but don't think that's related to your changes so probably just needs rerunning

**Comment by martyngigg** [comment]
Quick question. This got missed out of the list of things to merge to `release-next`. Is this too big a risk for the release at this point?

**Comment by RichardWaiteSTFC** [comment]
It's quite a big change to an algorithm used in a lot of powder/calibration scripts so it might be better to wait. The only reason to merge it is because the SNS people are working on Corelli calibration which will be impacted by this change, I don't know if they plan to squeeze anything in to this release? What do you think @DannyHindson?

**Comment by DannyHindson** [comment]
> It's quite a big change to an algorithm used in a lot of powder/calibration scripts so it might be better to wait. The only reason to merge it is because the SNS people are working on Corelli calibration which will be impacted by this change, I don't know if they plan to squeeze anything in to this release? What do you think @DannyHindson?

I think it's better to wait. I think for our users in ISIS it's good enough to have in the nightly build. So as soon as release-next created would be nice to get it merged into master
