### PR TITLE
Crash when opening AlgorithmHistoryWindow with a workspace with no history

### LINKED ISSUE #25230: Workbench crash when workspace doesn't have history
While working on an algorithm, I ended up with a workspace created from `WorkspaceFactory`. Trying to right-click view the history of it crashes the workbench. I believe a better behavior is to disable that menu option.
```python
LoadEmptyInstrument(InstrumentName='PG3', OutputWorkspace='PG3')
wksp = WorkspaceFactory.create(mtd['PG3'], NVectors=mtd['PG3'].getNumberHistograms(),
                               XLength=11, YLength=10)
AnalysisDataService.addOrReplace('wksp', wksp)
```

### PR DESCRIPTION
**Pull request by Pasarus**
**Description of work.**
It Crashed. Now it does not. The workbench would Segfault when this happened, to solve this I added an exception to be thrown. This stops the constructor and works fine in Workbench and MantidPlot.

**To test:**
- Open Workbench
- Run this script
```python
LoadEmptyInstrument(InstrumentName='PG3', OutputWorkspace='PG3')
wksp = WorkspaceFactory.create(mtd['PG3'], NVectors=mtd['PG3'].getNumberHistograms(),
                               XLength=11, YLength=10)
AnalysisDataService.addOrReplace('wksp', wksp)
```
- Right click on wksp
- Click show history
- The logger should show some warnings but not crash workbench.

Fixes #25230. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/widgets/common/src/AlgorithmHistoryWindow.cpp [hunk 1]
```diff
@@ -201,6 +201,16 @@ AlgorithmHistoryWindow::AlgorithmHistoryWindow(
       m_histPropWindow(nullptr), m_execSumGrpBox(nullptr),
       m_envHistGrpBox(nullptr), m_wsName(wsptr->getName().c_str()),
       m_view(wsptr->getHistory().createView()) {
+
```
Comment (martyngigg) [inline qt/widgets/common/src/AlgorithmHistoryWindow.cpp]: Could I suggest just a simple
```c++
if (m_algHist.empty()) {
   throw std::invalid_argument(
        "No history found on the given workspace");
}
```
rather than needing to move any of the other code?

Comment (martyngigg) [reply qt/widgets/common/src/AlgorithmHistoryWindow.cpp]: If we are now able to throw in the constructor we will also need to add `throw(std::invalid_argument)` to the end of the constructor declaration in [_common.sip](https://github.com/mantidproject/mantid/blob/master/qt/python/mantidqt/_common.sip#L290). The exception is then properly understood by Python.

**Review by martyngigg — CHANGES_REQUESTED** [review]

File: qt/widgets/common/src/AlgorithmHistoryWindow.cpp (hunk 1 above)
Comment (Pasarus) [reply qt/widgets/common/src/AlgorithmHistoryWindow.cpp]: That makes perfect sense! good call!

**Review by martyngigg — CHANGES_REQUESTED** [review]
This looks good and the workbench no longer crashes. 

Could I ask for one final tweak in [workspacewidget.py](https://github.com/mantidproject/mantid/blob/master/qt/applications/workbench/workbench/plugins/workspacewidget.py#L169)? The error I get now if I only have the logger set to `notice` is just "Could not open history of 'wksp'." with no clear idea of why. The exception itself is logged at debug though. Can we raise that to `warning` so that user sees what the error is?

**Review by martyngigg — APPROVED** [review]
