### PR TITLE
Fix various memory leaks in Kernel::Matrix

### LINKED ISSUE #19893: Resolve Valgrind issues in Kernel/KernelTests
Resolve various issues picked up by valgrind including
- Of by one errors
- Leaked memory
- Bare `new` -> `unique_ptr` where possible 
- Uninitialised reads
...etc

### PR DESCRIPTION
**Pull request by DavidFair**
Description of work.
This PR resolves a memory leak which could occur when the move constructor is invoked by replacing the bare new / delete with `std::unique_ptr`. This correctly deletes the memory reserved for the array.

It also resolves various other potential memory leaks which were pointed out by @martyngigg if we exit early from the `GuassJordan` method by using a `std::vector` instead.

I've also tidied up the member variable names to following the coding convention. The biggest changes being `v` -> `m_rawData`, `nx` -> `m_numRowsX`, `ny` -> `m_numColumnsY`.

-----

On a slightly related note a fix was merged upstream for a memory leak in the `neXus` library we were having. This has been merged [upsteam](https://github.com/nexusformat/code/pull/450) but I'm not sure how long it will take for package maintainers to pick up the changes (or if they will). 

-----

**To test:**
Code review
Ensure unit tests pass - pay attention to the Python Goniometer tests. This is very sensitive to any changes in Kernel::Matrix because of the Python Interface layer and will usually highlight any problems immediately. 

Fixes #19893 

*Does not need to be in the release notes. - Internal changes only*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Kernel/src/Matrix.cpp [hunk 1]
```diff
@@ -156,63 +160,61 @@ Matrix<T>::Matrix(const std::vector<T> &data, const size_t nrow,
...
-            jR++;
-          }
+  setMem(m_numRowsX, m_numColumnsY);
+  size_t iR(0);
+  for (size_t i = 0; i <= m_numRowsX; i++) {
+    if (i != nrow) {
+      size_t jR(0);
+      for (size_t j = 0; j <= m_numColumnsY; j++) {
+        if (j != ncol) {
+
```
Comment (martyngigg) [inline Framework/Kernel/src/Matrix.cpp]: Really picky I know but as there are other changes can we remove this whitespace?

File: Framework/Kernel/src/Matrix.cpp [hunk 2]
```diff
@@ -975,36 +970,37 @@ T Matrix<T>::Invert()
...
-    if (V[0][0] != static_cast<T>(0.))
-      V[0][0] = static_cast<T>(1.) / V[0][0];
+  if (m_numRowsX == 1) {
+    T det = m_rawData[0][0];
+    if (m_rawData[0][0] != static_cast<T>(0.))
+      m_rawData[0][0] = static_cast<T>(1.) / m_rawData[0][0];
     return det;
   }
-  auto indx = new int[nx]; // Set in lubcmp
+  std::vector<int> indx;
```
Comment (martyngigg) [inline Framework/Kernel/src/Matrix.cpp]: We could do the sizing on 1 line with `std::vector<int> indx(m_numRowsX)`?

File: Framework/Kernel/src/Matrix.cpp [hunk 3]
```diff
@@ -1033,18 +1030,20 @@ T Matrix<T>::factor()
    @return the factored matrix
 */
 {
-  if (nx != ny || nx < 1)
-    throw std::runtime_error("Matrix::factor Matrix is not NxN");
+  if (m_numRowsX != m_numColumnsY || m_numRowsX < 1)
+    throw std::runtime_error("Matrix::factor Matrix is not m_numRowsXN");
```
Comment (martyngigg) [inline Framework/Kernel/src/Matrix.cpp]: Replacement error on the string. The error message no longer makes sense.

**Review by martyngigg — CHANGES_REQUESTED** [review]
Good set of improvements.

Some minor comments below.

File: Framework/Kernel/src/Matrix.cpp [hunk 4]
```diff
@@ -1,9 +1,13 @@
-#include "MantidKernel/Exception.h"
 #include "MantidKernel/Matrix.h"
+
+#include "MantidKernel/Exception.h"
+#include "MantidKernel/make_unique.h"
 #include "MantidKernel/MersenneTwister.h"
 #include "MantidKernel/TimeSeriesProperty.h"
 #include "MantidKernel/V3D.h"
 
+#include <algorithm>
```
Comment (DavidFair) [inline Framework/Kernel/src/Matrix.cpp]: I pulled in `std::swap` for the transpose method

Comment (martyngigg) [inline Framework/Kernel/src/Matrix.cpp]: Ah yes. :+1:

File: Framework/Kernel/src/Matrix.cpp (hunk 2 above)
Comment (DavidFair) [inline Framework/Kernel/src/Matrix.cpp]: Bit of a brain fart when I was writing that - I completely forgot you can set the size on construction, there is another place in this file I'll also change that too.

File: Framework/Kernel/src/Matrix.cpp [hunk 5]
```diff
@@ -110,32 +114,32 @@ Matrix<T>::Matrix(const std::vector<T> &A, const std::vector<T> &B)
...
 }
 //
 template <typename T>
 Matrix<T>::Matrix(const std::vector<T> &data)
-    : nx(0), ny(0), V(nullptr) {
+    : m_numRowsX(0), m_numColumnsY(0) {
   size_t numel = data.size();
-  size_t nxt = static_cast<size_t>(sqrt(double(numel)));
-  size_t test = nxt * nxt;
+  size_t m_numRowsXt = static_cast<size_t>(sqrt(double(numel)));
```
Comment (DavidFair) [inline Framework/Kernel/src/Matrix.cpp]: Unfortunately we don't know `m_numRows` at this point as the constructor is testing if the matrix has valid dimensions at this point.

Comment (martyngigg) [inline Framework/Kernel/src/Matrix.cpp]: But we throw if it's not valid so if it's not square there won't be any object anyway...

Wouldn't something like:

```cpp
size_t numElements= data.size();
m_numRows = static_cast<size_t>(sqrt(double(numElements)));
if (numElements != m_numRows*m_numRows ) {
  throw(std::invalid_argument("...."
}
setMem(m_numRows , m_numRows);
...
```

work?

Comment (DavidFair) [inline Framework/Kernel/src/Matrix.cpp]: I would agree however we set the number of rows and columns in `setmem` so this ends up doing redundant work in this case. 

Looking through at the constructors in all but this case we have the details to set `m_numRows` and `m_numCols` as an initialiser list. I can also tidy up a lot of the code in `setmem` too by asserting that they are both set and just handling memory allocations in the function.

Comment (martyngigg) [inline Framework/Kernel/src/Matrix.cpp]: It's a fair point about the confusion over where `m_numRows` is set. Let's not change too much more structurally. My main thing here actually was just the variable name. Let's leave it as it currently is but have

```
size_t numRowsSquare = static_cast<size_t>(sqrt(double(numElements)));
```

as the variable name.

Comment (DavidFair) [inline Framework/Kernel/src/Matrix.cpp]: Oh woops - I've changed it so that `setmem` was a private method which takes no params to tidy it up.

To avoid this PR becoming too large I'll rename the variable names as suggested and hold onto the diff for a future PR?

Comment (martyngigg) [inline Framework/Kernel/src/Matrix.cpp]: Sounds good. `setMem` could better be called `resize` as a public member so I see no harm in leaving it as so.

Comment (DavidFair) [inline Framework/Kernel/src/Matrix.cpp]: But its only called internally and purely allocates a new block of memory hence I ended up refactoring it to do what it was documented. Anyway I'll open a separate low priority issue to apply the diff in the future.

File: Framework/TestHelpers/inc/MantidTestHelpers/FakeObjects.h [hunk 6]
```diff
@@ -177,9 +177,9 @@ class WorkspaceTester : public AxeslessWorkspaceTester {
     AxeslessWorkspaceTester::init(numspec, j, k);
 
     // Put an 'empty' axis in to test the getAxis method
-    m_axes.resize(2);
-    m_axes[0] = new Mantid::API::RefAxis(j, this);
-    m_axes[1] = new Mantid::API::SpectraAxis(this);
+    m_axes.resize(0);
```
Comment (martyngigg) [inline Framework/TestHelpers/inc/MantidTestHelpers/FakeObjects.h]: What's the reason for choosing `push_back` over the original implementation? I would still keep the `.resize(2)` anyway to avoid additional allocations.

Comment (martyngigg) [inline Framework/TestHelpers/inc/MantidTestHelpers/FakeObjects.h]: @DavidFair Could you address this final comment? I think this is ready to go otherwise.

**Review by martyngigg — APPROVED** [review]
Good to go from me now.
