### PR TITLE
Fix pseudovoigt

### LINKED ISSUE #24145: Fix PseudoVoigt's equation and documentation
PseudoVoigt function's documentation is too simple and implementation might have a bug.

### Expected behavior

PseudoVoigt function's shall have a clear documentation.

- The starting value of Mixing shall be set to 0.5.
- The starting value of FWHM shan't be 0.

### Actual behavior

PseudoVoigt function's documentation does not introduce the details how this function is calculated.   Also there might be a mistake in the implemented function.

### PR DESCRIPTION
**Pull request by wdzhou**
**Description of work.**

Pseudo-Voigt function in Mantid does not have a detailed description on its math.  The current implemented Pseudo-Voigt equation does not have any literature or paper that can back it.  Especially the mixing parameter cannot not reflect the ratio between Gaussian and Lorentzian.

**To test:**
1. Proof read the documentation about the proposed formula of Pseudo-Voigt
2. Check whether all the unit tests make sense
3. You may use this to fit a Gaussian, a Lorentzian and a Pseudo-Voigt.

Fixes #24145. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by NickDraper** [comment]
@wdzhou This branch apprears to have been ready for a test since december, but no one is touching it because it still has the "in progress" label.  You should do something about that.

**Comment by NickDraper** [comment]
@wdzhou This branch appears to have been ready for a test since December, but no one is touching it because it still has the "in progress" label. You should do something about that. Is it ready to go?

@peterfpeterson This is the second time I've asked this question

File: Framework/CurveFitting/test/Functions/PseudoVoigtTest.h [hunk 1]
```diff
@@ -198,61 +356,310 @@ class PseudoVoigtTest : public CxxTest::TestSuite {
...
+      numerical_paaram_partial_derivative(pv, 2, min_x0, max_x0, x0_resolution,
+                                          x, vec_x0, vec_numeric_deriv);
+
+      std::cout << "Jocobian size = " << vec_jocob_deriv.size() << ", "
+                << "Numerical size = " << vec_numeric_deriv.size() << "\n";
+
+      // compare
+      for (size_t i = 0; i < vec_x0.size(); ++i) {
+        TS_ASSERT_DELTA(vec_jocob_deriv[i], vec_numeric_deriv[i], 1.E-1);
+        //        std::cout << vec_x0[i] << "    " << vec_numeric_deriv[i] << "
```
Comment (peterfpeterson) [inline Framework/CurveFitting/test/Functions/PseudoVoigtTest.h]: Remove commented out code

File: Framework/CurveFitting/test/Functions/PseudoVoigtTest.h [hunk 2]
```diff
@@ -198,61 +356,310 @@ class PseudoVoigtTest : public CxxTest::TestSuite {
...
+                                          fwhm_resolution, x, vec_fwhm,
+                                          vec_numeric_deriv);
+
+      std::cout << "Jocobian size = " << vec_jocob_deriv.size() << ", "
+                << "Numerical size = " << vec_numeric_deriv.size() << "\n";
+
+      // compare
+      for (size_t i = 0; i < vec_fwhm.size(); ++i) {
+        TS_ASSERT_DELTA(vec_jocob_deriv[i], vec_numeric_deriv[i], 0.005);
+        // std::cout << vec_fwhm[i] << "    " << vec_numeric_deriv[i] << "    "
```
Comment (peterfpeterson) [inline Framework/CurveFitting/test/Functions/PseudoVoigtTest.h]: Remove commented out code

File: Framework/CurveFitting/test/Functions/PseudoVoigtTest.h [hunk 3]
```diff
@@ -198,61 +356,310 @@ class PseudoVoigtTest : public CxxTest::TestSuite {
...
+        //          << vec_jocob_deriv[i] << "\n";
+      }
     }
+    return;
+  }
+
+  /** Test the intensity ratio between a Gaussian and Lorentzian
+   * @brief testIntensityRatio
```
Comment (peterfpeterson) [inline Framework/CurveFitting/test/Functions/PseudoVoigtTest.h]: remove empty `@brief`

File: Framework/CurveFitting/test/Functions/PseudoVoigtTest.h [hunk 4]
```diff
@@ -198,61 +356,310 @@ class PseudoVoigtTest : public CxxTest::TestSuite {
...
+   */
+  void Redo_testIntensityRatio() {
+    // TODO - Implement!
```
Comment (peterfpeterson) [inline Framework/CurveFitting/test/Functions/PseudoVoigtTest.h]: This be filled in or the "test" should be removed

File: Framework/CurveFitting/test/Functions/PseudoVoigtTest.h [hunk 5]
```diff
@@ -198,61 +356,310 @@ class PseudoVoigtTest : public CxxTest::TestSuite {
...
+   * @param min_value: minimum value of the parameter to evalulate the
+   * derivative
+   * @param max_value: maximum value of the parameter to evalulate the
+   * derivative
+   * @param resolution: resolution (min step)
+   * @param x:x value
+   * @param param_vec: (output) parameter value vector
+   * @param deriv_vec: (output) derivative vector
+   */
+  void numerical_paaram_partial_derivative(IPeakFunction_sptr &pv,
```
Comment (peterfpeterson) [inline Framework/CurveFitting/test/Functions/PseudoVoigtTest.h]:
```suggestion
  void numerical_param_partial_derivative(IPeakFunction_sptr &pv,
```

File: Framework/CurveFitting/test/Functions/PseudoVoigtTest.h [hunk 6]
```diff
@@ -198,61 +356,310 @@ class PseudoVoigtTest : public CxxTest::TestSuite {
...
+      pv_vec.push_back(values[0]);
+      // increment
+      param_value += resolution;
+    }
+
+    // evalulate derivative to parameter (single way dx = (f(x+h) - f(x))/h
+    deriv_vec.resize(param_vec.size() - 1);
+    for (size_t i = 0; i < param_vec.size() - 1; ++i) {
+      deriv_vec[i] = (pv_vec[i + 1] - pv_vec[i]) / resolution;
+      // std::cout << i << ": d(pV)/da = " << deriv_vec[i] << "\n";
```
Comment (peterfpeterson) [inline Framework/CurveFitting/test/Functions/PseudoVoigtTest.h]: Remove commented out code

File: scripts/test/CrystalFieldTest.py [hunk 7]
```diff
@@ -314,8 +314,11 @@ def test_api_CrystalField_spectrum_background(self):
 
         x, y = cf.getSpectrum()
         y = y / c_mbsr
-        self.assertAlmostEqual(y[80], 2.5853144348907442, 8)
-        self.assertAlmostEqual(y[90], 6.6726254910965057, 8)
+        # FIXME - Whether this change makes sense?
```
Comment (peterfpeterson) [inline scripts/test/CrystalFieldTest.py]: Is this still relevant?

File: docs/source/release/v4.1.0/framework.rst [hunk 8]
```diff
@@ -27,6 +27,7 @@ Improvements
 - :ref:`AbsorptionCorrection <algm-AbsorptionCorrection>` has a new property `ScatterFrom` which allows for calculating the correction for the other components (i.e. container and environment)
 - Prevent an error due to the locale settings which may appear when reading, for instance, the incident energy Ei value from the logs in :ref:`ConvertUnits <algm-ConvertUnits>` and many other algorithms.
 - :code:`indices` and :code:`slicepoint` options have been added to :ref:`mantid.plots <mantid.plots>` to allow selection of which plane to plot from an MDHistoWorkspace
+- :ref:`Pseudo-Voigt <func-PseudoVoigt>` has been modified for better physics meaning.
```
Comment (peterfpeterson) [inline docs/source/release/v4.1.0/framework.rst]: A clearer meaning might be that "Pseudo-Voigt has been modified to be more in line with FULLPROF and GSAS.

**Review by peterfpeterson — CHANGES_REQUESTED** [review]
Lots of little changes. I like the greatly improved documentation and the changes to variable names to help understand what is going on. I haven't (yet) verified that the implementation matches the documentation.

**Comment by peterfpeterson** [comment]
It seems like `cal_ag`, `cal_bg`, cal_gaussian`, and `cal_lorentzian` should be `inline` static functions in an anonymous namespace. There are some comments on the functions themselves.

File: Framework/CurveFitting/src/Functions/PseudoVoigt.cpp [hunk 9]
```diff
@@ -17,83 +18,362 @@ namespace Functions {
...
+ * @param w
+ */
+void PseudoVoigt::setFwhm(const double w) { setParameter("FWHM", w, true); }
+
+/** a_G = 2/gamma * sqrt(ln2/pi)
+ * @param gamma :: FWHM
+ * @return
+ */
+double PseudoVoigt::cal_ag(const double gamma) const {
+  const double ag = 2. / gamma * sqrt(M_LN2 / M_PI);
```
Comment (peterfpeterson) [inline Framework/CurveFitting/src/Functions/PseudoVoigt.cpp]: Most of this could be defined as a file level `constexpr double`

File: Framework/CurveFitting/src/Functions/PseudoVoigt.cpp [hunk 10]
```diff
@@ -17,83 +18,362 @@ namespace Functions {
...
+  return ag;
+}
+
+/** b_G = 4 ln2 / gamma^2
+ * @param gamma :: FWHM
+ * @return
+ */
+double PseudoVoigt::cal_bg(const double gamma) const {
+  const double bg = 4 * M_LN2 / (gamma * gamma);
```
Comment (peterfpeterson) [inline Framework/CurveFitting/src/Functions/PseudoVoigt.cpp]: Same here

File: Framework/CurveFitting/src/Functions/PseudoVoigt.cpp [hunk 11]
```diff
@@ -17,83 +18,362 @@ namespace Functions {
...
+/** set FWHM
+ * @param w
+ */
+void PseudoVoigt::setFwhm(const double w) { setParameter("FWHM", w, true); }
+
+/** a_G = 2/gamma * sqrt(ln2/pi)
+ * @param gamma :: FWHM
+ * @return
+ */
+double PseudoVoigt::cal_ag(const double gamma) const {
```
Comment (peterfpeterson) [inline Framework/CurveFitting/src/Functions/PseudoVoigt.cpp]: Shouldn't be variable be named "sigma" as that is the greek letter?

File: Framework/CurveFitting/src/Functions/PseudoVoigt.cpp [hunk 12]
```diff
@@ -17,83 +18,362 @@ namespace Functions {
...
+  const double ag = 2. / gamma * sqrt(M_LN2 / M_PI);
+  return ag;
+}
+
+/** b_G = 4 ln2 / gamma^2
+ * @param gamma :: FWHM
+ * @return
+ */
+double PseudoVoigt::cal_bg(const double gamma) const {
```
Comment (peterfpeterson) [inline Framework/CurveFitting/src/Functions/PseudoVoigt.cpp]: The docs call this `H`

File: Framework/CurveFitting/test/Algorithms/FitTest.h [hunk 13]
```diff
@@ -1749,6 +1749,8 @@ class FitTest : public CxxTest::TestSuite {
     TS_ASSERT_DELTA(out->getParameter("Scale"), 0.25, 0.01);
   }
 
+  // FIXME - This Failed!
```
[the remark this answers is not in the document]
Comment (wdzhou) [reply Framework/CurveFitting/test/Algorithms/FitTest.h]: test_function_PseudoVoigt seems to work now.

File: scripts/test/CrystalFieldTest.py [hunk 14]
```diff
@@ -301,7 +301,7 @@ def test_api_CrystalField_spectrum_background(self):
         cf.peaks.param[1]['Sigma'] = 0.1
         cf.peaks.param[2]['Sigma'] = 0.2
         cf.peaks.param[3]['Sigma'] = 0.3
-        cf.background = Background(peak=Function('PseudoVoigt', Height=10*c_mbsr, FWHM=1, Mixing=0.5),
+        cf.background = Background(peak=Function('PseudoVoigt', Intensity=10*c_mbsr, FWHM=1, Mixing=0.5),
```
Comment (mantid-roman) [inline scripts/test/CrystalFieldTest.py]: @mducle Could you take a look at the changes please?

File: Framework/CurveFitting/src/Functions/PseudoVoigt.cpp [hunk 15]
```diff
@@ -17,83 +18,366 @@ namespace Functions {
...
+ * @brief PseudoVoigt::setHeight
+ * @param h
+ */
+void PseudoVoigt::setHeight(const double h) {
+  // set height
+  m_height = h;
+  update_set_history(2);
+  g_log.debug() << "PV: set height = " << m_height << "\n";
+  estimate_parameter_value();
+}
```
Comment (mantid-roman) [inline Framework/CurveFitting/src/Functions/PseudoVoigt.cpp]: `setHeight` can simply scale the intensity with the height's change factor: 
```
new_intensity = old_intensity * h / height()
```
Special case should be made for `height() == 0`

File: scripts/test/CrystalFieldTest.py (hunk 7 above)
Comment (wdzhou) [reply scripts/test/CrystalFieldTest.py]: Resolved with Andrea

File: Framework/CurveFitting/src/Functions/PseudoVoigt.cpp (hunk 15 above)
Comment (wdzhou) [reply Framework/CurveFitting/src/Functions/PseudoVoigt.cpp]: Thanks! It works with MantidPlot/Fit now.

**Review by mducle — CHANGES_REQUESTED** [review]
Just a couple of changes (mostly typos) to the documentation needed. Theory looks ok to me.

Tested the limiting cases (`Mixing=0` and `Mixing=1`) which looks ok, the intermediate cases also look ok now (the integrated area before these changes depended on the `Mixing` parameter, whereas now the area is constant for any value of `Mixing` as it should be).

**Comment by mducle** [comment]
One more comment - now that the `Height` parameter has been changed to `Intensity` - this should be emphasised in the change log because user scripts which use `PseudoVoigt` will need to be changed. 

(Unless it is possible to change this function to also accept a `Height` parameter as input - or change `ParamFunction` to accept the effective height attribute defined in the C++ code [but which is not available to Python]).

File: Framework/CurveFitting/src/Functions/PseudoVoigt.cpp (hunk 11 above)
Comment (wdzhou) [reply Framework/CurveFitting/src/Functions/PseudoVoigt.cpp]: this is to set FHWM but not sigma

File: docs/source/fitting/fitfunctions/PseudoVoigt.rst [hunk 16]
```diff
@@ -13,10 +13,136 @@ The Pseudo-Voigt function is an approximation for the Voigt function, which is a
...
++++++++++++++++++++++++++
+
+- Peak height :math:`h`: 
+
+.. math:: h = I \cdot (\eta \cdot a_G + (1 - \eta) \cdot \frac{2}{\pi\cdot H}) = \frac{2 I}{\pi H} (1 + (\sqrt{\pi\ln{2}}-1)\eta)
+
+- :math:`\sigma`:
+
+.. math:: \sigma = \frac{H}{2\sqrt{2\ln(2)}}
+
```
[the remark this answers is not in the document]
Comment (mantid-roman) [reply docs/source/fitting/fitfunctions/PseudoVoigt.rst]: We can expose the peak methods to python.

File: docs/source/fitting/fitfunctions/PseudoVoigt.rst [hunk 17]
```diff
@@ -13,10 +13,136 @@ The Pseudo-Voigt function is an approximation for the Voigt function, which is a
...
+Thus pseudo-voigt can be expressed in such way
+
+.. math:: pV(x) = I \cdot (\eta \cdot G'(x, H) + (1 - \eta) \cdot L'(x, H))
+
+where :math:`G'(x, H)` and `L'(x, H)` are normalized Gaussian and Lorentzian.
+
+To be noticed that the Fullprof manual's way to define parameter names is following.
+In the code, in order to avoid confusion between :math:`H` and peak height :math:`h`, 
+*gamma* will be used instead of :math:`H`.
+
```
[the remark this answers is not in the document]
Comment (wdzhou) [reply docs/source/fitting/fitfunctions/PseudoVoigt.rst]: I permanently changed the notation of FWHM from H to Gamma.

File: Framework/CurveFitting/src/Functions/PseudoVoigt.cpp (hunk 9 above)
Comment (wdzhou) [reply Framework/CurveFitting/src/Functions/PseudoVoigt.cpp]: constexpr does not work for any method calling sqrt() or exp() on Mantid's windows and mac osx builders.

File: Framework/CurveFitting/src/Functions/PseudoVoigt.cpp (hunk 10 above)
Comment (wdzhou) [reply Framework/CurveFitting/src/Functions/PseudoVoigt.cpp]: This one works with constexpr

File: docs/source/fitting/fitfunctions/PseudoVoigt.rst [hunk 18]
```diff
@@ -13,10 +13,136 @@ The Pseudo-Voigt function is an approximation for the Voigt function, which is a
...
+- Peak width (FWHMW :math:`H`)
+
+- Peak intensity
+
+- Peak height
+
+- Peak centre
+
+- Mixing parameter :math:`\eta` then can be estimated by peak width, intensity and height at estimated peak centre. 
+
```
[the remark this answers is not in the document]
Comment (wdzhou) [reply docs/source/fitting/fitfunctions/PseudoVoigt.rst]: It was an unfinished part. Not it is done.

**Review by mducle — DISMISSED** [review]
LGTM now.

**Review by peterfpeterson — APPROVED** [review]
