### PR TITLE
Fix unhandled exception in MuonAnalysis fit tab

### LINKED ISSUE #22042: Muon Analysis crash with data search directory
If you add the path to your data in the data search directory and then load some of the data from that location into Muon analysis then it will throw an exception when you change to the data analysis tab. 

This is because the name has been mangled: 

instrument + path

the solution is to remove the instrument if a path is given.

### PR DESCRIPTION
**Pull request by AnthonyLim23**
Muon analysis was crashing when a user directory was selected. This fixes the issue.

**To test:**
Open muon analysis
click manage user directories 
Turn off the search the data archive 
Make sure that the location of the file you are going to load is added to the search paths
Load your file via the browser
Go to data analysis (this would throw an uncaught exception in 3.12 branch) and it should be ok
Go back to home tab
Open manage user directories and remove the path to the file
Go to the data analysis tab (This works in 3.12)

Fixes #22042. 

**Release Notes** 

Not in release notes as it was broken between January and now.
---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/scientific_interfaces/Muon/MuonAnalysisFitDataPresenter.cpp [hunk 1]
```diff
@@ -303,7 +303,15 @@ std::vector<std::string> MuonAnalysisFitDataPresenter::generateWorkspaceNames(
   const auto periods = m_dataSelector->getPeriodSelections();
 
   Muon::DatasetParams params;
-  const std::string instRuns = instrument + runString;
+  std::string runNumber = runString;
+  auto index = runString.find(instrument);
```
Comment (martyngigg) [inline qt/scientific_interfaces/Muon/MuonAnalysisFitDataPresenter.cpp]: Why not add this code to `parseRunLabel` instead?

File: qt/scientific_interfaces/Muon/MuonAnalysisFitDataPresenter.cpp [hunk 2]
```diff
@@ -303,7 +303,15 @@ std::vector<std::string> MuonAnalysisFitDataPresenter::generateWorkspaceNames(
...
+  if (index != std::string::npos) {
+    // trim path
+    runNumber = runString.substr(index + instrument.size());
+    // trim extension
+    runNumber = runNumber.substr(0, runNumber.find_first_of("."));
+  }
+  const std::string instRuns = instrument + runNumber;
   std::vector<int> selectedRuns;
   MuonAnalysisHelper::parseRunLabel(instRuns, params.instrument, selectedRuns);
```
Comment (martyngigg) [inline qt/scientific_interfaces/Muon/MuonAnalysisFitDataPresenter.cpp]: Should we wrap this in a `try/catch`? If not it would still be possible for an exception generated by `parseRunLabel` to escape.

Comment (AnthonyLim23) [reply qt/scientific_interfaces/Muon/MuonAnalysisFitDataPresenter.cpp]: I think that catches in parseRunLabel should catch everything. I could add another one here for safety

File: qt/scientific_interfaces/Muon/MuonAnalysisHelper.cpp [hunk 3]
```diff
@@ -1016,9 +1016,13 @@ void parseRunLabel(const std::string &label, std::string &instrument,
...
         } else {
-          throw std::invalid_argument("Failed to parse run label: " + label);
+          throw std::invalid_argument("Failed to parse run label: " + label +
+                                      " too many tokens ");
         }
       } catch (const boost::bad_lexical_cast &) {
+        throw std::invalid_argument("Failed to parse run label: " + label +
+                                    " not a good run number");
+      } catch (...) {
         throw std::invalid_argument("Failed to parse run label: " + label);
```
Comment (martyngigg) [inline qt/scientific_interfaces/Muon/MuonAnalysisHelper.cpp]: While `catch(...)` does catch everything there is then a `throw` on the next line. Perhaps it would be better if `parseRunLabel` did catch everything and then output `runNumbers` vector was just empty if nothing could be parsed?

File: qt/scientific_interfaces/Muon/MuonAnalysisFitDataPresenter.cpp (hunk 1 above)
Comment (AnthonyLim23) [reply qt/scientific_interfaces/Muon/MuonAnalysisFitDataPresenter.cpp]: I just had a go at moving and sometimes the instrument is blank in parse run label and it therefor falls over if a path is given

**Review by martyngigg — APPROVED** [review]
I cannot induce the error any longer. The code changes that have been made are localised to where the error occurs so should be safe.

**Comment by LamarMoore** [comment]
I will check this now and then merge.

**Review by LamarMoore — APPROVED** [review]
Works as described.
