### PR TITLE
Project Recovery: Ignore empty groups when they are present in the ADS during save

### LINKED ISSUE #23901: Project Recovery: Empty groups in ADS
Project Recovery's saving thread breaks when an empty group is present in the ADS, this can be a problem when someone is developing a script that has an error and then does not have project recovery available should Mantid crash further down the line.

To see this in action use:

```python 
ws = CreateSampleWorkspace()
ws1 = CreateSampleWorkspace()
output = GroupWorkspaces(InputWorkspaces="ws,ws1")
groupWorkspace = AnalysisDataService.retrieve("output")
groupWorkspace.remove("ws")
groupWorkspace.remove("ws1")```

### PR DESCRIPTION
**Pull request by Pasarus**
**Description of work.**
Project Recovery's save thread could be segfault'd by an empty group being present in the ADS, this handles that situation by removing it before it can be acted on. 

**To test:**
- Start Mantid
- Run the Script
``` Python
ws = CreateSampleWorkspace()
ws1 = CreateSampleWorkspace()
output = GroupWorkspaces(InputWorkspaces="ws,ws1")
groupWorkspace = AnalysisDataService.retrieve("output")
groupWorkspace.remove("ws")
groupWorkspace.remove("ws1")
mantidplot.app.saveRecoveryCheckpoint()
Segfault(Dryrun=0)
```
- Re-launch mantid
- Click yes/reload last checkpoint when project recovery pops up.

Fixes #23901 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: MantidPlot/src/ProjectRecovery.cpp [hunk 1]
```diff
@@ -661,6 +665,21 @@ void ProjectRecovery::saveWsHistories(const Poco::Path &historyDestFolder) {
   }
 }
 
+void ProjectRecovery::removeEmptyGroupsFromADS(
+    std::vector<boost::shared_ptr<Mantid::API::Workspace>> &wsHandles) {
+  for (auto i = 0u; i < wsHandles.size(); ++i) {
```
Comment (OwenArnold) [inline MantidPlot/src/ProjectRecovery.cpp]: Would be done better as a range based for loop.

File: MantidPlot/src/ProjectRecovery.cpp [hunk 2]
```diff
@@ -630,6 +632,8 @@ void ProjectRecovery::saveWsHistories(const Poco::Path &historyDestFolder) {
   std::vector<boost::shared_ptr<Mantid::API::Workspace>> wsHandles =
```
Comment (OwenArnold) [inline MantidPlot/src/ProjectRecovery.cpp]: `auto wsHandles`

File: MantidPlot/src/ProjectRecovery.h [hunk 3]
```diff
@@ -114,6 +115,10 @@ class ProjectRecovery {
   // Return true if the folder at the end of the path is older than a month.
   bool olderThanAGivenTime(const Poco::Path &path, int64_t elapsedTime);
 
+  // Remove Empty WorkspaceGroups from the ADS and passed vector
+  void removeEmptyGroupsFromADS(
```
Comment (OwenArnold) [inline MantidPlot/src/ProjectRecovery.h]: This does not act on internal state. Should not be a member function.

File: MantidPlot/src/ProjectRecovery.cpp [hunk 4]
```diff
@@ -630,6 +632,8 @@ void ProjectRecovery::saveWsHistories(const Poco::Path &historyDestFolder) {
...
       ads.getObjects(Mantid::Kernel::DataServiceHidden::Include);
 
+  removeEmptyGroupsFromADS(wsHandles);
```
Comment (OwenArnold) [inline MantidPlot/src/ProjectRecovery.cpp]: I think this should be done after the check that the handles are empty. Seems more logical. Move below following statement.

Comment (OwenArnold) [reply MantidPlot/src/ProjectRecovery.cpp]: Nevertheless, this can be done as part of the existing loop lines 651. The dyanmic_cast and count-check should IMHO be performed there. That would eliminate the need for a secondary loop and the need to copy the vector of shared_ptr handles around.

**Review by OwenArnold — CHANGES_REQUESTED** [review]
I'm not clear from these changes why the segfault happens in the first place. What is the real origin of the crash? What is being assumed about the `WorkspaceGroups` when it comes to project saving and where is that?

File: MantidPlot/src/ProjectRecovery.cpp (hunk 4 above)
Comment (Pasarus) [reply MantidPlot/src/ProjectRecovery.cpp]: Check is performed before the empty check on purpose, so that it can remove groups before the check, because we want it to act as if it were empty should only empty groups remain.

File: MantidPlot/src/ProjectRecovery.cpp (hunk 1 above)
Comment (Pasarus) [reply MantidPlot/src/ProjectRecovery.cpp]: First iteration privately was, I changed from that because I needed an index to act upon on line 678 for wsHandles.erase() so I could give an accurate iterator.

File: MantidPlot/src/ProjectRecovery.h (hunk 3 above)
Comment (Pasarus) [reply MantidPlot/src/ProjectRecovery.h]: I'm not sure why that is a necessary requirement, after all it's a private member function so it's basically the same thing as a function declared in an anonymous namespace and in this case I get to define it closer to the one function that uses it?

**Comment by Pasarus** [comment]
It's being assumed that a WorkspaceGroup that is present in the ADS is that the it has groups inside of it, previously Project Recovery would just throw an error stating that fact. It then assumes that these groups have the history of the group in each of the workspaces inside of that group, it tries to access that and throws and error in Algorithm.cpp because I shouldn't be changing the GeneratePythonScript algorithm for a purely project recovery problem (This problem occurs because on line 1286 of Algorithm.cpp it checks whether it is an empty group and optional and since the property is not optional in GeneratePythonScript we get the error). An empty group should not be present in the ADS so it is safe to remove it, we explicitly make it hard for users to put it there and only in two cases I have seen where algorithms have failed mid-flow does it then crash project recovery.

File: MantidPlot/src/ProjectRecovery.cpp (hunk 4 above)
Comment (Pasarus) [reply MantidPlot/src/ProjectRecovery.cpp]: Also I don't copy them around I pass them by reference so that I can edit it on the fly, instead of making a copy.

File: MantidPlot/src/ProjectRecovery.h (hunk 3 above)
Comment (Pasarus) [reply MantidPlot/src/ProjectRecovery.h]: Closer means that I put the actual code directly below it so it is much easier to find and not at the top of the file in the anonymous namespace. I tried to find some links and I think it would be helpful to me for better understanding. Also with regards to your point 1, it doesn't change what is actually exposed outside of my class/type as it's a private member function, I believe that's where we disagree.

File: MantidPlot/src/ProjectRecovery.cpp (hunk 4 above)
Comment (OwenArnold) [reply MantidPlot/src/ProjectRecovery.cpp]: Maybe I'm missing something, but why wouldn't something along the lines of this be a better solution? As part of [this](https://github.com/mantidproject/mantid/blob/master/MantidPlot/src/ProjectRecovery.cpp#L646-L661) block
```cpp
for (auto i = 0u; i < wsHandles.size(); ++i) {
  if(auto groupWS = boost::dynamic_pointer_cast<Mantid::API::WorkspaceGroup>(wsHandles[i])) {
    if(groupWS->isEmpty())
      continue;
}
...
```

File: MantidPlot/src/ProjectRecovery.h (hunk 3 above)
Comment (OwenArnold) [reply MantidPlot/src/ProjectRecovery.h]: In a modern IDE, I don't think your code proximity has any relevance for navigation. Yes, you have to declare the function before you use it, but the declaration can be declared anywhere near your current member definition. So if proximity is an issue, you can put it directly above.

I think you're confusing the logical and physical parts of the c++ system. logically, yes this is private so it cannot be invoked from outside the object to which it belongs. However physically it gets seen as part of the pre-processor expansion of the include. i.e. any translation unit including this header will have to be recompiled. This is the whole reasoning behind PIMPL

Effective c++ item 23 (should be copies in the main office) by Scott Meyers offer a good explanation as to the topic of preferring non-member functions.

File: MantidPlot/src/ProjectRecovery.cpp (hunk 4 above)
Comment (Pasarus) [reply MantidPlot/src/ProjectRecovery.cpp]: Ah, this is something different to how I interpreted your earlier responses, that is actually a good idea! However previously I believed you were asking about the check on line 636 where a check for wsHandles.empty() is performed.

File: MantidPlot/src/ProjectRecovery.cpp [hunk 5]
```diff
@@ -647,6 +663,11 @@ void ProjectRecovery::saveWsHistories(const Poco::Path &historyDestFolder) {
   alg->setLogging(false);
 
   for (auto i = 0u; i < wsHandles.size(); ++i) {
+    // Check if workspace is an empty worksapce group and remove it if it is as
+    // well as skip
+    if (checkIfEmptyGroup(wsHandles[i]))
```
Comment (OwenArnold) [inline MantidPlot/src/ProjectRecovery.cpp]: 👍

File: MantidPlot/src/ProjectRecovery.cpp [hunk 6]
```diff
@@ -243,6 +243,24 @@ Poco::File addLockFile(const Poco::Path &lockFilePath) {
...
 }
 
+/**
+ * Checks the passed parameter and if it is an empty group then it returns true.
+ *
+ * @param ws :: check this workspace to see if it's an empty group
+ * @return true :: bool when it is an empty group
+ * @return false :: bool when it is not an empty group
+ */
+bool checkIfEmptyGroup(const Mantid::API::Workspace_sptr &ws) {
```
[the remark this answers is not in the document]
Comment (Pasarus) [reply MantidPlot/src/ProjectRecovery.cpp]: To save the build servers the hassle I'll refrain from renaming it again :)

**Review by OwenArnold — APPROVED** [review]
