### PR TITLE
Fix problem with logic for checking Efixed on indirect instruments

### LINKED ISSUE #35080: Sparse instrument feature doesn't work for indirect workspaces
Reported by Spencer Howells

Run this script (the input file is part of the Mantid test data so adjust path to match your machine):
```
from mantid.simpleapi import *

Load(Filename='C:/mantid/build/ExternalData/Testing/Data/UnitTest/iris26176_graphite002_red.nxs', OutputWorkspace='iris26176_graphite002_red')
PaalmanPingsMonteCarloAbsorption(InputWorkspace='iris26176_graphite002_red', EventsPerPoint='10', BeamHeight=3.2000000000000002, BeamWidth=2.1000000000000001, Shape='FlatPlate', Height=1, SampleWidth=1, SampleThickness=1, SampleChemicalFormula='Si', SampleDensity=1, CorrectionsWorkspace='iris26176_graphite002_MC_Corrections',
SparseInstrument=True, NumberOfDetectorRows=3, NumberOfDetectorColumns=2)
```

Gives error:

```
PaalmanPingsMonteCarloAbsorption started
Error in execution of algorithm MonteCarloAbsorption:
ExperimentInfo::getEFixed - Indirect mode efixed requested but detector has no Efixed parameter attached. ID=1
Error in execution of algorithm PaalmanPingsMonteCarloAbsorption
ExperimentInfo::getEFixed - Indirect mode efixed requested but detector has no Efixed parameter attached. ID=1
at line 403 in 'C:/MantidNightlyInstall/plugins/python\algorithms/WorkflowAlgorithms/PaalmanPingsMonteCarloAbsorption.py'
Got error from algorithm "PaalmanPingsMonteCarloAbsorption"
Stopping batch algorithm because of execution error
```

This has become obvious because the sparse instrument feature has been activated in the Indirect Corrections UI in this release (6.6). Spencer reported the problem when he ran the algorithm from this UI.

### PR DESCRIPTION
**Pull request by DannyHindson**
**Description of work.**

Only check for efixed on detectors that are associated with a spectrum when creating a sparse workspace. For the IRIS instrument only a subset of the detectors are associated with a spectrum depending on which analyzer is active.

These changes avoid an exception when trying to run an absorption correction on an IRIS workspace using the sparse workspace feature.

**To test:**

Run script on attached issue and check it doesn't fail with an exception

Fixes #35080.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by DannyHindson** [comment]
@MohamedAlmaki - I've fixed the issue that Spencer raised relating to the new Sparse workspace feature on the Indirect, Corrections UI. Let's discuss with Gemma what she thinks about putting in the release or not

File: Framework/Algorithms/src/SampleCorrections/SparseWorkspace.cpp [hunk 1]
```diff
@@ -132,7 +132,12 @@ SparseWorkspace::SparseWorkspace(const API::MatrixWorkspace &modelWS, const size
   if (eMode == Kernel::DeltaEMode::Direct) {
     mutableRun().addProperty("Ei", modelWS.getEFixed());
   } else if (eMode == Kernel::DeltaEMode::Indirect) {
-    const auto &detIDs = modelWS.detectorInfo().detectorIDs();
+    std::vector<detid_t> detIDs;
+    for (size_t i = 0; i < modelWS.getNumberHistograms(); i++) {
+      const auto &spec = modelWS.getSpectrum(i);
```
Comment (RichardWaiteSTFC) [inline Framework/Algorithms/src/SampleCorrections/SparseWorkspace.cpp:137]: Do we need a check for `isMonitor` or `hasDetector` before trying to retrieve the detector ID?

Comment (DannyHindson) [reply Framework/Algorithms/src/SampleCorrections/SparseWorkspace.cpp:137]: If the spectrum doesn't have any detectors then the getDetectorIDs calls will return nothing and the code will just insert nothing - so that part is fine I think. I'll have a think about the monitor case. I'm pretty sure the IRIS workspace that Spencer used to find this problem has a monitor so I'll see what that's actually doing in this bit of code

Comment (DannyHindson) [reply Framework/Algorithms/src/SampleCorrections/SparseWorkspace.cpp:137]: The IRIS workspace that Spencer supplied has been partially reduced in Mantid via the Indirect Reduction UI. The monitor spectrum seems to have been removed by the reduction so it's not showing up in this piece of code. Had it not been removed though I think it would have caused a problem because I don't think the monitor has an efixed value - the efixed is written to a comp assembly object ("analyzer") in the instrument definition that's a parent of all the real detectors but a parent of the monitor detector. So to be safe and more general I will add an exclusion on monitors.

Comment (SpencerHowells) [reply Framework/Algorithms/src/SampleCorrections/SparseWorkspace.cpp:138]: @DannyHindson @RichardWaiteSTFC IRIS & OSIRIS reduced data files which are used here do not indeed have the monitor spectrum.

**Review by RichardWaiteSTFC — APPROVED** [review]
Looks good - thanks for adding the monitor check to be on the safe side!
