### PR TITLE
Crystal Field Multisite Function

### LINKED ISSUE #19341: Crystal Field: better support for multi-site calculations.
During an experiment, it was found that the multi-site CrystalFieldMulti object cannot have / does not function with

 a.	Background
 b.	ResolutionModel
 c.	estimate_parameters

In case a) and b), whilst these can be set for the component sites, these properties are more properly part of the multi-site model, because only a single material is being measured. Else ties need to be established to ensure that only one background / resolution model is used (also even if this is done, the generated string is wrong, and gives an error when passed to Fit)

### PR DESCRIPTION
**Pull request by mantid-roman**
Added CrygstalFieldFunction which addresses the issues with calculations of multi-site crystal fields. 

**To test:**

See the unit tests and the doc page on the examples of usage.

Fixes #19341.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/CurveFitting/inc/MantidCurveFitting/Functions/CrystalFieldControl.h [hunk 1]
```diff
@@ -0,0 +1,125 @@
...
+  along with this program.  If not, see <http://www.gnu.org/licenses/>.
+
+  File change history is stored at: <https://github.com/mantidproject/mantid>
+  Code Documentation is available at: <http://doxygen.mantidproject.org>
+*/
+class MANTID_CURVEFITTING_DLL CrystalFieldControl
+    : public API::CompositeFunction {
+public:
+  CrystalFieldControl();
+  /// Set a value to attribute attName
```
Comment (AnthonyLim23) [inline Framework/CurveFitting/inc/MantidCurveFitting/Functions/CrystalFieldControl.h]: Is attName a typo?

Comment (mantid-roman) [reply Framework/CurveFitting/inc/MantidCurveFitting/Functions/CrystalFieldControl.h]: Yes

File: Framework/CurveFitting/inc/MantidCurveFitting/Functions/CrystalFieldFunction.h [hunk 2]
```diff
@@ -0,0 +1,247 @@
...
+
+  /// Get a reference to an attribute
+  std::pair<API::IFunction *, std::string>
+  getAttributeReference(const std::string &attName) const;
+  /// Build and cache the attribute names
+  void buildAttributeNames() const;
+
+  /// Make maps between parameter names and indices
+  void makeMaps() const;
+  void makeMapsSS() const;
```
Comment (AnthonyLim23) [inline Framework/CurveFitting/inc/MantidCurveFitting/Functions/CrystalFieldFunction.h]: what are SS, SM, MS and MM?

File: Framework/CurveFitting/src/ComplexMatrix.cpp [hunk 3]
```diff
@@ -301,8 +301,6 @@ void ComplexMatrix::eigenSystemHermitian(GSLVector &eigenValues,
   eigenValues.resize(n);
   eigenVectors.resize(n, n);
   auto workspace = gsl_eigen_hermv_alloc(n);
-  // RT: I think there is a bug in this function. It returns garbage in
-  // eigenvectors in a repeated call.
```
Comment (AnthonyLim23) [inline Framework/CurveFitting/src/ComplexMatrix.cpp]: has this bug been fixed?

Comment (mantid-roman) [reply Framework/CurveFitting/src/ComplexMatrix.cpp]: The bug wasn't in the gsl. And it has been fixed.

File: Framework/CurveFitting/src/Functions/CrystalFieldControl.cpp [hunk 4]
```diff
@@ -0,0 +1,354 @@
...
+    if (name == "Temperatures") {
+      m_temperatures = attr.asVector();
+      buildControls();
+    } else if (name == "FWHMs") {
+      m_FWHMs = attr.asVector();
+      if (m_FWHMs.size() == 1 && m_FWHMs.size() != m_temperatures.size()) {
+        m_FWHMs.assign(m_temperatures.size(), m_FWHMs.front());
+      }
+    }
+    API::IFunction::setAttribute(name, attr);
```
Comment (AnthonyLim23) [inline Framework/CurveFitting/src/Functions/CrystalFieldControl.cpp]: could we add an esle statement at the end that produces an error/warning?

File: Framework/CurveFitting/src/Functions/CrystalFieldFunction.cpp [hunk 5]
```diff
@@ -0,0 +1,1320 @@
+#include "MantidCurveFitting/Functions/CrystalFieldFunction.h"
+#include "MantidCurveFitting/Functions/CrystalElectricField.h"
```
Comment (AnthonyLim23) [inline Framework/CurveFitting/src/Functions/CrystalFieldFunction.cpp]: swap lines 1 and 2 (alphabetical order)

File: Framework/CurveFitting/src/Functions/CrystalFieldFunction.cpp [hunk 6]
```diff
@@ -0,0 +1,1320 @@
...
+}
+
+/// Get i-th parameter
+double CrystalFieldFunction::getParameter(size_t i) const {
+  checkSourceFunction();
+  checkTargetFunction();
+  if (i < m_nControlParams) {
+    return m_control.getParameter(i);
+  } else if (i < m_nControlSourceParams) {
+    return m_source->getParameter(i - m_nControlParams);
```
Comment (AnthonyLim23) [inline Framework/CurveFitting/src/Functions/CrystalFieldFunction.cpp]: should we also check if the index is valid?

File: Framework/CurveFitting/src/Functions/CrystalFieldFunction.cpp [hunk 7]
```diff
@@ -0,0 +1,1320 @@
...
+  checkSourceFunction();
+  updateTargetFunction();
+  IFunction::setUpForFit();
+}
+
+/// Declare a new parameter
+void CrystalFieldFunction::declareParameter(const std::string &, double,
+                                            const std::string &) {
+  throw Kernel::Exception::NotImplementedError(
+      "CrystalFieldFunction cannot not have its own parameters.");
```
Comment (AnthonyLim23) [inline Framework/CurveFitting/src/Functions/CrystalFieldFunction.cpp]: the double negative makes this error message a bit tricky to understand

File: Framework/CurveFitting/src/Functions/CrystalFieldFunction.cpp [hunk 8]
```diff
@@ -0,0 +1,1320 @@
...
+  for (size_t iSpec = 0; iSpec < m_control.nFunctions(); ++iSpec) {
+    std::string prefix(SPECTRUM_PREFIX);
+    prefix.append(std::to_string(iSpec)).append(".");
+    auto names = m_control.getFunction(iSpec)->getAttributeNames();
+    for (auto &name : names) {
+      name.insert(name.begin(), prefix.begin(), prefix.end());
+    }
+    m_attributeNames.insert(m_attributeNames.end(), names.begin(), names.end());
+  }
+  auto nSpec = nSpectra();
```
Comment (AnthonyLim23) [inline Framework/CurveFitting/src/Functions/CrystalFieldFunction.cpp]: this doesn't seem to be used anywhere other than the for loop below. Could we not just put 
`for (size_t iSpec = nSpectra(); iSpec < m_target->nFunctions(); ++iSpec) {`

File: Framework/CurveFitting/src/Functions/CrystalFieldFunction.cpp (hunk 6 above)
Comment (mantid-roman) [reply Framework/CurveFitting/src/Functions/CrystalFieldFunction.cpp]: We do it already. `m_nControlSourceParams` is set to the total number of parameters in `m_control` and `m_source`. `m_source->getParameter` makes also its own check.

File: Framework/CurveFitting/src/Functions/CrystalFieldFunction.cpp [hunk 9]
```diff
@@ -0,0 +1,1320 @@
...
+
+/// Build the target function in a single site - multi spectrum case.
+void CrystalFieldFunction::buildSingleSiteMultiSpectrum() const {
+  auto fun = new MultiDomainFunction;
+  m_target.reset(fun);
+
+  DoubleFortranVector en;
+  ComplexFortranMatrix wf;
+  ComplexFortranMatrix ham;
+  ComplexFortranMatrix hz;
```
Comment (AnthonyLim23) [inline Framework/CurveFitting/src/Functions/CrystalFieldFunction.cpp]: what is hz?

File: Framework/CurveFitting/src/Functions/CrystalFieldFunction.cpp [hunk 10]
```diff
@@ -0,0 +1,1320 @@
...
+  CrystalFieldUtils::buildSpectrumFunction(*spectrum, peakShape, values, xVec,
+                                           yVec, fwhmVariation, fwhm,
+                                           nRequiredPeaks, fixAllPeaks);
+  return IFunction_sptr(spectrum);
+}
+
+API::IFunction_sptr CrystalFieldFunction::buildPhysprop(
+    int nre, const DoubleFortranVector &en, const ComplexFortranMatrix &wf,
+    const ComplexFortranMatrix &ham, const std::string &propName) const {
+
```
Comment (AnthonyLim23) [inline Framework/CurveFitting/src/Functions/CrystalFieldFunction.cpp]: could make a function containing the below if statements and remove the returns. Then the new function can be called below with a get propFun and then returning it. Then the same function can be used in https://github.com/mantidproject/mantid/pull/20389/files#diff-e713a6a7351e91d3ef66099a149c18dfR936

File: Framework/CurveFitting/src/Functions/CrystalFieldFunction.cpp (hunk 9 above)
Comment (mducle) [reply Framework/CurveFitting/src/Functions/CrystalFieldFunction.cpp]: It's the Zeeman Hamiltonian term (the magnetic field dependent part) - `ham` is the crystal field Hamiltonian in zero external field. I guess it could be changed to `hzeeman` or something like that...

Comment (AnthonyLim23) [reply Framework/CurveFitting/src/Functions/CrystalFieldFunction.cpp]: I think thats a good idea. I thought it may have been the z component of the Hamiltonian.

**Comment by AnthonyLim23** [comment]
a few of the test have an index out of range

File: Framework/CurveFitting/src/Functions/CrystalFieldFunction.cpp (hunk 10 above)
Comment (mantid-roman) [reply Framework/CurveFitting/src/Functions/CrystalFieldFunction.cpp]: The reason is that this method creates functions for physical properties while the method below updates already created functions.

**Comment by AnthonyLim23** [comment]
code works as expected. The new fit functions work with the fit function GUI

**Review by AnthonyLim23 — CHANGES_REQUESTED** [review]
There are a few changes to make the code more readable. A few tests need fixing.

**Review by AnthonyLim23 — CHANGES_REQUESTED** [review]
tests need fixing and there are couple bits that are not clear in the code

File: Framework/CurveFitting/src/Functions/CrystalFieldControl.cpp (hunk 4 above)
Comment (mantid-roman) [reply Framework/CurveFitting/src/Functions/CrystalFieldControl.cpp]: I don't think it is needed here. Temperature and FWHMs require additional actions before `IFunction::setAttribute` is called.

File: Framework/CurveFitting/src/Functions/CrystalFieldFunction.cpp (hunk 7 above)
Comment (mantid-roman) [reply Framework/CurveFitting/src/Functions/CrystalFieldFunction.cpp]: :)

File: Framework/CurveFitting/src/Functions/CrystalFieldControl.cpp (hunk 4 above)
Comment (AnthonyLim23) [reply Framework/CurveFitting/src/Functions/CrystalFieldControl.cpp]: I just thought it would be good to make sure that the name is valid. So is that checked elsewhere?

Comment (mantid-roman) [reply Framework/CurveFitting/src/Functions/CrystalFieldControl.cpp]: Yes, by `IFunction::setAttribute`.

File: Framework/CurveFitting/src/Functions/CrystalFieldFunction.cpp (hunk 6 above)
Comment (AnthonyLim23) [reply Framework/CurveFitting/src/Functions/CrystalFieldFunction.cpp]: :)

**Review by AnthonyLim23 — APPROVED** [review]

**Comment by martyngigg** [comment]
@mantid-roman The RHEL failure was just a problem with that machine.

**Comment by martyngigg** [comment]
The Windows build failure is actually just a warning that is fixed in #20564

**Comment by martyngigg** [comment]
@mantid-roman The CodeConventions system test is failing.
