### PR TITLE
Ignore reduction type when not applicable

### LINKED ISSUE #33717: Ignore reduction type when not applicable
**Describe the bug**
The ISIS Reflectometry interface has a ReductionType drop-down on the Experiment Settings tab that is only applicable when SummationType is `SumInQ`. However, if you set it when SumInQ is selected then toggle to SumInLambda, it causes the reduction to fail. It should be ignored instead. Even worse, the box is greyed out so you have to toggle back to SumInQ to fix it.

**To Reproduce**

- Open the ISIS Reflectometry interface
- In the table enter run `13460` and angle `0.5`
- On the Experiment Settings tab, set the Summation Type to `SumInQ`. 
- Set ReductionType to `DivergentBeam`
- Set SummationType back to `SumInLambda`
- Back on the Runs tab, click Process. The reduction fails.

**Expected behavior**
ReductionType should be ignored for SumInLambda; or at least automatically reset back to Normal. 

It is also confusing to have the default of `Normal` which needs to be used for SumInLambda. I'm not sure why this was done but it would be better to use an empty string or some other method of being able to leave this unset instead if possible. 

It would also be preferable to hide inputs that are not applicable rather than grey them out, but this is beyond the scope of this issue as it applies to many other inputs on the interface as well.

**Screenshots**
image

**Platform/Version (please complete the following information):**
 - OS: all
 - OS Version: all
 - Mantid Version 6.3 and earlier

### PR DESCRIPTION
**Pull request by rbauststfc**
**Description of work.**

The ReductionType selected on the Experiment Settings tab is now ignored and a value of `Normal` is always used when the SummationType is SumInLambda.

Looking through the code, it seems that we're using `Normal` to represent that no ReductionType has been selected. Changing this to be a blank string throughout the code base would be ideal, but I think it would be an extensive change as it's used in lots of places. Instead I have changed the ReductionType dropdown to display a blank value rather than `Normal` to make it clear to the user that a value hasn't been set. Internally the code then converts the blank string to `Normal`.

**To test:**

- Open the ISIS Reflectometry interface
- In the table enter run 13460 and angle 0.5
- On the Experiment Settings tab, set the Summation Type to SumInQ.
- Set ReductionType to DivergentBeam
- Set SummationType back to SumInLambda
- Back on the Runs tab, click Process. The reduction should complete successfully.
- Also test that the reduction completes successfully when SummationType is set to SumInLambda and ReductionType is left blank

Fixes #33717. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/scientific_interfaces/ISISReflectometry/test/Batch/RowProcessingAlgorithmTest.h [hunk 1]
```diff
@@ -49,6 +49,14 @@ class RowProcessingAlgorithmTest : public CxxTest::TestSuite {
     checkExperimentSettings(*result);
   }
 
+  void testExperimentSettingsReductionTypeSetToNormalForSumInLambda() {
+    auto model = Batch(makeExperimentWithReductionTypeSetForSumInLambda(), m_instrument, m_runsTable, m_slicing);
```
Comment (gemmaguest) [inline qt/scientific_interfaces/ISISReflectometry/test/Batch/RowProcessingAlgorithmTest.h:53]: The test failures are caused by passing a temporary variable in the constructor of the `Batch`. This would be the right thing to do if passing by value, but the Batch constructor takes a reference, so when the temporary gets deleted, the Batch ends up holding a reference to something that doesn't exist any more. The error message about an incorrect analysis mode is just because that's the first part of the `Experiment` it attempts to use and it contains junk data.

This is easily fixed by creating a local variable the Batch can take a reference to instead for the duration of the test:

```suggestion
    auto experiment = makeExperimentWithReductionTypeSetForSumInLambda();
    auto model = Batch(experiment, m_instrument, m_runsTable, m_slicing);
```

**Review by gemmaguest — APPROVED** [review]
Code looks good and this functions as expected in all combinations of these two inputs. This is much more intuitive now, and really good to have a blank value instead of the misleading "Normal" label that was used before for when the input is ignored :+1: :+1:
