### PR TITLE
Colour Fill plots of ragged workspaces.

### LINKED ISSUE #20685: Colour fill plot doesn't show ragged workspaces correctly
### Expected behavior

Colour fill plot should draw each spectrum using that spectrum's x axis.

### Actual behavior

It seems that only the first spectrum axis is being used.

### Steps to reproduce the behavior

Draw this workspace:

```
w=CreateWorkspace(DataX='1,2,3,4,1,3,5,9,1,4,7,11,1,2,3,4', DataY='1,2,3,4,1,2,3,4,1,2,3,4', NSpec=4)
```

### Platforms affected

All

### PR DESCRIPTION
**Pull request by mantid-roman**
Check x axes of all histograms before setting the x scale.

**To test:**

Create a workspace with this script:
```
w=CreateWorkspace(DataX='1,2,3,4, 2,3,5,9, 3,4,7,11, 1,2,3,4', DataY='1,5,2,1,2,3,1,2,3,1,2,3', NSpec=4)
```
Then open a Colour Fill plot. It should show the data correctly.

Fixes #20685

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: MantidPlot/src/Spectrogram.cpp [hunk 1]
```diff
@@ -237,6 +239,25 @@ MantidQt::API::QwtRasterDataMD *Spectrogram::dataFromWorkspace(
...
+
+  // A MatrixWorkspace can be ragged. Make sure the x axis covers all
+  // histograms.
+  auto matrixWorkspace =
+      boost::dynamic_pointer_cast<const Mantid::API::MatrixWorkspace>(
+          workspace);
+  if (matrixWorkspace) {
+    for (size_t iHisto = 0; iHisto < matrixWorkspace->getNumberHistograms();
+         ++iHisto) {
+      auto &x = matrixWorkspace->x(iHisto);
```
Comment (samueljackson92) [inline MantidPlot/src/Spectrogram.cpp]: `const auto& x`?

File: MantidPlot/src/Spectrogram.cpp [hunk 2]
```diff
@@ -237,6 +239,25 @@ MantidQt::API::QwtRasterDataMD *Spectrogram::dataFromWorkspace(
...
+      if (x.front() < minX) {
+        minX = static_cast<Mantid::coord_t>(x.front());
+      }
+      if (x.back() > maxX) {
+        maxX = static_cast<Mantid::coord_t>(x.back());
+      }
+    }
+  }
```
Comment (samueljackson92) [inline MantidPlot/src/Spectrogram.cpp]: This is good. But can we move it to a separate private method? This one already does quite a lot.

**Review by samueljackson92 — CHANGES_REQUESTED** [review]
Colour fill plot now looks sensible 👍 . A couple of minor code comments.

File: MantidPlot/src/Spectrogram.cpp (hunk 1 above)
Comment (martyngigg) [reply MantidPlot/src/Spectrogram.cpp]: Should we put this code in https://github.com/mantidproject/mantid/blob/master/Framework/API/src/MatrixWorkspace.cpp#L1357 instead and have `MWXDimension` refer to the X-array with the largest extent?

Comment (mantid-roman) [reply MantidPlot/src/Spectrogram.cpp]: * `x` is `const` because `matrixWorkspace` is `const`. Plus method `x(...)` returns a `const`. Do we need another `const` here?
* I am not sure that this will work. My understanding that a MatrixWorkspace can be an MD workspace only when all x vectors are the same.

Comment (martyngigg) [reply MantidPlot/src/Spectrogram.cpp]: @mantid-roman The `const` is not strictly necessary here but I think it communicates the intent better.  

I see what you're saying although `getDimension` always worked for `MatrixWorkspace` anyway and has never checked the validity of the common bins. `MWXDimension` has always just arbitrarily referred to `x(0)` but we could just have it refer to he largest X vector and then that will at least ensure the dimension can encompass all of the data.

Comment (mantid-roman) [reply MantidPlot/src/Spectrogram.cpp]: @martyngigg There may not be a single x vector that covers the whole range. The axis vector has to be a combination of different vectors. How to bin it? Are you sure this change will not break the code that uses dimensions elsewhere?

Comment (martyngigg) [reply MantidPlot/src/Spectrogram.cpp]: @mantid-roman Good point. Let's leave this how it is for the release but I think we should see what effect it has so can we put this change into `master`?

**Review by samueljackson92 — APPROVED** [review]

**Comment by NickDraper** [comment]
Build failures are unrelated
