### PR TITLE
PaalmanPingsMonteCarloAbsorption beam profile with sparse instrument

### LINKED ISSUE #33574: PaalmanPingsMonteCarloAbsorption beam profile with sparse instrument
**Describe the bug**

An issue has been observed when sparse instrument is used to calculate absorption correction parameters with container using `PaalmanPingsMonteCarloAbsorption`. The following error is displayed: 

```
 Error in execution of algorithm MonteCarloAbsorption:
Cannot determine beam profile without a sample shape
```

This has been observed only when container geometry and material are provided and only with the sparse instrument. The issue does not seem to depend on the geometry type, as it was triggered for a flat plate and cylinder geometries.

**To Reproduce**

Run the example script below, with SparseInstrument property checked, and observe the error message:

```
import numpy as np
from mantid.simpleapi import *

kwargs = {}
kwargs['Shape'] = 'FlatPlate'
kwargs['SampleDensityType'] = 'Number Density'
kwargs['SampleNumberDensityUnit'] = 'Formula Units'
kwargs['ContainerDensityType'] = 'Number Density'
kwargs['ContainerNumberDensityUnit'] = 'Formula Units'
kwargs['SampleDensity'] = 0.1
kwargs['Height'] = 5.68
kwargs['SampleWidth'] = 0.2
kwargs['SampleChemicalFormula'] = "V"
kwargs['ContainerChemicalFormula'] = 'Al'
kwargs['ContainerDensity'] = 0.0721
kwargs['SampleThickness'] = 0.2
kwargs['ContainerFrontThickness'] = 0.1
kwargs['ContainerBackThickness'] = 0.1
kwargs['SampleAngle'] = 0
kwargs['EventsPerPoint'] = 1000

n_spec = 100
ws = CreateWorkspace(DataX=[3.15, 3.16]*n_spec, DataY=[0.1]*n_spec, 
		     NSpec=n_spec, UnitX="Wavelength", YUnitLabel="Counts")

EditInstrumentGeometry(ws,
                       PrimaryFlightPath=5.0,
                       SpectrumIDs=list(range(1, 1+n_spec)),
                       L2=[2.0]*n_spec,
                       Polar=list(np.arange(0, 120, 120/n_spec)),
                       Azimuthal=[0]*n_spec,
                       DetectorIDs=list(range(1, 1+n_spec)),
                       InstrumentName="Instrument")

SetSample(ws,
        Geometry={'Shape': 'FlatPlate', 'Height': kwargs['Height'],
                  'Width': kwargs['SampleWidth'], 'Thick': kwargs['SampleThickness'],
                  'Center': [0.,0.,0.]},
        Material={'ChemicalFormula': kwargs['SampleChemicalFormula'],
                  'NumberDensity': kwargs['SampleDensity']},
        ContainerGeometry={'Shape': 'FlatPlateHolder', 'Height': kwargs['Height'],
                  'Width': kwargs['SampleWidth'], 'Thick': kwargs['SampleThickness'],
                  'FrontThick': kwargs['ContainerFrontThickness'], 
                  'BackThick': kwargs['ContainerBackThickness'],
                  'Center': [0.,0.,0.]},
        ContainerMaterial={'ChemicalFormula': kwargs['ContainerChemicalFormula'],
                  'NumberDensity': kwargs['ContainerDensity'], 'NumberDensityUnit': kwargs['ContainerNumberDensityUnit']})     
mc_corr = PaalmanPingsMonteCarloAbsorption(ws, CorrectionsWorkspace='mc_corr',
                                           SparseInstrument=True,
                                           **kwargs)

```

**Expected behavior**

There are no errors and attenuation factors are properly calculated even if the sparse instrument is used.

**Platform/Version (please complete the following information):**
 - Mantid Version 6.3

**Additional context**

### PR DESCRIPTION
**Pull request by darominski**
**Description of work.**

This PR fixes the issue found in `MonteCarloAbsorption` algorithm, when the sparse instrument was used and container absorption was to be calculated. The proposed solution modifies the `beamProfile` function, where a test for validity of the sample shape is expanded to include the check for the existence of the environment, which should contain the information about the shape of the the container. From this information, the bounding box parameters can be obtained and a beam shape estimated.

**To test:**

Run the script from the related issue with SparseInstrument set to False and True, there should be no more issues.

Fixes #33574. 

Release notes updated.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gvardany** [comment]
Can you check if it fixes also this? https://github.com/mantidproject/mantid/issues/32243 It looks like a duplicate.

**Comment by darominski** [comment]
> Can you check if it fixes also this? #32243 It looks like a duplicate.

I see there was an issue for this then, didn't find it at the time by name. I can confirm this PR fixes the issue behind #32243.

**Comment by sf1919** [comment]
Please can you change the release note? Mantid project has now moved to separate release notes. Please see https://forum.mantidproject.org/t/move-to-separate-release-notes/803 for more information including links to new guidance for release notes.

**Review by DannyHindson — COMMENTED** [review]
I had a look into why this problem only happens when a sparse instrument is being used. I think it's because the beam profile isn't set up properly in SparseWorkspace.cpp. This PR https://github.com/mantidproject/mantid/pull/29189 added new parameter called "beam-shape" and that's not set up in the SparseWorkspace constructor (only "beam-width" and "beam-height" are copied):

```
  // Copy things needed for the simulation from the model workspace.
  auto &paramMap = instrumentParameters();
  auto parametrizedInstrument = getInstrument();
  // Copy beam parameters.
  const auto modelSource = modelWS.getInstrument()->getSource();
  const auto beamWidthParam = modelSource->getNumberParameter("beam-width");
  const auto beamHeightParam = modelSource->getNumberParameter("beam-height");
  if (beamWidthParam.size() == 1 && beamHeightParam.size() == 1) {
    auto parametrizedSource = parametrizedInstrument->getSource();
    paramMap.add("double", parametrizedSource.get(), "beam-width", beamWidthParam[0]);
    paramMap.add("double", parametrizedSource.get(), "beam-height", beamHeightParam[0]);
  }
```

So MonteCarloAbsorption::createBeamProfile doesn't find a beam shape and the fallback logic is used where the beam shape is defaulted from the sample details. I think we should probably fix the SparseWorkspace bug also because the calculation doesn't use the beam profile that is suggested by the BeamHeight and BeamWidth parameters in the PaalmanPingsMonteCarloAbsorption algorithm. Are you happy to do that? The full list of beam shape related parameters which may be present are: "beam-shape", "beam-width", "beam-height", "beam-radius". I think the SparseWorkspace constructor can just copy each of them into the sparse workspace if they're present in the modelWS ie you don't need to check if shape=slit and then copy just the width\height.

I've tested the changes you've made and they work fine and still useful in addition to what I describe above.

**Comment by darominski** [comment]
> I had a look into why this problem only happens when a sparse instrument is being used. I think it's because the beam profile isn't set up properly in SparseWorkspace.cpp. This PR #29189 added new parameter called "beam-shape" and that's not set up in the SparseWorkspace constructor (only "beam-width" and "beam-height" are copied):
> 
> ```
>   // Copy things needed for the simulation from the model workspace.
>   auto &paramMap = instrumentParameters();
>   auto parametrizedInstrument = getInstrument();
>   // Copy beam parameters.
>   const auto modelSource = modelWS.getInstrument()->getSource();
>   const auto beamWidthParam = modelSource->getNumberParameter("beam-width");
>   const auto beamHeightParam = modelSource->getNumberParameter("beam-height");
>   if (beamWidthParam.size() == 1 && beamHeightParam.size() == 1) {
>     auto parametrizedSource = parametrizedInstrument->getSource();
>     paramMap.add("double", parametrizedSource.get(), "beam-width", beamWidthParam[0]);
>     paramMap.add("double", parametrizedSource.get(), "beam-height", beamHeightParam[0]);
>   }
> ```
> 
> So MonteCarloAbsorption::createBeamProfile doesn't find a beam shape and the fallback logic is used where the beam shape is defaulted from the sample details. I think we should probably fix the SparseWorkspace bug also because the calculation doesn't use the beam profile that is suggested by the BeamHeight and BeamWidth parameters in the PaalmanPingsMonteCarloAbsorption algorithm. Are you happy to do that? The full list of beam shape related parameters which may be present are: "beam-shape", "beam-width", "beam-height", "beam-radius". I think the SparseWorkspace constructor can just copy each of them into the sparse workspace if they're present in the modelWS ie you don't need to check if shape=slit and then copy just the width\height.
> 
> I've tested the changes you've made and they work fine and still useful in addition to what I describe above.

Thank you for looking into this. I added setting of other beam parameters to the `SparseWorkspace` constructor, as requested.

**Comment by DannyHindson** [comment]
Thanks. All looks good now. One system test has just failed. It looks like it runs PaalmanPingsMonteCarloAbsorption with sparse=true. I'm guessing the cause may be an extra beam parameter in the workspace parameter map that the reference file is missing.

**Comment by darominski** [comment]
> Thanks. All looks good now. One system test has just failed. It looks like it runs PaalmanPingsMonteCarloAbsorption with sparse=true. I'm guessing the cause may be an extra beam parameter in the workspace parameter map that the reference file is missing.

I see that, we were depending on the fall-back logic to provide the beam that is larger than the sample bounding box. I am going to correct that asap, as the sample is not expected to be under-illuminated in normal conditions.

**Review by DannyHindson — DISMISSED** [review]
All looks good thanks

File: Framework/Algorithms/src/MonteCarloAbsorption.cpp [hunk 1]
```diff
@@ -416,30 +417,39 @@ MatrixWorkspace_uptr MonteCarloAbsorption::createOutputWorkspace(const MatrixWor
...
-    throw std::invalid_argument("Cannot determine beam profile without a sample shape");
-  const auto bbox = sample.getBoundingBox().width();
-  const auto bboxCentre = sample.getBoundingBox().centrePoint();
-  const double beamWidth = 2 * bboxCentre[frame->pointingHorizontal()] + bbox[frame->pointingHorizontal()];
-  const double beamHeight = 2 * bboxCentre[frame->pointingUp()] + bbox[frame->pointingUp()];
-  return std::make_unique<RectangularBeamProfile>(*frame, source->getPos(), beamWidth, beamHeight);
+  if (!sample.getShape().hasValidShape() && !sample.hasEnvironment()) {
+    throw std::invalid_argument("Cannot determine beam profile without a sample shape and environment");
+  } else {
+    V3D bbox;
```
Comment (DavidFair) [inline Framework/Algorithms/src/MonteCarloAbsorption.cpp:440]: We should omit this else branch and bring everything up one level since the throw above makes the else obsolete 
This feels like a nit, but clang-tidy also warns for this too so it's saving future work

**Review by DavidFair — CHANGES_REQUESTED** [review]
LGTM, just some minor nits

File: Framework/Algorithms/src/MonteCarloAbsorption.cpp (hunk 1 above)
Comment (DavidFair) [reply Framework/Algorithms/src/MonteCarloAbsorption.cpp:440]: So this:
```c++
  if (!sample.getShape().hasValidShape() && !sample.hasEnvironment()) {
    throw std::invalid_argument("Cannot determine beam profile without a sample shape and environment");
  } else {
    V3D bbox;
    V3D bboxCentre;
    if (sample.getShape().hasValidShape()) {
      bbox = sample.getShape().getBoundingBox().width();
      bboxCentre = sample.getShape().getBoundingBox().centrePoint();
    } else {
      bbox = sample.getEnvironment().boundingBox().width();
      bboxCentre = sample.getEnvironment().boundingBox().centrePoint();
    }
    const double beamWidth = 2 * bboxCentre[frame->pointingHorizontal()] + bbox[frame->pointingHorizontal()];
    const double beamHeight = 2 * bboxCentre[frame->pointingUp()] + bbox[frame->pointingUp()];
    return std::make_unique<RectangularBeamProfile>(*frame, source->getPos(), beamWidth, beamHeight);
  }
}
```

Can be rewritten as:
```c++
  if (!sample.getShape().hasValidShape() && !sample.hasEnvironment()) {
    throw std::invalid_argument("Cannot determine beam profile without a sample shape and environment");
  }
  V3D bbox;
  V3D bboxCentre;
  if (sample.getShape().hasValidShape()) {
    bbox = sample.getShape().getBoundingBox().width();
    bboxCentre = sample.getShape().getBoundingBox().centrePoint();
  } else {
    bbox = sample.getEnvironment().boundingBox().width();
    bboxCentre = sample.getEnvironment().boundingBox().centrePoint();
  }
  const double beamWidth = 2 * bboxCentre[frame->pointingHorizontal()] + bbox[frame->pointingHorizontal()];
  const double beamHeight = 2 * bboxCentre[frame->pointingUp()] + bbox[frame->pointingUp()];
  return std::make_unique<RectangularBeamProfile>(*frame, source->getPos(), beamWidth, beamHeight);
}
```

Since the throw causes the stack to unwind at the point of throw, so we can't get into the `else` block below making it redundant.
Clang-tidy highlights this as it usually causes us to have 2/3 nested if-else blocks (like this case) and can be bugprone so we remove the else to make the control flow easier to read-through

Comment (darominski) [reply Framework/Algorithms/src/MonteCarloAbsorption.cpp]: Now I get it, I thought that instead of flattening you are suggesting removing the case altogether. The last commit implements your suggestion.

**Review by DavidFair — APPROVED** [review]
LGTM, thanks for implementing those changes 👍
