### PR TITLE
Apply ties in correct order

### LINKED ISSUE #22925: Apply ties in correct order.
Currently parameter ties in fit functions applied in order they are set. It's not a problem as long as none of the tied parameters is used in the RHS of a tie. For example, the following ties will be applied incorrectly:
```
a = b + c
b = 2 * d
```
To make it correct the order must change:
```
b = 2 * d
a = b + c
```

### PR DESCRIPTION
**Pull request by mantid-roman**
**Description of work.**
Fit uses a list of ties sorted in such a way that a tie is applied to a parameter before it appears in the right-hand side of another tie. The sorting procedure finds any circular dependencies.

**Report to:** nobody.

**To test:**
* Define a function and set complex ties where the same parameters appear both in the left and the right-hand sides. Do a fit and check that the tie equations are satisfied.
* Check that ties that have circular dependencies make Fit give an error. Examples: `A=A`, `A=B, B=A`, `A=B, B=C, C=A`

Fixes #22925

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/API/src/IFunction.cpp [hunk 1]
```diff
@@ -1463,6 +1489,58 @@ std::vector<IFunction_sptr> IFunction::createEquivalentFunctions() const {
...
+        throw std::runtime_error(message);
+      }
+      orderedTieNodes.push_front(newNode);
+    } else {
+      orderedTieNodes.push_back(newNode);
+    }
+  }
+  for (auto &&node : orderedTieNodes) {
+    auto tie = getTie(node.left);
+    m_orderedTies.push_back(tie);
```
Comment (soininen) [inline Framework/API/src/IFunction.cpp]: `emplace_back()`?

File: Framework/API/src/IFunction.cpp [hunk 2]
```diff
@@ -1463,6 +1489,58 @@ std::vector<IFunction_sptr> IFunction::createEquivalentFunctions() const {
...
+        }
+        throw std::runtime_error(message);
+      }
+      orderedTieNodes.push_front(newNode);
+    } else {
+      orderedTieNodes.push_back(newNode);
+    }
+  }
+  for (auto &&node : orderedTieNodes) {
+    auto tie = getTie(node.left);
```
Comment (soininen) [inline Framework/API/src/IFunction.cpp]: `const`?

File: Framework/API/src/ParameterTie.cpp [hunk 3]
```diff
@@ -194,5 +194,15 @@ bool ParameterTie::findParametersOf(const IFunction *fun) const {
  */
 bool ParameterTie::isConstant() const { return m_varMap.empty(); }
 
+/** Get a list of parameters on the right-hand side of the equation
+ */
+std::vector<ParameterReference> ParameterTie::getRHSParameters() const {
+  std::vector<ParameterReference> out;
```
Comment (soininen) [inline Framework/API/src/ParameterTie.cpp]: Would it make sense to `out.reserve(m_varMap.size())`?

**Review by soininen — CHANGES_REQUESTED** [review]
The ties seem to work as promised for simple and composite functions from Python. Introducing circular dependencies throws an error as it should. Unit test have been added and generally the code changes look good. I wonder thought, shouldn't this be mentioned in the release notes?

File: docs/source/release/v3.14.0/framework.rst [hunk 4]
```diff
@@ -63,8 +63,8 @@ Bugfixes
 - :ref:`FilterEvents <algm-FilterEvents-v1>` output workspaces now contain the goniometer.
 - Fixed an issue where if a workspace's history wouldn't update for some algorithms
 - Fixed a ``std::bad_cast`` error in :ref:`algm-LoadLiveData` when the data size changes.
-- :ref:`Fit <algm-Fit>` now applies the ties in correct order independently on the order they are set. If any circular deoendencies are found
-Fit will give an error.
+- :ref:`Fit <algm-Fit>` now applies the ties in correct order independently on the order they are set. If any circular deoendencies are found Fit will give an error.
```
Comment (soininen) [inline docs/source/release/v3.14.0/framework.rst]: `deoendencies` -> `dependencies`. Sorry for initially missing this.

**Review by soininen — APPROVED** [review]
