### PR TITLE
ManageUserDirectories add missing slashes

### LINKED ISSUE #6098: Directory handling is not consistent in the Manage User Directories Dialog
This issue was originally [TRAC 5252](http://trac.mantidproject.org/mantid/ticket/5252)

Spencer has reported:

```
There is a 'feature' which sometimes throws out my routines.
In the Data Search Directories list the location ends with / or \.
Default Save Directory when you Browse & Select doesn't have the that last / or \.
Then when I do os.path.join the location is incorrect.
If I remember I add the /  !
```

We need to have a much more consistent handling of directory paths throught Mantid, i.e properties files, GUI etc

---

Keywords: NewStarter

### PR DESCRIPTION
**Pull request by josephframsay**
Slashes are now added to paths in the ManageUserDirectories dialog if they are not already there. This means that paths are treated as paths to directories, so can be loaded and joined correctly.

**To test:**

Open the 'Manage User Directories' dialog, add one of the following paths. 

- Path with no slash at the end
- Path of empty spaces
- Path with spaces at one (or both) ends
- Empty path

On reopening the dialog, the path should appear with a slash appended where appropriate.

Fixes #6098 . 

**Release Notes** 
*Does not need to be in the release notes.* - This is a minor change which Mantid should have previously handled

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] Do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: MantidQt/API/src/ManageUserDirectories.cpp [hunk 1]
```diff
@@ -119,6 +124,21 @@ void ManageUserDirectories::saveProperties() {
...
 
+/**
+ * Appends a forward slash to the end of a path if there is no slash (forward or
+ * back) there already, and strip whitespace from the path.
+ *
+ * @param path :: A reference to the path
+*/
+void ManageUserDirectories::appendSlashIfNone(QString &path) const {
+  path = path.trimmed();
+  if (path.endsWith("/") || path.endsWith("\\") || path.isEmpty()) {
```
Comment (brandonhewer) [inline MantidQt/API/src/ManageUserDirectories.cpp]: Is it possibly better to use:
```c++
if(!(path.endsWith("/") || path.endsWith("\\") || path.isEmpty())) { 
  path = path.append("/");
}
```
Rather than if-else with a return statement (i.e. using a not operator).

**Review by brandonhewer — CHANGES_REQUESTED** [review]

**Review by brandonhewer — APPROVED** [review]

**Comment by martyngigg** [comment]
@brandonhewer Can I just check that you did some functional testing here and not just a code review?

**Comment by brandonhewer** [comment]
@martyngigg Yes I tried each case given in the description (no slash at end, empty spaces, path with spaces at both ends, empty path). I also attempted adding extra slashes and whitespace into the file path. Resulting behaviour was as expected.

**Comment by martyngigg** [comment]
@brandonhewer Great. Thanks.

Just for future reference when you submit the review could you give a brief description of what you tried. It helps for future reference.
