### PR TITLE
Now uses MantidDesktopServices to open the link correctly

### LINKED ISSUE #26128: "Privacy Policy" link fails to lauch browser
### Expected behavior
Clicking privacy policy link on the "First Time Setup" screen should open privacy policy webpage. 

### Actual behavior
Screenshot from 2019-07-02 16-55-15

This dialog box is all that is shown, no browser is opened. 

### Steps to reproduce the behavior
1. Launch Mantid
2. Click first time setup from Help menu if it does not appear automatically.
3. Click privacy policy link in personal setup. 

### Platforms affected
Tested on Ubuntu 18.04.1 LTS

### PR DESCRIPTION
**Pull request by dtasev**
**Description of work.**

The dialog shown when there is an attempt to disable "Report usage data" is now a new class - `ReportUsageDisableDialog`. It should behave exactly the same, and look nearly the same.

**To test:**
#### Ubuntu
- Have Firefox as default web browser
- Open MantidPlot, wait for the "First time usage" window.
- Click "Privacy Policy", it should open in Firefox.
- Try to disable `Report usage data` (if already disabled, then enable and disable again)
- Consider if the dialog makes you want to press "No"
- If even then you pressed "Yes" the checkbox should be disabled
- Otherwise, pressing no should keep the checkbox enabled
- Pressing `Escape`, with the dialog focussed, should behave like pressing "No"

-----------

#### Windows
- Make sure "Privacy Policy" still works as before

Fixes #26128

Tagging @hsautessella for testing on Windows and how the dialog looks on 4K, and @Pasarus for Ubuntu

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: MantidPlot/src/Mantid/FirstTimeSetup.cpp [hunk 1]
```diff
@@ -10,11 +10,14 @@
...
 #include "MantidQtWidgets/Common/ManageUserDirectories.h"
 #include "MantidQtWidgets/Common/MantidDesktopServices.h"
+#include "ReportUsageDisableDialog.h"
 
+#include <QDialog>
 #include <QMessageBox>
 #include <QPainter>
 #include <QSettings>
 #include <QUrl>
+#include <iostream>
```
Comment (hsautessella) [inline MantidPlot/src/Mantid/FirstTimeSetup.cpp]: I think you may have forgotten to remove this include?

**Review by Pasarus — APPROVED** [review]
Looks good to go! LGTM

**Comment by DTasev** [comment]
RHEL7 test fail is not related to this PR
