### PR TITLE
Indirect Edit Results Option in ConvFit and IqtFit

### LINKED ISSUE #24691: Indirect - Edit Results Output Option
**Original reporter:** Spencer

### Expected behavior
During a sequential fit in Indirect Data Analysis, the end parameters of one spectrums fit become the start parameters for the next spectrum. This can be a problem if the next spectrum is not related to the previous spectrum and will lead to a bad fit.
An option to choose a spectrum to re-fit a single spectrum to get a better result and then insert it into the result workspace would be a very useful feature.

### Actual behavior
There is no options to edit the results of a fit currently.

### Steps to reproduce the behavior
1.`Interfaces`->`Indirect`->`Data Analysis`->ConvFit and IqtFit

### Platforms affected
All

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
During a sequential fit in Indirect Data Analysis, the end parameters of one spectrums fit become the start parameters for the next spectrum. This can be a problem if the next spectrum is not related to the previous spectrum and will lead to a bad fit.
This PR adds an `Edit Result` option which allows you to select a result workspace with multiple bins (produced by fitting multiple spectra at a time), and a result workspace with a single bin (produced by fitting a single spectrum) and then replace the corresponding values with the same Q in the larger workspace with the bins found in the single-bin workspace.

The output workspace is placed back into the result workspace group containing the workspace with multiple bins.

This option is only available for ConvFit and IqtFit.

**To test:**
1.`Interfaces`->`Indirect`->`Data Analysis`->`ConvFit` tab
2. Load the data below 
3. Select Fit Type to be One Lorentzian
4. Click `Run` and wait
5. Then select the spectrum selected to be `2` and click `Fit Single Spectrum`
6. Click `Edit Result` and a dialog box should appear.
7. Make sure the two output _Result workspaces are selected
8. Choose a name for your output workspace (make it different to the input workspace)
9. Click `Replace Bin`

Check the large _Results group workspace for the outputted workspace, and open this workspace. Open the original input result workspace and the result workspace corresponding to a single fit.

Compare the values in the column labelled `2` in the output workspaces with the values of the single fit result workspace - they should be the same.
Make sure that the values in the column labelled `2` in the output workspaces are different to those in the original input result workspace.

Repeat for IqtFit. Check to make sure invalid data can't be entered. Read the documentation to make sure it makes sense.

**Data Files**
ConvFit:
[iris26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2841458/iris26176_graphite002_red.zip)
[iris26173_graphite002_res.zip](https://github.com/mantidproject/mantid/files/2841459/iris26173_graphite002_res.zip)

IqtFit:
[irs26176_graphite002_iqt.zip](https://github.com/mantidproject/mantid/files/2844695/irs26176_graphite002_iqt.zip)
2 Exponentials and slide the endx slider slightly to the left

Fixes #24691 

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by TTitcombe — DISMISSED** [review]
Code changes are good. Documentation describes the changes well. Works in testing as expected

**Review by martyngigg — COMMENTED** [review]
It seems like we have written an algorithm with quite specific inputs/outputs yet the operation is actually quite general. Is there a reason to limit this to a single bin or does that just happen to be the output from a particular fit on the interface? Does it need to be limited to the indirect-style of naming?

Am I mistaken in saying that this basically is replace a range of values from one workspace with the values from another?

**Comment by robertapplin** [comment]
I and @martyngigg have decided that it would be better for a more generic algorithm to be created `CopyDataRange` which is called by the Indirect-specific algorithm `ReplaceIndirectResultBin`.

**Review by martyngigg — CHANGES_REQUESTED** [review]
As indicated by Rob we'd like to try and make the functionality a little more general as the data copying should be usable by anyone.

File: qt/widgets/common/src/WorkspaceSelector.cpp [hunk 1]
```diff
@@ -277,6 +287,24 @@ bool WorkspaceSelector::hasValidSuffix(const QString &name) const {
   return false;
 }
 
+bool WorkspaceSelector::hasValidNumberOfBins(
+    Mantid::API::Workspace_sptr object) const {
+  if (m_binLimits.first != 0 || m_binLimits.second != -1) {
+    auto const group =
+        boost::dynamic_pointer_cast<Mantid::API::WorkspaceGroup>(object);
+    if (group == nullptr) {
```
Comment (martyngigg) [inline qt/widgets/common/src/WorkspaceSelector.cpp]: It's possible that the workspace is not a `MatrixWorkspace` either. I think this would be safer if it just did
```c++
if(auto matrixWS = boost::dynamic_pointer_cast<Mantid::API::MatrixWorkspace>(object)) {
... bin number checking code
}

**Review by martyngigg — CHANGES_REQUESTED** [review]
This looks generally very good. I've just a few minor comments on the code.

File: Framework/Algorithms/src/CopyDataRange.cpp [hunk 2]
```diff
@@ -99,31 +99,22 @@ void CopyDataRange::init() {
...
   MatrixWorkspace_sptr inputWorkspace = getProperty("InputWorkspace");
-  auto const destWorkspaceName = getPropertyValue("DestWorkspace");
   MatrixWorkspace_sptr destWorkspace = getProperty("DestWorkspace");
-  auto const outputWorkspaceName = getPropertyValue("OutputWorkspace");
 
   int const specMinIndex = getProperty("StartWorkspaceIndex");
   int const specMaxIndex = getProperty("EndWorkspaceIndex");
-  int const xMinIndex = getProperty("XMinIndex");
-  int const xMaxIndex = getProperty("XMaxIndex");
+  int const xMinIndex = getProperty("XMin");
```
Comment (martyngigg) [inline Framework/Algorithms/src/CopyDataRange.cpp]: My apologies I don't think I explained myself too well here. I meant have `XMin` and `XMax` be the X values and not the indices as `CropWorkspace` does. It feels a little inconsistent to have one take indices and one take values. Would this be possible?

File: Framework/Algorithms/src/CopyDataRange.cpp [hunk 3]
```diff
@@ -155,28 +143,20 @@ void CopyDataRange::exec() {
...
+  int const xMaxIndex = getProperty("XMax");
   int const yInsertionIndex = getProperty("InsertionYIndex");
   int const xInsertionIndex = getProperty("InsertionXIndex");
+  MatrixWorkspace_sptr outputWorkspace = getProperty("OutputWorkspace");
+
+  if (destWorkspace != outputWorkspace)
```
Comment (martyngigg) [inline Framework/Algorithms/src/CopyDataRange.cpp]: Good. Can we add a unit test that covers the case where output = destination?

**Review by martyngigg — CHANGES_REQUESTED** [review]

File: Framework/Algorithms/src/CopyDataRange.cpp (hunk 2 above)
Comment (robertapplin) [reply Framework/Algorithms/src/CopyDataRange.cpp]: Ahh I understand now 👍

File: Framework/Algorithms/src/CopyDataRange.cpp [hunk 4]
```diff
@@ -17,23 +18,54 @@ using namespace Mantid::HistogramData;
 
 namespace {
 
+std::size_t getBinIndexOfValue(NumericAxis const *axis, double value) {
```
Comment (martyngigg) [inline Framework/Algorithms/src/CopyDataRange.cpp]: Would it be possible to use [MatrixWorkspace::binIndexOf](https://github.com/mantidproject/mantid/blob/master/Framework/API/inc/MantidAPI/MatrixWorkspace.h#L147) directly instead? I think this is the same thing?

Comment (robertapplin) [reply Framework/Algorithms/src/CopyDataRange.cpp]: `binIndexOf` appears to be doing something different - it doesn't return the right index when I tried using it!

File: Framework/API/src/MatrixWorkspace.cpp [hunk 5]
```diff
@@ -1260,28 +1262,54 @@ size_t MatrixWorkspace::binIndexOf(const double xValue,
...
-    }
-    hops = std::distance(xValues.cbegin(), lowit);
+    if (isHistogram && lowerIter == xValues.cbegin())
+      ++lowerIter;
+    else if (!isHistogram && lowerIter == xValues.cend())
+      --lowerIter;
+
+    hops = std::distance(xValues.cbegin(), lowerIter);
+
+    // If the tolerance makes no difference in the chosen iterator
```
Comment (martyngigg) [inline Framework/API/src/MatrixWorkspace.cpp]: Could you help me understand what this comment means and what the next if is doing? I don't quite follow it...

It is also generally better do avoid comparing double values exactly so it might be better to say `tolerance > 0.0` here rather than `!= 0`.

Comment (martyngigg) [reply Framework/API/src/MatrixWorkspace.cpp]: I'm finding the code a little difficult to follow as we have many `isHistogram` checks and 2 places that seem to have the same check for `tolerance != 0.0`. Would it be possible just to have a single check for `isHistogram` and the `if` part deals with that and the `else` deals with point data?

File: Framework/API/test/MatrixWorkspaceTest.h [hunk 6]
```diff
@@ -1732,7 +1732,114 @@ class MatrixWorkspaceTest : public CxxTest::TestSuite {
     checkDetectorSignedTwoTheta(Geometry::X, {{1., -1., -1., 1.}});
   }
 
+  void
+  test_that_binIndexOf_returns_the_correct_index_for_a_histogram_workspace_when_the_x_bins_are_in_ascending_order() {
+    std::vector<double> const xValues{1.0, 2.0, 3.0, 4.0};
+    auto const workspace = getWorkspaceWithPopulatedX(1, 4, 3, xValues);
+
+    TS_ASSERT_EQUALS(workspace.binIndexOf(3.0), 1);
```
Comment (martyngigg) [inline Framework/API/test/MatrixWorkspaceTest.h]: It's good we have more tests around this now. Could we add some different values for each of them so that we're not just testing the boundaries? I think the tests in `testBinIndexOf` could just be moved here?

File: Framework/API/test/MatrixWorkspaceTest.h [hunk 7]
```diff
@@ -1732,7 +1732,114 @@ class MatrixWorkspaceTest : public CxxTest::TestSuite {
...
+  }
+
+  void
+  test_that_binIndexOf_returns_the_correct_index_for_a_histogram_workspace_when_the_x_bins_are_in_descending_order() {
```
Comment (martyngigg) [inline Framework/API/test/MatrixWorkspaceTest.h]: Similarly the tests in `testBinIndexOfDescendingBinning` could go here?

**Review by martyngigg — CHANGES_REQUESTED** [review]
These are some really good changes and great extra tests.

The only thing I'm struggling with now is the name of the method. `binIndex` could now be misleading for point data so I'm wondering about changing it to something like `yIndexOf`? I'm wondering if that better reflects its intent? What do you think?

File: Framework/API/src/MatrixWorkspace.cpp (hunk 5 above)
Comment (robertapplin) [reply Framework/API/src/MatrixWorkspace.cpp]: I think I will change this to make it easier to read. If the workspace is for point data and the xValue passed is not stored in the xValues (+- tolerance), then this should probably throw (rather than having the if statement above)

**Comment by robertapplin** [comment]
@martyngigg I agree the name should probably be changed. Do you mean `xIndexOf` rather than `yIndexOf`?

**Comment by martyngigg** [comment]
@robertapplin I think this is where some of the confusion comes from with bin. The intention of the function originally was to give back the index of the bin centre of a histogram that contained the specified value. This would then correspond to the index of the Y value in the histogram not the index of the X value.

For example, asking for bin index of `value=2.5` gives back index=1 because it's the index of the bin, i.e the Y value and not edge that contains that value:
```
|  0  |  1  |
0     1     2
```

For the point data, as `len(Y)==len(X)`, then we would expect the indices to match for X and Y so in your case xIndexOf would work.

File: Framework/PythonInterface/mantid/api/src/Exports/MatrixWorkspace.cpp [hunk 8]
```diff
@@ -277,6 +297,13 @@ void export_MatrixWorkspace() {
            "Return the Run object for this workspace (deprecated, use "
            ":class:`~mantid.api.MatrixWorkspace.getRun` "
            "instead)")
+      .def("binIndexOf", &binIndexOfDeprecated,
+           MatrixWorkspace_yIndexOfXOverloads(
```
Comment (martyngigg) [inline Framework/PythonInterface/mantid/api/src/Exports/MatrixWorkspace.cpp]: So this is not quite there as it actually links `binIndexOf` to the `yIndexOverloads` and so the deprecation warning doesn't get out. I think we'll need to create an overloader for the `binIndexOfDeprecated` function with `BOOST_PYTHON_FUNCTION_OVERLOADS`. I think we can have the `binIndex` version not have the tolerance argument as it didn't have it before.

**Review by martyngigg — CHANGES_REQUESTED** [review]
This all works nicely and the extra tests are great. Just a minor thing to fix up with the deprecation warning and then we are good to go.

**Review by martyngigg — DISMISSED** [review]
This looks good now.

**Review by martyngigg — APPROVED** [review]
