### PR TITLE
Indirect Data Analysis - FABADA PDF plotting options

### LINKED ISSUE #24534: Indirect ConvFit - Plotting options for FABADA PDF data
**Original reporter:** Spencer

### Expected behavior
There should be plotting options for the output FABADA PDF data within the ConvFit interface.
Creating a more generic design (MVP) for the output options may be a good solution/addition.

### Steps to reproduce the behavior
1.`Interfaces`->`Indirect`->`Data Analysis`->`ConvFit` interface
2. Load the data below
3. Fit type is `TeixeiraWater`. FlatBackground and DeltaFunction
4. Select `FABADA` as the minimizer
5. Make sure that PDF is checked
6. Set the Fit String to be `0`
7. Click Run and wait

There should be a _PDFs workspace among the output workspaces. The ConvFit interface should have options for the plotting of this.

### Platforms affected
All

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR introduces an MVP style for the plotting options at the bottom of the MSDFit, IqtFit, ConvFit and JumpFit interfaces.
This PR introduces plotting options for the FABADA PDF output workspace in ConvFit and IqtFit.

**To test:**
1.`Interfaces`->`Indirect`->`Data Analysis`->`IqtFit` interface
2. Load the data below
3. Set as `2` exponentials
4. Move the endx slider on the miniplot a little to the left
5. Select `FABADA` as the minimizer and ensure PDF is ticked
6. Set the Fit string to be `0-2`
7. Click run and wait
8. Look at the output plot options. Make sure that:
  - The plot options are disabled while plotting is taking place
  - The plot options will plot the relevant parameters (in the combobox) when `Plot` is clicked
  - Select the PDF Group. Select one of its workspaces and a parameter and make sure `Plot` works
9. Change minimizer and click run again. The output options should only have the parameter combobox and Plot button

Repeat for `ConvFit` but select One Lorentzian, Delta function and flat background. This will take much longer to run.

**Data Files**
**IqtFit:**
[irs26176_graphite002_iqt.zip](https://github.com/mantidproject/mantid/files/2782977/irs26176_graphite002_iqt.zip)
**ConvFit:**
[irs26176_withhistory_red.zip](https://github.com/mantidproject/mantid/files/2782978/irs26176_withhistory_red.zip)
[irs26173_graphite002_res.zip](https://github.com/mantidproject/mantid/files/2782979/irs26173_graphite002_res.zip)

Make sure the new unit test files pass.

Fixes #24534

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/scientific_interfaces/Indirect/IndirectFitOutputOptionsView.cpp [hunk 1]
```diff
@@ -0,0 +1,124 @@
...
+
+#include <QMessageBox>
+
+namespace MantidQt {
+namespace CustomInterfaces {
+namespace IDA {
+
+IndirectFitOutputOptionsView::IndirectFitOutputOptionsView(QWidget *parent)
+    : IIndirectFitOutputOptionsView(parent),
+      m_outputOptions(new Ui::IndirectFitOutputOptions) {
```
Comment (SamJenkins1) [inline qt/scientific_interfaces/Indirect/IndirectFitOutputOptionsView.cpp]: its best to avoid using new wherever possible, maybe `std::make_unique<Ui::IndirectFitOutputOptions>()`

File: qt/scientific_interfaces/Indirect/IndirectFitAnalysisTab.cpp [hunk 2]
```diff
@@ -307,6 +284,13 @@ void IndirectFitAnalysisTab::setSpectrumSelectionView(
           m_fittingModel.get(), view);
 }
 
+void IndirectFitAnalysisTab::setOutputOptionsView(
+    IIndirectFitOutputOptionsView *view) {
+  m_outOptionsPresenter =
+      Mantid::Kernel::make_unique<IndirectFitOutputOptionsPresenter>(
+          new IndirectFitOutputOptionsModel(), view);
```
Comment (SamJenkins1) [inline qt/scientific_interfaces/Indirect/IndirectFitAnalysisTab.cpp]: Since this is created and then passed in immediately, it looks like its an owning pointer, is it possible to move in a smart pointer here? looking further in it looks like maybe its not due to QT

**Review by LowriJenkins — CHANGES_REQUESTED** [review]
a little pointer stuff first that might be able to be handled a little better

File: qt/scientific_interfaces/Indirect/test/IndirectFitOutputOptionsPresenterTest.h [hunk 3]
```diff
@@ -0,0 +1,430 @@
+// Mantid Repository : https://github.com/mantidproject/mantid
+//
+// Copyright &copy; 2018 ISIS Rutherford Appleton Laboratory UKRI,
+//     NScD Oak Ridge National Laboratory, European Spallation Source
+//     & Institut Laue - Langevin
+// SPDX - License - Identifier: GPL - 3.0 +
```
Comment (SamJenkins1) [inline qt/scientific_interfaces/Indirect/test/IndirectFitOutputOptionsPresenterTest.h]: if this file is new remember that its not 2018 anymore

File: qt/scientific_interfaces/Indirect/test/IndirectFitOutputOptionsModelTest.h [hunk 4]
```diff
@@ -0,0 +1,270 @@
+// Mantid Repository : https://github.com/mantidproject/mantid
+//
+// Copyright &copy; 2018 ISIS Rutherford Appleton Laboratory UKRI,
+//     NScD Oak Ridge National Laboratory, European Spallation Source
+//     & Institut Laue - Langevin
+// SPDX - License - Identifier: GPL - 3.0 +
```
Comment (SamJenkins1) [inline qt/scientific_interfaces/Indirect/test/IndirectFitOutputOptionsModelTest.h]: not 2018 anymore

File: qt/scientific_interfaces/Indirect/IndirectFitOutputOptionsView.h [hunk 5]
```diff
@@ -0,0 +1,68 @@
+// Mantid Repository : https://github.com/mantidproject/mantid
+//
+// Copyright &copy; 2018 ISIS Rutherford Appleton Laboratory UKRI,
+//     NScD Oak Ridge National Laboratory, European Spallation Source
+//     & Institut Laue - Langevin
+// SPDX - License - Identifier: GPL - 3.0 +
```
Comment (SamJenkins1) [inline qt/scientific_interfaces/Indirect/IndirectFitOutputOptionsView.h]: not 2018

File: qt/scientific_interfaces/Indirect/IndirectFitOutputOptionsView.cpp [hunk 6]
```diff
@@ -0,0 +1,124 @@
+// Mantid Repository : https://github.com/mantidproject/mantid
+//
+// Copyright &copy; 2018 ISIS Rutherford Appleton Laboratory UKRI,
+//     NScD Oak Ridge National Laboratory, European Spallation Source
+//     & Institut Laue - Langevin
+// SPDX - License - Identifier: GPL - 3.0 +
```
Comment (SamJenkins1) [inline qt/scientific_interfaces/Indirect/IndirectFitOutputOptionsView.cpp]: not 2018

File: qt/scientific_interfaces/Indirect/IndirectFitOutputOptionsPresenter.h [hunk 7]
```diff
@@ -0,0 +1,70 @@
+// Mantid Repository : https://github.com/mantidproject/mantid
+//
+// Copyright &copy; 2018 ISIS Rutherford Appleton Laboratory UKRI,
+//     NScD Oak Ridge National Laboratory, European Spallation Source
+//     & Institut Laue - Langevin
+// SPDX - License - Identifier: GPL - 3.0 +
+#ifndef MANTID_CUSTOMINTERFACES_INDIRECTFITOUTPUTOPTIONSPRESENTER_H_
```
Comment (SamJenkins1) [inline qt/scientific_interfaces/Indirect/IndirectFitOutputOptionsPresenter.h]: not 2018

File: qt/scientific_interfaces/Indirect/IndirectFitOutputOptionsPresenter.cpp [hunk 8]
```diff
@@ -0,0 +1,152 @@
+// Mantid Repository : https://github.com/mantidproject/mantid
+//
+// Copyright &copy; 2018 ISIS Rutherford Appleton Laboratory UKRI,
+//     NScD Oak Ridge National Laboratory, European Spallation Source
+//     & Institut Laue - Langevin
+// SPDX - License - Identifier: GPL - 3.0 +
+#include "IndirectFitOutputOptionsPresenter.h"
```
Comment (SamJenkins1) [inline qt/scientific_interfaces/Indirect/IndirectFitOutputOptionsPresenter.cpp]: not 2018

File: qt/scientific_interfaces/Indirect/IndirectFitOutputOptionsModel.h [hunk 9]
```diff
@@ -0,0 +1,80 @@
+// Mantid Repository : https://github.com/mantidproject/mantid
+//
+// Copyright &copy; 2018 ISIS Rutherford Appleton Laboratory UKRI,
+//     NScD Oak Ridge National Laboratory, European Spallation Source
+//     & Institut Laue - Langevin
+// SPDX - License - Identifier: GPL - 3.0 +
```
Comment (SamJenkins1) [inline qt/scientific_interfaces/Indirect/IndirectFitOutputOptionsModel.h]: not 2018

File: qt/scientific_interfaces/Indirect/IndirectFitOutputOptionsModel.cpp [hunk 10]
```diff
@@ -0,0 +1,245 @@
+// Mantid Repository : https://github.com/mantidproject/mantid
+//
+// Copyright &copy; 2018 ISIS Rutherford Appleton Laboratory UKRI,
+//     NScD Oak Ridge National Laboratory, European Spallation Source
+//     & Institut Laue - Langevin
+// SPDX - License - Identifier: GPL - 3.0 +
+#include "IndirectFitOutputOptionsModel.h"
```
Comment (SamJenkins1) [inline qt/scientific_interfaces/Indirect/IndirectFitOutputOptionsModel.cpp]: not 2018

File: qt/scientific_interfaces/Indirect/IIndirectFitOutputOptionsView.h [hunk 11]
```diff
@@ -0,0 +1,63 @@
+// Mantid Repository : https://github.com/mantidproject/mantid
+//
+// Copyright &copy; 2018 ISIS Rutherford Appleton Laboratory UKRI,
+//     NScD Oak Ridge National Laboratory, European Spallation Source
+//     & Institut Laue - Langevin
+// SPDX - License - Identifier: GPL - 3.0 +
+#ifndef MANTIDQTCUSTOMINTERFACESIDA_IINDIRECTFITOUTPUTOPTIONSVIEW_H_
```
Comment (SamJenkins1) [inline qt/scientific_interfaces/Indirect/IIndirectFitOutputOptionsView.h]: not 2018

File: qt/scientific_interfaces/Indirect/IIndirectFitOutputOptionsModel.h [hunk 12]
```diff
@@ -0,0 +1,57 @@
+// Mantid Repository : https://github.com/mantidproject/mantid
+//
+// Copyright &copy; 2018 ISIS Rutherford Appleton Laboratory UKRI,
+//     NScD Oak Ridge National Laboratory, European Spallation Source
+//     & Institut Laue - Langevin
+// SPDX - License - Identifier: GPL - 3.0 +
+#ifndef MANTIDQTCUSTOMINTERFACESIDA_IINDIRECTFITOUTPUTOPTIONSMODEL_H_
```
Comment (SamJenkins1) [inline qt/scientific_interfaces/Indirect/IIndirectFitOutputOptionsModel.h]: not 2018

**Review by LowriJenkins — CHANGES_REQUESTED** [review]
Im not able adjust EndX using the slider (though it updates fine when changed manually in fitting range.)
The `Plot Current Preview` button is not locked like the other plotting options, if you delete all the generted workspaces after running once (i.e. all but the loaded iqt workspace) then run again and click the plot current preview, mantid will crash.

ConvFit does not appear to share these problems.

**Review by LowriJenkins — APPROVED** [review]
