### PR TITLE
Saved instrument view shapes crash mantid.

### LINKED ISSUE #19725: Instrument view saves shapes into a workspace that may crash mantid.
### Expected behavior

Uncertain but definitely shouldn't crash.

### Actual behavior

The table workspace created by the [Save Shapes to Table] button on the Draw tab doesn't contain the information about the shapes. It is unclear what to do with the workspace but dragging and dropping it to the Instrument view crashes mantid.

### Steps to reproduce the behavior

* Open instrument view.
* Draw some shapes.
* Save them to a table workspace.
* Double click on the created workspace to open a table view.
* Drag and drop the table workspace to the instrument view.
* Crash

### Platforms affected

All

### PR DESCRIPTION
**Pull request by mantid-roman**
An open table view truncate the parameter string for a shape. This leads to a null pointer returned by a factory method.

Added a check for a null pointer.

**To test:**

Instructions are in the issue description.

Fixes #19725.

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: MantidQt/MantidWidgets/src/InstrumentView/Shape2DCollection.cpp [hunk 1]
```diff
@@ -685,7 +685,9 @@ void Shape2DCollection::loadFromTableWorkspace(
   for (size_t i = 0; i < ws->rowCount(); ++i) {
     const auto params = col[i];
     auto shape = Shape2D::loadFromProject(params);
-    m_shapes.append(shape);
+    if (shape != nullptr) {
```
Comment (DavidFair) [inline MantidQt/MantidWidgets/src/InstrumentView/Shape2DCollection.cpp]: This can be done as
`if (shape)`

Comment (mantid-roman) [inline MantidQt/MantidWidgets/src/InstrumentView/Shape2DCollection.cpp]: My thinking for doing it was:
1. According to mantid C++ coding standards: *Integers should not be cast to Booleans.* Raw pointers can be considered integers.
2. `auto shape` hides the actual type of variable `shape`. Comparing it with `nullptr` shows its type clearly, no need to investigate further what `if (shape)` means.

Comment (DavidFair) [inline MantidQt/MantidWidgets/src/InstrumentView/Shape2DCollection.cpp]: Ahh from the `auto` type I assumed this would be a pointer type. 
If it could be integer as implied with point 1. I agree this check should be against a `nullptr` type.

**Comment by DavidFair** [comment]
This PR fixes the crash described in the issue. :shipit:
