### PR TITLE
Fix plotting in old Muon Analysis GUI

### LINKED ISSUE #28080: Muon analysis old cannot plot
Open MantidPlot
Open Muon analysis old
Click load current run
A blank plot will appear and the logger will say:

```
TypeErrorLplotSpectrum() got an unexpected keyword argument 'source'
at line 61 in '<interface>'
caused by line 30 in '<interface>'
```

good starting point
https://github.com/mantidproject/mantid/blob/master/qt/scientific_interfaces/Muon/MuonAnalysis.cpp#L1775

### PR DESCRIPTION
**Pull request by StephenSmith25**
The old Muon Anaylsis GUI could no longer plot data. The error was occurring as the old Muon GUI was calling the newly exposed version of plotSpectrum, rather than the old qtplotting version.

**Description of work.**
The old GUI now calls the intended version of the function

**To test:**

1. Launch MantidPlot
2. Open the old Muon Analysis Interface
3. Load some data
4. **Should now be able to plot the data**

Fixes #28080. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/scientific_interfaces/Muon/MuonAnalysis.cpp [hunk 1]
```diff
@@ -1826,7 +1826,7 @@ void MuonAnalysis::plotSpectrum(const QString &wsName, bool logScale) {
   s << "def plot_data(ws_name,errors, connect, window_to_use):";
   if (parsePlotType(m_uiForm.frontPlotFuncs) == PlotType::Asymmetry) {
     // clang-format off
-    s << "  w = plotSpectrum(source = ws_name,"
+    s << "  w = pymantidplot.plotSpectrum(source = ws_name,"
```
Comment (martyngigg) [inline qt/scientific_interfaces/Muon/MuonAnalysis.cpp]: I was wondering if we could fix this another way with this patch: https://gist.github.com/martyngigg/0db2f49bb1d70fbdd85a8435a69e59f2. It will fix all of the plotting I think as it will just delete the new `plotSpectrum` from `mantid.simpleapi`.

**Review by martyngigg — CHANGES_REQUESTED** [review]

File: qt/scientific_interfaces/Muon/MuonAnalysis.cpp (hunk 1 above)
Comment (martyngigg) [reply qt/scientific_interfaces/Muon/MuonAnalysis.cpp]: Then we won't need to call `pymantidplot` especially anywhere.

Comment (StephenSmith25) [reply qt/scientific_interfaces/Muon/MuonAnalysis.cpp]: Yeah, that seems to work well and is a nice solution to the issue :+1:  . Maybe I don't have a full understanding of the problem, but would we never want to call the new versions of plotSpectrum and plotBin from MantidPlot, or are they inherently incompatible?

Comment (martyngigg) [reply qt/scientific_interfaces/Muon/MuonAnalysis.cpp]: The main problem was that any import like `from mantid.simpleapi *` would just overwrite the MantidPlot ones and any call to it in MantidPlot should use the old API.  They are supplied for workbench as a transition to keep scripts working and if they need to be accessed in workbench it would be possible to do from `mantid.plots import plotSpectrum` still.

**Review by martyngigg — DISMISSED** [review]
This looks good and should mean the old plotting functions used by any GUIs in MantidPlot keep working.

**Comment by AnthonyLim23** [comment]
@martyngigg are you happy with this? I think your old review got dismissed

**Review by martyngigg — APPROVED** [review]

**Comment by martyngigg** [comment]
@AnthonyLim23 Yes this is fine. I didn't realise the base-branch change dismissed reviews.
