### PR TITLE
Fix for Slice Viewer crash when peak is added in area of no coverage

### LINKED ISSUE #15162: Adding a Peak in the SliceViewer can happen in regions of no-coverage
Issue reported by Pascal Manuel during Beta Testing for 3.6

**To Reproduce**
* Create a MDEventWorkspace in HKL space. The Topaz scripts under the VATES/Diffraction script section should help with this
* Ensure you have a PeaksWorkspace available.
* Open the SliceViewer and PeaksViewer mode with the PeaksWorkspace
* Using the "Add Peaks" button on the PeaksViewer add a peak to a non-zero region of the Q-space map. This should work.
* Now try adding a peak off the covered region. This causes an exception about detectors not being found. 

**Note on Fix**
This is probably down to the constructor of the Peak type, which tries to find a detector based on the HKL position. This will not be possible. It would be better to either catch this exception and not add the peak, or prevent the peak being added in the first place.

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
Fixes #15162

Please see [here](https://github.com/mantidproject/mantid/issues/15162#issuecomment-182376955) for an issue description and suggested solution.

As mentioned in the link above the issue arises from a negative `qbeam` with:

``` cpp
  const double qBeam = q.scalar_prod(refBeamDir) * qSign; 
```

where q is the center of the peak in reciprocal space. This means that back-scattering components are not allowed (??).

@OwenArnold : 
- Does it make sense that qBeam cannot be negative and if so, why?
# For testing:

Please find an installer, a sample workspace and a corresponding peaks workspace here: TODO
1. Load the workspace into the Slice Viewer
2. Drag and drop the peaks workspace onto the SliceViewer
3. Slect the `Add peaks` feature
4. Start adding peaks on the centre of the workspace
   - Confirm that everything is OK
5. Add a peak on the outer right edge of the workspace (i got the issue there). You might have to try several areas.
   - Confirm that Mantid does not terminate.
   - Confirm that an error message is displayed instead
   - Confirm that no peak is generated

### CODE REVIEW

**Comment by matthew-d-jones** [comment]
Carried out test as described in PR. All behaves as expected. Code change looks fine.

File: MantidQt/SliceViewer/src/ConcretePeaksPresenter.cpp [hunk 1]
```diff
@@ -580,7 +580,16 @@ bool ConcretePeaksPresenter::addPeakAt(double plotCoordsPointX,
...
   alg->setProperty("Workspace", peaksWS);
   alg->setProperty("HKL", std::vector<double>(hkl));
-  alg->execute();
+
+
+// Execute the algorithm
+try {
+    alg->execute();
+} catch (...) {
+    g_log.warning("ConcretePeaksPresenter: Could not add the peak. Make sure "
```
Comment (OwenArnold) [inline MantidQt/SliceViewer/src/ConcretePeaksPresenter.cpp]: Personally, I would have put the bit about it being a "ConcretePeaksPresenter", into a separate debug message, as is not something we expect users observing Warnings to understand, but otherwise looks good.
