### PR TITLE
 Fix IDF loading for CreatesimulationWorkspace

### LINKED ISSUE #15674: CreateSimulationWorkspace does not load the correct IDF
__Issue__
The algorithm `CreateSimulationWorkspace` can be initialized with the input from `.nxs` or `.raw` files. Internally it creates an empty instrument, based on a dummy workspace with a time stamp from when it was created, ie it will point to the newest IDF. The data set to which this instrument is compared might be pointing to a different IDF with a different wiring table. 

__Solution__

Add a start date to the dummy workspace which is based on the start date of the input workspace

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
Fixes #15674.

**Issue**

The `CreateSimulationWorkspace`  can be used with a reference workspace (either Nexus or Raw). The simulation workspace currently loads the newest IDF, which does not necessarily match the reference workspace's IDF. This can lead to inconsistencies in the simulation workspace.

**Solution**

The simualtion workspace creates a blank dummy workspace initially. We populate the start and end times with the times from the refernce workspaces. This will pull in the adequate IDF.
# For testing

You can manually check two scenarios which were also added to the unit tests. You will need the unit test data available. We test two data sets which were measured around 2008/2009 and should be associated to the IDF `LOQ_Definition_20020226-.xml` (The current IDF for LOQ is `LOQ_Definition_20121016-` though)

**Test that correct IDF for Raw file is pulled in**
- Open Mantid
- Load the file `LOQ48094.raw`
  - Confirm (in the MantidDock) that the loaded IDF is `LOQ_Definition_20020226-.xml`
- Run:

``` python
ws = CreateSimulationWorkspace(Instrument="LOQ", BinParams="-30,3,279",UnitX="DeltaE",DetectorTableFileName="LOQ48094.raw")
```
- Check that the IDF of `ws` is also `LOQ_Definition_20020226-.xml`

**Test that correct IDF for Nexus file is pulled in**

Run the same protocol as above, but  use `LOQ49886.nxs`
# Release notes

Check changes in `framework.rst` file.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [x] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/DataHandling/test/StartAndEndTimeFromNexusFileExtractorTest.h [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+        "2010-06-09T14:29:07-04:00");
+
+    TSM_ASSERT("Should have the same start time",
+               startTime == expectedStartTimeString);
+    TSM_ASSERT("Should have the same end time",
+               endTime == expectedEndTimeString);
+  }
+};
+
+#endif /* MANTID_DATAHANDLING_STARTANDENDTIMEFROMNEXUSFILEEXTRACTORTEST_H_ */
```
Comment (matthew-d-jones) [inline Framework/DataHandling/test/StartAndEndTimeFromNexusFileExtractorTest.h]: Missing line at end of file

File: Framework/DataHandling/test/StartAndEndTimeFromNexusFileExtractorTest.h [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+    auto startTime = extractor.extractStartTime(fullFilePath);
+    auto endTime = extractor.extractEndTime(fullFilePath);
+
+    // Assert
+    Mantid::Kernel::DateAndTime expectedStartTimeString("2008-12-18T17:58:38");
+    Mantid::Kernel::DateAndTime expectedEndTimeString("2008-12-18T18:06:20");
+    TSM_ASSERT("Should have the same start time",
+               startTime == expectedStartTimeString);
+    TSM_ASSERT("Should have the same end time",
+               endTime == expectedEndTimeString);
```
Comment (matthew-d-jones) [inline Framework/DataHandling/test/StartAndEndTimeFromNexusFileExtractorTest.h]: The same test is repeated, refactor to a method (with filename, expected start and expected end arguments)?

File: Framework/DataHandling/test/CreateSimulationWorkspaceTest.h [hunk 3]
```diff
@@ -174,6 +200,50 @@ class CreateSimulationWorkspaceTest : public CxxTest::TestSuite {
...
+    TS_ASSERT_THROWS_NOTHING(alg->execute());
+    TS_ASSERT(alg->isExecuted());
+    Mantid::API::Workspace_sptr outWS = alg->getProperty("OutputWorkspace");
+    auto matWS =
+        boost::dynamic_pointer_cast<Mantid::API::MatrixWorkspace>(outWS);
+    auto idfForOriginal = matWS->getInstrument()->getFilename();
+    auto idfForSimulationWS =
+        simulationWorkspace->getInstrument()->getFilename();
+    TSM_ASSERT_EQUALS("Should have the same IDF", idfForOriginal,
+                      idfForSimulationWS);
```
Comment (matthew-d-jones) [inline Framework/DataHandling/test/CreateSimulationWorkspaceTest.h]: The Raw and Nexus tests are basically the same, refactor to use common method?

File: Framework/DataHandling/inc/MantidDataHandling/StartAndEndTimeFromNexusFileExtractor.h [hunk 4]
```diff
@@ -0,0 +1,60 @@
...
+  Mantid::Kernel::DateAndTime extractDateAndTime(TimeType type,
+                                                 std::string filename) const;
+  NexusType whichNexusType(std::string filename) const;
+  Mantid::Kernel::DateAndTime handleMuonNexusFile(TimeType type,
+                                                  std::string filename) const;
+  Mantid::Kernel::DateAndTime
+  handleProcessedNexusFile(TimeType type, std::string filename) const;
+  Mantid::Kernel::DateAndTime handleISISNexusFile(TimeType type,
+                                                  std::string filename) const;
+  Mantid::Kernel::DateAndTime handleTofRawNexusFile(TimeType type,
```
Comment (matthew-d-jones) [inline Framework/DataHandling/inc/MantidDataHandling/StartAndEndTimeFromNexusFileExtractor.h]: All methods are `const`, should this really be a class?

**Comment by matthew-d-jones** [comment]
Functional tests behaved as expected, release notes have been updated and code looks good.
:shipit:
