### PR TITLE
Fix SANS ILL Integration test flaky when default facility changed

### LINKED ISSUE #27022: SANSILLIntegrationTest Failure due to Default Facility Setting
### Expected behavior
The passing of the test should not depend on the Facility from the general settings. 
### Actual behavior
The test fails if the Facility is not set to ILL. 
### Steps to reproduce the behavior
1. Launch workbench/plot
2. Set the facility to ILL.
3. Run `ctest -R SANSILLIntegrationTest`
4. See the test pass.
5. Re-open Mantid and set the facility to any other.
6. Re-run `ctest -R SANSILLIntegrationTest --output-on-failure`
7. See the test fail, unable to find the file for the run number.
### Platforms affected
Observed on Ubuntu 18.04

### PR DESCRIPTION
**Pull request by DavidFair**
**Description of work.**
Fixes the SANS ILL Integration test becoming flaky when the default facility is changed. This is because the file finder will prepend an instrument name, which the ILL does not use, as the instrument was not previously changed.

I've also taken this chance to modernise older code in the `ConfigService` 

**To test:**
- Open Mantid and change the default inst to SNS
- Run the `SANSILLIntegrationTest` using ctest and check is passes
- Open Mantid and change to something that is not SNS
- Rerun the test
- Re-open Mantid and check it's still set to your previous val

Fixes #27022. 

*This does not require release notes* because it is a change only dev's will notice

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by Harrietbrown — DISMISSED** [review]
The default facility does not change after running the `SANSILLIntegrationTest` Good work.

File: Framework/Kernel/src/ConfigService.cpp [hunk 1]
```diff
@@ -1982,22 +1980,28 @@ ConfigServiceImpl::getFacility(const std::string &facilityName) const {
...
     g_log.error("Failed to set default facility to be " + facilityName +
                 ". Facility not found");
-    throw Exception::NotFoundError("Facilities", facilityName);
+    throw;
+  }
+  assert(foundFacility);
+  setString("default.facility", facilityName);
+
+  const auto &associatedInsts = foundFacility->instruments();
+  if (associatedInsts.size() == 0) {
```
Comment (gvardany) [inline Framework/Kernel/src/ConfigService.cpp]: Can we use `empty()` here instead?
I'm wondering what needs to be done in this case, maybe one should actually throw instead of just logging? Otherwise, what will be the value of the `default.instrument` ?

Comment (DavidFair) [reply Framework/Kernel/src/ConfigService.cpp]: Good catch
I've added a step to throw if there are no instruments, as I suspect that people will start to rely on this without checking that the chosen facility has correctly set an instrument (however unlikely) so throwing should alert us something screwy is happening

**Comment by gvardany** [comment]
@Harrietbrown Can you check once more?

**Review by Harrietbrown — APPROVED** [review]
Confirm this still functions as described and with no issues i can see in code review
