### PR TITLE
InstrumentMaskTab Exception Fix

### LINKED ISSUE #23548: Mask detector not working properly for SNAP ESS
**Original reporter:** Malcom Guthrie (ESS)

### Expected behavior

`Apply Mask` should not throw an error

### Actual behavior

`Apply Mask` throws an unhandled exception

### Steps to reproduce the behavior

* Get the data file `//olympic/Babylon5/Public/KeithButler/8x8r.nxs`
* Load the file in Mantid
* Go to the instrument view of the workspace
* Change `d-spacing` range to 0.94 - 0.99
* Set view to full 3D
* Go to the `Draw` tab
* Draw a small square over the detector view
* Click `Apply to Data`
* Mantid throws an exception 

### Platforms affected

All

### PR DESCRIPTION
**Pull request by LamarMoore**
**Description of work.**

Detector masking in the `InstrumentView` was broken after the introduction of the `InputWorkspaceIndexProperty` in `MaskBins` which no longer allowed duplicate workspace indices. When extracting workspace indices from the detector mask, a set is not used to ensure that no duplicates exist.

**Report to:** [user name]/[nobody]. 

**To test:**

See the original issue for details on how to test.

Fixes #23548. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/widgets/instrumentview/src/InstrumentActor.cpp [hunk 1]
```diff
@@ -1063,14 +1063,19 @@ void InstrumentActor::setDataIntegrationRange(const double &xmin,
...
     auto index = getWorkspaceIndex(det);
     if (index == INVALID_INDEX)
       continue;
-    wsIndices.emplace_back(index);
+    wi.insert(index);
   }
+
+  // We will be able to do this more efficiently in C++17
+  std::vector<size_t> wsIndices(wi.size());
+  std::copy(wi.begin(), wi.end(), wsIndices.begin());
```
Comment (SimonHeybrock) [inline qt/widgets/instrumentview/src/InstrumentActor.cpp]: Can't you just write this as `std::vector<size_t> wsIndices(wi.begin(), wi.end());`?

**Review by keeeto — APPROVED** [review]
This fixes the issue reported by the user.
