### PR TITLE
Calibration changes for MaNDi

### LINKED ISSUE #20051: SCDCalibratePanels fails for some MaNDi peaks
### Expected behavior
Good Calibration
### Actual behavior
Negative wavelength for some peaks

### PR DESCRIPTION
**Pull request by VickieLynch**
A few weak MaNDi peaks need try/catch for changing Q.

**To test:**
https://www.dropbox.com/s/f4u3ifre37j8gc7/natrolite_Niggli.integrate?dl=0
```python
#MANDI Detector calibration using new SCDCalibratePanels, 07/14/2017
LoadIsawPeaks(Filename='natrolite_Niggli.integrate', OutputWorkspace='Natrolite_Peaks')
FindUBUsingIndexedPeaks(PeaksWorkspace='Natrolite_Peaks', Tolerance=0.20000000000000001)
IndexPeaks(PeaksWorkspace='Natrolite_Peaks', Tolerance=0.25, RoundHKLs=False)

SCDCalibratePanels(PeakWorkspace='Natrolite_Peaks', 
  a=6.5840, b=9.7254, c=9.8911, 
  alpha=83.531, beta=70.560, gamma=70.215, 
  ChangeT0=True, EdgePixels=16, 
  DetCalFilename='MANDI_2017B.DetCal')

#Reindex and refine lattice constant for Natrolite crystal using new MANDI detector calibration
LoadIsawDetCal(InputWorkspace='Natrolite_Peaks', Filename='MANDI_2017B.DetCal')
FindUBUsingFFT(PeaksWorkspace='Natrolite_Peaks', MinD=5, MaxD=11, Tolerance=0.18)
IndexPeaks(PeaksWorkspace='Natrolite_Peaks', RoundHKLs=False)
```

Fixes #20051 

**Release Notes** 

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by VickieLynch** [comment]
@rosswhitfield MaNDi uses peaks from PredictPeaks so I need to catch a few peaks that are no longer there with the instrument calibration.  Would you test?

**Comment by rosswhitfield** [comment]
Can you put `MANDI_2017B.DetCal` somewhere I can access so I can test this.

**Comment by VickieLynch** [comment]
@rosswhitfield Sorry to mislead you with the script.  MANDI_2017.DetCal is the output of the calibration.  I just removed the reference to my directory so it works for you.

**Comment by VickieLynch** [comment]
[MANDI_2017B.DetCal.txt](https://github.com/mantidproject/mantid/files/1190438/MANDI_2017B.DetCal.txt)

File: Framework/Crystal/src/SCDCalibratePanels.cpp [hunk 1]
```diff
@@ -262,12 +262,17 @@ void SCDCalibratePanels::exec() {
...
     V3D Q2 = lattice0.qFromHKL(hkl);
-    peak.setInstrument(inst);
-    peak.setQSampleFrame(Q2);
-    peak.setHKL(hkl);
+    try {
+      peak.setInstrument(inst);
+      peak.setQSampleFrame(Q2);
+      peak.setHKL(hkl);
+    } catch (...) {
+      g_log.notice() << "Problem in applying calibration to peak " << i << "\n";
```
Comment (rosswhitfield) [inline Framework/Crystal/src/SCDCalibratePanels.cpp]: Would it be better to grab the error message and include it in the notice so that you know what the problem was?

**Review by rosswhitfield — CHANGES_REQUESTED** [review]
:+1: SCDCalibratePanels now works for this example, skipping over peaks when needed.

File: Framework/Crystal/src/SCDCalibratePanels.cpp (hunk 1 above)
Comment (VickieLynch) [inline Framework/Crystal/src/SCDCalibratePanels.cpp]: made this change

**Review by rosswhitfield — APPROVED** [review]

**Comment by quantumsteve** [comment]
build errors appear related to #19941.
