### PR TITLE
Reset loader name and version at end of algorithm

### LINKED ISSUE #37236: Load Algorithm no longer sets LoaderName
**Describe the bug**

When attempting to use the Load algorithm, if you do not set the LoaderName it used to set it for you once it ascertained the correct loader.  Now it does not.
[SNAPRed](https://github.com/neutrons/SNAPRed/) currently depends on this feature.

Based on my initial investigation, specifically [these lines](https://github.com/mantidproject/mantid/commit/117047e2c648750ef8e5d6f5b307b6ccb6012de8#diff-c2b373b035fb1f1debadccc5ca62f9a0b6750735af530723f5fba6b35797a425R346-R350) cause issue because now it doesn't call getFileLoader which is what sets the LoaderName [here](https://github.com/mantidproject/mantid/blob/117047e2c648750ef8e5d6f5b307b6ccb6012de8/Framework/DataHandling/src/Load.cpp#L199)

**To Reproduce**
1. Load any file with Load, do not set the LoaderName

or 

2. run SNAPRed's unit tests with pytest
(you'll need to build our conda env first, probably the first option will suffice)

or

2. Run this script within workbench.  Run in a prior version of workbench, then run in a dev build out of `main`.

``` python
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

workspace = mtd.unique_name(prefix="loadTest_")
filename = os.path.expanduser("~/test_file.nxs")

# create an easily readable event file
CreateWorkspace(
    OutputWorkspace=workspace,
    DataX=[0.5, 1.5],
    DataY=[0],
    DataE=[0.01],
    NSpec=1,
)
SaveNexus(
    Filename=filename,
    InputWorkspace=workspace,
)

# run the algorithm to get the loader name
load = AlgorithmManager.create("Load")
load.setProperty("Filename", filename)
load.setProperty("OutputWorkspace", "ws")
load.setProperty("LoaderName", "")
load.execute()
assert load.getPropertyValue("LoaderName") == "LoadNexusProcessed"
```

**Expected behavior**
LoaderName is set with correct loader name once algo completes successfully.

**Screenshots**

image

**Platform/Version (please complete the following information):**
 - OS: all?
 - OS Version:
 - Mantid Version mantid                    6.9.20240425.1854 py310hf6feea2_0    mantid/label/nightly

**Additional context**

### PR DESCRIPTION
**Pull request by rboston628**
#### Summary of work

The `Load` algorithm searches for the best loading algorithm to use to load a file, then returns the loaded workspace, the name of the loader used, and the version of the loader used.

A minor issue allowed a user to overwrite the name and version of the loader, resulting in invalid returns on those outputs.

This makes sure the loader name and version are correctly set at the end of the algorithm.

Fixes #37236 . 

#### Further detail of work
The `Load` algorithm terminates with a call to set the child loader, then sets the output workspace property.

At this point, the other two output properties can be set.

### To test:

I added a unit test which will make sure the loader and version are always set by the end of a program.

Run this script from within workbench.

``` python
from mantid.simpleapi import (
    AlgorithmManager,
    CreateSampleWorkspace,
    SaveNexus,
    Load,
    mtd,
)

inputWS = mtd.unique_name(prefix="loadTest_")
outputWS = mtd.unique_name(prefix="loadTest_")
filename = os.path.expanduser("~/test_file.nxs")

# create an easily readable event file
CreateSampleWorkspace(
    OutputWorkspace=inputWS,
    Random=True,
)
SaveNexus(
    Filename=filename,
    InputWorkspace=inputWS,
)

load = AlgorithmManager.create("Load")
load.setProperty("Filename", filename)
load.setProperty("OutputWorkspace", outputWS)
load.setProperty("LoaderName", "")
load.execute()

assert mtd[inputWS].getNumberHistograms() == mtd[outputWS].getNumberHistograms()
for i in range(mtd[inputWS].getNumberHistograms()):
    assert list(mtd[inputWS].readX(i)) == list(mtd[outputWS].readX(i))
    assert list(mtd[inputWS].readY(i)) == list(mtd[outputWS].readY(i))
print(load.getPropertyValue("LoaderName"))
assert load.getPropertyValue("LoaderName") == "LoadNexusProcessed"
```

If run out of an older version of mantid, this will pass.  If run out of a build from `main`, the very last line will fail.

Pull this branch and build, then launch workbench.  The script should run with no issues.

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by rboston628** [comment]
Failure was in random system test, PythonChannelTest
``` bash
======================================================================
ERROR: test_PythonLoggingChannel_update_instruments (PythonChannels.PythonLoggingTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/jenkins_workdir/workspace/pull_requests-conda-linux/Testing/SystemTests/tests/framework/PythonChannels.py", line 87, in test_PythonLoggingChannel_update_instruments
    self._create_script_and_execute(LoggingClass="PythonLoggingChannel", UpdateInstrumentDefinitions=1)
  File "/jenkins_workdir/workspace/pull_requests-conda-linux/Testing/SystemTests/tests/framework/PythonChannels.py", line 99, in _create_script_and_execute
    result = subprocess.run([sys.executable, TEST_SCRIPT_NAME], timeout=60)  # This will raise subprocess.TimeoutExpired if deadlocke
  File "/jenkins_workdir/workspace/pull_requests-conda-linux/mambaforge/envs/mantid-developer/lib/python3.10/subprocess.py", line 505, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/jenkins_workdir/workspace/pull_requests-conda-linux/mambaforge/envs/mantid-developer/lib/python3.10/subprocess.py", line 1154, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/jenkins_workdir/workspace/pull_requests-conda-linux/mambaforge/envs/mantid-developer/lib/python3.10/subprocess.py", line 2047, in _communicate
    self.wait(timeout=self._remaining_time(endtime))
  File "/jenkins_workdir/workspace/pull_requests-conda-linux/mambaforge/envs/mantid-developer/lib/python3.10/subprocess.py", line 1209, in wait
    return self._wait(timeout=timeout)
  File "/jenkins_workdir/workspace/pull_requests-conda-linux/mambaforge/envs/mantid-developer/lib/python3.10/subprocess.py", line 1951, in _wait
    raise TimeoutExpired(self.args, timeout)
subprocess.TimeoutExpired: Command '['/jenkins_workdir/workspace/pull_requests-conda-linux/mambaforge/envs/mantid-developer/bin/python3', 'pythonloggingtestscript.py']' timed out after 59.99998100101948 seconds

----------------------------------------------------------------------
```

**Review by robertapplin — CHANGES_REQUESTED** [review]
Thanks for this fix, looks good! Happy to approve once the unit test is finished

**Review by robertapplin — DISMISSED** [review]

File: Framework/DataHandling/src/Load.cpp [hunk 1]
```diff
@@ -340,6 +340,9 @@ void Load::exec() {
 
   // Set the remaining properties of the loader
   setOutputProperties(m_loader);
+  // Set the loader and version from correct loader
+  setPropertyValue("LoaderName", m_loader->name());
```
Comment (peterfpeterson) [inline Framework/DataHandling/src/Load.cpp:344]: This should be protected with an `if (m_loader)` in case no loader was chosen. The `assert` in `getFileLoader()` is only run in debug builds.

Comment (rboston628) [reply Framework/DataHandling/src/Load.cpp:344]: Thanks, I added this protection and a lengthier comment explaining the reason for those two lines.

**Review by peterfpeterson — DISMISSED** [review]
Thanks for bringing back this functionality

**Review by peterfpeterson — DISMISSED** [review]

**Review by peterfpeterson — APPROVED** [review]
