### PR TITLE
Fix crash when group workspace is validated by ReflectometryBackgroundSubtraction

### LINKED ISSUE #33627: ReflectometryBackgroundSubtraction dialog crashes if workspace group present in ADS
I've just spent some time investigating an obscure crash in the docs build on Jenkins in a PR (https://github.com/mantidproject/mantid/pull/33609) where I had added a new usage example to one of the correction algorithms (DiscusMultipleScatteringCorrection). The crash was caused by the fact that I had forgotten to clear down the ADS at the end of the new usage example and the algorithm had left behind a workspace group in the ADS. 

This was causing the doc build on ReflectometryBackgroundSubtraction to crash later on because it couldn't display the algorithm dialog. The crash happens in ReflectometryBackgroundSubtraction::validateInputs when validating the "ProcessingInstructions" parameter. Somewhere in the code it tries to cast the input workspace to a MatrixWorkspace and throws an unhandled exception if the cast doesn't succeed - which I guess it doesn't if the input is a workspace group.

The cause of the problem wasn't v clear from the Jenkins logs so I think it would be useful if the dialog for ReflectometryBackgroundSubtraction would still display even if a workspace group is in the ADS (which I guess gets used as the default input workspace if it's lying around).

I've added the missing mtd.clear() to my new usage example to fix this on my PR so no major hurry - or I can pick up in the next maintenance cycle perhaps if you agree this is useful

@gemmaguest, @DavidFair - just put in this issue relating to one of the reflectometry algorithms. Is this one of yours and if yes is this something you'd be happy to pick up at some point?

### PR DESCRIPTION
**Pull request by cailafinn**
**Description of work.**
When validating inputs the conversion of the index property to an index
set was causing unhandled exceptions that could crash mantid if run and
would interfere with the doc tests if not. This adds a catch for that
behaviour and also warns the user that they may not use a group
workspace for this algorithm (in the dialogue anyway, running from a script automatically converts group workspaces to re-run the algorithm for each member, so gets around the issue. This should probably be remedied at some point to have consistent behaviour, but is outside the scope of this PR and certainly not this close to release).

**To test:**

1. Put an empty group workspace in the ADS:
```
from mantid import api
groupws = api.WorkspaceGroup()
mtd['group'] = groupws
```
2. Open the ReflectometryBackgroundSubtraction dialogue 
3. It should open cleanly
4. Hit run with the group selected as the input workspace
5. The InputWorkspace property should be highlighted with an error

Fixes #33627 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Reflectometry/src/ReflectometryBackgroundSubtraction.cpp [hunk 1]
```diff
@@ -290,7 +290,13 @@ std::map<std::string, std::string> ReflectometryBackgroundSubtraction::validateI
 
   MatrixWorkspace_const_sptr inputWS = getProperty("InputWorkspace");
   auto indexProp = dynamic_cast<IndexProperty *>(getPointerToProperty("ProcessingInstructions"));
-  Indexing::SpectrumIndexSet indexSet = *indexProp;
+  Indexing::SpectrumIndexSet indexSet;
+  try {
+    indexSet = *indexProp;
+  } catch (std::runtime_error &e) {
```
Comment (robertapplin) [inline Framework/Reflectometry/src/ReflectometryBackgroundSubtraction.cpp:296]: I think this can be const
```suggestion
  } catch (const std::runtime_error &e) {
```

**Review by robertapplin — CHANGES_REQUESTED** [review]
This works as described and the code looks good. Is it possible to add a test for this?

**Comment by ConorMFinn** [comment]
> Is it possible to add a test for this?

As it was to do with the algorithm dialog, I didn't think it was. But after some more thought it is possible to do some kind of testing for it at least

**Review by robertapplin — APPROVED** [review]
Thanks for adding a test, looks good to me
