### PR TITLE
Muon crash

### LINKED ISSUE #20693: Muon Analysis crash
Muon Analysis will crash if the user deletes all of the workspaces while in the data analysis tab.

### PR DESCRIPTION
**Pull request by AnthonyLim23**
Just added an error message if the user deletes all of the files while using muon analysis. 

Fixes #20693. 

**Release Notes** 

---
Does not need to be in release notes -not reported by user. 

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by samueljackson92** [comment]
@AnthonyLim23 This stops the crash but now I get:
```
No Data available. Please load Some data.
```

Printed 5 times when I open the interface.

**Comment by AnthonyLim23** [comment]
ah. That will be because it sets up the interface at start up and there will be no data. The message is relevant but if we want to remove it we will need to be a bit more clever.

File: qt/widgets/common/src/MuonFitPropertyBrowser.cpp [hunk 1]
```diff
@@ -348,6 +348,10 @@ void MuonFitPropertyBrowser::setWorkspaceName(const QString &wsName) {
 * @param prop :: A pointer to the function name property
 */
 void MuonFitPropertyBrowser::enumChanged(QtProperty *prop) {
+  if (m_workspaceNames.empty() && this->isVisible()) {
+    g_log.error("No Data available. Please load Some data.");
+    return;
+  }
```
Comment (samueljackson92) [inline qt/widgets/common/src/MuonFitPropertyBrowser.cpp]: This is still not quite right. I think we always want to return when `m_workspaceNames` is empty but we only want to print the error if the `this` is visible AND `m_workspaceNames` is empty. 

i.e.
```cpp
if(m_workspaceNames.empty()) {
    if (this->visible()))
        g_log.error("...");
    return;
}
```

**Review by samueljackson92 — CHANGES_REQUESTED** [review]

**Review by samueljackson92 — APPROVED** [review]
This no longer crashes and now only shows an error on the tab that causes the crash.
