### PR TITLE
Muon analysis multiple fitting label

### LINKED ISSUE #22824: Muon Analysis multiple fitting label
In muon analysis loading current run and using the multiple fitting interface can cause problems.

**Original reporter:** Adrian. 
Open muon analysis
Load current run
Do a multiple fit
Go to previous run (arrow) 
Do a multiple fit - the label will be a path (wrong)
Go to previous run
Do a multiple fit - the label will not update at all

### PR DESCRIPTION
**Pull request by AnthonyLim23**
In muon analysis the loading the current run would cause problems for the multiple fitting label. 

**Report to:**Adrian. 

**To test:**

Open muon analysis
Go to the settings tab and make sure that the multiple fitting is enabled
On the home tab press `load current run` (set the instrument to HIFI)
Go the the groupings tab and add a second pair by typing a name in to the box below the one which says `long`
Go to the data analysis tab
The label will be the run number (without the leading zeros)
Go to the home tab and press the back arrow (to load previous run)
Go to the data analysis tab and the name should be updated (previously it was the path to the file)
Go to the home tab and press the back arrow (to load previous run)
Go to the data analysis tab and the name should be updated (previously it did not update from the path)

Fixes #22824. 

Does this update require release notes?
- [x ] Yes
- [ ] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] Do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/widgets/common/src/MuonFitDataSelector.cpp [hunk 1]
```diff
@@ -356,7 +356,23 @@ QString MuonFitDataSelector::getSimultaneousFitLabel() const {
  * @param label :: [input] Text to set as label
  */
 void MuonFitDataSelector::setSimultaneousFitLabel(const QString &label) {
-  m_ui.txtSimFitLabel->setText(label);
+  // do some checks that it is valid
+  auto safeLabel = label.toStdString();
+  auto index = safeLabel.find(".nxs");
```
Comment (NickDraper) [inline qt/widgets/common/src/MuonFitDataSelector.cpp]: This hard codes .nxs as the extension, don't you really mean any extension?

File: qt/widgets/common/src/MuonFitDataSelector.cpp [hunk 2]
```diff
@@ -356,7 +356,23 @@ QString MuonFitDataSelector::getSimultaneousFitLabel() const {
...
+  if (index != std::string::npos) {
+    safeLabel = safeLabel.substr(0, index);
+  }
+  index = safeLabel.find_last_of("\\");
```
Comment (NickDraper) [inline qt/widgets/common/src/MuonFitDataSelector.cpp]: This will only work on windows

File: qt/widgets/common/src/MuonFitDataSelector.cpp [hunk 3]
```diff
@@ -356,7 +356,23 @@ QString MuonFitDataSelector::getSimultaneousFitLabel() const {
...
+  if (index != std::string::npos) {
+    safeLabel = safeLabel.substr(index + 1, safeLabel.size());
+    // need to remove instrument name and leading zeros
+    index = safeLabel.find_last_of("0");
```
Comment (NickDraper) [inline qt/widgets/common/src/MuonFitDataSelector.cpp]: I think you have a problem here, INST0001234 would work, but INST0001101 would fail badly, and INST12345 would also give problems.

File: qt/widgets/common/src/MuonFitDataSelector.cpp [hunk 4]
```diff
@@ -356,7 +356,23 @@ QString MuonFitDataSelector::getSimultaneousFitLabel() const {
...
+    safeLabel = safeLabel.substr(index, safeLabel.size());
+    while (safeLabel.front() == '0') {
```
Comment (NickDraper) [inline qt/widgets/common/src/MuonFitDataSelector.cpp]: If the line above had worked as intended (and it doesn't) you wouldn't need this loop

**Review by NickDraper — CHANGES_REQUESTED** [review]
Several concerns with the code as is.

For rewriting consider the following:
1. Leave the string as q QString, it has much better manipulation methods on it.
2. QFileInfo.basename() will do a better cross platform job of removing extensions and file paths.
https://doc.qt.io/archives/qt-4.8/qfileinfo.html
3. A regular expression QRegExp will probably do a better job of extracting the run number from a filename.
This should work as a regex "[\D0]+(\d*)?"
https://regex101.com/r/LIywEl/1

File: qt/widgets/common/src/MuonFitDataSelector.cpp (hunk 1 above)
Comment (AnthonyLim23) [reply qt/widgets/common/src/MuonFitDataSelector.cpp]: it could be any extension yes, but it is always nxs (at present)

File: qt/widgets/common/src/MuonFitDataSelector.cpp (hunk 2 above)
Comment (AnthonyLim23) [reply qt/widgets/common/src/MuonFitDataSelector.cpp]: If I am not mistaken the load current run only works on windows, so other platforms will not see this error

File: qt/widgets/common/src/MuonFitDataSelector.cpp (hunk 3 above)
Comment (AnthonyLim23) [reply qt/widgets/common/src/MuonFitDataSelector.cpp]: ah, that should be first_of. I know that there will be at least one leading zero

File: qt/widgets/common/src/MuonFitDataSelector.cpp (hunk 4 above)
Comment (AnthonyLim23) [reply qt/widgets/common/src/MuonFitDataSelector.cpp]: Its because I dont know how many leading zeros are prersent

**Review by NickDraper — COMMENTED** [review]
Code review is now good, should work for common file names

**Review by NickDraper — APPROVED** [review]

**Comment by AnthonyLim23** [comment]
@mantidproject/gatekeepers could we get this into the release branch?

**Comment by martyngigg** [comment]
@AnthonyLim23 The target branch for this PR was set to `master` so it go merged there. For the future can you make sure the target branch is set to `release-next`. I've manually merged the branch into `release-next`.
thanks

**Comment by AnthonyLim23** [comment]
thank you. I missed the branch by mistake.
