### PR TITLE
CubicSpline : fix sorting of y-values

### LINKED ISSUE #19990: CubicSpline : fix in sorting y values
CubicSpline automatically sorts the x-values of the input, if they are not in ascending order. However it should also sort the y-values correspondingly.

### PR DESCRIPTION
**Pull request by gvardany**
This PR fixes the issue in sorting of x-y arrays in CubicSpline, when the input x-array is not initially in ascending order. 

**To test:**

Code review & tests pass.

Fixes #19990 . 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/CurveFitting/src/Functions/CubicSpline.cpp [hunk 1]
```diff
@@ -79,26 +79,39 @@ void CubicSpline::setupInput(boost::scoped_array<double> &x,
   bool xSortFlag = false;
```
Comment (AnthonyLim23) [inline Framework/CurveFitting/src/Functions/CubicSpline.cpp]: I would change this variable name, I found it to be misleading. I was expecting it to be true if the data was sorted correctly.

**Review by AnthonyLim23 — COMMENTED** [review]
the test passes

**Review by AnthonyLim23 — APPROVED** [review]
looks good to me
