### PR TITLE
Cuboid/Hexahedron bug fix

### LINKED ISSUE #15999: hexahedron incorrectly treated as a cuboid
I found several places where hexahedron is being treated as a cuboid and giving incorrect results. The occurs because cuboid and hexadron return the same type in [`GluGeometryHandler::GetObjectGeom(...)`](https://github.com/mantidproject/mantid/blob/master/Framework/Geometry/src/Rendering/GluGeometryHandler.cpp#L92)

There are at least two places in Object.cpp (
[here](https://github.com/mantidproject/mantid/blob/master/Framework/Geometry/src/Objects/Object.cpp#L1019) and [here](https://github.com/mantidproject/mantid/blob/master/Framework/Geometry/src/Objects/Object.cpp#L1605)) that call [Object::SolidAngleHelper]( 
https://github.com/mantidproject/mantid/blob/master/Framework/Geometry/src/Objects/Object.cpp#L1158), which uses only four of the eight points.

Hexahedron given the type "box", and therefore doesn't throw an exception.
https://github.com/mantidproject/mantid/blob/master/Framework/Geometry/src/Instrument/ObjCompAssembly.cpp#L385

### PR DESCRIPTION
**Pull request by LamarMoore**
The GluGeometry handler no longer returns the same type for cuboids and hexahedra when the geometry is queried. SolidAngles for Hexahedra and Cuboids are now handled separately. A hexahedron special case will be developed as a part of another issue as this functionality is not urgent. Another issue to address the weakly typed enums for the glugeometryhandler/object can be found here #16057 

Code Review

Fixes #15999.

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by quantumsteve** [comment]
At Framework/Geometry/src/Objects/Object.cpp#L1029, hexadrons are being treated as spheres.

File: Framework/Geometry/src/Rendering/GluGeometryHandler.cpp [hunk 1]
```diff
@@ -95,9 +95,6 @@ void GluGeometryHandler::GetObjectGeom(int &mytype,
     vectors = m_points;
     switch (type) {
     case CUBOID:
-      mytype = 1;
-      break;
-    case HEXAHEDRON:
```
Comment (quantumsteve) [inline Framework/Geometry/src/Rendering/GluGeometryHandler.cpp]: Since `HEXAHEDRON` doesn't have a height or radius, should it use the default?

File: Framework/Geometry/inc/MantidGeometry/Rendering/GluGeometryHandler.h [hunk 2]
```diff
@@ -48,7 +48,7 @@ class Object;
 class MANTID_GEOMETRY_DLL GluGeometryHandler : public GeometryHandler {
   /// the type of the geometry eg CUBOID,CYLINDER,CONE,SPHERE
   enum GEOMETRY_TYPE {
-    CUBOID,            ///< CUBOID
+    CUBOID = 1,        ///< CUBOID
     HEXAHEDRON,        ///< HEXAHEDRON
```
Comment (quantumsteve) [inline Framework/Geometry/inc/MantidGeometry/Rendering/GluGeometryHandler.h]: Should we also have `NOSHAPE=0`?

File: Framework/Geometry/src/Rendering/GluGeometryHandler.cpp (hunk 1 above)
Comment (LamarMoore) [inline Framework/Geometry/src/Rendering/GluGeometryHandler.cpp]: L1209 in Object.cpp is using ```type == 3``` however, hexahedron is 2. Could you explain in a little more detail?

**Comment by LamarMoore** [comment]
I noticed there was no bounding box calculation for hexahedral types now I have made these changes. I created an issue [here](https://github.com/mantidproject/mantid/issues/16106) which depends on this merge.

**Comment by quantumsteve** [comment]
The issues I found earlier have been addressed satisfactorily. Good to see issues created for further improvements to these classes.

:shipit:
