### PR TITLE
Muon Analysis - Fix Global Parameter Reset Bug

### LINKED ISSUE #30054: Global updates in muon analysis
When doing a simultaneous fit in muon analysis (after a fit), updating one of the globals and then changing group will cause the parameter to reset. 

This might also occur in indirect. @robertapplin could you please check?

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR fixes a bug in Muon analysis where global parameters get reset after switching to a different display dataset.

**To test:**
2. Muon Analysis interface
1. `MUSR` run `62260`
2. Fitting tab. Click Simultaneous fit
3. Add `GausOsc` function
4. Make `Sigma` Global
5. Click `Fit` and wait (optional)
6. Change the visible dataset using `>>`
7. Change the Sigma parameter to a different value.
8. Change visible dataset using `>>` again. The Sigma parameter should have the value you just gave it.

Fixes #30054

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/widgets/common/src/FunctionModel.cpp [hunk 1]
```diff
@@ -401,7 +409,9 @@ QString FunctionModel::getLocalParameterConstraint(const QString &parName,
 
 void FunctionModel::setLocalParameterValue(const QString &parName, int i,
                                            double value) {
-  getSingleFunction(i)->setParameter(parName.toStdString(), value);
+  auto function = getSingleFunction(i);
+  if (function && function->hasParameter(parName.toStdString()))
```
Comment (StephenSmith25) [inline qt/widgets/common/src/FunctionModel.cpp:413]: There seems to be a small change in behavior I think?  It seems if we called `setParameter` with a typo, e.g `setParameter("Sigmaa", 1.00)` we'd fail silently now, whereas before we'd have got a `invalid_argument` error. 
Likewise if we called `setParameter` before initializing the function we'd have got a `logic_error("function is undefined")` now we'd get nothing.

Not entirely sure which situation was better, but was there a reason for this change?

File: qt/widgets/common/src/FunctionModel.cpp [hunk 2]
```diff
@@ -44,40 +44,50 @@ void FunctionModel::setFunction(IFunction_sptr fun) {
...
+  auto const singleFun = m_function->getFunction(index);
+  for (auto paramIter = m_globalParameterNames.begin();
+       paramIter != m_globalParameterNames.end();) {
+    if (singleFun->hasParameter(paramIter->toStdString())) {
+      QStringList ties;
+      for (auto i = 0u; i < m_function->nFunctions(); ++i)
+        if (i != index)
+          ties << "f" + QString::number(i) + "." + *paramIter;
+
+      ties << "f" + QString::number(index) + "." + *paramIter;
```
Comment (StephenSmith25) [inline qt/widgets/common/src/FunctionModel.cpp:83]: How come we have to add this last tie at the end, rather than constructing it within the loop? Is this to ensure the value for the parameter is equal to that defined in the currently selected function?

File: qt/widgets/common/src/FunctionModel.cpp [hunk 3]
```diff
@@ -44,40 +44,50 @@ void FunctionModel::setFunction(IFunction_sptr fun) {
...
-    auto fun = m_function->getFunction(0);
-    auto compFun = std::dynamic_pointer_cast<CompositeFunction>(fun);
-    if (compFun && compFun->nFunctions() == 1) {
-      return compFun->getFunction(0);
+  return IFunction_sptr();
+}
+
+IFunction_sptr
+FunctionModel::getFitFunctionWithGlobals(std::size_t const &index) const {
+  auto function =
```
Comment (StephenSmith25) [inline qt/widgets/common/src/FunctionModel.cpp:71]: I realise this was existing code, but I'm wondering why we to make a copy of the function here using ->clone(), whereas if it’s a composite function we just return a pointer to that exact function (and not a copy).

File: qt/widgets/common/inc/MantidQtWidgets/Common/FunctionModel.h [hunk 4]
```diff
@@ -61,6 +61,7 @@ class EXPORT_OPT_MANTIDQT_COMMON FunctionModel : public IFunctionModel {
                               double value) override;
   void setLocalParameterValue(const QString &parName, int i, double value,
                               double error) override;
+  void setGlobalParameterValue(const QString &paramName, double value);
```
Comment (StephenSmith25) [inline qt/widgets/common/inc/MantidQtWidgets/Common/FunctionModel.h:64]: I wonder whether this needs to be a public member of the class. Also, unlike almost every other method in this file, this isn't overriding a base class method. I think if `setLocalParameterValue` is part of the interface in the base class then `setGlobalParameterValue` should probably also be in the base class.

**Review by StephenSmith25 — COMMENTED** [review]
This works well and fixes the bug, nice job. Just a couple of questions

File: qt/widgets/common/src/FunctionModel.cpp (hunk 1 above)
Comment (robertapplin) [reply qt/widgets/common/src/FunctionModel.cpp:413]: My assumption here was that each domain could have a different fit function. So when looping through each domain in `setGlobalParameterValue`, which calls `setLocalParameterValue` on each domain, I didn't want it to fail if one of the domains had a different function. I am not sure if the `FunctionModel` allows different functions for each domain, but I thought it would be preferable to do it this way?

File: qt/widgets/common/src/FunctionModel.cpp (hunk 2 above)
Comment (robertapplin) [reply qt/widgets/common/src/FunctionModel.cpp:83]: That is a good question, and I didn't notice this as it was already here. I think the answer is yes. I assume the order in which the ties are applied matters if we want the global tie to be equal to the currently selected function.

File: qt/widgets/common/src/FunctionModel.cpp (hunk 3 above)
Comment (robertapplin) [reply qt/widgets/common/src/FunctionModel.cpp:71]: I think a copy is made because it adds ties to this function which it doesn't want to be stored in `m_function`. I am not sure why it returns a pointer if its a composite function. It would probably be better if a copy of the composite was returned, I'll make this change 👍

File: qt/widgets/common/inc/MantidQtWidgets/Common/FunctionModel.h (hunk 4 above)
Comment (robertapplin) [reply qt/widgets/common/inc/MantidQtWidgets/Common/FunctionModel.h:64]: Good point 👍

File: qt/widgets/common/src/FunctionModel.cpp (hunk 1 above)
Comment (StephenSmith25) [reply qt/widgets/common/src/FunctionModel.cpp:413]: Ah I see, that makes sense. But wouldn't that situation where we have globals, but a different fit function defined at one domain index fail when we call `getFitFunctionWithGlobals`. As there we get each global parameter and construct a tie. E.g if A0 was a global parameter we essentially do 

```
for k = 1:nFunctions
    ties << fk.A0
ties.join("=").
```
which would yield `f0.A0=f1.A0=f2.A0 ect...` but the 2nd function may not have the A0 parameter.

Let me know if I've understood something wrong here. But, I wonder whether it's worthwhile worrying about this situation, I'm not sure it would make sense to have a global parameter that is not present in one of the functions. I just think its more likely that the hasParameter check will cover up a geniune code error, rather than this protecting against this edge case.

Comment (robertapplin) [reply qt/widgets/common/src/FunctionModel.cpp:413]: Thats a good point, it should probably fail in that case. I'll change this back 👍

**Review by StephenSmith25 — COMMENTED** [review]
Okay now I need to apolgize, after making you remove the `hasParameter` check, in `setLocalParameter`, I realise I had missed that it already existed because of something I added for an IDA bug 🤦‍♂️  #28963 . You'll have to add it back in, sorry! For some reason the functions in the ConvFit tab can get out of sync.

**Comment by robertapplin** [comment]
@StephenSmith25 Thanks for spotting that, I've added it back in now

**Review by StephenSmith25 — APPROVED** [review]
Fixes the bug and code looks good, nice work.
