### PR TITLE
Fix crash when fitting tablews with column of type float

### LINKED ISSUE #26922: Fit property browser crashes when fitting tableworkspaces with type float
### Expected behavior
When you fit a table workspace with an x column of type float or int the fit property browser crashes. It works correctly for doubles.

### Actual behavior
It should do the fit and not crash

### Steps to reproduce the behavior
1) Load a table workspace with a x column of a number type that is not double.
2) Press the fit button
3) It crashes

### Platforms affected
All

### PR DESCRIPTION
**Pull request by alicerussell1**
**Description of work.**
This PR fixes a bug that when a table workspace contains numbers that aren't doubles the fit property browser crashes

**To test:**
1. Open a table workspace containing `floats` or `ints` or create one using the script below.
2. Plot the workspace
3. Open fit browser and add a suitable function 
4. Plot guess, `Display->Plot Guess`, this should plot a line (and not crash)
5. Fit the function, `Fit->Fit`, this should plot the calculated values and differences (and also not crash)
```
#creates an table workspace with a gaussian curve and a background 
import math

tableWS = CreateEmptyTableWorkspace()

tableWS.addColumn(type="float",name="X")
tableWS.addColumn(type="float",name="Y")
tableWS.addColumn(type="float",name="E")

for i in range(0,40):
      xValue = i * 0.05
      yValue = 10.0 * math.exp(-0.5*(xValue - 1.0)**2/0.05) + 2.0
      eValue = i%2*0.05
      tableWS.addRow ( { 'X': xValue, 'Y': yValue, 'E': eValue } )
```
Fixes #26922 

*This does not require release notes* because **it fixes a bug created during this release**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by NickDraper — DISMISSED** [review]
Works fine, problem solved
image

File: Framework/CurveFitting/src/TableWorkspaceDomainCreator.cpp [hunk 1]
```diff
@@ -212,13 +212,15 @@ void TableWorkspaceDomainCreator::createDomain(
     throw std::runtime_error("Workspace contains no data.");
   }
 
-  auto X = static_cast<DataObjects::TableColumn<double> &>(
-      *m_tableWorkspace->getColumn(m_xColName));
-  auto XData = X.data();
+  auto X = m_tableWorkspace->getColumn(m_xColName);
+  std::vector<double> XData;
```
Comment (martyngigg) [inline Framework/CurveFitting/src/TableWorkspaceDomainCreator.cpp]: I think it is worth calling `xData.reserve(m_tableWorkspace->rowCount())` here as we know the size and we can avoid repeated memory allocation. There are a few other places in the changes that would benefit from this too. 

Also a really minor point that the coding standards mean that this should be called `xData` and not `XData`...

**Review by martyngigg — CHANGES_REQUESTED** [review]

**Review by martyngigg — APPROVED** [review]
Thanks for making those changes. Looks good. :+1:
