### PR TITLE
Fix for crop workspace memory bug

### LINKED ISSUE #34735: Memory increase when Cropping workspace
**Original reporter:**
Pascal Manuel

**Describe the bug**
There is possibly a memory leak when using the CropWorkspace algorithm. The memory usage goes up after the workspace is cropped, but if anything you'd expect it to go down.

**To Reproduce**
1. `Load(Filename='SXD23767.raw', OutputWorkspace='SXD23767')`
2. Note the memory usage is 1.5 GB
3. Execute CropWorkspace with XMin=1000 and XMax=12000. Set the output name equal to the input name.
4. After it has run, note the memory usage is now 2.1 GB . Why has this gone up!
5. Delete the workspace and the memory usage returns to a normal level

**Expected behavior**
If anything, the memory usage should slightly decrease when cropping a workspace

**Platform/Version (please complete the following information):**
- Replicated in Mantid Version 6.5 on windows

### PR DESCRIPTION
**Pull request by jhaigh0**
Co-authored-by: thomashampson <thomas.hampson@stfc.ac.uk>
**Description of work.**

This PR fixes a bug in `ExtractSpectra` (called by CropWorkspace) which was increasing memory usage, under certain conditions, after cropping a workspace. In a typical `Workspace2D` with common bins (X data is the same in all histograms), there is only one copy of the X Histogram stored in memory. A pointer to this X Histogram is stored in each of the histograms in the workspace, saving significantly on memory.
	When `ExtractSpectra` was cropping a workspace in the X dimension, the workspace would lose this property as a new X Histogram was saved for every histogram in the workspace. This PR ensures that the cropped workspace is constructed in the same memory-saving way by only saving a pointer in each histogram to the new, cropped, X Histogram.

**To test:**

Run the example crop from the issue #34753

Check that the memory usage does not rise significantly as before.
(I have found that it now stays the same, not entirely sure why. Each Y and E histogram is replaced with one of a smaller size, so you'd assume that'd be less memory, but maybe something funny is going on behind the scenes.)

Check that the resulting data is as you'd expect it to be.

Fixes #34735 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Algorithms/src/ExtractSpectra.cpp [hunk 1]
```diff
@@ -61,6 +60,22 @@ std::map<std::string, std::string> ExtractSpectra::validateInputs() {
...
+    const int minSpec_i = getProperty("StartWorkspaceIndex");
+    auto minSpec = static_cast<size_t>(minSpec_i);
+    API::MatrixWorkspace_sptr ws = getProperty("InputWorkspace");
+    const size_t numberOfSpectra = ws->indexInfo().globalSize();
+    int maxSpec_i = getProperty("EndWorkspaceIndex");
+    auto maxSpec = static_cast<size_t>(maxSpec_i);
+    if (isEmpty(maxSpec_i))
+      maxSpec = numberOfSpectra - 1;
+    if (maxSpec < minSpec) {
+      helpMessages["StartWorkspaceIndex"] = "StartWorkspaceIndex must be less than or equal to EndWorkspaceIndex";
```
Comment (AnthonyLim23) [inline Framework/Algorithms/src/ExtractSpectra.cpp:74]: is it worth making this a warning and then swapping the indices?

File: Framework/Algorithms/src/ExtractSpectra.cpp [hunk 2]
```diff
@@ -156,6 +172,80 @@ void ExtractSpectra::execHistogram() {
   }
 }
 
+/** Returns a pointer to a cropped X Histrogram to be used as the X Histogram
+ *  for each of the spectra in the new cropped workspace
+ *  @param workspace :: The workspace from which to get the cropped X Histogram
```
Comment (AnthonyLim23) [inline Framework/Algorithms/src/ExtractSpectra.cpp:177]: missing return in doc string

File: Framework/Algorithms/src/ExtractSpectra.cpp [hunk 3]
```diff
@@ -156,6 +172,80 @@ void ExtractSpectra::execHistogram() {
...
+ */
+const Kernel::cow_ptr<Mantid::HistogramData::HistogramX>
+ExtractSpectra::getCroppedXHistogram(const API::MatrixWorkspace &workspace) {
+  const auto hist = workspace.histogram(0);
+  auto begin = m_minXIndex;
+  auto end = m_maxXIndex;
```
Comment (AnthonyLim23) [inline Framework/Algorithms/src/ExtractSpectra.cpp:183]: can make these conditional assignments, see https://www.tutorialspoint.com/cplusplus/cpp_conditional_operator.htm

Comment (AnthonyLim23) [reply Framework/Algorithms/src/ExtractSpectra.cpp:183]:
```suggestion
  auto end = (m_isHistogramData) ? m_maxXIndex-1 : m_maxXIndex;
```

File: Framework/Algorithms/src/ExtractSpectra.cpp [hunk 4]
```diff
@@ -156,6 +172,80 @@ void ExtractSpectra::execHistogram() {
...
+/** Crops the given workspace in accordance with m_minX and m_maxX
+ *  @param workspace :: The output workspace to crop
+ *  @param XHistogram :: Pointer to the cropped X Histogram to be used in the output workspace
+ *  @param index :: The workspace index of the spectrum
+ */
+void ExtractSpectra::cropCommon(API::MatrixWorkspace &workspace,
+                                Kernel::cow_ptr<Mantid::HistogramData::HistogramX> XHistogram, int index) {
+  const auto hist = workspace.histogram(index);
+  auto begin = m_minXIndex;
+  auto end = m_maxXIndex;
```
Comment (AnthonyLim23) [inline Framework/Algorithms/src/ExtractSpectra.cpp:205]: if we use this a lot, should we make it a function?

File: Framework/Algorithms/src/ExtractSpectra.cpp [hunk 5]
```diff
@@ -156,6 +172,80 @@ void ExtractSpectra::execHistogram() {
...
+  size_t startX = this->getXMinIndex(index);
+  if (startX > size)
+    startX = size;
+  for (size_t i = 0; i < startX; ++i) {
+    Y[i] = 0.0;
+    E[i] = 0.0;
+  }
+  size_t endX = this->getXMaxIndex(index);
+  if (endX > 0)
+    endX -= m_isHistogramData;
```
Comment (AnthonyLim23) [inline Framework/Algorithms/src/ExtractSpectra.cpp:242]: I thought this was a bool. Why are we subtracting it here?

File: Framework/Algorithms/test/CropWorkspaceTest.h [hunk 6]
```diff
@@ -383,9 +391,32 @@ class CropWorkspaceTest : public CxxTest::TestSuite {
...
+  // after CropWorkspace
+  void testCropDoesNotCopyXData() {
+    Workspace2D_sptr inputWS = WorkspaceCreationHelper::create2DWorkspace(10, 10);
 
-private:
-  CropWorkspace crop;
+    const auto in_x0_address = &inputWS->x(0);
+    const auto in_x2_address = &inputWS->x(2);
+
+    TS_ASSERT_EQUALS(in_x0_address, in_x2_address);
```
Comment (AnthonyLim23) [inline Framework/Algorithms/test/CropWorkspaceTest.h:402]:
```suggestion
    TS_ASSERT_EQUALS(&inputWS->x(0), &inputWS->x(2));
```

File: Framework/Algorithms/test/CropWorkspaceTest.h [hunk 7]
```diff
@@ -383,9 +391,32 @@ class CropWorkspaceTest : public CxxTest::TestSuite {
...
+    TS_ASSERT_THROWS_NOTHING(crop.setPropertyValue("OutputWorkspace", "outputWS"));
+    TS_ASSERT_THROWS_NOTHING(crop.setPropertyValue("XMin", "2"));
+    TS_ASSERT_THROWS_NOTHING(crop.setPropertyValue("XMax", "6"));
+    TS_ASSERT(crop.execute());
+
+    MatrixWorkspace_sptr outputWS;
+    TS_ASSERT_THROWS_NOTHING(outputWS = AnalysisDataService::Instance().retrieveWS<MatrixWorkspace>("outputWS"));
+
+    const auto out_x0_address = &outputWS->x(0);
+    const auto out_x2_address = &outputWS->x(2);
```
Comment (AnthonyLim23) [inline Framework/Algorithms/test/CropWorkspaceTest.h:416]: see above

File: Framework/Algorithms/test/ExtractSpectraTest.h [hunk 8]
```diff
@@ -158,6 +158,22 @@ class ExtractSpectraTest : public CxxTest::TestSuite {
...
 
+  void test_x_data_is_not_coppied() {
+    Parameters params;
+    params.XMin = 1;
+    params.XMax = 5;
+
+    const auto ws = runAlgorithm(params);
+
+    if (!ws)
+      return;
```
Comment (AnthonyLim23) [inline Framework/Algorithms/test/ExtractSpectraTest.h:169]: should this not raise a failure?

**Comment by AnthonyLim23** [comment]
I have removed myself as I am going to be on holiday and dont want to block this getting reviewed

File: Framework/Algorithms/src/ExtractSpectra.cpp (hunk 5 above)
Comment (jhaigh0) [reply Framework/Algorithms/src/ExtractSpectra.cpp:242]: Yes, so this is happening in quite a few places in this file (``cropRagged`` was an existing function which I've moved). I've not replicated it in my new code, but I can go through and remove the occurrences in the rest of the file 👍 I agree it's confusing to read, even though you can technically do it (bool is just treated as 0 or 1).

File: Framework/Algorithms/test/ExtractSpectraTest.h (hunk 8 above)
Comment (jhaigh0) [reply Framework/Algorithms/test/ExtractSpectraTest.h:169]: Good point, I think I was just copying other tests, but this is certainly somewhere where bugs could get hidden 👍

File: Framework/Algorithms/test/CropWorkspaceTest.h (hunk 6 above)
Comment (jhaigh0) [reply Framework/Algorithms/test/CropWorkspaceTest.h:402]: I like to explicitly name the variables here so that what is happening can be understood quickly without the need for a comment.

**Comment by jhaigh0** [comment]
> I have removed myself as I am going to be on holiday and dont want to block this getting reviewed

I may need some more detailed instructions on how to recreate this, I am unsure on what order and with what data things are done.

**Comment by AnthonyLim23** [comment]
I just used the data you sent me and did it in the algorithm dialog, copying the arguments from the script in the doc.

**Comment by jhaigh0** [comment]
I get the same error on `main`.

To confirm this is running `SANSILLReduction` with `066321.nxs` and default parameters.

 Tried to run the script in [the V1 doc](https://docs.mantidproject.org/v4.0.0/algorithms/SANSILLReduction-v1.html), but can't get it to find the first file (I've downloaded the usage data and pointed Mantid at it).

File: Framework/Algorithms/src/ExtractSpectra.cpp (hunk 1 above)
Comment (jhaigh0) [reply Framework/Algorithms/src/ExtractSpectra.cpp:74]: This is the behaviour that was present before, I've just moved it. I think raising this as an error is in line with what most Mantid algorithms do, so my opinion would be to keep it as is.

**Review by robertapplin — CHANGES_REQUESTED** [review]
Nice work, I just had a few suggestions/questions

File: Framework/Algorithms/src/ExtractSpectra.cpp [hunk 9]
```diff
@@ -156,6 +172,81 @@ void ExtractSpectra::execHistogram() {
...
+    Y[i] = 0.0;
+    E[i] = 0.0;
+  }
+  size_t endX = this->getXMaxIndex(index);
+  if (endX > 0 && m_isHistogramData)
+    endX -= 1;
+  for (size_t i = endX; i < size; ++i) {
+    Y[i] = 0.0;
+    E[i] = 0.0;
+  }
```
[the remark this answers is not in the document]
Comment (jhaigh0) [reply Framework/Algorithms/src/ExtractSpectra.cpp:247]: This is existing code that I've just changed the location of, so it wasn't right at the end of the file, so I think I'll leave it as is.

File: Framework/Algorithms/src/ExtractSpectra.cpp [hunk 10]
```diff
@@ -156,6 +172,81 @@ void ExtractSpectra::execHistogram() {
...
+  auto begin = m_minXIndex;
+  auto end = m_maxXIndex;
+  if (m_isHistogramData) {
+    end -= 1;
+  }
+
+  auto cropped(hist);
+  cropped.resize(end - begin);
+
+  auto xEnd = hist.xMode() == Histogram::XMode::Points ? end : end + 1;
```
[the remark this answers is not in the document]
Comment (jhaigh0) [reply Framework/Algorithms/src/ExtractSpectra.cpp:192]: Again this is copying what was done before but it looks to me like there's very little difference. This is the function which is called to set `m_isHistogramData`

```
bool MatrixWorkspace::isHistogramDataByIndex(const std::size_t index) const {
  bool isHist = (x(index).size() != y(index).size());

  // TODOHIST temporary sanity check
  if (isHist) {
    if (getSpectrum(index).histogram().xMode() != HistogramData::Histogram::XMode::BinEdges) {
      throw std::logic_error("In MatrixWorkspace::isHistogramData(): "
                             "Histogram::Xmode is not BinEdges");
    }
  } else {
    if (getSpectrum(index).histogram().xMode() != HistogramData::Histogram::XMode::Points) {
      throw std::logic_error("In MatrixWorkspace::isHistogramData(): "
                             "Histogram::Xmode is not Points");
    }
  }
  return isHist;
}
```

Which I'd say is fairly confusingly written, but I think it would be fine to replace `Histogram::XMode::Points` with `!m_isHistogramData` if you'd like.

File: Framework/Algorithms/src/ExtractSpectra.cpp [hunk 11]
```diff
@@ -226,7 +317,11 @@ void ExtractSpectra::execEvent() {
       const auto oldDx = el.pointStandardDeviations();
       el.setHistogram(binEdges);
       if (oldDx) {
-        el.setPointStandardDeviations(oldDx.begin() + m_minX, oldDx.begin() + (m_maxX - m_histogram));
+        auto end = m_maxXIndex;
+        if (m_isHistogramData) {
+          end -= 1;
+        }
```
[the remark this answers is not in the document]
Comment (jhaigh0) [reply Framework/Algorithms/src/ExtractSpectra.cpp:323]: Sure, I can add a function for it

File: Framework/Algorithms/src/ExtractSpectra.cpp (hunk 10 above)
[the remark this answers is not in the document]
Comment (robertapplin) [reply Framework/Algorithms/src/ExtractSpectra.cpp]: Thanks for the explanation. I think to avoid us introducing any problems by accident, lets keep it as is for now

**Review by robertapplin — APPROVED** [review]
Thanks for the changes, good job!
