### PR TITLE
ConvertUnitsUsingDetectorTable emode bug

### LINKED ISSUE #16935: ConvertUnitsUsingDetectorTable sets EMode on failed run
See #16794 

This algorithms has a lot of copy pasted code from convertunits and suffers from the same problem.

### PR DESCRIPTION
**Pull request by NickDraper**
## Important

This branch is formed from #16881, and contains those changes - it should not be merged until that one has been merged

**To test:**

Several validation checks were taking place after the output workspace had already been altered. for In place workspaces this meant the workspace was altered even though the algorithm failed.

The changes delay the creation of the output workspace and changes until all of the validation has passed.

To test:
1. All unit tests and system tests must pass
2. Including the new unit test that checks this

Fixes #16935.

RELEASE NOTES

Either edit the file in docs/source/release/ui.rst

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by NickDraper** [comment]
@stuartcampbell As the original author of this alg I though I'd give you a heads up in case you wanted to check this PR has not broken anything.

File: Framework/Algorithms/src/ConvertUnits.cpp [hunk 1]
```diff
@@ -333,7 +340,7 @@ ConvertUnits::convertQuickly(API::MatrixWorkspace_const_sptr inputWS,
 */
 bool ConvertUnits::getDetectorValues(
     const Kernel::Unit &outputUnit, const Geometry::IComponent &source,
-    const Geometry::IComponent &sample, double l1, int emode,
+    const Geometry::IComponent &sample, double &l1, int &emode,
```
Comment (SimonHeybrock) [inline Framework/Algorithms/src/ConvertUnits.cpp]: Why non-`const` reference? In any case, I would prefer passing things like `double` and `int` by value, after all an `int` is smaller than a pointer, and you avoid some pointer overhead.

File: Framework/Algorithms/src/ConvertUnitsUsingDetectorTable.cpp [hunk 2]
```diff
@@ -276,29 +120,52 @@ void ConvertUnitsUsingDetectorTable::convertViaTOF(
...
-  EventWorkspace_sptr eventWS =
-      boost::dynamic_pointer_cast<EventWorkspace>(outputWS);
-  assert(static_cast<bool>(eventWS) == m_inputEvents); // Sanity check
+  // Now let's take a reference to the vectors.
+  const auto &l1Column = paramWS->getColVector<double>("l1");
+  const auto &l2Column = paramWS->getColVector<double>("l2");
+  const auto &twoThetaColumn = paramWS->getColVector<double>("twotheta");
+  const auto &efixedColumn = paramWS->getColVector<double>("efixed");
+  const auto &emodeColumn = paramWS->getColVector<int>("emode");
+  auto &spectraColumn = paramWS->getColVector<int>("spectra");
```
Comment (SimonHeybrock) [inline Framework/Algorithms/src/ConvertUnitsUsingDetectorTable.cpp]: This does not seem to be modified (lucky for us, otherwise it would edit the table since we now have a reference), so it should be `const`, I think.

File: Framework/Algorithms/src/ConvertUnitsUsingDetectorTable.cpp [hunk 3]
```diff
@@ -276,29 +120,52 @@ void ConvertUnitsUsingDetectorTable::convertViaTOF(
...
 
   // Get the unit object for each workspace
-  Kernel::Unit_const_sptr outputUnit = outputWS->getAxis(0)->unit();
-
+  Kernel::Unit_const_sptr outputUnit = m_outputUnit;
   std::vector<double> emptyVec;
   int failedDetectorCount = 0;
 
-  // ConstColumnVector<int> spectraNumber = paramWS->getVector("spectra");
+  // Perform Sanity Validation before creating workspace
```
Comment (SimonHeybrock) [inline Framework/Algorithms/src/ConvertUnitsUsingDetectorTable.cpp]: @NickDraper Just for my understanding: I could not find an equivalent for the code block performing these checks in the old version, i.e., these are new checks you added?

File: Framework/Algorithms/src/ConvertUnitsUsingDetectorTable.cpp [hunk 4]
```diff
@@ -91,168 +80,23 @@ void ConvertUnitsUsingDetectorTable::init() {
                   "http://www.mantidproject.org/ConvertUnits).");
 }
```
Comment (SimonHeybrock) [inline Framework/Algorithms/src/ConvertUnitsUsingDetectorTable.cpp]: `ConvertUnits::init` uses some validators for `InputWorkspace`. Since `ConvertUnitsUsingDetectorTable` is basically doing the same thing, maybe it makes sense to also put the stricter validators here?

**Comment by SimonHeybrock** [comment]
@NickDraper This looks all good to me. According to my difftool `ConvertUnitsUsingDetectorTable` was identical to `ConvertUnits` apart from `ConvertViaTOF`, which is now the only remaining part in the former algorithm, i.e., a lot of duplicated code was removed 👍 .

After the minor comments have been fixed and @stuartcampbell gave his ok this is ready for shipping.

File: Framework/Algorithms/src/ConvertUnitsUsingDetectorTable.cpp (hunk 3 above)
Comment (NickDraper) [inline Framework/Algorithms/src/ConvertUnitsUsingDetectorTable.cpp]: The previous code had some checks but they are down in the heart of the ToTOF and FromTOF of the unit classes themselves.  As such they were the cause of the problem as they threw exceptions after the output workspaces had already been modified.  Here, as in ConvertUnits I perform a trial unit conversion of a single spectra (from the input workspace) before I create the output workspace, so any errors from the unit classes can fire safely.

A better design would be to separate this validation into a more explicit method, but it would still need pretty much the same inputs.  Given the Core nature of ConvertUnits, I went for the smaller change.

File: Framework/Algorithms/src/ConvertUnits.cpp (hunk 1 above)
Comment (NickDraper) [inline Framework/Algorithms/src/ConvertUnits.cpp]: This was a hang over from a an earlier refactoring attempt where I was hoping to only have the algorithms differ by implementations of getDetectorValues.  However it turned out to be more complex than that.

I'll revert this change.

**Comment by SimonHeybrock** [comment]
@NickDraper This branch has developed merge conflicts.
@stuartcampbell Did you have a look at this, can I put the ship-it?

**Comment by NickDraper** [comment]
This isn't going to make the release, moved to 3.9

**Comment by stuartcampbell** [comment]
@SimonHeybrock - Sorry for some reason I missed the notification on this - yes I would say that it can be shipped as this is basically a bug fix and I don't think we should ship knowingly buggy code :shipit:

**Comment by FedeMPouzols** [comment]
The branch has merge conflicts in 3 files apparently.

**Comment by stuartcampbell** [comment]
@NickDraper or @SimonHeybrock will one of you resolve the merge conflicts ? I think that you are in the best position to work them out.. :smile:

**Comment by SimonHeybrock** [comment]
@NickDraper I did the merge, but had some trouble afterwards. `ConvertUnitsUsingDetectorTableTest` passes now, but please have a close look to see if the merge went fine.

**Review by martyngigg — APPROVED** [review]
