### PR TITLE
MergeLogs proposition

### LINKED ISSUE #24006: MergeLogs segfaults, Mantid crashes
Since working on `SampleLogsBehaviour` which also merges time series sample logs, I quickly wanted to try the algorithm `MergeLogs` if sample log units are present (I doubt this). I did certainly do something unexpected but still **expect Mantid not to crash**! Maybe this algorithm can make use of `SampleLogsBehaviour`.

```
CreateWorkspace(OutputWorkspace='cw1', DataX='0,1,2,3,4', DataY='2,2,2,2')
AddSampleLog(Workspace='cw1', LogName='a', LogText='1', LogType='Number', LogUnit='Wavelength')
AddSampleLog(Workspace='cw1', LogName='b', LogText='1', LogType='Number', LogUnit='Wavelength')
AddSampleLog(Workspace='cw1', LogName='start_time', LogText='2018-11-30T16:17:01', LogUnit='s')

CreateWorkspace(OutputWorkspace='cw2', DataX='0,1,2,3,4', DataY='5,5,5,5')
AddSampleLog(Workspace='cw2', LogName='a', LogText='2', LogType='Number', LogUnit='Wavelength')
AddSampleLog(Workspace='cw2', LogName='start_time', LogText='2018-11-30T16:17:11', LogUnit='s')

MergeLogs-[Information] Algorithm: MergeLogs v1
MergeLogs-[Information]   Name: Workspace, Value: cw1, Default?: No, Direction: InOut
MergeLogs-[Information]   Name: LogName1, Value: a, Default?: No, Direction: Input
MergeLogs-[Information]   Name: LogName2, Value: b, Default?: No, Direction: Input
MergeLogs-[Information]   Name: MergedLogName, Value: a, Default?: No, Direction: Input
MergeLogs-[Information]   Name: ResetLogValue, Value: 0, Default?: Yes, Direction: Input
MergeLogs-[Information]   Name: LogValue1, Value: 0, Default?: Yes, Direction: Input
MergeLogs-[Information]   Name: LogValue2, Value: 1, Default?: Yes, Direction: Input
MergeLogs-[Debug] Write-locking cw1
MergeLogs-[Error] Property (log) a is not of class TimeSeriesProperty!

********* UNHANDLED EXCEPTION *********
Segmentation fault
```

### PR DESCRIPTION
**Pull request by vreimund**
**Description of work.**

I found out that the algorithm `MergeLogs` produces a segmentation fault when using it wrong.
After reading the implementation, I believed that it can be rewritten in a shorter and easier way.
I find the documentation poor but did not modify it.

Some points:
- it now belongs to `Algorithms` and not anymore to `DataHandling`
- mandatory input validation (new)
- validation, if time series properties (not new, but working)
- validation, if `MergedLogName` is unique (new)
- more tests (properties to be merged not modified, units, more options (replace values))

Please be aware that these changes modify the existing behavior. There is no documentation about it, but I now follow the `general Mantid way`. For example: observe the log values for the example in the documentation.

**To test:**

The documentation has an example.
Unit tests are present, where the workspaces are only designed to test time series sample logs (not data). 

Fixes #24006.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Algorithms/src/MergeLogs.cpp [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+        ws->run().getTimeSeriesProperty<double>(log2name);
+    TimeSeriesProperty<double> *mlog1 = log1->clone();
+    TimeSeriesProperty<double> *mlog2 = log2->clone();
+    mlog1->setName(mlogname);
+    mlog2->setName(mlogname);
+    if (resetlogvalue) {
+      const double logvalue1 = this->getProperty("LogValue1");
+      const double logvalue2 = this->getProperty("LogValue2");
+      std::vector<double> logvector1(mlog1->size(), logvalue1);
+      std::vector<double> logvector2(mlog2->size(), logvalue2);
```
Comment (soininen) [inline Framework/Algorithms/src/MergeLogs.cpp]: These vectors could be declared `const`

File: Framework/Algorithms/src/MergeLogs.cpp [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+      mlog1->replaceValues(log1->timesAsVector(), logvector1);
+      mlog2->replaceValues(log2->timesAsVector(), logvector2);
+    }
+    mlog1->merge(mlog2);
+    ws->mutableRun().addProperty(mlog1);
```
Comment (soininen) [inline Framework/Algorithms/src/MergeLogs.cpp]: What happens to `mlog2`? Are we leaking memory here? Perhaps it would be safer to make `mlog1` and `mlog2` `std::unique_ptr`s. `mlog1` should be moved to to the run object here:
```c++
ws->mutableRun().addProperty(std::move(mlog1));
```

`mlog2` would be deleted automatically at scope end.

File: Framework/Algorithms/src/RunCombinationHelpers/SampleLogsBehaviour.cpp [hunk 3]
```diff
@@ -419,7 +419,7 @@ bool SampleLogsBehaviour::setNumericValue(const std::string &item,
 void SampleLogsBehaviour::mergeSampleLogs(MatrixWorkspace_sptr addeeWS,
                                           MatrixWorkspace_sptr outWS) {
   for (const auto &item : m_logMap) {
-    std::string logName = item.first.first;
+    const std::string logName = item.first.first;
```
Comment (soininen) [inline Framework/Algorithms/src/RunCombinationHelpers/SampleLogsBehaviour.cpp]: Should this be a reference as well to avoid copying the string?

**Review by soininen — CHANGES_REQUESTED** [review]
Nice modernization of the `MergeLogs` algorithm. The segfault is now gone, too.

File: Framework/Algorithms/src/MergeLogs.cpp [hunk 4]
```diff
@@ -0,0 +1,78 @@
...
+
+namespace Mantid {
+namespace Algorithms {
+
+DECLARE_ALGORITHM(MergeLogs)
+
+void MergeLogs::init() {
+
+  declareProperty(make_unique<WorkspaceProperty<MatrixWorkspace>>(
+                      "Workspace", "Anonymous", Direction::InOut),
```
[the remark this answers is not in the document]
Comment (reimundILL) [reply Framework/Algorithms/src/MergeLogs.cpp]: As discussed, Direction `InOut` needs its workspaces in the ADS or a default name to be used to add the workspace to the ADS. Unit tests rely the default name. And we will not break any existing scripts when keeping the old interface.
```
ws = CreateSampleWorkspace()
AddTimeSeriesLog(ws, 'a', '2010-01-01T00:50:00', 1.)
AddTimeSeriesLog(ws, 'b', '2010-01-01T00:50:01', 2.)
mtd.remove('ws')
MergeLogs(ws, 'a', 'b', 'merge')
```

File: Framework/Algorithms/src/RunCombinationHelpers/SampleLogsBehaviour.cpp [hunk 5]
```diff
@@ -342,7 +342,7 @@ std::vector<double> SampleLogsBehaviour::createTolerancesVector(
 std::shared_ptr<Property> SampleLogsBehaviour::addPropertyForTimeSeries(
     const std::string &item, const double value, MatrixWorkspace &ws) {
   std::shared_ptr<Property> returnProp;
-  const std::string unit = ws.getLog(item)->units();
+  const std::string &unit = ws.getLog(item)->units();
```
Comment (soininen) [inline Framework/Algorithms/src/RunCombinationHelpers/SampleLogsBehaviour.cpp]: This change breaks the unit tests. The log unit is copied the `unit` as a backup here and restored at the end of this function. So the reference doesn't work here. Perhaps the variable could be renamed to `originalUnit` or similar to signify that the copy is really needed?

File: Framework/Algorithms/src/RunCombinationHelpers/SampleLogsBehaviour.cpp [hunk 6]
```diff
@@ -375,7 +375,7 @@ std::shared_ptr<Property> SampleLogsBehaviour::addPropertyForList(
     const std::string &item, const std::string &value, MatrixWorkspace &ws) {
   std::shared_ptr<Property> returnProp;
 
-  const std::string unit = ws.getLog(item)->units();
+  const std::string &unit = ws.getLog(item)->units();
```
Comment (soininen) [inline Framework/Algorithms/src/RunCombinationHelpers/SampleLogsBehaviour.cpp]: Here I think we have the same issue as above: `unit` is a backup and making it a reference breaks the intended behavior.

File: Framework/Algorithms/src/RunCombinationHelpers/SampleLogsBehaviour.cpp [hunk 7]
```diff
@@ -419,10 +419,10 @@ bool SampleLogsBehaviour::setNumericValue(const std::string &item,
 void SampleLogsBehaviour::mergeSampleLogs(MatrixWorkspace_sptr addeeWS,
                                           MatrixWorkspace_sptr outWS) {
   for (const auto &item : m_logMap) {
-    std::string logName = item.first.first;
+    const std::string &logName = item.first.first;
 
     Property *addeeWSProperty = addeeWS->getLog(logName);
-    const std::string logUnit = addeeWS->getLog(logName)->units();
+    const std::string &logUnit = addeeWS->getLog(logName)->units();
```
Comment (soininen) [inline Framework/Algorithms/src/RunCombinationHelpers/SampleLogsBehaviour.cpp]: I am afraid that here again `logUnit` is a backup and cannot be a reference.

**Review by soininen — CHANGES_REQUESTED** [review]

File: Framework/Algorithms/src/RunCombinationHelpers/SampleLogsBehaviour.cpp (hunk 5 above)
Comment (reimundILL) [reply Framework/Algorithms/src/RunCombinationHelpers/SampleLogsBehaviour.cpp]: That's quite obvious from the failing builds. I think a name change can prevent to think a reference could be possible. 👍

**Review by soininen — APPROVED** [review]
