### PR TITLE
Masking workspaces with grouped spectra

### LINKED ISSUE #16808: Mask detectors with loaded xml mask does not work on grouped workspaces.
Majority of workspaces on ISIS instruments come grouped into 4-1 groups where every spectra is related to 4 engineering detectors.

If you mask such workspace and SaveMask, the mask is saved as xml file, containing masked detectors id-s. 

When one loads such mask using LoadMask algorithm, the resulting mask workspace comes ungrouped, containing 4 times more spectra then the initial workspace with each spectra corresponding to a single detector. 

MaskDetectors algorithm than refuses to apply such mask workspace to the initial workspace, as number of spectra in the mask workspace and the initial workspace are different. 

As the result, ISIS direct inelastic group can not use xml masks and standard masking procedure.

Probably the easiest way to resolve this issue is to change MaskDetectors algorithm to analyse masks detector's id rather than number of spectra while applying mask workspace to another workspace.

### PR DESCRIPTION
**Pull request by abuts**
fixes #16808 which may be considered a bug or very peculiar feature as the code provided below does not work until you apply this ticket changes. See detailed description of the issue within the ticket. 

To allow masking source workspace with mask, obtained from reduced workspace (which usually have different spectra numbers) I had to change a bit the algorithm logic which is reflected in unit tests and modified algorithm description. 

**To test:**

Behaviour have changed and Documentation reflects that.  System tests should assure nothing wrong happened. I made some changes to system tests to address the bugs, which become apparent while making the changes. 

Load ISIS run or any run with grouped detectors or non-trivial spectra-detector map (e.g. ISIS MAP-s file from system tests would be good), open instrument, view Draw a mask, apply it to data and save it to xml file:
e.g.:

``` Python
Load(Filename=r'.../Datastore/DataCopies/Testing/Data/SystemTest/MAP17186.raw', OutputWorkspace='MAP17186')
# drowing mask on instrument have occurred here
# here are commands which extract this mask
ExtractMask(InputWorkspace='MAP17186', OutputWorkspace='__InstrumentActor_MaskWorkspace')
MaskDetectors(Workspace='MAP17186', MaskedWorkspace='__TMP0000021CE2A7F2D0')

#Save the mask from 'MAP17186' workspace to xml file using SaveMask algorithm
SaveMask(InputWorkspace='MAP17186',OutputFIle='MapsMask1.xml')
```

Load another MAPS workspace

``` Python
Load(Filename=r'.../Datastore/DataCopies/Testing/Data/SystemTest/MAP17269.raw', OutputWorkspace='MAP17269')

#Load saved mask
LoadMask(Instrument='MAP', InputFile='D:/Data/Mantid_Testing/2016/MapsMask1.xml',OutputWorkspace='Masking')
```

Note that number of spectra in the loaded mask is different from the the one loaded.

Mask the loaded workspace:
`MaskDetectors(Workspace='MAP17269', MaskedWorkspace='Masking')`

Before the changes, this would fail. After the changes, on instrument view you would see exactly the same masked area as on the initial masked workspace. 

Release notes modified accordingly. 

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [x] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/DataHandling/inc/MantidDataHandling/LoadMask.h [hunk 1]
```diff
@@ -139,22 +110,22 @@ class DLLExport LoadMask : public API::Algorithm {
 
   /// Default setup.  If true, not masking, but use the pixel
   bool m_defaultToUse;
+  /// input porperty contains name of instrument definition file rather then
```
Comment (soininen) [inline Framework/DataHandling/inc/MantidDataHandling/LoadMask.h]: then -> than

File: Framework/DataHandling/src/LoadMask.cpp [hunk 2]
```diff
@@ -39,6 +39,234 @@ using namespace Mantid::Kernel;
...
+*                   inclusively, with step 1
+* @param tot_singles -- on input contains range of single values already
+*                   copied into the result by previous call to the routine,
+*                   on output, all signles and expanded pairs
+*                   from the input are added to it.
+*/
+template <typename T>
+void convertToVector(const std::vector<T> &singles,
+                     const std::vector<T> &ranges,
+                     std::vector<T> &tot_signles) {
```
Comment (soininen) [inline Framework/DataHandling/src/LoadMask.cpp]: tot_signles -> tot_singles

File: Framework/DataHandling/src/LoadMask.cpp [hunk 3]
```diff
@@ -39,6 +39,234 @@ using namespace Mantid::Kernel;
...
+//-------------------------------------------------------------------------------------------
+/** Convert ranged vectors to single-valued vector
+* @param singles -- input vector of single numbers to copy to result without
+*                   changes.
+* @param ranges  -- input vector of data ranges -- pairs of min-max values,
+*                   expanded to result as numbers from min to max
+*                   inclusively, with step 1
+* @param tot_singles -- on input contains range of single values already
+*                   copied into the result by previous call to the routine,
+*                   on output, all signles and expanded pairs
```
Comment (soininen) [inline Framework/DataHandling/src/LoadMask.cpp]: signles -> singles

File: Framework/DataHandling/src/LoadMask.cpp [hunk 4]
```diff
@@ -39,6 +39,234 @@ using namespace Mantid::Kernel;
...
+  // for efficient memory operations
+  tot_signles.reserve(n_total);
+  // add singles to the existing singles
+  tot_signles.insert(tot_signles.end(), singles.begin(), singles.end());
+  // expand pairs
+  for (size_t i = 0; i < ranges.size(); i += 2) {
+    for (T obj_id = ranges[i]; obj_id < ranges[i + 1] + 1; ++obj_id) {
+      tot_signles.push_back(obj_id);
+    }
+  }
```
Comment (soininen) [inline Framework/DataHandling/src/LoadMask.cpp]: Just as a side note, this could have been done by `std::iota` as well although the for loop works well enough here.

File: Framework/DataHandling/src/LoadMask.cpp [hunk 5]
```diff
@@ -39,6 +39,234 @@ using namespace Mantid::Kernel;
...
+}
+
+/*
+* Parse index range text to singles and pairs
+* Example: 3,4,9-10,33
+*
+* @param inputstr -- input string to process in the format as above
+* @param sinvles -- vector of obects, defined as singles
```
Comment (soininen) [inline Framework/DataHandling/src/LoadMask.cpp]: sinvles -> singles

File: Framework/DataHandling/src/LoadMask.cpp [hunk 6]
```diff
@@ -39,6 +39,234 @@ using namespace Mantid::Kernel;
...
+* @param pairs   -- vector of obects, defined as pairs, in the form min,max
+*                   value
+*/
+template <typename T>
+void parseRangeText(const std::string &inputstr, std::vector<T> &singles,
+                    std::vector<T> &pairs) {
```
Comment (soininen) [inline Framework/DataHandling/src/LoadMask.cpp]: Did you consider using `Mantid::Kernel::UserStringParser`?

File: Framework/DataHandling/src/LoadMask.cpp [hunk 7]
```diff
@@ -39,6 +39,234 @@ using namespace Mantid::Kernel;
...
+      T itemp = boost::lexical_cast<T>(rawstring);
+      singles.push_back(itemp);
+    }
+  } // ENDFOR i
+}
+
+/*
+* Parse a line in an ISIS mask file string to vector
+* Combination of 5 types of format for unit
+* (1) a (2) a-b (3) a - b (4) a- b (5) a- b
```
Comment (soininen) [inline Framework/DataHandling/src/LoadMask.cpp]: What is the difference between (4) and (5)? Typo?

File: Framework/DataHandling/src/LoadMask.cpp [hunk 8]
```diff
@@ -39,6 +39,234 @@ using namespace Mantid::Kernel;
...
+      splitstrings.erase(splitstrings.begin() + index);
+      for (size_t ic = 0; ic < 3; ic++) {
+        if (temps[ic].size() > 0) {
+          splitstrings.insert(splitstrings.begin() + index, temps[ic]);
+          index++;
+        }
+      }
+    } else {
+      // Exception
+      std::string err = "String " + splitstrings[index] + " has Too many '-'";
```
Comment (soininen) [inline Framework/DataHandling/src/LoadMask.cpp]: Too -> too

File: Framework/DataHandling/src/LoadMask.cpp [hunk 9]
```diff
@@ -39,6 +39,234 @@ using namespace Mantid::Kernel;
...
+                 boost::token_compress_on);
+    if (splitstrings[index].compare("-") == 0 || temps.size() == 1) {
+      // Nothing to split
+      index++;
+    } else if (temps.size() == 2) {
+      // Has a '-' inside.  Delete and Replace
+      temps.insert(temps.begin() + 1, "-");
+      splitstrings.erase(splitstrings.begin() + index);
+      for (size_t ic = 0; ic < 3; ic++) {
+        if (temps[ic].size() > 0) {
```
Comment (soininen) [inline Framework/DataHandling/src/LoadMask.cpp]: Just for future reference, there is also the `empty()` method in `std::vector`.

File: Framework/DataHandling/src/LoadMask.cpp [hunk 10]
```diff
@@ -39,6 +39,234 @@ using namespace Mantid::Kernel;
...
+          boost::lexical_cast<Mantid::specnum_t>(splitstrings[index + 2]));
+      index += 3;
+    }
+
+    if (index >= splitstrings.size())
+      tocontinue = false;
+  } // END-WHILE
+
+  splitstrings.clear();
+}
```
Comment (soininen) [inline Framework/DataHandling/src/LoadMask.cpp]: Is `clear()` necessary? I would think `splitstrings` will anyway die an all-clearing death on the next line.

File: Framework/DataHandling/src/LoadMask.cpp (hunk 7 above)
Comment (abuts) [inline Framework/DataHandling/src/LoadMask.cpp]: should be a -b

File: Framework/DataHandling/src/LoadMask.cpp (hunk 9 above)
Comment (abuts) [inline Framework/DataHandling/src/LoadMask.cpp]: not sure empty is suitable here -- you probably always have data in a string. Left as it was as its not my code.

File: Framework/DataHandling/src/LoadMask.cpp (hunk 10 above)
Comment (abuts) [inline Framework/DataHandling/src/LoadMask.cpp]: removed

File: Framework/DataHandling/src/LoadMask.cpp (hunk 9 above)
Comment (soininen) [inline Framework/DataHandling/src/LoadMask.cpp]: I meant to say there is `empty()` method in `std::string`, but yeah, it is not a biggie here.

File: Framework/DataHandling/src/LoadMask.cpp (hunk 6 above)
Comment (abuts) [inline Framework/DataHandling/src/LoadMask.cpp]: Again, took whatever was there, the purpose of this ticket barely touches loadMask

If you think it is important, it worth separate ticket. Such changes are not entirely trivial and muddle the changes, related to the ticket purpose.

File: Framework/DataHandling/src/LoadMask.cpp [hunk 11]
```diff
@@ -39,6 +39,232 @@ using namespace Mantid::Kernel;
...
+  // expand pairs
+  for (size_t i = 0; i < ranges.size(); i += 2) {
+    for (T obj_id = ranges[i]; obj_id < ranges[i + 1] + 1; ++obj_id) {
+      tot_singles.push_back(obj_id);
+    }
+  }
+}
+
+/*
+* Parse index range text to singles and pairs
```
Comment (soininen) [inline Framework/DataHandling/src/LoadMask.cpp]: Are these supposed to be doxygen comments? Should they not start with `/**` instead of `/*` to be recognized as such?

File: Framework/DataHandling/src/LoadMask.cpp [hunk 12]
```diff
@@ -39,6 +39,232 @@ using namespace Mantid::Kernel;
...
+@param isisfilename :: the string containing full path to an ISIS mask file
+@param SpectraMasks :: output list of the spectra numbers to mask.
+*/
+void loadISISMaskFile(const std::string &isisfilename,
+                      std::vector<Mantid::specnum_t> &spectraMasks) {
+
+  std::vector<Mantid::specnum_t> ranges;
+
+  std::ifstream ifs;
+  ifs.open(isisfilename.c_str(), std::ios::in);
```
Comment (soininen) [inline Framework/DataHandling/src/LoadMask.cpp]: Just for future reference, `open() in `std::ifstream` accepts `string`s directly as of C++11.

File: Framework/DataHandling/src/LoadMask.cpp [hunk 13]
```diff
@@ -39,6 +39,232 @@ using namespace Mantid::Kernel;
...
+  if (!ifs.is_open()) {
+    throw std::invalid_argument("Cannot open ISIS mask file" + isisfilename);
+  }
+
+  std::string isisline;
+  while (getline(ifs, isisline)) {
+    boost::trim(isisline);
+
+    // a. skip empty line
+    if (isisline.size() == 0)
```
Comment (soininen) [inline Framework/DataHandling/src/LoadMask.cpp]: There is 'empty()' in 'string'.

File: Framework/DataHandling/src/LoadMask.cpp [hunk 14]
```diff
@@ -39,6 +39,232 @@ using namespace Mantid::Kernel;
...
+      continue;
+
+    // b. skip comment line
+    if (isisline.c_str()[0] < '0' || isisline.c_str()[0] > '9')
```
Comment (soininen) [inline Framework/DataHandling/src/LoadMask.cpp]: Why not use `isisline[0] < '0'`? Or even `isisline.front() < '0'`?

File: Framework/DataHandling/src/LoadMask.cpp [hunk 15]
```diff
@@ -39,6 +39,232 @@ using namespace Mantid::Kernel;
...
+      continue;
+
+    // c. parse
+    parseISISStringToVector(isisline, ranges);
+  }
+  ifs.close();
```
Comment (soininen) [inline Framework/DataHandling/src/LoadMask.cpp]: Is this necessary? I think the input stream will close automagically when the function exits and the object is destroyed.

File: Framework/DataHandling/src/LoadMask.cpp [hunk 16]
```diff
@@ -83,7 +309,7 @@ void LoadMask::init() {
   declareProperty(
       Kernel::make_unique<WorkspaceProperty<API::MatrixWorkspace>>(
           "RefWorkspace", "", Direction::Input, PropertyMode::Optional),
-      "The name of the workspace with defines insrtument and spectra, "
+      "The name of the workspace with defines instrument and spectra, "
```
Comment (soininen) [inline Framework/DataHandling/src/LoadMask.cpp]: with -> which?

File: Framework/DataHandling/inc/MantidDataHandling/LoadMask.h [hunk 17]
```diff
@@ -139,22 +110,22 @@ class DLLExport LoadMask : public API::Algorithm {
...
+  // spectrum id-s to unmask
+  std::vector<detid_t> m_unMaskDetID;
 
   // spectra mask provided
-  std::vector<int32_t> m_MaskSpecID;
-  // spectra unmask provided
-  std::vector<int32_t> m_unMaskSpecID;
+  std::vector<specnum_t> m_maskSpecID;
+  // spectra unmask provided NOT IMPLEMENTED
+  // std::vector<specnum_t> m_unMaskSpecID;
```
Comment (soininen) [inline Framework/DataHandling/inc/MantidDataHandling/LoadMask.h]: There seems to be a bit of commented-out code regarding unmasking. Are there plans to implement this functionality?

File: Framework/DataHandling/src/LoadMask.cpp [hunk 18]
```diff
@@ -179,14 +404,11 @@ void LoadMask::initDetectors() {
  *                   in masking
  *   @param tomask:  true to mask, false to unmask
  *   @param singledetids: list of individual det ids to mask
- *   @param pairdetids_low: list of lower bound of det ids to mask
- *   @param pairdetids_up: list of upper bound of det ids to mask
+
```
Comment (soininen) [inline Framework/DataHandling/src/LoadMask.cpp]: Spurious empty line?

File: Framework/DataHandling/src/LoadMask.cpp [hunk 19]
```diff
@@ -179,14 +404,11 @@ void LoadMask::initDetectors() {
...
  */
 void LoadMask::processMaskOnDetectors(const detid2index_map &indexmap,
                                       bool tomask,
-                                      std::vector<int32_t> singledetids,
-                                      std::vector<int32_t> pairdetids_low,
-                                      std::vector<int32_t> pairdetids_up) {
+                                      std::vector<int32_t> singledetids) {
```
Comment (soininen) [inline Framework/DataHandling/src/LoadMask.cpp]: I might be blind to the bigger picture here, but why not pass `singledetids` as reference?

File: Framework/DataHandling/src/LoadMask.cpp [hunk 20]
```diff
@@ -202,26 +424,22 @@ void LoadMask::processMaskOnDetectors(const detid2index_map &indexmap,
...
 }
 
 //----------------------------------------------------------------------------------------------
-/** Convert a component to detectors.  It is a generalized version of
- * bankToDetectors()
+/** Extract a component's detectors and return it within detectors array
+ *  It is a generalized version of bankToDetectors()
+ *
+ * @param componentnames -- vector of components names to process
+ * @param detectors      -- vector of detectors id, which belongs to components
```
Comment (soininen) [inline Framework/DataHandling/src/LoadMask.cpp]: components names -> component names?
detectors id -> detector ids

File: Framework/DataHandling/src/LoadMask.cpp [hunk 21]
```diff
@@ -246,17 +464,17 @@ void LoadMask::componentToDetectors(
 
     g_log.debug() << "Number of Children = " << children.size() << '\n';
 
-    int32_t numdets = 0;
-    int32_t id_min = 1000000;
-    int32_t id_max = 0;
+    size_t numdets(0);
+    detid_t id_min = std::numeric_limits<Mantid::detid_t>::max();
+    detid_t id_max = 0;
```
Comment (soininen) [inline Framework/DataHandling/src/LoadMask.cpp]: I wonder why mix the `numdets(0)` type initialization with the assignment style initialization. Shouldn't one choose a single style and stick to it?

File: Framework/DataHandling/src/LoadMask.cpp [hunk 22]
```diff
@@ -273,11 +491,12 @@ void LoadMask::componentToDetectors(
 
 //----------------------------------------------------------------------------------------------
 /** Convert bank to detectors
+* This routine have never been invoked.
```
Comment (soininen) [inline Framework/DataHandling/src/LoadMask.cpp]: have -> has?
Never been invoked?

File: Framework/DataHandling/src/LoadMask.cpp [hunk 23]
```diff
@@ -300,24 +519,16 @@ void LoadMask::bankToDetectors(const std::vector<std::string> &singlebanks,
...
-      g_log.debug() << "Apply 1 by 1  "
-                    << "DetID: " << detid_first << ", " << detid_last << '\n';
 
-      for (const auto &det : idetectors) {
-        int32_t detid = det->getID();
-        detectors.push_back(detid);
-      }
+    for (const auto &det : idetectors) {
+      int32_t detid = det->getID();
+      detectors.push_back(detid);
```
Comment (soininen) [inline Framework/DataHandling/src/LoadMask.cpp]: Not that it matters here, but I guess one should generally prefer `emplace_back` over `push_back`.

File: Framework/DataHandling/src/LoadMask.cpp [hunk 24]
```diff
@@ -473,375 +674,68 @@ void LoadMask::parseXML() {
...
     } else if (pNode->nodeName().compare("component") == 0) {
       // Node "component"
       if (ingroup) {
-        this->parseComponent(value, tomask);
+        parseComponent(value, tomask, m_maskCompIdSingle, m_uMaskCompIdSingle);
       } else {
-        g_log.error() << "XML File heirachial (component) error!\n";
+        g_log.error() << "XML File hierarchical (component) error!\n";
       }
       // g_log.information() << "Component: " << value << '\n';
```
Comment (soininen) [inline Framework/DataHandling/src/LoadMask.cpp]: Commented out code.

File: Framework/DataHandling/src/LoadMask.cpp [hunk 25]
```diff
@@ -473,375 +674,68 @@ void LoadMask::parseXML() {
...
-    if (index >= splitstrings.size())
-      tocontinue = false;
-  } // END-WHILE
-
-  splitstrings.clear();
-}
 /* Convert spectra mask into det-id mask using workspace as source of
 *spectra-detector maps
 *
 * @param sourceWS       -- the workspace containing source spectra-detecot map
```
Comment (soininen) [inline Framework/DataHandling/src/LoadMask.cpp]: detecot -> detector

File: Framework/DataHandling/src/LoadMask.cpp [hunk 26]
```diff
@@ -473,375 +674,68 @@ void LoadMask::parseXML() {
...
-*to use on masks
+*                          to use on masks
 * @param maskedSpecID   -- vector of spectra id to mask
 * @param singleDetIds   -- output vector of detectors id to mask
```
Comment (soininen) [inline Framework/DataHandling/src/LoadMask.cpp]: detectors id -> detector ids

File: Framework/DataHandling/src/MaskDetectors.cpp [hunk 27]
```diff
@@ -8,7 +8,30 @@
 
 #include "MantidKernel/ArrayProperty.h"
 #include "MantidKernel/BoundedValidator.h"
+#include "MantidKernel/EnabledWhenProperty.h"
 #include <set>
+#include <numeric>
+
+namespace { // declare file scoped function
+/* internal method copies values in specified range from source list to the
```
Comment (soininen) [inline Framework/DataHandling/src/MaskDetectors.cpp]: For doxygen comments, please use `/**` instead of `/*`.

File: Framework/DataHandling/src/MaskDetectors.cpp [hunk 28]
```diff
@@ -8,7 +8,30 @@
...
+@param targetList :: vector of output values
+@param minIndex   :: min value to include in the list of output values
+@param maxIndex   :: max value to include in the list of output values
+*/
+void constrainIndexInRange(std::vector<size_t> &sourceList,
+                           std::vector<size_t> &targetList, size_t minIndex,
+                           size_t maxIndex) {
+  targetList.reserve(sourceList.size());
+  std::sort(sourceList.begin(), sourceList.end());
+  for (auto it = sourceList.begin(); it != sourceList.end(); it++) {
```
Comment (soininen) [inline Framework/DataHandling/src/MaskDetectors.cpp]: Why not use the new-style for loop here? Or even `std::copy_if`?

File: Framework/DataHandling/src/MaskDetectors.cpp [hunk 29]
```diff
@@ -45,17 +68,32 @@ void MaskDetectors::init() {
...
-                  "The index of the first workspace index of input "
-                  "MaskedWorkspace to be included in the calculation. Default "
-                  "is 0.");
-  declareProperty("EndWorkspaceIndex", EMPTY_INT(), mustBePosInt,
-                  "The index number of the last workspace index of input "
-                  "MaskedWorkspace to be included in the calculation. Default "
-                  "is the last histogram.");
+  declareProperty(
+      "StartWorkspaceIndex", 0, mustBePosInt,
+      "If other masks fields are provided, its the first index of the "
```
Comment (soininen) [inline Framework/DataHandling/src/MaskDetectors.cpp]: its -> it's?

File: Framework/DataHandling/src/MaskDetectors.cpp [hunk 30]
```diff
@@ -45,17 +68,32 @@ void MaskDetectors::init() {
...
+      "target workspace to be allowed to be masked from by these masks, "
+      "if not, its the first index of the target workspace to mask.\n"
```
Comment (soininen) [inline Framework/DataHandling/src/MaskDetectors.cpp]: its -> it's?

File: Framework/DataHandling/inc/MantidDataHandling/MaskDetectors.h [hunk 31]
```diff
@@ -80,14 +80,28 @@ class DLLExport MaskDetectors : public API::Algorithm {
...
-  void fillIndexListFromSpectra(std::vector<size_t> &indexList,
-                                const std::vector<specnum_t> &spectraList,
-                                const API::MatrixWorkspace_sptr WS);
-  void appendToIndexListFromWS(std::vector<size_t> &indexList,
-                               const API::MatrixWorkspace_sptr maskedWorkspace);
+  void
+  fillIndexListFromSpectra(std::vector<size_t> &indexList,
+                           const std::vector<specnum_t> &spectraList,
+                           const API::MatrixWorkspace_sptr WS,
+                           const std::tuple<size_t, size_t, bool> &range_info);
```
Comment (soininen) [inline Framework/DataHandling/inc/MantidDataHandling/MaskDetectors.h]: `std::tuple` is an interesting choice here. Why not use a plain old struct instead? IMHO, it is easier to read
```
range_info.min = 0;
```
than
```
std::get<0>(range_info) = 0;
```
no?

File: Framework/DataHandling/src/MaskDetectors.cpp [hunk 32]
```diff
@@ -191,10 +239,92 @@ void MaskDetectors::exec() {
...
+std::tuple<size_t, size_t, bool>
+MaskDetectors::getRanges(const MatrixWorkspace_sptr &targWS) {
+  int endIndex = getProperty("EndWorkspaceIndex");
+  int startIndex = getProperty("StartWorkspaceIndex");
+  size_t max_ind = targWS->getNumberHistograms() - 1;
+
+  if (endIndex == EMPTY_INT() && startIndex == 0) {
+    return std::tuple<size_t, size_t, bool>(0, max_ind, false);
+  } else {
+    if (startIndex < 0) {
```
Comment (soininen) [inline Framework/DataHandling/src/MaskDetectors.cpp]: *StartWorkspaceIndex* (and *EndWorkspaceIndex*) property has the requirement of being positive by the `mustBePosInt` validator so this check is not necessarily needed.

File: Framework/DataHandling/src/MaskDetectors.cpp [hunk 33]
```diff
@@ -191,10 +239,92 @@ void MaskDetectors::exec() {
...
+      startIndex = 0;
+    }
+    size_t startIndex_l = static_cast<size_t>(startIndex);
+    size_t endIndex_l = static_cast<size_t>(endIndex);
+
+    if (endIndex == EMPTY_INT()) {
+      endIndex_l = max_ind;
+    }
+    if (endIndex_l > max_ind) {
```
Comment (soininen) [inline Framework/DataHandling/src/MaskDetectors.cpp]: Why not combine this with the test above?

File: Framework/DataHandling/src/MaskDetectors.cpp [hunk 34]
```diff
@@ -191,10 +239,92 @@ void MaskDetectors::exec() {
...
+      endIndex_l = max_ind;
+    }
+    if (startIndex_l > endIndex_l) {
+      startIndex_l = endIndex_l;
+    }
```
Comment (soininen) [inline Framework/DataHandling/src/MaskDetectors.cpp]: The shorthand for this would be
```
startIndex_1 = std::min(startIndex_1, endIndex_1);
```
but the `if` statement here is perhaps more readable.

File: Framework/DataHandling/src/MaskDetectors.cpp [hunk 35]
```diff
@@ -191,10 +239,92 @@ void MaskDetectors::exec() {
...
+
+    return std::tuple<size_t, size_t, bool>(startIndex_l, endIndex_l, true);
+  }
+}
+/* Constrain masked indexes by limits, provided as input
+* @param indexList  :: list of indexes to verify against constrain on input
```
Comment (soininen) [inline Framework/DataHandling/src/MaskDetectors.cpp]: constrain -> constrains?

File: Framework/DataHandling/src/MaskDetectors.cpp [hunk 36]
```diff
@@ -191,10 +239,92 @@ void MaskDetectors::exec() {
...
+*                      and list of constrained indexes on the output.
+* @param startIndex :: minimal index (inclusive) to include in the constrained
+* list.
+* @param endIndex   :: maximal index (inclusive) to include in the constrained
+* list
```
Comment (soininen) [inline Framework/DataHandling/src/MaskDetectors.cpp]: Missing '.'

File: Framework/DataHandling/src/MaskDetectors.cpp [hunk 37]
```diff
@@ -191,10 +239,92 @@ void MaskDetectors::exec() {
...
+    std::vector<size_t> &indexList,
+    const std::tuple<size_t, size_t, bool> &range_info) {
+
+  std::vector<size_t> tmp;
+  constrainIndexInRange(indexList, tmp, std::get<0>(range_info),
+                        std::get<1>(range_info));
+  tmp.swap(indexList);
+}
+
+/* Method to extract detector's id-s from mask workspace
```
Comment (soininen) [inline Framework/DataHandling/src/MaskDetectors.cpp]: detector's id-s -> detector id-s?

File: Framework/DataHandling/src/MaskDetectors.cpp [hunk 38]
```diff
@@ -191,10 +239,92 @@ void MaskDetectors::exec() {
...
+
+  int64_t nHist = maskWS->getNumberHistograms();
+  for (int64_t i = 0; i < nHist; ++i) {
+    if (maskWS->readY(i)[0] > 0.5) {
+
+      try {
+        const auto dets = maskWS->getSpectrum(i).getDetectorIDs();
+        for (auto det : dets) {
+          detectorList.push_back(det);
+        }
```
Comment (soininen) [inline Framework/DataHandling/src/MaskDetectors.cpp]: Just for the record, there is also
```
detectorList.insert(detectorList.end(), dets.begin(), dets.end());
```

File: Framework/DataHandling/src/MaskDetectors.cpp [hunk 39]
```diff
@@ -269,83 +399,143 @@ void MaskDetectors::execPeaks(PeaksWorkspace_sptr WS) {
...
+
+  std::vector<size_t> tmp_index;
+  size_t startIndex = std::get<0>(range_info);
+  size_t endIndex = std::get<1>(range_info);
+  bool range_constrained = std::get<2>(range_info);
+
+  if (range_constrained) {
+    constrainIndexInRange(indexList, tmp_index, startIndex, endIndex);
+  } else {
+    tmp_index.swap(indexList);
```
Comment (soininen) [inline Framework/DataHandling/src/MaskDetectors.cpp]: Why swap? Wouldn't
```
tmp_index.assign(indexList.cbegin(), indexList.cend());
```
make more sense?

File: Framework/DataHandling/src/MaskDetectors.cpp [hunk 40]
```diff
@@ -269,83 +399,143 @@ void MaskDetectors::execPeaks(PeaksWorkspace_sptr WS) {
...
+    }
+    size_t ws_index = element->second;
+
+    if (range_constrained && (ws_index < startIndex || ws_index > endIndex)) {
+      continue;
     }
+    tmp_index.push_back(ws_index);
   }
+
+  tmp_index.swap(indexList);
```
Comment (soininen) [inline Framework/DataHandling/src/MaskDetectors.cpp]: Why not use `tmp_index.assing()` here as well?

File: Framework/DataHandling/src/MaskDetectors.cpp [hunk 41]
```diff
@@ -269,83 +399,143 @@ void MaskDetectors::execPeaks(PeaksWorkspace_sptr WS) {
...
 void MaskDetectors::appendToIndexListFromWS(
-    std::vector<size_t> &indexList,
-    const MatrixWorkspace_sptr maskedWorkspace) {
-  // Convert the vector of properties into a set for easy searching
-  std::set<int64_t> existingIndices(indexList.begin(), indexList.end());
-  int endIndex = getProperty("EndWorkspaceIndex");
-  if (endIndex == EMPTY_INT())
-    endIndex = static_cast<int>(maskedWorkspace->getNumberHistograms() - 1);
-  int startIndex = getProperty("StartWorkspaceIndex");
+    std::vector<size_t> &indexList, const MatrixWorkspace_sptr sourceWS,
```
Comment (soininen) [inline Framework/DataHandling/src/MaskDetectors.cpp]: `const MatrixWorkspace_sptr` -> `MatrixWorkspace_const_sptr`?

File: Framework/DataHandling/src/MaskDetectors.cpp [hunk 42]
```diff
@@ -269,83 +399,143 @@ void MaskDetectors::execPeaks(PeaksWorkspace_sptr WS) {
...
+        det = sourceWS->getDetector(i);
+      } catch (Exception::NotFoundError &) {
+        continue;
+      }
+      if (det->isMasked()) {
+        tmp_index.push_back(i);
+      }
     }
   }
+  tmp_index.swap(indexList);
```
Comment (soininen) [inline Framework/DataHandling/src/MaskDetectors.cpp]: Also here swapping is not necessary, I'd use `assign` instead.

File: Framework/DataHandling/src/MaskDetectors.cpp [hunk 43]
```diff
@@ -269,83 +399,143 @@ void MaskDetectors::execPeaks(PeaksWorkspace_sptr WS) {
...
+
+  return;
```
Comment (soininen) [inline Framework/DataHandling/src/MaskDetectors.cpp]: Superfluous `return`.

File: Framework/DataHandling/src/MaskDetectors.cpp [hunk 44]
```diff
@@ -269,83 +399,143 @@ void MaskDetectors::execPeaks(PeaksWorkspace_sptr WS) {
...
+    for (size_t i = 0; i < endIndex; ++i) {
+
+      if (maskedWorkspace->dataY(i)[0] > 0.5) {
+        g_log.debug() << "Adding WorkspaceIndex " << i << " to mask.\n";
+        tmp_index.push_back(i);
+      }
     }
   }
+  tmp_index.swap(indexList);
+  return;
```
Comment (soininen) [inline Framework/DataHandling/src/MaskDetectors.cpp]: Ditto here for `swap` and `return`.

File: docs/source/algorithms/MaskDetectors-v1.rst [hunk 45]
```diff
@@ -6,35 +6,99 @@
 
 .. properties::
 
+Introduction
+------------
+
+To understand the algorithms options, user should clearly understand the difference between *WorkspaceIndex* 
+-- the numbers, specified in *WorkspaceIndexList* and *StartWorkspacIndex*, *EndWorkspaceIndex* properties,
+the *Spectra ID* -- values of the **SpectraList** property and *Detector ID* -- the numbers to provide for
```
Comment (soininen) [inline docs/source/algorithms/MaskDetectors-v1.rst]: Is *Spectra ID* actually known more generally as *spectum number*?

File: docs/source/algorithms/MaskDetectors-v1.rst [hunk 46]
```diff
@@ -6,35 +6,99 @@
...
 
+Introduction
+------------
+
+To understand the algorithms options, user should clearly understand the difference between *WorkspaceIndex* 
+-- the numbers, specified in *WorkspaceIndexList* and *StartWorkspacIndex*, *EndWorkspaceIndex* properties,
+the *Spectra ID* -- values of the **SpectraList** property and *Detector ID* -- the numbers to provide for 
+*DetectorList* property.
+
+The *WorkspaceIndex* is the number a spectra has in a workspace, e.g. ::
```
Comment (soininen) [inline docs/source/algorithms/MaskDetectors-v1.rst]: ...and here I would phrase this as 'The *WorkspaceIndex is the index of a spectrum in a workspace'.
Anyway, spectra -> spectrum.

File: docs/source/algorithms/MaskDetectors-v1.rst [hunk 47]
```diff
@@ -6,35 +6,99 @@
...
+
+  sp = ws.getSpectrum(0) 
+
+always returns first spectra present in the workspace.
```
Comment (soininen) [inline docs/source/algorithms/MaskDetectors-v1.rst]: spectra -> spectrum. I guess there are more such typos.

File: docs/source/algorithms/MaskDetectors-v1.rst [hunk 48]
```diff
@@ -6,35 +6,99 @@
...
+
+The *spectra ID* mean the number, assigned to spectra. This number is often equal to *WorkspaceIndex+1*, e.g. ::
```
Comment (soininen) [inline docs/source/algorithms/MaskDetectors-v1.rst]: Exactly, it is *workspace index*, *spectrum number*, AND *detector id*.

File: docs/source/algorithms/MaskDetectors-v1.rst [hunk 49]
```diff
@@ -6,35 +6,99 @@
...
+being a *Mask Workspace* (SpecialWorkspace2D object) or  `Matrix Workspace <http://docs.mantidproject.org/nightly/concepts/MatrixWorkspace.html#matrixworkspace>`_. 
+
+If source *MaskedWorkspace* is a *Mask Workspace* and the number of spectra in the source 
+*MaskedWorkspace* is equal to number of spectra in the target *Workspace*, the 
+spectra numbers of the *MaskedWorkspace* are used as source 
+of masking information for the target workspace. 
+
+If the numbers of spectra in *Workspace* and *MaskedWorkspace* are different,
+the algorithm extracts list of masked detector IDS from source workspace and
+used them to mask the correspondent spectra of the target workspace.
```
Comment (soininen) [inline docs/source/algorithms/MaskDetectors-v1.rst]: used -> uses

File: docs/source/algorithms/MaskDetectors-v1.rst [hunk 50]
```diff
@@ -6,35 +6,99 @@
...
+*MaskedWorkspace* is equal to number of spectra in the target *Workspace*, the 
+spectra numbers of the *MaskedWorkspace* are used as source 
+of masking information for the target workspace. 
+
+If the numbers of spectra in *Workspace* and *MaskedWorkspace* are different,
+the algorithm extracts list of masked detector IDS from source workspace and
+used them to mask the correspondent spectra of the target workspace. 
+
+Setting property *ForceInstrumentMasking* to true forces algorithm 
+to always use *MaskedWorkspace* detectors ID
```
Comment (soininen) [inline docs/source/algorithms/MaskDetectors-v1.rst]: detectors ID -> detector IDs

File: docs/source/algorithms/MaskDetectors-v1.rst [hunk 51]
```diff
@@ -309,7 +367,88 @@ Output
...
+
+.. testcode:: ExMaskInRange
+
+  # Create a data workspace
+  ws = CreateSampleWorkspace()
+  # Mask 3 detectors using the masking range
+  MaskDetectors(ws, StartWorkspaceIndex=2, EndWorkspaceIndex=4)  
 
+  # Check masking of first 6 detectors
+  for ind in xrange(0,6):
```
Comment (soininen) [inline docs/source/algorithms/MaskDetectors-v1.rst]: `xrange` is gone in python 3, so I'd drop it from here, as well, and use `range` instead. The list of values is pretty short, anyway.

File: docs/source/algorithms/MaskDetectors-v1.rst [hunk 52]
```diff
@@ -309,7 +367,88 @@ Output
...
+    det = ws.getDetector(ind)
+    print 'Detector',det.getID(),'is masked:',det.isMasked()
```
Comment (soininen) [inline docs/source/algorithms/MaskDetectors-v1.rst]: Maybe use the function-like `print()` for future Python 3 compatibility. Start teaching it to the users already.

File: Framework/DataHandling/src/LoadMask.cpp (hunk 6 above)
Comment (soininen) [inline Framework/DataHandling/src/LoadMask.cpp]: I guess you are right here. I was not going to force this anyway. Maybe it would be preferable to find all these local little parsers scattered around the Mantid codebase and unify them to a general one, but that is indeed an issue of another time.

File: Framework/DataHandling/src/LoadMask.cpp (hunk 11 above)
Comment (abuts) [inline Framework/DataHandling/src/LoadMask.cpp]: changed

File: Framework/DataHandling/src/LoadMask.cpp (hunk 12 above)
Comment (abuts) [inline Framework/DataHandling/src/LoadMask.cpp]: yes, its an old code, which was not C++11

File: Framework/DataHandling/src/LoadMask.cpp (hunk 14 above)
Comment (abuts) [inline Framework/DataHandling/src/LoadMask.cpp]: that's scary -- it may slightly change the behaviour and I would better not to touch this remembering wide usage of this algorithm and variety of various mask files. 

I better leave it as it is.

File: Framework/DataHandling/src/LoadMask.cpp (hunk 15 above)
Comment (abuts) [inline Framework/DataHandling/src/LoadMask.cpp]: people say you should check errors. But who cares....

File: Framework/DataHandling/src/LoadMask.cpp (hunk 16 above)
Comment (abuts) [inline Framework/DataHandling/src/LoadMask.cpp]: yes.

File: Framework/DataHandling/inc/MantidDataHandling/LoadMask.h (hunk 17 above)
Comment (abuts) [inline Framework/DataHandling/inc/MantidDataHandling/LoadMask.h]: Do not know -- I was asking Nick to remove this code (for another ticket) and he suggested to keep it. May be he misunderstood me, but if needs to be removed I have to ask him again. 
this would be another ticket.

File: Framework/DataHandling/src/LoadMask.cpp (hunk 19 above)
Comment (abuts) [inline Framework/DataHandling/src/LoadMask.cpp]: Strange. I believe I have weed up all these cases for another ticket.

File: Framework/DataHandling/src/LoadMask.cpp (hunk 20 above)
Comment (abuts) [inline Framework/DataHandling/src/LoadMask.cpp]: ok

File: Framework/DataHandling/src/LoadMask.cpp (hunk 21 above)
Comment (abuts) [inline Framework/DataHandling/src/LoadMask.cpp]: hm...

File: Framework/DataHandling/src/LoadMask.cpp (hunk 23 above)
Comment (abuts) [inline Framework/DataHandling/src/LoadMask.cpp]: not familiar with this construct.

File: Framework/DataHandling/src/LoadMask.cpp (hunk 25 above)
Comment (abuts) [inline Framework/DataHandling/src/LoadMask.cpp]: Ok

File: Framework/DataHandling/src/MaskDetectors.cpp (hunk 28 above)
Comment (abuts) [inline Framework/DataHandling/src/MaskDetectors.cpp]: let it be just new style

File: Framework/DataHandling/inc/MantidDataHandling/MaskDetectors.h (hunk 31 above)
Comment (abuts) [inline Framework/DataHandling/inc/MantidDataHandling/MaskDetectors.h]: structure needs definition and tuple is the part of the language. So question of the taste and changes are too big for just cosmetic.

File: Framework/DataHandling/src/MaskDetectors.cpp (hunk 32 above)
Comment (abuts) [inline Framework/DataHandling/src/MaskDetectors.cpp]: I do not remember reason for this, may be just caution or testing, but I did it for some vague purpose. Do not remember it now (~8 week went after I deal with this code)

File: Framework/DataHandling/src/MaskDetectors.cpp (hunk 33 above)
Comment (abuts) [inline Framework/DataHandling/src/MaskDetectors.cpp]: again, do not remember the exact reason but recalling some thought. May be just testing separately...

File: Framework/DataHandling/src/MaskDetectors.cpp (hunk 35 above)
Comment (abuts) [inline Framework/DataHandling/src/MaskDetectors.cpp]: do constrain

File: Framework/DataHandling/src/MaskDetectors.cpp (hunk 37 above)
Comment (abuts) [inline Framework/DataHandling/src/MaskDetectors.cpp]: probably more then one id meant here.

File: Framework/DataHandling/src/MaskDetectors.cpp (hunk 38 above)
Comment (abuts) [inline Framework/DataHandling/src/MaskDetectors.cpp]: not sure if it works for set and lazy checking. Its the same anyway.

File: Framework/DataHandling/src/MaskDetectors.cpp (hunk 39 above)
Comment (abuts) [inline Framework/DataHandling/src/MaskDetectors.cpp]: swap modifies indexList and return the result. Assign will then work without tmp vector but needs internal reallocations.

File: Framework/DataHandling/src/MaskDetectors.cpp (hunk 41 above)
Comment (abuts) [inline Framework/DataHandling/src/MaskDetectors.cpp]: initial matrixWorkspace_sptr is not const -- I just transferring it as const to the function. Compiler recognises  MatrixWorkspace_const_sptr as different type. Would not work

File: Framework/DataHandling/src/MaskDetectors.cpp (hunk 42 above)
Comment (abuts) [inline Framework/DataHandling/src/MaskDetectors.cpp]: done to avoid internal reallocations.

File: Framework/DataHandling/src/MaskDetectors.cpp (hunk 43 above)
Comment (abuts) [inline Framework/DataHandling/src/MaskDetectors.cpp]: ok

File: docs/source/algorithms/MaskDetectors-v1.rst (hunk 45 above)
Comment (abuts) [inline docs/source/algorithms/MaskDetectors-v1.rst]: There is various terminology within Mantid and in a wild (among IS), may be worth mentioning both terms.  as DetectorID is mentioned spectra ID refereed first here

File: docs/source/algorithms/MaskDetectors-v1.rst (hunk 49 above)
Comment (abuts) [inline docs/source/algorithms/MaskDetectors-v1.rst]: ok

File: docs/source/algorithms/MaskDetectors-v1.rst (hunk 51 above)
Comment (abuts) [inline docs/source/algorithms/MaskDetectors-v1.rst]: xrange works on 2.7.  People who will modify this code, will use much longer lists.

File: docs/source/algorithms/MaskDetectors-v1.rst (hunk 52 above)
Comment (abuts) [inline docs/source/algorithms/MaskDetectors-v1.rst]: print() under python 2.7 works but prints brackets too. 
Lethal for doctests which run under 2.7

File: Framework/DataHandling/src/MaskDetectors.cpp (hunk 32 above)
Comment (soininen) [inline Framework/DataHandling/src/MaskDetectors.cpp]: You are correct that a signed value should be tested for positiveness before casting to unsigned; I'm just pointing out here that `startIndex` is implicitly positive due to the validator of *StartWorkspaceIndex*. I guess leaving the test as-is doesn't really hurt.

File: Framework/DataHandling/inc/MantidDataHandling/MaskDetectors.h (hunk 31 above)
Comment (soininen) [inline Framework/DataHandling/inc/MantidDataHandling/MaskDetectors.h]: Structs are part of the core language as well and I think the use cases for tuples in C++ lay elsewhere. But as you say, this is partly a question of taste and if you feel the improvement in code readability does not justify the amount of changes, then I think we should leave the tuple as it is.

File: docs/source/algorithms/MaskDetectors-v1.rst (hunk 51 above)
Comment (soininen) [inline docs/source/algorithms/MaskDetectors-v1.rst]: Good point.

File: docs/source/algorithms/MaskDetectors-v1.rst (hunk 52 above)
Comment (soininen) [inline docs/source/algorithms/MaskDetectors-v1.rst]: I see. Interesting. So,
```
print('a: ',det.getID())
```
thinks it's a tuple in Python 2.x. One could use string formatting here:
```
print('Detector {} is masked: {}'.format(det.getID(), det.isMasked))
```
to make python 3 and doctests happy.

**Review by soininen — CHANGES_REQUESTED** [review]
Please address the terminology issues in MaskDetectors-v1.rst:
Spectra ID -> spectrum number

**Review by soininen — APPROVED** [review]

**Comment by abuts** [comment]
I have modified documentation clarifying various terminology and explaining a bit more details about spectra.

File: Framework/DataHandling/src/MaskDetectors.cpp (hunk 32 above)
Comment (abuts) [inline Framework/DataHandling/src/MaskDetectors.cpp]: I vaguely remember that there is opposite case here -- unsigned static_cast-ed to int without any checks. Of course, its very unlikely that this unsigned will be big enough to produce negative value, so placed this check rather instinctively, but its not performance critical, so let it be there.

**Comment by soininen** [comment]
With these changes it is indeed possible to load and apply a mask originating from a workspace with grouped detectors. Worked fine with the test mentioned in the PR and in the few other simple scenarios I tested this on, at least. As I see it, the code is of good quality and this should be nice improvement for users working with instruments generating these types of workspaces. :shipit:
