### PR TITLE
detector header isaw peaks file

### LINKED ISSUE #19414: Header for Peaks file should have all banks in instrument
### Expected behavior
All banks in header file
### Actual behavior
Banks that contain peaks in header file
### Steps to reproduce the behavior
SaveIsawPeaks

### PR DESCRIPTION
**Pull request by VickieLynch**
`SaveIsawPeaks` header should contain all the banks in the instrument that are not masked.  `LoadIsawPeaks` should mask all banks in the instrument that are not in the header.

**To test:**

```python
test=LoadIsawPeaks(Filename='test.integrate')
SaveIsawPeaks(Filename='test2.integrate',InputWorkspace=test)
MaskBTP(Workspace=test,Bank="14,16,17,18,19,20,21,22,23,26,27,28,29,33,34,36,37,38,39,46,47,48,49")
SaveIsawPeaks(Filename='test3.integrate',inputWorkspace=test)
test3=LoadIsawPeaks(Filename='test3.integrate')
```
test2.integrate and test.integrate should be the same within numerical precision.  test3.integrate should only have the bank that was not masked.
https://www.dropbox.com/s/57zrutvoyiqg14f/test.integrate?dl=0

Fixes #19414

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Crystal/src/SaveIsawPeaks.cpp [hunk 1]
```diff
@@ -373,6 +395,41 @@ void SaveIsawPeaks::exec() {
   out.close();
 }
 
+bool SaveIsawPeaks::bankMasked(IComponent_const_sptr parent,
+                               const DetectorInfo &detectorInfo) {
```
Comment (SimonHeybrock) [inline Framework/Crystal/src/SaveIsawPeaks.cpp]: Just a quick comment: Have a look at https://github.com/mantidproject/mantid/blob/master/Framework/API/inc/MantidAPI/ComponentInfo.h#L62. This function might simplify to something like

```cpp
for (auto detIndex : ws.componentInfo().detectorIndices(compIndex)) {
  if detInfo.isMasked(detIndex);
}
```

**Comment by peterfpeterson** [comment]
This works as advertised. :shipit:
