### PR TITLE
Save project dialog bug

### LINKED ISSUE #19562: "Save project" dialog doesn't show when closing MantidPlot
### Expected behavior

If there are changes to a mantid project (opened new plot windows, etc) when closing MantidPlot by pressing the [x] button a dialog shows and asks if you want to save the project.

### Actual behavior

The dialog doesn't show, MantidPlot just closes.

### Steps to reproduce the behavior

Load a dataset, plot a spectrum, close MantidPlot pressing the [x] button.

### Platforms affected

All.

### PR DESCRIPTION
**Pull request by mantid-roman**
Moved the call to save the project to the event handler of `ApplicationWindow`'s `close` event. This way it is called from both the "close" button and the File->Quit menu.

**To test:**

Create some windows, including main windows such as SliceViewer. Close mantid by different ways. It should offer to save the project.

Fixes #19562.

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by martyngigg — COMMENTED** [review]
The code changes look sensible to me.

I'll take it for a quick spin.

**Comment by martyngigg** [comment]
As we discussed offline we are going to apply a small change so that if you click "Yes" to save the project but then click "Cancel" on the save dialog you *do not* quit the application. This is a safer and the style that users are used to with other applications such as word.

File: MantidPlot/src/ApplicationWindow.cpp [hunk 1]
```diff
@@ -6071,7 +6071,12 @@ void ApplicationWindow::prepareSaveProject() {
       projectname, *serialiser, windows, this);
   connect(m_projectSaveView, SIGNAL(projectSaved()), this,
           SLOT(postSaveProject()));
-  m_projectSaveView->show();
+  return m_projectSaveView->exec();
+}
+
+void ApplicationWindow::prepareSaveProject() {
+  auto result = execSaveProjectDialog();
```
Comment (martyngigg) [inline MantidPlot/src/ApplicationWindow.cpp]: Do we need to capture the variable here? Can't we just not assign the function call to anything?

**Review by martyngigg — APPROVED** [review]
This looks good now.

Please :shipit:.

**Comment by martyngigg** [comment]
I've run the failing serialise test many times on my machine (on Windows) and I can't get it to fail - I don't think it is related to these changes.

**Comment by rosswhitfield** [comment]
:+1: MantidPlotProjectSerialiseTest is already in the *Mantid Build False Positives* spreadsheet
