### PR TITLE
Fix stack overflow error due to invalid condition

### LINKED ISSUE #38704: Crash on setting invalid data search dirs
**Original reporter:** Sam Jones

**Describe the bug**
```
 I ran a script that contained:
ConfigService.setDataSearchDirs("/archive/NDXSANS2D/user/masks/,/archive/NDXSANS2D/user/Masks/")
```

**Expected behavior**
Raise an error / warning instead of segfaulting.

**Platform/Version (please complete the following information):**
 - OS: Ubuntu
 - OS Version: 20.04.6
 - Mantid Version 6.11

### PR DESCRIPTION
**Pull request by MohamedAlmaki**
### Description of work
This PR fixes a stack overflow error in `ConfigService` due to an invalid condition causing infinite recursion in the function `makeAbsolute`. 

Fixes #38704

#### Further detail of work

In the `splitPath` function, the previous condition was only checking for the ";" delimiter. This causes `makeAbsolute` to call itself infinitely when the string contains only "," delimiters. I have corrected the function to include the "," delimiter, similar to the condition in `make absolute`, to ensure consistency. 
### To test:
1- Run this line in the Python script area:
``ConfigService.setDataSearchDirs("/archive/NDXSANS2D/user/masks/,/archive/NDXSANS2D/user/Masks/")``
2- It should work well without a crash
3- Check the data search dirs in Manage directories to ensure the two paths have been added correctly
4- Try different paths with combinations of "," and ";"

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by GuiMacielPereira — DISMISSED** [review]
Fix makes sense. I tested with one comma as suggested and then with several combinations of `,` and `;`, and it worked fine with no issues.

File: Framework/Kernel/src/ConfigService.cpp [hunk 1]
```diff
@@ -86,15 +86,15 @@ namespace { // anonymous namespace for some utility functions
...
+ * Split the supplied string on semicolons and commas.
  *
  * @param path The path to split.
  * @returns vector containing the split path.
  */
 std::vector<std::string> splitPath(const std::string &path) {
   std::vector<std::string> splitted;
 
-  if (path.find(';') == std::string::npos) { // don't bother tokenizing
+  if (path.find_first_of(";,") == std::string::npos) { // don't bother tokenizing
```
Comment (cailafinn) [inline Framework/Kernel/src/ConfigService.cpp:97]: These two needing to be in sync has the potential to cause issues down the line. Can we make a constant called `PATH_DELIMITERS` or something that can be used in both places so this is less likely to happen again?

**Review by cailafinn — CHANGES_REQUESTED** [review]
Quick note on the code about using a constant instead of literals. 

Additionally, It looks like this could benefit from a test or two - and it needs a release note as the bug was user-facing.

File: docs/source/release/v6.13.0/Framework/Python/Bugfixes/38821.rst [hunk 2]
```diff
@@ -0,0 +1 @@
+- Fix a crash that happens when trying to use :class:`ConfigService.setDataSearchDirs <mantid.kernel.ConfigServiceImpl.setDataSearchDirs>` with comma separated paths.
```
Comment (cailafinn) [inline docs/source/release/v6.13.0/Framework/Python/Bugfixes/38821.rst:1]: Could we reword this somewhat to match the style mentioned in the release notes talk last week?
```suggestion
- :class:`ConfigService.setDataSearchDirs <mantid.kernel.ConfigServiceImpl.setDataSearchDirs>` will no longer crash when comma separated paths are used in the `datasearch.directories` setting of the `mantid.user.properties` file. 
```

**Review by cailafinn — CHANGES_REQUESTED** [review]
One tiny nitpick before merging:

File: docs/source/release/v6.13.0/Framework/Python/Bugfixes/38821.rst (hunk 2 above)
Comment (MohamedAlmaki) [reply docs/source/release/v6.13.0/Framework/Python/Bugfixes/38821.rst]: Modifed and squashed the commits for clear history

**Review by cailafinn — APPROVED** [review]
