### PR TITLE
GetEi version 1 does not work anymore

### LINKED ISSUE #16049: GetEi version 1 does not work any more.
### If one tries to run GetEi version 1, it fails, e.g: 
`
Load(Filename='MER30514.nxs', OutputWorkspace='MER30514', LoadMonitors=True, SpectrumMin=69631, SpectrumMax=69640)`
`
 GetEi('MER30514_monitors',69634,69638,100,Version=1)
`
should return Ei and  first peak time
### Actually:   it throws the error:
"Attempt to assign to property (StartWorkspaceIndex) of incorrect type"

### Tried on windows and RHEL7

### PR DESCRIPTION
**Pull request by abuts**
Description of work.

**To test:**
See ticket description -- GetEi version 1 fails before the fix and should run fine after. 
Changes are small and obvious so code review should be sufficient. 

Fixes #16049.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [ ] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Algorithms/src/GetEi.cpp [hunk 1]
```diff
@@ -325,10 +325,17 @@ void GetEi::extractSpec(int64_t wsInd, double start, double end) {
 
   childAlg->setProperty<MatrixWorkspace_sptr>("InputWorkspace",
                                               getProperty("InputWorkspace"));
+
   childAlg->setProperty("XMin", start);
   childAlg->setProperty("XMax", end);
-  childAlg->setProperty("StartWorkspaceIndex", wsInd);
-  childAlg->setProperty("EndWorkspaceIndex", wsInd);
+  if (wsInd < std::numeric_limits<int>::max()) {
```
Comment (quantumsteve) [inline Framework/Algorithms/src/GetEi.cpp]: I don't understand why this function's signature takes an `int64_t` when the child algorithm needs and `int`. It looks like version 2 has the same issue but hides it with a `static_cast<int>`. 

Would changing `GetEi::extractSpec` so that `wsInd` is an `int` or changing `CropWorkspace` so that `StartWorkspaceIndex` and `EndWorkspaceIndex` are `int64_t` be better solutions? The former advertises a limitation, while the later may introduce other bugs but makes it work as a naive developer would assume.

**Comment by quantumsteve** [comment]
Would you add a unit test for version 1 so that issues like these are more likely to be caught?

**Comment by abuts** [comment]
Hmm.

**Comment by abuts** [comment]
I do not know why its int_64 and have not looked at GetEi v2. 
The thing I did is minimal modification I needed to sort issue with experiment. 

I would better talk to Martyn who wrote both algorithms and discuss why this issue ever appear. Its possible it left from the time when we may have 2-bytes int on 32 bit system, but as these times have long gone, so we may change the GetEi V1. I do not think we will have instruments with ~4*10^9 detectors in forcible future, so no point in changing CropWorkspace. 

I will add unit test for version 1 if you think its needed.

**Comment by quantumsteve** [comment]
If this version's worth fixing, then it's worth having a test to ensure the same issue doesn't happen again. If GetEi v1 hasn't been used in years, it should also inherit from `Mantid::API::DeprecatedAlgorithm`.

**Comment by abuts** [comment]
Yes, it was not used but not I was actually needed it after all, so let it exist.

**Comment by quantumsteve** [comment]
The change look good. Should this be in the release notes?

**Comment by abuts** [comment]
I do not think release notes are necessary, as first its bugfix so people would expect it to work anyway, plus GetEi v1 can not be currently used in SNS reduction + reduction code needs changing if one wants to use it in ISIS reduction. GetEi v1 has very narrow area of applicability (like this time, when I was trying to identify why GetEi v1 returns incorrect results and appears that its sample problem) 

Let GetEi v1 to stay for emergencies and comparison reasons but its area of applicability belongs to advanced usage in very specific circumstances so only very special people in very special circumstances should care about it.

**Comment by quantumsteve** [comment]
:shipit:
