### PR TITLE
Fix overwriting of settings for existing batches when adding a new one

### LINKED ISSUE #34845: Adding a new batch tab wipes the existing batch
**Original reporter:** Becky at ISIS

In the ISIS Reflectometry interface, if you go to Batch menu and select New, it will add a new batch tab. There is a bug where this incorrectly clears the experiment settings on any other batch tabs.

The bug happens with all instruments except INTER.

Steps to reproduce:
- Open the ISIS Reflectometry interface
- Set instrument to POLREF
- On the Experiment settings tab, change some values or enter a value in the table, e.g. `1` in ROI.
- Go to the Batch menu and select New
- The values you changed are reverted

### PR DESCRIPTION
**Pull request by rbauststfc**
**Description of work:**

The first step we perform when adding a new batch is to populate the dropdown list of instruments on the Runs tab. It seems that when you add a new item to a `QComboBox` it is automatically selected and this triggers the signal `currentIndexChanged`. In our code this then kicks off the workflow to handle a change in instrument. Within this workflow, we load the new instrument and then, if the new instrument is different to the old instrument, we reset the settings across all batch tabs and notify the slit calculator. This behaviour meant that when we added a new batch for an instrument other than the one selected by default (INTER), the step that populated the dropdown for the new batch would trigger a reset of any existing batch settings.

When we create the very first batch as part of creating the Reflectometry GUI we need to run through the steps that populate the dropdown, load the instrument and configure the slits. When we're adding new batches for the current instrument, we just need to populate the dropdown and (as commented in the code) reload the instrument to ensure all settings are up to date. Loading the instrument and configuring the slits are currently only included in the workflow that is triggered when the selected instrument is changed, there isn't a separate workflow that handles these steps when adding a new batch.

I think the ideal fix for this issue would involve looking at where we could separate the workflows for setting up a new batch vs handling a change in instrument, obviously being mindful of duplication. However, because we are so close to the next release, the fix in this PR simply refactors the `QtRunsView::setInstrumentList` method so that it takes the name of the instrument that should be selected, blocks all signals while the dropdown is populated and the correct instrument selected, and then manually emits the signal to trigger the rest of the workflow using the correct selection.

Even as part of a short-term fix, it feels like we shouldn't need to be blocking signals, however I couldn't find anything in the docs for `QComboBox` that seemed to allow you to populate the dropdown and specify the item you want to be selected at the same time.

Unfortunately I also couldn't see a way to add a test for the changes in this PR, but happy to take advice on that if there's a way to do it that I've missed.

**To test:**

See steps on the linked issue that would have previously reproduced the bug. Now no settings should be overwritten on existing batch tabs. Note that changes in the Runs and Instrument settings tabs should be tested too, as these were also being overwritten by the bug.

Fixes #34845. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by robertapplin — APPROVED** [review]
Works as expected, and code looks good. I have also struggled in the past to find a Qt method on QCombobox that does what we want here, so happy with this solution

File: qt/scientific_interfaces/ISISReflectometry/GUI/Runs/QtRunsView.cpp [hunk 1]
```diff
@@ -158,14 +158,24 @@ void QtRunsView::setUpdateIntervalSpinBoxEnabled(bool enabled) { m_ui.spinBoxUpd
...
 @param instruments : The list of instruments available
+@param selectedInstrument : The name of an instrument to select from the dropdown
 default
 */
-void QtRunsView::setInstrumentList(const std::vector<std::string> &instruments) {
+void QtRunsView::setInstrumentList(const std::vector<std::string> &instruments, const std::string &selectedInstrument) {
+  // We block signals while populating the list and setting the selected instrument because adding the first item
+  // will trigger a currentIndexChanged signal. This causes existing batch settings to be overwritten when we're
+  // initialising a new batch for an instrument that isn't the first in the list.
+  m_ui.comboSearchInstrument->blockSignals(true);
```
Comment (martyngigg) [inline qt/scientific_interfaces/ISISReflectometry/GUI/Runs/QtRunsView.cpp:171]: I won't hold this up but I just want to signpost the `QSignalBlocker` (https://doc.qt.io/qt-5/qsignalblocker.html). It's useful for this situations where you need to block/do something/unblock but using the RAII pattern to manage it with an object lifetime. It is a nice way of ensuring that if an exception is thrown in the middle that the signal still unblocks.
