### PR TITLE
Change the units for time remaining in the algorithm progress bar from h-h to h-min

### LINKED ISSUE #23640: Progress Bar for Algorithms has units of hr-hr
**Original reporter:** Ron Smith . (ISIS) James Lord (ISIS)

### Expected behavior

The progress bar should estimate the length of an algorithm's run-time in hr-min

### Actual behavior

The progress bar displays time in hr-hr
screen shot 2018-09-26 at 16 50 06

### Steps to reproduce the behavior

Execute an algorithm in Mantid
The progress bar has also started to flash in some instances of 3.13

### PR DESCRIPTION
**Pull request by PhilColebrooke**
**Description of work.**
When executing an algorithm that takes more than an hour in MantidPlot, the progress bar showing the time remaining now has the correct units of h-min instead of h-h.

**To test:**
1. In MantidPlot, run an algorithm that takes over an hour. Example: CalculatePolynomialBackground with a high degree (30+).
2. Check that the time remaining is in the correct units.

Fixes #23640 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: MantidPlot/src/Mantid/AlgorithmDockWidget.cpp [hunk 1]
```diff
@@ -81,7 +81,8 @@ void AlgorithmDockWidget::updateProgress(void *alg, const double p,
       } else {
         int hours = static_cast<int>(estimatedTime / 3600);
         int min = static_cast<int>((estimatedTime - hours * 3600) / 60);
-        mess << hours << "h" << std::setfill('0') << std::setw(2) << min << "h";
+        mess << hours << "h" << std::setfill('0') << std::setw(2) << min
+             << "min";
```
Comment (Pasarus) [inline MantidPlot/src/Mantid/AlgorithmDockWidget.cpp]: This should probably be "m"
```suggestion
             << "m";
```

**Review by Pasarus — CHANGES_REQUESTED** [review]
To fit with other places in mantid I have suggested a change.

**Review by Pasarus — APPROVED** [review]
