### PR TITLE
Fix issues regarding zero or non-unity length V3Ds

### LINKED ISSUE #24898: Components with null vector as facing direction
Adding a check in `Kernel::V3D::normalize()` to make sure that we are not normalizing a null vector revealed some issues in Mantid, most notably in code that rotates the component face. If the component and the 'facing point' are both in the same position, the rotation is not well defined.

### PR DESCRIPTION
**Pull request by soininen**
The main gist of this PR make is to make `V3D::normalize()` and `Track` to throw when given vectors are of invalid length. Rest of the PR revolves around fixing the problems that thus became exposed, mostly in unit tests.

**To test:**

Careful code review.

Fixes #24898.

*This does not require release notes* because this is an internal change.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Geometry/test/InstrumentRayTracerTest.h [hunk 1]
```diff
@@ -156,9 +157,13 @@ class InstrumentRayTracerTest : public CxxTest::TestSuite {
...
   void doTestRectangularDetector(std::string message, Instrument_sptr inst,
                                  V3D testDir, int expectX, int expectY) {
-    //    std::cout << message << '\n';
     InstrumentRayTracer tracker(inst);
-    testDir.normalize(); // Force to be unit vector
+    const auto norm = testDir.norm();
+    if (norm == 0.) {
+      TS_ASSERT_THROWS_ANYTHING(tracker.traceFromSample(testDir));
+      return;
+    }
```
Comment (peterfpeterson) [inline Framework/Geometry/test/InstrumentRayTracerTest.h]: This feels like it should be an `else`

**Review by peterfpeterson — CHANGES_REQUESTED** [review]
A welcome improvement

File: Framework/Geometry/test/InstrumentRayTracerTest.h (hunk 1 above)
Comment (soininen) [reply Framework/Geometry/test/InstrumentRayTracerTest.h]: I moved this case to its own test function.

**Review by peterfpeterson — APPROVED** [review]
