### PR TITLE
Get radius from sample in AnvredCorrection

### LINKED ISSUE #32893: AbsorptionCorrection doesn't get spherical sample shape from workspace
**Describe the bug**
The algorithm gets the material properties (number density etc.) from the workspace, but not the sphere radius.
The sphere radius is marked as an optional property but if not provided ends up as a nonsense empty double.

**To Reproduce**
(1) Run this script
```
 ConvertUnits(InputWorkspace='SXD33338_sm_deadCor', OutputWorkspace='SXD33338_sm_deadCor', Target='Wavelength')
shape = '''<sphere id="V-sphere">
    <centre x="0.0"  y="0.0" z="0.0" />
    <radius val="0.0025"/>
    </sphere>'''
SetSample('SXD33338_sm_deadCor', Geometry={'Shape': 'CSG', 'Value': shape},
          Material={'ChemicalFormula': 'V0.95-Nb0.05', 'SampleNumberDensity': 0.0119}) # ScatteringXSection = 5.197,AttenuationXSection=4.739
SphericalAbsorption(InputWorkspace='SXD33338_sm_deadCor', OutputWorkspace='van_abs_corr')
```
(2) Get this warning with unphysical muR
`AnvredCorrection-[Warning] muR (6.63432e+306) is not in range of Dwiggins' table ( 0 < muR < 2.5) so using extrapolation of cubic fit.`

**Expected behavior**
Would get shape from sample (as done in other algorithms).

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: [e.g. Windows, RHEL 7, Ubuntu, macOS]
 - OS Version:
 - Mantid Version [e.g. 6.0.0]

**Additional context**

### PR DESCRIPTION
**Pull request by RichardWaiteSTFC**
**Description of work.**

Added validation to input to `AnvredCorrection` to check that if a radius is not supplied then the sample must have a spherical sample with a radius (this is technically a breaking change, but if users hadn't supplied a radius (it has always been optional) then the result would be nonsense so it is probably good to throw an error).

Also corrected a polynomial coefficient at one theta - further details can be found here
https://github.com/mantidproject/mantid/issues/31342#issuecomment-960816860

**To test:**
Test it using `SphericalAbsorption` (which calls `AnvredCorrection`)
(1) Run this script without error
```
ws = CreateSampleWorkspace()
ConvertUnits(InputWorkspace='ws', OutputWorkspace='ws', Target='Wavelength')
shape = '''<sphere id="V-sphere">
    <centre x="0.0"  y="0.0" z="0.0" />
    <radius val="0.0025"/>
    </sphere>'''
SetSample(ws, Geometry={'Shape': 'CSG', 'Value': shape},
          Material={'ChemicalFormula': 'V0.95-Nb0.05', 'SampleNumberDensity': 0.0119}) 
SphericalAbsorption(InputWorkspace=ws, OutputWorkspace='van_abs_corr')
```
It should print in the log that the radius was 0.25 cm
(2) Check that the radius used (printed in the log) is the one supplied rather than from sample (backward compatibility)
```
SphericalAbsorption(InputWorkspace=ws, OutputWorkspace='van_abs_corr', SphericalSampleRadius=0.5)
```
(3) Try setting a non-spherical sample - it should throw an error
```
SetSample(ws, Geometry={'Shape': 'HollowCylinder', 'Height': 4.0, 'InnerRadius': 0.8, 'OuterRadius': 1.0, 'Center': [0.,0.,0.]},
    Material={'ChemicalFormula': 'V0.95-Nb0.05', 'SampleNumberDensity': 0.0119})
SphericalAbsorption(InputWorkspace=ws, OutputWorkspace='van_abs_corr_cylinder')
```

Fixes #32893 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Algorithms/src/SphericalAbsorption.cpp [hunk 1]
```diff
@@ -64,7 +64,8 @@ void SphericalAbsorption::init() {
                   "The number density of the sample in number of atoms per "
                   "cubic angstrom, if not set with SetSampleMaterial");
   declareProperty("SphericalSampleRadius", EMPTY_DBL(), mustBePositive,
-                  "The radius of the spherical sample in centimetres");
+                  "The radius of the spherical sample in centimetresif "
```
Comment (DavidFair) [inline Framework/Algorithms/src/SphericalAbsorption.cpp:67]: Small nit: missing space between `centimetres if`

Also I think this needs rewording slightly, to something like:
"in centimetres. This can be omitted if a spherical sample with known radius is set using SetSample`

File: Framework/Crystal/src/AnvredCorrection.cpp [hunk 2]
```diff
@@ -94,7 +94,9 @@ void AnvredCorrection::init() {
   declareProperty("LinearAbsorptionCoef", EMPTY_DBL(), mustBePositive,
                   "Linear absorption coefficient at 1.8 Angstroms in 1/cm if "
                   "not set with SetSampleMaterial");
-  declareProperty("Radius", EMPTY_DBL(), mustBePositive, "Radius of the sample in centimeters");
+  declareProperty("Radius", EMPTY_DBL(), mustBePositive,
+                  "Radius of the sample in centimeters if "
+                  "not set with SetSample.");
```
Comment (DavidFair) [inline Framework/Crystal/src/AnvredCorrection.cpp:99]: Ditto

File: Framework/Crystal/src/AnvredCorrection.cpp [hunk 3]
```diff
@@ -114,6 +116,22 @@ void AnvredCorrection::init() {
...
+std::map<std::string, std::string> AnvredCorrection::validateInputs() {
+  std::map<std::string, std::string> result;
+
+  const double radius = getProperty("Radius");
+  if (radius == EMPTY_DBL()) {
+    // check that if radius isn't supplied that the radius can be accessed from the sample
+    m_inputWS = getProperty("InputWorkspace");
+    const auto &sampleShape = m_inputWS->sample().getShape();
+    if (!sampleShape.hasValidShape() ||
+        sampleShape.shapeInfo().shape() != Geometry::detail::ShapeInfo::GeometryShape::SPHERE) {
```
Comment (DavidFair) [inline Framework/Crystal/src/AnvredCorrection.cpp:128]: Does this need to be a sphere or would this work with cylinders too as per the [implementation](https://doxygen.mantidproject.org/nightly/d0/d72/ShapeInfo_8cpp_source.html)?

Secondly, do we need to check that `shapeInfo().radius != 0`?

**Review by DavidFair — COMMENTED** [review]
Small typo / questions

File: Framework/Crystal/src/AnvredCorrection.cpp (hunk 3 above)
Comment (RichardWaiteSTFC) [reply Framework/Crystal/src/AnvredCorrection.cpp:128]: The implementation does not work for cylinders - or rather cylinders require different coefficients for the polynomial in the array `pc`.
I just checked and it is possible to set a sample to have a radius of 0, in this case `mur = mu*radius = 0` - this is fine for the code, which will evaluate the absorption correction to be `astar=1`. Perhaps more worrying is that I've just checked and I can set a negative radius!
A negative radius will at least throw an error later on
https://github.com/mantidproject/mantid/blob/e3b55babd91d978685a38e84605b957ed823ab04/Framework/Crystal/src/AnvredCorrection.cpp#L432-L433
But I can add some validation if you like?

File: Framework/Algorithms/src/SphericalAbsorption.cpp (hunk 1 above)
Comment (RichardWaiteSTFC) [reply Framework/Algorithms/src/SphericalAbsorption.cpp:67]: Thanks for spotting the typo, I think actually the doc string should reflect the fact that any value added there will be used instead of the sample radius on the shape, even if a valid one exists - I will do this.

File: Framework/Crystal/src/AnvredCorrection.cpp (hunk 3 above)
Comment (RichardWaiteSTFC) [reply Framework/Crystal/src/AnvredCorrection.cpp:128]: Perhaps there should be some validation on the shape itself to ensure radius is not negative?

**Comment by DavidFair** [comment]
From testing:
- This works `SphericalAbsorption(InputWorkspace=ws, OutputWorkspace='van_abs_corr', SphericalSampleRadius=0.)`
- This also works and produces a large number of warnings:
```
ws = CreateSampleWorkspace()
ConvertUnits(InputWorkspace='ws', OutputWorkspace='ws', Target='Wavelength')
SphericalAbsorption(InputWorkspace=ws, OutputWorkspace='van_abs_corr')
```

**Comment by RichardWaiteSTFC** [comment]
> From testing:
> 
> * This works `SphericalAbsorption(InputWorkspace=ws, OutputWorkspace='van_abs_corr', SphericalSampleRadius=0.)`
> * This also works and produces a large number of warnings:
> 
> ```
> ws = CreateSampleWorkspace()
> ConvertUnits(InputWorkspace='ws', OutputWorkspace='ws', Target='Wavelength')
> SphericalAbsorption(InputWorkspace=ws, OutputWorkspace='van_abs_corr')
> ```

I think this is actually because muR is too large - rather than the sample radius being 0
https://github.com/mantidproject/mantid/blob/e3b55babd91d978685a38e84605b957ed823ab04/Framework/Crystal/src/AnvredCorrection.cpp#L434-L438
At least that is the warning I get when I try your code.

File: Framework/Crystal/src/AnvredCorrection.cpp (hunk 3 above)
Comment (DavidFair) [reply Framework/Crystal/src/AnvredCorrection.cpp:128]: Is it possible to set a negative radius using setSample?
If so, I would move it to validation. Otherwise, it implies a broken IDF / something screwy going on and we can leave the check to last minute as it's not easy for a user to accidentally do

**Comment by DavidFair** [comment]
> I think this is actually because muR is too large - rather than the sample radius being 0

Ah I didn't check correctly if `CreateSampleWorkspace` assigned a sample shape / radius that was spherical.
Can we emit this warning once as it completely fill the log and wipes out all other info? Also the `std::endl` should be replaced with `\n` as it forces a buffer flush in the logging layer

File: Framework/Crystal/src/AnvredCorrection.cpp (hunk 3 above)
Comment (RichardWaiteSTFC) [reply Framework/Crystal/src/AnvredCorrection.cpp:128]: It isn't possible to set a negative radius when the user supplies it as an argument to the algorithm (we validate it is always positive). but it is possible for the user to set a sample shape as a sphere with a negative radius as so.
```
shape = '''<sphere id="V-sphere">
    <centre x="0.0"  y="0.0" z="0.0" />
    <radius val="0.0025"/>
    </sphere>'''
SetSample(ws, Geometry={'Shape': 'CSG', 'Value': shape})
```

Comment (RichardWaiteSTFC) [reply Framework/Crystal/src/AnvredCorrection.cpp:128]: > > I think this is actually because muR is too large - rather than the sample radius being 0
> 
> Ah I didn't check correctly if `CreateSampleWorkspace` assigned a sample shape / radius that was spherical. Can we emit this warning once as it completely fill the log and wipes out all other info? Also the `std::endl` should be replaced with `\n` as it forces a buffer flush in the logging layer

The trouble is the function which contains this check, `absor_sphere`, is called in a loop over events/bins, but I could print a single warning outrside the loop over events (probably do one per spectrum) if I add a bool `invalid_muR` argument to `absor_sphere` - would that work for you?

**Comment by RichardWaiteSTFC** [comment]
As discussed offline these concerns will be addressed in a separate PR to keep things moving and prevent conflicts - in particular
1. Adding validation in `SetSample` to ensure radius of sphere (and radii of cylinders?) is never negative will be done in #32892 
2. Moving warning/validation of muR outside loop over events (possibly pre-calculate muR) will be done in #32922 (in prog)
3. Altering doc string of parameters to make clear will take radius, and xs passed as arguments to alg instead of the values in the sample object of the workspace - #32922 (in prog)

**Review by DavidFair — APPROVED** [review]
Thanks for going through all of that, lets :shipit: as all the other tests worked correctly :+1:
