### PR TITLE
VSI crash fixed.

### LINKED ISSUE #24996: VSI made to crash
1. Run a script like the SXD_NaCl.py [here](https://github.com/mantidproject/mantid/blob/master/scripts/Vates/SXD_NaCl.py) script 
2. Show VSI (r-click) menu option in workspace list on the `QLab` workspace
3. Go to splatter plot mode
4. Drag-drop the integrated peaks workspace from the MantidPlot workspace list onto the VSI
5. From the Peaks menu in the VSI select the "Show All Peaks in Table" option. Crashes VSI.

Issue discovered on OSX testing the nightly build from 4th March

### PR DESCRIPTION
**Pull request by mantid-roman**
**Description of work.**
A shared pointer was referenced after it was moved. Copy the pointer instead.

**To test:**
Follow the instructions in the issue description and after that drag and drop the other peaks workspace. This way it always crashes (without the fix).

Fixes #24996.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/paraview_ext/VatesSimpleGui/ViewWidgets/src/PeaksTabWidget.cpp [hunk 1]
```diff
@@ -138,7 +138,7 @@ void PeaksTabWidget::updateTab(const std::vector<bool> &visiblePeaks,
 void PeaksTabWidget::addNewPeaksWorkspace(
     Mantid::API::IPeaksWorkspace_sptr peaksWorkspace,
     std::vector<bool> visiblePeaks) {
-  m_ws.push_back(std::move(peaksWorkspace));
+  m_ws.push_back(peaksWorkspace);
```
Comment (OwenArnold) [inline qt/paraview_ext/VatesSimpleGui/ViewWidgets/src/PeaksTabWidget.cpp]: Agreed this is a bug

**Review by OwenArnold — APPROVED** [review]
Works on osx. No crash.
