### PR TITLE
Fix hexahedron bounding box calculation

### LINKED ISSUE #16735: Make hexahedron bounding box geometry calculation more general
### Expected behavior
It should be possible to calculate the bounding box for any valid hexahedron shape.

### Actual behavior
The calculation logic excepts all hexahedron corners to have positive Z coordinates. Also, certain assumptions are made of 'front', 'left' and 'right'. If these restriction are violated, the Instrument view in Mantid cannot be opened due to error in creating bounding box.

### Steps to reproduce the behavior
Create a hexahedron shape in an IDF with negative Z coordinates, load it, and open the Instrument View in Mantid.

### PR DESCRIPTION
**Pull request by soininen**
The bounding box is now calculated in a more general way.

**To test:** Try viewing an instrument with hexahedron shapes with negative Z coordinates in Mantid GUI. With this fix the Instrument view should show up normally.

Fixes #16735.

### CODE REVIEW

File: Framework/Geometry/src/Objects/Object.cpp [hunk 1]
```diff
@@ -1647,20 +1647,19 @@ void Object::calcBoundingBoxByGeometry() {
...
-    auto dz = vectors[4] - lf;
-
-    minX = std::min(lf.X(), lb.X());
-    maxX = std::max(rb.X(), rf.X());
-    minY = lb.Y();
-    maxY = rf.Y();
-    minZ = 0;
-    maxZ = dz.Z();
+    // These will be replaced by more realistic values in the loop below
+    minX = minY = minZ = std::numeric_limits<decltype(minZ)>::max();
```
Comment (LamarMoore) [inline Framework/Geometry/src/Objects/Object.cpp]: Good

File: Framework/Geometry/test/ObjectTest.h [hunk 2]
```diff
@@ -811,7 +811,7 @@ class ObjectTest : public CxxTest::TestSuite {
     // See
     // http://docs.mantidproject.org/nightly/concepts/HowToDefineGeometricShape.html#hexahedron
     Hexahedron hex;
-    hex.lbb = V3D(0, 0, 0);
+    hex.lbb = V3D(0, 0, -2);
```
Comment (LamarMoore) [inline Framework/Geometry/test/ObjectTest.h]: This is sensible, adjusting the limits to include negative portions of the z axis for checking the bounding box calculation. Good stuff.

**Comment by LamarMoore** [comment]
Looks good to me :shipit:
