### PR TITLE
Fix PointData/Histogram conversion of RebinnedOutput

### LINKED ISSUE #33937: Monments still giving NAN's
The moments tab of indirect's reduction GUI is giving NAN's for everything except the first moment. It looks like this is caused by https://github.com/mantidproject/mantid/blob/main/Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SofQWMoments.py#L141

**Describe the bug**

1. Open Indirect->reduction
2. In the energy transfer tab use run `26176`
3. Press run
4. Go to the S(Q, w) tab
5. Change from file to workspace and select the one you just made
6. Tick the rebin in energy option
7. Set E Low to -0.5
8. Set E High to 0.5
9. Press run
10. Go to the moments tab
11. Change from file to workspace and select the one you just made
12. Press run -> a single line will appear. Inspecting the data from the ADS shows that the other spectra are all NAN's

**Expected behavior**

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: [e.g. Windows, RHEL 7, Ubuntu, macOS]
 - OS Version:
 - Mantid Version [e.g. 6.0.0]

**Additional context**

### PR DESCRIPTION
**Pull request by mducle**
**Description of work.**

This PR makes the routines which convert to/from histogram/point data understand the `RebinnedOutput` type which carries bin fractions as well as bin frequencies. Now when these are converted to point data the fractions are set to unity.

It also reverts `SofQWMoments` to the original code/flow, and fixes the changes to `Integration` for the `RebinnedOutput` types introduced in #33408 . `SofQWMoments` relies on multiplication of the signals as points rather than bins and hence converts the data from histograms to points for a some of its processing. During this conversion, because `XDataConverter` is not aware of the bin fractions arising from the fractional rebinning algorithm `SofQW3` which produces the `RebinnedOutput` type it discards them (sets them to zero) which then causes the new `Integration` routine which _is_ aware of them to output `NaN`s because it uses the fractions to normalise the output data (as described in the issue #33407 which PR #33408 fixes).

`RebinnedOutput` types are only created by `SofQW3` and this output is always a histogram. Hence any call to `XConvertData` on this is either: 1) from `ConvertToPointData` called on the output of `SofQW3` or 2) `ConvertToHistogram` called on the output of `ConvertToPointData` from the output of `SofQW3`. Since fractional bin weights make no sense when we are discarding the bin information in `ConvertToPointData`, this PR sets all the fractional weights to unity (which effectively restores the behaviour of `Integration` to what it was before PR #33408).

The PR also reverts all the changes in PR #33798 (including changes to the test data) which was a Python-only fix of this issue by removing some of the `ConvertToPointData` calls - however it seems that these are necessary for `SofQWMoments` to function.

**To test:**

Make sure unit tests of `SofQWMoments` pass. Run `SofQWMoments` on some test data and make sure the output matches that from Mantid 6.2 or earlier versions.

Fixes #33937. 

Release notes and other documentation to follow.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by AnthonyLim23 — DISMISSED** [review]
Looks good to me. It produces the same results as previous versions of Mantid.

**Comment by Harrietbrown** [comment]
Good work, it matches the output for 6.1 perfectly.

File: Framework/Algorithms/src/XDataConverter.cpp [hunk 1]
```diff
@@ -61,6 +65,12 @@ void XDataConverter::exec() {
   if (inputWS->axes() > 1)
     outputWS->replaceAxis(1, std::unique_ptr<API::Axis>(inputWS->getAxis(1)->clone(outputWS.get())));
 
+  bool isRebinnedWorkspace = inputWS->id() == "RebinnedOutput";
+  RebinnedOutput_sptr outRB = std::dynamic_pointer_cast<RebinnedOutput>(outputWS);
+  // Force fractions to unity (converting from histo to point discards bin info).
+  MantidVecPtr outF;
+  outF.access().resize(inputWS->getNumberBins(0), 1.0);
```
Comment (DannyHindson) [inline Framework/Algorithms/src/XDataConverter.cpp:72]: Couple of things relating to these few lines:
- the number of bins could in theory be different on each spectra so please can you move the declaration\initialisation of outF into the loop so you can call getNumberBins(i)? I appreciate this doesn't happen v often but since this is a very commonly used algorithm it's worth doing I think
- Please can you check outRB isn't empty before it's used? Just add `if (outRB)` before it's used below. We run Coverity scans on the code outside of Jenkins and it will flag this up

**Review by DannyHindson — CHANGES_REQUESTED** [review]

File: Framework/Algorithms/src/XDataConverter.cpp (hunk 1 above)
Comment (AnthonyLim23) [reply Framework/Algorithms/src/XDataConverter.cpp:72]: for the second point I assume you mean to check its not None?

File: Framework/Algorithms/src/XDataConverter.cpp [hunk 2]
```diff
@@ -69,17 +69,19 @@ void XDataConverter::exec() {
   RebinnedOutput_sptr outRB = std::dynamic_pointer_cast<RebinnedOutput>(outputWS);
   // Force fractions to unity (converting from histo to point discards bin info).
   MantidVecPtr outF;
+  // need this line to prevent a hard crash
```
Comment (DannyHindson) [inline Framework/Algorithms/src/XDataConverter.cpp:72]: I think the declaration of outF needs to be moved into the loop at~L79 as well. At the moment you may have different threads in the parallel if statement lower down resizing the single outF vector to different sizes. If the spectra don't have the same number of bins this will cause a problem. Moving the declaration inside the loop will mean that each thread has its own copy of outF.
If you do this I think you'll be able to remove the extra resize call on L73

**Review by DannyHindson — CHANGES_REQUESTED** [review]

File: Framework/Algorithms/src/XDataConverter.cpp (hunk 2 above)
Comment (DannyHindson) [reply Framework/Algorithms/src/XDataConverter.cpp]: I think Anthony has just done that in his last commit. The code looks fine to me now. Will approve shortly once it's passed a couple more of the jobs

Comment (mducle) [reply Framework/Algorithms/src/XDataConverter.cpp]: Ah, I meant something like:

```
    MantidVecPtr outF;

    // Copy over the Y and E data
    outputWS->setSharedY(i, inputWS->sharedY(i));
    outputWS->setSharedE(i, inputWS->sharedE(i));
    if (isRebinnedWorkspace) {
      outF.access().resize(inputWS->getNumberBins(i), 1.0);
      if (outRB) {
         outRB->setF(i, outF);
      }
    }
```

sorry for messing ip the spacings (writing this on my phone)...

Comment (AnthonyLim23) [reply Framework/Algorithms/src/XDataConverter.cpp]: If the first part of an if statement fails for an "and", it does not evaluate the second part (as it fails as a whole anyway)

**Review by Harrietbrown — DISMISSED** [review]
Changes from code review have not broken anything and the processes work perfectly. good job.

File: Framework/Algorithms/src/XDataConverter.cpp (hunk 2 above)
Comment (mducle) [reply Framework/Algorithms/src/XDataConverter.cpp]: Yes, sorry I have misread outRB as outF so rearranged the ifs but its not necessary as you say...

**Review by DannyHindson — APPROVED** [review]
