### PR TITLE
Fix multi dataset fitting bugs

### LINKED ISSUE #24954: Unscripted Testing Multi dataset fitting
1. Read http://www.mantidproject.org/Unscripted_Manual_Testing
1. Comment against this ticket the OS environment you are testing against.
1. Don't spend more than a few hours on the testing as fatigue will kick in.
1. If you find errors in the possibly scant documentation, then correct them.
1. Close the this issue once you are done.

If you find bugs:
* Search to see if an issue already exists
* create an issue if it is new
 * Urgent bugs or crashes should by against the current release, and assigned to a developer, then go and talk to the developer if possible.
 * Less urgent bugs should be against a subsequent release, and assigned if the correct developer is known.

### Specific Notes:

Follow: https://www.mantidproject.org/Fitting_QENS_I(Q,_t)

### PR DESCRIPTION
**Pull request by mantid-roman**
**Description of work.**
Always use the single-dataset fit if only 1 spectrum is fitted.
Remove the crystal field functions from gui dialogs.
Improved handling of workspace groups.

**To test:**
1. Try sequential and simultaneous fitting of a single spectrum. The result should be the same.
2. Check that there are no CrystalField* functions in the Add Function dialog.
3. Check that workspace groups that don't contain matrix workspaces don't show in the Add Workspace dialog.

Fixes #24954

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by soininen** [comment]
Probably out of scope of this PR, but I'll report it here anyway: There is an issue with the 'Fit' button becoming disabled.
1. I created a workspace with
```python
import numpy as np

x = np.linspace(-8, 3, 23)
y = x * x
ws = CreateWorkspace(x, y, NSpec=1)
```

2. Open Interfaces->General->Multi dataset fitting
3. Add workspace ws
4. Add function Background->Polynomial
5. Set n = 2; A2 = 1
6. Fit
7. Change property Fitting from Simultaneous to Sequential
7. Fit

The Fit button becomes disabled and stays that way even if the parameters or properties change making it difficult try again.

**Comment by mantid-roman** [comment]
I'll have a look

File: Framework/API/src/FunctionFactory.cpp [hunk 1]
```diff
@@ -361,6 +363,23 @@ void FunctionFactoryImpl::addTie(IFunction_sptr fun,
...
+std::vector<std::string> FunctionFactoryImpl::getFunctionNamesGUI() const {
+  auto &allNames = getFunctionNames<IFunction1D>();
+  std::vector<std::string> names;
+  names.reserve(allNames.size());
+  auto excludes =
+      Kernel::ConfigService::Instance().getString("curvefitting.guiExclude");
+  Kernel::StringTokenizer tokenizer(excludes, ";",
+                                    Kernel::StringTokenizer::TOK_TRIM);
+  std::set<std::string> excludeList(tokenizer.begin(), tokenizer.end());
+  for (auto &name : allNames) {
```
Comment (soininen) [inline Framework/API/src/FunctionFactory.cpp]: I was just fixing some `cppcheck` 1.87 warnings, and here I think it would tell one to use `std::copy_if` instead of the raw loop. Maybe it is worth trying?
```c++
std::copy_if(allNames.cbegin(), allNames.cend(), std::back_inserter(names), [&excludeList](const auto &name) {
  return excludedList.count(name) == 0
});
```

File: qt/scientific_interfaces/MultiDatasetFit/MDFAddWorkspaceDialog.cpp [hunk 2]
```diff
@@ -89,6 +72,59 @@ void AddWorkspaceDialog::selectAllSpectra(int state) {
...
+          hasMatrixWorkspace = true;
+          break;
+        }
+      }
+      if (hasMatrixWorkspace) {
+        workspaceNames << QString::fromStdString(*name);
+      }
+    }
+  }
+  workspaceNames.sort();
```
Comment (soininen) [inline qt/scientific_interfaces/MultiDatasetFit/MDFAddWorkspaceDialog.cpp]: Excuse my ignorance, but are the names not sorted by the call to `ADS.getObjectNames(Mantid::Kernel::DataServiceSort::Sorted)` already?

File: qt/scientific_interfaces/MultiDatasetFit/MDFAddWorkspaceDialog.cpp [hunk 3]
```diff
@@ -89,6 +72,59 @@ void AddWorkspaceDialog::selectAllSpectra(int state) {
...
+    m_maxIndex = static_cast<int>(mws->getNumberHistograms()) - 1;
+  } else {
+    auto grp = getWorkspaceGroup(wsName);
+    if (grp) {
+      int maxIndex = std::numeric_limits<int>::max();
+      for (auto ws : grp->getAllItems()) {
+        auto mws = boost::dynamic_pointer_cast<MatrixWorkspace>(ws);
+        if (mws) {
+          auto n = static_cast<int>(mws->getNumberHistograms()) - 1;
+          if (n < maxIndex) {
```
Comment (soininen) [inline qt/scientific_interfaces/MultiDatasetFit/MDFAddWorkspaceDialog.cpp]: `maxIndex = std::min(maxIndex, n)` could be more compact.

**Review by soininen — CHANGES_REQUESTED** [review]
Fitting a single histogram workspace using Multi dataset fit works; both simultaneous and sequential fits give the same results. Workspace groups without matrix workspaces don't show up in the combo box. The code changes look good in general, although I wonder if it would be possible to implement some tests for the new `FunctionFactoryImpl::getFunctionNamesGUI`? Also, has this been an issue in the previous release? If so, maybe release notes should be updated as well?

**Review by soininen — DISMISSED** [review]

**Comment by soininen** [comment]
Great work. Thanks for fixing the Fit button issue as well!
