### PR TITLE
Fix access violation in MonteCarloAbsorption

### LINKED ISSUE #29624: Access violation in MonteCarloAbsorptionTest
MonteCarloAbsorptionTest occasionally crashes on Windows during the unit tests on Jenkins. This issue is to find and fix the source of the problem
The error message in the console output from Jenkins is:

Running 16 tests.......Access violation

The number of dots (7) in the message gives an indication of which test in the suite it was processing when the access violation happened. It suggests it happened during the 8th unit test in MonteCarloAbsorptionTest.h which is test_Lambda_StepSize_Two_Linear_Interpolation

The interpolation functionality in MonteCarloAbsorption has been updated during the 5.1 release cycle

I have been able to reproduce this locally in debug mode. The access violation happens in MonteCarloAbsorptionTest.h in this line:
outputWS->e(0).front()
or
outputWS->y(0).front()

The e(0) and y(0) vectors are occasionally empty. They appear to become empty somewhere in MonteCarloAbsorption::doSimulation within the multithreaded section
It's always the 0th histogram that has empty y or e for some reason
Seems like some part of the interpolation code in MonteCarloAbsorption.cpp isn't threadsafe

### PR DESCRIPTION
**Pull request by DannyHindson**
**Description of work.**

The unit test suite MonteCarloAbsorptionTest has occasionally been failing on Windows with an access violation on Jenkins. I've been able to track this down to the test Lambda_StepSize_Two_Linear_Interpolation which was failing

I can reproduce this locally (even in a debug build) by modifying the test to repeat 1000 times and it eventually fails. Although the access violation occurs in a couple of different places:
a) the y() or e() vector in the 0th histogram is sometimes empty once the MonteCarloAbsorption algorithm completes which causes some of the test asserts to fall over because they assume y(0).front() or e(0).front is valid
b) sometimes the code in MonteCarloAbsorption.cpp itself has an access violation when yIndexOfX on ~L404 returns an index out of range of the histogram

Both problems happen in the multi-threaded code in MonteCarloAbsorption::doSimulation and it seems to be the interaction between the call to MatrixWorkspace::yIndexOfX and the code that updates a histogram with interpolated results via MatrixWorkspace::setHistogram. Something in these two functions isn't threadsafe. I found that yIndexOfX calls IsHistogramData() which checks the 0th histogram in the workspace even if the MonteCarloAbsorption code is processing the 1st, 2nd etc workspace. I think if the 0th histogram is in the process of being updated by another thread then yIndexOfX can fail or else the setHistogram call fails.

I have done two changes:
- only call yIndexOfX once (there was a redundant 2nd call)
- I have modified yIndexOfX so it takes an additional histogram index parameter. This allows me to keep each MonteCarloAbsorption thread interacting with a single histogram only. I have defaulted the new parameter to zero so other
code behaves as before

Don't know why this only happened on Windows

**To test:**

The problem isn't v easy to reproduce so mainly a case of just doing a code review. 

You can encourage it to happen by changing the code in MonteCarloAbsorptionTest to run the test 1000 times as follow (but maybe changing the code isn't normally within scope of PR testing so this is optional). This change drops the test_ prefix off the actual test method and adds a new test_ method that loops 1000 times:

```
  void test_Lambda_StepSize_Two_Linear_Interpolation() {
    for (int i = 0; i < 1000; i++) {
      Lambda_StepSize_Two_Linear_Interpolation();
    }
  }

  void Lambda_StepSize_Two_Linear_Interpolation() {
etc....
```

If you do this change then you should see an access violation before these code changes and no access violation after. May need to run the test a few times to see the access violation even with the for loop in place. I suggest you do a Release build because some of the tests in this suite are significantly slower in a Debug build.

Fixes #29624 .

*This does not require release notes* because **it has no functional impact**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/API/src/MatrixWorkspace.cpp [hunk 1]
```diff
@@ -1051,18 +1051,19 @@ void MatrixWorkspace::setDistribution(bool newValue) {
  *  Whether the workspace contains histogram data
  *  @return whether the workspace contains histogram data
  */
-bool MatrixWorkspace::isHistogramData() const {
+bool MatrixWorkspace::isHistogramData(const std::size_t index) const {
```
Comment (martyngigg) [inline Framework/API/src/MatrixWorkspace.cpp:1054]: Nice explanation of the issue and I see what is happening now.

The only thing I'm slightly uncomfortable with here is that as this is part of the public API it suggests that it might be possible for each index to return a different answer to this question when in fact we use in quite a few places the fact that the whole workspace is in either point/histogram mode.

Would we be able to leave the original `bool MatrixWorkspace::isHistogramData() const` method not taking an index but maybe have a private method that accepts an index so that this can be used in `yIndexOfX`? The public method can then just call this with `index==0`?

**Review by martyngigg — CHANGES_REQUESTED** [review]

File: Framework/API/src/MatrixWorkspace.cpp (hunk 1 above)
Comment (DannyHindson) [reply Framework/API/src/MatrixWorkspace.cpp:1054]: It looks to me as though it is possible to create a workspace with histograms having different xmodes using the MatrixWorkspace::setHistogram method so on that basis I was thinking that changing the API was a positive thing. Perhaps this is a loophole though that we don't want to advertise or encourage?

Fine to make the changes but thought I'd double check first

Comment (martyngigg) [reply Framework/API/src/MatrixWorkspace.cpp:1054]: You're right it's a fair point that those set methods do allow you to set arbitrary histograms without checking but those are fairly low level and if we do allow/encourage it I'm a little worried that other places are not set up to cope with it properly. Could preserve the current behaviour for now?

**Review by martyngigg — APPROVED** [review]

File: Framework/API/src/MatrixWorkspace.cpp (hunk 1 above)
Comment (DannyHindson) [reply Framework/API/src/MatrixWorkspace.cpp]: I'll record one comment against this in case there are any more problems in future with the multithreaded section of this algorithm. There's a comment against the function cow_ptr<DataType>::access() which says that the function isn't threadsafe. I wonder if this is what I came across in this issue since the X\Y\E vectors in the histograms are managed as cow ptrs. 

All the threads were only writing to a single histogram even before this PR so it seems like there shouldn't have been a problem. Perhaps the copy on write functionality isn't thread safe? One option might be to lock the mutex higher up outside of the if statement but that may have a negative performance impact

```
template <typename DataType> DataType &cow_ptr<DataType>::access() {
  // Use a double-check for sharing so that we only acquire the lock if
  // absolutely necessary
  if (!Data.unique()) {
    std::lock_guard<std::mutex> lock{copyMutex};
    // Check again because another thread may have taken copy and dropped
    // reference count since previous check
    if (!Data.unique()) {
      std::atomic_store(&Data, std::make_shared<DataType>(*Data));
    }
  }
  return *Data;
}
```
