### PR TITLE
Fix fit browser workspace index bug

### LINKED ISSUE #24457: FitPropertyBrowser has initial workspace index -1
### Expected behavior
If the workspace is set the initial value for the workspace index must be 0.

### Actual behavior
It can be -1

### Steps to reproduce the behavior
1. Indirect->Data Analysis->ConvFit tab
2. Load data
3. Select TeixeiraWater as the fit function
4. Look at the TeixeiraWater parameters. The Q Value and workspaceIndex are very large. The Q value should be around 0.4.

### Platforms affected
All

### PR DESCRIPTION
**Pull request by mantid-roman**
**Description of work.**
Set checks ensuring that workspace index cannot be < 0.

**To test:**
1. Indirect->Data Analysis->ConvFit tab
2. Load data
3. Select TeixeiraWater as the fit function
4. Look at the TeixeiraWater parameters. The Q Value and workspaceIndex are very large. The Q value should be around 0.4.

Fixes #24457 

*This does not require release notes* because the bug is fresh and wasn't in any release.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/widgets/common/src/FitPropertyBrowser.cpp [hunk 1]
```diff
@@ -2473,6 +2437,50 @@ Mantid::API::IFunction_const_sptr FitPropertyBrowser::theFunction() const {
 
 void FitPropertyBrowser::checkFunction() {}
 
+/**
+ * If the current wrkspace index is set to a disallowed value this fuunction
```
Comment (robertapplin) [inline qt/widgets/common/src/FitPropertyBrowser.cpp]: 'workspace' and 'function' typo's

**Review by robertapplin — CHANGES_REQUESTED** [review]
This PR fixes a bug within the Indirect Data Analysis ConvFit interface. The code changes look good. There is a few typo's in one of the comments.

**Review by robertapplin — APPROVED** [review]
