### PR TITLE
Fix multidomainfunctiontest with gsl2

### LINKED ISSUE #16684: CurveFitting MultiDomainFunctionTest fails with GSL2
This unit test `CurveFittingTest.MultiDomainFunctionTest.test_Fit_algorithm` fails sporadically when using GSL2 such as on Ubuntu 16.04. It's hard to reproduce but can be seen [here](http://builds.mantidproject.org/job/master_clean-ubuntu-16.04/119/)

### PR DESCRIPTION
**Pull request by mantid-roman**
The LM optimiser of GSL2 creates the Jacobian matrix but doesn't initialise it with 0s as it is done in GSL1. The fix is to initialise the matrix in MultiDomainFunction. 

**To test:**

Unit tests must pass on gsl2 platforms.

Fixes #16684

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/CurveFitting/test/Algorithms/FitTest.h [hunk 1]
```diff
@@ -1093,15 +1096,14 @@ class FitTest : public CxxTest::TestSuite {
     fit.execute();
     TS_ASSERT(fit.isExecuted());
 
-#if GSL_MAJOR_VERSION < 2
```
Comment (rosswhitfield) [inline Framework/CurveFitting/test/Algorithms/FitTest.h]: You can remove the `#include <gsl/gsl_version.h>` line as well now.

**Comment by rosswhitfield** [comment]
I wonder how many of our other GSL 2 problems have been because of the uninitialized Jacobian matrix.

Anyway, LGTM :+1: I couldn't get this to fail even after running this unit test 100 times. Tested on Ubuntu 16.04 with GSL `2.1` and Arch Linux with GSL `2.2.1` :shipit:

**Comment by mantid-roman** [comment]
@rosswhitfield The functions are usually expected to fill in all of the Jacobian but the MultiDomainFunction in some cases can save a few derivative calls if it knows that it'll be 0. (Un)fortunately this never happens in practice apart from a few unit tests. Usually the jacobian is computed numerically and it means that all elements are evaluated even if they are zero.
