### PR TITLE
Discard the Figure resize event if it has a negative size

### LINKED ISSUE #36179: Exception on IDAaaS ALFView after loading data
**Original reporter:** David Voneshen

**Describe the bug**
There is an error after loading a run number in the ALFView interface in IDAaaS. The same problem does not happen on Windows.

**To Reproduce**
1. Create an IDAaaS ALF powder instance
2. Open Mantid 6.7
3. Go to `Manage User Directories` and set search archive to `all`
4. Open `Direct`->`ALFView` interface
5. Load run 86878 in the sample box
6. There is an exception:
```
File "/opt/mantidworkbench6.7/lib/python3.8/site-packages/matplotlib/backends/backend_qt.py", line 344, in resizeEvent
    self.figure.set_size_inches(winch, hinch, forward=False)
  File "/opt/mantidworkbench6.7/lib/python3.8/site-packages/matplotlib/figure.py", line 2967, in set_size_inches
    raise ValueError(f'figure size must be positive finite not {size}')
ValueError: figure size must be positive finite not [ 1.85714286 -0.03061224 ]
```

**Expected behavior**
There should be no exception. The data should load fine as it does on Windows.

**Platform/Version (please complete the following information):**
 - OS: IDAaaS, Linux

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work**
This PR ensures that a QResizeEvent for a C++ ColorbarWidget is discarded if the size is negative or zero. If either of these is true, matplotlib shows an exception which threatens to terminate Mantid.

The bug is present in InstrumentView as well and should be fixed now.

**To test:**
Follow the instructions in the attached issue

Fixes #36179

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by MohamedAlmaki** [comment]
I tried to run an unstable build in IDaaS instance as instructed in the issue but I got this error: 
> (python:6750): GLib-GIO-ERROR **: 12:41:02.587: Settings schema 'org.gtk.Settings.FileChooser' does not contain a key named 'show-type-column'QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-a1124419'Fontconfig error: Cannot load default config file: No such file: (null)

This is the same error happened to me last time

**Comment by robertapplin** [comment]
> I tried to run an unstable build in IDaaS instance as instructed in the issue but I got this error:
> 
> > (python:6750): GLib-GIO-ERROR **: 12:41:02.587: Settings schema 'org.gtk.Settings.FileChooser' does not contain a key named 'show-type-column'QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-a1124419'Fontconfig error: Cannot load default config file: No such file: (null)
> 
> This is the same error happened to me last time

I think this is an unrelated error. It should be possible to test this on Linux if you have access to a linux machine and then build this branch?

**Comment by MohamedAlmaki** [comment]
I am having trouble connecting to my Linux machine. I will test it once I regain access

**Review by MohamedAlmaki — APPROVED** [review]
No exception is raised. Thanks for the fix

File: qt/widgets/mplcpp/src/ColorbarWidget.cpp [hunk 1]
```diff
@@ -50,6 +51,7 @@ ColorbarWidget::ColorbarWidget(QWidget *parent)
     : QWidget(parent), m_ui(), m_mappable(Normalize(0, 1), getCMap(defaultCMapName())) {
   initLayout();
   connectSignals();
+  m_canvas->installEventFilterToMplCanvas(new FigureEventFilter());
```
Comment (gemmaguest) [inline qt/widgets/mplcpp/src/ColorbarWidget.cpp:54]: Do you know what happens to the ownership of the new event filter? I see it gets passed through to QWidget::installEventFilter but I can't tell whether the QWidget takes ownership of it at that point so I'm concerned it might leak?

File: qt/widgets/mplcpp/src/FigureEventFilter.cpp [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+#include "MantidQtWidgets/MplCpp/FigureEventFilter.h"
+
+#include <QResizeEvent>
+
+namespace MantidQt::Widgets::MplCpp {
+
+bool FigureEventFilter::eventFilter(QObject *obj, QEvent *ev) {
+  if (ev->type() == QEvent::Resize) {
+    auto const size = static_cast<QResizeEvent *>(ev)->size();
+    if (size.width() < 1 || size.height() < 1) {
```
Comment (thomashampson) [inline qt/widgets/mplcpp/src/FigureEventFilter.cpp:16]: FYI, could instead use the `QSize::isEmpty()` function:
https://doc.qt.io/qt-5/qsize.html#isEmpty

**Review by thomashampson — APPROVED** [review]

File: qt/widgets/mplcpp/src/ColorbarWidget.cpp (hunk 1 above)
Comment (robertapplin) [reply qt/widgets/mplcpp/src/ColorbarWidget.cpp:54]: Good point, I've opened a PR to fix this https://github.com/mantidproject/mantid/pull/36204
