### PR TITLE
34486 fix elwin workspace run

### LINKED ISSUE #34486: Incorrect plots as a result of indirect data analysis when loading data as workspaces
**Describe the bug**
When using the `indirect`, `data analysis`, `Elwin` tab to analyse reduce data in the form of a workspace, incorrect `elf` plots are output. This differs to what happens when the data is read in as a file (hence there is a work around)
More specifically:
1. `elf` graph is plotted against `q`, not temperature as expected
2. only 1 line appears on the plot, regardless of the number of groups specified during data reduction.
3. Plot appears to be a bin plot, as opposed to a spectra plot.

Edit: Bug was present in 6.4.0 

**To Reproduce**
1.  Make sure you have access to the ISIS data archive
2. Open the `data reduction` interface via interfaces > indirect > data reduction.
3. Input runs `26173-26174`, enter to load.
5. Under `detector grouping`, set the grouping to `groups`
6. Set the `Number of Groups` to be `3`
7. Click `Run`
8. Two workspaces are generated, save these workspaces using File > Save Project (to be used later)
9. Open the `data analysis` interface via interfaces > indirect > data analysis
10. On the `Elwin` tab, tab over to `workspace` and add to two generated workspaces, selecting `All Spectra`
11. Click Run
12. Right click on the new workspace created that is appended `elf`
13. Observe that you can only plot as a bin plot, do so.
14. Observe the x axis is `q` - it is expected to be temperature
15. Observe there is only 1 line, not the 3 expected. Plot is named after only the first spectra
16. Clear all mantid workspaces
17. On the `Elwin` tab, tab back over to `File`, loading the previously saved files
18. Repeat steps `12-14` and observe correct behaviour (note that for this dataset the y axis for `elf` is run No, I believe as the data does not have temperature logged)

**Below images should be the same:**

image

### LINKED ISSUE #34639: Elwin loading processes are different when loading workspaces from loading files
In the indirect elwin tab we have an option for loading from files and loading from workspaces. these use different process that mean some data is lost. this issue is to locate the differences and make them the same.

### PR DESCRIPTION
**Pull request by Harrietbrown**
**Description of work.**

Thsi PR fixes a bug in the Elwin interface that cause it to not process spectra added through the workspace input method properly. instead it only ran for a single selected workspace for all spectra instead of only the spectra chosen from multiple workspaces.

**To test:**

Repeat steps to recreate from the initial issue. test that the plots look as expercted.

Fixes #34486
Fixes #34639

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by SilkeSchomann** [comment]
I've been following the instructions from the initial issue with a small modification for step 8 (Open the data analysis interface via interfaces > indirect > data analysis) as Elwin is now part of the new Data Manipulation interface in the Inelastic category. When I open Data Manipulation though these error messages appear:

image

**Review by SilkeSchomann — DISMISSED** [review]
Code looks good and it works as expected 👍

File: qt/scientific_interfaces/Indirect/InelasticDataManipulationElwinTab.cpp [hunk 1]
```diff
@@ -201,19 +202,25 @@ void InelasticDataManipulationElwinTab::runWorkspaceInput() {
...
-  m_model->setupElasticWindowMultiple(m_batchAlgoRunner, m_view->getCurrentPreview(), inputGroupWsName,
+  m_model->setupElasticWindowMultiple(m_batchAlgoRunner, "ELWIN_workspace_output", inputGroupWsName,
                                       m_view->getLogName(), m_view->getLogValue());
 
   connect(m_batchAlgoRunner, SIGNAL(batchComplete(bool)), this, SLOT(unGroupInput(bool)));
   m_batchAlgoRunner->executeBatchAsync();
 
   // Set the result workspace for Python script export
-  m_pythonExportWsName = (m_view->getCurrentPreview() + "_elwin_eq2").toStdString();
+  m_pythonExportWsName = "ELWIN_workspace_output_elwin_eq2";
```
Comment (martyngigg) [inline qt/scientific_interfaces/Indirect/InelasticDataManipulationElwinTab.cpp:223]: Can I just double check that it's correct that this is hardcoded with a fixed string?

Comment (Harrietbrown) [reply qt/scientific_interfaces/Indirect/InelasticDataManipulationElwinTab.cpp:223]: Yes when outputing via workspace input that output is hardcoded

Comment (SpencerHowells) [reply qt/scientific_interfaces/Indirect/InelasticDataManipulationElwinTab.cpp:223]: @Harrietbrown @martyngigg Shouldn't have the instrument & runnumber etc?

Comment (Harrietbrown) [reply qt/scientific_interfaces/Indirect/InelasticDataManipulationElwinTab.cpp:223]: There can be potentially multiple run numbers or instruments as they can be selected together in the input

Comment (martyngigg) [reply qt/scientific_interfaces/Indirect/InelasticDataManipulationElwinTab.cpp:223]: What was `m_view->getCurrentPreview()` returning before?

Comment (Harrietbrown) [reply qt/scientific_interfaces/Indirect/InelasticDataManipulationElwinTab.cpp:223]: it was the workspace that was in the preview plot

Comment (martyngigg) [reply qt/scientific_interfaces/Indirect/InelasticDataManipulationElwinTab.cpp:223]: So the name was misleading as it could contain inputs from multiple workspaces yet the name suggested a single source? Is this name only used if you generate a script from Python so in that case it's easy for someone to change to something more meaningful?

Comment (Harrietbrown) [reply qt/scientific_interfaces/Indirect/InelasticDataManipulationElwinTab.cpp:223]: What do you mean if they generate it from python? do you mean if they get the workspace history of the output?

Comment (martyngigg) [reply qt/scientific_interfaces/Indirect/InelasticDataManipulationElwinTab.cpp:223]: I was just thinking of the name of the variable and whether it was linked to something that is output to a script? Isn't there a button on the interface to generate one?

Comment (Harrietbrown) [reply qt/scientific_interfaces/Indirect/InelasticDataManipulationElwinTab.cpp:223]: There isn;t a button to generate a script in elwin

Comment (martyngigg) [reply qt/scientific_interfaces/Indirect/InelasticDataManipulationElwinTab.cpp:223]: Ah okay. Could we rename this variable to avoid the confusion?

Comment (Harrietbrown) [reply qt/scientific_interfaces/Indirect/InelasticDataManipulationElwinTab.cpp:223]: Which variable? do you mean set the name for the suffix before using it for the name?

Comment (martyngigg) [reply qt/scientific_interfaces/Indirect/InelasticDataManipulationElwinTab.cpp:223]: I was more meaning `m_pythonExportWsName` feels like it is suggesting it is used in Python somehow but if it's not can we make it clearer what it is used for?

Comment (Harrietbrown) [reply qt/scientific_interfaces/Indirect/InelasticDataManipulationElwinTab.cpp:223]: is used in all of the indirectTabs where a python export is used. it would not be simple to replace that for all of them. currently it also works for all the other outputs whenever it is needed.

Comment (martyngigg) [reply qt/scientific_interfaces/Indirect/InelasticDataManipulationElwinTab.cpp:223]: Okay. I'll defer to @AnthonyLim23 & @MohamedAlmaki for the future to decide where to take this so we can hand this over before you go. Thanks.
