### PR TITLE
Populate OutputWorkspace with LHSWorkspace value if available

### LINKED ISSUE #34787: Populate OutputWorkspace with LHS workspace instead of RHS if possible
**Original reporter:**
Liliana De Campo

**Describe the bug**
Population the output workspace name in an algorithm dialog with a LHS and RHS workspace will populate using the RHS workspace. It probably makes more sense to populate using the LHS workspace.

**To Reproduce**

For example
1. Open the Minus algorithm dialog
2. Enter a LHS and RHS workspace
3. Click the populate output workspace name button
4. It populates using the RHS workspace, but it probably makes more sense to use the LHS workspace.

**Expected behavior**
The LHS workspace name should be copied instead of the RHS workspace.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by jhaigh0**
**Description of work**

In certain algorithm dialogues (such as `Subtract`) the properties are `LHSWorkspace` and `RHSWorkspace`. When clicking the button to populate the `OutputWorkspace` property field, `LHSWorkspace` should be chosen always so the syntax is the same as `a = a - b`.
This is already done for algorithms with the property `InputWorkspace`.

**Summary of work**
Added a second check to choose any property called `LHSWorkspace`.

**To test:**

- Load or create two workspaces
- Open the `Subtract` algorithm dialogue (you could also try `Plus`, `Divide` etc)
- Set LHS and RHS workspace inputs to be different values, every time you click the button to populate the `OutputWorkspace` filed, it should be the LHS value

Fixes #34787 

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

File: qt/widgets/common/src/AlgorithmPropertiesWidget.cpp [hunk 1]
```diff
@@ -279,6 +279,12 @@ bool isCalledInputWorkspace(PropertyWidget *const candidate) {
   return propertyName == "InputWorkspace";
 }
 
+bool isCalledLHSWorkspace(PropertyWidget *const candidate) {
+  Mantid::Kernel::Property const *const property = candidate->getProperty();
+  const std::string &propertyName = property->name();
+  return propertyName == "LHSWorkspace";
```
Comment (robertapplin) [inline qt/widgets/common/src/AlgorithmPropertiesWidget.cpp:285]: I think it might be possible to have a slight speed-up here if we put this line in the function above e.g. 
```suggestion
  return propertyName == "InputWorkspace"   || propertyName == "LHSWorkspace";
```

as we wouldn't need to call `getProperty` and `name` twice whenever we open the algorithm dialog. We could then just call one of the functions, and change the function name

File: qt/widgets/common/src/AlgorithmPropertiesWidget.cpp [hunk 2]
```diff
@@ -312,10 +318,11 @@ void AlgorithmPropertiesWidget::replaceWSClicked(const QString &propName) {
       // Choose from candidates, only do this if there are candidates to select
       // from.
       if (candidateReplacementSources.size() > 0) {
-        CollectionOfPropertyWidget::iterator selectedIt = std::find_if(
-            candidateReplacementSources.begin(), candidateReplacementSources.end(), isCalledInputWorkspace);
+        CollectionOfPropertyWidget::iterator selectedIt =
+            std::find_if(candidateReplacementSources.begin(), candidateReplacementSources.end(),
```
Comment (robertapplin) [inline qt/widgets/common/src/AlgorithmPropertiesWidget.cpp:322]: We can refactor this existing code to use const iterators e.g.

```suggestion
        const auto selectedIt =
            std::find_if(candidateReplacementSources.cbegin(), candidateReplacementSources.cend(),
```

**Review by robertapplin — CHANGES_REQUESTED** [review]
Looks good and works really well, just had a few suggestions

**Review by robertapplin — APPROVED** [review]
Thanks for the changes, looks good to go
