### PR TITLE
LoadMD fix for integrated dimensions

### LINKED ISSUE #17492: LoadMD cannot load workspaces with integrated dimensions
Suppose one has an MD workspace, and integrates one of the dimensions. See the script below.
One would expect to be able to save, then load the resulting workspace.
```
w=CreateMDWorkspace(Dimensions=4, Extents=[-1,1,-1,1,-1,1,-10,10], Names="H,K,L,E", Units="U,U,U,V")
slice=BinMD(InputWorkspace=w, AxisAligned=False, 
BasisVector0='A, r, 1, 0, 0, 0', 
BasisVector1='B, r, 0.5, 1, 0, 0', 
BasisVector2='C, r, 0, 0, 1, 0',  
OutputExtents='-1,1,-1,1,-1,1', OutputBins='200,300,200', NormalizeBasisVectors=False)
SaveMD(slice,'/tmp/test.nxs')
recover=LoadMD('/tmp/test.nxs')
```
The script above yields:
```
Error in execution of algorithm LoadMD:
number of elements in input vector have to be square of some value
```

### PR DESCRIPTION
**Pull request by AndreiSavici**
LoadMD now should be able to load workspaces that have integrated dimensions

**To test:**

See that the script in the original issue is working

Fixes #17492.

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by raquelalvarezbanos** [comment]
Looks good to me: the script ran successfully and running `CompareMDWorkspaces` on the saved and loaded workspaces reveals that they match.

:ship:

File: Framework/MDAlgorithms/src/LoadMD.cpp [hunk 1]
```diff
@@ -650,10 +650,17 @@ CoordTransform *LoadMD::loadAffineMatrix(std::string entry_name) {
...
   m_file->getAttr<int>("columns", inD);
   m_file->closeData();
+  Matrix<coord_t> mat(outD, inD);
+  size_t ic(0);
+  for (size_t i = 0; i < static_cast<size_t>(outD); i++) {
+    for (size_t j = 0; j < static_cast<size_t>(inD); j++) {
+      mat[i][j] = vec[ic];
+      ic++;
+    }
+  }
```
Comment (quantumsteve) [inline Framework/MDAlgorithms/src/LoadMD.cpp]: What do you think about updating or adding a constructor for Rectangular Matrices and using that instead?

http://doxygen.mantidproject.org/nightly/dc/da6/classMantid_1_1Kernel_1_1Matrix.html#a265deafa95ceb2e94950b127f45df08c
