### PR TITLE
Fix column name error in CompareWorkspaces for Peak Workspace

### LINKED ISSUE #31000: Mismatched system test data found when fixing the column name error in CompareWorkspaces for Peak Workspace
> - Original Gitlab task: [SCD271](https://code.ornl.gov/sns-hfir-scse/diffraction/single-crystal/single-crystal-diffraction/-/issues/271)
> - Related branch:   [SCD271_FixColNameErrorInCompareWorkspacesPWS](https://github.com/mantidproject/mantid/tree/SCD271_FixColNameErrorInCompareWorkspacesPWS) 

Several system tests are failing after fixing a bug where the column name was incorrectly set for Peak Workspace in `CompareWorkspaces`, including

## [ReduceOneSCD_Run](https://github.com/mantidproject/mantid/blob/master/Testing/SystemTests/tests/framework/ReduceOneSCD_Run.py)

The error is related to the set tolerance lower than the difference
```
CompareWorkspaces-[Notice] Wavelength
CompareWorkspaces-[Notice] s1 = 0.740069
CompareWorkspaces-[Notice] s2 = 0.740069
CompareWorkspaces-[Notice] std::fabs(s1 - s2) = 1.27904e-07
CompareWorkspaces-[Notice] tolerance = 1e-08
CompareWorkspaces-[Notice] Data mismatch at cell (row#,col#): (0,5)
CompareWorkspaces-[Notice] The workspaces did not match: Data mismatch
CompareWorkspaces-[Notice] CompareWorkspaces successful, Duration 0.00 seconds
```

## [Diffraction_Workflow_Test](https://github.com/mantidproject/mantid/blob/master/Testing/SystemTests/tests/framework/Diffraction_Workflow_Test.py)

The results cached in reference file is different from calculated value (reasons unknown)
```
CompareWorkspaces-[Notice] DSpacing
CompareWorkspaces-[Notice] s1 = 0.701967
CompareWorkspaces-[Notice] s2 = 0.702038
CompareWorkspaces-[Notice] std::fabs(s1 - s2) = 7.09542e-05
CompareWorkspaces-[Notice] tolerance = 1e-08
CompareWorkspaces-[Notice] Data mismatch at cell (row#,col#): (0,8)
CompareWorkspaces-[Notice] The workspaces did not match: Data mismatch
CompareWorkspaces-[Notice] CompareWorkspaces successful, Duration 0.00 seconds
```

## [FindSatellitePeaksTest](https://github.com/mantidproject/mantid/blob/master/Testing/SystemTests/tests/framework/FindSatellitePeaksTest.py)
- FindSatellitePeaksTestFixedNumQ
  The reference file contains a very different number than the one calculated from the system test
```
CompareWorkspaces-[Notice] BinCount
CompareWorkspaces-[Notice] s1 = 60818
CompareWorkspaces-[Notice] s2 = 0
CompareWorkspaces-[Notice] std::fabs(s1 - s2) = 60818
CompareWorkspaces-[Notice] tolerance = 1e-08
CompareWorkspaces-[Notice] Data mismatch at cell (row#,col#): (0,12)
CompareWorkspaces-[Notice] The workspaces did not match: Data mismatch
CompareWorkspaces-[Notice] CompareWorkspaces successful, Duration 0.00 seconds
``` 
- FindSatellitePeaksTestAutoFindQ
  Similar issue as the previous one, the reference file seems to contains a very different data set
```
CompareWorkspaces-[Notice] BinCount
CompareWorkspaces-[Notice] s1 = 60818
CompareWorkspaces-[Notice] s2 = 0
CompareWorkspaces-[Notice] std::fabs(s1 - s2) = 60818
CompareWorkspaces-[Notice] tolerance = 1e-08
CompareWorkspaces-[Notice] Data mismatch at cell (row#,col#): (0,12)
CompareWorkspaces-[Notice] The workspaces did not match: Data mismatch
CompareWorkspaces-[Notice] CompareWorkspaces successful, Duration 0.00 seconds
```

### PR DESCRIPTION
**Pull request by KedoKudo**
**Description of work.**

- Original Gitlab task: [SCD271](https://code.ornl.gov/sns-hfir-scse/diffraction/single-crystal/single-crystal-diffraction/-/issues/271)
- This is #31002 into `master`

The column names of peak workspace defined in `ComapreWorkspaces` are all in lower cases whereas the current Mantid is using Camel cased column names for Peak Workspaces.
This PR fix this issue and will enable `CompareWorkspaces` to check  the content of two input Peak Workpaces instead of only checking the total number peaks.

**To test:**

Use the following code to generate two __different__ peak workspaces
```
ws = CreateSampleWorkspace()
peaks = CreatePeaksWorkspace(InstrumentWorkspace='ws')
peaks2 = CreatePeaksWorkspace(InstrumentWorkspace='ws')
peaks.getPeak(0).setRunNumber(123)
CompareWorkspaces(peaks, peaks2)
```

This PR will allow mantid to distinguish these two instead of treating them as the same.

Fixes #31000. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Algorithms/src/CompareWorkspaces.cpp [hunk 1]
```diff
@@ -1109,10 +1109,10 @@ void CompareWorkspaces::doPeaksComparison(PeaksWorkspace_sptr tws1,
       std::string name = col->name();
       double s1 = 0.0;
       double s2 = 0.0;
-      if (name == "runnumber") {
+      if (name == "RunNumber") {
```
Comment (martyngigg) [inline Framework/Algorithms/src/CompareWorkspaces.cpp:1112]: Thanks for catching and fixing this error. Should we try and protect against further issues in the future by transforming `name` to lower case first and then comparing with all lowercase?

File: Framework/Algorithms/src/CompareWorkspaces.cpp [hunk 2]
```diff
@@ -1124,42 +1124,42 @@ void CompareWorkspaces::doPeaksComparison(PeaksWorkspace_sptr tws1,
...
-      } else if (name == "row") {
+      } else if (name == "Row") {
         s1 = peak1.getRow();
         s2 = peak2.getRow();
-      } else if (name == "col") {
+      } else if (name == "Col") {
         s1 = peak1.getCol();
         s2 = peak2.getCol();
       }
       if (std::fabs(s1 - s2) > tolerance) {
```
Comment (martyngigg) [inline Framework/Algorithms/src/CompareWorkspaces.cpp:1155]: Could we add an `else` that would throw an exception with an unknown name? I think that would be an error if we get one that does not match?

**Review by martyngigg — CHANGES_REQUESTED** [review]

File: Framework/Algorithms/src/CompareWorkspaces.cpp (hunk 2 above)
Comment (KedoKudo) [reply Framework/Algorithms/src/CompareWorkspaces.cpp:1155]: Adding a default "else" here would make the `PeaksWorkspace` a lot less flexible and potentially confusing for the users.  For example, users could add additional columns to an existing PeaksWorkspace to store some metadata or derived values.  Currently this will not affect how PeaksWorkspace function. However, if we add a default case here that will throw an error, we are basically telling the users

- You are not supposed to add any additional columns to an existing peak workspaces since the PeaksWorkspace should have a subset of predefined (allowed) columns.
- You can add new columns in if you try, and Mantid will not try to stop you unless you are trying to use `CompareWorkspaces`

Allowing users to do one thing in one location but not another will lead to confusion, and I believe Mantid should (try to) deliver a consistent messages across all algorithms.

Comment (martyngigg) [reply Framework/Algorithms/src/CompareWorkspaces.cpp:1155]: I must admit I hadn't checked but is it possible to add columns to a `PeaksWorkspace`?

I completely agree that if we can do that then we don't want to make this an error here. Perhaps we could issue a warning instead just so there is something rather than silently slipping through?

Comment (KedoKudo) [reply Framework/Algorithms/src/CompareWorkspaces.cpp:1155]: Yes, `PeaksWorkspace` has a method that will allow one to add a new column to it on the fly
```
pws.addColumn?
Docstring:
addColumn( (ITableWorkspace)self, (str)type, (str)name) -> bool :
    Add a named column with the given type. Recognized types are: int,float,double,bool,str,V3D,long64

addColumn( (ITableWorkspace)self, (str)type, (str)name, (int)plottype) -> bool :
    Add a named column with the given datatype (int,float,double,bool,str,V3D,long64) 
    and plottype (0 = None, 1 = X, 2 = Y, 3 = Z, 4 = xErr, 5 = yErr, 6 = Label).
Type:      method
```

We could add a warning message, but I would recommend setting its level to information (or even debug) so that it does not flood the stdout when users run it.

Comment (KedoKudo) [reply Framework/Algorithms/src/CompareWorkspaces.cpp:1155]: I forgot to mention that `pws` was created with
```
CreatePeaksWorkspace(NumberOfPeaks=3, OutputWorkspace='pws')
```

Comment (martyngigg) [reply Framework/Algorithms/src/CompareWorkspaces.cpp:1155]: Ah yes of course, it extends the table workspace interface. Thanks.

My primary aim with the column name is just to make sure that users don't think a thing is successful when actually it hasn't done what they expected, which is I think what was happening before your fixes here? Do you expect users to see this warning often? Perhaps I am misunderstanding the workflow?

Comment (KedoKudo) [reply Framework/Algorithms/src/CompareWorkspaces.cpp:1155]: Yes, the issue was that `CompareWorkspaces` skipped all columns due to name mismatch, and users (including most developers) were assuming that all columns were compared.

As for the warning messages, if the workflow script users uses have a lot of appended columns, they will see a lot of warning messages on the terminal stating that those columns are not compared. I am inclined to have those warning set to information or debug level so that only developers and experienced users can see them while the rest regular users don't get overwhelmed by the additional information.

Comment (martyngigg) [reply Framework/Algorithms/src/CompareWorkspaces.cpp:1155]: I don't think too many people do this but information level is fine.

**Review by martyngigg — APPROVED** [review]
