### PR TITLE
Fix fitting gui (multidata, muon) crash.

### LINKED ISSUE #19904: Unknown function parameter in fitting
If the user tries to create the following fit the an exception is thrown. 

Start with a product function, then add a flatbackground and a composite function. That should work. If you then add a flat background to the composite function and exception is thrown.

### PR DESCRIPTION
**Pull request by mantid-roman**
Removed references to deleted fitting parameters after a function has been removed.

**To test:**

Instructions for testing in the issue description.

Fixes #19904.

**Release Notes** 

*Does not need to be in the release notes.* because the issue wasn't reported by users.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/CurveFitting/test/CompositeFunctionTest.h [hunk 1]
```diff
@@ -147,6 +147,31 @@ class CompositeFunctionTest : public CxxTest::TestSuite {
         "curvefitting.peakRadius", m_preSetupPeakRadius);
   }
 
+  void test_has_parameter() {
+    auto mfun = boost::make_shared<CompositeFunction>();
+    auto g = boost::make_shared<CurveFittingGauss>();
+    auto g1 = boost::make_shared<CurveFittingGauss>();
+    auto g2 = boost::make_shared<CurveFittingGauss>();
+    auto bk = boost::make_shared<CurveFittingLinear>();
+    auto c = boost::make_shared<CompositeFunction>();
```
Comment (AnthonyLim23) [inline Framework/CurveFitting/test/CompositeFunctionTest.h]: A minor thing, but could we rename these to make them a bit clearer? e.g. gauss instead of g

**Comment by AnthonyLim23** [comment]
When I was testing there was an exception thrown. I added a product function, then a flatbackground, then a composite function and then another flatbackground. Mantid then threw the exception unknown function parameter f0.A0. However, this is only in muon analysis.  

If you click continue then the changes in this PR work as described.

**Review by AnthonyLim23 — APPROVED** [review]
looks good

**Review by AnthonyLim23 — APPROVED** [review]
looks good to me
