### PR TITLE
Move GitHub api keys

### LINKED ISSUE #30356: Improve error message DownloadInstruments
When things go wrong in `DownloadInstruments` and the json file downloaded is zero size, the error message says that it is invalid format. A better message, would be that it is zero length. This should be improved in [DownloadInstrument](https://github.com/mantidproject/mantid/blob/master/Framework/DataHandling/src/DownloadInstrument.cpp#L216-L223) and [GitHubApiHelper](https://github.com/mantidproject/mantid/blob/master/Framework/Kernel/src/GitHubApiHelper.cpp#L101-L105). 

Unfortunately, [`std::filesystem::file_size`](https://en.cppreference.com/w/cpp/filesystem/file_size) doesn't exist in all of the compilers we use so something else should be selected instead (e.g. [`boost::filesystem::file_size`](https://www.boost.org/doc/libs/1_72_0/libs/filesystem/doc/reference.html#file_size)).

### LINKED ISSUE #30357: Remove github api key
The following was sent by our friends at GitHub
```
As a precautionary measure, we have revoked the token. You will need to generate a new token for the app to authenticate to GitHub.
Here are a couple of steps you can do to ensure your account security has not been compromised:
* Review any unauthorized applications, and remove any you don't recognize:
https://docs.github.com/articles/reviewing-your-authorized-integrations/#reviewing-your-authorized-oauth-apps
https://docs.github.com/articles/reviewing-your-authorized-integrations/#reviewing-your-authorized-github-apps
* Review your security log to ensure that no malicious activity has occurred: https://docs.github.com/articles/reviewing-your-security-log/
The commit in question is at https://github.com/mantidproject/mantid/blob/eaf776a0c1d54961b8d470f43a9122b6c69d51f2/Framework/Kernel/CMakeLists.txt
Please feel free to contact us at https://github.com/contact if you have any questions or concerns.
Thanks,
GitHub.com
```

The effect is that `DownloadInstrument` fails. #30347 changes that the code will correctly fall-back to using an unauthenticated connection.

Current design to fix the problem (needs updating):
* Remove the key from it's current location
* Move key to be provided by `ConfigService` as `GitHubToken`. User/system can supply new key through `ConfigService`
* If `ConfigService` doesn't have a token, an empty string will be returned
* `GitHubAPIHelper` will interpret empty string to mean only try unauthenticated web calls
* Default key is inserted in templated file through cmake variable. The variable will be supplied through an environment variable injected during the build. The default key (in cmake) is an empty string.

### PR DESCRIPTION
**Pull request by peterfpeterson**
As described in #30357, github invalidated our API keys, this moves how the keys are shared and inserted into packages. Additionally, this allows for overriding the key via `ConfigService`.

**To test:**

The main way is to turn on debug logging, then run `DownloadInstrument` after configuring `cmake -DGITHUB_AUTHORIZATION_TOKEN=9f1c1acd61ecb87b21ad0382f6b403c8294992c5 .` (rejected old key). This will get the old authorization error back, and fall back to unauthenticated. After that, set `network.github.api_token=unset` in your properties file and see that it only tries unauthenticated access.

Fixes #30356 
Fixes #30357

The version into `ornl-next` is #30565

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Kernel/src/GitHubApiHelper.cpp [hunk 1]
```diff
@@ -47,12 +51,58 @@ std::string formatRateLimit(const int rateLimit, const int remaining,
...
+  }
+
+  // log what the token is and create final string to set in header
+  if (token.empty()) {
+    // only unauthenticated calls
+    g_log.information("Making unauthenticated calls to GitHub");
+    return "";
+  } else {
+    g_log.information("Attempting authenticated calls to GitHub");
+    g_log.debug() << "Using token \"" << token << "\"\n";
```
Comment (martyngigg) [inline Framework/Kernel/src/GitHubApiHelper.cpp:87]: I know this is useful for debugging but do we want to be leaking the token in the logs?

**Review by martyngigg — COMMENTED** [review]
This is a far better implementation that we had and allows us to provide a token without it being in the source code while also allowing a user to override it if necessary.

Just one comment around the logging of the token.

File: Framework/Kernel/src/GitHubApiHelper.cpp (hunk 1 above)
Comment (peterfpeterson) [reply Framework/Kernel/src/GitHubApiHelper.cpp:87]: I wasn't entirely sure myself. I figured that the average person would never see it, but developers can in case of needing to debug a user's system.

**Review by martyngigg — APPROVED** [review]
Looks good to me!
