### PR TITLE
Prevent EqualBinsChecker generating unwanted log messages

### LINKED ISSUE #29750: Lazy generation of doc strings produces errors if workspaces present
The behaviour implemented in #28953 seems to produce errors in certain situations when editing a python script in workbench

image

I noticed this during testing of https://github.com/mantidproject/mantid/pull/29468

To reproduce:
1. Open up workbench
2. Set default facility=ILL, default instrument=D11
3. Run this script which creates a workspace with unequal bins. Note problem nothing to do with SANS this is just a script that generates a workspace with the required properties. The script uses data files in ExternalData/Testing/Data/SystemTest/ILL/D11:
```
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

SANSILLAutoProcess(
    SampleRuns="2889,2885,2881",
    SampleTransmissionRuns="2871",
    BeamRadius="0.1,0.1,0.1",
    TransmissionBeamRadius=0.1,
    TransmissionBeamRuns="2867+2868",
    OutputWorkspace="ws"
)
```
4. Edit the script - doesn't matter what edit. Can add a space somewhere or add a carriage return. This triggers the lazy algorithm initialisation process
5. Observe errors in screenshot above from the EqualBinsChecker.cpp unit - from EqualBinsChecker::validate() to be precise

Based on some early investigation the errors seem to come from the lazy initialization of the doc strings for the ApplyDeadTimeCorr and MaxEnt algorithms. The problem is triggered by two of the workspaces in the workspace group called "ws" (specifically ws_3 and ws_stitched) created by the script I've included above. Don't think it's important they're in a group though

### PR DESCRIPTION
**Pull request by DannyHindson**
**Description of work.**

The EqualBinsChecker class was generating error\warning messages at unusual times if there was a workspace present in the ADS with uneven bins. The messages were generated for example when the user edited a python script for the first time following start of of workbench if a load action had created a workspace with uneven bins or a script had been run that created such a workspace. The reason the editing of a script triggered this is that it runs a lazy algorithm initialisation process that was introduced in #28953

The messages were being triggered from the MaxEnt and ApplyDeadTimeCorr algorithms. I've changed this so when EqualBinsChecker is called from the IValidator it only returns a true\false statement about whether it's valid or not.
The extra behaviour where EqualBinsChecker performs a softer warning check can now only be trigged by explicitly creating an EqualBinsChecker object in an algorithm (as was already done in the FFT algorithm). I have updated the MaxEnt algorithm so it applies this additional check. ApplyDeadTimeCorr only checked for errors so didn't require this extra bit of code

**To test:**

1. Open workbench
2. Load the attached workspace (which has uneven bins)
[ws_3.zip](https://github.com/mantidproject/mantid/files/5392379/ws_3.zip)
3. Edit a python script (any edit will do - this triggers the lazy algorithm initialisation process)
4. Observe that you don't get errors like this any more written to the log

image

5. Open a dialog for the MaxEnt algorithm and validate that the ws_3 workspace isn't available in the dropdown for InputWorkspace
6. Key in ws_3 into input workspace and observe that there is a meaningful error message saying the workspace is invalid because it has unequal bins

Fixes #29750.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Algorithms/inc/MantidAlgorithms/MaxEnt.h [hunk 1]
```diff
@@ -79,6 +79,9 @@ class MANTID_ALGORITHMS_DLL MaxEnt : public API::Algorithm {
                        size_t nspec, const std::vector<double> &result,
                        bool complex, API::MatrixWorkspace_sptr &outWS,
                        bool autoShift);
+  /// Checks the bin spacing is equal
+  void validateBinEdges(std::string wsName,
```
Comment (robertapplin) [inline Framework/Algorithms/inc/MantidAlgorithms/MaxEnt.h:83]: Can this be `const &`?

File: Framework/Algorithms/src/MaxEnt.cpp [hunk 2]
```diff
@@ -259,13 +260,35 @@ void MaxEnt::init() {
                   "The output workspace containing the reconstructed data.");
 }
 
+//----------------------------------------------------------------------------------------------
+/** Revisit bin edge validation to write errors/warnings to the log
+ */
+void MaxEnt::validateBinEdges(std::string wsName,
+                              std::map<std::string, std::string> &messages) {
+  const double warningLevel = 0.01;
+  MatrixWorkspace_sptr ws = getProperty(wsName);
```
Comment (robertapplin) [inline Framework/Algorithms/src/MaxEnt.cpp:269]: Can this be `auto const`?

**Review by robertapplin — CHANGES_REQUESTED** [review]
Code changes look good and the error messages no longer appear. Just a few minor comments

File: Framework/Algorithms/src/MaxEnt.cpp (hunk 2 above)
Comment (DannyHindson) [reply Framework/Algorithms/src/MaxEnt.cpp:269]: It can't be auto because getProperty returns Mantid::Kernel::IPropertyManager::TypedValue which doesn't support the use as a boolean value on the next line. The use of the explicit type is casting it to a shared_ptr. Will change to const though

**Review by robertapplin — APPROVED** [review]
Looks good to me 👍

**Review by martyngigg — COMMENTED** [review]
Nice catch. I think I had seen this once but dismissed it for some reason as being related to what I was doing.
