### PR TITLE
Reduce workspace history duplication

### LINKED ISSUE #23748: Workspace history is excessive
### Actual behavior
Currently when adding many workspaces together in an algorithm that uses the ADSValidator to parse incoming strings of workspace names. All of their combined histories are combined, this can lead to some duplication, regardless of the duplication it can lead to very excessive .nxs file sizes, previously files may have been under a 1mb and now exceed 1.5Gb.

### Steps to reproduce the behavior
Do something with a workspace to create some history, then split that workspace's spectra up to separate workspaces (creating workspaces with identical history), then group the workspaces together again (this will cause their history to copy onto each other).

### Platforms affected
All

### Suggested Fix
Reduce the excessiveness by removing copies by checking the call of the name against the nanosecond of execution and then removing the history of a duplicate.

### PR DESCRIPTION
**Pull request by Pasarus**
**Description of work.**
I accomplished two things. 1. To properly compare the uniqueness of piece of Algorithm history by comparing name and execution date to the nano second, 2. Ensure that it is possible to import and load from files the correct history even though it stores them to the second in current .nxs implementations, this is achieved by assuming the history is complete and correct and in order, it now increments the nanosecond counter by 1 until it is unique and can fit in the std::set

**To test:**
- Run a script that produces a large amount of history for different workspaces and then groups them together a good example is the GEM Focus scripts @SamJenkins1 
- Check the history of the output workspaces and see that their history is correct (may need to look at what your script is doing for this)
- Save out the Group that was made by the script into a nexus
- Load in that group again after clearing the ADS
- Check that the history of the workspaces loaded back in are the same as the previously saved ones

Fixes #23748  

Doesn't require release notes as this effects only the current dev-builds due it being a relatively recent change that causes history to record properly, when utilizing the ADSValidator on a string list of workspaces.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by LowriJenkins — CHANGES_REQUESTED** [review]
The produced histories do not leave information in the correct order, and the order on them is not consistent before and after loading. see the attached txt [files](https://github.com/mantidproject/mantid/files/2468314/Histories.zip)

**Review by LowriJenkins — DISMISSED** [review]

File: Framework/API/inc/MantidAPI/AlgorithmHistory.h [hunk 1]
```diff
@@ -93,6 +80,8 @@ class MANTID_API_DLL AlgorithmHistory {
   }
   /// get the execution count
   const std::size_t &execCount() const { return m_execCount; }
+  /// get the uuid
+  const std::string uuid() const { return m_uuid; }
```
Comment (soininen) [inline Framework/API/inc/MantidAPI/AlgorithmHistory.h]: Why force the return to be `const`? Or is `&` missing?

File: Framework/API/src/WorkspaceHistory.cpp [hunk 2]
```diff
@@ -26,6 +31,25 @@ namespace API {
 namespace {
 /// static logger object
 Kernel::Logger g_log("WorkspaceHistory");
+struct AlgorithmHistorySearch {
```
Comment (soininen) [inline Framework/API/src/WorkspaceHistory.cpp]: Why do these functors need to be `struct`? Wouldn't plain old function suffice?

File: Framework/API/src/WorkspaceHistory.cpp [hunk 3]
```diff
@@ -362,16 +401,24 @@ WorkspaceHistory::parseAlgorithmHistory(const std::string &rawData) {
...
+  // If not legacy version construct normally else Parse in the legacy data
+  if (std::isdigit(date[6])) {
+    Mantid::Types::Core::DateAndTime timeConstruction(date + "T" + time);
+    utc_start = timeConstruction;
+  } else {
+    Poco::DateTime start_timedate;
+    // This is needed by the Poco parsing function
+    int tzdiff(-1);
+    if (!Poco::DateTimeParser::tryParse("%Y-%b-%d %H:%M:%S", date + " " + time,
+                                        start_timedate, tzdiff)) {
```
Comment (soininen) [inline Framework/API/src/WorkspaceHistory.cpp]: Is the time string supposed to be ISO8601? Would `Mantid::Types::Core::DateTimeHelpers::stringIs*` functions be of any help here?

**Review by soininen — CHANGES_REQUESTED** [review]

File: Framework/API/src/WorkspaceHistory.cpp (hunk 2 above)
Comment (Pasarus) [reply Framework/API/src/WorkspaceHistory.cpp]: So the struct definitions are there so I can use them in an std::unordered_set, in comparison with a std::function call in some cases it can be much faster to define them as a struct and thus an operator() function because of inlining. In this case speed comes well before nice looking code as it can have detrimental effects on algorithms such as GroupWorkspaces or really anything that moves large amounts of history. I can only really cite https://stackoverflow.com/questions/25985248/speed-of-bound-lambda-via-stdfunction-vs-operator-of-functor-struct as reasoning here :)

File: Framework/API/inc/MantidAPI/AlgorithmHistory.h (hunk 1 above)
Comment (Pasarus) [reply Framework/API/inc/MantidAPI/AlgorithmHistory.h]: & is missing

File: Framework/API/src/WorkspaceHistory.cpp (hunk 2 above)
Comment (soininen) [reply Framework/API/src/WorkspaceHistory.cpp]: Fair enough. It's better to use functors then.

File: Framework/API/src/WorkspaceHistory.cpp (hunk 3 above)
Comment (soininen) [reply Framework/API/src/WorkspaceHistory.cpp]: For compatibility reasons, then.

**Review by soininen — APPROVED** [review]
