### PR TITLE
Fix bug in CentroidPeaks with EdgePixels option

### LINKED ISSUE #20355: CentroidPeaks does not work with EdgePixels option
Fix bug introduced by pull request #20055

### PR DESCRIPTION
**Pull request by VickieLynch**
Description of work.
Check that results of CentroidPeaks are inside panels.  Fix bug in PeaksWorkspace::removePeaks.

**To test:**
```python
Load(Filename='TOPAZ_3132_event.nxs', OutputWorkspace='TOPAZ_3132_event')
FilterBadPulses(InputWorkspace='TOPAZ_3132_event', OutputWorkspace='TOPAZ_3132_event', LowerCutoff=25)
ConvertToMD(InputWorkspace='TOPAZ_3132_event', QDimensions='Q3D', dEAnalysisMode='Elastic', Q3DFrames='Q_sample', LorentzCorrection=True, OutputWorkspace='TOPAZ_3132_md', MinValues='-25,-25,-25', MaxValues='25,25,25', SplitInto='2', SplitThreshold=50, MaxRecursionDepth=13, MinRecursionDepth=7)
FindPeaksMD(InputWorkspace='TOPAZ_3132_md', PeakDistanceThreshold=0.37680000000000002, MaxPeaks=50, DensityThresholdFactor=100, OutputWorkspace='TOPAZ_3132_peaks')
CentroidPeaks(InPeaksWorkspace='TOPAZ_3132_peaks', InputWorkspace='TOPAZ_3132_event', PeakRadius=4, EdgePixels=20, OutPeaksWorkspace='TOPAZ_3132_peaks')
```
Then open TOPAZ_3132_peaks in MantidPlot.  Should see this error before fix and not after:
centroidpeaks

Fixes #20355 

**Release Notes** 

*Does not need to be in the release notes since fixing bug introduced in this release.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by quantumsteve — CHANGES_REQUESTED** [review]
I verified that the branch avoids the exception shown above.

I'm concerned about moving away from the erase-remove idiom. In #17307, this change makes SCDCalibratePanels about twice as fast.

Lastly, I found a few places where clarity may be improved.

File: Framework/Crystal/src/CentroidPeaks.cpp [hunk 1]
```diff
@@ -355,5 +363,32 @@ void CentroidPeaks::removeEdgePeaks(
...
 }
 
+void CentroidPeaks::sizeBanks(std::string bankName, int &nCols, int &nRows) {
+  if (bankName == "None")
+    return;
+  boost::shared_ptr<const IComponent> parent =
+      inst->getComponentByName(bankName);
+  if (!parent)
+    return;
+  if (parent->type() == "RectangularDetector") {
```
Comment (OwenArnold) [inline Framework/Crystal/src/CentroidPeaks.cpp]: Unfortuantely #20274 isn't quite ready yet, but that would have helped a lot as that provides a `isRectangularBank` method. i,e you could have written.

```cpp
auto index = componentInfo.indexOf(parent->getComponentID());
if(componentInfo.isRectangularBank(index)){
....
}
```
And avoided the string comparison. For the time being, would it be better to define/use a `static const std::string RectangularDetectorType` defined somewhere rather than a temporary string for this comparison?

File: Framework/Crystal/src/CentroidPeaks.cpp [hunk 2]
```diff
@@ -355,5 +363,32 @@ void CentroidPeaks::removeEdgePeaks(
...
+    boost::shared_ptr<const RectangularDetector> RDet =
+        boost::dynamic_pointer_cast<const RectangularDetector>(parent);
+
+    nCols = RDet->xpixels();
+    nRows = RDet->ypixels();
+  } else {
+    std::vector<Geometry::IComponent_const_sptr> children;
```
Comment (OwenArnold) [inline Framework/Crystal/src/CentroidPeaks.cpp]: I'm not entirely sure what is happening here, but this could definitely use some comments. Looks like code to handle "rectangular like" detector banks that are not `RectangularDectectors`?

Have you considered using `ComponentInfo::componentsInSubtree`? and `ComponentInfo::detectorsInSubtree` I think these could probably be used to extract the same nRows, nColumns as you are currently doing.

**Review by OwenArnold — CHANGES_REQUESTED** [review]

File: Framework/DataObjects/src/PeaksWorkspace.cpp [hunk 3]
```diff
@@ -157,19 +157,12 @@ void PeaksWorkspace::removePeaks(std::vector<int> badPeaks) {
...
-  for (int i = 0; index < end; ++index, ++i) {
-    // if index of peak is not in badPeaks
-    if (!std::binary_search(badPeaks.begin(), badPeaks.end(), i)) {
-      // include in result
-      *result = std::move(*index);
-      ++result;
+  for (int i = static_cast<int>(peaks.size()) - 1; i >= 0; i--) {
+    // if index of peak is in badPeaks remove
+    if (std::binary_search(badPeaks.begin(), badPeaks.end(), i)) {
+      removePeak(i);
```
[the remark this answers is not in the document]
Comment (VickieLynch) [reply Framework/DataObjects/src/PeaksWorkspace.cpp]: Done

File: Framework/Crystal/src/CentroidPeaks.cpp [hunk 4]
```diff
@@ -264,8 +270,10 @@ void CentroidPeaks::integrateEvent() {
     // Set pixelID to change row and col
     row = int(rowcentroid / intensity);
     row = std::max(0, row);
+    row = std::min(nRows - 1, row);
```
[the remark this answers is not in the document]
Comment (VickieLynch) [reply Framework/Crystal/src/CentroidPeaks.cpp]: Done

File: Framework/Crystal/src/CentroidPeaks.cpp [hunk 5]
```diff
@@ -264,8 +270,10 @@ void CentroidPeaks::integrateEvent() {
...
     col = int(colcentroid / intensity);
     col = std::max(0, col);
+    col = std::min(nCols - 1, col);
```
[the remark this answers is not in the document]
Comment (VickieLynch) [reply Framework/Crystal/src/CentroidPeaks.cpp]: Done

File: Framework/Crystal/src/CentroidPeaks.cpp [hunk 6]
```diff
@@ -355,5 +363,32 @@ void CentroidPeaks::removeEdgePeaks(
   peakWS.removePeaks(std::move(badPeaks));
 }
 
+void CentroidPeaks::sizeBanks(std::string bankName, int &nCols, int &nRows) {
```
[the remark this answers is not in the document]
Comment (VickieLynch) [reply Framework/Crystal/src/CentroidPeaks.cpp]: Done

File: Framework/Crystal/src/CentroidPeaks.cpp (hunk 1 above)
Comment (VickieLynch) [reply Framework/Crystal/src/CentroidPeaks.cpp]: Removed

File: Framework/Crystal/src/CentroidPeaks.cpp (hunk 2 above)
Comment (VickieLynch) [reply Framework/Crystal/src/CentroidPeaks.cpp]: Done

**Review by quantumsteve — APPROVED** [review]

File: Framework/Crystal/src/CentroidPeaks.cpp [hunk 7]
```diff
@@ -355,5 +360,48 @@ void CentroidPeaks::removeEdgePeaks(
   peakWS.removePeaks(std::move(badPeaks));
 }
 
+void CentroidPeaks::sizeBanks(const std::string &bankName, int &nCols,
+                              int &nRows) {
+  if (bankName == "None")
```
Comment (OwenArnold) [inline Framework/Crystal/src/CentroidPeaks.cpp]: Wouldn't it be easier to tell the nRows by running `compInfo->componentsInSubtree(bankIndex) - compInfo->detectorsInSubtree(bankIndex)`
At least for `RectangularDetectors` that is. For `RectuangularDetectors` I believe that the only non-detectors in the subtree are the `CompAssemblies` forming the columns.

Comment (VickieLynch) [reply Framework/Crystal/src/CentroidPeaks.cpp]: Done

**Review by OwenArnold — APPROVED** [review]
