### PR TITLE
Project Recovery: Handle Legacy checkpoints

### LINKED ISSUE #23739: Project Recovery: Legacy checkpoints cause exceptions
Handle an issue where Legacy project recovery checkpoints are present and remove them on check for load.

### PR DESCRIPTION
**Pull request by Pasarus**
~~ONLY TO BE MERGED AFTER #23737 AND #23638~~

**Description of work.**
I rearranged some of project recovery's code to reduce calculations and added handling for legacy checkpoints, which should stop people getting a pop up at mantid startup asking if you want to terminate.

**To test:**
[computername.zip](https://github.com/mantidproject/mantid/files/2459958/computername.zip)
- Extract this zip into your ~/.mantid/recovery/YOURCOMPUTERNAME directory. (Make sure these files are the only ones there)
- Start mantid
- All these files should dissapear and nothing should pop up for mantid at start for project recovery.

The folder 123 represents a folder with a lock file in it,
The folder 2018-11-01T10-10-11 represents a legacy checkpoint,
The folder 121345 represents an empty folder with no checkpoints inside it.

Fixes #23739. 

This doesn't need release notes as it fixes a bug added after the last release

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by keeeto — COMMENTED** [review]
Can `removeLockedCheckpoints` be removed from the header? Or is it reused elsewhere?

**Comment by Pasarus** [comment]
It should be removable so I have

**Comment by DanNixon** [comment]
@Pasarus You have the wrong issue number in the `Fixes #` annotation.

**Review by DanNixon — CHANGES_REQUESTED** [review]
I tried putting some other nonsense files into the `~/.mantid/recovery/[hostname]/` directory and got different results with every different combination of things I tried.

- Following the  testing instructions exactly gives the outcome you specify
- Adding an empty directory with a text name (e.g. `bbb`) opens the recovery dialog and asks if I want to recover 0 workspaces (citing the legacy recovery point) (all files are removed as expected)
- Adding en empty file gives `ProjectRecovery-[Warning] Project Recovery: Caught exception whilst attempting to check for existing recovery` and leaves files in the `recovery` directory
- Adding both an empty file `aaa` and empty directory `bbb` gives the same error as above
- Adding both an empty file `bbb` and empty directory `aaa` gives the MantidPlot termination dialog, some files and directories are left in the `recovery` directory

File: MantidPlot/src/ProjectRecovery.cpp [hunk 1]
```diff
@@ -794,6 +799,12 @@ void ProjectRecovery::repairCheckpointDirectory() {
                 "mantid has been unable to successfully handle repair so "
                 "checkpoints may be invalid");
   }
+
+  if (vectorToDelete.size() > 0) {
+    g_log.information("Project Recovery: A repair of the checkpoint directory "
+                      "has been perfomed");
+  }
+
   bool recurse = true;
```
Comment (DanNixon) [inline MantidPlot/src/ProjectRecovery.cpp]: Is this `bool` assigned anywhere?

File: MantidPlot/src/ProjectRecovery.cpp [hunk 2]
```diff
@@ -794,6 +799,12 @@ void ProjectRecovery::repairCheckpointDirectory() {
                 "mantid has been unable to successfully handle repair so "
                 "checkpoints may be invalid");
   }
+
+  if (vectorToDelete.size() > 0) {
+    g_log.information("Project Recovery: A repair of the checkpoint directory "
```
Comment (DanNixon) [inline MantidPlot/src/ProjectRecovery.cpp]: This is probably the wrong place to log this, a "repair" would only be complete after the broken directories have been removed.

File: MantidPlot/src/ProjectRecovery.cpp [hunk 3]
```diff
@@ -767,4 +717,102 @@ std::vector<Poco::Path> ProjectRecovery::getRecoveryFolderCheckpointsPR(
   return getRecoveryFolderCheckpoints(recoveryFolderPath);
 }
 
+std::vector<std::string>
+ProjectRecovery::findOlderCheckpoints(const std::string &recoverFolder,
+                                      const std::vector<int> &possiblePids) {
+  // Currently set to a month in microseconds
+  const int64_t timeToDeleteAfter = 2592000000000;
```
Comment (DanNixon) [inline MantidPlot/src/ProjectRecovery.cpp]: `constexpr Poco::Timestamp::TimeDiff timeToDeleteAfter = 1000000 * 60 * 60 * 24 * 30` would be clearer.

**Review by DanNixon — CHANGES_REQUESTED** [review]
The edge cases seem to be handled correctly now, just a few more comments.

File: MantidPlot/src/ProjectRecovery.cpp (hunk 1 above)
Comment (Pasarus) [reply MantidPlot/src/ProjectRecovery.cpp]: Only 2 lines below when passed to the file.remove() function. It's going to be replaced shortly.

File: MantidPlot/src/ProjectRecovery.cpp (hunk 2 above)
Comment (Pasarus) [reply MantidPlot/src/ProjectRecovery.cpp]: That is true :+1:

File: MantidPlot/src/ProjectRecovery.cpp (hunk 3 above)
Comment (Pasarus) [reply MantidPlot/src/ProjectRecovery.cpp]: :+1:

File: MantidPlot/src/ProjectRecovery.cpp (hunk 1 above)
Comment (DanNixon) [reply MantidPlot/src/ProjectRecovery.cpp]: But if it is never assigned apart form here it is pointless being a parameter at all.

File: MantidPlot/src/ProjectRecovery.cpp (hunk 3 above)
Comment (Pasarus) [reply MantidPlot/src/ProjectRecovery.cpp]: Ah, I am unable to compile it as it overflows after the 100000 * 60 * 60, I believe it has to do with how it calculates the expression in the compiler.

File: MantidPlot/src/ProjectRecovery.cpp (hunk 1 above)
Comment (Pasarus) [reply MantidPlot/src/ProjectRecovery.cpp]: Hence why it was removed

File: MantidPlot/src/ProjectRecovery.cpp (hunk 3 above)
Comment (DanNixon) [reply MantidPlot/src/ProjectRecovery.cpp]: Ah yes, you'd have to specify the length otherwise it will assume the default integer width. `constexpr Poco::Timestamp::TimeDiff timeToDeleteAfter(1000000L * 60 * 60 * 24 * 30);` works

Comment (Pasarus) [reply MantidPlot/src/ProjectRecovery.cpp]: :+1:

Comment (Pasarus) [reply MantidPlot/src/ProjectRecovery.cpp]: Even if I turn each one into a long type it throws a warning of overflow on Windows, so I am going to change it back. :(

**Comment by DanNixon** [comment]
Please use an interactive rebase to fix your mistakes from previous commits in the same PR.

**Comment by Pasarus** [comment]
Done :+1:

**Review by DanNixon — DISMISSED** [review]

File: MantidPlot/src/ProjectRecovery.cpp [hunk 4]
```diff
@@ -145,9 +145,14 @@ std::vector<int> orderProcessIDs(std::vector<Poco::Path> paths) {
...
             });
-
   for (auto c : paths) {
-    returnValues.emplace_back(std::stoi(c.directory(c.depth() - 1)));
+    try {
+      returnValues.emplace_back(std::stoi(c.directory(c.depth() - 1)));
+    } catch (std::invalid_argument) {
+      // The folder or file here is not a number (So shouldn't exist) so delete
+      // it recursively
+      Poco::File(c).remove(true);
```
Comment (SimonHeybrock) [inline MantidPlot/src/ProjectRecovery.cpp]: Recursively removing files/directories sounds dangerous. Are we absolutely certain that `paths` never contains anything that may cause this to fail and accidentally remove a home directory, recursively? Can we do some sort of sanity check here?

**Comment by Pasarus** [comment]
@SimonHeybrock and @martyngigg Is the added sanity checks sufficient? or should I add more, as I'd like to get this merged :)

**Comment by Pasarus** [comment]
@mantidproject/gatekeepers This is a reoccuring issue on master and can cause a unhandled exception at startup if not merged. This PR has just been sitting here for a while any chance we can get this merged?

**Review by martyngigg — CHANGES_REQUESTED** [review]
A couple of minor corrections that I'm happy to merge this

File: MantidPlot/src/ProjectRecovery.cpp [hunk 5]
```diff
@@ -145,9 +145,19 @@ std::vector<int> orderProcessIDs(std::vector<Poco::Path> paths) {
...
-
   for (auto c : paths) {
-    returnValues.emplace_back(std::stoi(c.directory(c.depth() - 1)));
+    try {
+      returnValues.emplace_back(std::stoi(c.directory(c.depth() - 1)));
+    } catch (std::invalid_argument) {
+      // The folder or file here is not a number (So shouldn't exist) so delete
+      // it recursively. However perform a sanity check as recursively removing
+      // files is dangerous
+      const auto sanityCheckPath(getRecoveryFolderCheck());
```
[the remark this answers is not in the document]
Comment (Pasarus) [reply MantidPlot/src/ProjectRecovery.cpp]: :+1:

File: MantidPlot/src/ProjectRecovery.cpp [hunk 6]
```diff
@@ -145,9 +145,19 @@ std::vector<int> orderProcessIDs(std::vector<Poco::Path> paths) {
               // Last modified is first!
               return a1.getLastModified() > b1.getLastModified();
             });
-
   for (auto c : paths) {
```
[the remark this answers is not in the document]
Comment (Pasarus) [reply MantidPlot/src/ProjectRecovery.cpp]: Good spot! :+1:

File: MantidPlot/src/ProjectRecovery.cpp [hunk 7]
```diff
@@ -145,9 +145,19 @@ std::vector<int> orderProcessIDs(std::vector<Poco::Path> paths) {
...
-    returnValues.emplace_back(std::stoi(c.directory(c.depth() - 1)));
+    try {
+      returnValues.emplace_back(std::stoi(c.directory(c.depth() - 1)));
+    } catch (std::invalid_argument) {
```
[the remark this answers is not in the document]
Comment (Pasarus) [reply MantidPlot/src/ProjectRecovery.cpp]: Good spot! +1

**Comment by Pasarus** [comment]
Changes have been made

**Review by martyngigg — APPROVED** [review]

**Comment by martyngigg** [comment]
Test failure is unrelated.
