### PR TITLE
Stop hidden workspaces leaking to ADS during `LoadAndMerge` algorithm if run as child

### LINKED ISSUE #39041: ReflectometryISISCreateTransmission creates hidden workspaces if run as a child algorithm
**Describe the bug**
If ran as a child algorithm without an lvalue, `ReflectometryISISCreateTransmission` creates a hidden workspace in the ADS.

For example, ensuring `Show Invisible Workspaces` is selected in workbench settings:
`ReflectometryISISCreateTransmission(InputRuns='POLREF32130', StoreInADS=False)`

Observe a hidden workspace created in the ADS.

I don't think this is the correct behaviour. Child algorithms are routinely those called from other algorithms not via the simpleapi. You'd expect to just be able to be concerned with the scope of the return value, not be concerned about hidden ADS workspaces.

**Expected behavior**
If the algorithm is run as a child algorithm, no workspaces to be stored in the ADS.

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: [e.g. Windows, RHEL 7, Ubuntu, macOS]
 - OS Version:
 - Mantid Version [e.g. 6.0.0]

**Additional context**

### PR DESCRIPTION
**Pull request by MialLewis**
#### Summary of work

This PR ensures that the `LoadAndMerge` algorithm does not output workspaces to the ADS if run as a child algorithm, or the `StoreInADS` keyword set to equal `False`.

This behaviour was causing issues in algorithms down the line where hidden workspaces were being created in the ADS unexpectedly, contrary to specification.

To do this, I have exposed `getAlwaysStoreInADS` to python, and simply remove output workspaces from the ADS at the end of the algorithm. In the short term this is preferable to making changes to `MergeRuns` which would in all likelihood require more widespread changes to other algorithms. See: https://github.com/mantidproject/mantid/pull/39214/files#diff-a2152741e27e12b0ffd8a303849c522241c235238d6a500aef925ec3871b436cR117

Fixes #39041

### To test:

1) From `File` > `Settings` > Turn on `Show Invisible Workspaces`

2) Run the following script (that uses `LoadAndMerge` internally:
```
from mantid.simpleapi import *

ReflectometryISISCalculatePolEff(NonMagInputRuns='POLREF00032130,POLREF00032132', ProcessingInstructions='270-292', BackgroundProcessingInstructions='520-640', MagInputRuns='POLREF00032131,POLREF00032133', MagProcessingInstructions='270-292', MagBackgroundProcessingInstructions='520-640', I0MonitorIndex=2, MonitorIntegrationWavelengthMin=2.5, MonitorIntegrationWavelengthMax=10, IncludeDiagnosticOutputs=True)
```

3) Observe no hidden workspaces leaked to ADS

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

File: Framework/PythonInterface/mantid/api/src/Exports/IAlgorithm.cpp [hunk 1]
```diff
@@ -427,6 +427,9 @@ void export_ialgorithm() {
       .def("setAlwaysStoreInADS", &IAlgorithm::setAlwaysStoreInADS, (arg("self"), arg("do_store")),
            "If true then even child algorithms will have their workspaces "
            "stored in the ADS.")
+      .def("getAlwaysStoreInADS", &IAlgorithm::getAlwaysStoreInADS, arg("self"),
+           "Returns true if child algorithms set tol have their workspaces "
```
Comment (adriazalvarez) [inline Framework/PythonInterface/mantid/api/src/Exports/IAlgorithm.cpp:431]:
```suggestion
           "Returns true if child algorithms set to have their workspaces "
```
Typo in here.

File: Framework/API/src/AnalysisDataService.cpp [hunk 2]
```diff
@@ -167,6 +168,11 @@ Workspace_sptr AnalysisDataServiceImpl::remove(const std::string &name) {
   if (ws) {
     ws->setName("");
   }
+
+  auto group = std::dynamic_pointer_cast<WorkspaceGroup>(ws);
```
Comment (adriazalvarez) [inline Framework/API/src/AnalysisDataService.cpp:172]: why did you add this part on remove?

**Review by adriazalvarez — CHANGES_REQUESTED** [review]
It is working fine, temporary workspaces are not stuck in the ads anymore. 
Just found a typo otherwise looks good.

File: Framework/API/src/AnalysisDataService.cpp (hunk 2 above)
Comment (MialLewis) [reply Framework/API/src/AnalysisDataService.cpp:172]: Previously, If a group workspace was removed from the ADS, it would keep observing ADS notifications.

Let's say the group workspace removed from the ADS contains 4 workspaces stored in the ADS. This means that if one of the workspaces inside the group is removed from the ADS, the group workspaces receives a notification, and that workspace is also removed from the workspace group.

This seems strange to me - I've removed the group workspace from the ADS so I expect a degree of separation.

This behaviour was getting in the way of what I wanted to do. I wanted to remove the group workspace and all the workspaces it contains from the ADS store these as an OutputWorkspace property. This requires keeping the group and the workspaces it contains intact.

**Review by adriazalvarez — DISMISSED** [review]
Thanks for fixing this.

File: Framework/PythonInterface/mantid/api/src/Exports/IAlgorithm.cpp (hunk 1 above)
Comment (adriazalvarez) [reply Framework/PythonInterface/mantid/api/src/Exports/IAlgorithm.cpp:431]: We agreed to correct the typo in a future PR to avoid unncesary CI overload.

File: Framework/PythonInterface/plugins/algorithms/LoadAndMerge.py [hunk 3]
```diff
@@ -199,5 +201,19 @@ def PyExec(self):
...
+    def remove_output_from_ads(self, output_ws_name):
+        remove_ws = [output_ws_name]
+        if self.is_group_ws(output_ws_name):
+            remove_ws.extend(list(mtd[output_ws_name].getNames()))
+        for ws in remove_ws:
+            mtd.remove(ws)
+
+    @staticmethod
+    def is_group_ws(ws_name):
+        return issubclass(type(mtd[ws_name]), WorkspaceGroup)
```
Comment (cailafinn) [inline Framework/PythonInterface/plugins/algorithms/LoadAndMerge.py:216]: I'm not sure if this method is necessary. Given we're already accessing the workspace object through `mtd`, is there a reason not to use `mtd[ws_name].isGroup()`?

File: docs/source/release/v6.13.0/Framework/Algorithms/Bugfixes/39041.rst [hunk 4]
```diff
@@ -0,0 +1 @@
+- Fixes a bug in :ref:`algm-LoadAndMerge` where output workspaces were stored in the ADS when set not to. This caused the leaking of temporary workspaces in algorithms that call :ref:`algm-LoadAndMerge` as a child. Legacy behaviour can be achieved by passing `StoreInADS=True` to the algorithm.
```
Comment (cailafinn) [inline docs/source/release/v6.13.0/Framework/Algorithms/Bugfixes/39041.rst:1]: This is only worth changing if you have to push anyway, but you need to use double backticks for monospace formatting in `.rst` files. (Also applies to the other release note)
```suggestion
- Fixes a bug in :ref:`algm-LoadAndMerge` where output workspaces were stored in the ADS when set not to. This caused the leaking of temporary workspaces in algorithms that call :ref:`algm-LoadAndMerge` as a child. Legacy behaviour can be achieved by passing ``StoreInADS=True`` to the algorithm.
```

**Review by cailafinn — CHANGES_REQUESTED** [review]
Just a quick couple of things to ask before merging:

File: Framework/PythonInterface/plugins/algorithms/LoadAndMerge.py (hunk 3 above)
Comment (MialLewis) [reply Framework/PythonInterface/plugins/algorithms/LoadAndMerge.py]: I don't think so - I just copied this function from elsewhere in Reflectometry.

**Review by cailafinn — APPROVED** [review]
This now looks good to me. Nice fix :shipit:
