### PR TITLE
Fix for transpose issue in ReplicateMD

### LINKED ISSUE #16619: ReplicateMD accessing out of bounds index.
### Expected behavior

Run `MDAlgorithmsTest` without the indexes going out of bounds.

### Actual behavior

During `test_auto_transpose_2d()`, the `targetIndex` exceeds the capacity of the `transposedDataWS`. 

### Steps to reproduce the behavior

1. apply [this patch](https://github.com/mantidproject/mantid/files/314896/ReplicateMD_out_of_range.txt) to master. It fixes another bug where the index wasn't being checked before accessing it, and adds a runtime check to the `m_masks` array. 
2. Build targets `MDAlgorithms` & `MDAlgorithmsTest`.
3. Run  `MDAlgorithmsTest_ReplicateMDTest` and look at exception thrown in `test_auto_transpose_2d()`

### Platforms affected

All

---

I found this while investigating #16583. This particular issue appears to be isolated to ReplicateMD.

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
This PR fixes a bug in the ReplicateMD algorithm. TransposeMD was only applied to the DataWorkspace if it had the same dimensionality as the ShapeWorkspace, i.e. DIM(data) == DIM(shape). In general the dimensionality of the ShapeWorkspace will be larger than the DataWorkspace (for ReplicateMD to make sense) in which case the automatic TransposeMD mechanism had not been applied. 

The automatic TransposeMD check was changed to DIM(data) <= DIM(shape).

Fixes  #16619 
**To test:**

Follow the instructions in #16619 and confirm that the unit tests do not break any longer.

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AntonPiccardoSelg** [comment]
@quantumsteve This PR should fix the issue that was blocking you.

File: Framework/MDAlgorithms/src/ReplicateMD.cpp [hunk 1]
```diff
@@ -293,8 +293,25 @@ void ReplicateMD::exec() {
...
+    // Check that the indices stored in axes are compatible with the
+    // dimensionality of the data workspace
+    const auto numberOfDimensionsOfDataWorkspace = static_cast<int>(nDimsData);
+    int axisDimCounter = 0;
+    for (const auto &axis : axes) {
+      if (axis >= numberOfDimensionsOfDataWorkspace) {
+        std::string message =
+            "ReplicateMD: Cannot transpose the data workspace. Attempting to "
+            "swap dimension index " +
+            std::to_string(axisDimCounter) + " with index " +
```
Comment (quantumsteve) [inline Framework/MDAlgorithms/src/ReplicateMD.cpp]: Can you obtain axisDimCounter with `&axis - axes.data()` or `std::distance(&axis,axes.data())` and remove the counter?

**Comment by AntonPiccardoSelg** [comment]
@quantumsteve Your suggested changes were applied.

**Comment by quantumsteve** [comment]
LGTM :shipit:

File: Framework/MDAlgorithms/src/ReplicateMD.cpp [hunk 2]
```diff
@@ -293,8 +293,23 @@ void ReplicateMD::exec() {
    the linear index -> linear index calculation below will not work correctly.
    */
   MDHistoWorkspace_const_sptr transposedDataWS = dataWS;
-  if (dataWS->getNumDims() == shapeWS->getNumDims()) {
+  if (nDimsData <= nDimsShape) {
     auto axes = findAxes(*shapeWS, *dataWS);
+    // Check that the indices stored in axes are compatible with the
+    // dimensionality of the data workspace
+    const auto numberOfDimensionsOfDataWorkspace = static_cast<int>(nDimsData);
+    for (auto &axis : axes) {
```
Comment (FedeMPouzols) [inline Framework/MDAlgorithms/src/ReplicateMD.cpp]: Could this be `const auto`
