### PR TITLE
Tiled plot does not update if multi fit re-run

### LINKED ISSUE #21775: Tiled plot does not update if multi fit re-run
### Expected behavior
If you re-run a multifit with a tiled plot of the results open the graphs should update

### Actual behavior
They lose all of the curves and go blank

### Steps to reproduce the behavior
1. Run a multi dataset fit (with say 4 datasets)
1. Right click on the output group workspace and create a tiled plot of all the results
1. Run the multi dataset fit again with the same output workspace name
1. The graphs go blank

### PR DESCRIPTION
**Pull request by mantid-roman**
Old output workspaces were being deleted before each fit making graphs to close. These changes delete workspaces only when the number of datasets changes. Plots now update normally.

**To test:**

Run Multi-dataset fitting interface and plot the results. See that the plots update on re-runs.

Fixes #21775

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/scientific_interfaces/MultiDatasetFit/MultiDatasetFit.cpp [hunk 1]
```diff
@@ -773,10 +773,21 @@ void MultiDatasetFit::setParameterNamesForPlotting() {
 /// Remove old output from Fit.
 void MultiDatasetFit::removeOldOutput() {
   auto outWS = m_outputWorkspaceName.toStdString();
-  if (Mantid::API::AnalysisDataService::Instance().doesExist(outWS) &&
-      Mantid::API::AnalysisDataService::Instance()
-          .retrieveWS<Mantid::API::WorkspaceGroup>(outWS)) {
-    Mantid::API::AnalysisDataService::Instance().deepRemoveGroup(outWS);
+  auto &ADS = Mantid::API::AnalysisDataService::Instance();
```
Comment (AnthonyLim23) [inline qt/scientific_interfaces/MultiDatasetFit/MultiDatasetFit.cpp]: could we not do all of the if statements in one go using &&?

**Comment by AnthonyLim23** [comment]
It works for the general multiple fitting GUI. However, the bug still exists in Muon Analysis (instructions below). I think it may be better to make a general solution that other interfaces can call. 

Instructions:
Open Muon analysis and load MUSR00062260
go to the settings tab and make sure multiple fitting is selected 
Go to the data analysis tab and run a fit
Plot a tiled plot of the result
Rerun the fit and the plot goes blank. 

I think the relevant bit of code is:
https://github.com/mantidproject/mantid/blob/master/qt/widgets/common/src/MuonFitPropertyBrowser.cpp#L973 but adding your changes from the MultipleFitting GUI here does not fix it

**Review by AnthonyLim23 — APPROVED** [review]
works for muon and general multi fits
