### PR TITLE
Hexahedron Bounding Box Calculation Fix

### LINKED ISSUE #16106: Bounding Box Calculation for Hexahedral primitives
Currently there seems to be no bounding box calculation for hexahedral primitives:

https://github.com/mantidproject/mantid/blob/master/Framework/Geometry/src/Objects/Object.cpp#L1594

### PR DESCRIPTION
**Pull request by LamarMoore**
There was a bug in the bounding box calculation for hexahedra i.e it wasn't being calculated at all.

Code Review

Fixes #16106 .

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Geometry/src/Objects/Object.cpp [hunk 1]
```diff
@@ -1644,7 +1644,23 @@ void Object::calcBoundingBoxByGeometry() {
       maxZ = std::max(maxZ, vector.Z());
     }
   } break;
-
+  case 2: // HEXAHEDRON
```
Comment (SimonHeybrock) [inline Framework/Geometry/src/Objects/Object.cpp]: There is a comment on the `default:` label below, which says that `2` is a SPHERE. Is the comment wrong, it the `2` here?

File: Framework/Geometry/src/Objects/Object.cpp [hunk 2]
```diff
@@ -1644,7 +1644,23 @@ void Object::calcBoundingBoxByGeometry() {
...
+    auto &lf = vectors[1];
+    auto &lb = vectors[0];
+    auto &rb = vectors[3];
+    auto &rf = vectors[2];
+    auto dz = vectors[4] - lf;
+
+    minX = std::min(lf.X(), lb.X());
+    maxX = std::max(rb.X(), rf.X());
+    minY = lb.Y();
+    maxY = rf.Y();
```
Comment (SimonHeybrock) [inline Framework/Geometry/src/Objects/Object.cpp]: Given the two lines for `minX` and `maxX` above, doesn't this imply that :
```cpp
minY = std::min(lb.Y(), rb.Y());
maxY = std::max(lf.Y(), rf.Y());
```

File: Framework/Geometry/src/Objects/Object.cpp [hunk 3]
```diff
@@ -1644,7 +1644,23 @@ void Object::calcBoundingBoxByGeometry() {
...
+    minZ = 0;
+    maxZ = dz.Z();
```
Comment (SimonHeybrock) [inline Framework/Geometry/src/Objects/Object.cpp]: This implies that the bottom and top plane are always parallel to the x-y plane?

**Comment by SimonHeybrock** [comment]
I am not familiar with this Geometry stuff at all, so my comments above are rather uninformed. Someone else apart from me should have a look, maybe @OwenArnold?

**Comment by NickDraper** [comment]
I've got it

**Comment by NickDraper** [comment]
Yes bounding boxes are always axis aligned for speed and efficiency reasons.

**Comment by NickDraper** [comment]
Is there a reason we don't have any unit tests for this?

**Comment by SimonHeybrock** [comment]
@NickDraper My question was about the alignment of the top and bottom plane of the Hexahedron, not about the planes of its bounding box.

File: Framework/Geometry/src/Objects/Object.cpp (hunk 1 above)
Comment (LamarMoore) [inline Framework/Geometry/src/Objects/Object.cpp]: The comment is wrong, it needs to be changed. However, there is another pull request which uses a scoped enum instead of hard-coded integer values.

**Comment by NickDraper** [comment]
@SimonHeybrock Sorry, my misunderstanding, Hexahedron surfaces can be any orientation, only bounding boxes are axis aligned.

File: Framework/Geometry/src/Objects/Object.cpp (hunk 3 above)
Comment (LamarMoore) [inline Framework/Geometry/src/Objects/Object.cpp]: For the current StructuredDetector implementation, yes.

**Comment by LamarMoore** [comment]
@NickDraper I can create an issue to address the unit tests unless you think I should include them now.

**Comment by NickDraper** [comment]
We have bounding box tests for Sphere and Cylinder, I think we should at least add one for hexahedra in this PR.

**Comment by NickDraper** [comment]
e.g. ObjectTest.h->testGetBoundingBoxForSphere()

**Comment by NickDraper** [comment]
Unit test is good, code quality is good.

:shipit:
