### PR TITLE
Make unsaved changes pop-up appear once in ISIS Reflectometry Polref Interface

### LINKED ISSUE #16250: Unsaved changes warning appears twice when loading new table into Reflectometry (Polref)
This issue was found during unscripted testing of the ISIS Reflectometry (Polref) interface.

### Expected behavior
- User should be asked once whether they want to save or discard their unsaved changes when loading in a new table to the Reflectometry (Polref) interface.

### Actual behavior
- The warning about unsaved changes appears twice.

### Steps to reproduce the behavior
- Go to `Interfaces > Reflectometry > ISIS Reflectometry (Polref)`
- Edit the table in some way
- Attempt to open a new TBL into the Table (Find the INTER TBL file in ISIS-Sample Data)
- See that the warning appears twice in series.

### Platforms affected

All

### PR DESCRIPTION
**Pull request by MattKing06**
In ISIS Reflectometry Polref the user should be asked once whether they want to save or discard their unsaved changes when loading in a new table to the Reflectometry (Polref) interface. However this pop-up was appearing twice if the user chose not to discard their changes.

**To test:**
- Go to `Interfaces > Reflectometry > ISIS Reflectometry (Polref)`
- Import `INTER_NR.TBL` from SampleData-ISIS (`Reflectometry > Import .TBL`)
- Remove all of the rows in the processing table and insert just one row
- Fill in some of the columns in the processing table.
- Go to `Reflectometry > Open Table > Your TBL File`
- See that the unsaved changes warning only appears once.
- Ensure that all other functionality of the TBL regarding loading/saving table still works properly.

Fixes #16250
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: MantidQt/CustomInterfaces/src/Reflectometry/QDataProcessorWidget.cpp [hunk 1]
```diff
@@ -74,7 +74,7 @@ this method is intended to be called by the presenter
 */
 void QDataProcessorWidget::setModel(const std::string &name) {
   m_toOpen = name;
-  m_presenter->notify(DataProcessorPresenter::OpenTableFlag);
+  m_presenter->notify(DataProcessorPresenter::TableUpdatedFlag);
```
Comment (raquelalvarezbanos) [inline MantidQt/CustomInterfaces/src/Reflectometry/QDataProcessorWidget.cpp]: Removing this line should be enough to fix the problem. This way we can keep the original `OpenTableFlag` in the first `setModel()`

**Comment by raquelalvarezbanos** [comment]
Changing the flat to the presenter solved the issued: the warning only appears once now.

:shipit:
