### PR TITLE
Expose workspace readLock to python to prevent segfaults

### LINKED ISSUE #31367: Crash with sliceviewer open on live data
### Expected behavior
You should be able to view live data with sliceviewer

### Actual behavior
Mantid can crash if sliceviewer is open and the live data workspace updates.

### Steps to reproduce the behavior
Must be on IDAaaS with real live data available.
- Open the ISIS Reflectometry interface
- Set the instrument to INTER
- In the Live Data section at the bottom left, set the interval to `1s` and click `Start monitor`
- When the `TOF_live` workspace appears, open sliceviewer on it
- Mantid then crashes pretty quickly afterwards

### Platforms affected
Only seen on IDAaaaS so far.

Reproducible in nightly and v6.0.0 so it is not a new problem, but users are trying to use this right now so it is an important fix.

I've only been able to reproduce this so far with starting it from the reflectometry interface so it's possible it's related to that, but I suspect it is more likely to do with the more complex processing that is done affecting the timing. It seems to work fine without sliceviewer open so it does implicate sliceviewer.

### PR DESCRIPTION
**Pull request by joseph-torsney**
#31367 finds a crash that occurs when running `LoadInstrument` multiple times while the `SliceViewer` is open. This is because, on the first run of `LoadInstrument`, the workspace it is running on changes. The `SliceViewerADSObserver` detects this and begins to draw the view, where it accesses some spectra information on the workspace. While this update has been happening, `LoadInstrument` modifies the same workspace again which leads to a segfault.

This PR exposes workspace `readLock` and `unlock` to the python API so that widgets can lock the workspace while they update themselves.

**To test:**
1. Load some data, e.g. `INTER38417`
2. Open sliceviewer on this workspace
3. Run an algorithm repeatedly that modifies this workspace e.g. by using the following script
```
ws = mtd["INTER38417"]
while True:
    LoadInstrument(Workspace=ws, RewriteSpectraMap=False, InstrumentName="INTER")
``` 
4. Workbench shouldn't crash

Fixes #31367

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Kernel/inc/MantidKernel/DataItem.h [hunk 1]
```diff
@@ -54,6 +54,11 @@ class MANTID_KERNEL_DLL DataItem {
   virtual const std::string toString() const = 0;
   //@}
 
+  /// Acquires a read lock. If another thread currently holds a write lock,
+  /// waits until the write lock is released.
+  void readLock();
```
Comment (martyngigg) [inline Framework/Kernel/inc/MantidKernel/DataItem.h:59]: Can we inline this instead as it's just a pass through, i.e.

```cpp
inline void readLock() { getLock()->readLock(); }
```

File: qt/python/mantidqt/utils/qt/qappthreadcall.py [hunk 2]
```diff
@@ -47,7 +48,10 @@ def __call__(self, *args, **kwargs):
         else:
             self._ensure_self_on_qapp_thread()
             self._store_function_args(args, kwargs)
-            QMetaObject.invokeMethod(self, "on_call", Qt.BlockingQueuedConnection)
+            if self.blocking:
```
Comment (martyngigg) [inline qt/python/mantidqt/utils/qt/qappthreadcall.py:51]: It can be good practice to avoid repetition of the function/method call itself in cases like this and instead just adjust the parameter so that when reading the code it's obvious that only a parameter differs. In this case it's not too bad but for more parameters you need to more carefully read both clauses to see if the other arguments are the same, e.g.
```python
            connection_type = Qt.BlockingQueuedConnection if self.blocking else Qt.AutoConnection
            QMetaObject.invokeMethod(self, "on_call", connection_type)
```

File: qt/python/mantidqt/widgets/sliceviewer/presenter.py [hunk 3]
```diff
@@ -396,10 +396,13 @@ def refresh_view(self):
         # the meantime, so check it still exists. See github issue #30406 for detail.
         if sip.isdeleted(self.view):
             return
+        ws = self.model._get_ws()
         # we don't want to use model.get_ws for the image info widget as this needs
         # extra arguments depending on workspace type.
-        self.view.data_view.image_info_widget.setWorkspace(self.model._get_ws())
```
Comment (martyngigg) [inline qt/python/mantidqt/widgets/sliceviewer/presenter.py:401]: This is a really nice fix. Just one thing to be careful about when dealing with locks - exceptions. In you Python export methods we use the `ReleaseGlobalInterpreterLock` struct to ensure we always lock the GIL again.
In this case if anything throws an exception after the lock then the unlock won't run. In Python we can use `try...finally` to do something similar to RAII so that the `finally` clause always runs regardless if there is an exception, e.g.
 
```python
ws.readLock()
try:
    self.view.data_view.image_info_widget.setWorkspace(ws)
    self.new_plot()
finally:
    ws.unlock()
```

**Review by martyngigg — DISMISSED** [review]
A neat fix to our race condition problem. Just a couple of suggestions for improving the robustness of the code.

File: Framework/Kernel/inc/MantidKernel/DataItem.h (hunk 1 above)
Comment (joseph-torsney) [reply Framework/Kernel/inc/MantidKernel/DataItem.h:59]: When I do this inline I get `Pointer to incomplete class type is not allowed` on the `getLock()` call. It resolves if I do `include <Poco/RWLock.h>` in this header, but doesn't that mean everything that includes `DataItem.h` will also include this bit of Poco?

Comment (martyngigg) [reply Framework/Kernel/inc/MantidKernel/DataItem.h:59]: Ah yes that's a fair point. Maybe it is better to keep this more encapsulated. Let's leave it as you have it 👍🏻

**Comment by martyngigg** [comment]
Thanks for making those changes. Could you add a snippet of test instructions?

**Comment by joseph-torsney** [comment]
Ah my bad, forgot them while taking it out of draft. Thanks for the review and some good tips!

**Comment by martyngigg** [comment]
It looks like we might still have an issue here. In debug a few iterations of `LoadInstrument` now get through but in release it falls over after first one for me.

**Comment by joseph-torsney** [comment]
Should be fixed now. When `refresh_view` was called by the ADSObserver, it does a `readLock()`. This solved most of the crashes, but the view update is split between this and [`canvas.draw_idle()`](https://github.com/mantidproject/mantid/blob/f9efc92eba5645c0e64484504df53953a485cba0/qt/python/mantidqt/widgets/sliceviewer/view.py#L360). `draw_idle` puts the draw on the qt event loop. Then `refresh_view` unlocks the workspace. While we're waiting for the event loop to get around to the draw, another call to `LoadInstrument` sneaks in and modifies the workspace again, which caused another segfault. 

The solution is to replace `draw_idle` with `draw`, so that it is called immediately within the original `readLock`, and the entire update happens at the same time.

**Review by DanielMurphy22 — APPROVED** [review]
This seems to work in release and debug! Good job!
