### PR TITLE
Sample Transmission Calculator: remove option to change y-axis to logarithmic

### LINKED ISSUE #24981: Sample Transmission Calculator - output plot's y-axis ticks sometimes disappear when changing to log scale
**Original reporter:** hsautessella. 

### Expected behavior
Y-axis ticks should always be displayed in sample transmission calculator's output window.

### Actual behavior
Y-axis ticks disappear when converting y-axis to logarithmic scale. 

### Steps to reproduce the behavior
- In MantidPlot go to `Interfaces`->`General`->`Sample Transmission Calculator`.
- Enter the following settings and click calculate:
image
- Right-click the output plot and change the y-axis to a logarithmic scale.
- The y-axis ticks should disappear.
image

### Platforms affected
Tested on WIndows 10 and Ubuntu 18.04 (VM)

### PR DESCRIPTION
**Pull request by PhilColebrooke**
**Description of work.**
In the Sample Transmission Calculator, the y-axis of the plot would disappear when it was changed from linear to logarithmic. This was because all of the y-axis values were originally less than 1 so the logs would be negative, and negative values are not shown on the plot. Therefore the option to change the Y-Axis has been removed.

**To test:**
1. Go to Interfaces -> General -> Sample Transmission Calculator.
2. Right-click the plot and check that there is no 'Y-Axis' option.

Fixes #24981 
---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/widgets/plotting/src/Qwt/PreviewPlot.cpp [hunk 1]
```diff
@@ -987,3 +987,11 @@ void PreviewPlot::handleAxisTypeSelect() {
   // Update the plot
   emit needToHardReplot();
 }
+
+/**
+ * Removes the Y-Axis option from the context menu as the Sample Transmission
+ * Calculator does not need it.
+ */
+void PreviewPlot::disableYAxisMenu() {
+  m_contextMenu->actions().at(4)->setVisible(false);
```
Comment (DTasev) [inline qt/widgets/plotting/src/Qwt/PreviewPlot.cpp]: This is not very robust - it will break if the order is ever changed for some reason. There's no unit tests for this whole thing, so it won't be detected at all, until someone looks at it.

It should use a more robust approach instead - setting the object name via `menu->setObjectName(<insert_string_here>);`, in the `addOptionsToMenus` function. The string should be a static class variable to make it easier to re-use. Also watch out as the function is used multiple times for different menus - the `menuName` should also be part of the object name!

The main menu `m_contextMenu` can then be queried for this specific object via `m_contextMenu->findChild<QMenu*>(same_name_as_above);`

**Review by dtasev — CHANGES_REQUESTED** [review]

**Comment by DTasev** [comment]
There seems to be conflict in the release notes now

File: qt/widgets/plotting/src/Qwt/PreviewPlot.cpp [hunk 2]
```diff
@@ -987,3 +995,20 @@ void PreviewPlot::handleAxisTypeSelect() {
...
+ * Calculator does not need it.
+ *
+ * @throw Runtime error thrown if the Y Axis action can't be found by its object
+ * name
+ */
+void PreviewPlot::disableYAxisMenu() {
+  auto menu = m_contextMenu->findChild<QAction *>(g_yAxisMenuName);
+
+  if (menu == NULL)
+    throw std::runtime_error("There was a problem with object naming.");
```
Comment (DTasev) [inline qt/widgets/plotting/src/Qwt/PreviewPlot.cpp]: Can this be made more specific, something like "Y-Axis menu object cannot be retrieved"?

**Review by dtasev — CHANGES_REQUESTED** [review]

**Review by dtasev — APPROVED** [review]
Works well. No test can be added as there's no unit tests for this GUI at all, but the object name approach makes this a bit more robust
