### PR TITLE
Norm MD Error with non-intersecting accumulation workspaces

### LINKED ISSUE #25618: NormMD should throw error when accumulating non intersecting regions
### Expected behavior
If attempting accumulating over non-intersecting regions, `NormMD` should throw an error.

### Actual behavior
The algorithm accumulates correctly in the `TemporaryDataWorkspace` but not in the `TemporaryNormalizationWorkspace`.

### Steps to reproduce the behavior
Try accumulating over any two regions in the same run which do not intersect.

### PR DESCRIPTION
**Pull request by sullivanbt**
**Description of work.**
MDNorm now throws errors when trying to accumulate using bins from different regions.

**To test:**
```python
from mantid.simpleapi import *
import numpy as np

MDdata = LoadMD('/SNS/MANDI/shared/ProfileFitting/folding_data/mde/MANDI_mde_sample_9113.nxs')
LoadIsawUB(InputWorkspace=MDdata, Filename='/SNS/MANDI/shared/ProfileFitting/folding_data/beta_lac_july2018_secondxtal.mat')
flux_cdf = Load(Filename='/SNS/users/ntv/Desktop/data_folding/spectra.nxs', OutputWorkspace='flux_cdf')
sa = Load(Filename='/SNS/users/ntv/Desktop/data_folding/MANDI_solidAngle_nomask.nxs', OutputWorkspace='sa')    

qx, qy, qz = [2.41384893046, -0.42977673369, 0.355479910083]
dQ = 0.05
dQPixel = 0.003

#Clear the accumulation workspaces
if mtd.doesExist('dataMD'):
    DeleteWorkspace('dataMD')
if mtd.doesExist('normMD'):
    DeleteWorkspace('normMD')
if mtd.doesExist('result'):
    DeleteWorkspace('result') 
MDNorm(InputWorkspace=MDdata,
       SolidAngleWorkspace='sa',
       RLU=False,
       FluxWorkspace='flux_cdf',
       QDimension0='1,0,0',
       QDimension1='0,1,0',
       QDimension2='0,0,1',
       Dimension0Name='QDimension0',
       Dimension0Binning='{0},{1},{2}'.format(qx-dQ, dQPixel, qx+dQ),
       Dimension1Name='QDimension1',
       Dimension1Binning='{0},{1},{2}'.format(qy-dQ, dQPixel, qy+dQ),
       Dimension2Name='QDimension2',
       Dimension2Binning='{0},{1},{2}'.format(qz-dQ, dQPixel, qz+dQ),
       TemporaryDataWorkspace='dataMD' if mtd.doesExist('dataMD') else None, 
       TemporaryNormalizationWorkspace='normMD' if mtd.doesExist('normMD') else None, 
       OutputWorkspace='result',
       OutputDataWorkspace='dataMD',
       OutputNormalizationWorkspace='normMD')   
print('Finished first MDNorm')
#Try with the same peak to show it works if we keep the binning the same       
MDNorm(InputWorkspace=MDdata,
       SolidAngleWorkspace='sa',
       RLU=False,
       FluxWorkspace='flux_cdf',
       QDimension0='1,0,0',
       QDimension1='0,1,0',
       QDimension2='0,0,1',
       Dimension0Name='QDimension0',
       Dimension0Binning='{0},{1},{2}'.format(qx-dQ, dQPixel, qx+dQ),
       Dimension1Name='QDimension1',
       Dimension1Binning='{0},{1},{2}'.format(qy-dQ, dQPixel, qy+dQ),
       Dimension2Name='QDimension2',
       Dimension2Binning='{0},{1},{2}'.format(qz-dQ, dQPixel, qz+dQ),
       TemporaryDataWorkspace='dataMD' if mtd.doesExist('dataMD') else None, 
       TemporaryNormalizationWorkspace='normMD' if mtd.doesExist('normMD') else None, 
       OutputWorkspace='result',
       OutputDataWorkspace='dataMD',
       OutputNormalizationWorkspace='normMD')       
print('Finished second MDNorm')       
#Try with a different point, should fail
qx += np.random.rand()-0.5
qy += np.random.rand()-0.5
qz += np.random.rand()-0.5
MDNorm(InputWorkspace=MDdata,
       SolidAngleWorkspace='sa',
       RLU=False,
       FluxWorkspace='flux_cdf',
       QDimension0='1,0,0',
       QDimension1='0,1,0',
       QDimension2='0,0,1',
       Dimension0Name='QDimension0',
       Dimension0Binning='{0},{1},{2}'.format(qx-dQ, dQPixel, qx+dQ),
       Dimension1Name='QDimension1',
       Dimension1Binning='{0},{1},{2}'.format(qy-dQ, dQPixel, qy+dQ),
       Dimension2Name='QDimension2',
       Dimension2Binning='{0},{1},{2}'.format(qz-dQ, dQPixel, qz+dQ),
       TemporaryDataWorkspace='dataMD' if mtd.doesExist('dataMD') else None, 
       TemporaryNormalizationWorkspace='normMD' if mtd.doesExist('normMD') else None, 
       OutputWorkspace='result',
       OutputDataWorkspace='dataMD',
       OutputNormalizationWorkspace='normMD') 
print('Finished third MDNorm')
```

Fixes #25618  

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/MDAlgorithms/src/MDNorm.cpp [hunk 1]
```diff
@@ -365,6 +365,32 @@ std::map<std::string, std::string> MDNorm::validateInputs() {
...
+  // validate accumulation workspaces, if provided
+  // this only checks that, if given, the two workspaces
+  // have the same dimensions.  We verify that binning parameters
+  // are the same when we execute the algorithm.
+  boost::shared_ptr<IMDHistoWorkspace> tempNormWS =
+      this->getProperty("TemporaryNormalizationWorkspace");
+  Mantid::API::IMDHistoWorkspace_sptr tempDataWS =
+      this->getProperty("TemporaryDataWorkspace");
+  if (tempNormWS || tempDataWS) {
+    if ((!tempNormWS) || (!tempDataWS)) {
```
Comment (AndreiSavici) [inline Framework/MDAlgorithms/src/MDNorm.cpp]: This should be replaced with `tempNormWS && tempDataWS`. Then do the for loop. The error message should follow an `else`. Currently you are likely to dereference a null pointer. Not good.

File: Framework/MDAlgorithms/src/MDNorm.cpp [hunk 2]
```diff
@@ -365,6 +365,32 @@ std::map<std::string, std::string> MDNorm::validateInputs() {
...
+      errorMessage.emplace(
+          "AccumulationWorkspaces",
+          "Must provide either no accumulation workspaces or,"
+          "both TemporaryNormalizationWorkspaces and TemporaryDataWorkspace");
+      for (size_t i = 0; i < 3; i++) {
+        auto ax1 = tempNormWS->getDimension(i);
+        auto ax2 = tempDataWS->getDimension(i);
+        if (!(ax1->getMinimum() == ax2->getMinimum()) &&
```
Comment (AndreiSavici) [inline Framework/MDAlgorithms/src/MDNorm.cpp]: Check if the dimension names are identical

File: Framework/MDAlgorithms/src/MDNorm.cpp [hunk 3]
```diff
@@ -675,6 +701,69 @@ void MDNorm::createNormalizationWS(
...
+ * @return :: bool - true means the binning is correct to aggreagete using
+ * tempDataWS
+ */
+bool MDNorm::isValidBinningForTemporaryDataWorkspace(
+    const std::map<std::string, std::string> &parameters,
+    const Mantid::API::IMDHistoWorkspace_sptr tempDataWS) {
+
+  std::string numBinsStr = parameters.at("OutputBins");
+  std::string extentsStr = parameters.at("OutputExtents");
+  std::string tmp;
```
Comment (AndreiSavici) [inline Framework/MDAlgorithms/src/MDNorm.cpp]: Check dimension names as well. I know you only do Q_sample, but someone might use a different workspace.

File: Framework/MDAlgorithms/src/MDNorm.cpp [hunk 4]
```diff
@@ -365,6 +365,32 @@ std::map<std::string, std::string> MDNorm::validateInputs() {
...
+      this->getProperty("TemporaryNormalizationWorkspace");
+  Mantid::API::IMDHistoWorkspace_sptr tempDataWS =
+      this->getProperty("TemporaryDataWorkspace");
+  if (tempNormWS || tempDataWS) {
+    if ((!tempNormWS) || (!tempDataWS)) {
+      errorMessage.emplace(
+          "AccumulationWorkspaces",
+          "Must provide either no accumulation workspaces or,"
+          "both TemporaryNormalizationWorkspaces and TemporaryDataWorkspace");
+      for (size_t i = 0; i < 3; i++) {
```
Comment (AndreiSavici) [inline Framework/MDAlgorithms/src/MDNorm.cpp]: Why only 3 dimensions? First check if the number of dimensions is the same, then do it for all dimensions.

File: Framework/MDAlgorithms/src/MDNorm.cpp [hunk 5]
```diff
@@ -675,6 +701,69 @@ void MDNorm::createNormalizationWS(
...
+
+  pos = 0; // parse extents
+  while ((pos = extentsStr.find(",")) != std::string::npos) {
+    tmp = extentsStr.substr(0, pos);
+    extents.push_back(std::stof(tmp));
+    extentsStr.erase(0, pos + 1);
+  }
+
+  // parse the input data workspace
+  for (int i = 0; i < 3; i++) {
```
Comment (AndreiSavici) [inline Framework/MDAlgorithms/src/MDNorm.cpp]: You can have 4D workspaces as well. Or 5D, ...

**Review by AndreiSavici — CHANGES_REQUESTED** [review]
Do not assume the workspaces are 3D. Also, do not assume that the dimensions are Q_sample

**Comment by sullivanbt** [comment]
The newest version should address all of those issues.

File: Framework/MDAlgorithms/src/MDNorm.cpp [hunk 6]
```diff
@@ -365,6 +366,45 @@ std::map<std::string, std::string> MDNorm::validateInputs() {
...
+  }
+  // check that both accumulation workspaces are on the same grid
+  if (tempNormWS && tempDataWS) {
+    size_t numNormDims = tempNormWS->getNumDims();
+    size_t numDataDims = tempDataWS->getNumDims();
+    if (numNormDims == numDataDims) {
+      for (size_t i = 0; i < numNormDims; i++) {
+        const auto dim1 = tempNormWS->getDimension(i);
+        const auto dim2 = tempDataWS->getDimension(i);
+        if (!((dim1->getMinimum() == dim2->getMinimum()) &&
```
Comment (sullivanbt) [inline Framework/MDAlgorithms/src/MDNorm.cpp]: make cleaner - use != instead of !(==) and ors instead of ands.

File: Framework/MDAlgorithms/src/MDNorm.cpp [hunk 7]
```diff
@@ -675,6 +731,211 @@ void MDNorm::createNormalizationWS(
...
+ * @param tempDataWS :: the workspace weare using to aggregate from
+ * @return :: bool - true means the binning is correct to aggreagete using
+ * tempDataWS
+ */
+void MDNorm::validateBinningForTemporaryDataWorkspace(
+    const std::map<std::string, std::string> &parameters,
+    const Mantid::API::IMDHistoWorkspace_sptr tempDataWS) {
+
+  // make sure the number of dimensions is the same for both workspaces
+  size_t numDimsInput = m_inputWS->getNumDims();
```
Comment (sullivanbt) [inline Framework/MDAlgorithms/src/MDNorm.cpp]: shouldnt need to use numDimsInput

File: Framework/MDAlgorithms/src/MDNorm.cpp [hunk 8]
```diff
@@ -675,6 +731,204 @@ void MDNorm::createNormalizationWS(
...
+  }
+
+  pos = 0; // parse extents
+  while ((pos = extentsStr.find(",")) != std::string::npos) {
+    tmp = extentsStr.substr(0, pos);
+    extents.push_back(std::stof(tmp));
+    extentsStr.erase(0, pos + 1);
+  }
+
+  // parse the input data workspace
```
Comment (sullivanbt) [inline Framework/MDAlgorithms/src/MDNorm.cpp]: temporary

**Review by AndreiSavici — DISMISSED** [review]

File: Framework/MDAlgorithms/src/MDNorm.cpp [hunk 9]
```diff
@@ -675,6 +732,185 @@ void MDNorm::createNormalizationWS(
...
+      nonDimensionIndex; // stores non-h,k,l or non-Qx,Qy,Qz dimensions
+  for (auto const &p : parameters) {
+    auto key = p.first;
+    auto value = p.second;
+    if (value.find("QDimension0") != std::string::npos) {
+      dimensionIndex[0] = parametersIndex;
+      const std::string dimXName =
+          tempDataWS->getDimension(parametersIndex)->getName();
+      if (m_isRLU) { // hkl
+        if (dimXName.compare(QDimensionName(m_Q0Basis)) != 0) {
```
Comment (quantumsteve) [inline Framework/MDAlgorithms/src/MDNorm.cpp]: use operator==()

File: Framework/MDAlgorithms/src/MDNorm.cpp [hunk 10]
```diff
@@ -675,6 +732,185 @@ void MDNorm::createNormalizationWS(
...
+          errorMessage << "TemporaryDataWorkspace does not have the  ";
+          errorMessage << "correct name for dimension " << parametersIndex;
+          debugMessage << "QDimension0 Names: Output will be: "
+                       << QDimensionName(m_Q0Basis);
+          debugMessage << " TemporaryDataWorkspace: " << dimXName;
+          g_log.warning(debugMessage.str());
+          throw(std::invalid_argument(errorMessage.str()));
+        }
+      } else {
+        if (dimXName.compare(QDimensionNameQSample(0)) != 0) {
```
Comment (quantumsteve) [inline Framework/MDAlgorithms/src/MDNorm.cpp]: use `operator==()`

File: Framework/MDAlgorithms/src/MDNorm.cpp [hunk 11]
```diff
@@ -675,6 +732,185 @@ void MDNorm::createNormalizationWS(
...
+          g_log.warning(debugMessage.str());
+          throw(std::invalid_argument(errorMessage.str()));
+        }
+      }
+    } else if (value.find("QDimension1") != std::string::npos) {
+      dimensionIndex[1] = parametersIndex;
+      const std::string dimYName =
+          tempDataWS->getDimension(parametersIndex)->getName();
+      if (m_isRLU) { // hkl
+        if (dimYName.compare(QDimensionName(m_Q1Basis)) != 0) {
```
Comment (quantumsteve) [inline Framework/MDAlgorithms/src/MDNorm.cpp]: use `operator==()`

File: Framework/MDAlgorithms/src/MDNorm.cpp [hunk 12]
```diff
@@ -675,6 +732,185 @@ void MDNorm::createNormalizationWS(
...
+          errorMessage << "TemporaryDataWorkspace does not have the  ";
+          errorMessage << "correct name for dimension " << parametersIndex;
+          debugMessage << "QDimension1 Names: Output will be: "
+                       << QDimensionName(m_Q1Basis);
+          debugMessage << " TemporaryDataWorkspace: " << dimYName;
+          g_log.warning(debugMessage.str());
+          throw(std::invalid_argument(errorMessage.str()));
+        }
+      } else {
+        if (dimYName.compare(QDimensionNameQSample(1)) != 0) {
```
Comment (quantumsteve) [inline Framework/MDAlgorithms/src/MDNorm.cpp]: use `operator==()`

File: Framework/MDAlgorithms/src/MDNorm.cpp [hunk 13]
```diff
@@ -675,6 +732,185 @@ void MDNorm::createNormalizationWS(
...
+          errorMessage << "TemporaryDataWorkspace does not have the  ";
+          errorMessage << "correct name for dimension " << parametersIndex;
+          debugMessage << "QDimension1 Names: Output will be: "
+                       << QDimensionNameQSample(1);
+          debugMessage << " TemporaryDataWorkspace: " << dimYName;
+          g_log.warning(debugMessage.str());
+          throw(std::invalid_argument(errorMessage.str()));
+        }
+      }
+    } else if (value.find("QDimension2") != std::string::npos) {
```
Comment (quantumsteve) [inline Framework/MDAlgorithms/src/MDNorm.cpp]: use `operator==()`

File: Framework/MDAlgorithms/src/MDNorm.cpp [hunk 14]
```diff
@@ -675,6 +732,185 @@ void MDNorm::createNormalizationWS(
...
+      dimensionIndex[2] = parametersIndex;
+      const std::string dimZName =
+          tempDataWS->getDimension(parametersIndex)->getName();
+      if (m_isRLU) { // hkl
+        if (dimZName.compare(QDimensionName(m_Q2Basis)) != 0) {
```
Comment (quantumsteve) [inline Framework/MDAlgorithms/src/MDNorm.cpp]: use `operator==()`

File: Framework/MDAlgorithms/src/MDNorm.cpp [hunk 15]
```diff
@@ -675,6 +732,185 @@ void MDNorm::createNormalizationWS(
...
+          errorMessage << "TemporaryDataWorkspace does not have the  ";
+          errorMessage << "correct name for dimension " << parametersIndex;
+          debugMessage << "QDimension2 Names: Output will be: "
+                       << QDimensionName(m_Q2Basis);
+          debugMessage << " TemporaryDataWorkspace: " << dimZName;
+          g_log.warning(debugMessage.str());
+          throw(std::invalid_argument(errorMessage.str()));
+        }
+      } else {
+        if (dimZName.compare(QDimensionNameQSample(2)) != 0) {
```
Comment (quantumsteve) [inline Framework/MDAlgorithms/src/MDNorm.cpp]: use `operator==()`

File: Framework/MDAlgorithms/src/MDNorm.cpp [hunk 16]
```diff
@@ -675,6 +732,185 @@ void MDNorm::createNormalizationWS(
...
+  }
+
+  // make sure the names of non-directional dimensions are the same
+  if (!(nonDimensionIndex.empty())) {
+    for (auto it = nonDimensionIndex.begin(); it != nonDimensionIndex.end();
+         ++it) {
+      const size_t indexID = *it;
+      const std::string nameInput = m_inputWS->getDimension(indexID)->getName();
+      const std::string nameData = tempDataWS->getDimension(indexID)->getName();
+      if (nameInput.compare(nameData) != 0) {
```
Comment (quantumsteve) [inline Framework/MDAlgorithms/src/MDNorm.cpp]: use `operator==()`

File: Framework/MDAlgorithms/src/MDNorm.cpp [hunk 17]
```diff
@@ -675,6 +732,185 @@ void MDNorm::createNormalizationWS(
...
+ * @return :: bool - true means the binning is correct to aggreagete using
+ * tempDataWS
+ */
+void MDNorm::validateBinningForTemporaryDataWorkspace(
+    const std::map<std::string, std::string> &parameters,
+    const Mantid::API::IMDHistoWorkspace_sptr tempDataWS) {
+
+  // parse the paramters map and get extents from tempDataWS
+  const std::string numBinsStr = parameters.at("OutputBins");
+  const std::string extentsStr = parameters.at("OutputExtents");
```
Comment (quantumsteve) [inline Framework/MDAlgorithms/src/MDNorm.cpp]: are these two keys guaranteed to be in `parameters`? Otherwise these functions will throw a potentially confusing `out_of_range` exception.

**Review by quantumsteve — CHANGES_REQUESTED** [review]
Please remove cases where you can use `==` instead of `std::string::find` and `std::string::compare`
https://clang.llvm.org/extra/clang-tidy/checks/readability-string-compare.html

**Comment by NickDraper** [comment]
Could you take a look at the conflict on this please

File: Framework/MDAlgorithms/src/MDNorm.cpp (hunk 17 above)
Comment (AndreiSavici) [reply Framework/MDAlgorithms/src/MDNorm.cpp]: Yes, the `OutputBins` and `OutputExtents` are part of the output from `getBinParameters()`

**Review by quantumsteve — APPROVED** [review]
