### PR TITLE
Engg:: Fix hang when using invalid data on load

### LINKED ISSUE #17419: Engg:: Fitting tab - Using invalid data and using load hangs Mantid
### Expected behavior
The engineering diffraction interface should gracefully handle invalid data being used instead of a focused file in the fitting tab.
### Actual behavior
If you select a file which has the incorrect format such as `ENGINX00193749.nxs` then click `Load` Mantid will hang probably stuck in a loop somewhere
### Platforms affected
All

### PR DESCRIPTION
**Pull request by DavidFair**
Description of work.
This PR fixes an issue where if the user tried to use an unfocused file the GUI would freeze whilst it tried (and failed) to plot 200+ curves.
**To test:**
Open the Engineering Diffraction Interface
Go to the `Fitting` Tab
Use an unfocused file such as `ENGINX00193749.nxs` and select Load
If Mantid doesn't freeze and stops with an error this PR works

Fixes #17419 .

Does not need to be in the release notes.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by KarlPalmen** [comment]
RHEL7 + System Tests have not yet completed despite running overnight.

**Comment by DavidFair** [comment]
I re-ran it this morning as `HFIRTestsAPIv2.HFIRTestsAPIv2` failed spuriously. It should go through fine as long as that unit test behaves this time.

**Comment by KarlPalmen** [comment]
:shipit:

File: MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp [hunk 1]
```diff
@@ -1530,6 +1532,19 @@ void EnggDiffFittingPresenter::plotFocusedFile(bool plotSinglePeaks) {
     auto focusedPeaksWS =
         ADS.retrieveWS<MatrixWorkspace>(g_focusedFittingWSName);
     auto focusedData = ALCHelper::curveDataFromWs(focusedPeaksWS);
+
+    // Check that the number of curves to plot isn't excessive
+    // lets cap it at 20 to begin with - this number could need
+    // raising but each curve creates about ~5 calls on the stack
+    // so keep the limit low. This will stop users using unfocused
+    // files which have 200+ curves to plot and will "freeze" Mantid
+    constexpr int maxCurves = 20;
```
Comment (FedeMPouzols) [inline MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp]: We could double-check this threshold with Saurabh. With the current conventions it could be just 1, as every bank is focused independently and the results written into separate files for every bank. It could also be the number of banks in the instrument (or texture pseudo-banks) if we ever write all the focused results into a single file, but probably never above that number.

**Comment by FedeMPouzols** [comment]
Yes, I think that `HFIRTestsAPIv2.HFIRTestsAPIv2` has become a little unstable lately.
