### PR TITLE
Fix a couple property handler bugs

### LINKED ISSUE #37129: Crash when removing a function from a composite function inside a convolution function
**Describe the bug**
Mantid crashes when you try to remove a function from a composite function inside a convolution function

**To Reproduce**
1. Load a workspace and open a plot
2. Open the fitting interface
3. Add a convolution function
4. Inside the convolution function add a composite function
5. Inside the convolution function add two functions (e.g. two Gaussians is fine)
6. Attempt to remove one of the Gaussians
(See screenshot for set up)

**Expected behavior**
Function should be removed and no crash should occur.

**Screenshots**
image

**Platform/Version (please complete the following information):**
 - OS: Recreated on Windows but probably on all OS
 - Mantid Version 6.9 - not checked whether it's a regression

### PR DESCRIPTION
**Pull request by jhaigh0**
### Description of work

Initially this work was just to fix #37129, but I also found a bug where all the remaining "Fix" properties would be removed when removing a function from the same composite function.

#### Summary of work
- To fix the original issue, the parameter index needed to be retrieved from the top level composite function so the long prefix (`f0.f0.f0`) could be parsed properly.
- To fix the issue with removing the Fix sub properties, a check has been added to `renameChildren` to see if the parameter is fixed.
- I noticed that when adding the first function to a convolution, it sets all parameters to be fixed. When this gets initialised in the property handler, I've changed it to use the `fix` function so it is all more consistent
- I've also reduced some code reuse by changing `fix` to call `addTie` which now checks if the tie is static (aka a fix).

Fixes #37129

`renameChildren` definitely still contains a problem or two. I don't think it copes well if you had a bunch of nested composite function and wanted to tie across different levels, but this isn't a regression, so I will try and fix these in a later pr.

### To test:

 - Follow the instructions from the issue
 - Clear the model
 - Add two Gaussians
 - Right click to fix the height of one of the Gaussians
 - Remove the other Gaussian, the fix property should remain in place.

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

File: qt/widgets/common/src/PropertyHandler.cpp [hunk 1]
```diff
@@ -472,16 +470,23 @@ void PropertyHandler::renameChildren(const Mantid::API::CompositeFunction &cf) {
     QString parName = it.key();
     QString fullName = functionPrefix() + "." + parName;
     QtProperty *prop = it.value();
-    Mantid::API::ParameterTie *tie = cf.getTie(cf.parameterIndex(fullName.toStdString()));
+    const auto paramIndex = m_browser->compositeFunction()->parameterIndex(fullName.toStdString());
```
Comment (robertapplin) [inline qt/widgets/common/src/PropertyHandler.cpp:473]: Just want to check, `compositeFunction()` can never return a nullptr in this situation?

File: qt/widgets/common/src/PropertyHandler.cpp [hunk 2]
```diff
@@ -1137,47 +1142,42 @@ void PropertyHandler::addTie(const QString &tieStr) {
...
-      tieProp = m_browser->m_stringManager->addProperty("Fix");
-      m_ties[parName] = tieProp;
-    }
-    m_browser->m_stringManager->setValue(tieProp, parValue);
-    m_browser->m_changeSlotsEnabled = true;
-    parProp->addSubProperty(tieProp);
-    tieProp->setEnabled(false);
-  } catch (...) {
-  }
+  addTie(functionPrefix() + "." + parName + "=" + parValue);
```
Comment (robertapplin) [inline qt/widgets/common/src/PropertyHandler.cpp:1180]: Also want to check `functionPrefix()` will never return an empty string?

**Review by robertapplin — CHANGES_REQUESTED** [review]
Code looks good and the original crash no longer happens. I just had two questions, then happy to approve

File: qt/widgets/common/src/PropertyHandler.cpp (hunk 1 above)
Comment (jhaigh0) [reply qt/widgets/common/src/PropertyHandler.cpp:473]: Should always be created in `createCompositeFunction`, called from the `FitPropertyBrowser::init()`

File: qt/widgets/common/src/PropertyHandler.cpp (hunk 2 above)
Comment (jhaigh0) [reply qt/widgets/common/src/PropertyHandler.cpp:1180]: Since there is always a composite function at the base level of the fitproperty browser, there should always be at least one level of prefix.

**Review by robertapplin — APPROVED** [review]
Thanks for confirming - in that case happy to approve!
