### PR TITLE
Fix nightly MacOS app bundle

### LINKED ISSUE #30504: MacOS version crashes
**Original reporter:** SNS/granroth

### Expected behavior
Be able to start MantidWorkbench

### Actual behavior
Crash

### Steps to reproduce the behavior
`The release crashes when I try to run it although if I run mantid python it seems to be in Python 3.8.  Does Mantid need 3.6?   If I run the nightly it complains about not being able to find a library in /usr/local/boost.  There is no /usr/local/boost directory.  I am  on mojave.`

Comment from @quantumsteve
` I wonder if the name change between MantidWorkbench and MantidWorkbenchNightly is causing MantidWorkbenchNightly to not be fixed up in packaging `
https://github.com/mantidproject/mantid/blob/c7dc6157d39bbc8fe94fa60828333707cc9c2399/installers/MacInstaller/make_package.rb#L593
### Platforms affected
MacOS

### PR DESCRIPTION
**Pull request by quantumsteve**
Signed-off-by: Steven Hahn <hahnse@ornl.gov>

**Description of work.**

Use Pathname.basename to get executable name

**Report to:** @AndreiSavici @granrothge 

**To test:**

Download MacOS .app bundle and try to start MantidWorkbench.

Fixes #30504. 

*This does not require release notes* because only affects nightly builds

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: installers/MacInstaller/make_package.rb [hunk 1]
```diff
@@ -590,12 +590,13 @@ def stop_if_bundle_not_self_contained(basepath, extra = [])
   requirements_files << REQUIREMENTS_WORKBENCH_FILE
   bundled_qt_plugins = QT_PLUGINS_COMMON + ['platforms', 'printsupport', 'styles']
   host_qt_plugins_dir = QT5_PLUGINS_DIR
-  executables << "#{contents_macos}/MantidWorkbench"
+  executables << "#{contents_macos}/#{bundle_path.basename}"
+  fatal("MantidWorkbechUnstable? #{contents_macos}/#{bundle_path.basename}")
```
Comment (martyngigg) [inline installers/MacInstaller/make_package.rb:594]: This doesn't matter for the release but it will mean we can't build packages on pull requests. Does it currently not work in this case?

Comment (quantumsteve) [reply installers/MacInstaller/make_package.rb:594]: I added this line strictly for debugging and will remove it soon.

I downloaded the a package from the build server and found that `MantidWorkbenchUnstable` is still linked against boost libraries in `/usr/local/`. Want to verify `#{contents_macos}/#{bundle_path.basename}` is giving what I expect before investigating further.

**Review by martyngigg — DISMISSED** [review]
I can confirm that the nightly bundle now starts up as expected. 🎉

**Review by martyngigg — APPROVED** [review]
