### PR TITLE
Fixes and unit tests for AlignAndFocusPowder Refs #23888

### LINKED ISSUE #8929: Add unit test for AlignAndFocusPowder
This issue was originally [TRAC 8084](http://trac.mantidproject.org/mantid/ticket/8084)

This ticket is blocked by : 
- [X] [TRAC8074](http://trac.mantidproject.org/mantid/ticket/8074)

Anything is better than what is(n't) there now.

### LINKED ISSUE #17840: AlignAndFocusPowder algorithm is missing Unit Tests
The algorithm `AlignAndFocusPowder` seems to be missing unit tests. I couldn't find any written in either C++ or Python

### LINKED ISSUE #23888: Add unit tests for AlignAndFocusPowder
`AlignAndFocusPowder` requires unit tests. Make sure to add a unit test for the case for preserve events `false` as this appears to be failing for POLARIS data

### PR DESCRIPTION
**Pull request by marshallmcdonnell**
**Description of work.**
Adds unit test for [`AlignAndFocusPowder`](http://docs.mantidproject.org/nightly/algorithms/AlignAndFocusPowder-v1.html) with bug fixes found during the test development. 

Bug fixes:
1) Non-event workspaces did not clone the input workspace, thus an empty workspace was returned
2) Calling `AlignAndFocusPowder` with the `GroupingFilename` it will extract the grouping workspace without applying the mask and pass this to the child algorithm `DiffractionFocussing` with the `GroupingWorkspace` argument. Yet if you call `DiffractionFocussing` with the `GroupingFileName` argument, it will go ahead and apply the mask. Thus, to make `AlignAndFocusPowder` with the `GroupingFilename` work the same way as `DiffractionFocussing` with the `GroupingFileName` argument, the mask is now applied to the grouping workspace passed to `DiffractionFocussing` as the `GroupingWorkspace` argument.

**To test:**

1. Build branch
2. Build the `WorkflowAlgorithmsTest` tests
3. Run the `AlignAndFocusPowderTest` test suite

Example script for step 2 and 3:
`ninja && ninja WorkflowAlgorithmsTest && ctest -R AlignAndFocusPowderTest`

NOTE: If it helps, for manually setting up the tests on HRPD test files in the `ExternalDataStore`, the following python script helped me plot results to figure out when I encountered bugs. (has .txt file extension so GitHub would let me upload)
[alignfocuspowder_testing.txt](https://github.com/mantidproject/mantid/files/2727611/alignfocuspowder_testing.txt)

Fixes #8929, fixes #17840, and fixes #23888

Refs #17841, #19105, #19109, #22602, #23869, and #24386

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/WorkflowAlgorithms/test/AlignAndFocusPowderTest.h [hunk 1]
```diff
@@ -0,0 +1,817 @@
...
+    preserveEvents = true;
+    useGroupAll = false;
+    useResamplex = true;
+    maskBinTableWS = createMaskBinTable();
+
+    // Run the main test function
+    dotestEventWksp();
+
+    // Reset inputs to default values
+    maskBinTableWS = NULL;
```
Comment (peterfpeterson) [inline Framework/WorkflowAlgorithms/test/AlignAndFocusPowderTest.h]: should be `nullptr`

File: Framework/WorkflowAlgorithms/test/AlignAndFocusPowderTest.h [hunk 2]
```diff
@@ -0,0 +1,817 @@
...
+    LoadNexus loader;
+    loader.initialize();
+    loader.setPropertyValue("Filename", "HRP38692a.nxs");
+    loader.setPropertyValue("OutputWorkspace", inputWS);
+    loader.execute();
+    TS_ASSERT_THROWS_NOTHING(loader.execute());
+    TS_ASSERT(loader.isExecuted());
+  }
+
+  void dotestHRP38692(bool useCalfile, bool useCalWksp, bool useGroupfile,
```
Comment (peterfpeterson) [inline Framework/WorkflowAlgorithms/test/AlignAndFocusPowderTest.h]: rename to `doTestHRP38692`

File: Framework/WorkflowAlgorithms/test/AlignAndFocusPowderTest.h [hunk 3]
```diff
@@ -0,0 +1,817 @@
...
+    TS_ASSERT_EQUALS(inWS->y(0)[18], 237);
+    TS_ASSERT_DELTA(inWS->x(0)[38], 6519.0800, 0.0001);
+    TS_ASSERT_EQUALS(inWS->y(0)[38], 199);
+    TS_ASSERT_DELTA(inWS->x(0)[58], 9792.2800, 0.0001);
+    TS_ASSERT_EQUALS(inWS->y(0)[58], 772);
+    TS_ASSERT_DELTA(inWS->x(0)[88], 14702.0800, 0.0001);
+    TS_ASSERT_EQUALS(inWS->y(0)[88], 2162);
+  }
+
+  void dotestEventWksp() {
```
Comment (peterfpeterson) [inline Framework/WorkflowAlgorithms/test/AlignAndFocusPowderTest.h]: rename to `doTestEventWksp`

File: Framework/WorkflowAlgorithms/test/AlignAndFocusPowderTest.h [hunk 4]
```diff
@@ -0,0 +1,817 @@
...
+    freqAlg.setPropertyValue("LogName", "Frequency");
+    freqAlg.setPropertyValue("LogText", "200.0");
+    freqAlg.setPropertyValue("LogUnit", "Hz");
+    freqAlg.setPropertyValue("LogType", "Number Series");
+    freqAlg.setPropertyValue("NumberType", "Double");
+    freqAlg.setPropertyValue("Workspace", inputWS);
+    freqAlg.execute();
+  }
+
+private:
```
Comment (peterfpeterson) [inline Framework/WorkflowAlgorithms/test/AlignAndFocusPowderTest.h]: coding convention says member variables should start with `m_` to make them easier to spot. Also, initialized values should be defined as `int m_numBanks{1};` as done in newer C++.

File: Framework/WorkflowAlgorithms/test/AlignAndFocusPowderTest.h [hunk 5]
```diff
@@ -0,0 +1,817 @@
...
+    TS_ASSERT_DELTA(outWS->y(0)[600], 7283.29652, 0.0001);
+  }
+
+  /* Setup for event data */
+
+  void setUp_EventWorkspace(int numBanks, int numPixels,
+                            int numEvents = 10000) {
+    inputWS = "eventWS";
+
+    CreateSampleWorkspace createSampleAlg;
```
Comment (peterfpeterson) [inline Framework/WorkflowAlgorithms/test/AlignAndFocusPowderTest.h]: It would be a good idea (follow-on PR) to make this the default functionality for `CreateSampleWorkspace(Function='Powder Diffraction', ...)` as having the instrument centered on two_theta=90 is fairly common.

**Review by peterfpeterson — CHANGES_REQUESTED** [review]
Overall a great improvement as demonstrated by the bugs found and fixed. The changes requested are code style/convention.

**Review by peterfpeterson — APPROVED** [review]

File: Framework/WorkflowAlgorithms/test/AlignAndFocusPowderTest.h (hunk 5 above)
Comment (marshallmcdonnell) [reply Framework/WorkflowAlgorithms/test/AlignAndFocusPowderTest.h]: Issue created #24411
