### PR TITLE
Reset row state when experiment settings are changed via the Preview tab

### LINKED ISSUE #35565: Changing ROI via Preview tab does not reset row state
**Describe the bug**
If you manually edit the ROI in the Experiment Settings tab, any processed runs get their state reset (i.e. reset from green to white). However, if you change the ROI via the Apply button on the Preview tab, the state is not reset.

**To Reproduce**
- Open the ISIS Reflectometry interface and set instrument to INTER
- On the Runs tab enter run number 45455 and angle 1.0. Click Process - the row should turn green.
- On the Preview tab, enter run number 45455 and angle 1.0. Click the Signal button and draw a region on the middle plot. This should perform a reduction and the last plot should update with a line. 
- Click the Apply button. Check the Experiment Settings tab and the ROI should have been set in the table.
- Back on the Runs tab, the row's state should have been cleared and returned to white, but it remains green.

**Expected behavior**
The state of any runs that are processed or errored should be reset when the experiment settings are changed.

**Platform/Version (please complete the following information):**
 - Ubuntu 22.04, probably all
 - Mantid Version 6.6

### PR DESCRIPTION
**Pull request by rbauststfc**
**Description of work**

**Purpose of work**

This fix ensures that processed runs display the correct state when settings have been changed in the Experiment Settings lookup table via the Apply button on the Preview tab. For further details, see the linked issue.

**Summary of work**

When the Apply button on the Preview tab is clicked, I've added a check to make sure that there are changes that need to be applied to the row. If there are then, after these are applied, I've added a call to notify the batch that experiment settings have changed. This triggers the workflow to reset the row state.

**To test:**

See instructions in linked issue, although I would recommend testing with run number `11934` and angle `1.0` to avoid potentially confusing error messages. These error message are the result of recent changes that now require other settings to be present for run `45455` to reduce correctly.

Fixes #35565. 

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

File: qt/scientific_interfaces/ISISReflectometry/test/Experiment/ExperimentPresenterTest.h [hunk 1]
```diff
@@ -820,13 +820,17 @@ class ExperimentPresenterTest : public CxxTest::TestSuite {
...
+
     presenter.notifyPreviewApplyRequested(previewRow);
     // Row with angle 2.3 is the last row in the look-up table
     auto row = presenter.experiment().lookupTableRows().back();
     TS_ASSERT_EQUALS(row.roiDetectorIDs().get(), "9");
     TS_ASSERT_EQUALS(row.processingInstructions().get(), "10");
     TS_ASSERT_EQUALS(row.backgroundProcessingInstructions().get(), "11");
     TS_ASSERT_EQUALS(row.transmissionProcessingInstructions().get(), "12");
+
+    verifyAndClear();
```
Comment (robertapplin) [inline qt/scientific_interfaces/ISISReflectometry/test/Experiment/ExperimentPresenterTest.h:833]: Is `verifyAndClear` used at the end of each of the tests? If so, maybe it could go in the tearDown method?

**Review by robertapplin — CHANGES_REQUESTED** [review]
The code looks good, and the colour of the processed row gets reset when the experiment settings is updated. I just had one suggestion

File: qt/scientific_interfaces/ISISReflectometry/test/Experiment/ExperimentPresenterTest.h (hunk 1 above)
Comment (rbauststfc) [reply qt/scientific_interfaces/ISISReflectometry/test/Experiment/ExperimentPresenterTest.h:833]: Good spot, I think it is now. I _think_ it's only technically needed if you have set expectations on the presenter or view (which all tests now do). I don't know if it would be an issue if you called `verifyAndClear` without any expectations set. I'm afraid I'm a bit pushed for time at the moment, so would you be happy if I open a maintenance issue for this one to look at during the release period?

Comment (robertapplin) [reply qt/scientific_interfaces/ISISReflectometry/test/Experiment/ExperimentPresenterTest.h:833]: Yes doing it as part of maintenance is no problem. Which tests do you not see it in which are causing confusion?

**Review by robertapplin — APPROVED** [review]

File: qt/scientific_interfaces/ISISReflectometry/test/Experiment/ExperimentPresenterTest.h (hunk 1 above)
Comment (rbauststfc) [reply qt/scientific_interfaces/ISISReflectometry/test/Experiment/ExperimentPresenterTest.h:833]: Great, thanks. Sorry, my comment wasn't very clear, I mean if for example you look at a totally different file such as PreviewPresenterTest.h I can't immediately see something that looks equivalent to what the `verifyAndClear` method seems to be doing, so I was keen to take the time to understand why that is (or spot where it is in PreviewPresenterTest.h).

Comment (robertapplin) [reply qt/scientific_interfaces/ISISReflectometry/test/Experiment/ExperimentPresenterTest.h:833]: Ah I see, I'm not sure either - if you find out then let me know!

Comment (gemmaguest) [reply qt/scientific_interfaces/ISISReflectometry/test/Experiment/ExperimentPresenterTest.h:833]: This is because we have mocks like `m_mainPresenter` which are members of the test class. `Mock::VerifyAndClearExpectations` will be called automatically when the mock is destroyed but because it's a member that won't happen till all the tests have finished, so we have to call it manually at the end of each test. The newer tests create the mocks as local variables so they get destroyed at the end of each test, which is the better way to do it.

Comment (rbauststfc) [reply qt/scientific_interfaces/ISISReflectometry/test/Experiment/ExperimentPresenterTest.h:833]: Ah, thanks very much Gemma, that's really useful to know. So we should really see if we can refactor it to create the mocks as local variables when we look at the maintenance issue then.
