### PR TITLE
Indirect - Elwin - Add check in case of invalid value within IPF file

### LINKED ISSUE #20858: Add more robust checks around reading IPF elements in IDA
On Friday we found that an instrument parameter file with a misspelled XML element was causing Mantid to crash unexpectedly. We corrected this in #20856, but we should make the code more robust as well.

### Expected behavior
Mantid should not crash. 

### Actual behavior
Mantid crashes because it expects the element to exist and be correctly spelled. If this is not the case it gets a `nullptr` and falls over at line 291 in Elwin.cpp.

https://github.com/mantidproject/mantid/blob/21bccfe66a959f3a56e6b0f6860fed37eab64dd9/qt/scientific_interfaces/Indirect/Elwin.cpp#L286-L291

### Steps to reproduce the behavior
See #20856 

### Platforms affected
All.

### PR DESCRIPTION
**Pull request by brandonhewer**
In the Elwin interface (Elwin.cpp), it is possible to crash Mantid, when there is an attempt to load an IPF file which contains an invalid value.

This PR adds a check for when this condition occurs and provides a warning message to the user.

**To test:**
1. Add the \*\_Parameters file to your instrument parameters directory.
2. Navigate to Interfaces > Indirect > Data Analysis Elwin.
3. Supply the \*\_red file as the input.
4. Run the Elwin interface and ensure Mantid does not crash and an error message is displayed.

**Test Files:**
[elwin-ipf-test-files.zip](https://github.com/mantidproject/mantid/files/1422106/elwin-ipf-test-files.zip)

Fixes #20858. 

**Release Notes** 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/scientific_interfaces/Indirect/Elwin.cpp [hunk 1]
```diff
@@ -288,19 +288,25 @@ void Elwin::setDefaultResolution(Mantid::API::MatrixWorkspace_const_sptr ws,
...
-      double res = params[0];
-      m_dblManager->setValue(m_properties["IntegrationStart"], -res);
-      m_dblManager->setValue(m_properties["IntegrationEnd"], res);
+    if (comp) {
+      auto params = comp->getNumberParameter("resolution", true);
 
-      m_dblManager->setValue(m_properties["BackgroundStart"], -10 * res);
-      m_dblManager->setValue(m_properties["BackgroundEnd"], -9 * res);
+      // set the default instrument resolution
+      if (params.size() > 0) {
```
Comment (soininen) [inline qt/scientific_interfaces/Indirect/Elwin.cpp]: Please use `if (!params.empty())` instead. It conveys the intention better.

**Review by soininen — CHANGES_REQUESTED** [review]

**Comment by soininen** [comment]
Could there be a test file attached to this pull request so it could be tested?

**Comment by soininen** [comment]
@brandonhewer I couldn't make vanilla Mantid 'master' to crash with the test files provided. The interface seems to work just fine. What am I supposed to see when these changes are not applied?

**Comment by NickDraper** [comment]
@brandonhewer This appears to be stuck with you

**Comment by brandonhewer** [comment]
This PR adds a simple check, currently I've been unable to reproduce the issue with the file I supplied.
This PR shouldn't break any existing code (please see the diff) and it may be best to check it works with the supplied test.

**Review by Anders-Markvardsen — APPROVED** [review]
The code adds an extra null pointer check. Bug can't been reproduced from this branch and previous test suggest can't easily do this with older version, but this extra change provides an extra safety and therefore approve

**Review by soininen — APPROVED** [review]
