### PR TITLE
Fix Rebin dialog crash with group workspace

### LINKED ISSUE #36689: Crash with attempt at opening Rebin dialog
**Describe the bug**

Workbench disappears with no error reporter

**To Reproduce**
- Load ZOOM 22699
- Type `Rebin` into the algorithm box in the bottom left, select the `Rebin` algorithm, press enter

**Platform/Version (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - Mantid Version 6.8 and latest 6.9 debug build

### PR DESCRIPTION
**Pull request by jclarkeSTFC**
If the workspace selected in the dialog is a group workspace, then calling `getProperty()` with `MatrixWorkspace` as the return type will return null. In that case we can check if the specified workspace name exists in the ADS and skip the `Rebin` parameters validation (which requires a `MatrixWorkspace`). When `Rebin` is actually called, it will be called on each of the members of the group workspace individually, and the parameters will be validated for each one.

#### Summary of work
- When validating parameter for `Rebin`, if the specified input workspace is not a `MatrixWorkspace`, then check if it at least exists in the ADS before adding an error if it doesn't.
- Added a test to check validation of group workspaces.
- Fixed another test that was trying to check bin parameter validation (e.g. `1,1,20`), but it wasn't setting an input workspace, so the validation would now fail before getting to the bin parameter validation.
- Fixed a cppcheck error instead of changing the line number in the suppression file.

Fixes #36689. 

### To test:

See #36689 for how to reproduce.

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

File: Framework/Algorithms/src/Rebin.cpp [hunk 1]
```diff
@@ -135,15 +136,25 @@ std::map<std::string, std::string> Rebin::validateInputs() {
...
-    std::vector<double> validParams = rebinParamsFromInput(rbParams, *inputWS, g_log, binMode);
-    // if the binmode has been set, force the rebin params to be consistent
-    if (binMode != BinningMode::DEFAULT) {
-      setProperty(PropertyNames::PARAMS, validParams);
-      rbParams = validParams;
+  if (inputWS == nullptr) {
+    // The workspace could exist, but not be a MatrixWorkspace, e.g. it might be
+    // a group workspace. In that case we don't want a validation error for the
+    // Rebin parameters.
+    std::string inputWsName = getProperty(PropertyNames::INPUT_WKSP);
```
Comment (cailafinn) [inline Framework/Algorithms/src/Rebin.cpp:143]: We don't seem to change this. Could it be const &?
```suggestion
    const std::string &inputWsName = getProperty(PropertyNames::INPUT_WKSP);
```

File: Framework/Algorithms/src/Rebin.cpp [hunk 2]
```diff
@@ -135,15 +136,25 @@ std::map<std::string, std::string> Rebin::validateInputs() {
...
+    const bool wsExists = AnalysisDataService::Instance().doesExist(inputWsName);
+    if (!wsExists)
+      helpMessages[PropertyNames::INPUT_WKSP] = "Input workspace not in ADS.";
```
Comment (cailafinn) [inline Framework/Algorithms/src/Rebin.cpp:146]: I think this is actually clearer if this is one line. It makes clear that we're checking the workspace exists explicitly in the ADS.
```suggestion
    if (!AnalysisDataService::Instance().doesExist(inputWsName)) {
      helpMessages[PropertyNames::INPUT_WKSP] = "Input workspace not in ADS.";
    }
```
As an aside, I've also suggested that curly braces be added in. It's not in our standards but I think it should be. Single line if's without them look initially neater but can easily lead to problems down the line if more statements get added without due care. David Fairbrother sent me an article about a big security issue caused by these that happened to Apple a while back. Worth a read if you get time. I found it interesting, at least: https://www.imperialviolet.org/2014/02/22/applebug.html

File: docs/source/release/v6.9.0/Workbench/Bugfixes/36689.rst [hunk 3]
```diff
@@ -0,0 +1 @@
+- Fixed crash when opening the `Rebin` algorithm dialog when a group workspace is selected as the input workspace.
```
Comment (cailafinn) [inline docs/source/release/v6.9.0/Workbench/Bugfixes/36689.rst:1]: Could this be a `:ref:` link to the algorithm? Though as a side-note, if you want `monospace` style in `.rst` files you need two backticks around the string.
```suggestion
- Fixed crash when opening the :ref:`algm-Rebin` algorithm dialog when a group workspace is selected as the input workspace.
```

**Review by cailafinn — CHANGES_REQUESTED** [review]
Works well, nice fix. No longer crashes when opening with a group workspace. Just a couple of code comments:

**Review by cailafinn — APPROVED** [review]
Looks good to me now, nice work :shipit:
