### PR TITLE
Fixed cow_ptr move constructor and assignment

### LINKED ISSUE #16476: Kernel::cow_ptr is not movable
In `Kernel::cow_ptr` we have the move constructor and move assignment set as `= default`. However, the compiler does not generate them. The reason seems to be the `std::mutex` member.

Since `cow_ptr` wraps a `shared_ptr` the negative impact of this is probably rather small, but it should be cleaned up nevertheless.

### PR DESCRIPTION
**Pull request by SimonHeybrock**
Defaulted (compiler generated) move of `Kernel::cow_ptr` did not do what expected due to a non-movable class member. In this commit we therefore provide a custom implementation.

**To test:**

Code review & make sure the tests catch the regression if the bug is reintroduced.

Fixes #16476 .

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Kernel/inc/MantidKernel/cow_ptr.h [hunk 1]
```diff
@@ -71,9 +71,14 @@ template <typename DataType> class cow_ptr {
   /// Constructs a cow_ptr with no managed object, i.e. empty cow_ptr.
   constexpr cow_ptr(std::nullptr_t) : Data(nullptr) {}
   cow_ptr(const cow_ptr<DataType> &);
-  cow_ptr(cow_ptr<DataType> &&) = default;
+  // Move is hand-written, since std::mutex member prevents auto-generation.
+  cow_ptr(cow_ptr<DataType> &&other) : Data(std::move(other.Data)) {}
```
Comment (quantumsteve) [inline Framework/Kernel/inc/MantidKernel/cow_ptr.h]: Can this be marked `noexcept`?

File: Framework/Kernel/inc/MantidKernel/cow_ptr.h [hunk 2]
```diff
@@ -71,9 +71,14 @@ template <typename DataType> class cow_ptr {
...
   cow_ptr<DataType> &operator=(const cow_ptr<DataType> &);
-  cow_ptr<DataType> &operator=(cow_ptr<DataType> &&) = default;
+  // Move is hand-written, since std::mutex member prevents auto-generation.
+  cow_ptr<DataType> &operator=(cow_ptr<DataType> &&rhs) {
```
Comment (quantumsteve) [inline Framework/Kernel/inc/MantidKernel/cow_ptr.h]: Can this be marked `noexcept`?

**Comment by SimonHeybrock** [comment]
@quantumsteve Yes you are right -- `shared_ptr` moves are `noexcept`, so I added it also here.

**Comment by quantumsteve** [comment]
The move constructor and move assignment operator LGTM and two new tests verify that it functions correctly. We want a unique mutex per cow_ptr, so keeping it out of the member initializer list and relying on the default constructor makes sense.

:shipit:

**Comment by FedeMPouzols** [comment]
I think this may be the second place in the code where we have `noexcept`! This may be a good area for a bit of modernization/maintenance.

**Comment by quantumsteve** [comment]
@FedeMPouzols clang-tidy checks that move constructors and move assignment operators are marked `noexcept` and suggests 9 more places where we could use this keyword.

http://clang.llvm.org/extra/clang-tidy/checks/misc-noexcept-move-constructor.html
