### PR TITLE
Fix restricted suffix not working on Elwin interface.

### LINKED ISSUE #38041: Restrict input by extension not working in Elwin interface
**Describe the bug**

The workspace dialog appearing on the Elwin interface whenever the `Add Workspace` is clicked selects workspaces with a valid suffix from the ADS (those with allowed suffix: typically `_red` and `_sqw` for Elwin) and displays them on the table. 
If from the settings menu of the interface, the option `Restrict allowed input files...` is unticked, the workspace dialog from the Elwin interface should allow any valid name from the ADS to be added to the elwin interface. 

On latest nightly, this option is not working and this seems to be a regression. 
 
**To Reproduce**

- Add any workspace to the ADS. 
- Open Data Processor interface, and on Settings dialog (cog icon) untick the `Restrict allowed input files by name ` checkbox. 
- Go to the `Elwin` tab, click on `Add Workspaces`, the workspace added to the workspace should be appearing as an entry on the table of this dialog. 

**Platform/Version (please complete the following information):**
 - OS: All
 - OS Version:
 - Mantid Version Nightly

**Additional context**

### PR DESCRIPTION
**Pull request by adriazalvarez**
### Description of work
Fixes #38041 

#### Summary of work

The WorkspaceMultiSelector widget was created from the DataSelector widget, but there are many functions of the DataSelector which don't need to be used (and probably we won't need to use them in the future) and clutter the class. I have remove the workspacetype and show group properties of the table and simplify the code where possible. Additionally, the suffix was not being properly updated when initiating the class, which may be why the unrestricted setting was being ignored. 

Fixes #38041. 

### To test:
Note: this test modifies the Procesor interface settings, which is done from a Settings dialog, everytime you change a Settings, make sure to click the button `Apply` and then `Ok` for the setting to change. 
- Load any data. 
- Open Data Processor interface. 
- Click on Settings icon (cog), make sure to untick the `Restrict allowed input files.. .` checkbox.
- Go to the Elwin tab, and click on `Add Workspaces`. The resulting dialog should contain a table with 1 entry with the same data as that you added on step 1. 
- Close the Dialog. 
- Go to Settings again, and this time tick the `Restrict allowed input files..` checkbox. 
- Go to the elwin tab, click on `Add Workspaces`, the resulting dialog should contain no data (unless the data you loaded had suffix _red or _sqw) 
- Close the dialog and the Data Processor interface. 
- Clear the ADS. 
- Load any _red data (for example irs26176_graphite002_red from SampleData-ISIS). 
- Open the Data Processor interface, check that the Settings `Restrict allowed input..` is ticked. Then on Elwin tab click on `Add Workspaces` and in the resulting dialog you should see an entry with the data that you added to the ADS(irs26176..) . 
- Close the dialog, and in the Settings dialog, untick again the `Restrict allowed input..` checkbox. 
- Wehn opening again the `Add Workspaces` dialog from the Elwin tab, you should still see the data that you added (irs26176...)

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by GuiMacielPereira — DISMISSED** [review]
Manual testing is working as intended, the filtering of workspaces by suffix is working correctly. Code is much cleaner and unused sections (filtering by types and groups) was removed.

All good!

File: qt/widgets/common/src/WorkspaceMultiSelector.cpp [hunk 1]
```diff
@@ -80,67 +77,37 @@ void WorkspaceMultiSelector::setupTable() {
...
   return (item != nullptr);
 }
 
-QStringList WorkspaceMultiSelector::getWSSuffixes() const { return m_suffix; }
+const QStringList &WorkspaceMultiSelector::getWSSuffixes() const { return m_suffix; }
 
 void WorkspaceMultiSelector::setWSSuffixes(const QStringList &suffix) {
-  if (suffix != m_suffix) {
+  if (suffix != m_suffix)
     m_suffix = suffix;
```
Comment (GuiMacielPereira) [inline qt/widgets/common/src/WorkspaceMultiSelector.cpp:109]: I just spotted that you could just do:
```suggestion
  m_suffix = suffix;
```
since it's a simple assignment so it's as quick as checking the if statement anyway.
But it is a pedantic change so it's good either way

**Review by GuiMacielPereira — APPROVED** [review]
