### PR TITLE
26919 load ngem compiler error

### LINKED ISSUE #26919: LoadNGem compiler error on MSVC Debug build
### Expected behavior
The `DataHandling` target should build on MSVC in Debug

### Actual behavior
It does not:
```
Build FAILED.

"mantid-build\Framework\DataHandling\DataHandling.vcxproj" (default target) (1) ->
(ClCompile target) ->
 mantid\Framework\DataHandling\src\LoadNGEM.cpp(114,1): error C3016: 'i': index variable in OpenMP 'for' statement must have signed integral type [mantid-build\Framework\DataHandling\DataHandling.vcxproj]
```

It looks like OpenMP is complaining about being passed an unsigned `size_t` integer. Replacing with an `int` or `long` as required fixes this.
https://github.com/mantidproject/mantid/blob/1cfc6edf2c9562e7c50d7fc3f7257101ace02809/Framework/DataHandling/src/LoadNGEM.cpp#L115

### Steps to reproduce the behavior
Try to build the `.\Framework\DataHandling\DataHandling.vcxproj` target in debug mode on Windows

### Platforms affected
Windows

### PR DESCRIPTION
**Pull request by DannyHindson**
**Description of work.**

Resolve issue with DataHandling.dll not compiling in Visual Studio 2019 - specific problem was an OpenMP for loop in LoadNGEM.cpp. Problem appears to have been arisen due to earlier versions of Visual Studio 2019 unintentionally accepting an unsigned int as the index of an OpenMP for loop. Microsoft have since fixed this problem which means an unsigned int now gives a compiler error. See:

https://developercommunity.visualstudio.com/content/problem/650998/incorrect-number-of-threads-spawned-in-openmp-for.html

This link suggests earlier VS 2019 versions didn't produce expected functionality with an OpenMP for loop that used an unsigned int as an index even though it compiled.

Unit test LoadNGEMTest (in DataHandlingTest) has been run successfully on fixed code - these tests execute createEventWorkspace which contains the fix

**To test:**

Load file GEM000005_00_000_short.edb into a workspace in MantidPlot. The file is in the unit testing file set (in mantid\build\ExternalData\Testing\Data\UnitTest\)

Fixes #26919. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/DataHandling/src/LoadNGEM.cpp [hunk 1]
```diff
@@ -112,11 +112,10 @@ void createEventWorkspace(const int &maxToF, const double &binWidth,
   dataWorkspace = DataObjects::create<DataObjects::EventWorkspace>(
       NUM_OF_SPECTRA, HistogramData::Histogram(HistogramData::BinEdges(xAxis)));
   PARALLEL_FOR_NO_WSP_CHECK()
-  for (size_t i = 0; i < events.size(); ++i) {
+  for (int i = 0; i < events.size(); ++i) {
```
Comment (martyngigg) [inline Framework/DataHandling/src/LoadNGEM.cpp]: Thanks for fixing this. The current build problems are due to the Linux compilers producing a warning that there is a unsigned compared with a signed number in `i < events.size()` as `.size` returns an unsigned.

This basically forces us to always write these loops as:

```
  for (int64_t i = 0; i < static_cast<int64_t>(events.size()); ++i) {
```

We cast the size to `int64` to make sure that we don't cut off the size if it is over what would fit in a 32-bit `int`.

**Review by martyngigg — CHANGES_REQUESTED** [review]
Thanks for finding and fixing this and also providing a clear explanation of how the issue happened.

The only issue to clear up is the problem as mentioned with the warning produced by the Linux/macOS compilers.

File: Framework/DataHandling/src/LoadNGEM.cpp (hunk 1 above)
Comment (DannyHindson) [reply Framework/DataHandling/src/LoadNGEM.cpp]: OK thanks. The index i is subsequently used to set the spectrum number and detector number in the workspace (setSpectrumNo and setDetectorID) so it will have to end up as a 32 bit int. 

Looking a bit further around that unit the events vector and the workspace that is being created are both set up to be of size NUM_OF_SPECTRA which is an int constant. I will change the for loop to iterate up to NUM_OF_SPECTRA and set the for loop index to be int. Please let me know if that looks better once I've done the change

Comment (DannyHindson) [reply Framework/DataHandling/src/LoadNGEM.cpp]: I've pushed the change I described earlier and all the checks pass now apart from "Ubuntu + Doc Tests" which fails on this (which isn't obviously related to me):
LiveDataTest_KafkaHistoStreamDecoderTest

13:26:42 Running 1 testFacilityInfo-[Notice] No timezone specified for TEST in Facilities.xml
13:26:42 
13:26:42 In KafkaHistoStreamDecoderTest::test_Histo_Stream:
13:26:42 /jenkins_workdir/workspace/pull_requests-ubuntu/Framework/LiveData/test/KafkaHistoStreamDecoderTest.h:80: Error: Test failed: Decoder's data buffers should be created now
13:26:42 /jenkins_workdir/workspace/pull_requests-ubuntu/Framework/LiveData/test/KafkaHistoStreamDecoderTest.h:80: Error: Assertion failed: decoder->hasData()
13:26:42 /jenkins_workdir/workspace/pull_requests-ubuntu/Framework/LiveData/test/KafkaHistoStreamDecoderTest.h:81: Error: Test failed: No message to process yet.
13:26:42 /jenkins_workdir/workspace/pull_requests-ubuntu/Framework/LiveData/test/KafkaHistoStreamDecoderTest.h:81: Error: Expected (workspace = decoder->extractData()) not to throw, but it did
13:26:42 /jenkins_workdir/workspace/pull_requests-ubuntu/Framework/LiveData/test/KafkaHistoStreamDecoderTest.h:87: Error: Test failed: Expected non-null workspace pointer from extractData()
13:26:42 /jenkins_workdir/workspace/pull_requests-ubuntu/Framework/LiveData/test/KafkaHistoStreamDecoderTest.h:87: Error: Assertion failed: workspace
13:26:42 /jenkins_workdir/workspace/pull_requests-ubuntu/Framework/LiveData/test/KafkaHistoStreamDecoderTest.h:91: Error: Test failed: Expected a Workspace2D from extractData(). Found something else
13:26:42 /jenkins_workdir/workspace/pull_requests-ubuntu/Framework/LiveData/test/KafkaHistoStreamDecoderTest.h:91: Error: Assertion failed: histoWksp
13:26:42 Segmentation fault

Comment (martyngigg) [reply Framework/DataHandling/src/LoadNGEM.cpp]: Good point about the maximum size being fixed. I'd forgotten this was for a very specific detector configuration.

As you may have noted already as the job passes now we have a couple of tests in the system that seem to have some instability in them. They always run find on developers machines on their own but occasionally when run in parallel on builders they fail.

**Comment by martyngigg** [comment]
The fix looks good now. We're trying to keep the git history quite flat and uncluttered. Would you be able to use `rebase` to drop all but the last commit?

**Comment by DannyHindson** [comment]
OK I've consolidated the commits using a rebase and pushed this to GitHub. 

After doing a rebase on the branch in my local repository I wasn't able to push this up to GitHub so I did a push with the --force option in the end. If this should work without the --force option then let me know and I'll avoid this in future. Perhaps I did the wrong thing in the interactive rebase when I choosing which commit to retain

**Comment by martyngigg** [comment]
@DannyHindson That's great - thanks.

You do have to do `--force` in these situations as it overwrites the other work and `git` wants to force you to acknowledge that. For our work we generally work on our branches alone so overwriting is okay in those circumstances. These days git does have a slightly safer option: `--force-with-lease` which will only allow the push if the remote branch looks the same as yours, i.e. no one has made any changes to it. We tend to use this flag instead.

**Review by martyngigg — APPROVED** [review]
