### PR TITLE
Fix bug in ConvertToReflectometryQ

### LINKED ISSUE #14279: Fix another bug in ConvertToReflectometryQ
There are still some NaN's at the edge on the (Qx,Qz) plot (see image below):

nansattheedge

This figure was produced running the following script:

```
workspace_name = "POLREF4699"
workspace_nexus_file = workspace_name + ".nxs"

Load(Filename=workspace_nexus_file,OutputWorkspace=workspace_name)
X = mtd[workspace_name]
X = ConvertUnits(InputWorkspace=X,Target="Wavelength",AlignBins="1")
# Reference intensity to normalise by
CropWorkspace(InputWorkspace=X,OutputWorkspace='Io',XMin=0.8,XMax=14.5,StartWorkspaceIndex=2,EndWorkspaceIndex=2)
# Crop out transmission and noisy data
CropWorkspace(InputWorkspace=X,OutputWorkspace='D',XMin=0.8,XMax=14.5,StartWorkspaceIndex=3)
Io=mtd['Io']
D=mtd['D']

# Peform the normalisation step
Divide(LHSWorkspace=D,RHSWorkspace=Io,OutputWorkspace='I',AllowDifferentNumberSpectra='1',ClearRHSWorkspace='1')
I=mtd['I'][0]

# Move the detector so that the detector channel matching the reflected beam is at 0,0
PIX = 1.1E-3 #m
SC = 75
avgDB = 29
zOffset = -PIX * ((SC - avgDB) * 0.5 + avgDB)
MoveInstrumentComponent(Workspace = I, ComponentName = "lineardetector", X = 0, Y = 0, Z = zOffset)

# Should now have signed theta vs Lambda
ConvertSpectrumAxis(InputWorkspace=I,OutputWorkspace='SignedTheta_vs_Wavelength',Target='signed_theta')

qxqy, vertexes_qxqy = ConvertToReflectometryQ(InputWorkspace='SignedTheta_vs_Wavelength', OutputDimensions='Q (lab frame)', Extents='-0.0001,0.0001,0,0.03', OutputAsMDWorkspace=False,Method='NormalisedPolygon')
```

However, the expected result should be more similar to:

nonansattheedge

The problem is that quadrilaterals created in `CalculateReflectometryQxQz::createQuad()` are not properly ordered, that is, the first vertex forming the polygon is not always the `ll` (lower left) vertex.

### LINKED ISSUE #14297: Add progress report in algorithms: SumNeighbours, DgsReduction, HFIRLoad, HFIRSANSNormalise
These algorithm don't seem to report progress.

There are some examples in the usage examples / doc tests that could be used to work on this ticket/issue.

For an example of algorithm that does report progress status, see SumSpectra or Rebin. I think that those two are good examples.

This may be helpful:

C++ API doxygen page: http://doxygen.mantidproject.org/nightly/de/dd6/classMantid_1_1API_1_1Progress.html
Python: http://www.mantidproject.org/PythonAlgorithm_Progress_Reporting

### PR DESCRIPTION
**Pull request by raquelalvarezbanos**
Fixes #14279

To test: code review. Run the first example in the algorithm's documentation, you should get something similar to the following graph:

reflectometryresults

Release notes: http://www.mantidproject.org/index.php?title=Release_Notes_3_6_Reflectometry&diff=25512&oldid=25467

### CODE REVIEW

File: Framework/DataObjects/src/FractionalRebinning.cpp [hunk 1]
```diff
@@ -20,7 +20,8 @@ namespace FractionalRebinning {
 
 /**
  * Find the possible region of intersection on the output workspace for the
- * given polygon. The given polygon must have a CLOCKWISE winding.
+ * given polygon. The given polygon must have a CLOCKWISE winding and the
```
Comment (OwenArnold) [inline Framework/DataObjects/src/FractionalRebinning.cpp]: Thanks for recording this. Hopefully it will make other peoples lives easier now.

File: Framework/Geometry/src/Math/Quadrilateral.cpp [hunk 2]
```diff
@@ -156,5 +156,16 @@ ConvexPolygon Quadrilateral::toPoly() const {
   return ConvexPolygon(points);
 }
 
+/// Shifts the vertexes in a clockwise manner
+void Quadrilateral::shiftVertexesClockwise() {
+
```
Comment (OwenArnold) [inline Framework/Geometry/src/Math/Quadrilateral.cpp]: As a clean-up task. A better function would be one that simply rearranged the vertexes to be in the right order for the intersection algorithms. Something like `orderClockwise()` and `isOrderedClockwise()` may be good names. I would also suggest adding a static public constructional method, called `makeClockwise()`, which called the existing constructor and returned the created object, but did everything necessary to put the vertexes in the right place.

**Comment by OwenArnold** [comment]
A good piece of detective work to solve this.
