### PR TITLE
17454 build without ph

### LINKED ISSUE #17454: Mantid is not building on Windows without precompiled headers
If one tries to build recent Mantid without pre-compiled headers, build fails. 

### Platforms affected
Discovered on Windows 10

### PR DESCRIPTION
**Pull request by abuts**
This should enable building Mantid under windows without precompiled headers enabled. 

**To test:**
Test by code review. Changes are trivial. 

You probably need windows, VS2015 SP3 to test it properly, then when building with cmake you should disable precompiled headers. Current mantid build fails before changes but you can trust me -- it works after the changes. 

Fixes #17454.

Internal, no release notes are necessary.

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: MantidPlot/src/WindowFactory.h [hunk 1]
```diff
@@ -14,6 +14,7 @@
 #include <cstring>
 #include <map>
 #include <vector>
+#include <iterator>
```
Comment (peterfpeterson) [inline MantidPlot/src/WindowFactory.h]: This doesn't look like it belongs in this PR

Comment (abuts) [inline MantidPlot/src/WindowFactory.h]: It does belongs to it -- it need <iterator> to compile without PH

File: Framework/DataHandling/inc/MantidDataHandling/LoadEventNexus.h [hunk 2]
```diff
@@ -7,14 +7,21 @@
...
 #include "MantidDataObjects/Events.h"
 #include "MantidAPI/WorkspaceGroup.h"
 #include "MantidGeometry/Instrument.h"
 #include "MantidGeometry/Instrument/ParameterMap.h"
 #include "MantidKernel/TimeSeriesProperty.h"
 #include "MantidDataHandling/EventWorkspaceCollection.h"
+
+#ifdef _WIN32 // fixing windows issue causing conflict between
+// winnt char and nexus char
+#undef CHAR
```
Comment (DavidFair) [inline Framework/DataHandling/inc/MantidDataHandling/LoadEventNexus.h]: Where is `CHAR` defined - I've looked and it's not a standard define from the [MSVC compiler](https://msdn.microsoft.com/en-us/library/b0084kay.aspx) and grepping for `#define CHAR` isn't revealing anything? 
Although it's extremely unlikely if anyone relies on the previous definition of `CHAR` and Nexus `CHAR` redefines it by doing this it could lead to issues.

Comment (abuts) [inline Framework/DataHandling/inc/MantidDataHandling/LoadEventNexus.h]: char conflicting with nexus is defined in winnt.h and its probably the windows compiler bug as nexus char is defined in nexus namespace.  
The compiler bug is probable as it works fine if precompiled headers are enabled but fails if they are not. 
Despite that, you still need to be clever to be able to compile this piece of code without precompiled headers.

**Comment by DavidFair** [comment]
Builds on Windows 10 with Visual Studio 2015 Update 3 so it resolves the issue. :shipit:

File: Framework/DataHandling/inc/MantidDataHandling/LoadEventNexus.h (hunk 2 above)
Comment (martyngigg) [inline Framework/DataHandling/inc/MantidDataHandling/LoadEventNexus.h]: I think it might be better to remove the `nexus` includes from this header and just forward declare the `::NeXus::File` class

Comment (abuts) [inline Framework/DataHandling/inc/MantidDataHandling/LoadEventNexus.h]: I tried this -- does not work or have not find a way to make it working. 

The conflict occurs when ::Nexus templates are instantiated within ProcessBankData.c where winnt. and nexus.hpp definitions are clashing. 

Naturally I can not predefine only ::Nexus::file as more nexus objects are defined in this header, requering full definition.

File: Framework/DataHandling/src/ProcessBankData.cpp [hunk 3]
```diff
@@ -1,6 +1,6 @@
 #include "MantidDataHandling/ProcessBankData.h"
-#include "MantidDataHandling/LoadEventNexus.h"
-#include "MantidDataObjects/Events.h"
+
+//#include "MantidDataObjects/Events.h"
```
Comment (quantumsteve) [inline Framework/DataHandling/src/ProcessBankData.cpp]: Why are you keeping commented out code?

Comment (abuts) [inline Framework/DataHandling/src/ProcessBankData.cpp]: that's a leftover -- Initially I was not sure It would compile without and then forget to remove

File: MantidPlot/src/WindowFactory.h (hunk 1 above)
Comment (quantumsteve) [inline MantidPlot/src/WindowFactory.h]: `<iterator>` defines `std::back_inserter(...)`
