### PR TITLE
Fit function available in FqFit depend on type of input data. 

### LINKED ISSUE #36348: Fit functions available on FqFit should depend on the input data
**Original reporter:** Spencer

**Describe the bug**
The fit functions which are made available on the FqFit tab on the Data Analysis interface should be dependent on the type of data which is loaded. If EISF data is loaded, then the fit functions beginning with EISF should be the only functions made available. If FWHM  data is loaded, then the fit functions not beginning with EISF should be the only functions made available.

**To Reproduce**
On the ConvFit tab
1. Load a sample and resolution from the sample dataset
2. Load in 0-5 spectra
3. Select 2 lorentzians
4. Click Run and wait
5. There should be a results workspace in the ADS

Then on FqFit:
1. Load the results workspace
2. All fit functions are available, no matter if FWHM or EISF data is selected

**Expected behavior**
If EISF data is loaded, then the fit functions beginning with EISF should be the only functions made available. If FWHM  data is loaded, then the fit functions not beginning with EISF should be the only functions made available.

### PR DESCRIPTION
**Pull request by adriazalvarez**
### Description of work
 The selectable fit functions on the drop-down list of the function browser on the FqFit tab on the Data Analysis interface are made to be dependent on the type of data which is loaded. If EISF data is loaded, then the fit functions beginning with EISF are the only functions made available. If FWHM  data is loaded, then the fit functions not beginning with EISF are the only functions made available.

#### Summary of work

The functions are updated in the fit property browser widget of the tab, which is in no direct communication with the data presenter, where new data is added. To avoid using QSignals, I have tried the following approach, not sure if is the more elegant way, or there are better ways to handle this: 
- The fit property browser widget class contains the function template browser, which handles the fit functions. I have added a function in the class to update the function list which are made available when the tab is created.
- Subscribe a pointer of the fit property browser to the presenter.
- Update the function list whenever a type of data (WIDTH or EISF) is added to the tab, to the appropiate subfunction list. These subfunctions are already defined in the `FitTabConstants` header.

Fixes #36348 . 

### To test:
On the ConvFit tab
1. Load a sample and resolution from the sample dataset:`irs26173_graphite002`.
2. Load in 0-5 spectra.
3. Select 2 lorentzians.
4. Click Run and wait
5. There should be a `_results` workspace in the ADS.

Then on FqFit:
1. Load the results workspace
2. Only FWHM functions are available (without EISF prefix)

Again on ConvFit tab
1. Load a sample and resolution from the sample dataset:`irs26173_graphite002`.
2. Load in 0-5 spectra.
3. Select 2 lorentzians.
4. Tick `Delta Function` checkbox as `True` in the Function Property list. 
5. Run and wait
6. There should be a `Delta_..._results` workspace in the ADS.

Back on FqFit:
1. Load the `Delta_..._results` workspace selecting `EISF` as a parameter type in the add workspace dialog window.
2. Only EISF functions are available.

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by robertapplin — CHANGES_REQUESTED** [review]
Really nice and neat changes, I think its a good idea the way you have subscribed the browser to the FqFitDataPresenter. The only thing I would suggest is to create an interface class for the `IndirectFitPropertyBrowser`, but only with the one function we need (`updateFunctionListInBrowser`). In the future we can then add to this interface class as and when needed.

Then I would suggest creating a `MockIndirectFitPropertyBrowser` which inherits from the interface, and use this in the test suite. This would be a better way of doing things because it makes it easier to test the `FqFitDataPresenter` class in isolation from its dependencies

**Comment by robertapplin** [comment]
Just did some functional testing and I think its almost there. One thing I noticed:

1. Load this dataset. Add a Width and an EISF spectrum from this dataset 
[IN16B_125878_QLd_Result.zip](https://github.com/mantidproject/mantid/files/13890506/IN16B_125878_QLd_Result.zip)

2. Check which spectrum you have selected in the `Plot Spectrum` combo box
3. Check the functions in the list
4. Change the `Plot Spectrum` to a different spectrum
5. The functions in the list remain the same.

File: qt/scientific_interfaces/Inelastic/Analysis/FqFitDataPresenter.h [hunk 1]
```diff
@@ -53,12 +55,14 @@ class MANTIDQT_INELASTIC_DLL FqFitDataPresenter : public IndirectFitDataPresente
   void updateParameterOptions(FqFitAddWorkspaceDialog *dialog, const FqFitParameters &parameters);
   void updateParameterTypes(FqFitAddWorkspaceDialog *dialog, FqFitParameters &parameters);
   std::vector<std::string> getParameterTypes(FqFitParameters &parameters) const;
+  std::map<std::string, std::string> chooseFqFitFunctions(bool paramWidth);
```
Comment (robertapplin) [inline qt/scientific_interfaces/Inelastic/Analysis/FqFitDataPresenter.h:58]: Can this function be `const`?

File: qt/scientific_interfaces/Inelastic/Analysis/FqFitDataPresenter.cpp [hunk 2]
```diff
@@ -228,12 +232,15 @@ void FqFitDataPresenter::addWorkspace(const std::string &workspaceName, const st
   const auto name = getHWHMName(workspace->getName());
   const auto parameters = createFqFitParameters(workspace);
   const auto spectrum = getParameterSpectrum(parameters);
+  auto fqFitFunctionList = chooseFqFitFunctions(paramType == "Width");
```
Comment (robertapplin) [inline qt/scientific_interfaces/Inelastic/Analysis/FqFitDataPresenter.cpp:235]:
```suggestion
  const auto fqFitFunctionList = chooseFqFitFunctions(paramType == "Width");
```

File: qt/scientific_interfaces/Inelastic/Analysis/IIndirectFitDataView.h [hunk 3]
```diff
@@ -42,6 +43,7 @@ class MANTIDQT_INELASTIC_DLL IIndirectFitDataView {
   virtual void clearTable() = 0;
   virtual QString getText(int row, int column) const = 0;
   virtual QModelIndexList getSelectedIndexes() const = 0;
+  virtual bool DataColumnContainsText(QString text) const = 0;
```
Comment (robertapplin) [inline qt/scientific_interfaces/Inelastic/Analysis/IIndirectFitDataView.h:46]: This is very picky, but can the first letter in this function name be lower case?

Comment (robertapplin) [reply qt/scientific_interfaces/Inelastic/Analysis/IIndirectFitDataView.h:46]: Can you also change the parameter to be a `std::string const &`? Currently the `text` parameter is being passed in by value, meaning each time a parameter is passed in a copy is made https://www.ibm.com/docs/en/zos/2.4.0?topic=calls-pass-by-reference-c-only

File: qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataView.cpp [hunk 4]
```diff
@@ -179,6 +179,14 @@ void IndirectFitDataView::setCell(std::unique_ptr<QTableWidgetItem> cell, size_t
   m_uiForm->tbFitData->setItem(static_cast<int>(row), static_cast<int>(column), cell.release());
 }
 
+bool IndirectFitDataView::DataColumnContainsText(QString columnText) const {
+  if (!m_uiForm->tbFitData->findItems(columnText, Qt::MatchContains).isEmpty()) {
+    return true;
+  } else {
+    return false;
+  };
```
Comment (robertapplin) [inline qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataView.cpp:187]: This can be simplified
```suggestion
  return !m_uiForm->tbFitData->findItems(columnText, Qt::MatchContains).isEmpty();
```

File: qt/scientific_interfaces/Inelastic/test/Analysis/FqFitDataPresenterTest.h [hunk 5]
```diff
@@ -63,25 +64,30 @@ class FqFitDataPresenterTest : public CxxTest::TestSuite {
     m_presenter = std::make_unique<FqFitDataPresenter>(m_tab.get(), m_model.get(), m_view.get());
     m_workspace = createWorkspaceWithTextAxis(6, getTextAxisLabels());
     m_ads = std::make_unique<SetUpADSWithWorkspace>("WorkspaceName", m_workspace);
+    m_fitPropertyBrowser = std::make_unique<NiceMock<MockFitPropertyBrowser>>();
+    m_presenter->subscribeFitPropertyBrowser(std::move(m_fitPropertyBrowser.get()));
```
Comment (robertapplin) [inline qt/scientific_interfaces/Inelastic/test/Analysis/FqFitDataPresenterTest.h:68]: In this case the `std::move` doesn't do anything because we are passing in a raw non-owning pointer. Plus we also don't want the presenter to own the browser, just have a pointer to it
https://stackoverflow.com/questions/3413470/what-is-stdmove-and-when-should-it-be-used

File: qt/scientific_interfaces/Inelastic/Analysis/FqFitDataPresenter.cpp [hunk 6]
```diff
@@ -246,6 +253,21 @@ void FqFitDataPresenter::addWorkspace(const std::string &workspaceName, const st
   }
 }
 
+std::map<std::string, std::string> FqFitDataPresenter::chooseFqFitFunctions(bool paramWidth) {
+  if (m_view->isTableEmpty()) { // when first data is added to table, it can only be either WIDTH or EISF
+    return paramWidth ? FqFit::WIDTH_FITS : FqFit::EISF_FITS;
+  } else {
```
Comment (robertapplin) [inline qt/scientific_interfaces/Inelastic/Analysis/FqFitDataPresenter.cpp:259]: Nice use of a ternary operator 👍 In this case we technically don't need the `else` because this function will return anyway if we enter the if statement. Sometimes not using an `else` can mean we can de-dent some of our code and make it more readable

**Review by robertapplin — CHANGES_REQUESTED** [review]
Thanks for the changes, its looking really good! Just had a few more suggestions we could do

File: qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataView.cpp (hunk 4 above)
Comment (adriazalvarez) [reply qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataView.cpp:187]: You are totally right.

File: qt/scientific_interfaces/Inelastic/Analysis/FqFitDataPresenter.cpp (hunk 6 above)
Comment (adriazalvarez) [reply qt/scientific_interfaces/Inelastic/Analysis/FqFitDataPresenter.cpp:259]: Thanks for letting me know. I agree is not necessary, but I would have though is better to have in this case.

File: qt/scientific_interfaces/Inelastic/Analysis/IIndirectFitDataView.h (hunk 3 above)
Comment (adriazalvarez) [reply qt/scientific_interfaces/Inelastic/Analysis/IIndirectFitDataView.h:46]: We are going to erradicate all QString from Mantid. :)

File: qt/scientific_interfaces/Inelastic/test/Analysis/FqFitDataPresenterTest.h (hunk 5 above)
Comment (adriazalvarez) [reply qt/scientific_interfaces/Inelastic/test/Analysis/FqFitDataPresenterTest.h]: I'm trying to do that in the latest commit, but if `m_fitpropertybrowser` is not unique pointer, the test throws an exception, do you know why?

Comment (robertapplin) [reply qt/scientific_interfaces/Inelastic/test/Analysis/FqFitDataPresenterTest.h]: I think we want to keep `m_fitPropertyBrowser` as a unique pointer, but on the subscribe line we want to do:
```
m_presenter->subscribeFitPropertyBrowser(m_fitPropertyBrowser.get());
```
(i.e. without the `std::move`) because we don't want the presenter to own the browser. Instead we want the TestSuite to own the browser. Does this work?

Comment (adriazalvarez) [reply qt/scientific_interfaces/Inelastic/test/Analysis/FqFitDataPresenterTest.h]: No, it seems it doesn't work with that syntax either.

**Review by robertapplin — CHANGES_REQUESTED** [review]
The code changes look great, and the fit functions now change depending on if EISF or Width spectra are loaded. If both types are loaded, then all fit functions are allowed - and I think this makes good sense

Can you add a release note? I'm happy to approve after this

**Review by robertapplin — APPROVED** [review]
