### PR TITLE
Engg:: Enable Fitting tab to accept cropped and texture files

### LINKED ISSUE #17241: Engg:: Enable fitting tab to accept cropped/textured files
Currently if you try to enter a cropped or textured focus file in
Custom Interfaces -> Engineering Diffraction -> Fitting and hit fit
Mantid will crash as certain assumptions are made about it in `setDifcTzero(focusedWS)`.

### PR DESCRIPTION
**Pull request by shahrozahmed1**
**Description of work.**

User now will be able to provide a cropped or texture workspace as an input for the Fitting Tab.
The algorithm SaveDiffFittingAscii will be utilised and will be saving the output as `csv` file in the following folder: C:\EnginX_Mantid\User<RB-Number>\SinglePeakFitting\ according to the run number of the cropped or texture file.

**To test:**

Focused files can be found here: `\\olympic\Babylon5\Public\Shahroz\`
Make sure you can find the texture and cropped files in directory above.

**Test 1**
Go to: `Interfaces/Diffraction/Engineering Diffraction/Fitting Tab`

Browse the file `ENGINX_256663_focused_cropped.nxs`
Bank widget should be updated to `cropped`
Click `Fit` button once it has been enabled
Upon completion, please checks that Fitting results has been saved in the following directory `C:\EnginX_Mantid\User\<RB-Number>\SinglePeakFitting` with the following format `ENGINX_1256663_Single_Peak_Fitting.csv` with bank name set as `customised`

**Test 2**
Go to: `Interfaces/Diffraction/Engineering Diffraction/Fitting Tab`

Browse the file `ENGINX_256664_focused_texture_bank_3.nxs`
Bank widget should be updated to 3
Click `Fit` button once it has been enabled
Upon completion, please checks that Fitting results has been saved in the following directory `C:\EnginX_Mantid\User\<RB-Number>\SinglePeakFitting` with the following format `ENGINX_256664_Single_Peak_Fitting.csv` with bank name set as `customised`

Fixes #17241
_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp [hunk 1]
```diff
@@ -367,20 +382,19 @@ void EnggDiffFittingPresenter::processSingleRun(
...
-    std::vector<std::string> &fittingRunNoDirVec) {
+    const std::string &focusDir, const std::string &runNumberVec,
+    std::vector<std::string> &fittingRunNoDirVec,
+    std::vector<std::string> &foundRunNumber) {
 
   try {
-    std::string cwd(bankDir);
+    bool found = false;
+
+    std::string cwd(focusDir);
```
Comment (DavidFair) [inline MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp]: Could be `const`

File: MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp [hunk 2]
```diff
@@ -367,20 +382,19 @@ void EnggDiffFittingPresenter::processSingleRun(
...
     Poco::DirectoryIterator it(cwd);
     Poco::DirectoryIterator end;
```
Comment (DavidFair) [inline MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp]: Does `end` need to be initialised or is this implicitly constructed?

File: MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp [hunk 3]
```diff
@@ -390,19 +404,26 @@ void EnggDiffFittingPresenter::updateFittingDirVec(
...
-          if (g_fitting_runno_counter == 1)
+          if (g_fitting_runno_counter == 1) {
             g_multi_run_directories.push_back(itFilePath);
+          }
         }
       }
       ++it;
     }
+
+    if (found)
```
Comment (DavidFair) [inline MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp]: Wrap in braces

File: MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp [hunk 4]
```diff
@@ -348,15 +358,20 @@ void EnggDiffFittingPresenter::processMultiRun(
 void EnggDiffFittingPresenter::processSingleRun(
     const std::string &focusDir, const std::string &strFocusedFile,
     std::vector<std::string> &runnoDirVector,
-    const std::vector<std::string> &splitBaseName,
-    std::vector<std::string> &runNoVec) {
+    const std::vector<std::string> &splitBaseName) {
+
+  if (g_fitting_runno_counter == 0)
```
Comment (DavidFair) [inline MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp]: Wrap if in braces

File: MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp [hunk 5]
```diff
@@ -288,6 +293,9 @@ void EnggDiffFittingPresenter::browsedFile(
     const std::vector<std::string> &splitBaseName,
     std::vector<std::string> &runNoVec, const std::string &bankFileDir) {
   // to track the FittingRunnoChanged loop number
+  if (g_fitting_runno_counter == 0)
```
Comment (DavidFair) [inline MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp]: Wrap if in braces

File: MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp [hunk 6]
```diff
@@ -444,32 +465,48 @@ void EnggDiffFittingPresenter::enableMultiRun(
             "Please try again");
       } else {
 
+        // clear previous directories set before updateFittingDirVec
+        if (g_fitting_runno_counter == 0)
```
Comment (DavidFair) [inline MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp]: Wrap if in braces

File: MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp [hunk 7]
```diff
@@ -444,32 +465,48 @@ void EnggDiffFittingPresenter::enableMultiRun(
...
         for (size_t i = 0; i < RunNumberVec.size(); i++) {
           // save dir for every vector
-          updateFittingDirVec(focusDir, RunNumberVec[i], fittingRunNoDirVec);
+          updateFittingDirVec(focusDir, RunNumberVec[i], fittingRunNoDirVec,
+                              foundRunNumber);
         }
+
         int diff = (lastNum - firstNum) + 1;
-        auto run_vec_size = RunNumberVec.size();
+        auto run_vec_size = foundRunNumber.size();
```
Comment (DavidFair) [inline MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp]: Could we make this `size_t` instead of `auto`?

File: MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp [hunk 8]
```diff
@@ -1417,7 +1465,7 @@ void EnggDiffFittingPresenter::setDefaultBank(
     m_view->setFittingRunNo(selectedFile);
 }
 
-bool EnggDiffFittingPresenter::isDigit(std::string text) {
+bool EnggDiffFittingPresenter::isDigit(std::string text) const {
   // bool isDig = true;
   for (size_t i = 0; i < text.size(); i++) {
```
Comment (DavidFair) [inline MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp]: This can be turned into
`for ( size_t : text) { `

File: MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp [hunk 9]
```diff
@@ -1467,7 +1470,7 @@ void EnggDiffFittingPresenter::setDefaultBank(
 
 bool EnggDiffFittingPresenter::isDigit(std::string text) const {
   // bool isDig = true;
-  for (size_t i = 0; i < text.size(); i++) {
+  for (auto i : text) {
     char *str = &text[i];
```
Comment (DimitarTasev) [inline MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp]: @DavidFair Does this work? `auto i` gives you the character, it fails horribly in MingW: http://prntscr.com/c8uv2z

Comment (FedeMPouzols) [inline MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp]: Yes, I'd say that you'd use `i` which is the character directly as the parameter to `isdigit()`.

File: MantidQt/CustomInterfaces/inc/MantidQtCustomInterfaces/EnggDiffraction/EnggDiffFittingPresenter.h [hunk 10]
```diff
@@ -139,7 +139,7 @@ protected slots:
   void fittingRunNoChanged();
 
 private:
-  bool isDigit(std::string text);
+  bool isDigit(std::string text) const;
```
Comment (FedeMPouzols) [inline MantidQt/CustomInterfaces/inc/MantidQtCustomInterfaces/EnggDiffraction/EnggDiffFittingPresenter.h]: `const std::string &text` as this is only input.

File: MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp [hunk 11]
```diff
@@ -348,15 +359,21 @@ void EnggDiffFittingPresenter::processMultiRun(
...
   // to track the FittingRunnoChanged loop number
   g_fitting_runno_counter++;
 
   m_view->setFittingSingleRunMode(true);
 
-  updateFittingDirVec(focusDir, strFocusedFile, runnoDirVector);
+  // dummy vector will not be used
+
+  std::vector<std::string> foundRunNumber;
+  updateFittingDirVec(focusDir, strFocusedFile, runnoDirVector, foundRunNumber);
```
Comment (FedeMPouzols) [inline MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp]: Would there be a way to avoid the use of this "dummy".

File: MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp [hunk 12]
```diff
@@ -444,32 +468,48 @@ void EnggDiffFittingPresenter::enableMultiRun(
...
+          g_multi_run_directories.clear();
+        }
         // to track the FittingRunnoChanged loop number
         g_fitting_runno_counter++;
 
-        // if given a multi run number instead
+        // rewrite the vector of run number which is available
+        std::vector<std::string> foundRunNumber;
+
         for (size_t i = 0; i < RunNumberVec.size(); i++) {
```
Comment (FedeMPouzols) [inline MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp]: This loop can be range-based?

File: MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp (hunk 9 above)
Comment (FedeMPouzols) [inline MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp]: And I think it can be `const auto`

File: MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp (hunk 11 above)
Comment (DavidFair) [inline MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp]: We could use a default parameter however I'm trying to think of a way we can hint to the compiler not to create this variable as it won't be used or if it will be smart enough to figure that out

Comment (DimitarTasev) [inline MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp]: Could you create it inside the function only if it finds something, so in the case of nothing found you could return a nullptr and then check for that later?

Comment (FedeMPouzols) [inline MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffFittingPresenter.cpp]: When following the code we've agreed that a few places would benefit from some general code refactoring. An issue has been created for this: #17301.

**Comment by FedeMPouzols** [comment]
This works well, tested with several test focused ENGINX file. Error conditions are checked and error messages are informative.
The code has been polished as well, and more work will continue in #17301.

:shipit:
