### PR TITLE
FindSXPeaks - Support grouped detectors

### LINKED ISSUE #19503: FindSXPeaks now throws error for instruments with grouped detectors
`FindSXPeaks` algorithm no longer works for instruments such as WISH that have hardware grouped detectors. 

### Expected behavior
Algorithm should work and find peaks

### Actual behavior
During `spectrumInfo` refactoring in #18554 a check was added to the algorithm that requires the mapping between workspace indicies and detectors to be unique. 

Previously this would use averages of the group for values of phi, theta etc., which for WISH is fine as they spatial close together.

### Steps to reproduce the behavior
Try running `FindSXPeaks` on WISH data

### Platforms affected
All.

### PR DESCRIPTION
**Pull request by DavidFair**
Description of work.
This PR resolves an issue where FindSXPeaks could not supports instruments with multiple detectors per spectra. When we come across multiple detectors we now correctly cast to a `DetectorGroup` and call `getPhi` which get the average `phi` value of all detectors.

Additionally I have added a validator to make sure only TOF data is used as previously it performed no validation.

**To test:**
*You will need minimum 16GB of RAM*
- Load a WISH data file - such as the following
`LoadRaw(Filename='WISH00036238.raw', OutputWorkspace='36238', LoadLogFiles=False)`
- Run `FindSXPeaks` on the workspace
- Open the loaded file in the instrument view, and drag the table workspace onto the view
- Check the peak positions look sane by clicking on some, and the within the peak plot (bottom left) the peak with the highest intensity is labelled.

For the validator:
- Create a sample workspace with units not TOF
- Ensure that the algorithm does not accept this workspace unless it has TOF units. 

Fixes #19503 .

Added to release notes here: [here](https://github.com/mantidproject/mantid/blob/7ee78a6f2fa2585fa73f1e7b0be87162046e1a09/docs/source/release/v3.10.0/diffraction.rst)

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by samueljackson92 — DISMISSED** [review]
Algorithm now works as expected. A couple of minor points from code review.

File: Framework/Crystal/src/FindSXPeaks.cpp [hunk 1]
```diff
@@ -152,26 +206,27 @@ void FindSXPeaks::exec() {
...
-    // If no detector found, skip onto the next spectrum
-    if (!spectrumInfo.hasDetectors(static_cast<size_t>(i))) {
-      continue;
-    }
-    if (!spectrumInfo.hasUniqueDetector(i)) {
-      std::ostringstream sout;
-      sout << "Spectrum at workspace index " << i
-           << " has unsupported number of detectors.";
-      throw std::runtime_error(sout.str());
+    double phi = -999;
```
Comment (DavidFair) [inline Framework/Crystal/src/FindSXPeaks.cpp]: It was for testing. Good catch - I think setting it to `inf` would make a good canary value as not many calculations result in infinity (vs `NaN`)

**Comment by KarlPalmen** [comment]
I found a suitable WISH file (I think it was 19610). Load took nearly 5 minutes and FindSXPeaks took about a minute and a half. Peaks were shown on instrument view and after you showed me, were OK.
When checking units validation, I found that the workspace without TOF units was not listed in those available to the algorithm. Memory was freed when Mantid was closed down. :shipit:
