### PR TITLE
Fix an integer overflow issue in LoadBankFromDiskTask

### LINKED ISSUE #22889: LoadEventNeXus fails to load VULCAN's high angle bank of run 163113
SNS/Yan Chen reported that there was signal in reduced GSAS file from /SNS/VULCAN/IPTS-21357/nexus/VULCAN_163113.nxs.h5.

### Expected behavior

Run 163113 lasted for more than 10 hours.  There shall be a regular diffraction pattern on high angle bank.

### Actual behavior

The reduced data shows nothing on high angle bank.

### PR DESCRIPTION
**Pull request by wdzhou**
There is an integer overflow issue in LoadBankFromDiskTask.  This causes a negative number of events to stop the loading process.  Changing the data type to int64_t shall resolve the issue.

It is same as PR #22890, which was based on master.

**Report to:** Yan Chen of SNS

**To test:**

Load /SNS/VULCAN/IPTS-21357/nexus/VULCAN_163113.nxs.h5.  Check number of events in the high angle bank (from spectrum 6469). 

Fixes #22889. 

Does this update require release notes?
- [ ] Yes
- [x] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by peterfpeterson — APPROVED** [review]
Same comments as #22890.

File: Framework/DataHandling/inc/MantidDataHandling/LoadBankFromDiskTask.h [hunk 1]
```diff
@@ -79,9 +79,9 @@ class MANTID_DATAHANDLING_DLL LoadBankFromDiskTask : public Kernel::Task {
   /// Old names in the file?
   bool m_oldNexusFileNames;
   /// Index to load start at in the file
-  std::vector<int> m_loadStart;
+  std::vector<int64_t> m_loadStart;
```
Comment (martyngigg) [inline Framework/DataHandling/inc/MantidDataHandling/LoadBankFromDiskTask.h]: Is there a reason we don't use an unsigned type for the index start/end?

**Comment by martyngigg** [comment]
The ICAT test failure is unrelated.

**Comment by martyngigg** [comment]
I did a stupid thing here. As the ICAT tests failed the RHEL build never got to running the system tests. It looks like this change has picked up an issue with the `BSS_13387_event.nxs` file for basis as it's now failing to load some banks correctly in the most recent [nightly build](http://builds.mantidproject.org/view/Release%20Pipeline/job/release_systemtests-ubuntu-16.04/82/testReport/junit/SystemTests/).
