### PR TITLE
Instrument View: Convert histogram to points when plotting summed detectors

### LINKED ISSUE #23966: 1D plot in instrument view not working
**Original reporter:** Fabio Orlandi ISIS

Mantid Nightly 3.13.20181106.1635

### Expected behavior

When picking a section in instrument view a 1D plot of the spectrum should appear in the instrument viewer.

### Actual behavior

The 1D plot does not materialise.

### Steps to reproduce the behavior

* Load some instrument data e.g. `MARI11060` from the ISIS-Sample data
* Open instrument view
* Go to the `Pick` tab
* Select a region of interest
* There is no spectrum in the plotting widget on the left of the GUI

### Platforms affected

All - Mantid Nightly 3.13.20181106.1635

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

The original instrument view miniplot code used C arrays and passed the length of the Y array as a parameter. In the case of a bin edge X array the last X value was just ignored (technically incorrect). In #23789 the code was updated to use vectors and check on their sizes was introduced. This required them to be equal and exposed the bug that the X bin edges were used for plotting in the case of a detector sum and not the bin centres as they should. This fixes the issue and used bin centres for the summed detector case.

**Report to:** Fabio Orlandi, ISIS

**To test:**

See the original issue for test instructions.

Fixes #23966 

*This does not require release notes* because **as it was a regression introduced in this development cycle.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/widgets/instrumentview/src/InstrumentActor.cpp [hunk 1]
```diff
@@ -598,15 +598,15 @@ void InstrumentActor::sumDetectorsRagged(const std::vector<size_t> &dets,
...
+    const auto &firstY = ws->y(0);
+    x.assign(commonX.begin(), commonX.end());
+    y.assign(firstY.begin(), firstY.end());
 
     // add the spectra
     for (size_t i = 0; i < nSpec; ++i) {
-      const auto &Y = ws->y(i);
-      std::transform(y.begin(), y.end(), Y.begin(), y.begin(),
+      const auto &specY = ws->y(i);
+      std::transform(y.begin(), y.end(), specY.begin(), y.begin(),
```
Comment (soininen) [inline qt/widgets/instrumentview/src/InstrumentActor.cpp]: Would it make sense to use `cbegin`, `cend` for the input parameters?

**Review by soininen — CHANGES_REQUESTED** [review]
The miniplot now shows the graph when selecting a ROI in the test data, so I think this works as expected. The code changes make sense, however I still managed to find something to comment on, see below.

**Review by soininen — APPROVED** [review]
