### PR TITLE
Fix Unreliable Access Violation when using QtPropertyBrowser

### LINKED ISSUE #30362: Enable FitScriptGeneratorViewTest
### Description
Find out what is going wrong with `FitScriptGeneratorViewTest` which is an unable test. When it is fixed you can enable it again.

https://builds.mantidproject.org/job/master_clean-windows/1454/testReport/junit/projectroot.qt.widgets/common/MantidQtWidgetsCommonTestQt5_FitScriptGeneratorViewTest/

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
Credit to @martyngigg for helping fix this problem.

This PR fixes an unreliable access violation when opening the `FunctionTreeView`. A similar issue is also present in `FitOptionsBrowser`. It is suspected that the issue might still be present in other areas where `unsetFactoryForManager` is not used in the destructors, there is a separate issue for this #30419.

Its cause was a dangling pointer to a manager object being left behind when destructing a FunctionTreeView. This dangling point was still existing in a global static variable (m_managerToFactoryToViews or m_viewToManagerToFactory) in qtpropertybrowser.cpp. When creating a new instance of FunctionTreeView, the memory location would sometimes be reused,
causing problems.

The solution used to fix this was to do:
```
m_browser->unsetFactoryForManager(m_manager)
```
in the destructor of FunctionTreeView and FitOptionsBrowser.
 
*Release notes are not needed as this is a very unlikely error to happen - it probably hasn't been noticed.*

**To test:**
It has been confirmed that the new `FunctionTreeViewTest` and `FitOptionsBrowserTest` will have previously failed in an unreliable way - these should no longer fail.

Run the `FunctionTreeViewTest`, `FitOptionsBrowserTest` and `FitScriptGeneratorViewTest` many times and make sure it does not fail.
```
ctest --repeat-until-fail 25 -C RelWithDebInfo -R MantidQtWidgetsCommonTestQt5_FitScriptGeneratorViewTest -V
```

A quick test of the indirect data analysis interface is also recommended.

Fixes #30362

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/widgets/common/test/FitOptionsBrowserTest.h [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+    return new FitOptionsBrowserTest;
+  }
+  static void destroySuite(FitOptionsBrowserTest *suite) { delete suite; }
+
+  void setUp() override { m_numberOfTries = 100u; }
+
+  void tearDown() override { m_fitOptionsBrowser.reset(); }
+
+  void
+  test_that_the_FunctionTreeView_can_be_instantiated_many_times_without_instability() {
```
Comment (robertapplin) [inline qt/widgets/common/test/FitOptionsBrowserTest.h:50]: should be `FitOptionsBrowser`

**Review by RichardWaiteSTFC — APPROVED** [review]
Looks good, the tests seem reliable and no problem with opening/closing many instances of muon analysis interface which should be impacted by this. @martyngigg are you happy for this to go into release-next?

**Comment by martyngigg** [comment]
Yep I'm happy. Let's keep an eye on the tests though to ensure we haven't introduced an instability.
