### PR TITLE
Fix ComponentInfo performance Problems 

### LINKED ISSUE #19307: Fix ComponentInfo performance Problems
Changes introduced as part of issue #19015 PR #19153 have caused a dramatic slow down to the performance tests. Particularly for `DiffractionFocussing2TestPerformance` which currently times out due to the extent of the slow down.

### PR DESCRIPTION
**Pull request by OwenArnold**
Use a cache and reuse approach similar to that employed for `DetectorInfo`. So we do not create the `ComponentInfo` parsing the whole instrument tree unless we really need to.

The approach here is to reuse the `ComponentInfo` and `DetectorInfo` on the incoming instrument if it has already been provisioned with them. 

**To test:**

* Code review.
* We expect that performance tests, particularly `DiffractionFocussing2TestPerformance` execute in a similar time to before. Though there will be additional overhead on the first instrument creation when loaded.

Fixes #19307 

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Geometry/inc/MantidGeometry/Instrument/ParameterMap.h [hunk 1]
```diff
@@ -381,8 +388,13 @@ class MANTID_GEOMETRY_DLL ParameterMap {
   /// Pointer to the DetectorInfo object. NULL unless the instrument is
   /// associated with an ExperimentInfo object.
   boost::shared_ptr<const Beamline::DetectorInfo> m_detectorInfo{nullptr};
+  /// Pointer to the ComponentInfo object. NULL unless the instrument is
+  /// associated with an ExperimentInfo object.
+  boost::shared_ptr<const Beamline::ComponentInfo> m_componentInfo{nullptr};
+  /// Component ids.
+  std::vector<Geometry::ComponentID> m_componentIds;
```
Comment (OwenArnold) [inline Framework/Geometry/inc/MantidGeometry/Instrument/ParameterMap.h]: I think that the storage mode here would be something to review as part of another issue. But those internals can be dealt with another time provided they are not causing big performance issues.

**Comment by OwenArnold** [comment]
Release Build OSX. Using a 100*100 detector rectangular bank instrument (`ExperimentInfoTestPerformance`). Here are the timings in microseconds for the relevant parts of `ExperimentInfo::setInstrument`

```
Time to construct Beamline DetectorInfo: 789233
Time to construct API Detectorinfo: 139414
Time to info visit instrument: 309634
Time to construct Beamline ComponentInfo: 5480
```
And if the instrument is provisioned....
```
Time to copy construct Beamline DetectorInfo: 2
Time to construct API Detectorinfo: 161801
Time to copy construct Beamline ComponentInfo: 1
```

File: Framework/Geometry/inc/MantidGeometry/Instrument/ParameterMap.h [hunk 2]
```diff
@@ -346,9 +347,15 @@ class MANTID_GEOMETRY_DLL ParameterMap {
 
   bool hasDetectorInfo() const;
   const Beamline::DetectorInfo &detectorInfo() const;
+  bool hasComponentInfo() const;
+  const Beamline::ComponentInfo &componentInfo() const;
   size_t detectorIndex(const detid_t detID) const;
+  const std::vector<Geometry::ComponentID> &componentIds() const;
   void
   setDetectorInfo(boost::shared_ptr<const Beamline::DetectorInfo> detectorInfo);
+  void setComponentInfo(
```
Comment (martyngigg) [inline Framework/Geometry/inc/MantidGeometry/Instrument/ParameterMap.h]: Is it intentional to take `componentIds` by value?

**Review by martyngigg — COMMENTED** [review]
A few questions...

File: Framework/API/src/ExperimentInfo.cpp [hunk 3]
```diff
@@ -110,6 +111,7 @@ void ExperimentInfo::copyExperimentInfoFrom(const ExperimentInfo *other) {
   //   not here since we just copy the experiment data).
   // - For cached groupings (for MDWorkspaces), grouping was not copied in the
   //   old implementation either.
+  *m_componentInfo = *other->m_componentInfo;
```
Comment (OwenArnold) [inline Framework/API/src/ExperimentInfo.cpp]: This was a bug I noticed.

Comment (martyngigg) [inline Framework/API/src/ExperimentInfo.cpp]: :+1:

File: Framework/API/src/ComponentInfo.cpp [hunk 4]
```diff
@@ -13,16 +13,39 @@ namespace API {
...
+ * Constructor
+ * @brief ComponentInfo::ComponentInfo
+ * @param componentInfo
+ * @param componentIds : r-value reference to ComponentIDs ordered by component
+ * index
+ */
+ComponentInfo::ComponentInfo(
+    const Mantid::Beamline::ComponentInfo &componentInfo,
+    std::vector<Mantid::Geometry::IComponent *> &&componentIds)
+    : m_componentInfo(componentInfo),
```
Comment (OwenArnold) [inline Framework/API/src/ComponentInfo.cpp]: I'm not sure that that would work with the reference collapsing rules, or without adding a universal reference. I've added a `std::move`.  Let me know if you have a better idea.

File: Framework/Geometry/inc/MantidGeometry/Instrument/ParameterMap.h (hunk 2 above)
Comment (OwenArnold) [inline Framework/Geometry/inc/MantidGeometry/Instrument/ParameterMap.h]: It's a good point. As I've commented already, this is something I'd like to revisit at a later point along side some other ownership issues. I doubt this will have much impact on the performance at present, so I would suggest leaving it the way that it is.

Comment (martyngigg) [inline Framework/Geometry/inc/MantidGeometry/Instrument/ParameterMap.h]: :+1:

File: Framework/API/src/ComponentInfo.cpp (hunk 4 above)
Comment (martyngigg) [inline Framework/API/src/ComponentInfo.cpp]: Inside the r-value reference constructor `componentIds` is now an lvalue which should be able to bind to a non-const lvalue reference I think?

This seems to work, for example: 

```
struct Foo {
  Foo(std::vector<int> & ids) : cids(ids) {
     ids = {1,2,3,4,5};
  }
  Foo(std::vector<int> && ids) : Foo(ids) {} 
  std::vector<int> cids;
};

int main() {
    std::vector<int> my_ids;
    {
     Foo f(my_ids);
    }
    std::copy(std::begin(my_ids), std::end(my_ids),
              std::ostream_iterator<int>(std::cout, ","));   
}
```

Demo on [wandbox](https://wandbox.org/permlink/GMO6FlH7vVBpM19R).

Comment (OwenArnold) [inline Framework/API/src/ComponentInfo.cpp]: @martyngigg I'm not convinced the above is doing what you think. My demo on [wandbox](https://wandbox.org/permlink/72jhJCeYgIxzRcVV)
A slight variant of yours...
```
struct Arg {

    Arg(){std::cout << "default constructor called" << std::endl;};
    Arg(const Arg& ){std::cout << "copy constructor called" << std::endl;}
    Arg(Arg&& ){std::cout << "move constructor called" << std::endl;}
};

struct Foo {
  Foo(const Arg & arg) : m_arg(arg) {
     
  }
  Foo(Arg && arg) : Foo(arg) 
  {} 
    
  /*
  // Uncomment. This avoids the copy!
  Foo(Arg && arg) : m_arg(std::move(arg)) //Foo(arg) 
  {} 
  */

  Arg m_arg;
};

int main() {
    
    Arg arg;
    Foo f1{arg};
    
    Foo f2{Arg{}};
}
```

Comment (OwenArnold) [inline Framework/API/src/ComponentInfo.cpp]: Arg&& & becomes Arg&

**Comment by martyngigg** [comment]
@OwenArnold I think is good to go once we fix the formatting.

**Comment by martyngigg** [comment]
:shipit:

LGTM when Jenkins gives its okay.

File: Framework/API/src/ComponentInfo.cpp (hunk 4 above)
Comment (SimonHeybrock) [inline Framework/API/src/ComponentInfo.cpp]: Why not just pass by value and move, instead of having two constructor + `init()`?

File: Framework/API/src/ExperimentInfo.cpp (hunk 3 above)
Comment (SimonHeybrock) [inline Framework/API/src/ExperimentInfo.cpp]: I think actually this could be removed, as well as the line `*m_detectorInfo = *other->m_detectorInfo;` above. `setInstrument()` already handles this, I think?

File: Framework/API/src/ComponentInfo.cpp (hunk 4 above)
Comment (OwenArnold) [inline Framework/API/src/ComponentInfo.cpp]: 👍

File: Framework/API/src/ExperimentInfo.cpp (hunk 3 above)
Comment (OwenArnold) [inline Framework/API/src/ExperimentInfo.cpp]: Ok I'll take a look

**Comment by SimonHeybrock** [comment]
RHEL7 build took a bit long, we should jeep an eye on this. Merging for now.

**Comment by OwenArnold** [comment]
@SimonHeybrock Yes. Something is happening in `VesuvioCommandsTest.BankByBankForwardSpectraNoBackground`. I'm investigating that.
