### PR TITLE
Fix problem determining bounding box of beam

### LINKED ISSUE #32236: Fix bug in calculation of bounding box in MonteCarloAbsorption
**Describe the bug**

There is a bug in calculation of the sample bounding box in MonteCarloAbsorption when the sample shape doesn't contain the origin. The calculation returns an empty box due to an assumption that the "extreme" coordinates along each axis are one positive and one negative value. If they're both positive the calculation fails

This results in an error being generated when running MonteCarloAbsorption during a validation check in BoundingBox.h that the box has non-zero extent in x/y/z:

image

**To Reproduce**

Run this script:
```

from __future__ import (absolute_import, division, print_function)

from mantid.simpleapi import *
import matplotlib.pyplot as plt

def cylinder_sample(workspace, radius, height):
    # Define function to create sample shape
    radius_m = radius/100.
    height_m = height/100.
    xml = '<cylinder id="sample">' \
               '<centre-of-bottom-base x="0.0" y="{0}" z="0.0" />' \
                '<axis x="0.0" y="1.0" z="0" />' \
                '<radius val="{1}" />' \
                '<height val="{2}" />'\
                '</cylinder>'.format(0.5*height_m, radius_m, height_m)
    CreateSampleShape(InputWorkspace=workspace, ShapeXML=xml)
    SetSampleMaterial(workspace, ChemicalFormula=material,
                      SampleNumberDensity=num_density)
    return workspace


def make_sample_workspace():
    # Create a fake workspace with TOF data
    sample_ws = CreateSampleWorkspace(Function='Powder Diffraction',
                                      NumBanks=1,BankPixelWidth=1,XUnit='TOF',
                                      XMin=1000,XMax=10000)
    return sample_ws

def get_montecarlo_results(sample_ws):
    ConvertUnits(InputWorkspace=sample_ws, OutputWorkspace=sample_ws, Target="Wavelength")
    mc_abs_factor = MonteCarloAbsorption(sample_ws, OutputWorkspace='mc_abs_factor')
    mc_abs = sample_ws / mc_abs_factor
    mc_abs.setDistribution(False)
    # create flat S(Q) for vanadium
    X=[0,10,20,30,40]
    Y=[1,1,1,1,1]
    SQ=CreateWorkspace(DataX=X,DataY=Y,UnitX="MomentumTransfer")
    mc_corrections = CalculateMultipleScattering(sample_ws, SofqWorkspace=SQ, NumberScatterings=2)
    # apply ms correction using ratio method
    multi_scatt_ratio = mc_corrections[1]/(mc_corrections[1] + mc_corrections[2])
    mc_ms = sample_ws * multi_scatt_ratio
    # apply absorption correction after ms correction to get total correction
    mc_ms = mc_ms / mc_abs_factor

    return mc_abs, mc_ms


if True: # __name__=="__main__":
    # Set sample workspace with instrument
    sample_ws = make_sample_workspace()

    # Set sample material
    material = 'V'
    num_density = 0.07261
    cyl_height_cm = 4
    cyl_radius_cm = 0.25
    sample_ws = cylinder_sample(sample_ws, cyl_radius_cm, cyl_height_cm)

    # Calculate corrections
    mc_abs, mc_ms = get_montecarlo_results(sample_ws)

```

### PR DESCRIPTION
**Pull request by DannyHindson**
**Description of work.**

When run with a sample that is offset from the origin, the calculation of the beam height and width could result in a beam that didn't overlap with the sample. This caused an error when running the MonteCarloAbsorption algorithm

Have added unit test to cover this scenario and have modified the RectangularBeamProfile
class to expose the min\max points on the beam profile to support this

**To test:**

Run script on attached issue and check it completes without an error

Fixes #32236.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Algorithms/inc/MantidAlgorithms/SampleCorrections/RectangularBeamProfile.h [hunk 1]
```diff
@@ -30,6 +30,15 @@ class MANTID_ALGORITHMS_DLL RectangularBeamProfile final : public IBeamProfile {
   IBeamProfile::Ray generatePoint(Kernel::PseudoRandomNumberGenerator &rng,
                                   const Geometry::BoundingBox &bounds) const override;
   Geometry::BoundingBox defineActiveRegion(const Geometry::BoundingBox &) const override;
+  /// Returns the min point of the profile
+  inline Kernel::V3D minPoint() const { return Kernel::V3D{m_min[0], m_min[1], m_min[2]}; }
+  /// Returns the max point of the profile
+  inline Kernel::V3D maxPoint() const {
+    auto maxPt = Kernel::V3D{m_min[0], m_min[1], m_min[2]};
```
Comment (robertapplin) [inline Framework/Algorithms/inc/MantidAlgorithms/SampleCorrections/RectangularBeamProfile.h:37]: Can this be changed to
```suggestion
    auto maxPt = minPoint();
```
?

File: Framework/Algorithms/inc/MantidAlgorithms/SampleCorrections/RectangularBeamProfile.h [hunk 2]
```diff
@@ -30,6 +30,15 @@ class MANTID_ALGORITHMS_DLL RectangularBeamProfile final : public IBeamProfile {
   IBeamProfile::Ray generatePoint(Kernel::PseudoRandomNumberGenerator &rng,
                                   const Geometry::BoundingBox &bounds) const override;
   Geometry::BoundingBox defineActiveRegion(const Geometry::BoundingBox &) const override;
+  /// Returns the min point of the profile
+  inline Kernel::V3D minPoint() const { return Kernel::V3D{m_min[0], m_min[1], m_min[2]}; }
```
Comment (robertapplin) [inline Framework/Algorithms/inc/MantidAlgorithms/SampleCorrections/RectangularBeamProfile.h:34]: I noticed there is a `m_upIdx`, `m_beamIdx` and `m_horIdx`. Just thought I'd ask whether they can be used here instead of 0, 1 and 2?

**Review by robertapplin — CHANGES_REQUESTED** [review]
The script runs without error and the changes look good. I just have two questions

File: Framework/Algorithms/inc/MantidAlgorithms/SampleCorrections/RectangularBeamProfile.h (hunk 2 above)
Comment (DannyHindson) [reply Framework/Algorithms/inc/MantidAlgorithms/SampleCorrections/RectangularBeamProfile.h:34]: I don't think we can do this although it is something I also wondered about.

I think the m_upIdx and m_horIdx are used to indicate which of the x, y, z axes are up and horizontal. It's normally y up and x horizontal but some instruments use a different convention. The benefit of these fields (I think) is that a user of the RectangularBeamProfile class can call the constructor with a width and a height without needing to know which of the axes corresponds to the width\height.

I think regardless of this choice, the 0th field in m_min always contains a value along the x axis. And the developer calling minPoint() would expect the first (x) element in the returned V3D object to contain an x axis coordinate. So I don't think we can use m_upIdx\m_horIdx here

File: Framework/Algorithms/inc/MantidAlgorithms/SampleCorrections/RectangularBeamProfile.h [hunk 3]
```diff
@@ -30,14 +30,23 @@ class MANTID_ALGORITHMS_DLL RectangularBeamProfile final : public IBeamProfile {
...
```
Comment (robertapplin) [inline Framework/Algorithms/inc/MantidAlgorithms/SampleCorrections/RectangularBeamProfile.h:34]: Now that `m_min` is a `Kernel::V3D`, can we just return `m_min` here?
```suggestion
  inline Kernel::V3D minPoint() const { return m_min; }
```

**Review by robertapplin — CHANGES_REQUESTED** [review]
Thanks for making that change and the clarification. I just have one more question now that `m_min` is a `Kernel::V3D`

File: Framework/Algorithms/inc/MantidAlgorithms/SampleCorrections/RectangularBeamProfile.h (hunk 3 above)
Comment (DannyHindson) [reply Framework/Algorithms/inc/MantidAlgorithms/SampleCorrections/RectangularBeamProfile.h:34]: For some reason, m_min is defined as a std::array<double, 3> so I don't think it will work if I just return m_min. I don't see a good reason for not defining m_min as a V3D but I guess I decided to leave this alone given that I was just adding a couple of get methods to this class.

**Review by robertapplin — APPROVED** [review]
Looks good to go
