### PR TITLE
Prevent crash - missing error handling in `RunCombinationHelper`

### LINKED ISSUE #22383: `ConjoinXRuns` segfaults when giving a `TableWorkspace` input etc (input validation fails)
`ConjoinXRuns` should only receive MatrixWorkspaces or groups of MatrixWorkspaces.

I investigated the input validation for Stitch1DMany that has similar input requirements. And found some differences, then tested the input validation of ConjoinXRuns with a TableWorkspace  and it crashes MantidPlot. The auto generated GUI puts all workspaces in the ADS to the selection list. Then, it is easy to select a wrong workspace type.

Try something like:
ws1 = CreateSampleWorkspace()
ws2 =CreateEmptyTableWorkspace()
ConjoinXRuns(ws1, ws2)

### PR DESCRIPTION
**Pull request by vreimund**
`RunCombinationHelper` did not check, if the input workspaces represent either a GroupWorkspace or alternatively a MatrixWorkspace. This affects today the algorithms `ConjoinXRuns`, `MergeRuns`, and `SumOverlappingTubes`.

Now, it throws a std::runtime_error that need to be catched during input validation in `ConjoinXRuns` (otherwise the GUI freezes). It may be ok for `MergeRuns` and `SumOverlappingTubes` to just throw an error.

If the input workspace is not a group, I added the check if it is a MatrixWorkspace instead. It may be enough to add the workspace name to the std::vector as implemented before.
In `ConjoinXRuns`, I think it is not good to get the name of a workspace if the corresponding pointer does not exist.

**To test:**

```Python
CreateSampleWorkspace(OutputWorkspace='ws')
CreateEmptyTableWorkspace(OutputWorkspace='table')
out = ConjoinXRuns(mtd["table"], mtd["ws"])
```

Fixes #22383.

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Algorithms/test/RunCombinationHelperTest.h [hunk 1]
```diff
@@ -40,6 +40,20 @@ class RunCombinationHelperTest : public CxxTest::TestSuite {
...
+
+    TS_ASSERT_THROWS_EQUALS(
+        m_testee.unWrapGroups(std::vector<std::string>{"ws1", "ws?"}),
+        const std::runtime_error &e, std::string(e.what()),
+        "Unable to find workspace type with name 'ws?': data service  search "
+        "object ws?");
+
+    removeWS("ws1");
+  }
+
```
Comment (josephframsay) [inline Framework/Algorithms/test/RunCombinationHelperTest.h]: Could we also test that trying to conjoin invalid workspaces such as tables throws?

**Review by josephframsay — CHANGES_REQUESTED** [review]
This is a nice fix - the changes look good, and the crash has disappeared in all 3 algorithms. Just one comment about units tests

File: Framework/Algorithms/test/RunCombinationHelperTest.h (hunk 1 above)
Comment (reimundILL) [reply Framework/Algorithms/test/RunCombinationHelperTest.h]: That's true, the std::runtime error with message "The input ... is neither a WorkspaceGroup nor a MatrixWorkspace" should be tested instead.

**Review by josephframsay — APPROVED** [review]

**Comment by josephframsay** [comment]
All looks good to go now!
