### PR TITLE
Fix Mantid crash when deleting many workspaces in MantidDock

### LINKED ISSUE #17729: Fix Mantid crash when closing many workspaces via MantidDock
Rob mentioned that closing about 200 workspaces at once via MantidDock causes a crash. 

**Solution**
Avoid deleting the workspaces via the `DeleteWorkspace` algorithm and clear them instead directly from the ADS.

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
Fixes #17729

We delete the workspaces from the MantidDock directly in the ADS without the indirection of the algorithm.

**To test:**

*\* Test that deleting many workspaces does not crash**
1. Create many wokspaces with:

``` python
for i in range(3000):
    name = "WS_" + str(i)
    CreateSampleWorkspace(OutputWorkspace=name)
```
1. Select all in the ADS
2. Press the delte button
   - Confirm that Mantid does not crash and that the time it takes to clear the 3000 workspaces is  acceptable.

*\* Test that deleting few very large data sets does not disturb the user experience (too much)**
1. Find a sample data set here: smb://olympic/babylon5/Scratch/Anton/SampleWS . The relevant file is MDEvent_ellipPeaks_new.nxs
1. If you have a 16GB computer run the follow script, else you have to modify the times you can load the file.

``` python
for i in range(10):
    name = "WS_" + str(i)
    Load(Filename='PATH_TO/MDEvent_ellipPeaks_new.nxs', OutputWorkspace=name)
```
1. Select all workspace and delete them.
   - Confirm that the time taken is acceptable and that the screen does not freeze. It will be unusable tough.

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: MantidPlot/src/Mantid/MantidUI.cpp [hunk 1]
```diff
@@ -459,10 +459,11 @@ void MantidUI::saveNexusWorkspace() { executeSaveNexus(); }
 @param workspaceName :: Name of the workspace to delete
 */
 void MantidUI::deleteWorkspace(const QString &workspaceName) {
-  auto alg = createAlgorithm("DeleteWorkspace");
-  alg->setLogging(false);
-  alg->setPropertyValue("Workspace", workspaceName.toStdString());
-  executeAlgorithmAsync(alg);
+  auto workspaceNameStdString = workspaceName.toStdString();
```
Comment (martyngigg) [inline MantidPlot/src/Mantid/MantidUI.cpp]: I agree with the swap to calling the ADS directly. Using an algorithm to do this seems like overkill.

File: MantidPlot/src/Mantid/MantidUI.cpp [hunk 2]
```diff
@@ -459,10 +459,11 @@ void MantidUI::saveNexusWorkspace() { executeSaveNexus(); }
...
+  auto &ads = Mantid::API::AnalysisDataService::Instance();
+  if (ads.doesExist(workspaceNameStdString)) {
```
Comment (martyngigg) [inline MantidPlot/src/Mantid/MantidUI.cpp]: Is it necessary to check the existence first? `DataService::remove` does nothing if the name does not exist so this results in a double look up most of the time.

**Review by martyngigg — APPROVED** [review]
I've tested the provided scripts before and after the changes. Before the change I get a crash on Ubuntu if I increase the loop terminator to 5000.

After the changes the deletion happens successfully.

**Comment by martyngigg** [comment]
:shipit:
