### PR TITLE
Mcstas error fix

### LINKED ISSUE #13323: LoadMcstas uncertainties currently all set to 1.0
LoadMcstas sets all uncertainties currently to 1.0.  This is overestimates the error and needs to be fixed.

### PR DESCRIPTION
**Pull request by granrothge**
Adds the ability to populate uncertainties with probability squared on load.  Added a flag ErrorBarsSetTo1 which is by default false.  To access the previous behaviour set this flag to true.

Fixes #13323

### CODE REVIEW

File: Code/Mantid/Framework/DataHandling/src/LoadMcStas.cpp [hunk 1]
```diff
@@ -61,6 +61,8 @@ void LoadMcStas::init() {
   declareProperty(new WorkspaceProperty<Workspace>("OutputWorkspace", "",
                                                    Direction::Output),
                   "An output workspace.");
+  // added to allow control of errorbars
+  declareProperty("ErrorBarsSetTo1",false);
```
Comment (Anders-Markvardsen) [inline Code/Mantid/Framework/DataHandling/src/LoadMcStas.cpp]: Add description for this property, e.g. "When this property set to false errors set equal to data values, and when set to true all errors are set to one. Default to false"
