### PR TITLE
Sanitise Invalid Nexus Log Characters

### LINKED ISSUE #19062: LoadNexusLogs triggers debug assertion on bad log values
### Expected behavior
The loading method within `LoadNexusLogs` should strip and warn on any invalid characters. Whilst the invalid characters shouldn't be there we should handle them better
### Actual behavior
We are passing them on to the c library - this comes with additional risks as correctly detected by MSVC
### Steps to reproduce the behavior
Load `IMAT00003680.nxs` in debug mode on MSVC to see the assertion when loading in the `EPICS_PUTLOG` property
### Platforms affected
All

### PR DESCRIPTION
**Pull request by DavidFair**
Description of work.
This PR fixes an issue where invalid characters were being passed to `iscntrl`. We now check that the character is within a valid range (0 - 255) for the c style locale we use by default then continue to call `iscntrl`.

Additionally I've swapped out the c style library `cctypes` with `locale` and switched to `std::iscntrl`.

**To test:**
- Build on MSVC in debug mode (for the assertion to work):
- Load 
[IMAT00003680](https://github.com/mantidproject/mantid/files/821190/IMAT00003680.zip) on Master, ensure it throws a assertion error (note if you run without debugging Mantid will appear to close gracefully)
- Load the same file on this branch - it should load successfully
- Go to log data. Check the value for `EPICS_PUTLOG` does not contain special characters

Fixes #19062 .

Does not need to be in the release notes. - Assertion is only enabled for debug mode.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/DataHandling/src/LoadNexusLogs.cpp [hunk 1]
```diff
@@ -654,5 +656,33 @@ LoadNexusLogs::createTimeSeries(::NeXus::File &file,
   }
 }
 
+/**
+  * Checks whether the specified character is invalid or a control
+  * character. If it is invalid (i.e. negative) or a control character
+  * the method returns true. If it is valid and not a control character
+  * it returns false. Additionally if the character is invalid is
```
Comment (AnthonyLim23) [inline Framework/DataHandling/src/LoadNexusLogs.cpp]: small thing, but I think there is a typo at the end of the above line

File: Framework/DataHandling/src/LoadNexusLogs.cpp [hunk 2]
```diff
@@ -654,5 +656,33 @@ LoadNexusLogs::createTimeSeries(::NeXus::File &file,
...
+  * @param c :: Character to check
+  * @param propName :: The name of the property currently being checked for
+  *logging
+  * @param log :: Reference to logger to print out to
+  * @return :: True if control character OR invalid. Else False
+  */
+bool LoadNexusLogs::isControlValue(const char &c, const std::string &propName,
+                                   Kernel::Logger &log) {
+  // Have to check it falls within range accepted by c style check
+  if (c <= -1) {
```
Comment (AnthonyLim23) [inline Framework/DataHandling/src/LoadNexusLogs.cpp]: I think it would be safer if we used a static_cast on c. Then we know it is comparing two integers.

Comment (DavidFair) [inline Framework/DataHandling/src/LoadNexusLogs.cpp]: So I double checked this as I was unsure what the compiler would do. According to the C++ standard this is up to the compiler:
http://en.cppreference.com/w/cpp/language/implicit_conversion#Numeric_promotions
So the compiler could compare `char` types or `int` types (using promotion).

Checking the compiler output confirms my suspicions - both the compiler chosen type and static_cast types are treated identically because of this:
https://godbolt.org/g/7lFs4p

For this reason I think a static_cast wouldn't be appropriate here as it implies we can check for a range larger than char (which is untrue) and it may force the compiler to use `int` types when a `char` type is appropriate

File: Framework/DataHandling/src/LoadNexusLogs.cpp (hunk 1 above)
Comment (DavidFair) [inline Framework/DataHandling/src/LoadNexusLogs.cpp]: 👍

File: Framework/DataHandling/src/LoadNexusLogs.cpp (hunk 2 above)
Comment (AnthonyLim23) [inline Framework/DataHandling/src/LoadNexusLogs.cpp]: something about comparing a char and an int makes me uneasy.

Comment (DavidFair) [inline Framework/DataHandling/src/LoadNexusLogs.cpp]: Your right - looking around whilst for `int` and other larger types the default sign is specified in the standard for a `char` it is implementation defined (based on architecture)

In this case if we cast up from an unsigned `char` where that is used on that architecture to a `signed int` we should be able to both hold the value and sign regardless. Additionally if we do this we need to check the value is not greater than 255 as well (if using unsigned types)

Looking again at the compiler output this doesn't add any extra overhead but should ensure we are doing the correct thing : https://godbolt.org/g/Y5ewMz

Comment (AnthonyLim23) [inline Framework/DataHandling/src/LoadNexusLogs.cpp]: sounds good to me

**Comment by AnthonyLim23** [comment]
Behaves as expected. :shipit:

File: Framework/DataHandling/inc/MantidDataHandling/LoadNexusLogs.h [hunk 3]
```diff
@@ -97,6 +97,11 @@ class DLLExport LoadNexusLogs : public API::Algorithm {
   /// Create a time series property
   Kernel::Property *createTimeSeries(::NeXus::File &file,
                                      const std::string &prop_name) const;
+
+  /// Returns true if the character is a control value or invalid
+  static bool isControlValue(const char &c, const std::string &propName,
```
Comment (martyngigg) [inline Framework/DataHandling/inc/MantidDataHandling/LoadNexusLogs.h]: Is there any reason this needs to be a static on the class? Can it just be a simple anonymous function defined only in the `.cpp` file?

Comment (DavidFair) [inline Framework/DataHandling/inc/MantidDataHandling/LoadNexusLogs.h]: Completely forgot about using anonymous namespaces good point.

**Review by martyngigg — APPROVED** [review]
