### PR TITLE
Fix bug with mask boundary for MDEventWorkspaces

### LINKED ISSUE #14962: Bug with boundary of masks for MDEventWorkspaces
Boxes that have a single face on one of the planes which bound a mask are counted as masked. This should not be the case as events within that box must be outside of the intended mask region, in other words the box and masked region do not share any volume. The workspace created with the script below should have one octant masked, instead the masked region appears to be larger.

```python
ws_mdew = CreateMDWorkspace(Dimensions='3', Extents='-2,2,-2,2,-2,2', Names='h,k,l',
                       Units='rlu,rlu,rlu', SplitInto='12')
FakeMDEventData(ws_mdew, UniformParams='1000', RandomizeSignal='1')
ws_mdew = SliceMD(ws_mdew,AlignedDim0='h,-2,2,12',AlignedDim1='k,-2,2,12',AlignedDim2='l,-2,2,12')
ws_masked_mdew = CloneMDWorkspace(ws_mdew)
MaskMD(Workspace=ws_masked_mdew,Dimensions="h,k,l",Extents="-2,0,-2,0,-2,0")
```

It's probably a bug in `MDGridBox::getBoxes`.

### PR DESCRIPTION
**Pull request by matthew-d-jones**
Fixes #14962

**To Test:**

.deb is at `smb://olympic/babylon5/Scratch/Matthew%20Jones/15209`

Use the script below to make a masked and unmasked 3D workspace. The masked workspace should have one octant masked.
View the workspaces in Slice Viewer or VSI, it should be clear that exactly one octant is masked. Previously the masked region appeared too large by one in bin in each dimension.

``` python
ws_mdew = CreateMDWorkspace(Dimensions='3', Extents='-2,2,-2,2,-2,2', Names='h,k,l',
                       Units='rlu,rlu,rlu', SplitInto='12')
FakeMDEventData(ws_mdew, UniformParams='1000', RandomizeSignal='1')
ws_mdew = SliceMD(ws_mdew,AlignedDim0='h,-2,2,12',AlignedDim1='k,-2,2,12',AlignedDim2='l,-2,2,12')
ws_masked_mdew = CloneMDWorkspace(ws_mdew)
MaskMD(Workspace=ws_masked_mdew,Dimensions="h,k,l",Extents="-2,0,-2,0,-2,0")
```

### CODE REVIEW

File: Framework/Geometry/test/MDPlaneTest.h [hunk 1]
```diff
@@ -210,10 +210,38 @@ class MDPlaneTest : public CxxTest::TestSuite {
...
+               p1.isPointInside(point));
+
+    // Point lies on the plane, not inside it
+    point.clear();
+    point.push_back(5.0);
+    point.push_back(-5.0);
+    TSM_ASSERT("Point should not be found to be inside region bounded by "
+               "plane, it lies exactly on the plane",
+               !p1.isPointInside(point));
+  }
```
Comment (picatess) [inline Framework/Geometry/test/MDPlaneTest.h]: is there a test for the array version of the `isPointInside` function?

File: Framework/Geometry/inc/MantidGeometry/MDGeometry/MDPlane.h [hunk 2]
```diff
@@ -125,6 +125,42 @@ class DLLExport MDPlane {
...
+  //----------------------------------------------------------------------------------------------
+  /** Is a point in MDimensions bounded by this hyperplane, that is,
+   * is (a1*x1 + a2*x2 + ... > b)?
+   * False for points that lie on the hyperplane, this is used to detect
+   * when two volumes (for example an MDBox and a mask) touch but do
+   * not share a finite volume
+   *
+   * @param coords :: nd-sized vector of coordinates. No size check is made!
+   * @return true if it is bounded by the plane
+   */
```
Comment (picatess) [inline Framework/Geometry/inc/MantidGeometry/MDGeometry/MDPlane.h]: good comments

File: Framework/Geometry/inc/MantidGeometry/MDGeometry/MDPlane.h [hunk 3]
```diff
@@ -125,6 +125,42 @@ class DLLExport MDPlane {
...
+  inline bool isPointInside(const std::vector<coord_t> &coords) const {
+    coord_t total = 0;
+    for (size_t d = 0; d < m_nd; d++) {
+      total += m_normal[d] * coords[d];
```
Comment (picatess) [inline Framework/Geometry/inc/MantidGeometry/MDGeometry/MDPlane.h]: you can do ++d

**Comment by picatess** [comment]
* Code Review: Code looks fine, some changes were made, good testing
* Functional testing: Works as described above. The masked region is clearly bound at 0. 
Happy to merge.
