### PR TITLE
Correct with sqrt

### LINKED ISSUE #15929: Correccion to error computation in PDFFourierTransform
### Expected behavior
Error values should be smaller than actual values

### Actual behavior
Error values inordinate large

### Steps to reproduce the behavior
Use PDFFourierTransform on any S(Q) data

### Platforms affected
All

### PR DESCRIPTION
**Pull request by jmborr**
Errors have been corrected with sqrt. Furthermore, S(Q) channels are assumed independent from each other (justified according to [Toby et al](http://apps.webofknowledge.com/full_record.do?product=UA&search_mode=GeneralSearch&qid=1&SID=3BEpjrIq7tv2K1M79lI&page=1&doc=1))

**To test:**

Fixes #15929

[Release notes](https://github.com/mantidproject/mantid/blob/15929_PDFFourierTransForm_errors/docs/source/release/v3.7.0/diffraction.rst) have been updated
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [x] Is user-facing documentation written in a user-friendly manner?
- [x] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by jmborr** [comment]
@peterfpeterson Pete, Do you have a G(r)+errors data set computed from S(Q) by other means than PDFFourierTransform?

File: Framework/Algorithms/src/PDFFourierTransform.cpp [hunk 1]
```diff
@@ -216,9 +216,9 @@ void PDFFourierTransform::exec() {
   if (soqType == S_OF_Q_MINUS_ONE) {
     g_log.information() << "Multiplying all values by Q\n";
     // error propagation
-    for (size_t i = 0; i < inputDfOfQ.size(); ++i) {
-      inputDfOfQ[i] = inputQ[i] * inputDfOfQ[i] + inputFOfQ[i] * inputDQ[i];
-    }
+    // for (size_t i = 0; i < inputDfOfQ.size(); ++i) {
```
Comment (peterfpeterson) [inline Framework/Algorithms/src/PDFFourierTransform.cpp]: Delete the code rather than comment it out

**Comment by peterfpeterson** [comment]
The reference should go into the help/rst file similar to [SetSampleMaterial](https://github.com/mantidproject/mantid/blob/master/docs/source/algorithms/SetSampleMaterial-v1.rst). 

Also, this correction belongs in the release notes.

**Comment by peterfpeterson** [comment]
You still need to edit two `rst` files. See comment above.

**Comment by jmborr** [comment]
@peterfpeterson I think everything's all set now.

File: docs/source/algorithms/PDFFourierTransform-v1.rst [hunk 2]
```diff
@@ -17,11 +17,19 @@ spectral density :math:`S(Q)`, :math:`S(Q)-1`, or :math:`Q[S(Q)-1]`
 The input Workspace spectrum should be in the Q-space (\ **MomentumTransfer**\ ) `units <http://www.mantidproject.org/Units>`_ . 
 (d-spacing is not supported any more. Contact development team to fix that and enable **dSpacing** again)
 
+References
+----------
+
+#. B. H. Toby and T. Egami, *Accuracy of Pair Distribution Functions Analysis Appliced to Crystalline and Non-Crystalline Materials*, Acta Cryst. (1992) A**48**, 336-346
+   `doi: 10.1107/S0108767391011327 <http://scripts.iucr.org/cgi-bin/paper?S0108767391011327>`_
```
Comment (peterfpeterson) [inline docs/source/algorithms/PDFFourierTransform-v1.rst]: url should be `http://dx.doi.org/10.1107/S0108767391011327`

File: docs/source/algorithms/PDFFourierTransform-v1.rst [hunk 3]
```diff
@@ -17,11 +17,19 @@ spectral density :math:`S(Q)`, :math:`S(Q)-1`, or :math:`Q[S(Q)-1]`
...
+#. B.H. Toby and S. Billinge, *Determination of Standard uncertainities in fits to pair distribution functions*  Acta Cryst. (2004) A**60**, 315-317]
+   `doi: 10.1107/S0108767304011754 <http://scripts.iucr.org/cgi-bin/paper?S0108767304011754>`_
```
Comment (peterfpeterson) [inline docs/source/algorithms/PDFFourierTransform-v1.rst]: url should be `http://dx.doi.org/10.1107/S0108767304011754`

File: docs/source/release/v3.7.0/diffraction.rst [hunk 4]
```diff
@@ -40,6 +40,11 @@ Graphical user interface:
   is enabled. As well as option to select peak, add peak or save peaks
   from the data plot is now supported.
 
+Powder Diffraction
```
Comment (peterfpeterson) [inline docs/source/release/v3.7.0/diffraction.rst]: There is a merge conflict in this file

File: Framework/Algorithms/src/PDFFourierTransform.cpp [hunk 5]
```diff
@@ -215,10 +215,6 @@ void PDFFourierTransform::exec() {
   }
   if (soqType == S_OF_Q_MINUS_ONE) {
     g_log.information() << "Multiplying all values by Q\n";
-    // error propagation
-    for (size_t i = 0; i < inputDfOfQ.size(); ++i) {
```
Comment (peterfpeterson) [inline Framework/Algorithms/src/PDFFourierTransform.cpp]: This is propagating uncertainty in `S(Q)` and needs to come back

File: Framework/Algorithms/src/PDFFourierTransform.cpp [hunk 6]
```diff
@@ -325,7 +321,7 @@ void PDFFourierTransform::exec() {
 
     // put the information into the output
     outputY[r_index] = fs * 2 / M_PI;
-    outputE[r_index] = error * 2 / M_PI; // TODO: Wrong!
+    outputE[r_index] = sqrt(error) * 2 / M_PI; // TODO: Wrong!
```
Comment (peterfpeterson) [inline Framework/Algorithms/src/PDFFourierTransform.cpp]: Remove the  comment here. It confuses people that dare to read that far.

**Comment by peterfpeterson** [comment]
Comments about current version (being crazy about checking equations): L169-L170 (converting from d-spacing to Q) is missing a factor of pi for the uncertainties. This could be done by `std::transform(..., std::bind1st(std::divides<double>(), PI_2));` or by moving L169-170 to just after L172-173.

Also please address the inline comments on the code.

**Comment by quantumsteve** [comment]
@peterfpeterson [`std::bind1st`](http://www.cplusplus.com/reference/functional/bind1st/) and [`std::bind2nd`](http://www.cplusplus.com/reference/functional/bind2nd/) are both deprecated in C++11. In new code one should use either `std::bind` or a lambda expression.

**Comment by peterfpeterson** [comment]
:shipit:

File: Framework/Algorithms/src/PDFFourierTransform.cpp [hunk 7]
```diff
@@ -166,12 +166,11 @@ void PDFFourierTransform::exec() {
     // nothing to do
   } else if (inputXunit == "dSpacing") {
     // convert the x-units to Q/MomentumTransfer
+    const double PI_2(2. * M_PI);
+    std::for_each(inputQ.begin(), inputQ.end(),
```
Comment (AndreiSavici) [inline Framework/Algorithms/src/PDFFourierTransform.cpp]: you should use range based for loops

**Comment by jmborr** [comment]
@AndreiSavici Can you please give this the final kick?

**Comment by jmborr** [comment]
@AndreiSavici Sorry, I just saw your comment regarding the range-based loop. Why should I use the range-based loop instead of the lambda?
