### PR TITLE
Move the AlgorithmProgress widget to C++

### LINKED ISSUE #23582: Workbench Algorithm Progress bar turns fully green after quick execution of algorithms
Update: Still an issue as of 06/02/2019

------------------------

### Expected behavior
Running many algorithms in a row should not change how the progress bar looks.

### Actual behavior
Running many algorithms in a row changes the background of the progress bar to be green.

### Steps to reproduce the behavior
Run the following code (may need to run it multiple times, it seems to be random) inside the Mantid Interpreter
```python
from __future__ import (absolute_import, division, print_function, unicode_literals)
from mantid.simpleapi import *

b = CreateWorkspace(1,1)

for i in range(10):
    b = AppendSpectra(b,b)
```

> To make a C++ algorithm run slow this line can be added `std::this_thread::sleep_for(std::chrono::seconds(1));` -> 1 second sleep 

### Platforms affected
Windows 10

### LINKED ISSUE #25063: Move AlgorithmProgress from Python to C++
**Original reporter:** 
Jos ISIS

### Expected behavior
Algorithms run as fast as in MantidPlot.

### Actual behavior
Algorithms run ~10x slower due to the progress bar being updated too slowly. The AlgorithmProgress meeting will be moved to C++

### PR DESCRIPTION
**Pull request by dtasev**
**Description of work.**
The algorithm progress widget is now in C++.

**To test:**
- Run a script that runs many small algorithms (thus gets to update what the progress bar is looking after quickly)
- Run that script simultaneously in multiple code editors
- Run a script that is slower and has multiple progress stages
- Open the details window, and repeat the above

The progress bar should also show progress messages sent from the algs when reporting.

Fixes #25063 
Fixes #23582

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by martyngigg — CHANGES_REQUESTED** [review]
Code review looks good. I'm just building a package in release to verify functionality.

Just a couple of things:
 - can we create an issue for unit tests around this?
 - can we add some doxygen to the C++ methods?

File: qt/widgets/common/src/AlgorithmProgress/AlgorithmProgressDialogWidget.cpp [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+namespace MantidQt {
+namespace MantidWidgets {
+
+AlgorithmProgressDialogWidget::AlgorithmProgressDialogWidget(
+    QWidget *parent, AlgorithmProgressModel &model)
+    : QDialog(parent),
+      m_presenter{std::make_unique<AlgorithmProgressDialogPresenter>(
+          parent, this, model)},
+      m_tree{new QTreeWidget(this)} {
+  setAttribute(Qt::WA_DeleteOnClose);
```
[the remark this answers is not in the document]
Comment (DTasev) [reply qt/widgets/common/src/AlgorithmProgress/AlgorithmProgressDialogWidget.cpp]: The issue I had here was that then I have to hook the parent to the widget's close event in order to properly delete it. 

I got around that by adding `setAttribute(Qt::WA_DeleteOnClose)` to the child, and storing the pointer in a [`QPointer`](https://doc.qt.io/qt-5/qpointer.html#details) which guarantees that it will be set to `nullptr` when the child is deleted (which it does itself when closed).

**Comment by DTasev** [comment]
Unit tests issue: https://github.com/mantidproject/mantid/issues/25161

**Comment by martyngigg** [comment]
This also seems to fix #23582 so I've added it to the fixes list.

File: qt/widgets/common/src/AlgorithmProgress/AlgorithmProgressWidget.cpp [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+namespace MantidWidgets {
+
+AlgorithmProgressWidget::AlgorithmProgressWidget(QWidget *parent)
+    : QWidget(parent),
+      m_progressBar{new QProgressBar(this)}, m_layout{new QHBoxLayout(this)},
+      m_detailsButton{new QPushButton("Details")},
+      m_presenter{std::make_unique<AlgorithmProgressPresenter>(parent, this)}
+
+{
+  setAttribute(Qt::WA_DeleteOnClose);
```
Comment (martyngigg) [inline qt/widgets/common/src/AlgorithmProgress/AlgorithmProgressWidget.cpp]: Similar comment to the details one. Should this not be set by the code that creates the widget?

**Review by martyngigg — CHANGES_REQUESTED** [review]
This looks really good. The progress updates now don't hold up the scripts as they did and the speed of scripts is comparable to MantidPlot.

I've one minor code comment but the slightly bigger item is that we are missing the cancel button for each algorithm on the details dialog so we can no longer cancel algorithms :)

File: qt/widgets/common/src/AlgorithmProgress/AlgorithmProgressDialogWidget.cpp [hunk 3]
```diff
@@ -54,16 +53,21 @@ AlgorithmProgressDialogWidget::AlgorithmProgressDialogWidget(
...
+  const auto properties = alg->getProperties();
   const auto item =
       new QTreeWidgetItem(m_tree, QStringList{QString::fromStdString(name)});
 
   m_tree->addTopLevelItem(item);
   auto progressBar = new QProgressBar(m_tree);
   progressBar->setAlignment(Qt::AlignHCenter);
 
+  auto cancelButton = new AlgorithmProgressDialogWidgetCancelButton(
+      alg, QString::fromStdString("Cancel"), m_tree);
```
Comment (DTasev) [inline qt/widgets/common/src/AlgorithmProgress/AlgorithmProgressDialogWidget.cpp]: Would it be better to just hard code "Cancel" in the class? This button isn't used anywhere else. That way the parsing is avoided on every addAlgortihm call.

Comment (Pasarus) [reply qt/widgets/common/src/AlgorithmProgress/AlgorithmProgressDialogWidget.cpp]: Makes sense :+1:

File: qt/widgets/common/src/AlgorithmProgress/AlgorithmProgressWidget.cpp (hunk 2 above)
Comment (Pasarus) [reply qt/widgets/common/src/AlgorithmProgress/AlgorithmProgressWidget.cpp]: I believe that it should stay here as otherwise in Python it would have a very odd position. Specifically in widget.py.

image

Comment (Pasarus) [reply qt/widgets/common/src/AlgorithmProgress/AlgorithmProgressWidget.cpp]: The reason behind it being needed to be done in python is that the widget itself owns the presenter so the presenter would not be making the widget.

**Comment by DTasev** [comment]
I've just added a bunch of doxygen comments, tested the Cancel button locally and it works great 👍 I think it's ready for another review @martyngigg

File: qt/widgets/common/src/AlgorithmProgress/AlgorithmProgressDialogWidget.cpp [hunk 4]
```diff
@@ -0,0 +1,95 @@
...
+}
+
+/// Adds a new widget item for the algorithm.
+/// @param alg The algorithm that should be displayed
+/// @returns The QTreeWidgetItem that was made, as well as the QProgressBar
+/// displaying the progress of the algorithm
+std::pair<QTreeWidgetItem *, QProgressBar *>
+AlgorithmProgressDialogWidget::addAlgorithm(Mantid::API::IAlgorithm_sptr alg) {
+  const auto name = alg->name();
+  const auto properties = alg->getProperties();
```
Comment (martyngigg) [inline qt/widgets/common/src/AlgorithmProgress/AlgorithmProgressDialogWidget.cpp]: Can we use `const auto &` for the `getProperties` call? The copy could be an expensive call for some algorithms.

**Review by martyngigg — CHANGES_REQUESTED** [review]

File: qt/widgets/common/src/AlgorithmProgress/AlgorithmProgressDialogWidget.cpp [hunk 5]
```diff
@@ -0,0 +1,95 @@
...
+  buttonLayout->addStretch();
+  buttonLayout->addWidget(button);
+
+  auto layout = new QVBoxLayout();
+  layout->addWidget(m_tree);
+  layout->addLayout(buttonLayout);
+
+  setLayout(layout);
+  setWindowTitle("Mantid - Algorithm Progress");
+  setWindowIcon(QIcon(":/MantidPlot_Icon_32offset.png"));
```
Comment (martyngigg) [inline qt/widgets/common/src/AlgorithmProgress/AlgorithmProgressDialogWidget.cpp]: Can we use [MantidIcon](`https://github.com/mantidproject/mantid/blob/master/qt/applications/workbench/workbench/app/mainwindow.py#L601`) here so we're not referencing the old icon resource?

File: qt/widgets/common/src/AlgorithmProgress/AlgorithmProgressDialogWidget.cpp (hunk 4 above)
Comment (Pasarus) [reply qt/widgets/common/src/AlgorithmProgress/AlgorithmProgressDialogWidget.cpp]: I added it to the name as well for good measure.

Comment (martyngigg) [reply qt/widgets/common/src/AlgorithmProgress/AlgorithmProgressDialogWidget.cpp]: I think name does not return by reference?

File: qt/widgets/common/src/AlgorithmProgress/AlgorithmProgressDialogWidget.cpp [hunk 6]
```diff
@@ -0,0 +1,95 @@
...
+  resize(500, 300);
+}
+
+/// Adds a new widget item for the algorithm.
+/// @param alg The algorithm that should be displayed
+/// @returns The QTreeWidgetItem that was made, as well as the QProgressBar
+/// displaying the progress of the algorithm
+std::pair<QTreeWidgetItem *, QProgressBar *>
+AlgorithmProgressDialogWidget::addAlgorithm(Mantid::API::IAlgorithm_sptr alg) {
+  const auto &name = alg->name();
```
Comment (martyngigg) [inline qt/widgets/common/src/AlgorithmProgress/AlgorithmProgressDialogWidget.cpp]: [IAlgorithm::name](https://github.com/mantidproject/mantid/blob/master/Framework/API/inc/MantidAPI/IAlgorithm.h#L46) returns by value so the reference qualifier is not valid on that one I think?

**Review by martyngigg — CHANGES_REQUESTED** [review]

File: qt/widgets/common/src/AlgorithmProgress/AlgorithmProgressDialogWidget.cpp (hunk 4 above)
Comment (Pasarus) [reply qt/widgets/common/src/AlgorithmProgress/AlgorithmProgressDialogWidget.cpp]: It does not, my mistake!

**Review by martyngigg — DISMISSED** [review]
This looks good now.

**Review by martyngigg — APPROVED** [review]
I rebased the branch and resolved a trivial merge conflict. Still good to go
