### PR TITLE
Loading data with whitespaces in path

### LINKED ISSUE #33779: Whitespaces in data path
**Describe the bug**
A user has reported that there is an issue in validation when whitespaces are present in the paths or names of the data, which prevents loading of such data. The issue has been observed only when full paths are given to a loader. In such a case, the data does not pass validation and the error message contains information that the file cannot be found, in which all whitespaces are removed, making the path incorrect. This issue does not arise when only file names are given, without full paths.

**To Reproduce**

1. Create a directory or files that have a whitespace, e.g. create a couple of workspaces using `CreateSampleWorkspace` and save them in preferred location.
2. Try to load these files using e.g. `LoadAndMerge` algorithm, observe the validation issue. The path or name mentioned in validation issue is not consistent with actual name of the input to the `Filename` property.

**Expected behavior**

It should be possible to load data even if the path or the filename contains (an unfortunate) white space.

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: observed on Ubuntu 18.04, Windows 10
 - OS Version:
 - Mantid Version 6.3

**Additional context**

### PR DESCRIPTION
**Pull request by darominski**
**Description of work.**
The proposed solution is to leverage already existing mechanism to steer whether whitespaces should be trimmed or not, contained in `m_autoTrim` variable of the `Property` class. So, `setAutoTrim()` and `autoTrim()` functions are exposed to the Python API so they can be now set for `FileProperty` and `MultiFileProperty`. Internally, MultiFileProperty and FileProperty required a modification that the trimming would be performed only when `m_autoTrim` is set to true (true by default), and some patching of information flow between `MultiFileProperty` and `FileProperty`. MultiFileNameParser was trimming whitespaces by default, which is no longer the case: this is now controlled by new variable: `m_trimWhiteSpaces` and related setters and getters were implemented. This modification required also the `parseMultiRunString` to be moved from the global scope to inside Parser class scope.

This PR currently modifies trimming workspaces only for the `LoadAndMerge` algorithm, and does not do the same for the `Load` algorithm. I would like to hear from the reviewer whether it would be safe to do for the `Load` as well.

**To test:**

1. Create a directory or files that have a whitespace, e.g. create a couple of workspaces using `CreateSampleWorkspace` and save them in preferred location.
2. Try to load these files using e.g. `LoadAndMerge` algorithm
3. There should be no validation issues now.
4. All tests should be passing, any possible issues linked to not trimming whitespaces in `LoadAndMerge`?

Testing on other operating system that Linux would  be of great use.

Fixes #33779 . 

Release notes added.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by Harrietbrown — DISMISSED** [review]
No issues loading from directorates with whitespaces. The code look good. Good Job.

File: Framework/API/src/FileProperty.cpp [hunk 1]
```diff
@@ -216,7 +214,10 @@ bool FileProperty::isOptional() const {
  * An empty string indicates success.
  */
 std::string FileProperty::setValue(const std::string &propValue) {
-  std::string strippedValue = Kernel::Strings::strip(propValue);
```
Comment (martyngigg) [inline Framework/API/src/FileProperty.cpp:219]: Could I just double check my understanding. I thought `strip` just called `boost::trim` that only trims leading and trailing whitespaces (an example on compiler explorer: https://gcc.godbolt.org/z/r3TdY8zoj) and not all whitespace?
I am assuming I have slightly misunderstood the input but I wanted to check to answer the question about `Load`.

**Review by martyngigg — COMMENTED** [review]
I just have a question about what I thought the code was doing before but I also wondered if further tests in `FilePropertyTest` could be added?

File: Framework/API/src/FileProperty.cpp (hunk 1 above)
Comment (darominski) [reply Framework/API/src/FileProperty.cpp:219]: I had a look into this and you are correct. The changes proposed in this PR regarding `FileProperty` are actually not necessary for this fix to work, and the only part of the code that needs touching considers the string parser. I propose then to revert changes done to `FileProperty` and connections to it done in MultiFileProperty and leave in only bits that allow control over removing all whitespaces, which is defined in the `MultiFileNameParser`.

**Comment by darominski** [comment]
Following @martyngigg 's comment, I reverted changes done to the `FileProperty` as they are not relevant to this issue.

File: Framework/API/src/FileProperty.cpp (hunk 1 above)
Comment (martyngigg) [reply Framework/API/src/FileProperty.cpp]: Sounds good to me. Thanks for checking and clarifying here.

File: Framework/API/src/FileProperty.cpp [hunk 2]
```diff
@@ -216,7 +216,7 @@ bool FileProperty::isOptional() const {
 std::string FileProperty::setValue(const std::string &propValue) {
   std::string strippedValue = propValue;
   if (autoTrim()) { // strip whitespaces only when requested (default)
-    strippedValue = Kernel::Strings::strip(propValue);
```
Comment (martyngigg) [inline Framework/API/src/FileProperty.cpp]: I think you were actually right to fix this though? The local variable here cannot be used anywhere so the strip never happens?

Comment (darominski) [reply Framework/API/src/FileProperty.cpp]: Apologies for the confusion, but I cannot see this change when looking at the files changed. This must be a part issue of the reverting of some commits not necessarily in the proper order. Now, the `FileProperty` should not have any meaningful changes except of the imports cleanup. Because of the mess with reverting, perhaps it would be best to squash the commits when merging.

Comment (martyngigg) [reply Framework/API/src/FileProperty.cpp]: Yes I think you are right. You fixed the local variable shadowing but then its now been reverted. As it's a bug I was wondering if we should reinstate that?

Comment (darominski) [reply Framework/API/src/FileProperty.cpp]: The shadowing was introduced by the other commit actually, so the fix referred to that rather than an issue in the main branch.

Comment (martyngigg) [reply Framework/API/src/FileProperty.cpp]: Ah I see. Sorry for the confusion. I'm happy with this and I'll merge it now.

**Review by martyngigg — APPROVED** [review]
