### PR TITLE
Fix spinbox crash in IDA GUI

### LINKED ISSUE #29111: Hard crash when entering Lorentzians value in ConvFit, Indirect DA GUI
### Expected behaviour
In the ConvFit tab of the Indirect Data Analysis GUI, for the Lorentzians property you can either increment/decrement using the arrows to the right or type a number in directly. Typing in a number and pressing enter should not cause an error.

### Actual behaviour
Pressing enter after entering a value causes a hard crash that does not launch the error reporter.

### Steps to reproduce the behaviour
1. Open up the Indirect Data Analysis GUI
2. Navigate to the ConvFit tab
3. Not necessary to specify data files, error occurs with or without
4. Click on the Lorentzians property and type in a number, press enter

### Platforms affected
Confirmed on windows, assumed on all platforms

### PR DESCRIPTION
**Pull request by StephenSmith25**
**Description of work.**
This PR fixes a crash in the IDA GUI which occurs when a value is entered into one of the spinbox using the keyboard and `enter` pressed. To circumvent the issue for the time being, this PR implements a SpinBox factory which creates spinboxes with a read only lineedit.  

_**The problem that lead here:**_
This issue came about while fixing another issue with the spinbox, where they could doubly increment while we were holding onto the GUI thread. This caused the spinbox to think the mouse was being held down. To avoid this we offloaded some of the processing onto a separate thread and while that was running we called qApp->processEvents().

**_The issue now:_**
When the spinbox is changed a propertyChanged signal is emitted. This is connected to the intChanged slot in ConvTemplateBrowser.cpp (L391). This calls the presenter to update the model and subsequently the view, using the function setSubType in the ConvTemplatePresenter.cpp (L50). Here, we use a QtConncurrent::run call so we can keep processing the GUI events using qApp->processEvents()).

```
auto future = QtConcurrent::run(fun);
 while (future.isRunning()) 
 qApp->processEvents();
 } 

```
While we are processing these events, QT dispatches a deleteLater event for our spinbox, which means by the time we've returned from the slot our spinbox has been deleted - hence causing a hard crash. The cause of this delete call is as yet unknown. So for now we've implemented a temporary fix.  In the future we should try:

- Updating the PropertyBrowser code, which is available here: https://code.qt.io/cgit/qt/qttools.git/tree/src/shared/qtpropertybrowser?h=5.8
- Try it again on Qt 5.14 as it may be related to this bug https://bugreports.qt.io/browse/QTBUG-40

**To test:**
- Data to test the GUI can be found in #26631.
- Open the IDA GUI
- Go to to the IqtFit tab
- Load data
- Change the exponentials spinbox, it shouldn't crash and should't accept keyboard inputs.
- Do the same for ConvFit (it should behave the same)

Fixes #29111. 

*This does not require release notes* because **as it was introduced this release**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/widgets/common/inc/MantidQtWidgets/Common/QtPropertyBrowser/qteditorfactory.h [hunk 1]
```diff
@@ -104,24 +104,113 @@ class QColor;
...
+  Q_PRIVATE_SLOT(d_func(), void slotSetValue(int))
+  Q_PRIVATE_SLOT(d_func(), void slotEditorDestroyed(QObject *))
+};
+
+class EXPORT_OPT_MANTIDQT_COMMON QtSpinBoxFactory
+    : public QtSpinBoxFactoryBase<QSpinBox> {
+  Q_OBJECT
+public:
+  QtSpinBoxFactory(QObject *parent = nullptr);
+  ~QtSpinBoxFactory() override;
```
Comment (Mantid-Matthew) [inline qt/widgets/common/inc/MantidQtWidgets/Common/QtPropertyBrowser/qteditorfactory.h:211]: Why do we override the destructor here and not in QtSpinBoxFactoryReadOnly?

File: qt/widgets/common/inc/MantidQtWidgets/Common/QtPropertyBrowser/qteditorfactory.h [hunk 2]
```diff
@@ -778,16 +867,98 @@ class QtSliderFactoryPrivate : public EditorFactoryPrivate<QSlider> {
...
 
-class QtSpinBoxFactoryPrivate : public EditorFactoryPrivate<QSpinBox> {
-  QtSpinBoxFactory *q_ptr;
-  Q_DECLARE_PUBLIC(QtSpinBoxFactory)
+template <class SpinBox>
+class QtSpinBoxFactoryPrivateBase : public EditorFactoryPrivate<SpinBox> {
 public:
+  // This q_ptr is public due to the base class QtSpinBoxFactoryBase needing
+  // access to it.
+  QtSpinBoxFactoryBase<SpinBox> *q_ptr;
```
Comment (Mantid-Matthew) [inline qt/widgets/common/inc/MantidQtWidgets/Common/QtPropertyBrowser/qteditorfactory.h:875]: I don't quite understand the comment here. Is this not the base class we are defining here? And if so can this be protected rather than private?

File: qt/widgets/common/inc/MantidQtWidgets/Common/QtPropertyBrowser/qteditorfactory.h [hunk 3]
```diff
@@ -104,24 +104,113 @@ class QColor;
...
 
 protected:
   void connectPropertyManager(QtIntPropertyManager *manager) override;
   QWidget *createEditorForManager(QtIntPropertyManager *manager,
                                   QtProperty *property,
                                   QWidget *parent) override;
   void disconnectPropertyManager(QtIntPropertyManager *manager) override;
+  QtSpinBoxFactoryPrivateBase<SpinBox> *d_ptr;
+  friend class QtSpinBoxFactoryPrivateBase<SpinBox>;
+  void initailiseQPtr() { d_ptr->q_ptr = this; }
```
Comment (Mantid-Matthew) [inline qt/widgets/common/inc/MantidQtWidgets/Common/QtPropertyBrowser/qteditorfactory.h:127]: Minor point but there is a typo in initialise

File: qt/widgets/common/src/QtPropertyBrowser/qteditorfactory.cpp [hunk 4]
```diff
@@ -203,9 +136,9 @@ void QtSpinBoxFactoryPrivate::slotSetValue(int value) {
     Creates a factory with the given \a parent.
 */
 QtSpinBoxFactory::QtSpinBoxFactory(QObject *parent)
-    : QtAbstractEditorFactory<QtIntPropertyManager>(parent) {
+    : QtSpinBoxFactoryBase<QSpinBox>(parent) {
   d_ptr = new QtSpinBoxFactoryPrivate();
```
Comment (Mantid-Matthew) [inline qt/widgets/common/src/QtPropertyBrowser/qteditorfactory.cpp:140]: This may not work within the structure here but would it be possible to have this be a unique pointer rather than a raw pointer which we delete in the destructor?

File: qt/widgets/common/inc/MantidQtWidgets/Common/QtPropertyBrowser/qteditorfactory.h (hunk 2 above)
Comment (Mantid-Matthew) [reply qt/widgets/common/inc/MantidQtWidgets/Common/QtPropertyBrowser/qteditorfactory.h:875]: Actually I have now seen where this needs to be accessed further down. What has changed to mean this needs to be private now though.

**Review by Matthew-Andrew — COMMENTED** [review]
A few minor code comments I did wonder whether there is a nicer way to handle this factory pattern in general but think that is well beyond the scope of this PR.

In functional testing Tom was able to get the interface to reliably crash by quickly clicking up and down on the spin box. I suspect this is the same issue where multiple signals in quick succession from the spin box cause an error. This would then not be resolved by this PR because it only resolves one way of doing so. At this stage it may be worth considering removing the processEvents call and implementing a more correct threading solution instead but this comes down to a matter of priorities. This PR does fix the editing and then pressing enter issue though.

File: qt/widgets/common/inc/MantidQtWidgets/Common/QtPropertyBrowser/qteditorfactory.h (hunk 1 above)
Comment (StephenSmith25) [reply qt/widgets/common/inc/MantidQtWidgets/Common/QtPropertyBrowser/qteditorfactory.h:211]: I've added an override to the QtSpinBoxFactory to be consistent with what was being done before.

File: qt/widgets/common/inc/MantidQtWidgets/Common/QtPropertyBrowser/qteditorfactory.h (hunk 2 above)
Comment (StephenSmith25) [reply qt/widgets/common/inc/MantidQtWidgets/Common/QtPropertyBrowser/qteditorfactory.h:875]: So the Q_DELCARE_PUBLIC / Q_DECLARE_PRIVATE Macros usually handle this but isn't implemented for templated classes. So in order for the constructor of the base class to see this q_ptr we had to make it public... It was all a bit confusing

File: qt/widgets/common/src/QtPropertyBrowser/qteditorfactory.cpp (hunk 4 above)
Comment (StephenSmith25) [reply qt/widgets/common/src/QtPropertyBrowser/qteditorfactory.cpp:140]: So the Qt pointer to implementation pattern uses raw pointers throughout, I don't think it would be trivial (or worthwhile at the moment to change it to smart pointers).

**Comment by StephenSmith25** [comment]
I've pushed a commit which removes the processEvents call and the offloading to a separate thread. These were causing far too many issues at the moment. To get round the previous issue of double incrementing spinboxes I have created a custom spinbox with a custom timer event. Hopefully this will avoid any crashes....

**Review by Matthew-Andrew — APPROVED** [review]
This latest solution works well for me. I cannot get the GUI to crash either by typing in a name and pressing enter or by quickly changing the values in the spin-box. On my machine(with a DEBUG build) the delay on clicking the buttons was only noticeable when I looked hard and didn't impact the workflow.

I think given the various options we have tried and discussed to solve this issue this one gets the closest to resolving all the problems.
