### PR TITLE
Get selected spectrum number not combobox index

### LINKED ISSUE #23225: Parameters not updating in fit browser of Conv Fit after minimisation
**Original reporter:** n/a

### Expected behavior

After fitting has completed the parameters of the function should be updated. The plot preview should also show the new fitted function.

### Actual behavior

The parameters do not update

### Steps to reproduce the behavior

* Go to `Interfaces` > `Indirect` > `Data Analysis`
* Go to the `Conv Fit` tab
* Load the `irs26174_graphite002_red.nxs ` file from the sample data
* Load the resolution file `irs26173_graphite002_res.nxs` from the sample data
* Set `Fit spectra` to String 3
* Set `Fit type` to Two Lorentzians
* Set `Max iterations` to 100
* Expand the function `f0-Loretnzian` - note the parameters
* Click `Run`
* Check the parameters of `f0-Lorentzian` they have not updated
* Set `Fit spectra` to range 3 to 4
* Click `Run`
* The parameters of `f0-Lorentzian` have now updated and the function shows in the preview plot

### Platforms affected

OSX at least

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR fixes an issue where the parameter values are not updated for a selected spectrum when you use the  `Fit String` option in ConvFit.
The problem was that the selected spectrum number was wrong and so an update of the parameter values did not occur. Instead of retrieving the selected spectrum number, the currently selected Combobox index was returned instead.

**To test:**
- Go to Interfaces > Indirect > Data Analysis
- Go to the Conv Fit tab
- Load the reduced and resolution files below
- Set `Fit spectra` to String 3
- Set `Fit type` to Two Lorentzian's
- Set `Max iterations` to 100
- Expand the function f0-Lorentzian - note the parameters
- Click `Run`
- Check the parameters of f0-Lorentzian are updated

- `Run` the fit for other `Fit spectra` Strings, and change between each fitted spectra to ensure that the parameter values are updating

**Test Files**
[irs26173_graphite002_res.zip](https://github.com/mantidproject/mantid/files/2339793/irs26173_graphite002_res.zip)
[irs26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/2339794/irs26176_graphite002_red.zip)

Fixes #23225 

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/scientific_interfaces/Indirect/IndirectFitPlotView.cpp [hunk 1]
```diff
@@ -3,6 +3,7 @@
 #include "MantidQtWidgets/Common/SignalBlocker.h"
 
 #include <boost/numeric/conversion/cast.hpp>
+#include <string>
```
Comment (Pasarus) [inline qt/scientific_interfaces/Indirect/IndirectFitPlotView.cpp]: This include is not necessary

**Review by Pasarus — CHANGES_REQUESTED** [review]
Your tests work as described. Just a change to be made. No need for tests here.

**Review by Pasarus — APPROVED** [review]

**Review by Pasarus — CHANGES_REQUESTED** [review]
Actually you need to make release notes! This is a user facing feature

**Comment by robertapplin** [comment]
This PR doesn't need release notes because no new features have been added, and no improvements have been made - it's just a behind-the-scenes fix that users would expect to have been implemented already. I think that because it's such a small fix (and for the above reason), adding release notes isn't justified.

**Review by Pasarus — APPROVED** [review]
Looking Good!
