### PR TITLE
Fix bug in crystallography convention PredictPeaks

### LINKED ISSUE #18148: PredictPeaks has wrong sign with Crystallography convention

### PR DESCRIPTION
**Pull request by VickieLynch**
Description of work.
Change in hkl sign for Crystallography convention was put in PredictPeaks again and test now checks sign of hkl.
**To test:**

Do this script with and without Crystallography convention to check that sign is changed in hkl:
```python
Load(Filename='TOPAZ_3132_event.nxs', OutputWorkspace='TOPAZ_3132_event')
FilterBadPulses(InputWorkspace='TOPAZ_3132_event', OutputWorkspace='TOPAZ_3132_event', LowerCutoff=25)
ConvertToMD(InputWorkspace='TOPAZ_3132_event', QDimensions='Q3D', dEAnalysisMode='Elastic', Q3DFrames='Q_sample', LorentzCorrection=True, OutputWorkspace='TOPAZ_3132_md', MinValues='-25,-25,-25', MaxValues='25,25,25', SplitInto='2', SplitThreshold=50, MaxRecursionDepth=13, MinRecursionDepth=7)
FindPeaksMD(InputWorkspace='TOPAZ_3132_md', PeakDistanceThreshold=0.37680000000000002, MaxPeaks=50, DensityThresholdFactor=100, OutputWorkspace='TOPAZ_3132_peaks')
FindUBUsingFFT(PeaksWorkspace='TOPAZ_3132_peaks', MinD=3, MaxD=15, Tolerance=0.12)
IndexPeaks(PeaksWorkspace='TOPAZ_3132_peaks', Tolerance=0.12)
PredictPeaks(InputWorkspace='TOPAZ_3132_peaks', WavelengthMin=0.40000000000000002, WavelengthMax=3.5, MinDSpacing=0.40000000000000002, MaxDSpacing=8.5, OutputWorkspace='TOPAZ_3132_peaks')
RenameWorkspace(InputWorkspace='TOPAZ_3132_peaks', OutputWorkspace='TOPAZ_3132_inelasticpeaks')
```
Fixes #18148

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Crystal/src/PredictPeaks.cpp [hunk 1]
```diff
@@ -413,13 +413,14 @@ void PredictPeaks::setStructureFactorCalculatorFromSample(
...
  */
-void PredictPeaks::calculateQAndAddToOutput(const V3D &hkl,
+void PredictPeaks::calculateQAndAddToOutput(V3D &hkl,
                                             const DblMatrix &orientedUB,
                                             const DblMatrix &goniometerMatrix) {
   // The q-vector direction of the peak is = goniometer * ub * hkl_vector
   // This is in inelastic convention: momentum transfer of the LATTICE!
   // Also, q does have a 2pi factor = it is equal to 2pi/wavelength.
-  V3D q = orientedUB * hkl * (2.0 * M_PI * m_qConventionFactor);
+  hkl *= m_qConventionFactor;
```
Comment (MichaelWedel) [inline Framework/Crystal/src/PredictPeaks.cpp]: Could this also be done in line 435 (`p.setHKL(hkl * m_qConventionFactor);`)? Then `hkl` could still be `const`. But the factor would have to be left in the calculation of `q`.

**Comment by AndreiSavici** [comment]
Looks good. :shipit:
