### PR TITLE
Fix typo in IndirectResolution documentation

### LINKED ISSUE #37771: Iqt Enforce Normalisation unusual result for ISIS data
**Description**
When the `Enforce Normalisation` option is unticked in the Iqt tab of the Inelastic Data Processor interfaces, we get an unexpected result when using data from ISIS. It gives the following plot:

Image

But we would expect something more similar to this:

Image

When working on this, we **must** get feedback from ORNL to ensure we do not break anything on their side.

**To Replicate**
1. Open Inelastic->Data Processor interface
2. Go to the Iqt tab
3. Load the usual 26176 _red file as sample
4. Load the usual 26173 _res file as resolution
5. Untick `Enforce Normalisation`
6. Click `Run`
7. Plot the first spectrum. Many of the initial values are zeros.

### PR DESCRIPTION
**Pull request by robertapplin**
### Description of work
This PR does two things:
- It fixes a typo in the IndirectResolution documentation
- It removes setting the OutputWorkspace property in the child algorithm calls in CalculateIqt (for cleaner code).

Fixes #37771

### To test:
1. Open Inelastic->Data Processor interface
2. Go to the Iqt tab
3. Load the usual 26176 _red file as sample
4. Load the usual 26173 _res file as resolution
5. Untick `Enforce Normalisation`
6. Click `Run`
7. Plot the first spectrum. It should look something like this
image

9. Tick `Enforce Normalisation`
10. Click `Run`
11. The first point in the plot should start at 1, and then exponentially decrease 

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

File: Framework/Algorithms/src/CalculateIqt.cpp [hunk 1]
```diff
@@ -143,9 +143,8 @@ void CalculateIqt::exec() {
   m_resolutionIntegral = integration(rebin(resolution, rebinParams));
 
   resolution = fourierTransform(resolution, rebinParams);
-  if (enforceNormalization) {
-    resolution = divide(resolution, m_resolutionIntegral);
-  }
+  // Always normalise the resolution to unity
+  resolution = divide(resolution, m_resolutionIntegral);
```
Comment (mpatrou) [inline Framework/Algorithms/src/CalculateIqt.cpp:147]: The enforceNormalization flag can determine when normalization occurs, instead of enabling it every time to avoid altering the results of the data when using the algorithm.

**Review by mpatrou — APPROVED** [review]
it looks good!
