### PR TITLE
Prevent show full function resetting fit in indirect data analysis

### LINKED ISSUE #29888: Indirect data analysis: Full function view removes fit curves
### Expected behavior
You should be able to view the full function without removing the fit data from the plot
### Actual behavior
The fit is removed when the tickbox is checked.
### Steps to reproduce the behavior
- Open the indirect GUI
- Go to ConvFit - load sample and resolution
- Add a Lorentizan
- Do a fit 
- View the full function and the fit will be cleared from the plot

### PR DESCRIPTION
**Pull request by Harrietbrown**
This PR fixes a bug fixes a bug that caused previous fits to be erased when showing the full fit function in indirect data analysis.

**Report to:** @SpencerHowells

**To test:**

1. open indirect data analysis.
2. in each of the fit tabs:
3. load data
4. run a fit.
5. see full function, check that the plotted fit is not erased.

Fixes #29888

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/scientific_interfaces/Indirect/IndirectFitPropertyBrowser.cpp [hunk 1]
```diff
@@ -117,20 +117,24 @@ QStringList IndirectFitPropertyBrowser::getLocalParameters() const {
 void IndirectFitPropertyBrowser::syncFullBrowserWithTemplate() {
   auto const fun = m_templateBrowser->getFunction();
   if (fun) {
+    m_functionBrowser->blockSignals(true);
```
Comment (StephenSmith25) [inline qt/scientific_interfaces/Indirect/IndirectFitPropertyBrowser.cpp:120]: If any of `setFunction`, `updateMultiDataSetParamters`, `setGlobalParameters` or `setCurrentDataSe` throw our `functionBrowser` will be left with blocked signals.

**Review by StephenSmith25 — CHANGES_REQUESTED** [review]
This works, but I feel it may be safer to do toggles like this using RAII. From what I remember, we catch a lot of exceptions in the indirect code base, which means we may get in a strange state if the function browser signals aren't restored to their default setting. If we use a structure, which blocks the signal on construction and re-enables it on destruction we should always return to the "normal" state even if one of the methods we call throws. 

Something like the following would work
```
struct ScopedSignalBlocker
{
    // block signals on construction
    ScopedSignalBlocker(FunctionBrowser& myObject) : m_object(myObject)
    {
        m_object.blockSignals(true);
    }
    // enable signals on destruction
    ~ScopedSignalBlocker()
    {
        m_object.blockSignals(false);
    }
    FunctionBrowser& m_object;
};

void syncFullBrowserWithTemplate()
{
    ScopedSignalBlocker blocker(*m_functionBrowser);
    // Signal is now blocked
    // Do stuff
} // signal is now re-enabled when we leave the function scope
```
Missing some of the details, but hopefully still expresses the idea. This can wait if you'd prefer to stick with the current solution as from what I recall you're currently refactoring all this code anyway.

File: qt/scientific_interfaces/Indirect/IndirectFitPropertyBrowser.cpp (hunk 1 above)
Comment (Harrietbrown) [reply qt/scientific_interfaces/Indirect/IndirectFitPropertyBrowser.cpp:120]: Good thinking. and a good solution too. I'll sort that

**Review by StephenSmith25 — APPROVED** [review]
Looks good 👍
