### PR TITLE
Sample Transmission Calculator no longer accepts negative wavelength values

### LINKED ISSUE #24224: Sample Transmission Calculator - Wavelengths can be negative in multiple input mode
**Original reporter:** [aybamidele ISIS/STFC/RAL]

### Expected behaviour
When a wavelength range is entered, there should be validation to prevent negative values from being entered when in multiple input mode.

### Actual behaviour
There is only validation to prevent negative values on the width parameter, not the low and high parameters.

### Steps to reproduce the behaviour
-Open Sample Transmission Calculator (interfaces -> general)
-Enter valid chemical formula (e.g. H2-O) and bin width
-Select multiple type in the dropdown menu and use '-50, 0.1, -1.0' as the wavelength range
-Set both Low and High values for the wavelength range as negatives
-Observe lack of errors

### Platforms affected
Seen on Windows 10

### PR DESCRIPTION
**Pull request by PhilColebrooke**
**Description of work.**
When the input type is set to Multiple, the interface no longer executes if negative wavelengths have been inputted.

**To test:**
1. Interfaces -> General -> Sample Transmission Calculator
2. Under Input Wavelength Range, set Type to Multiple.
3. Enter a comma-separated list of three values (min wavelength, width, max wavelength), making either or both wavelengths negative. E.g. -10,0.1,-5.
4. Enter H for Chemical Formula and click Calculate.
5. Check an error is thrown, and check that the interface works correctly when negative wavelengths aren't used.

Fixes #24224 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/scientific_interfaces/General/SampleTransmission.cpp [hunk 1]
```diff
@@ -82,6 +82,20 @@ bool SampleTransmission::validate(bool silent) {
...
     uiv.checkFieldIsNotEmpty("Multiple binning", m_uiForm.leMultiple,
                              m_uiForm.valMultiple);
+
+    int firstChararacterAfterWhitespaceIndex{static_cast<int>(
+        m_uiForm.leMultiple->text().toStdString().find_first_not_of(' '))};
+
+    // checks that the first number in the list is not negative
+    // only need to check the first number because if it isn't negative then the
+    // rest can't be
+    // the Rebin algorithm takes care of the rest of the checks
```
Comment (hsautessella) [inline qt/scientific_interfaces/General/SampleTransmission.cpp]: A bit picky, but could we clean up this comment with capital letters and punctuation?

**Review by ghost — CHANGES_REQUESTED** [review]
Looks good and functions well 👍. One comment below

File: qt/scientific_interfaces/General/SampleTransmission.cpp (hunk 1 above)
Comment (PhilColebrooke) [reply qt/scientific_interfaces/General/SampleTransmission.cpp]: Fixed the comment and also removed the cast because I realised it isn't needed

Comment (PhilColebrooke) [reply qt/scientific_interfaces/General/SampleTransmission.cpp]: Martyn told me that it's best to avoid using toStdString() so I've now taken a different approach

**Review by ghost — APPROVED** [review]
