### PR TITLE
ALC No Longer Empty's Interface On New Runs

### LINKED ISSUE #30067: Muon ALC Prevent Calculation Settings Resetting On New Runs If Available
**Original reporter:** Stephen Cottrell / ISIS

The ALC interface currently populates calculation parameters from the first run that is entered into the interface. Once the run numbers are changed, these parameters are reset to defaults/empty boxes. There is an exception when the first run number has not changed the interface does not reset. 

Instead of resetting all the time with the one exception, we want to instead check if we can re-use the same parameters/settings for a new set of runs. It was suggested that once a user has clicked load that the parameters all be saved. And then when a new set of runs is entered to check if the new runs have the same available parameters (log value, periods etc.), and if it does to use the previous values. This would effectively just mean leaving the interface as it is. If the same parameters are not available (for example loading multi period data and then loading single period), the interface should just default in those cases.

### PR DESCRIPTION
**Pull request by Matt-Cumber**
**Ready**

~~**Merge #30628 first**~~ **Merged**

**Description of work.**
Updated sorting of logs to fix bug. 
Stopped setting interface to empty unless parameters can't be reused.
Defaulted to 1 minus 2 if only 2 periods

**To test:**
Open ALC
First Load 2 period Data (EMU74470)
Notice it now the interface has 1 subtract 2 for periods
Check logs are now alphabetically sorted (ignoring problems with underscores)(before some logs were in the wrong place if they started with the same letter)
Change all the settings in the interface
Change periods to 2 subtract 1
Now Load EMU74471 (also 2 period)
All settings should remain the same including the periods
Load single period data EMU20883
periods should have changed

Fixes #30067 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by tolu28-coder — DISMISSED** [review]
Everything works as expected

File: qt/scientific_interfaces/Muon/ALCDataLoadingPresenter.cpp [hunk 1]
```diff
@@ -326,7 +323,18 @@ void ALCDataLoadingPresenter::updateAvailableInfo() {
 
   // sort alphabetically
   std::sort(logs.begin(), logs.end(), [](std::string &logA, std::string &logB) {
-    return std::tolower(logA[0]) < std::tolower(logB[0]);
```
Comment (martyngigg) [inline qt/scientific_interfaces/Muon/ALCDataLoadingPresenter.cpp:329]: Could I ask why  simply `std::sort(logs.begin() logs.end())` isn't sufficient?

`operator<` is defined for [std::string](https://en.cppreference.com/w/cpp/string/basic_string/operator_cmp) so by default `sort` should use that.

**Review by martyngigg — CHANGES_REQUESTED** [review]

File: qt/scientific_interfaces/Muon/ALCDataLoadingPresenter.cpp (hunk 1 above)
Comment (Matt-Cumber) [reply qt/scientific_interfaces/Muon/ALCDataLoadingPresenter.cpp:329]: Because some of the logs are all capitalised and some are not, which means the end result is not fully alphabetised using the standard sort

Comment (martyngigg) [reply qt/scientific_interfaces/Muon/ALCDataLoadingPresenter.cpp:329]: Yes I see, I somehow didn't see the `tolower`. Could we add a comment about that?

There is a nice example of this on [stackoverflow](https://stackoverflow.com/a/33380725) using just STL algorithms without the need for our own `for` loop. They show an example in an [`online IDE`](http://ideone.com/BVgyD2).

**Review by martyngigg — APPROVED** [review]

**Comment by Matt-Cumber** [comment]
Please could you not merge this yet

**Review by martyngigg — CHANGES_REQUESTED** [review]
Marking as requests changes so it doesn't get merged.

**Comment by Matt-Cumber** [comment]
I have updated the code a little so it should be tested again. Would be great if you could give it a quick test @tolu28-coder since the sorting has been unchanged

**Review by tolu28-coder — APPROVED** [review]
Everything looks good and works as expected

**Review by martyngigg — APPROVED** [review]
