### PR TITLE
Checkbox for setting global peak type in fit browser

### LINKED ISSUE #31930: Default peak type behaves as current peak type
### Expected behavior
Default peak function in settings would be the peak function set on opening any new fitbrowser.

### Actual behavior
Changing the peak function in the interactive tool of a fitbrowser changes the default peak type - i.e. it behaves as a current peak function.

This occurs because when the peak function is changed in the interactive tool it emits a signal
https://github.com/mantidproject/mantid/blob/465ed823cb07a8aa3cad4520a37c80a1ee25649e/qt/python/mantidqt/widgets/fitpropertybrowser/interactive_tool.py#L211
which ends up changing the global setting
https://github.com/mantidproject/mantid/blob/68807241aa3f38cb10850c8cf7262977238b0ec2/qt/widgets/common/src/FitPropertyBrowser.cpp#L1045
If the above line is commented out you can change the default peak in the interactive tool without affecting the global settings - but the function changing in the fitbrowser works (i.e. the peak you add will be of the type yuo select). See discussion on PR#31748 for more details.

### Steps to reproduce the behavior
(1) Create a workspace
```
ws = CreateSampleWorkspace(Function="User Defined",   UserDefinedFunction="name=LinearBackground, 
    A0=0.3;name=Gaussian, PeakCentre=5, Height=10, Sigma=0.7",  NumBanks=1, BankPixelWidth=1, XMin=0, XMax=10, 
    BinWidth=0.1, WorkspaceType="Event")
```
(2) Plot a spectrum, open the fit browser and add a peak - note the function (e.g. Gaussian)
(3) Change the peak type in the interactive tool (Right-click on plot > Select Peak Type > Lorentzian)
(4) Check in the workbench settings (File>Settings>Fitting>Default Peak Shape) -  the peak function will have been overwritten with the one selected e.g. Lorentizan

### PR DESCRIPTION
**Pull request by thomashampson**
**Description of work.**

When selecting a peak type in the fit browser, the dialog now has a checkbox for setting the application's default peak type. This allows you to change the peak type without altering the default setting. Previously it would update the setting whenever the peak type was changed.
image

**To test:**

0. Make a note of the default peak type in `File->Settings->Fitting->Default peak shape`
1. Open a plot and open the fit browser.
2. Right click the plot and click "Select peak type".
3. Choose a peak type different to the default setting. Leave the checkbox **unticked**.
4. Press OK (optionally click the plot to place the peak).
5. Check that `File->Settings->Fitting->Default peak shape` has not changed.
6. Repeat steps 2-5 but this time **tick the checkbox**. Confirm that the default peak type in `File->Settings->Fitting->Default peak shape` has changed appropriately.
7. Make sure the checkbox isn't present in the other related dialogs ("Add background" and "Add other function") accessed via the same context menu.

Fixes #31930 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/widgets/common/src/FitPropertyBrowser.cpp [hunk 1]
```diff
@@ -1042,7 +1042,6 @@ std::string FitPropertyBrowser::defaultPeakType() {
 void FitPropertyBrowser::setDefaultPeakType(const std::string &fnType) {
```
Comment (RichardWaiteSTFC) [inline qt/widgets/common/src/FitPropertyBrowser.cpp:1042]: Should we still refer to this a the default peak type or current peak type here?

**Review by RichardWaiteSTFC — DISMISSED** [review]
Works really well and now the default peak function behaves like a default as opposed to a current peak function. 
When two plots are open, selecting a peak function in one and setting as global does not effect the peak function chosen in the other, which I think is the expected/intuitive behaviour.
I have also checked this doesn't effect the functionality in the EngDiff UI introduced in #31748. 
I have one comment about renaming default peak type to current in the `FitPropertyBrowser.cpp` - but I'm happy to approve as is.

File: qt/widgets/common/src/FitPropertyBrowser.cpp (hunk 1 above)
Comment (thomashampson) [reply qt/widgets/common/src/FitPropertyBrowser.cpp:1042]: Yes, that would be useful.

Comment (thomashampson) [reply qt/widgets/common/src/FitPropertyBrowser.cpp:1042]: I'll leave the name for now because there are a few other "default" variables in the base class, e.g. the background type. And it is at least a default in the context of the fit browser itself.

**Review by RichardWaiteSTFC — APPROVED** [review]
Looks good -thanks for removing the redundant code form EngDiff UI. 
Just done some more testing and found that if you have two plots open, open the fitbrowser in one and change the global peak function then open the fitbrowser in the other plot and add a peak it hasn't updated the global peak function. I.e. the current peak function is the global function at the time the figure is created not when the fitbrowser is opened (because the fitbrowser is initialised at the creation of the figure I believe). This behaviour was known from PR #31748. I don't think it's an issue so approving.
