### PR TITLE
Indirect Data Analysis - Error bars for results

### LINKED ISSUE #24421: Indirect Data Analysis - Error bars on data from Plot Result and Plot Current Preview
**Original reporter:** Spencer

### Expected behavior
When you click `Plot Result`, errors should be shown on the Data. Plot Current preview should also show Error bars but on the data only.

### Actual behavior
No error bars currently.

### Steps to reproduce the behavior
1.`Interfaces`->`Indirect`->`Data Analysis`

### Platforms affected
All

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR ensures error bars are plotted for the graphs plotted when you Plot the data in the Result workspaces in Indirect Data Analysis.

**To test:**
1.`Interfaces`->`Indirect`->`Data Analysis`->`MSDFit` tab
2. Load the data below
3. Select Gaussian as FitType
4. Click Run and wait
5. Select a parameter in the output options combo box, and click `Plot`.
6. The graph plotted should have error bars

**Data Files**
[osi104367-104371_graphite002_red_elwin_eq.zip](https://github.com/mantidproject/mantid/files/2733355/osi104367-104371_graphite002_red_elwin_eq.zip)

Fixes #24421 

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/scientific_interfaces/Indirect/IndirectTab.cpp [hunk 1]
```diff
@@ -285,14 +285,15 @@ void IndirectTab::plotSpectrum(const QStringList &workspaceNames,
...
  */
-void IndirectTab::plotSpectrum(const QString &workspaceName, int spectraIndex) {
-  if (workspaceName.isEmpty())
-    return;
-
-  QStringList workspaceNames;
-  workspaceNames << workspaceName;
-  plotSpectrum(workspaceNames, spectraIndex);
+void IndirectTab::plotSpectrum(const QString &workspaceName, int spectraIndex,
+                               bool errorBars) {
```
Comment (TTitcombe) [inline qt/scientific_interfaces/Indirect/IndirectTab.cpp]: Const int, const bool?

**Review by TTitcombe — DISMISSED** [review]

**Comment by TTitcombe** [comment]
Code changes are good.
Docs contain clear updates.
Works as intended in testing.

**Review by TTitcombe — APPROVED** [review]
Changes good.
Works as intended during testing
