### PR TITLE
ISIS Reflectometry GUI: Fixed bug where unexpected error was thrown when processing with output notebook option

### LINKED ISSUE #19245: ISIS Reflectometry GUI: Unexpected error thrown when attempting to process with IPython Notebook
### Expected behavior

When attempting to process any data in the table with the `Output Notebook` option selected at the bottom, an IPython notebook should be generated without error.

### Actual behaviour

The following unexpected exception is thrown - `invalid map<K, T> key`

### Steps to reproduce the behavior

- Access the interface from Interfaces->Reflectometry->ISIS Reflectometry
- Obtain some sample data (e.g. import `INTER_NR_test2.tbl` from ISIS sample datasets).
- Check the `Output Notebook` option at the bottom of the `Runs` tab.
- Process some data - a window for saving the notebook should appear.
- The error should appear when attempting to save.

### Platforms affected

Windows, likely others.

### PR DESCRIPTION
**Pull request by PranavBahuguna**
As described in the related issue, attempting to process runs with the `Output Notebook` option selected will throw an unexpected error. This PR fixes this problem so an IPython notebook is generated normally without error.

**To test:**
- Access the interface from Interfaces->Reflectometry->ISIS Reflectometry
- Obtain some sample data (e.g. import INTER_NR_test2.tbl from ISIS sample datasets).
- Check the Output Notebook option at the bottom of the Runs tab.
- Process some data - a window for saving the notebook should appear. Enter some name for the file.
- It should save the notebook normally without throwing an error.

Fixes #19245.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: MantidQt/MantidWidgets/src/DataProcessorUI/GenericDataProcessorPresenter.cpp [hunk 1]
```diff
@@ -600,25 +600,26 @@ GenericDataProcessorPresenter::reduceRow(const std::vector<std::string> &data) {
...
 
         auto optionsMap = parseKeyValueString(options);
         auto runWS = prepareRunWorkspace(runStr, preprocessor, optionsMap);
+
         alg->setProperty(propertyName, runWS->getName());
       }
     } else {
       // No pre-processing needed
-      auto propertyValue = data.at(i);
+      const std::string propertyValue = data.at(i);
```
Comment (raquelalvarezbanos) [inline MantidQt/MantidWidgets/src/DataProcessorUI/GenericDataProcessorPresenter.cpp]: I don't understand why we needed to change `ReflRunsTabPresenter` and `GenericDataProcessorPresenter` to make the notebook work? As far as I can see (correct me if I am wrong), the issue was in [this](https://github.com/mantidproject/mantid/blob/master/MantidQt/MantidWidgets/src/DataProcessorUI/DataProcessorGenerateNotebook.cpp#L466) line, so I think something like:

```
const std::string options = preprocessingOptionsMap.count(colName) > 0
                                        ? preprocessingOptionsMap.at(colName)
                                        : "";
```

should work.

Comment (PranavBahuguna) [inline MantidQt/MantidWidgets/src/DataProcessorUI/GenericDataProcessorPresenter.cpp]: I think I was trying to do what you have done (pass an empty string as option). I believe your solution works better as it does not involve having to potentially change any tests though, so I will try to implement that.

**Comment by gemmaguest** [comment]
The changes look good and behave as described. Please :shipit:
