### PR TITLE
SumSpectra: Fixed one-off errors & input validation

### LINKED ISSUE #15414: Wrong fallback max index in SumSpectra
`SumSpectra.cpp` line 101:

``` cpp
  // Something for m_maxSpec was given but it is out of range?
  if (!isEmpty(m_maxSpec) &&
      (m_maxSpec > m_numberOfSpectra - 1 || m_maxSpec < m_minSpec)) {
    g_log.warning("EndWorkspaceIndex out of range! Set to max Workspace Index");
    m_maxSpec = m_numberOfSpectra;
  }
```

Shouldn't the last lin read `m_maxSpec = m_numberOfSpectra - 1;`?

### PR DESCRIPTION
**Pull request by ThomasLohnert**
Fixes #15414.

Fixed the one-off errors in SumSpectra's min/max fallback indices as described in the ticket. Also added input validation for the max index and index list properties which should prevent the fallback values from being needed in the first place.

**To test:**
1. Create sample workspace
1. Run SumSpectra on it 
1. Try entering invalid values (i.e. negative, or greater than maximum spectrum index) for StartWorkspaceIndex, EndWorkspaceIndex or ListOfWorkspaceIndices properties
1. Confirm an error appears when trying to run the algorithm, and the tooltip for the invalid input is understandable
1. Confirm functionality of the algorithm is unchanged for valid inputs

[Release Notes](https://github.com/mantidproject/mantid/pull/19830/commits/ad572aa8b8b353f19fcdead786f8fe763f69b468)

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Algorithms/src/SumSpectra.cpp [hunk 1]
```diff
@@ -76,6 +76,40 @@ void SumSpectra::init() {
...
+  if (maxIndex != EMPTY_INT() && maxIndex > m_numberOfSpectra) {
+    validationOutput["EndWorkspaceIndex"] =
+        "Selected maximum workspace index is greater than available spectra.";
+  }
+
+  // check ListOfWorkspaceIndices in range
+  const std::vector<int> indices_list = getProperty("ListOfWorkspaceIndices");
+  this->m_indices.clear();
+  // only if specified
+  if (indices_list.size() > 0) {
```
Comment (soininen) [inline Framework/Algorithms/src/SumSpectra.cpp]: Please check `!indices_list.emtpy()` instead of comparison to `0`. It conveys the intention better.

File: Framework/Algorithms/src/SumSpectra.cpp [hunk 2]
```diff
@@ -76,6 +76,40 @@ void SumSpectra::init() {
...
+    this->m_indices.insert(indices_list.begin(), indices_list.end());
+    auto listMaxIndex = std::prev(this->m_indices.end());
+    auto listMinIndex = this->m_indices.begin();
```
Comment (soininen) [inline Framework/Algorithms/src/SumSpectra.cpp]: How about `m_indices->front()` and `m_indices->back()`? No need for the iterator stuff here. Also, please use `const auto`.

File: Framework/Algorithms/src/SumSpectra.cpp [hunk 3]
```diff
@@ -76,6 +76,40 @@ void SumSpectra::init() {
...
+* containing the error messages.
+*/
+std::map<std::string, std::string> SumSpectra::validateInputs() {
+  // create the map
+  std::map<std::string, std::string> validationOutput;
+
+  // check StartWorkspaceIndex in range
+  MatrixWorkspace_const_sptr localworkspace = getProperty("InputWorkspace");
+  m_numberOfSpectra = static_cast<int>(localworkspace->getNumberHistograms());
+  int maxIndex = getProperty("EndWorkspaceIndex");
```
Comment (soininen) [inline Framework/Algorithms/src/SumSpectra.cpp]: Can't this variable be declared `const`?

File: Framework/Algorithms/src/SumSpectra.cpp [hunk 4]
```diff
@@ -76,6 +76,40 @@ void SumSpectra::init() {
...
+  if (maxIndex != EMPTY_INT() && maxIndex > m_numberOfSpectra) {
```
Comment (soininen) [inline Framework/Algorithms/src/SumSpectra.cpp]: I believe you need to test here for `maxIndex >= m_numberOfSpectra`.

File: Framework/Algorithms/src/SumSpectra.cpp [hunk 5]
```diff
@@ -95,7 +129,7 @@ void SumSpectra::exec() {
   this->m_yLength = static_cast<int>(localworkspace->blocksize());
 
   // Check 'StartSpectrum' is in range 0-m_numberOfSpectra
-  if (m_minWsInd > m_numberOfSpectra) {
+  if (m_minWsInd >= m_numberOfSpectra) {
```
Comment (soininen) [inline Framework/Algorithms/src/SumSpectra.cpp]: How about testing *StartWorkspaceIndex* in `validateInputs` as well? You would need to ensure that `m_minWsInd < m_maxWsInd` and `m_minWsInd < m_numberOfSpectra`.

File: Framework/Algorithms/src/SumSpectra.cpp [hunk 6]
```diff
@@ -379,7 +413,7 @@ void SumSpectra::doRebinnedOutput(MatrixWorkspace_sptr outputWorkspace,
   // Loop over spectra
   for (const auto i : m_indices) {
     // Don't go outside the range.
-    if ((i >= m_numberOfSpectra) || (i < 0)) {
+    if ((i >= this->m_numberOfSpectra) || (i < 0)) {
```
Comment (soininen) [inline Framework/Algorithms/src/SumSpectra.cpp]: The `this->` thing is used inconsistently throughout this file anyhow. Personally, I'd remove them as my IDE color-codes member variables automatically but your mileage my vary...

**Review by soininen — CHANGES_REQUESTED** [review]
Tested this as instructed. There are few issues with the code but overall these are nice improvements. This PR does fix an actual bug, so why not add a line to the release notes?

File: Framework/Algorithms/src/SumSpectra.cpp (hunk 6 above)
Comment (ThomasLohnert) [inline Framework/Algorithms/src/SumSpectra.cpp]: You're right, there really is not much point to using `this->` - while my IDE does not highlight it, the `m_` naming convention for member variables implies the same anyway. I have removed it throughout the file in the interest of consistency

**Review by soininen — APPROVED** [review]
