### PR TITLE
Prevent segmentation fault when running CrystalFieldFit with multiple sites and resolution models

### LINKED ISSUE #35839: Segmentation fault when running CrystalFieldFit with multiple sites
A segmentation fault occurs when running a CrystalFieldFit for multiple sites that use the resolution model.

**Original reporter:** Duc Le at ISIS

**To Reproduce**
Run the following script: https://gist.github.com/mducle/7d4480ce9f5926de4b2e44c42caaa868

**Expected behavior**
The script should run without causing a segmentation fault.

**Platform/Version (please complete the following information):**
 - CentOS Linux 7 
 - Mantid Version 6.7

**Additional context**
The same script runs without problems when the resolution model is not used.

### PR DESCRIPTION
**Pull request by SilkeSchomann**
**Description of work**
When CrystalField objects use the resolution model FWHM values are unset as they would otherwise override the resolution model. As a consequence, the FWHMs of a CrystalField object for multiple sites can be empty. This can cause a segmentation fault in the setAttribute function as it tries to access the first FWHM value even when there are no FWHMs.

**Purpose of work**
Prevent a segmentation fault.

**Report to:** Duc Le

**To test:**

Run the script from the original issue https://github.com/mantidproject/mantid/issues/35839 and check whether there is a segmentation fault occurring.

Fixes #35839

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by robertapplin — CHANGES_REQUESTED** [review]
There is no longer a segmentation fault when running the provided crystal field script. Would it be possible to add a test for this?

**Comment by SilkeSchomann** [comment]
> There is no longer a segmentation fault when running the provided crystal field script. Would it be possible to add a test for this?

Good idea. I've added a test for this.

**Review by robertapplin — DISMISSED** [review]
Thanks for adding the test, looks good 👍

File: Framework/CurveFitting/test/Functions/CrystalFieldControlTest.h [hunk 1]
```diff
@@ -347,4 +347,30 @@ class CrystalFieldControlTest : public CxxTest::TestSuite {
     TS_ASSERT_EQUALS(isMultiSpectrum, true);
     TS_ASSERT_EQUALS(nControls, 2);
   }
+
+  void test_build_17() {
```
Comment (thomashampson) [inline Framework/CurveFitting/test/Functions/CrystalFieldControlTest.h:351]: Could you name your test more descriptively?

**Review by thomashampson — CHANGES_REQUESTED** [review]

File: Framework/CurveFitting/test/Functions/CrystalFieldControlTest.h (hunk 1 above)
Comment (SilkeSchomann) [reply Framework/CurveFitting/test/Functions/CrystalFieldControlTest.h:351]: Yes, I could. Probably makes sense to rename the other 16 tests as well...

Comment (thomashampson) [reply Framework/CurveFitting/test/Functions/CrystalFieldControlTest.h:351]: Only if you understand what they're testing 😄

Comment (SilkeSchomann) [reply Framework/CurveFitting/test/Functions/CrystalFieldControlTest.h]: The renaming is quite straightforward. Unfortunately void `xtest_build_7()` started to fall over after just renaming. It is not a surprise as there was one unnecessary line in the test code so easy to fix. It just makes me wonder how this test was not failing before as it should have failed.

Comment (robertapplin) [reply Framework/CurveFitting/test/Functions/CrystalFieldControlTest.h]: I think the `x` at the front of the old name `xtest_build_7` means that the test wasn't being run previously

**Review by thomashampson — APPROVED** [review]
Thanks for renaming all of the tests!
