### PR TITLE
Set default angle on preview tab

### LINKED ISSUE #34212: Get the default angle on the preview tab from the logs
The ISIS reflectometry interface preview tab currently attempts to perform a full reduction when you first load data. It will fail by default if angle is not changed because the reduction requires a non-zero angle. It would be good to provide a sensible default for the angle. This should be available in the sample logs as `Theta` so we could extract that from the file and populate the angle box after loading and before performing the reduction.

### PR DESCRIPTION
**Pull request by thomashampson**
This work was pair programmed with: @rbauststfc @robertapplin @gemmaguest 

**Description of work.**

This PR sets a default angle on the Preview tab in the ISIS Reflectometry interface. The angle is taken from the sample logs for a run when the workspace is loaded, if it exists and is valid (i.e. positive non-zero). This will provide a sensible default that will enable a full reduction to be run when the user loads a file. 

Note that the value is only updated if the current value is zero. This is so that a user-entered value is not overwritten; however it does mean that on changing to a different run, the value is not changed for the new run. This will be fixed by improvements to the UX in future PRs.

**To test:**

Must be run in a Debug build.

- Ensure the ISIS data archive is enabled in your user directories settings.
- Open the ISIS reflectometry GUI
- Set instrument to INTER
- On the Preview tab, enter run number 43583 and click Load
- The value in the Angle box should change from zero to `1.3`
- Note that you will now get an error because the processing will fail (this is expected for this run because it is a detector type that is not supported yet).
- Change the angle to `1.0` and click Load again. The angle should not change.

Fixes #34212.

*This does not require release notes* because **it relates to functionality that is not exposed in the release yet**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewModel.cpp [hunk 1]
```diff
@@ -122,4 +137,22 @@ void PreviewModel::exportReducedWsToAds() const {
...
 }
+
+std::optional<double> PreviewModel::getThetaFromLogs(const std::string &logName) const {
+  const Mantid::API::Run &run = getLoadedWs()->run();
+  if (!run.hasProperty(logName)) {
+    return std::nullopt;
+  }
+  Property *logData = run.getLogData(logName);
+  auto logPWV = dynamic_cast<const PropertyWithValue<double> *>(logData);
+  auto logTSP = dynamic_cast<const TimeSeriesProperty<double> *>(logData);
```
Comment (rbauststfc) [inline qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewModel.cpp:148]: Sorry, I should have thought of this yesterday and it's just a minor thing so possibly not worth changing at this stage, but I noticed we perform this cast when we potentially don't need it. I think this section of the method could maybe be written as:

```
auto logPWV = dynamic_cast<const PropertyWithValue<double> *>(logData);
if (logPWV) {
  return *logPWV;
}

auto logTSP = dynamic_cast<const TimeSeriesProperty<double> *>(logData);
if (logTSP && logTSP->realSize() > 0) {
  return logTSP->lastValue();
}

return std::nullopt;
```

Comment (gemmaguest) [reply qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewModel.cpp:148]: I agree but think it's not a big enough deal to change the PR at this stage seeing as we need this merged asap

**Review by gemmaguest — APPROVED** [review]
Code looks good and it functions as expected. I think the UX is a bit suboptimal at the moment but as this is work in progress I think that's fine and probably needs discussion with scientists before we polish this anyway, so I'm happy for this to go in :+1:
