### PR TITLE
IndirectDataReduction - Transmission - plotPreview crash

### LINKED ISSUE #17543: Indirect DataReduction - Transmission - crashes when updating preview plot
_Found during unscripted testing of indirect interfaces on 3.7.20160919.1516 (using Windows 7)_

When running the transmission interface the preview plot crashes as it attempts to plot a group workspace

### Steps to reproduce the behavior
Indirect < Data Reduction < Transmission

### PR DESCRIPTION
**Pull request by louisemccann**
The name of the result group workspace has been changed to avoid clashing with the output workspace, hence the plotPreview no longer attempts to plot a group workspace.

**To test:**
Indirect < Data Reduction < Transmission
Sample: IRS26176
Background: IRS26173

Fixes #17543.

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by tom-perkins** [comment]
Ran the interface using the data files above. No crash seen, and data plotted in the preview plot OK.
:shipit: (when the builds pass)

File: MantidQt/CustomInterfaces/src/Indirect/IndirectTransmission.cpp [hunk 1]
```diff
@@ -147,7 +148,8 @@ void IndirectTransmission::saveClicked() {
  * Handle mantid plotting
  */
 void IndirectTransmission::plotClicked() {
-  QString outputWs = (m_uiForm.dsSampleInput->getCurrentDataName() + "_trans");
+  QString outputWs =
+      (m_uiForm.dsSampleInput->getCurrentDataName() + "_transmission");
```
Comment (tom-perkins) [inline MantidQt/CustomInterfaces/src/Indirect/IndirectTransmission.cpp]: Would be good to refactor this so the string `_transmission` only appears in one place, e.g. as a constant. (Outside scope of this issue, can be done as a future maintenance task)
