### PR TITLE
Fix "List Data" causing MantidPlot crash

### LINKED ISSUE #14367: "List Data" option when right clicking on masked workspace causes crash
Occurs with an MDHistoWorkspace that has a mask applied. Right clicking on workspace and selecting "List Data" causes MantidPlot to crash.

This issue is related to a general review of masks: #12689.

Can be repeated with the workspace created with the following python
```python

ws = CreateMDWorkspace(Dimensions='3', Extents='-2,2,-2,2,-2,2', Names='h,k,l',
                       Units='rlu,rlu,rlu', SplitInto='4')
FakeMDEventData(ws, PeakParams='10000,1,1,1,0.1', RandomSeed='63759', RandomizeSignal='1')
FakeMDEventData(ws, PeakParams='100000,0,0,0,0.1', RandomSeed='63759', RandomizeSignal='1')
FakeMDEventData(ws, PeakParams='40000,1,1,0,0.1', RandomSeed='63759', RandomizeSignal='1')
print "Number of events =", ws.getNEvents()
wsBinned = BinMD(ws,AlignedDim0='h,-2,2,100',AlignedDim1='k,-2,2,100',AlignedDim2='l,-2,2,100')
MaskMD(Workspace=wsBinned,Dimensions="h,k,l",Extents="-2,2,-2,2,-2,2")

```

### PR DESCRIPTION
**Pull request by matthew-d-jones**
Fixes #14367 

For large masked regions of MDHistoWorkspaces choosing "List Data" when right clicking on the workspace causes MantidPlot to crash. This was caused by stack overflow due to high recursion depth in the `MDHistoWorkspaceIterator`. It has been fixed by refactoring `MDHistoWorkspaceIterator::next()` to avoid recursion. Test coverage was improved in the process; the case of using an implicit function and a mask on the same workspace is now covered.

**To Test:**
Selecting "List Data" when right clicking on workspace "wsBinned", created with the following code, would previously crash MantidPlot. The observed behaviour was that MantidPlot would instantly cease running and disappear. "List Data" should now not cause the crash, and a table of data with a single row should appear.

``` python

ws = CreateMDWorkspace(Dimensions='3', Extents='-2,2,-2,2,-2,2', Names='h,k,l',
                       Units='rlu,rlu,rlu', SplitInto='4')
FakeMDEventData(ws, PeakParams='10,1,1,1,0.1', RandomizeSignal='1')
wsBinned = BinMD(ws,AlignedDim0='h,-2,2,64',AlignedDim1='k,-2,2,64',AlignedDim2='l,-2,2,64')
MaskMD(Workspace=wsBinned,Dimensions="h,k,l",Extents="-2,2,-2,2,-2,2")

```

### CODE REVIEW

File: Framework/DataObjects/src/MDHistoWorkspaceIterator.cpp [hunk 1]
```diff
@@ -311,24 +312,20 @@ bool MDHistoWorkspaceIterator::next() {
...
         m_center[d] =
             m_origin[d] + (coord_t(m_index[d]) + 0.5f) * m_binWidth[d];
-        //          std::cout << m_center[d] << ",";
       }
-      //        std::cout<<std::endl;
-      // Keep incrementing until you are in the implicit function
-    } while (!allIncremented && !m_function->isPointContained(m_center) &&
-             m_pos < m_max);
+      // Keep incrementing until you are in the implicit function and not masked
+    } while (m_pos < m_max &&
```
Comment (OwenArnold) [inline Framework/DataObjects/src/MDHistoWorkspaceIterator.cpp]: Yes. This looks right.

**Comment by matthew-d-jones** [comment]
Added regression test and made existing test name more explicit. I've checked that the test fails with the old implementation of `MDHistoWorkspaceIterator::next()` and passes with the new one.
