### PR TITLE
Fix issues in DataHandlingTest reported by address sanitizer

### LINKED ISSUE #17439: DataHandling::LoadDetectorInfo: AddressSanitizer: heap-buffer-overflow
From a run of units tests with Address Sanitizer (compiled with `-DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=-fsanitize=address`):

```
738/1683 Test #738: DataHandlingTest_LoadDetectorInfoTest ........................***Failed    1.79 sec
FrameworkManager-[Notice] Welcome to Mantid 3.7.20160907.1229
FrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid
Running 5 tests=================================================================
==95671==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6030004d4268 at pc 0x7fea3608bafa bp 0x7ffcca4ce8e0 sp 0x7ffcca4ce088
READ of size 72 at 0x6030004d4268 thread T0
    #0 0x7fea3608baf9 (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x2faf9)
    #1 0x7fea3081d44d (/usr/lib/x86_64-linux-gnu/libhdf5_serial.so.8+0x7244d)
    #2 0x7fea309b364a in H5VM_opvv (/usr/lib/x86_64-linux-gnu/libhdf5_serial.so.8+0x20864a)
    #3 0x7fea3081cd8c (/usr/lib/x86_64-linux-gnu/libhdf5_serial.so.8+0x71d8c)
    #4 0x7fea3082d7d0 (/usr/lib/x86_64-linux-gnu/libhdf5_serial.so.8+0x827d0)
    #5 0x7fea3082e02c in H5D__select_write (/usr/lib/x86_64-linux-gnu/libhdf5_serial.so.8+0x8302c)
    #6 0x7fea3081de3c in H5D__contig_write (/usr/lib/x86_64-linux-gnu/libhdf5_serial.so.8+0x72e3c)
    #7 0x7fea30827c10 (/usr/lib/x86_64-linux-gnu/libhdf5_serial.so.8+0x7cc10)
    #8 0x7fea30828323 in H5Dwrite (/usr/lib/x86_64-linux-gnu/libhdf5_serial.so.8+0x7d323)
    #9 0x7fea317b15e7 (/usr/lib/libNeXus.so.0+0xf5e7)
    #10 0x7fea3157cb44 in NeXus::File::putData(void const*) (/usr/lib/libNeXusCPP.so.0+0xfb44)
    #11 0xaa317e in writeDetNXSfile /home/simon/code/mantid/Framework/DataHandling/test/LoadDetectorInfoTest.h:178
    #12 0xaa6098 in LoadDetectorInfoTest::LoadDetectorInfoTest() /home/simon/code/mantid/Framework/DataHandling/test/LoadDetectorInfoTest.h:257
    #13 0xaa5eb2 in LoadDetectorInfoTest::createSuite() /home/simon/code/mantid/Framework/DataHandling/test/LoadDetectorInfoTest.h:246
    #14 0xab05b6 in CxxTest::DynamicSuiteDescription<LoadDetectorInfoTest>::createSuite() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/RealDescriptions.h:162
    #15 0xaaf9db in CxxTest::DynamicSuiteDescription<LoadDetectorInfoTest>::setUp() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/RealDescriptions.h:179
    #16 0xbc510e in CxxTest::TestRunner::runSuite(CxxTest::SuiteDescription&) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:76
    #17 0xbc4d7f in CxxTest::TestRunner::runWorld() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:63
    #18 0xbc49ca in CxxTest::TestRunner::runAllTests(CxxTest::TestListener&) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:24
    #19 0xbd2703 in CxxTest::XUnitPrinter::run() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/XUnitPrinter.h:30
    #20 0xbd41f7 in int CxxTest::Main<CxxTest::XUnitPrinter>(CxxTest::XUnitPrinter&, int, char**) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestMain.h:106
    #21 0xbbd8d1 in main /home/simon/build/mantid-debug/Framework/DataHandling/test/DataHandlingTest_runner.cpp:27
    #22 0x7fea2f769a3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20a3f)
    #23 0x4a4378 in _start (/home/simon/build/mantid-debug/bin/DataHandlingTest+0x4a4378)

0x6030004d4268 is located 0 bytes to the right of 24-byte region [0x6030004d4250,0x6030004d4268)
allocated by thread T0 here:
    #0 0x7fea360b41af in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x581af)
    #1 0x58ca22 in __gnu_cxx::new_allocator<float>::allocate(unsigned long, void const*) /usr/include/c++/4.9/ext/new_allocator.h:104
    #2 0x58c98b in std::allocator_traits<std::allocator<float> >::allocate(std::allocator<float>&, unsigned long) /usr/include/c++/4.9/bits/alloc_traits.h:357
    #3 0x58c8a1 in std::_Vector_base<float, std::allocator<float> >::_M_allocate(unsigned long) /usr/include/c++/4.9/bits/stl_vector.h:170
    #4 0x58c6c4 in std::_Vector_base<float, std::allocator<float> >::_M_create_storage(unsigned long) /usr/include/c++/4.9/bits/stl_vector.h:185
    #5 0x58c3b2 in std::_Vector_base<float, std::allocator<float> >::_Vector_base(unsigned long, std::allocator<float> const&) /usr/include/c++/4.9/bits/stl_vector.h:136
    #6 0x5970f3 in std::vector<float, std::allocator<float> >::vector(unsigned long, std::allocator<float> const&) /usr/include/c++/4.9/bits/stl_vector.h:278
    #7 0xaa213e in writeDetNXSfile /home/simon/code/mantid/Framework/DataHandling/test/LoadDetectorInfoTest.h:100
    #8 0xaa6098 in LoadDetectorInfoTest::LoadDetectorInfoTest() /home/simon/code/mantid/Framework/DataHandling/test/LoadDetectorInfoTest.h:257
    #9 0xaa5eb2 in LoadDetectorInfoTest::createSuite() /home/simon/code/mantid/Framework/DataHandling/test/LoadDetectorInfoTest.h:246
    #10 0xab05b6 in CxxTest::DynamicSuiteDescription<LoadDetectorInfoTest>::createSuite() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/RealDescriptions.h:162
    #11 0xaaf9db in CxxTest::DynamicSuiteDescription<LoadDetectorInfoTest>::setUp() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/RealDescriptions.h:179
    #12 0xbc510e in CxxTest::TestRunner::runSuite(CxxTest::SuiteDescription&) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:76
    #13 0xbc4d7f in CxxTest::TestRunner::runWorld() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:63
    #14 0xbc49ca in CxxTest::TestRunner::runAllTests(CxxTest::TestListener&) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:24
    #15 0xbd2703 in CxxTest::XUnitPrinter::run() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/XUnitPrinter.h:30
    #16 0xbd41f7 in int CxxTest::Main<CxxTest::XUnitPrinter>(CxxTest::XUnitPrinter&, int, char**) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestMain.h:106
    #17 0xbbd8d1 in main /home/simon/build/mantid-debug/Framework/DataHandling/test/DataHandlingTest_runner.cpp:27
    #18 0x7fea2f769a3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20a3f)

SUMMARY: AddressSanitizer: heap-buffer-overflow ??:0 ??
Shadow bytes around the buggy address:
  0x0c06800927f0: fd fd fd fa fa fa fd fd fd fd fa fa fd fd fd fa
  0x0c0680092800: fa fa 00 00 00 00 fa fa 00 00 00 fa fa fa 00 00
  0x0c0680092810: 00 05 fa fa 00 00 00 05 fa fa 00 00 00 fa fa fa
  0x0c0680092820: 00 00 00 fa fa fa 00 00 00 fa fa fa 00 00 00 fa
  0x0c0680092830: fa fa 00 00 00 fa fa fa 00 00 00 fa fa fa 00 00
=>0x0c0680092840: 00 fa fa fa fd fd fd fd fa fa 00 00 00[fa]fa fa
  0x0c0680092850: fd fd fd fa fa fa fd fd fd fa fa fa fd fd fd fa
  0x0c0680092860: fa fa fd fd fd fa fa fa fd fd fd fa fa fa fd fd
  0x0c0680092870: fd fd fa fa fd fd fd fa fa fa fd fd fd fd fa fa
  0x0c0680092880: fd fd fd fd fa fa fd fd fd fd fa fa fd fd fd fa
  0x0c0680092890: fa fa fd fd fd fa fa fa fd fd fd fa fa fa fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Contiguous container OOB:fc
  ASan internal:           fe
```

### LINKED ISSUE #17441: DataHandling::LoadILLSANS: AddressSanitizer: heap-buffer-overflow
From a run of units tests with Address Sanitizer (compiled with `-DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=-fsanitize=address`):

```
758/1683 Test #758: DataHandlingTest_LoadILLSANSTest .............................***Failed    2.38 sec
FrameworkManager-[Notice] Welcome to Mantid 3.7.20160907.1229
FrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid
Running 5 tests...LoadILLSANS-[Notice] LoadILLSANS started
=================================================================
==100762==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6140000167d0 at pc 0x7f86c838653b bp 0x7ffe43480a50 sp 0x7ffe43480a40
READ of size 4 at 0x6140000167d0 thread T0
    #0 0x7f86c838653a in double* std::__copy_move<false, false, std::random_access_iterator_tag>::__copy_m<float*, double*>(float*, float*, double*) /usr/include/c++/4.9/bits/stl_algobase.h:336
    #1 0x7f86c83857de in double* std::__copy_move_a<false, float*, double*>(float*, float*, double*) /usr/include/c++/4.9/bits/stl_algobase.h:396
    #2 0x7f86c838239c in double* std::__copy_move_a2<false, float*, double*>(float*, float*, double*) /usr/include/c++/4.9/bits/stl_algobase.h:434
    #3 0x7f86c837e152 in double* std::copy<float*, double*>(float*, float*, double*) /usr/include/c++/4.9/bits/stl_algobase.h:466
    #4 0x7f86c837ab97 in void std::vector<double, std::allocator<double> >::_M_assign_aux<float*>(float*, float*, std::forward_iterator_tag) /usr/include/c++/4.9/bits/vector.tcc:284
    #5 0x7f86c83791e9 in void std::vector<double, std::allocator<double> >::_M_assign_dispatch<float*>(float*, float*, std::__false_type) /usr/include/c++/4.9/bits/stl_vector.h:1336
    #6 0x7f86c8376fb3 in void std::vector<double, std::allocator<double> >::assign<float*, void>(float*, float*) /usr/include/c++/4.9/bits/stl_vector.h:508
    #7 0x7f86c8370b27 in Mantid::DataHandling::LoadHelper::getTimeBinningFromNexusPath(Mantid::NeXus::NXEntry const&, std::string const&) /home/simon/code/mantid/Framework/DataHandling/src/LoadHelper.cpp:69
    #8 0x7f86c83afaa1 in Mantid::DataHandling::LoadILLSANS::initWorkSpace(Mantid::NeXus::NXEntry&, std::string const&) /home/simon/code/mantid/Framework/DataHandling/src/LoadILLSANS.cpp:210
    #9 0x7f86c83ae110 in Mantid::DataHandling::LoadILLSANS::exec() /home/simon/code/mantid/Framework/DataHandling/src/LoadILLSANS.cpp:88
    #10 0x7f86c933cf56 in Mantid::API::Algorithm::execute() /home/simon/code/mantid/Framework/API/src/Algorithm.cpp:563
    #11 0x99584d in LoadILLSANSTest::test_exec_TOF() /home/simon/code/mantid/Framework/DataHandling/test/LoadILLSANSTest.h:45
    #12 0x9972dc in TestDescription_suite_LoadILLSANSTest_test_exec_TOF::runTest() /home/simon/build/mantid-debug/Framework/DataHandling/test/LoadILLSANSTest.cpp:45
    #13 0xbbf5b9 in CxxTest::RealTestDescription::run() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/RealDescriptions.cpp:96
    #14 0xbc558e in CxxTest::TestRunner::runTest(CxxTest::TestDescription&) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:94
    #15 0xbc51af in CxxTest::TestRunner::runSuite(CxxTest::SuiteDescription&) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:79
    #16 0xbc4d7f in CxxTest::TestRunner::runWorld() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:63
    #17 0xbc49ca in CxxTest::TestRunner::runAllTests(CxxTest::TestListener&) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:24
    #18 0xbd2703 in CxxTest::XUnitPrinter::run() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/XUnitPrinter.h:30
    #19 0xbd41f7 in int CxxTest::Main<CxxTest::XUnitPrinter>(CxxTest::XUnitPrinter&, int, char**) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestMain.h:106
    #20 0xbbd8d1 in main /home/simon/build/mantid-debug/Framework/DataHandling/test/DataHandlingTest_runner.cpp:27
    #21 0x7f86c314da3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20a3f)
    #22 0x4a4378 in _start (/home/simon/build/mantid-debug/bin/DataHandlingTest+0x4a4378)

0x6140000167d0 is located 0 bytes to the right of 400-byte region [0x614000016640,0x6140000167d0)
allocated by thread T0 here:
    #0 0x7f86c9a982ef in operator new[](unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x582ef)
    #1 0x7f86c821b532 in Mantid::NeXus::NXDataSetTyped<float>::alloc(int) /home/simon/code/mantid/Framework/DataHandling/../Nexus/inc/MantidNexus/NexusClasses.h:454
    #2 0x7f86c82199cf in Mantid::NeXus::NXDataSetTyped<float>::load(int, int, int, int, int) /home/simon/code/mantid/Framework/DataHandling/../Nexus/inc/MantidNexus/NexusClasses.h:428
    #3 0x7f86c8370a80 in Mantid::DataHandling::LoadHelper::getTimeBinningFromNexusPath(Mantid::NeXus::NXEntry const&, std::string const&) /home/simon/code/mantid/Framework/DataHandling/src/LoadHelper.cpp:62
    #4 0x7f86c83afaa1 in Mantid::DataHandling::LoadILLSANS::initWorkSpace(Mantid::NeXus::NXEntry&, std::string const&) /home/simon/code/mantid/Framework/DataHandling/src/LoadILLSANS.cpp:210
    #5 0x7f86c83ae110 in Mantid::DataHandling::LoadILLSANS::exec() /home/simon/code/mantid/Framework/DataHandling/src/LoadILLSANS.cpp:88
    #6 0x7f86c933cf56 in Mantid::API::Algorithm::execute() /home/simon/code/mantid/Framework/API/src/Algorithm.cpp:563
    #7 0x99584d in LoadILLSANSTest::test_exec_TOF() /home/simon/code/mantid/Framework/DataHandling/test/LoadILLSANSTest.h:45
    #8 0x9972dc in TestDescription_suite_LoadILLSANSTest_test_exec_TOF::runTest() /home/simon/build/mantid-debug/Framework/DataHandling/test/LoadILLSANSTest.cpp:45
    #9 0xbbf5b9 in CxxTest::RealTestDescription::run() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/RealDescriptions.cpp:96
    #10 0xbc558e in CxxTest::TestRunner::runTest(CxxTest::TestDescription&) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:94
    #11 0xbc51af in CxxTest::TestRunner::runSuite(CxxTest::SuiteDescription&) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:79
    #12 0xbc4d7f in CxxTest::TestRunner::runWorld() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:63
    #13 0xbc49ca in CxxTest::TestRunner::runAllTests(CxxTest::TestListener&) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:24
    #14 0xbd2703 in CxxTest::XUnitPrinter::run() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/XUnitPrinter.h:30
    #15 0xbd41f7 in int CxxTest::Main<CxxTest::XUnitPrinter>(CxxTest::XUnitPrinter&, int, char**) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestMain.h:106
    #16 0xbbd8d1 in main /home/simon/build/mantid-debug/Framework/DataHandling/test/DataHandlingTest_runner.cpp:27
    #17 0x7f86c314da3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20a3f)

SUMMARY: AddressSanitizer: heap-buffer-overflow /usr/include/c++/4.9/bits/stl_algobase.h:336 double* std::__copy_move<false, false, std::random_access_iterator_tag>::__copy_m<float*, double*>(float*, float*, double*)
Shadow bytes around the buggy address:
  0x0c287fffaca0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c287fffacb0: 00 00 00 00 00 00 00 00 00 00 00 fa fa fa fa fa
  0x0c287fffacc0: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c287fffacd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c287ffface0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c287fffacf0: 00 00 00 00 00 00 00 00 00 00[fa]fa fa fa fa fa
  0x0c287fffad00: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c287fffad10: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c287fffad20: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c287fffad30: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fa fa
  0x0c287fffad40: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Contiguous container OOB:fc
  ASan internal:           fe
```

### LINKED ISSUE #17442: DataHandling::LoadSINQFocus: AddressSanitizer: heap-buffer-overflow
From a run of units tests with Address Sanitizer (compiled with `-DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=-fsanitize=address`):

```
799/1683 Test #799: DataHandlingTest_LoadSINQFocusTest ...........................***Failed    1.60 sec
FrameworkManager-[Notice] Welcome to Mantid 3.7.20160907.1229
FrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid
Running 4 tests...DeprecatedAlgorithm-[Warning] Invalid replacement algorithm 'LoadSINQ'Replacement algorithm not registered.
LoadSINQFocus-[Error] LoadSINQFocus is deprecated (on 2013-10-28). Use LoadSINQ instead.
LoadSINQFocus-[Notice] LoadSINQFocus started
=================================================================
==106822==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62100005d9b8 at pc 0x7f04bc34f53b bp 0x7ffe3e02ea50 sp 0x7ffe3e02ea40
READ of size 4 at 0x62100005d9b8 thread T0
    #0 0x7f04bc34f53a in double* std::__copy_move<false, false, std::random_access_iterator_tag>::__copy_m<float*, double*>(float*, float*, double*) /usr/include/c++/4.9/bits/stl_algobase.h:336
    #1 0x7f04bc34e7de in double* std::__copy_move_a<false, float*, double*>(float*, float*, double*) /usr/include/c++/4.9/bits/stl_algobase.h:396
    #2 0x7f04bc34b39c in double* std::__copy_move_a2<false, float*, double*>(float*, float*, double*) /usr/include/c++/4.9/bits/stl_algobase.h:434
    #3 0x7f04bc347152 in double* std::copy<float*, double*>(float*, float*, double*) /usr/include/c++/4.9/bits/stl_algobase.h:466
    #4 0x7f04bc343b97 in void std::vector<double, std::allocator<double> >::_M_assign_aux<float*>(float*, float*, std::forward_iterator_tag) /usr/include/c++/4.9/bits/vector.tcc:284
    #5 0x7f04bc3421e9 in void std::vector<double, std::allocator<double> >::_M_assign_dispatch<float*>(float*, float*, std::__false_type) /usr/include/c++/4.9/bits/stl_vector.h:1336
    #6 0x7f04bc33ffb3 in void std::vector<double, std::allocator<double> >::assign<float*, void>(float*, float*) /usr/include/c++/4.9/bits/stl_vector.h:508
    #7 0x7f04bc339b27 in Mantid::DataHandling::LoadHelper::getTimeBinningFromNexusPath(Mantid::NeXus::NXEntry const&, std::string const&) /home/simon/code/mantid/Framework/DataHandling/src/LoadHelper.cpp:69
    #8 0x7f04bc51425a in Mantid::DataHandling::LoadSINQFocus::loadDataIntoTheWorkSpace(Mantid::NeXus::NXEntry&) /home/simon/code/mantid/Framework/DataHandling/src/LoadSINQFocus.cpp:163
    #9 0x7f04bc513211 in Mantid::DataHandling::LoadSINQFocus::exec() /home/simon/code/mantid/Framework/DataHandling/src/LoadSINQFocus.cpp:93
    #10 0x7f04bd305f56 in Mantid::API::Algorithm::execute() /home/simon/code/mantid/Framework/API/src/Algorithm.cpp:563
    #11 0x79d69d in LoadSINQFocusTest::test_exec() /home/simon/code/mantid/Framework/DataHandling/test/LoadSINQFocusTest.h:43
    #12 0x79dee2 in TestDescription_suite_LoadSINQFocusTest_test_exec::runTest() /home/simon/build/mantid-debug/Framework/DataHandling/test/LoadSINQFocusTest.cpp:45
    #13 0xbbf5b9 in CxxTest::RealTestDescription::run() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/RealDescriptions.cpp:96
    #14 0xbc558e in CxxTest::TestRunner::runTest(CxxTest::TestDescription&) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:94
    #15 0xbc51af in CxxTest::TestRunner::runSuite(CxxTest::SuiteDescription&) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:79
    #16 0xbc4d7f in CxxTest::TestRunner::runWorld() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:63
    #17 0xbc49ca in CxxTest::TestRunner::runAllTests(CxxTest::TestListener&) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:24
    #18 0xbd2703 in CxxTest::XUnitPrinter::run() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/XUnitPrinter.h:30
    #19 0xbd41f7 in int CxxTest::Main<CxxTest::XUnitPrinter>(CxxTest::XUnitPrinter&, int, char**) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestMain.h:106
    #20 0xbbd8d1 in main /home/simon/build/mantid-debug/Framework/DataHandling/test/DataHandlingTest_runner.cpp:27
    #21 0x7f04b7116a3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20a3f)
    #22 0x4a4378 in _start (/home/simon/build/mantid-debug/bin/DataHandlingTest+0x4a4378)

0x62100005d9b8 is located 0 bytes to the right of 4280-byte region [0x62100005c900,0x62100005d9b8)
allocated by thread T0 here:
    #0 0x7f04bda612ef in operator new[](unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x582ef)
    #1 0x7f04bc1e4532 in Mantid::NeXus::NXDataSetTyped<float>::alloc(int) /home/simon/code/mantid/Framework/DataHandling/../Nexus/inc/MantidNexus/NexusClasses.h:454
    #2 0x7f04bc1e29cf in Mantid::NeXus::NXDataSetTyped<float>::load(int, int, int, int, int) /home/simon/code/mantid/Framework/DataHandling/../Nexus/inc/MantidNexus/NexusClasses.h:428
    #3 0x7f04bc339a80 in Mantid::DataHandling::LoadHelper::getTimeBinningFromNexusPath(Mantid::NeXus::NXEntry const&, std::string const&) /home/simon/code/mantid/Framework/DataHandling/src/LoadHelper.cpp:62
    #4 0x7f04bc51425a in Mantid::DataHandling::LoadSINQFocus::loadDataIntoTheWorkSpace(Mantid::NeXus::NXEntry&) /home/simon/code/mantid/Framework/DataHandling/src/LoadSINQFocus.cpp:163
    #5 0x7f04bc513211 in Mantid::DataHandling::LoadSINQFocus::exec() /home/simon/code/mantid/Framework/DataHandling/src/LoadSINQFocus.cpp:93
    #6 0x7f04bd305f56 in Mantid::API::Algorithm::execute() /home/simon/code/mantid/Framework/API/src/Algorithm.cpp:563
    #7 0x79d69d in LoadSINQFocusTest::test_exec() /home/simon/code/mantid/Framework/DataHandling/test/LoadSINQFocusTest.h:43
    #8 0x79dee2 in TestDescription_suite_LoadSINQFocusTest_test_exec::runTest() /home/simon/build/mantid-debug/Framework/DataHandling/test/LoadSINQFocusTest.cpp:45
    #9 0xbbf5b9 in CxxTest::RealTestDescription::run() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/RealDescriptions.cpp:96
    #10 0xbc558e in CxxTest::TestRunner::runTest(CxxTest::TestDescription&) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:94
    #11 0xbc51af in CxxTest::TestRunner::runSuite(CxxTest::SuiteDescription&) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:79
    #12 0xbc4d7f in CxxTest::TestRunner::runWorld() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:63
    #13 0xbc49ca in CxxTest::TestRunner::runAllTests(CxxTest::TestListener&) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestRunner.h:24
    #14 0xbd2703 in CxxTest::XUnitPrinter::run() /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/XUnitPrinter.h:30
    #15 0xbd41f7 in int CxxTest::Main<CxxTest::XUnitPrinter>(CxxTest::XUnitPrinter&, int, char**) /home/simon/code/mantid/Testing/Tools/cxxtest/cxxtest/TestMain.h:106
    #16 0xbbd8d1 in main /home/simon/build/mantid-debug/Framework/DataHandling/test/DataHandlingTest_runner.cpp:27
    #17 0x7f04b7116a3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20a3f)

SUMMARY: AddressSanitizer: heap-buffer-overflow /usr/include/c++/4.9/bits/stl_algobase.h:336 double* std::__copy_move<false, false, std::random_access_iterator_tag>::__copy_m<float*, double*>(float*, float*, double*)
Shadow bytes around the buggy address:
  0x0c4280003ae0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4280003af0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4280003b00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4280003b10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4280003b20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c4280003b30: 00 00 00 00 00 00 00[fa]fa fa fa fa fa fa fa fa
  0x0c4280003b40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4280003b50: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4280003b60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4280003b70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4280003b80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Contiguous container OOB:fc
  ASan internal:           fe
```

### PR DESCRIPTION
**Pull request by martyngigg**
**Description of work.**

Fixes buffer overflows and some memory leaks within the DataHandling library.

**Report to:** [nobody]. 

**To test:**

Code review.

Fixes #17441  
Fixes #17442 
Fixes #17439 

*This does not require release notes* because **they are not large enough to report**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/DataHandling/inc/MantidDataHandling/LoadBankFromDiskTask.h [hunk 1]
```diff
@@ -54,12 +54,13 @@ class MANTID_DATAHANDLING_DLL LoadBankFromDiskTask : public Kernel::Task {
...
   void prepareEventId(::NeXus::File &file, int64_t &start_event,
-                      int64_t &stop_event, std::vector<uint64_t> &event_index);
-  void loadEventId(::NeXus::File &file);
-  void loadTof(::NeXus::File &file);
-  void loadEventWeights(::NeXus::File &file);
+                      int64_t &stop_event,
+                      const std::vector<uint64_t> &event_index);
+  std::unique_ptr<uint32_t[]> loadEventId(::NeXus::File &file);
+  std::unique_ptr<float[]> loadTof(::NeXus::File &file);
+  std::unique_ptr<float[]> loadEventWeights(::NeXus::File &file);
```
Comment (quantumsteve) [inline Framework/DataHandling/inc/MantidDataHandling/LoadBankFromDiskTask.h]: similarly, can these three functions return a `std::vector`? Or does that expand the scope too much?

File: Framework/DataHandling/inc/MantidDataHandling/LoadBankFromDiskTask.h [hunk 2]
```diff
@@ -54,12 +54,13 @@ class MANTID_DATAHANDLING_DLL LoadBankFromDiskTask : public Kernel::Task {
 
 private:
   void loadPulseTimes(::NeXus::File &file);
-  void loadEventIndex(::NeXus::File &file, std::vector<uint64_t> &event_index);
+  std::unique_ptr<std::vector<uint64_t>> loadEventIndex(::NeXus::File &file);
```
Comment (quantumsteve) [inline Framework/DataHandling/inc/MantidDataHandling/LoadBankFromDiskTask.h]: I think it is more idiomatic to return a `std::vector<uint64_t>`, then at the end use `std::move` to move contents of the container into a `boost::shared_ptr`.

File: Framework/DataHandling/src/LoadAscii2.cpp [hunk 3]
```diff
@@ -514,13 +514,12 @@ void LoadAscii2::newSpectra() {
...
       }
-      delete m_curSpectra;
-      m_curSpectra = nullptr;
+      m_curSpectra.reset();
     }
 
-    m_curSpectra =
-        new DataObjects::Histogram1D(HistogramData::Histogram::XMode::Points,
-                                     HistogramData::Histogram::YMode::Counts);
+    m_curSpectra = Kernel::make_unique<DataObjects::Histogram1D>(
```
Comment (quantumsteve) [inline Framework/DataHandling/src/LoadAscii2.cpp]: Now that we require C++14, may we now use `std::make_unique`?

**Review by quantumsteve — CHANGES_REQUESTED** [review]
👍 for finding and addressing these issues from address sanitizer.

Comments are a few additional recommendations to make this a bit cleaner.

File: Framework/DataHandling/inc/MantidDataHandling/LoadBankFromDiskTask.h (hunk 1 above)
Comment (martyngigg) [reply Framework/DataHandling/inc/MantidDataHandling/LoadBankFromDiskTask.h]: I had considered this at first too but then later on the array is shared between several parallel tasks and refactoring that code was going to expand the scope a little too much.

File: Framework/DataHandling/inc/MantidDataHandling/LoadBankFromDiskTask.h (hunk 2 above)
Comment (martyngigg) [reply Framework/DataHandling/inc/MantidDataHandling/LoadBankFromDiskTask.h]: Good point. That is clearer.

File: Framework/DataHandling/src/LoadAscii2.cpp (hunk 3 above)
Comment (martyngigg) [reply Framework/DataHandling/src/LoadAscii2.cpp]: It does look like all of our compiles now support this so I think we're good.

**Comment by martyngigg** [comment]
Thanks for the suggestions, Steve. I've made the changes.

File: Framework/DataHandling/src/LoadAscii2.cpp (hunk 3 above)
Comment (martyngigg) [reply Framework/DataHandling/src/LoadAscii2.cpp]: Should we announce that people should now prefer `std::make_unique` of `Kernel` and create a maintenance task to replace everything?

**Review by quantumsteve — APPROVED** [review]

File: Framework/DataHandling/src/LoadAscii2.cpp (hunk 3 above)
Comment (quantumsteve) [reply Framework/DataHandling/src/LoadAscii2.cpp]: Yes, we need to announce this to more people. Since it is the first breaking change with GCC 4.8, we also need some discussion of changes in how we build on RHEL 7.

@VickieLynch @peterfpeterson
