### PR TITLE
Fix slice viewer bug with text axis

### LINKED ISSUE #30344: Error/Crash when using Slice Viewer on a workspace from FFT
### Expected behavior
When using the Slice Viewer on a workspace that is the output of an FFT, Slice Viewer should not cause an error when interacting with the plot.

### Actual behavior
The following stacktrace is reported in the messages pane:
```
IndexError: invalid vector subscript
Traceback (most recent call last):
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\backends\backend_qt5.py", line 506, in _draw_idle
    self.draw()
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\backends\backend_agg.py", line 388, in draw
    self.figure.draw(self.renderer)
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\figure.py", line 1708, in draw
    mimage._draw_list_compositing_images(
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\axes\_base.py", line 2647, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\MantidNightlyInstall\bin\mantid\plots\resampling_image\samplingimage.py", line 72, in draw
    self._resample_image()
  File "C:\MantidNightlyInstall\bin\mantid\plots\resampling_image\samplingimage.py", line 109, in _resample_image
    x, y, data = get_matrix_2d_ragged(self.ws,
  File "C:\MantidNightlyInstall\bin\mantid\plots\datafunctions.py", line 519, in get_matrix_2d_ragged
    counts = interpolate_y_data(workspace, x_centers, y, normalize_by_bin_width, spectrum_info=spec_info,
  File "C:\MantidNightlyInstall\bin\mantid\plots\datafunctions.py", line 593, in interpolate_y_data
    if not (spectrum_info and spectrum_info.hasDetectors(workspace_index) and spectrum_info.isMonitor(
IndexError: invalid vector subscript
```

Only once have I found this to cause a sad mantid.

### Steps to reproduce the behavior
1. Run the following script:
```
ws = CreateSampleWorkspace(OutputWorkspace='ws')
ws = FFT(ws, AutoShift=True)
```
2. Open sliceviewer and manipulate the plot (zoom in and out, pan around) until the exception occurs.

### Platforms affected
Tested on Windows

### PR DESCRIPTION
**Pull request by Harrietbrown**
**Description of work.**

In issue was found with using slice viewer on the output of FFT, this was a result of an underflow in getting the index of a value from a TextAxis, this PR changes the function in TextAxis to be consistent with the same functions in other Axis objects.

**To test:**

1. Load a workspace with a text axis, or run:
```
ws = CreateSampleWorkspace(OutputWorkspace='ws')
ws = FFT(ws, AutoShift=True)
```
2. open the workspace in sliceviewer.
3. zoom out so that the plot range is outside of the range of spectra. this will produce an error in the log but will not crash. this error is already present in other workspaces when zoomed out.

Fixes #30344

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/API/src/TextAxis.cpp [hunk 1]
```diff
@@ -71,7 +72,14 @@ void TextAxis::setValue(const std::size_t &index, const double &value) {
  * Returns the value that has been passed to it as a size_t
  */
 size_t TextAxis::indexOfValue(const double value) const {
-  return static_cast<size_t>(value);
+  auto spec_num = length();
```
Comment (robertapplin) [inline Framework/API/src/TextAxis.cpp:75]: I think this line is unused

File: Framework/API/src/TextAxis.cpp [hunk 2]
```diff
@@ -71,7 +72,14 @@ void TextAxis::setValue(const std::size_t &index, const double &value) {
...
+  std::vector<double> spectraNumbers;
+  spectraNumbers.reserve(length());
+  for (size_t i = 0; i < length(); i++) {
+    spectraNumbers.push_back(static_cast<double>(i));
```
Comment (robertapplin) [inline Framework/API/src/TextAxis.cpp:79]: `emplace_back` is preferred for this

**Review by robertapplin — CHANGES_REQUESTED** [review]
Looks good, just a few comments. Would it be possible to add a test for this?

**Review by robertapplin — APPROVED** [review]
