### PR TITLE
Workbench: Notification service and Notifications on errors

### LINKED ISSUE #27305: Notifications for Algorithm Error
James Lord via the Mantid Forum: https://forum.mantidproject.org/t/error-dialog-boxes/588

Currently if an Algorithm fails (but the inputs passed their individual validators) there is an error message in red in the Messages Window. While developers see this, Users may have this hidden or covered by plots and so the Algorithm failure is unnoticed.

Proposed ideas around this include:
- A pop-up to notify and explain the error (potentially tedious).
- A notification system to do the same as above.
- Something red appearing in the Algorithms Window (the progress bar could go red or the entire Window!) This approach assumes a user can at all times see the Algorithm Window. 

-Worth discussing would this replace or complement the error in the Messages Window
-Would any of this apply to similar errors from scripts?

### PR DESCRIPTION
**Pull request by NickDraper**
**Description of work.**

Added a NotificationService QtWidget, and set the messagedisplay in workbench to show a notification when it receives an error or higher.  This was asked for as just errors in the log can be hard to spot. 
Also added the ability to turn off notifications using the workbench properties or the properties file.

**Report to:** James Lord

**To test:**
**Important:** The implementation of notifications varies across different OS's, so this needs testing on:
- [x]  Mac
- [x] Windows
- [x] Linux

1. Start workbench (there are no notifications set in MPlot)
1. open File->Settings, check that notifications are on
image
1. run some things that will produce an error.  Incorrect python is the easiest to do.
```python
# The following line helps with future compatibility with Python 3
# print must now be used as a function, e.g print('Hello','World')
from __future__ import (absolute_import, division, print_function, unicode_literals)

# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *

import matplotlib.pyplot as plt

import numpy a
```
1. Repeat with notifications turned off
1. Check that the setting is preserved across workbench sessions.

Fixes #27305

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/widgets/common/inc/MantidQtWidgets/Common/NotificationService.h [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+//     & Institut Laue - Langevin
+// SPDX - License - Identifier: GPL - 3.0 +
+#ifndef MANTIDQTAPI_NOTIFICATIONSERVICE_H_
+#define MANTIDQTAPI_NOTIFICATIONSERVICE_H_
+
+#include "DllOption.h"
+#include <QObject>
+#include <QSystemTrayIcon>
+
+/** The ase class from which mantid custom widgets are derived it contains
```
Comment (ConorMFinn) [inline qt/widgets/common/inc/MantidQtWidgets/Common/NotificationService.h]:
```suggestion
/** The base class from which mantid custom widgets are derived contains
```

File: qt/widgets/common/src/NotificationService.cpp [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+  } catch (Mantid::Kernel::Exception::FileError) {
+    // The Config Service could not find the properties file
+    // Disable notifications
+    retVal = false;
+  } catch (Poco::ExistsException) {
+    // The Config Service could not find the properties file
+    // Disable notifications
+    retVal = false;
+  }
+  return retVal;
```
Comment (ConorMFinn) [inline qt/widgets/common/src/NotificationService.cpp]: Would it be better to return the values in the try/catch statements, rather than storing them in a variable?

File: qt/widgets/common/src/NotificationService.cpp [hunk 3]
```diff
@@ -0,0 +1,68 @@
...
+#include "MantidQtWidgets/Common/NotificationService.h"
+#include "MantidKernel/ConfigService.h"
+#include "MantidKernel/Exception.h"
+#include <QApplication>
+
+namespace MantidQt {
+namespace MantidWidgets {
+
+// Key for the "normalize data to bin width" plot option
+const std::string NotificationService::NOTIFICATIONSENABLEDKEY =
```
Comment (ConorMFinn) [inline qt/widgets/common/src/NotificationService.cpp]: Should this be in all caps snake case? 
```suggestion
const std::string NotificationService::NOTIFICATIONS_ENABLED_KEY =
```

**Review by cailafinn — CHANGES_REQUESTED** [review]
Just a few code comments. Functions well when tested on Ubuntu 18.04.

File: qt/widgets/common/src/NotificationService.cpp (hunk 2 above)
Comment (NickDraper) [reply qt/widgets/common/src/NotificationService.cpp]: Slightly personal preference here, I dislike having return statements all over the code generally as it can make it harder to read.  However I do accept that it doesn't make much difference in this example.

**Review by cailafinn — COMMENTED** [review]
Code looks good and still functions as expected. :+1:

Approved for Ubuntu 18.04

**Review by cailafinn — DISMISSED** [review]

**Comment by NickDraper** [comment]
Last change was just sorting out a merge conflict in the release notes

**Review by cailafinn — APPROVED** [review]
Re-Approved after merge conflict fixes for release notes. 

The Notification appears in `Microsoft.Explorer.Notification.{E8D48F0...`, in the Windows notifications panel, but does not affect primary functionality. 

(Ubuntu 18.04 & Windows 10)
