### PR TITLE
Catch error thrown when overlay peaks side-by-side view in instrument view

### LINKED ISSUE #34365: Instrument view crashes when overlaying peaks in Side by Side view
**Original reporter:**
Michael Ritchie (SXD student)

**Describe the bug**
Instrument view hard-crashes when overlaying peaks in side-by-side view (at least for SXD data).

**To Reproduce**
(1) Run this script to load a run (from system test data) and make peaks
```
Load(Filename=r'SXD23767.raw', OutputWorkspace='SXD23767')
CreatePeaksWorkspace(InstrumentWorkspace='SXD23767', NumberOfPeaks=0, OutputWorkspace='SingleCrystalPeakTable')
AddPeak(PeaksWorkspace='SingleCrystalPeakTable', RunWorkspace='SXD23767', TOF=3271, DetectorID=32615)
```
(2) Open `SXD23767` in instrument view (right-click on ws in ADS > Show INstrument)
(3) From the drop-down box at the top of the Render tab select `Side by Side`
(4) Drag the `SingleCrystalPeakTable` ws from ADS into the instrument view window

**Expected behavior**
It would be great to support peak overlay in Side by Side mode, from memory I don't think we have ever done this though. In which case I think we should disable the feature properly, or at least catch it and throw a warning.

**Platform/Version (please complete the following information):**
 - OS: Windows and IDAaaS
 - Mantid Version: Nightly 26-Aug, Manual testing release candidate

**Additional context**

### PR DESCRIPTION
**Pull request by RichardWaiteSTFC**
**Description of work.**
 Small fix to catch error thrown when overlay peaks side-by-side view in instrument view

To-Do
- Add test if possible

**To test:**
(1) Follow instructions on issue - it should now print an error to the log rather than crash

Fixes #34365 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/widgets/instrumentview/src/PeakOverlay.cpp [hunk 1]
```diff
@@ -245,9 +245,13 @@ void PeakOverlay::createMarkers(const PeakMarker2D::Style &style) {
       return;
     }
     // Project the peak (detector) position onto u,v coords
-    double u, v, uscale, vscale;
-    m_surface->project(pos, u, v, uscale, vscale);
-
+    try {
+      double u, v, uscale, vscale;
```
Comment (martyngigg) [inline qt/widgets/instrumentview/src/PeakOverlay.cpp:249]: It looks like the builds are failing because these variables are defined inside the `try{}` but they are needed in the call to construct the peak marker.

**Review by martyngigg — CHANGES_REQUESTED** [review]

File: qt/widgets/instrumentview/src/PeakOverlay.cpp (hunk 1 above)
Comment (RichardWaiteSTFC) [reply qt/widgets/instrumentview/src/PeakOverlay.cpp:249]: Ah yes sorry, I got a cpp warning when I had them above the try - so I'll just pop the marker stuff in the try as well!

**Review by martyngigg — APPROVED** [review]
Confirmed that this no longer causes a crash.
