### PR TITLE
Fixed number type problem with AddSampleLog algorithm

### LINKED ISSUE #14178: AddSampleLog algorithm causing type problems
For this algorithm, numbers must be passed as a string. Currently if "0" is passed it is stored as an _int_ and if "0.0" was passed it would be stored as a _double_. There are different methods for retrieving each of these types.

Doing something like:
```setProperty("LogText", boost::lexical_cast<std::string>(log_number))```
where ```log_number``` is a _double_, can therefore lead to non-obvious errors when ```log_number``` happens to be an integer valued _double_.

The suggestion is to add a property to force the "LogText" to be interpreted as a particular type.

### PR DESCRIPTION
**Pull request by matthew-d-jones**
Closes #14178 

The problem and solution are described in the issue.
Added property "NumberType" which may be "Double" or "Int". Covered new functionality with tests and updated the documentation for the algorithm.

**For Tester:**

You can test using the following python. For the first workspace the NumberType property is not used and LogText="12" is stored as an integer, "12" should be printed. For the second workspace the NumberType property is "Double" and LogText="12" is stored as a double, "12.0" should be printed.

``` python

sample_ws_1 = CreateSampleWorkspace()
AddSampleLog(Workspace=sample_ws_1, LogName="LogName", LogText="12", LogType="Number")
print sample_ws_1.getRun().getProperty("LogName").value

sample_ws_2 = CreateSampleWorkspace()
AddSampleLog(Workspace=sample_ws_2, LogName="LogName", LogText="12", LogType="Number", NumberType="Double")
print sample_ws_2.getRun().getProperty("LogName").value

```

### CODE REVIEW

File: Framework/Algorithms/src/AddSampleLog.cpp [hunk 1]
```diff
@@ -37,6 +37,15 @@ void AddSampleLog::init() {
                   boost::make_shared<StringListValidator>(propOptions),
                   "The type that the log data will be.");
   declareProperty("LogUnit", "", "The units of the log");
+
+  std::vector<std::string> typeOptions;
+  typeOptions.push_back("Int");
```
Comment (OwenArnold) [inline Framework/Algorithms/src/AddSampleLog.cpp]: Should have static const std::string for Int and Double. Can then use elsewhere in the code instead of writing "Int", "Double"

File: Framework/Algorithms/src/AddSampleLog.cpp [hunk 2]
```diff
@@ -37,6 +37,15 @@ void AddSampleLog::init() {
...
+  typeOptions.push_back("Double");
+  typeOptions.push_back("");
```
Comment (OwenArnold) [inline Framework/Algorithms/src/AddSampleLog.cpp]: Why have an empty entry?

File: Framework/Algorithms/src/AddSampleLog.cpp [hunk 3]
```diff
@@ -51,6 +60,13 @@ void AddSampleLog::exec() {
   std::string propValue = getProperty("LogText");
   std::string propUnit = getProperty("LogUnit");
   std::string propType = getPropertyValue("LogType");
+  std::string propNumberType = getPropertyValue("NumberType");
+
+  if (!propNumberType.empty() &&
```
Comment (OwenArnold) [inline Framework/Algorithms/src/AddSampleLog.cpp]: Might be better if that wen't into an information log instead. Maybe this is why you have the empty entry.
