### PR TITLE
Fix instrument widget pick tab tool selection after changing integration range

### LINKED ISSUE #30894: Instrument view: selected tool is reset after resizing TOF range
### Expected behavior
In the "pick" tab of the instrument view I expect my selected tool to persist after reszing the time-of-flight range.

### Actual behavior
After manipulating the time-of-flight range by dragging the range bar, the tool selection will reset itself without updating the button selection. See the image below, where the pixel selection tool button appears to be selected, but the tool description at the bottom of the window refers to the zoom tool.
image

### Steps to reproduce the behavior
- Load a workspace and open the instrument view.
- Open the pick tab; the pixel selection tool will be active.
- Move the cursor around the instrument to see pixel information.
- Modify the time-of-flight range by dragging either end of the bar at the bottom.
- The tool description at the bottom will change to the zoom tool's description, as will the behviour of the tool in the instrument display. However, the pixel select tool button is still highlighted.

### PR DESCRIPTION
**Pull request by joseph-torsney**
Fixes an issue where if the user changed the integration range whilst a tool is selected on the pick tab, the tool is reset to the tool that is selected on the mask (draw) tab. 

Now, when the `InstrumentWidgetMaskTab` recieves the signal that the integration range has changed, it checks whether it is the current selected tab before it updates the selected tool. This prevents it from 'overwriting' what tool is selected by the pick tab.

**To test:**
1. Open the instrument viewer and go to the pick tab.
2. Select any tool
3. Change the integration range using the slider at the bottom of the screen
4. Check that your tool is still selected, it behaves correctly on the 3d view, and the tooltip at the bottom of the page is correct.
5. Repeat on the Mask (draw) tab.

Fixes #30894 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/widgets/instrumentview/src/InstrumentWidgetMaskTab.cpp [hunk 1]
```diff
@@ -1338,7 +1338,10 @@ void InstrumentWidgetMaskTab::storeMask() {
 
 void InstrumentWidgetMaskTab::changedIntegrationRange(double /*unused*/,
                                                       double /*unused*/) {
-  enableApplyButtons();
+  InstrumentWidgetTab* baseTab = this;
+  if (m_instrWidget->isCurrentTab(baseTab)) {
```
Comment (thomashampson) [inline qt/widgets/instrumentview/src/InstrumentWidgetMaskTab.cpp:1342]: No need for the first line:
```suggestion
  if (m_instrWidget->isCurrentTab(this)) {
```

**Review by thomashampson — CHANGES_REQUESTED** [review]
Minor comment, otherwise this PR fixes the bug.

**Review by thomashampson — APPROVED** [review]
