### PR TITLE
Handle empty alarm log files

### LINKED ISSUE #31605: ICP_alarm files for INES prevent loading logs
### Expected behavior
Loading a raw file loads the logs successfully.
### Actual behavior
Loading INES raw data from a recent cycle gives the following error 
```
Unable to successfully run LoadLog Child Algorithm:
File/archive/NDXINES/Instrument/data/cycle_20_3/INS17770_ICPalarm.txt is not a standard ISIS log file.
Expected to be a file starting with DateTime String format.
```
### Steps to reproduce the behavior
- Run Load on /archive/NDXINES/Instrument/data/cycle_20_3/INS17770.raw
- Mantid also tries to pick up the ICPalarm.txt file and then cannot load the logs fully.
- In the case of run INS17770, the ICP_alarm file is empty
### Platforms affected
All

### PR DESCRIPTION
**Pull request by thomashampson**
**Description of work.**
Added check for empty ICPalarm log files when loading raw data files to prevent LoadLog throwing an exception when it attempts to process an empty log file. The user will no longer see a worrying warning message for a situation that is normal.

**To test:**
Do not test on Windows (see #31986 for reason).
- Change the log level to `information` by right clicking the messages widget
- Run Load on /archive/NDXINES/Instrument/data/cycle_20_3/INS17770.raw
- Verify that there are no warning messages
- Verify that the following information message is present:
`Skipping empty log file: /path/to/file/INS17770_ICPalarm.txt`

Fixes #31605

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Kernel/test/FileDescriptorTest.h [hunk 1]
```diff
@@ -130,6 +133,11 @@ class FileDescriptorTest : public CxxTest::TestSuite {
     TS_ASSERT_EQUALS(0, stream.tellg());
   }
 
+  void testEmptyFile() {
```
Comment (DavidFair) [inline Framework/Kernel/test/FileDescriptorTest.h:136]: Since were not using this for any other test can we move `m_emptyFilePath` into here as a local variable

Additionally, you can use [FileFinder](https://github.com/mantidproject/mantid/blob/3fe5e56b7c926586bcae8141a80a6175ca4c0a6c/Framework/API/test/FileFinderTest.h#L116) rather than building Poco Paths. It's less boilerplate and avoids bugs in test code around handling paths

**Review by DavidFair — CHANGES_REQUESTED** [review]
Some minor edge cases that can be improved

Otherwise looks good

**Comment by DavidFair** [comment]
Testing locally on Ubuntu this works correctly for me

File: Framework/DataHandling/src/LoadRawHelper.cpp [hunk 2]
```diff
@@ -683,18 +683,26 @@ void LoadRawHelper::runLoadLog(const std::string &fileName, const DataObjects::W
...
+    std::string statusSuffix = "ICPstatus.txt";
+    if (boost::algorithm::ends_with(*logPath, statusSuffix)) {
       g_log.information("Skipping log file: " + *logPath);
       continue;
     }
 
-    ignoreSuffix = "ICPdebug.txt";
-    if (boost::algorithm::ends_with(*logPath, ignoreSuffix)) {
+    std::string debugSuffix = "ICPdebug.txt";
+    if (boost::algorithm::ends_with(*logPath, debugSuffix)) {
```
[the remark this answers is not in the document]
Comment (thomashampson) [reply Framework/DataHandling/src/LoadRawHelper.cpp]: Changed to boost::algorithm::iends_with for case insensitive comparison.

File: Framework/Kernel/src/FileDescriptor.cpp [hunk 3]
```diff
@@ -104,6 +104,16 @@ bool FileDescriptor::isAscii(FILE *file, const size_t nbytes) {
...
 }
 
+/**
+ * Check whether a file is empty.
+ * @param filename
+ * @return true if the file is empty.
+ */
+bool FileDescriptor::isEmpty(const std::string &filename) {
+  std::ifstream file(filename.c_str());
+  return file.peek() == std::ifstream::traits_type::eof();
```
[the remark this answers is not in the document]
Comment (thomashampson) [reply Framework/Kernel/src/FileDescriptor.cpp:119]: I've added a throw, similar to other static methods in this class.

File: Framework/Kernel/test/FileDescriptorTest.h (hunk 1 above)
Comment (DavidFair) [reply Framework/Kernel/test/FileDescriptorTest.h:137]: On discussion it was pointed out this is in Kernel so we cannot use FileFinder from API

Comment (thomashampson) [reply Framework/Kernel/test/FileDescriptorTest.h:137]: MantidAPI isn't currently available in the KernelTest project and it might be overkill to add it just for this one usage.

**Review by DavidFair — APPROVED** [review]
This still works after the requested changes

Thanks for doing them, I'm happy to :shipit:
