### PR TITLE
Indirect Diffraction OSIRIS Diffspec - default value for spectra max 

### LINKED ISSUE #16333: Indirect Diffraction OSIRIS Diffspec - default spectra range and warning
**Feed back from Beta tester**

### Expected behavior
* The default spectra range should be from 3 - 15 as these are the default spectra for diffraction on OSIRIS. There should also be a warning to the user if you exceed this range
 
### Actual behavior
* Default range is min to max spectra (3 - 962). No warning is provided

### Steps to reproduce the behavior
* Look at the OSIRIS Diffraction interface in Diff spec mode

### Platforms affected
* All

### PR DESCRIPTION
**Pull request by ElliotAOram**
Indirect Diffraction OSIRIS Diffspec interface should now have a default value of 15 for specMax

**To test:**
- Change default facility/instrument to `ISIS/OSIRIS` (View > Preferences > Mantid)
- Open Indirect Diffraction (Interfaces > Indirect > Diffraction)
- Change instrument to `OSIRIS` (if not already set)
- Change Reflection to `diffspec` 
- Observe that the default `Spectra Max` is `15`

Fixes #16333

_Does not need to be in the release notes. As it is a minor update to the default value in an interface_

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: MantidQt/CustomInterfaces/src/Indirect/IndirectDiffractionReduction.cpp [hunk 1]
```diff
@@ -487,6 +487,10 @@ void IndirectDiffractionReduction::instrumentSelected(
   double specMin = instrument->getNumberParameter("spectra-min")[0];
   double specMax = instrument->getNumberParameter("spectra-max")[0];
 
+  if (instrumentName == "OSIRIS" && reflectionName == "diffspec") {
+	  specMax = 15;
```
Comment (LamarMoore) [inline MantidQt/CustomInterfaces/src/Indirect/IndirectDiffractionReduction.cpp]: Should this hard coded value be a const stored somewhere?

Comment (ElliotAOram) [inline MantidQt/CustomInterfaces/src/Indirect/IndirectDiffractionReduction.cpp]: Yes that's a good idea. I'll find a more sensible place to put it in the instrument parameter file

**Comment by SpencerHowells** [comment]
OSIRIS_diffraction_diffspec_parameters.xml is the obvious place.

**Comment by ElliotAOram** [comment]
@LamarMoore this should now ready to test now providing tests pass!

**Comment by LamarMoore** [comment]
Works as expected. I like the addition to the paramters xml file as opposed to a hard-coded value. :shipit:
