### PR TITLE
Fix bug with loading logs for raw files with alternate data stream

### LINKED ISSUE #31986: LoadRaw not processing .txt log files on Windows
### Expected behavior
On Windows, LoadRaw(Helper) should process all log files associated with a .raw file.

### Actual behavior
On Windows, the .txt log files are not being processed. The following warning message is displayed as a result:
`Cannot process ICPevent log. Period 1 assumed for all data.`

### Steps to reproduce the behavior
- Load a raw data file, e.g. \\isis\inst$\NDXINES\Instrument\data\cycle_20_3\INS17769.raw
- Observe warning message in the message log

### Platforms affected
Windows

### PR DESCRIPTION
**Pull request by thomashampson**
**Description of work.**

When loading a .raw file using Windows, the list of associated log files is taken from the alternative data stream if it exists (stored at "raw_file_name:checksum"). There was a bug which meant the list of files wasn't being correctly returned, so the .txt log files were not being loaded. This has been fixed.

**To test:**

**On Windows only**
- Change the log level to information in the messages widget.
- Load this file from the archive: `\\isis\inst$\NDXINES\Instrument\data\cycle_20_3\INS17770.raw`
- Verfiy that the warning message `Cannot process ICPevent log. Period 1 assumed for all data.` is NOT present.
- Confirm that the following messages ARE present:
`Skipping empty log file: \\isis\inst$\NDXINES\Instrument\data\cycle_20_3\INS17770_ICPalarm.txt`
and
`Skipping log file: \\isis\inst$\NDXINES\Instrument\data\cycle_20_3\INS17770_ICPdebug.txt`

Fixes #31986 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/DataHandling/src/LoadRawHelper.cpp [hunk 1]
```diff
@@ -79,7 +79,8 @@ std::set<std::string> logFilesFromAlternateDataStream(const Poco::Path &pathToRa
       const size_t asteriskPos = line.find('*');
       if (asteriskPos == std::string::npos)
         continue;
-      Poco::Path logFilePath(dirOfFile.append(line.substr(asteriskPos + 1)));
```
Comment (thomashampson) [inline Framework/DataHandling/src/LoadRawHelper.cpp:82]: This was the cause of the problem.

**Review by SilkeSchomann — APPROVED** [review]
Looks good
