### PR TITLE
Fix cppcheck warnings

### LINKED ISSUE #19773: Reduce cppcheck warning count
Work on reducing cppcheck warning count on master: http://builds.mantidproject.org/job/master_cppcheck/

Releated issues:
- [ ] #13950 ([FindPeaks.cpp](http://builds.mantidproject.org/job/master_cppcheck/966/cppcheckResult/source.16/#1076))
- [ ] #19952

### PR DESCRIPTION
**Pull request by gemmaguest**
This PR fixes the 32 cppcheck warnings currently being reported by [Jenkins](http://builds.mantidproject.org/job/master_cppcheck/).

**To test:**
Code review

Fixes #19773 .

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/ICat/src/CatalogDownloadDataFiles.cpp [hunk 1]
```diff
@@ -164,10 +164,8 @@ std::string CatalogDownloadDataFiles::doDownloadandSavetoLocalDrive(
         nullptr, certificateHandler, context);
 
     // Session takes ownership of socket
-    Poco::Net::SecureStreamSocket *socket =
-        new Poco::Net::SecureStreamSocket(context);
-    Poco::Net::HTTPSClientSession session(*socket);
-    socket = nullptr;
+    Poco::Net::SecureStreamSocket socket(context);
```
Comment (quantumsteve) [inline Framework/ICat/src/CatalogDownloadDataFiles.cpp]: Here be dragons. I think this was allocated on the heap to avoid an error, but when I looked into this a while ago never found where the socket was deleted. Also check that tests for this are enabled (they may have been disabled to avoid network communication in the unit tests).

Comment (gemmaguest) [inline Framework/ICat/src/CatalogDownloadDataFiles.cpp]: It doesn't look like the socket is being deleted, although I can't prove it without further investigation. I'll create a separate issue for this so it doesn't hold up this PR

Thanks for the tip on the tests - I hadn't noticed they were disabled. Unfortunately they crash when I enable them (not related to this change). I'll look into that as part of the separate issue.

**Comment by gemmaguest** [comment]
@peterfpeterson @quantumsteve This PR is ready for review. Could one of you take a look, or unassign yourselves if you don't have time?

**Review by peterfpeterson — APPROVED** [review]
Nothing looks too crazy.

File: MantidPlot/src/Folder.cpp [hunk 2]
```diff
@@ -54,8 +54,7 @@ QStringList Folder::subfolders() {
   QStringList list;
   QObjectList folderList = children();
   if (!folderList.isEmpty()) {
-    QObject *f;
-    foreach (f, folderList)
+    foreach (QObject *f, folderList)
```
Comment (quantumsteve) [inline MantidPlot/src/Folder.cpp]: FWIW, the `foreach` macro is deprecated. I added removing it to the list of maintenance tasks.
