### PR TITLE
Reflectometry interface (Polref): Fix to have 'Get Defaults' wrap polarization constant values in quote marks

### LINKED ISSUE #18208: Reflectometry interface (Polref): 'Get defaults' not wrapping double list parameters in quote marks
### Expected behavior
- Several parameters in the `Settings` tab are given as double lists - a string of comma-separated double values. If consisting of a single value, the quote marks are not necessary.
- When clicking either `Get Defaults` button in the `Settings` tab, it is expected that if it provides a set of values for a double list parameter, it wraps them in quote marks.

### Actual behavior
- It does not wrap the values in quote marks.
- This causes the reduction to fail and throw an error if attempted, unless quote marks are re-inserted.

### Steps to reproduce the behavior
- The Reflectometry interface can be accessed from Interfaces->Reflectometry->ISIS Reflectometry (Polref).
- On the `Runs` tab, set `Instrument` to POLREF.
- On the `Settings` tab, for the Experiment Settings section, click the `Get Defaults` button.
- Parameters `CRho`, `CAlpha`, `CAp`, `CPp` should be filled with multiple values. Notice that none of them are wrapped in quote marks. If a reduction is attempted without them, it will fail.

### PR DESCRIPTION
**Pull request by PranavBahuguna**
(This is essentially a merge conflict fix for PR https://github.com/mantidproject/mantid/pull/18211)

In the Settings tab, the polarization constants (CRho, CAlpha, CAp, CPp) are given as a string of comma-separated values. The original problem with the 'Get Defaults' button however was that it did not wrap these values with quote marks. Without re-inserting the quote marks, an attempt at data reduction would fail. This PR fixes this by adding the quote marks back in when 'Get Defaults' is clicked.

Edit: Quote marks are now added when the interface retrieves the values from the view, rather than added in the view itself.

To test:

- Access the Reflectometry interface from from Interfaces->Reflectometry->ISIS Reflectometry (Polref).
- On the Runs tab, set Instrument to POLREF.
- On the Settings tab, for the Experiment Settings section, click the Get Defaults button.
- Parameters CRho, CAlpha, CAp, CPp should be filled with multiple values. 
- Processing runs should not throw an error.

Fixes #18208.

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: MantidQt/CustomInterfaces/src/Reflectometry/ReflSettingsPresenter.cpp [hunk 1]
```diff
@@ -292,25 +300,35 @@ void ReflSettingsPresenter::getExpDefaults() {
...
+    defaults[4] = "\"" + cAp[0] + "\"";
 
   auto cPp = inst->getStringParameter("cPp");
   if (!cPp.empty())
-    defaults[5] = cPp[0];
+    defaults[5] = "\"" + cPp[0] + "\"";
 
   defaults[6] = alg->getPropertyValue("ScaleFactor");
 
   m_view->setExpDefaults(defaults);
```
Comment (gvardany) [inline MantidQt/CustomInterfaces/src/Reflectometry/ReflSettingsPresenter.cpp]: I think in `ReflSettingsPresenter::getExpDefaults()` you should not wrap the values in quotes, since it is not nice that they appear in the view. These properties are double array properties, to me it is not intuitive to see them wrapped. Wrapping should only happen behind the scenes, when setting the properties from the view to the algorithm (so in ` ReflSettingsPresenter::getReductionOptions()` as you did). For example, if one wants to set these settings manually (not getting the defaults), is he supposed to put them in quote marks?

**Review by gvardany — CHANGES_REQUESTED** [review]
I have a couple of remarks, see inline.

**Comment by PranavBahuguna** [comment]
I have added the new changes as requested. Please review them again.

**Review by gvardany — APPROVED** [review]

**Comment by gvardany** [comment]
Looks good :shipit:
