### PR TITLE
Fix bug with TableWorkspace plot type & sorting

### LINKED ISSUE #19518: Sorting a PeaksWorkspace column causes the column type to reset
If you set the type of a column then sort a column the type is reset. This is kind of annoying.

### Expected behavior
The type should remain unchanged

### Actual behavior
The type is reset to it's default

### Steps to reproduce the behavior
 - Right click on a column -> set type -> something other than the default
 - Right click on a column -> sort by -> ascending
 - Column type disappears.

### Platforms affected
All

### PR DESCRIPTION
**Pull request by samueljackson92**
This fixes a bug where if you set the plot type on a table workspace column via a table view, the workspace is not correctly updated with the plot type.

**To test:**
 - Follow the steps to reproduce the bug in the issue report #19518.
 - Apply the fix, check this is now solved.
 - Code review.

Fixes #19518

**Release Notes** 
[See here](https://github.com/mantidproject/mantid/compare/19518-sort-peaks-ws-column?expand=1#diff-314160101dcfa40a50e85e320e4e750fR54)

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: MantidPlot/src/Mantid/MantidTable.cpp [hunk 1]
```diff
@@ -423,6 +429,19 @@ void MantidTable::sortColumns(const QStringList &s, int type, int order,
   }
 }
 
+/** Set the plot type on the workspace for each selected column
+ *
+ * @param plotType :: the plot type to set the selected columns to.
+ */
+void MantidTable::setPlotTypeForSelectedColumns(int plotType) {
+  const QStringList list = selectedColumns();
+  for (int i = 0; i < static_cast<int>(list.count()); i++) {
```
Comment (edwardb96) [inline MantidPlot/src/Mantid/MantidTable.cpp]: I think this can be converted to a range-based for loop?

**Review by edwardb96 — CHANGES_REQUESTED** [review]
This fix works fine on my PC (Fedora/Linux). 👍 
It's probably worth changing the for loop over though.

File: MantidPlot/src/Mantid/MantidTable.cpp (hunk 1 above)
Comment (samueljackson92) [reply MantidPlot/src/Mantid/MantidTable.cpp]: Yes. You're right. 👍

**Review by edwardb96 — APPROVED** [review]
