### PR TITLE
Fix two issues with absolute rotations in RotateInstrumentComponent (via ComponentHelper::rotateComponent)

### LINKED ISSUE #18750: ComponentHelper: Rotating wrong if any parent component apart from immidiate parent is rotated
This should be the absolute rotation, not the relative rotation: https://github.com/mantidproject/mantid/blob/master/Framework/Geometry/src/Instrument/ComponentHelper.cpp#L81

Example:
```cpp
Load(Filename='MAR11015.raw', OutputWorkspace='MAR11015')
RotateInstrumentComponent(Workspace='MAR11015', ComponentName='wide angle bank', Z=1, Angle=-10, RelativeRotation=False)
RotateInstrumentComponent(Workspace='MAR11015', ComponentName='W1-1', Z=1, Angle=60, RelativeRotation=False)
RotateInstrumentComponent(Workspace='MAR11015', DetectorID=1101, Z=1, Angle=90, RelativeRotation=False)
```

The result is that detector 1101 is rotated to `-10` degree, instead of 90.

Note that the first two rotate calls are just for setting up a "bad" situtation: If those components have any previously set relative rotations (e.g., from the IDF) this will show the bug as well.

### LINKED ISSUE #18811: ComponentHelper: Absolute rotations wrong if any of the parents is rotated.
This should be the absolute rotation, not the relative rotation: https://github.com/mantidproject/mantid/blob/master/Framework/Geometry/src/Instrument/ComponentHelper.cpp#L83

Example:
```cpp
LoadEmptyInstrument(InstrumentName='MAR', OutputWorkspace='ws')
RotateInstrumentComponent(Workspace='ws', ComponentName='wide angle bank', Y=1, Angle=90)
RotateInstrumentComponent(Workspace='ws', ComponentName='W1-1', Z=1, Angle=90, RelativeRotation=False)
```

The result is `W1-1` at a weird location instead of being simple rotated around Z.

Note that the first rotate call is just for setting up a "bad" situtation: If those components have any previously set relative rotations (e.g., from the IDF) this will show the bug as well.

### PR DESCRIPTION
**Pull request by SimonHeybrock**
See issues.

**To test:**

Code review, and check if the following gives the expected result (in comparison to the old rotation computation, which did not):

For testing the first issue:

```python
LoadEmptyInstrument(InstrumentName='MAR', OutputWorkspace='ws')
RotateInstrumentComponent(Workspace='ws', ComponentName='wide angle bank', Z=1, Angle=-20, RelativeRotation=False)
RotateInstrumentComponent(Workspace='ws', ComponentName='W1-1', Z=1, Angle=60, RelativeRotation=False)
RotateInstrumentComponent(Workspace='ws', DetectorID=1101, Z=1, Angle=90, RelativeRotation=False)
```

For testing the second issue (need non-planar rotations, the second issue is not visible in the previous example):

```python
LoadEmptyInstrument(InstrumentName='MAR', OutputWorkspace='ws')
RotateInstrumentComponent(Workspace='ws', ComponentName='wide angle bank', Y=1, Angle=90)
RotateInstrumentComponent(Workspace='ws', ComponentName='W1-1', Z=1, Angle=90, RelativeRotation=False)
```

Fixes #18750.
Fixes #18811.

Release notes have been updated. This change affects the behavior of `RotateInstrumentComponent` when absolute rotations are enabled.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by SimonHeybrock** [comment]
@OwenArnold I decided to also fix the second rotation issue in this branch, see updated issue description for testing instructions.

**Comment by SimonHeybrock** [comment]
@OwenArnold I think the reason is probably that most instruments are fixed: They are just loaded from IDF or Nexus files, and in that case parameters are inserted directly into the `ParameterMap`, so those will never exercise this code path.

**Comment by OwenArnold** [comment]
We have two manual tests here that should be quite easy to create as unit tests in `ComponentHelper` via a Mocked or Faked `Component`/`CompAssembly`. I'd like to see that this gets enshrined as the normal behaviour now. Do you think you could write the tests?

**Comment by SimonHeybrock** [comment]
@OwenArnold Added new tests. Running the new tests locally on master fails.

File: Framework/Geometry/test/ComponentHelperTest.h [hunk 1]
```diff
@@ -107,6 +110,59 @@ class ComponentHelperTest : public CxxTest::TestSuite {
...
+    TS_ASSERT_EQUALS(pixel->getRotation(), rootRot);
+    ComponentHelper::rotateComponent(*bank, *pmap, bankRot, type);
+    TS_ASSERT_EQUALS(instrument.getRotation(), rootRot);
+    TS_ASSERT_EQUALS(bank->getRotation(), bankRot);
+    TS_ASSERT_EQUALS(pixel->getRotation(), bankRot);
+    ComponentHelper::rotateComponent(*pixel, *pmap, pixelRot, type);
+    TS_ASSERT_EQUALS(instrument.getRotation(), rootRot);
+    TS_ASSERT_EQUALS(bank->getRotation(), bankRot);
+    TS_ASSERT_EQUALS(pixel->getRotation(), pixelRot);
+  }
```
Comment (OwenArnold) [inline Framework/Geometry/test/ComponentHelperTest.h]: This testing should be sufficient.

File: Framework/Geometry/test/ComponentHelperTest.h [hunk 2]
```diff
@@ -107,6 +110,59 @@ class ComponentHelperTest : public CxxTest::TestSuite {
...
+    const int pixels = 1;
+    auto base =
+        ComponentCreationHelper::createTestInstrumentRectangular(banks, pixels);
+    auto pmap = boost::make_shared<ParameterMap>();
+    Instrument instrument(base, pmap);
+
+    const auto bank = instrument.getComponentByName("bank1");
+    const auto pixel = instrument.getDetector(1);
+
+    Quat rootRot(100.0, V3D(1, 2, 3));
```
Comment (OwenArnold) [inline Framework/Geometry/test/ComponentHelperTest.h]: `Quat` has quite a few constructors. A minor improvement might be to comment or provide named variables so that it's clear the construction arguments are in this case rotation angle and axis.

**Comment by OwenArnold** [comment]
This is definitely the right direction with the fix. One oddity I don't understand is that the rotation of the detector does not come out as exactly 90 degrees around `z` in the example provided.

```
LoadEmptyInstrument(InstrumentName='MAR', OutputWorkspace='ws')
# workspace index 3 is detector id 1101
print(mtd['ws'].getDetector(3).getRotation())
RotateInstrumentComponent(Workspace='ws', ComponentName='wide angle bank', Z=1, Angle=-20, RelativeRotation=False)
RotateInstrumentComponent(Workspace='ws', ComponentName='W1-1', Z=1, Angle=60, RelativeRotation=False)
RotateInstrumentComponent(Workspace='ws', DetectorID=1101, Z=1, Angle=90, RelativeRotation=False)
print(mtd['ws'].getDetector(3).getRotation())
```

or to simplify:
```
LoadEmptyInstrument(InstrumentName='MAR', OutputWorkspace='ws')
# workspace index 3 is detector id 1101
print(mtd['ws'].getDetector(3).getRotation())
RotateInstrumentComponent(Workspace='ws', DetectorID=1101, Z=1, Angle=90, RelativeRotation=False)
print(mtd['ws'].getDetector(3).getRotation())
```
This isn't the PI/2 rotation I would expect to see. Maybe this is a misunderstanding on my part? But I would expect this should rotate around the detector centre by 90 degrees.

Other comments are that the InstrumentView can be made to crash, and it doesn't seem to properly display the rotations, but these are separate issues I will write.

**Comment by SimonHeybrock** [comment]
@OwenArnold What are you getting? Looks like a correct rotation to me, but I may be wrong. After setting it to 90 degree around Z the quaternion is `[0.707107,0,0,0.707107]`.

**Comment by OwenArnold** [comment]
@SimonHeybrock Yes that's 81.02 degree rotation I think.

**Comment by SimonHeybrock** [comment]
@OwenArnold This is printing the parameters of the quaternion. The first one is `cos(theta/2)`.

**Comment by OwenArnold** [comment]
@SimonHeybrock Ok. This makes sense. I misread that as being Euler angles.

**Comment by OwenArnold** [comment]
My conclusion from some testing directly in Eigen is that you're changes here are correct. https://github.com/DMSC-Instrument-Data/instrument-prototype/pull/45/files However, I'd still like to find out why I get some bizarre rotations reported for Mari. This could well be down to the the IDF parsing. I've already spotted some unpleasant implementation in `InstrumentDefinitionParser::setLocation`, but I'd like to investigate this further.

**Comment by OwenArnold** [comment]
I found out what was going wrong with those Euler angles. Looking at the code, there's some kind of bizarre default convention. Here's an example I coded.

```python
from mantid.kernel import Quat
import math
theta = math.pi/2
quat = Quat(math.cos(theta/2), 0, 0, math.sin(theta/2))
print(quat.getEulerAngles())
print(quat.getEulerAngles(convention="XYZ"))
```
Gives
```
[0,90,-0]
[0,0,90]
```
The rotation (quaternion) itself looks OK.

**Comment by OwenArnold** [comment]
:shipit:
