### PR TITLE
Indirect Bayes ResNorm -  Fix crash when using workspace as input

### LINKED ISSUE #16621: Indirect Bayes ResNorm - Running with complex workspace names
### Expected behavior
* Any two valid workspaces should be able to be run in the interface

### Actual behavior
* `osiris120661_multi_graphite002_red` and `osiris120661_graphite002_multi_res` as **Workspace** inputs produces the error 

image

### Steps to reproduce the behavior
* Load in the data mentioned above
* Select these as workspace inputs for the interface
* Click `Run`

### Platforms affected
* Found on Mac (will affect all)

### PR DESCRIPTION
**Pull request by ElliotAOram**
ResNorm should no longer crash when using workspaces (rather than files) as input.

**To test:**
- Load the `irs26173_graphite002_red.nxs` and `irs261763_graphite002_res.nxs` workspaces 
- Open ResNorm (Interfaces > Indirect > Bayes > Resnorm)
- Select the workspace option for the Vanadium and Resolution inputs
  - These should default to `_red` workspace for vanadium and `_res` workspace for Resolution (this is correct)
- Click `Run` 
- Ensure the algorithm runs without error and the mini plot is updated with the red `Fit` curve

Fixes #16621 

[RELEASE NOTES](https://github.com/mantidproject/mantid/blob/66c54c53372dacc7e049b10340d8ed54549f82d5/docs/source/release/v3.8.0/indirect_inelastic.rst#bugfixes)

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: MantidQt/CustomInterfaces/src/Indirect/ResNorm.cpp [hunk 1]
```diff
@@ -173,8 +173,11 @@ void ResNorm::handleAlgorithmComplete(bool error) {
   if (plotOptions == "Fit" || plotOptions == "All")
     plotSpectrum(fitWsName, 0, 1);
 
-  loadFile(m_uiForm.dsResolution->getFullFilePath(),
-           m_uiForm.dsResolution->getCurrentDataName());
+  if (!AnalysisDataService::Instance().doesExist(
+          m_uiForm.dsResolution->getCurrentDataName().toStdString())) {
```
Comment (MattKing06) [inline MantidQt/CustomInterfaces/src/Indirect/ResNorm.cpp]: you can use `resWsName.toStdString()` here. Also, do we know why we are only checking if the Res workspace is present in the ADS? and if yes, should we be checking if the Vanadium workspace is also available?

**Comment by MattKing06** [comment]
Tested on win7 and everything is still fine after the recent changes so I say we can :shipit: now

**Comment by FedeMPouzols** [comment]
@MattKing06: remember to tick the boxes in the PR description. This one is small and it is obvious what was done and tested, but in general it helps the tester to not forget any important step.
