### PR TITLE
Fixed bug in Refl GUI that allowed table workspaces to be available for saving

### LINKED ISSUE #19692: Refl GUI: Saving table workspace crashes interface
### Expected behavior

I do not believe one should be able to select table workspaces in the first place as they cannot be saved to ascii.

### Actual behavior

Table workspaces are available to save, and doing so will crash Mantid.

### Steps to reproduce the behavior

- Open the `Reflectometry` interface and import `INTER_NR_test2.tbl`, giving the output table workspace some name.
- Navigate to the `Save ASCII` tab and refresh `List of Workspaces`. The table workspace name should appear there.
- Select this name and press the `Save` button - this causes Mantid to crash.

### Platforms affected

Windows, Linux, likely all.

### PR DESCRIPTION
**Pull request by PranavBahuguna**
Description of work.

In the `Save ASCII` tab of the Reflectometry interface, the `List of Workspaces` list shows all the workspaces that can are available for saving in ASCII format. This however mistakenly included table workspaces which could not be saved to ASCII format. Attempting to select one and save it resulted in Mantid crashing. This PR fixes this issue by preventing table workspaces from appearing in the list.

**To test:**

- Code review.
- Open the `Reflectometry` interface and import `INTER_NR_test2.tbl`, giving the output table workspace some name.
- Navigate to the `Save ASCII` tab and refresh `List of Workspaces`. The table workspace name should no longer appear there.

Fixes #19692.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: MantidQt/CustomInterfaces/inc/MantidQtCustomInterfaces/Reflectometry/ReflSaveTabPresenter.h [hunk 1]
```diff
@@ -64,6 +64,9 @@ class MANTIDQT_CUSTOMINTERFACES_DLL ReflSaveTabPresenter
   /// Obtains all available workspace names
   std::vector<std::string> getAvailableWorkspaceNames();
 
+  /// Predicate to checks if a workspace is of a group or table workspace type
+  struct isGroupOrTable;
```
Comment (DTasev) [inline MantidQt/CustomInterfaces/inc/MantidQtCustomInterfaces/Reflectometry/ReflSaveTabPresenter.h]: Consider using the check in `operator()` as a lambda:
```
      [](const std::string &wsName) {
        // Predicate to checks if a workspace is either of group or table types
        // or not
        return AnalysisDataService::Instance().retrieveWS<WorkspaceGroup>(
                   wsName) ||
               AnalysisDataService::Instance().retrieveWS<ITableWorkspace>(
                   wsName);
      }
```

it will save a struct declaration, and the `isGroupOrTable` isn't used anywhere else

**Review by dtasev — APPROVED** [review]

**Comment by DTasev** [comment]
looks good, table workspaces are not shown and saving doesn't crash anymore. :shipit:
