### PR TITLE
Prevent crash when fixing fit parameter

### LINKED ISSUE #34982: Crash when fixing fit parameter
**Describe the bug**
Mantid will crash when you attempt to fix a fit parameter in the fit browser.

**To Reproduce**
1. Open a 1D plot
2. Open the fit panel
3. Add a peak
4. Expand the function, right click one of the parameters and click "Fix"

**Expected behavior**
Parameter should be fixed at current value without causing any problems.

**Platform/Version (please complete the following information):**
 - OS: all
 - Mantid Version 6.5.20230115.2237

**Additional context**
No stack trace, but the following output was taken from a crash on macOS:
```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000048
Exception Codes:       0x0000000000000001, 0x0000000000000048
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [38588]

VM Region Info: 0x48 is not in any region.  Bytes before following region: 140737488084920
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      VM_ALLOCATE              7ffffffbe000-7ffffffbf000 [    4K] r-x/r-x SM=ALI  

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libMantidAPI.dylib            	       0x1078bcbf4 Mantid::API::ParameterTie::asString(Mantid::API::IFunction const*) const + 52
1   libMantidQtWidgetsCommonQt5.dylib	       0x15de8687c MantidQt::MantidWidgets::FitPropertyBrowser::stringChanged(QtProperty*) + 1180
2   libQt5Core.5.15.6.dylib       	       0x10fd33ce4 0x10fbe8000 + 1359076

```

### PR DESCRIPTION
**Pull request by DanielMurphy22**
I have added a new separate function getOldExpressionAsString() which returns a previously set tie value and this new function enabled testing.
If there is an oldTie for the parameter, which was a tie to function (e.g. f0.Height=f1.Height) then the oldTieExpression is returned. This allows an edited Tie to function text box to revert upon an invalid entry see pr #34817 Note this function does not get an oldTie if it was custom (e.g. f0.Height=2.0) This new function also allows fixing a parameter, when oldTie is nullptr.

**Description of work.**

Prevent crash on fixing a fit parameter. The whole point of looking for the oldTieExpression is, only in the case of a tie to a function, a new invalid entry to the textbox for the Tie will be reverted to the old function.

**To test:**

- [ ] Check no crash when fixing a parameter
  - Open Workbench and run CreateSampleWorkspace()
  - Double Click on the produced workspace and plot the first spectrum
  - Click the Fit toolbar button to activate the FitPropertyBrowser
  - Right-click on the plot and Add a Peak
  - Click the triangle by the newly added peak function to get the parameter dropdownlist.
  - Right-click on a parameter, such as Height, and select "Fix".
  - A fix should be applied with no crash!
  - Run Fit>Fit, a success or failed fit is fine. 
- [ ] Run through these instructions I copied over from on this PR: https://github.com/mantidproject/mantid/pull/34817
  - Load some data
  - Plot a spectrum
  - Click 'Fit' to open the fitting widget
  - Right click and add a peak, then a second
  - Right click f0.Height -> Tie -> To function -> f1.Height
  - Click on the tie box and change it from f1.Height to something invalid (e.g hello)
  - Check that an error box was shown
  - Click okay on the error box and check the tie value has reverted to f1.Height
  - Click on the tie box and change the value to f1.Sigma to test it will update correctly
  - Note that if you run these instructions but set your "invalid entry" as a number (e.g. `6`) then you have reproduced a different issue: https://github.com/mantidproject/mantid/issues/34980
- [ ] Code review

Fixes #34982

*This does not require release notes* because **fix bug introduced in this release cycle**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/widgets/common/inc/MantidQtWidgets/Common/FitPropertyBrowser.h [hunk 1]
```diff
@@ -443,6 +443,11 @@ private slots:
   /// Clear the Fit status display
   void clearFitResultStatus();
 
+public: // functions declared public for testing
+  QString getOldExpressionAsString(QString &parameterName) const;
```
Comment (DannyHindson) [inline qt/widgets/common/inc/MantidQtWidgets/Common/FitPropertyBrowser.h:447]: I think the parameter can be const as well here and in the .cpp file ie `const QString &parameterName`

File: qt/widgets/common/test/FitPropertyBrowserTest.h [hunk 2]
```diff
@@ -53,4 +62,39 @@ class FitPropertyBrowserTest : public CxxTest::TestSuite {
     // Make sure the FunctionFactory does not have a dead link as an observer
     TS_ASSERT_THROWS_NOTHING(FunctionFactory::Instance().unsubscribe("FitPropertyBrowserTest_Funct");)
   }
+
+  void test_getOldExpressionAsString_returns_empty_string_when_tie_is_null() {
+    // initialise it fitPropertyBrowser- this adds an observer on the function factory update message
```
Comment (DannyHindson) [inline qt/widgets/common/test/FitPropertyBrowserTest.h:67]: I think you can remove the extra "it" from the comment here? And same on next test

**Review by DannyHindson — CHANGES_REQUESTED** [review]
Tests worked fine and crash no longer present. Just a couple of minor code review things

**Comment by DannyHindson** [comment]
Just noticed one of the Jenkins jobs failed with a warning. The message isn't totally clear think it wants you to catch the exception in getOldExpressionAsString by reference rather than by value:
`} catch (std::exception &) {`

**Review by DannyHindson — APPROVED** [review]
Looks good thanks!
