### PR TITLE
SortXAxis allow a skip of the histogram validity check

### LINKED ISSUE #25242: Indirect - TOSCA Old Run numbers not Reducing
### Actual behavior
There is an error in the results log on Data Reduction when trying to reduce old run numbers.

"The date range applicable are mentioned in the Instrument definition file header. Such as TOSCA_DefinitionDAE1.xml should be used for files date range 31-03-2000 to 10-08-2006. Time range will also be available there. 
We have to read the time stamp of the sample file and compare with the stored date and time range of those instrument files to determine the matching instrument files. " - Scientist

See line 194 of IndirectDataReduction.cpp

### Steps to reproduce the behavior
1.`Interfaces`->`Indirect`->`Data Reduction`->`ISISEnergyTransfer`
2. Instrument is `TOSCA`
3. Enter the run number `4970`
4. Click `Run`
5. Error in results log!

This might be because the older run numbers are using the wrong Instrument Definition file (i.e. not the IDF for the correct time period for TOSCA).

### Platforms affected
All

### PR DESCRIPTION
**Pull request by Pasarus**
**Description of work.**
At the ISIS facility there is some legacy data that has spectra missing a detector. This means when convert units runs it doesn't reverse the XAxis order like all of the other spectra. This means SortXAxis would not "Sort" it. Therefore in an Indirect workflow it breaks on some older TOSCA data. This is a semi-temporary fix for that data/workflow.

**Report to:** Sanghamitra. 

**To test:**
- Open MantidPlot
- Open Interfaces->Indirect->Data Reduction
- Switch to the TOSCA instrument
- Enter the run number 4790
- Then click run
- It should run successfully.

Fixes #25242. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Algorithms/src/SortXAxis.cpp [hunk 1]
```diff
@@ -51,15 +51,24 @@ void SortXAxis::init() {
...
+  declareProperty("IgnoreHistogramValidation", false,
+                  "This will stop SortXAxis from throwing if the workspace is "
+                  "not a valid histogram for this algorithm to work on.");
 }
 
 void SortXAxis::exec() {
 
   MatrixWorkspace_const_sptr inputWorkspace = getProperty("InputWorkspace");
   MatrixWorkspace_sptr outputWorkspace = inputWorkspace->clone();
+  bool ignoreHistogramValidation = getProperty("IgnoreHistogramValidation");
```
Comment (SamJenkins1) [inline Framework/Algorithms/src/SortXAxis.cpp]:
```suggestion
  const bool ignoreHistogramValidation = getProperty("IgnoreHistogramValidation");
```

**Review by LowriJenkins — CHANGES_REQUESTED** [review]
one small change, otherwise looks fine

**Review by LowriJenkins — DISMISSED** [review]

**Review by LowriJenkins — DISMISSED** [review]

**Comment by soininen** [comment]
I do not understand the issue here. `SortXAxis::determineIfHistogramIsValid` correctly rejects histogram data if the binning does not make sense at all. How do missing detectors enter the picture?

File: Framework/Algorithms/src/SortXAxis.cpp [hunk 2]
```diff
@@ -51,15 +51,25 @@ void SortXAxis::init() {
       boost::make_shared<StringListValidator>(orderingValues);
   declareProperty("Ordering", orderingValues[0], orderingValidator,
                   "Ascending or descending sorting", Direction::Input);
+  declareProperty("IgnoreHistogramValidation", false,
+                  "This will stop SortXAxis from throwing if the workspace is "
+                  "not a valid histogram for this algorithm to work on.");
```
Comment (reimundILL) [inline Framework/Algorithms/src/SortXAxis.cpp]: Does not the option `Ordering` help you in this case?

- the method *determineIfHistogramIsValid* seems to be wrong to me: histograms are sorted already but can be sorted reversely and point data can be unsorted -> in my opinion this can be deleted?

Explanation of valid/invalid histogram missing.

`SortXAxis` should be able generally to handle these cases and a new input option seems to be redundant.

**Comment by reimundILL** [comment]
But maybe adding a new algorithm input is hard to get rid of in the (breaking API) future and deleting the validator is simpler.

**Comment by soininen** [comment]
Then the new property doc string should clearly state that it is a temporary fix and will be removed in a later release. It might be a good idea to open an issue (setting the milestone to 4.1) reminding that this issues needs a proper fix as well.

**Review by martyngigg — CHANGES_REQUESTED** [review]
Marking as changes requested to await property documentation update as suggested by Antti.

**Review by martyngigg — DISMISSED** [review]

**Comment by martyngigg** [comment]
@Pasarus Can you add a comment with the issue number for the "proper" fix for this so we can track it?

**Comment by martyngigg** [comment]
@SamJenkins1 I think there are a couple of issues:
# new algorithm able to remove spectra from a workspace
# use the new algorithm in the indirect workflow and remove the hack with this property.

**Comment by martyngigg** [comment]
Thanks, @SamJenkins1.

**Comment by martyngigg** [comment]
`macOS` failure is unrelated.

File: Framework/Algorithms/src/SortXAxis.cpp [hunk 3]
```diff
@@ -51,15 +51,28 @@ void SortXAxis::init() {
...
 void SortXAxis::exec() {
 
   MatrixWorkspace_const_sptr inputWorkspace = getProperty("InputWorkspace");
   MatrixWorkspace_sptr outputWorkspace = inputWorkspace->clone();
+  const bool ignoreHistogramValidation =
+      getProperty("IgnoreHistogramValidation");
 
   // Check if it is a valid histogram here
-  bool isAProperHistogram = determineIfHistogramIsValid(*inputWorkspace);
+  bool isAProperHistogram;
```
Comment (DanNixon) [inline Framework/Algorithms/src/SortXAxis.cpp]: Can we use a `const` ternary operator here?

**Review by DanNixon — CHANGES_REQUESTED** [review]
Small style comment.

File: Framework/Algorithms/src/SortXAxis.cpp (hunk 3 above)
Comment (SamJenkins1) [reply Framework/Algorithms/src/SortXAxis.cpp]: I've updated this for sam since he's currently busy with something else.

**Review by martyngigg — APPROVED** [review]

**Comment by robertapplin** [comment]
@Pasarus When I follow the test instructions I get a vector subscript out of range error 
image. Tested on windows
