### PR TITLE
Change Mask Energies Label Indirect

### LINKED ISSUE #25214: Indirect Fitting Change Mask Energies Label
### Description
The `Mask Energies` label in the Multiple Input table in MSDFit, IqtFit, ConvFit and FQFit should be changed to `Mask X Range`. This is because the X axis is not necessary energy.

The similar notation under the miniplots should also be changed to `Mask X Range`.

Make sure you also change any references in the documentation.

### Steps to reproduce the behavior
1.`Interfaces`->`Indirect`->`Data Analysis`->MSDFit, IqtFit, ConvFit and FQFit

### Platforms affected
All

### PR DESCRIPTION
**Pull request by TTitcombe**
**Description of work.**
This PR changes the name of a column in some indirect tabs to more accurately describe the nature of the x data (previously it was "Mask Energies", but the x data is not necessarily energy)

**To test:**
1. Interfaces -> Indirect -> Data Analysis
2. The Multiple input table in the MSDFit and IqtFit tabs should have a column "Mask X Range"
3. The multiple input table in the ConvFit and FQFit tabs should have a column "Mask Q Range"

Fixes #25214 

*This does not require release notes* because **fill in an explanation of why**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/scientific_interfaces/Indirect/ConvFitDataTablePresenter.cpp [hunk 1]
```diff
@@ -17,7 +17,7 @@ QStringList convFitHeaders() {
           << "WS Index"
           << "StartX"
           << "EndX"
-          << "Mask Energies";
+          << "Mask Q Range";
```
Comment (robertapplin) [inline qt/scientific_interfaces/Indirect/ConvFitDataTablePresenter.cpp]: My apologies I think my explanations have been unclear. Would it be better for this to be `Mask X Range` too (and for JumpFit) so that it is consistent with the `Mask X Range Of Spectrum` under the mini plots?

Comment (TTitcombe) [reply qt/scientific_interfaces/Indirect/ConvFitDataTablePresenter.cpp]: I think keeping all of them the same makes sense

**Review by robertapplin — APPROVED** [review]
The changes are good and describes the purpose of Masking in a clearer and more consistent way.
