### PR TITLE
Indirect Iqt Bug with Monte Carlo Error calculation

### LINKED ISSUE #25806: Indirect Iqt - The Monte Carlo errors seen towards the end of the spectra are too small
### Expected behavior
When calculating errors on Iqt, the monte carlo errors calculated towards the end of the spectra are expected to be larger than they  currently are. I believe small errors are being caused by the incorrect calculation of simulation workspaces.

### Actual behavior
Currently, the errors towards the noisy end of the spectra are too small and are expected to be smaller.

### Steps to reproduce the behavior
1. `Interfaces`->`Indirect`->`Data Analysis`->`Iqt` tab
2. Tick `Calculate errors`

### Platforms affected
All

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR fixes a bug causing the Monte Carlo errors calculated on Iqt to be false. The problem was caused by identical simulated workspaces!
 Make sure that `Plot error bars on output plots` is turned on in the Indirect Settings GUI (accessible from the bottom left of any indirect interface).

**To test:**
1. `Interfaces`->`Indirect`->`Data Analysis`->`Iqt` tab
2. Load the data below
3. Click `Run`
4. Click `Plot Spectrum` in the output options. The external plot should look like the following graph where you can see the errors are getting bigger towards the end of the spectra:
image

**Data Files**
[irs26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/3315171/irs26176_graphite002_red.zip)
[irs26173_graphite002_res.zip](https://github.com/mantidproject/mantid/files/3315172/irs26173_graphite002_res.zip)

Fixes #25806 and #25819 

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/scientific_interfaces/Indirect/IndirectInterface.cpp [hunk 1]
```diff
@@ -50,9 +50,13 @@ IndirectInterface::getInterfaceSettings() const {
...
-  ManageUserDirectories *ad = new ManageUserDirectories(this);
-  ad->show();
-  ad->setFocus();
+  if (!m_manageUserDirectories) {
+    m_manageUserDirectories = std::make_unique<ManageUserDirectories>(this);
+    m_manageUserDirectories->setAttribute(Qt::WA_DeleteOnClose, false);
+  }
+  m_manageUserDirectories->show();
+  m_manageUserDirectories->setFocus();
+  m_manageUserDirectories->setModal(true);
```
Comment (hsautessella) [inline qt/scientific_interfaces/Indirect/IndirectInterface.cpp]: This doesn't actually make the window modal the first time it's opened, only after closing it and re-opening will it be modal. This can be fixed by calling `setModal` *before* calling `show`. This also means there's no need to call `setFocus` since a modal window will automatically take focus from its parents.

**Review by ghost — COMMENTED** [review]
This looks good and the plot comes out as described. Just one very minor comment

**Review by ghost — APPROVED** [review]
