### PR TITLE
ReflectometryReductionOneAuto has issues with multi-period transmission workspaces

### LINKED ISSUE #14488: Polarization Correction producing the wrong results
This issue follows on from: #14139

The polarization correction algorithm is not producing the right results, some detective work needs to be done to find the source of the problem.

### PR DESCRIPTION
**Pull request by MattKing06**
It doesn't make sense for the transmission workspaces in ReflectometryReductionAutoOne to be multi-period. Now, when processing the group workspaces, ReflectometryReductionAutoOne will sum over the transmission workspaces in the group and use the sum as the transmission workspace.

A change has also been made so that the `CorrectionAlgorithm` is set to `None` when re-running the ReflectometryReduction again after PolarizationCorrection has been performed.

**To Test:**
**Release Notes:**: //todo
Fixes #14488

### CODE REVIEW

**Comment by OwenArnold** [comment]
The updated algorithm needs testing. I suggest building a system test around Jos example.

File: Framework/Algorithms/src/ReflectometryReductionOneAuto.cpp [hunk 1]
```diff
@@ -592,8 +594,20 @@ bool ReflectometryReductionOneAuto::processGroups() {
     alg->setProperty("OutputWorkspaceWavelength", IvsLamName);
 
     // Handle transmission runs
-    if (firstTransG)
-      alg->setProperty("FirstTransmissionRun", firstTransG->getItem(i)->name());
+    auto transmissionRunSum = firstTransG->getItem(0)->name();
```
Comment (OwenArnold) [inline Framework/Algorithms/src/ReflectometryReductionOneAuto.cpp]: This can't be right. I'm guessing this has not been exercised.

File: Framework/Algorithms/src/ReflectometryReductionOneAuto.cpp [hunk 2]
```diff
@@ -592,8 +594,20 @@ bool ReflectometryReductionOneAuto::processGroups() {
...
+    if (firstTransG) {
+      for (size_t item = 1; item < firstTransG->size(); item++) {
+        auto plusAlg = this->createChildAlgorithm("Plus");
+        plusAlg->setChild(true);
+        plusAlg->initialize();
+        plusAlg->setProperty("LHSWorkspace", transmissionRunSum);
```
Comment (OwenArnold) [inline Framework/Algorithms/src/ReflectometryReductionOneAuto.cpp]: I suspect this would break if I actually ran it?

File: Framework/Algorithms/src/ReflectometryReductionOneAuto.cpp [hunk 3]
```diff
@@ -592,8 +594,20 @@ bool ReflectometryReductionOneAuto::processGroups() {
...
+        plusAlg->setProperty("RHSWorkspace", firstTransG->getItem(item));
+        plusAlg->setProperty("OutputWorkspace", transmissionRunSum);
+        plusAlg->execute();
+        transmissionRunSum = plusAlg->getPropertyValue("OutputWorkspace");
+      }
+      alg->setProperty("FirstTransmissionRun", transmissionRunSum);
+    }
     if (secondTransG)
       alg->setProperty("SecondTransmissionRun",
```
Comment (OwenArnold) [inline Framework/Algorithms/src/ReflectometryReductionOneAuto.cpp]: The second transmission run needs to be processed in the same way as the first tranmsission run

File: Framework/Algorithms/src/ReflectometryReductionOneAuto.cpp [hunk 4]
```diff
@@ -592,8 +594,20 @@ bool ReflectometryReductionOneAuto::processGroups() {
     alg->setProperty("OutputWorkspaceWavelength", IvsLamName);
 
     // Handle transmission runs
-    if (firstTransG)
-      alg->setProperty("FirstTransmissionRun", firstTransG->getItem(i)->name());
+    auto transmissionRunSum = firstTransG->getItem(0)->name();
+    if (firstTransG) {
+      for (size_t item = 1; item < firstTransG->size(); item++) {
```
Comment (OwenArnold) [inline Framework/Algorithms/src/ReflectometryReductionOneAuto.cpp]: Do not rely on the transmission input having the same number of entries as the InputWorkspace. Create a for loop outside of the main for loop for this.

File: Framework/Algorithms/src/ReflectometryReductionOneAuto.cpp [hunk 5]
```diff
@@ -552,7 +553,7 @@ bool ReflectometryReductionOneAuto::processGroups() {
         AnalysisDataService::Instance().retrieveWS<Workspace>(firstTrans);
     firstTransG = boost::dynamic_pointer_cast<WorkspaceGroup>(firstTransWS);
 
-    if (!firstTransG)
+    if (!firstTransG) // sum over transmission workspaces here?
```
Comment (OwenArnold) [inline Framework/Algorithms/src/ReflectometryReductionOneAuto.cpp]: This is no longer a valid check

File: Framework/Algorithms/src/ReflectometryReductionOneAuto.cpp [hunk 6]
```diff
@@ -569,7 +570,8 @@ bool ReflectometryReductionOneAuto::processGroups() {
     secondTransG = boost::dynamic_pointer_cast<WorkspaceGroup>(secondTransWS);
 
     if (!secondTransG)
-      alg->setProperty("SecondTransmissionRun", secondTrans);
+      alg->setProperty("SecondTransmissionRun",
```
Comment (OwenArnold) [inline Framework/Algorithms/src/ReflectometryReductionOneAuto.cpp]: This is no longer a valid check

File: Framework/Algorithms/src/ReflectometryReductionOneAuto.cpp [hunk 7]
```diff
@@ -521,6 +522,23 @@ bool ReflectometryReductionOneAuto::checkGroups() {
   return false;
 }
 
+Mantid::API::Workspace_sptr
+ReflectometryReductionOneAuto::handleTransmissionGroup(
+    Mantid::API::WorkspaceGroup_sptr transG) {
```
Comment (OwenArnold) [inline Framework/Algorithms/src/ReflectometryReductionOneAuto.cpp]: I would name this function something else. As a general rule avoid `manage` `utility` `helper` or `handler` from names in software if possible.

File: Framework/Algorithms/src/ReflectometryReductionOneAuto.cpp [hunk 8]
```diff
@@ -569,15 +583,22 @@ bool ReflectometryReductionOneAuto::processGroups() {
     secondTransG = boost::dynamic_pointer_cast<WorkspaceGroup>(secondTransWS);
 
     if (!secondTransG)
-      alg->setProperty("SecondTransmissionRun", secondTrans);
-    else if (group->size() != secondTransG->size())
-      throw std::runtime_error("SecondTransmissionRun WorkspaceGroup must be "
```
Comment (OwenArnold) [inline Framework/Algorithms/src/ReflectometryReductionOneAuto.cpp]: This check is still valid if you are NOT doing PolarizationCorrection. So make sure it still runs the check if you are NOT doing PolarizationCorrection.

File: Framework/Algorithms/src/ReflectometryReductionOneAuto.cpp [hunk 9]
```diff
@@ -569,15 +583,22 @@ bool ReflectometryReductionOneAuto::processGroups() {
...
-                               "WorkspaceGroup");
+      alg->setProperty("SecondTransmissionRun",
+                       secondTrans); // sum over transmission workspaces here?
   }
 
   std::vector<std::string> IvsQGroup, IvsLamGroup;
 
+  // Handle transmission runs before processing InputWorkspace group members.
+  if (firstTransG) {
+    auto firstTransmissionSum = handleTransmissionGroup(firstTransG);
```
Comment (OwenArnold) [inline Framework/Algorithms/src/ReflectometryReductionOneAuto.cpp]: Good

File: Framework/Algorithms/src/ReflectometryReductionOneAuto.cpp [hunk 10]
```diff
@@ -569,15 +583,22 @@ bool ReflectometryReductionOneAuto::processGroups() {
...
+    alg->setProperty("FirstTransmissionRun", firstTransmissionSum);
+  }
+  if (secondTransG) {
+    auto secondTransmissionSum = handleTransmissionGroup(secondTransG);
```
Comment (OwenArnold) [inline Framework/Algorithms/src/ReflectometryReductionOneAuto.cpp]: Good

**Comment by OwenArnold** [comment]
What about the system tests?

**Comment by OwenArnold** [comment]
1. Running your System test. I don't see where the summation of the transmission group is happening in the history. I should see that plus has been called 4 times, but I don't see it for some reason.

2. If I sum the group by myself I can reliably get mantid to crash here `Mantid::Algorithms::ReflectometryReductionOneAuto::processGroups()`. You can use the following to reproduce it.

```python

#pylint: disable=no-init,invalid-name,line-too-long

"""
This system test verifies that OFFSPEC data is processed correctly
by ReflectometryReductionAutoOne with PolarizationCorrection performed
as part of the workflow.
"""

from mantid.simpleapi import *

class OFFSPECReflRedOneAutoPolarizationCorrection(object):
    def runTest(self):
        inputWorkspace = Load("OFFSPEC00033767.nxs")
        transmissionGroup = Load("OFFSPEC00033772.nxs")
        #set up our transmission workspace
        transWorkspace = CreateTransmissionWorkspaceAuto(transmissionGroup,
                                                         AnalysisMode="MultiDetectorAnalysis",
                                                         ProcessingInstructions="110-120",
                                                         WavelengthMin=2.0,
                                                         WavelengthMax=12.0)
                                                         
        sum = transWorkspace[0] + transWorkspace[1] + transWorkspace[2] + transWorkspace[3]                                                 
        # set up our efficiency constants
        CRho=[1]
        CAlpha=[1]
        CAp=[1]
        CPp=[1]
        #run reflectometryReductionOneAuto
        __, _IvsLam_polCorr,__ = ReflectometryReductionOneAuto(inputWorkspace, AnalysisMode="MultiDetectorAnalysis",
                                                              ProcessingInstructions="110-120",
                                                              FirstTransmissionRun=sum,
                                                              ThetaIn="1.2",WavelengthMin=2.0,
                                                              WavelengthMax=12.0,CorrectionAlgorithm='None',
                                                              PolarizationAnalysis='PA',
                                                              CPp=CPp,CAp=CAp,CRho=CRho,CAlpha=CAlpha)
        return True

    def validate(self):
        return ("_IvsLam_polCorr", "OFFSPECReflRedOneAutoPolarizationCorrection_good.nxs")

    def requiredFiles(self):
        return ["OFFSPEC00033767.nxs",
                "OFFSPEC00033772.nxs",
                "OFFSPECReflRedOneAutoPolarizationCorrection_good.nxs"]
                
                
OFFSPECReflRedOneAutoPolarizationCorrection().runTest()
```

File: Framework/Algorithms/src/ReflectometryReductionOneAuto.cpp [hunk 11]
```diff
@@ -520,11 +520,48 @@ bool ReflectometryReductionOneAuto::checkGroups() {
...
+ * @param transGroup : The transmission group to be processed
+ * @return A workspace pointer containing the sum of transmission workspaces.
+ */
+Mantid::API::Workspace_sptr
+ReflectometryReductionOneAuto::sumOverTransmissionGroup(
+    WorkspaceGroup_sptr transGroup) {
+  // Handle transmission runs
+  auto transmissionRunSum = transGroup->getItem(0);
+  MatrixWorkspace_sptr total;
+  for (size_t item = 1; item < transGroup->size(); item++) {
```
Comment (picatess) [inline Framework/Algorithms/src/ReflectometryReductionOneAuto.cpp]: ++item See (here)[http://stackoverflow.com/questions/1392820/why-use-i-instead-of-i-in-cases-where-the-value-is-not-used-anywhere-else-in]  for example

File: Framework/Algorithms/src/ReflectometryReductionOneAuto.cpp [hunk 12]
```diff
@@ -520,11 +520,48 @@ bool ReflectometryReductionOneAuto::checkGroups() {
...
+    auto plusAlg = this->createChildAlgorithm("Plus");
+    plusAlg->setChild(true);
+    // plusAlg->setRethrows(true);
```
Comment (picatess) [inline Framework/Algorithms/src/ReflectometryReductionOneAuto.cpp]: What do you want to do with this?

Comment (MattKing06) [inline Framework/Algorithms/src/ReflectometryReductionOneAuto.cpp]: Get the sum of all the workspaces in the transmission group and put it into one workspace to return.

File: Framework/Algorithms/src/ReflectometryReductionOneAuto.cpp [hunk 13]
```diff
@@ -552,9 +589,13 @@ bool ReflectometryReductionOneAuto::processGroups() {
...
 
-    if (!firstTransG)
+    if (!firstTransG) {
+      // we only have one transmission workspace, so we use it as it is.
       alg->setProperty("FirstTransmissionRun", firstTrans);
-    else if (group->size() != firstTransG->size())
+    } else if (group->size() != firstTransG->size() &&
+               !isPolarizationCorrectionOn)
+      // if they are not the same size then we cannot associate a transmission
+      // group workspace member with every input group workpspace member.
```
Comment (picatess) [inline Framework/Algorithms/src/ReflectometryReductionOneAuto.cpp]: This is correct code, but rather a matter of personal choice. Although you have a single statement here, the effective block size is 5 lines(with the comment). I find it easier to read when curly backets are used. But as I said this is a matter or personal choice and maybe there are good reasons against it.

File: Testing/SystemTests/tests/analysis/OFFSPECReflRedOneAutoPolarizationCorrection.py [hunk 14]
```diff
@@ -0,0 +1,43 @@
...
+                                                              ProcessingInstructions="110-120",
+                                                              FirstTransmissionRun=transWorkspace,
+                                                              ThetaIn="1.2",WavelengthMin=2.0,
+                                                              WavelengthMax=12.0,CorrectionAlgorithm='None',
+                                                              PolarizationAnalysis='PA',
+                                                              CPp=CPp,CAp=CAp,CRho=CRho,CAlpha=CAlpha)
+        return True
+
+    def validate(self):
+        return ("_IvsLam_polCorr", "OFFSPECReflRedOneAutoPolarizationCorrection_good.nxs")
```
Comment (picatess) [inline Testing/SystemTests/tests/analysis/OFFSPECReflRedOneAutoPolarizationCorrection.py]: I think you normally have a clean up stage as well, but I might be wrong here. The system tests should all be run in their own processes, so it should not really matter. But maybe have a look around some other tests if cleaning up is normally done.  Good way to see which workspaces live in the ADS currently is 
```python
for element in mtd.getObjectNames():
    print element
```

File: Framework/Algorithms/src/ReflectometryReductionOneAuto.cpp [hunk 15]
```diff
@@ -520,11 +520,47 @@ bool ReflectometryReductionOneAuto::checkGroups() {
...
+ * @return A workspace pointer containing the sum of transmission workspaces.
+ */
+Mantid::API::Workspace_sptr
+ReflectometryReductionOneAuto::sumOverTransmissionGroup(
+    WorkspaceGroup_sptr &transGroup) {
+  // Handle transmission runs
+  auto transmissionRunSum = transGroup->getItem(0);
+  MatrixWorkspace_sptr total;
+  for (size_t item = 1; item < transGroup->size(); ++item) {
+    auto plusAlg = this->createChildAlgorithm("Plus");
```
Comment (picatess) [inline Framework/Algorithms/src/ReflectometryReductionOneAuto.cpp]: as just discussed, it is probably good to create the algorithm only once and only reasign/execute in a loop. Maybe time the difference, that would be interesting

**Comment by OwenArnold** [comment]
@MattKing06  Has this been checked by instrument scientists yet?

**Comment by MattKing06** [comment]
@OwenArnold I've sent an installer with the changes on to Jos, I'm just waiting for him to get back to me

**Comment by MattKing06** [comment]
Jos has approved the changes, he had some small worries with the way that the data was plotting as it didn't match up exactly with what he predicted. However, he has said this may will clear itself up after some more of the issues with ReflectometryReductionOneAuto are merged so he said that it's fine as it is now.
