### PR TITLE
GroupWorkspaces allows a Workspace with the same name as the group

### LINKED ISSUE #24100: Project saving segfaults when a workspace group contains a workspace of the same name
### Expected behavior

I think you should be able to have a group workspace contain a workspace of the same name or at least this behavior is not currently forbidden by Mantid. Given that workspaces and group workspaces are actually stored in a flat structure it perhaps should be and this may just be a case of this case breaking a whole load of things.

### Actual behavior

Mantid will segfualt when project saveing is attempted

### Steps to reproduce the behavior

Run this script and wait for project saving to attempt

```
dataX = [0, 1, 2, 3, 4, 5] * 4
dataY = [10, 20, 30, 20, 10] + \
        [20, 30, 40, 30, 20] + \
        [30, 40, 50, 40, 30] + \
        [40, 50, 60, 50, 40]
print(dataY)
input_workspace = CreateWorkspace(dataX, dataY, NSpec=4)

input_workspace = GroupWorkspaces(input_workspace)
```

### PR DESCRIPTION
**Pull request by Pasarus**
**Description of work.**
The original issue shed light on the fact that GroupWorkspaces the algorithm allows the addition of a workspace with the same name as the group. Which lead to an investigation of the ADS in which it was found that this is "perfectly valid". The current ADS structure assumes this isn't the case. It registered two items with the same name in a "map" representation. So the checks have to be added at input time so extra validation was added to the ADS add, addOrReplace and addToGroup functions to remove this.

**To test:**
If tests pass ADS changes can be assumed.
Run this script to test GroupWorkspaces changes:
```python
dataX = [0, 1, 2, 3, 4, 5] * 4
dataY = [10, 20, 30, 20, 10] + \
        [20, 30, 40, 30, 20] + \
        [30, 40, 50, 40, 30] + \
        [40, 50, 60, 50, 40]
print(dataY)
input_workspace = CreateWorkspace(dataX, dataY, NSpec=4)

input_workspace = GroupWorkspaces(input_workspace)
```

Fixes #24100 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/API/src/AnalysisDataService.cpp [hunk 1]
```diff
@@ -73,16 +73,18 @@ AnalysisDataServiceImpl::isValid(const std::string &name) const {
...
+  verifyName(name, group);
+
   // Attach the name to the workspace
   if (workspace)
     workspace->setName(name);
   Kernel::DataService<API::Workspace>::add(name, workspace);
 
   // if a group is added add its members as well
-  auto group = boost::dynamic_pointer_cast<WorkspaceGroup>(workspace);
   if (!group)
```
Comment (TTitcombe) [inline Framework/API/src/AnalysisDataService.cpp]: Should we move this check up with `auto group = ....`

File: Framework/API/src/AnalysisDataService.cpp [hunk 2]
```diff
@@ -147,6 +148,14 @@ void AnalysisDataServiceImpl::addOrReplace(
  */
 void AnalysisDataServiceImpl::rename(const std::string &oldName,
                                      const std::string &newName) {
+
+  auto oldWorkspace = retrieve(oldName);
+  auto group = boost::dynamic_pointer_cast<WorkspaceGroup>(oldWorkspace);
+  if (group && group->contains(newName)) {
+    throw std::runtime_error(
+        "Unable to rename group as the new name matches its member's");
```
Comment (TTitcombe) [inline Framework/API/src/AnalysisDataService.cpp]:
```suggestion
        "Unable to rename group as the new name matches its members");
```

File: Framework/API/src/AnalysisDataService.cpp [hunk 3]
```diff
@@ -362,13 +376,24 @@ void AnalysisDataServiceImpl::setIllegalCharacterList(
...
+void AnalysisDataServiceImpl::verifyName(
+    const std::string &name,
+    const boost::shared_ptr<API::WorkspaceGroup> &group) {
   const std::string error = isValid(name);
   if (!error.empty()) {
     throw std::invalid_argument(error);
   }
+
+  if (group && group->contains(name)) {
+    throw std::runtime_error(
```
Comment (TTitcombe) [inline Framework/API/src/AnalysisDataService.cpp]: I think this should be an invalid_argument error (both checks are valid name checks so should throw the same thing)

**Review by TTitcombe — CHANGES_REQUESTED** [review]

**Comment by TTitcombe** [comment]
While testing, I've found a couple of cases which aren't covered by this PR:
Say you have a group A containing workspaces B and C, and then a workspace D on its own.
If you rename D to "A", then you will have three workspaces, A, B, and C, all ungrouped.
If you rename A to "D" then you will have a group workspace D containing B and C, but the original D workspace no longer exists.

This is probably too much scope creep to deal with in this PR?

File: Framework/API/src/AnalysisDataService.cpp (hunk 1 above)
Comment (Pasarus) [reply Framework/API/src/AnalysisDataService.cpp]: No, because we still want to be able to add normal workspaces to the ADS

**Comment by TTitcombe** [comment]
Speaking offline to @Pasarus, we've found a case where groups containing groups can still be renamed to workspaces they contain.

```
a = CreateSampleWorkspace()
b = GroupWorkspaces([a])
c = CreateSampleWorkspace()
d = GroupWorkspaces([c])
d.add("b")
RenameWorkspace(d, "a")
```

**Review by TTitcombe — APPROVED** [review]

**Comment by TTitcombe** [comment]
This PR introduces a good change to workspace management. Useful error messages are raised when trying to create group workspaces with the same name as one of its members, in all test cases I could think of
