### PR TITLE
Move Values Saved to `sasprocessnote` to `sasprocess` in SaveNXCanSAS

### LINKED ISSUE #36552: Inconsistency in where some metadata is stored in NXcanSAS output
**Original reporter:**
Greg Smith, ISIS

**Describe the bug**
The following zip archive contains 2 files of the same data saved from Mantid in the two most common SANS output formats:
[RT1standard-LARMOR.zip](https://github.com/mantidproject/mantid/files/13662155/RT1standard-LARMOR.zip)

Both files are valid and will load and can be analysed in SasView.

However, we have noticed that where some of the metadata is stored differs between the two. The consequence of this is that the SasView data loader is unable to interpret and present as much of the metadata as it could.

Specifically, it seems to be the .h5 file which differs. In this file the information about the run numbers used in the reduction are stored under sasnote:
image

In the .xml file these appear under sasprocess and sasnote is empty:
image

The SasView metadata display for these two files are captured here:
[RT1 standard_1D reduction_metadata_NXcanSAS.txt](https://github.com/mantidproject/mantid/files/13662256/RT1.standard_1D.reduction_metadata_NXcanSAS.txt)
[RT1 standard_1D reduction_metadata_canSAS1D.txt](https://github.com/mantidproject/mantid/files/13662259/RT1.standard_1D.reduction_metadata_canSAS1D.txt)

As can be seen, the runs appear in the canSAS1D metadata but not in the NXcanSAS metadata.

**To Reproduce**
1D reduce some SANS data in Mantid and output as canSAS1D and NXcanSAS.
Load the output files in SasView
Right-click on the files in the Data Explorer and select DataInfo.

**Expected behavior**
The locations of metadata should be consistent between the two formats. The NXcanSAS metadata output should be adjusted.

### PR DESCRIPTION
**Pull request by cailafinn**
#### Summary of work
Adjusts the `SaveNXCanSAS` algorithm so that the metadata saved to `sasprocessnote` is saved to `sasprocess` instead. 

Fixes #36552 

#### Further detail of work
Note: The data that was saved to `sasprocessnote` (now in `sasprocess`) is not loaded back into mantid when the `.h5` file is loaded. Only the User File and Batch File are loaded as sample logs. This is obviously not ideal, but is outside the scope of this PR and should be done all at once with the other values in `sasprocess` if it is desired. 

### To test:
1. Boot the SANS GUI
2. Load the user file and batch file from the `loqdemo` in the training course data
3. Set the save mode to both NXcanSAS and CanSAS1D. 
4. Process All
5. Open the output `.xml` in your text editor of choice
6. Open the `.h5` in [HDFView](https://www.hdfgroup.org/downloads/hdfview/)
7. Compare the values in sasprocess and ensure that both files have the same structure. 

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

File: Framework/DataHandling/src/SaveNXcanSAS.cpp [hunk 1]
```diff
@@ -384,15 +384,6 @@ void addProcess(H5::Group &group, const Mantid::API::MatrixWorkspace_sptr &works
...
- * Create a note class within process
- * @param group: the sasEntry
- */
-void createNote(H5::Group &group) {
-  auto process = group.openGroup(sasProcessGroupName);
-  Mantid::DataHandling::H5Util::createGroupCanSAS(process, sasNoteGroupName, nxNoteClassAttr, sasNoteClassAttr);
-}
-
 /**
  * Add a note containing sample or can run numbers to the process group.
```
Comment (rbauststfc) [inline Framework/DataHandling/src/SaveNXcanSAS.cpp:388]: There are a few comments around and within this method referring to notes that might be worth updating now that there isn't a notes section.

**Review by rbauststfc — COMMENTED** [review]
I just had a minor comment about updating comments in the code now that the note section doesn't exist, but otherwise this is working very well. The metadata is now showing up in the correct section and it's still possible to load the file in the same way as before (as noted, the metadata isn't currently loaded back into Mantid, so this change doesn't impact that).

**Review by rbauststfc — APPROVED** [review]
The comments have all been updated appropriately, so this looks good to go in. 👍
