### PR TITLE
Fix convert spectrum axis

### LINKED ISSUE #24795: Issue with ConvertSpectrumAxis and event workspaces following refactor
Broken code from maintenance on issue #22935. To demo run this in Mantid
```
ws = CreateSampleWorkspace(WorkspaceType='Event')
as_theta=ConvertSpectrumAxis(ws, Target='theta')
```
Output:
```
Error in execution of algorithm ConvertSpectrumAxis:
EventWorkspace cannot be initialized non-NULL Y or E data
RuntimeError: EventWorkspace cannot be initialized non-NULL Y or E data
```

I believe the offending code is [here](https://github.com/mantidproject/mantid/blame/master/Framework/Algorithms/src/ConvertSpectrumAxis2.cpp#L233-L234)
Which is explicitly rejected [here](https://github.com/mantidproject/mantid/blob/master/Framework/DataObjects/src/EventWorkspace.cpp#L124) 

We should start by adding a unit test to ConvertSpectrumAxis2 for converting the spectrum axis of an event workspace. 

Maybe @SimonHeybrock can offer help/advice if needed.

### PR DESCRIPTION
**Pull request by LowriJenkins**
**Description of work.**
The algorithm was failing on event workspaces following a refactor, a test ensuring it works, and the fix necessary have been added.
**To test:**
Ensure unit tests pass, run script supplied in issue, it should finish without error

Fixes #24795 

*This does not require release notes* because **The bug has is not present in a full release**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Algorithms/test/ConvertSpectrumAxis2Test.h [hunk 1]
```diff
@@ -468,6 +468,22 @@ class ConvertSpectrumAxis2Test : public CxxTest::TestSuite {
...
+    Mantid::Algorithms::ConvertSpectrumAxis2 conv;
+    conv.initialize();
+
+    TS_ASSERT_THROWS_NOTHING(conv.setProperty("InputWorkspace", testWS));
+    TS_ASSERT_THROWS_NOTHING(
+        conv.setPropertyValue("OutputWorkspace", outputWS));
+    TS_ASSERT_THROWS_NOTHING(conv.setPropertyValue("Target", target));
+    TS_ASSERT_THROWS_NOTHING(conv.execute());
+    TS_ASSERT(conv.isExecuted());
+  }
```
Comment (OwenArnold) [inline Framework/Algorithms/test/ConvertSpectrumAxis2Test.h]: Can you check the vertical axis of the output workspace to demonstrate the the units have been converted to theta?

File: Framework/Algorithms/test/ConvertSpectrumAxis2Test.h [hunk 2]
```diff
@@ -468,6 +468,22 @@ class ConvertSpectrumAxis2Test : public CxxTest::TestSuite {
...
     }
   }
+
+  void test_eventWS() {
+    const std::string outputWS("outWS");
+    const std::string target("theta");
+    auto testWS =
+        WorkspaceCreationHelper::createEventWorkspaceWithFullInstrument(500, 3);
+    Mantid::Algorithms::ConvertSpectrumAxis2 conv;
+    conv.initialize();
```
Comment (OwenArnold) [inline Framework/Algorithms/test/ConvertSpectrumAxis2Test.h]: Because you haven't set `conv.setRethrows(true)`, the `execute()` below will not throw anyway, so the ASSERT check wrapping it is redundant.

IMHO, TS_ASSERT_THROWS_NOTHING is usually noise and acutally makes it harder to establish the point of failure in the test so I suggest removing all of them from here.

Comment (OwenArnold) [reply Framework/Algorithms/test/ConvertSpectrumAxis2Test.h]: You should call `conv.setChild(true)` that way the algorithm will not interact with the ADS, and you can get the output workspace easily without going through the ADS.

**Review by OwenArnold — DISMISSED** [review]

File: Framework/Algorithms/test/ConvertSpectrumAxis2Test.h (hunk 1 above)
Comment (SamJenkins1) [reply Framework/Algorithms/test/ConvertSpectrumAxis2Test.h]: so check that the unit is degrees?

Comment (OwenArnold) [reply Framework/Algorithms/test/ConvertSpectrumAxis2Test.h]: Indeed. Possibly also check that the 2two theta value is what should be expected for the spectrum.

**Comment by OwenArnold** [comment]
@SamJenkins1 I'm away now until 3rd March. If you make these review-comment changes, it looks like the changes are going to yield the right behaviour. So please pass it on to a second reviewer. I'll dismiss my original review.

**Comment by SimonHeybrock** [comment]
I am not sure I understand this change. `ConvertSpectrumAxis` now converts from events to histograms? I thought previously it preserved events?

**Comment by SimonHeybrock** [comment]
I know. But don't you want to preserve events?

File: Framework/Algorithms/test/ConvertSpectrumAxis2Test.h [hunk 3]
```diff
@@ -468,6 +468,25 @@ class ConvertSpectrumAxis2Test : public CxxTest::TestSuite {
...
+    conv.setChild(true);
+    conv.initialize();
+
+    conv.setProperty("InputWorkspace", testWS);
+
+    conv.setPropertyValue("OutputWorkspace", outputWS);
+    conv.setPropertyValue("Target", target);
+    conv.execute();
+    TS_ASSERT(conv.isExecuted());
+    const MatrixWorkspace_sptr output = conv.getProperty("OutputWorkspace");
```
Comment (SimonHeybrock) [inline Framework/Algorithms/test/ConvertSpectrumAxis2Test.h]: Changes look good now, just one small thing: Can you add an assert here that tests whether this is actually an `EventWorkspace`?

**Review by SimonHeybrock — DISMISSED** [review]

**Review by SimonHeybrock — APPROVED** [review]
