### PR TITLE
Show Detector ROIs as Ranges on the Experiment Settings Tab

### LINKED ISSUE #34606: Show ROIs as ranges rather than lists
On the ISIS Reflectometry interface Preview tab, when you apply the selected instrument viewer ROI to the Experiment settings, each individual selected detector gets listed in the table, creating a very long string. We should consolidate contiguous ranges of detectors into a grouping pattern string instead, e.g. `1-5, 10-12` instead of `1,2,3,4,5,10,11,12`. There may be some string utilities in Kernel or elsewhere we could use to help with this.

See also #34326

**To reproduce**
- Open the ISIS Reflectometry interface
- On the Preview tab, enter run `INTER45455_inst` and click Load (see this issue for the data: #31069)
- Select a region on the instrument viewer plot and click Apply
- Go to the Experiment tab and check the `ROI Detector IDs` field in the table - it lists every detector individually.

### PR DESCRIPTION
**Pull request by cailafinn**
**Description of work.**
Make the Apply button on the preview tab fill the Experiment Settings tab's ROI Detector IDs column with ranges rather than an unreadable list of values. 

**To test:**
1. Open the ISIS Reflectometry interface
2. Go to the Preview tab
3. Enter run `INTER45455_inst` and click Load (This data is available on this Epic and must be in your path: #31069)
4. Select the `Draw a Rectangle` button on the instrument viewer. 
5. Draw over some of the detectors. 
6. Hit Apply
7. Check that the selected detectors are now present on the Experiment Settings tab's final column. 

Fixes #34606 

*This does not require release notes* because **this piece of work is not user facing yet.**

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/scientific_interfaces/ISISReflectometry/GUI/Experiment/ExperimentPresenter.cpp [hunk 1]
```diff
@@ -111,7 +111,7 @@ void ExperimentPresenter::notifyPreviewApplyRequested(PreviewRow const &previewR
   if (auto const foundRow = m_model.findLookupRow(previewRow, m_thetaTolerance)) {
     auto lookupRowCopy = *foundRow;
 
-    lookupRowCopy.setRoiDetectorIDs(previewRow.getSelectedBanks());
+    lookupRowCopy.setRoiDetectorIDs(getRangesFromListOfBanks(previewRow.getSelectedBanks()));
```
Comment (rbauststfc) [inline qt/scientific_interfaces/ISISReflectometry/GUI/Experiment/ExperimentPresenter.cpp:114]: I noticed that the selected banks are set in `PreviewPresenter::notifyInstViewShapeChanged()`, which formats them as a comma delimited string. Would it work to set the format we need straight away within the `PreviewPresenter` method instead of having to reformat here, or does that cause problems?

File: qt/scientific_interfaces/ISISReflectometry/test/Preview/PreviewModelTest.h [hunk 2]
```diff
@@ -83,14 +83,6 @@ class PreviewModelTest : public CxxTest::TestSuite {
     TS_ASSERT_EQUALS(inputRoi, *model.getSelectedBanks())
   }
 
-  void test_set_selected_signal_region_converts_to_processing_instructions_string() {
```
Comment (rbauststfc) [inline qt/scientific_interfaces/ISISReflectometry/test/Preview/PreviewModelTest.h:86]: Sorry if the answer to this question is obvious, but was there a reason for removing this test?

**Review by rbauststfc — COMMENTED** [review]
The fix works really well and the logic for reformatting a comma delimited string into a range looks good. The test coverage for the new method also looks great. 👍

I just had a couple of thoughts/queries.

File: qt/scientific_interfaces/ISISReflectometry/GUI/Experiment/ExperimentPresenter.cpp [hunk 3]
```diff
@@ -125,6 +125,57 @@ void ExperimentPresenter::notifyPreviewApplyRequested(PreviewRow const &previewR
   }
 }
 
+boost::optional<ProcessingInstructions>
+ExperimentPresenter::getRangesFromListOfBanks(boost::optional<ProcessingInstructions> banks) const {
```
[the remark this answers is not in the document]
Comment (ConorMFinn) [reply qt/scientific_interfaces/ISISReflectometry/GUI/Experiment/ExperimentPresenter.cpp:129]: Ah, yes. I did think about that, but wasn't sure where it would be best to have it. Having it in there seems like it would make more sense. Thanks

**Review by rbauststfc — APPROVED** [review]
Changes look great. Good spot finding the `joinCompress` method in the Kernel Strings utility. 👍
