### PR TITLE
SortXAxis Vector Subscript out of range error

### LINKED ISSUE #25396: SortXAxis - Vector subscript out of range error when sorting y data
### Description
There is a vector subscript out of range error when the y data is being sorted within the SortXAxis algorithm. 
This is happening because a `workspaceIndices` vector is calculated based off the x data, and then this is used to sort y data without being re-sized properly (XSize == Ysize+1 for histogram workspaces). Hence a vector subscript out of range error occurs.

### Steps to reproduce the behavior
1.`Interfaces`->`Indirect`->`Data Reduction`->`ISISEnergyTransfer` tab
2. Instrument is `TOSCA`
3. Enter run number `4970`
4. Click `Run` and wait
Error

### Platforms affected
Windows (not on a Windows VM however)

### PR DESCRIPTION
**Pull request by robertapplin**
Only test on windows, and on Debug mode
------------------------------------------------
**Description of work.**
This PR fixes a vector subscript out of range error in the `SortXAxis` algorithm. This causes old TOSCA workflows to fail.
A system test is also included to try and provide coverage for older TOSCA run numbers.

**To test:**
1.`Interfaces`->`Indirect`->`Data Reduction`->`ISISEnergyTransfer` tab
2. Instrument is `TOSCA`
3. Enter run number `4970`
4. Click `Run` and wait
There should be no error.

Fixes #25396 and #25345 

*No release notes required as this affects older data and occurs only for windows users*

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Algorithms/src/SortXAxis.cpp [hunk 1]
```diff
@@ -179,51 +188,45 @@ void SortXAxis::copyXandDxToOutputWorkspace(
...
-                  inputWorkspace.y(specNum).size());
-    workspaceIndicies.erase(lastIndexIt);
-  }
-
+    Mantid::API::MatrixWorkspace &outputWorkspace, unsigned int specNum) {
   auto &inSpaceY = inputWorkspace.y(specNum);
+  const auto ySize = inSpaceY.size();
+
+  // Remove workspace indices which are out of index range for y space
+  removeElementsIf(workspaceIndices, [&ySize](const std::size_t &index) {
```
Comment (Pasarus) [inline Framework/Algorithms/src/SortXAxis.cpp]: This isn't a simple refactor, the actual behavior of how many values that are removed from the Y axis of the spectrum has changed. Now I understand that this will potentially catch any failures with data that is  and make it simpler to interact with, I however disagree with this approach. This is because this will remove potentially valid data and "do the sort", this algorithm should just fail in this case if it is a histogram. The algorithm is not stated to fix your broken data but just sort a workspace based on it's X axis.

If at this stage it needs to remove more than one workspace index from the passed vector, then something has gone really wrong with expected data and we should not process it. I would like to suggest reverting to only remove one value at the end of the vector given it is a histogram using previously generated bool values (This could be made a member variable) to keep previous efficiency. Further more I would like to suggest we throw if it should need to remove more than one, as we do not support that data in this algorithm, so it should not be processed, perhaps that could be done early in exec.

(Let alone the fact this is ran for every single data value passed to this function, which never had to occur for the original purpose of this algorithm which was actually sorting point data, not flipping a histograms X Axis.)

File: Testing/SystemTests/tests/analysis/ISISIndirectInelastic.py [hunk 2]
```diff
@@ -227,6 +227,19 @@ def get_reference_files(self):
         return ["II.TOSCAReductionFromFile.nxs"]
 
 
+class TOSCASimpleReductionUsingOldRunNumber(ISISIndirectInelasticReduction):
```
Comment (Pasarus) [inline Testing/SystemTests/tests/analysis/ISISIndirectInelastic.py]: I can't seem to work out what this does, but I believe these don't run on linux variants or macOS, since RHEL7 is our main tester for these I don't think these would run for a normal dev to see during a PR. Would it be possible to make a unit test specifically for the TOSCA data that this PR is attempting to fix, somewhere else? If not then here is about as good as we can get.

**Review by Pasarus — CHANGES_REQUESTED** [review]
Good work so far, but I do disagree with some fundamental changes that have been done here. Specifically the part about using std::remove_if instead of generally removing one WorkspaceIndex from the list if it is histogram data, which is the only case in which this should be ran. 

Interestingly enough this error could only be found to run on a developer's build on windows in Debug mode, unless you checked that the error could be replicated in the Release/Packaged modes. As with @SamJenkins1 I struggle to fathom the difference between VM and native windows being a problem here, as effectively the operating systems are the same, it's the hardware it thinks it has access to that is different from my understanding. I am working to validate this with a colleague. 

Other than the other stated changes, this PR has some nice changes! Good Work! :+1:

**Comment by Pasarus** [comment]
When running the test on a native Windows build in Debug mode, I get no error as happened previously, however I do get an error in the logs:

```
Error in ececution of algorithm LoadLog:
File:\\isis.clrc.ac.uk\inst$\ndxtosca\instrument\data\cycle_02_6\TSC04970.log is not a standard ISIS log file. Expected to be a file starting with DateTime String format.
Unable to successfully run LoadLog Child Algorithm
Unable to successfully run LoadLog Child Algorithm
Cannout process ICPevent log. Period 1 assumed for all data.
```
This is unrelated to change but the test stated no errors.

Also I have just confirmed that a VM on Debug mode shows the error so the assumption of VM being wrong is incorrect, however does point to an interesting quirk that release isn't showing this error.

File: Testing/SystemTests/tests/analysis/ISISIndirectInelastic.py (hunk 2 above)
Comment (robertapplin) [reply Testing/SystemTests/tests/analysis/ISISIndirectInelastic.py]: I think this is the best place for this test

File: Framework/Algorithms/src/SortXAxis.cpp (hunk 1 above)
Comment (robertapplin) [reply Framework/Algorithms/src/SortXAxis.cpp]: I have added a check which will throw if the input workspace is not point data or a histogram workspace so that it is now safe to remove just the last workspaceIndex

**Review by Pasarus — CHANGES_REQUESTED** [review]
I think we should talk in person about further changes to this algorithm as I do not believe that it is within the scope of the original issue. Since this comes about because of a temporary change until the RemoveSpectra Algorithm is finished, I believe since this is the case the PR needs some rethinking as to the scope of changes to be done to a general algorithm used in other algorithms.

The changes themselves are being questioned in the review comments.

**Review by Pasarus — DISMISSED** [review]
All looking good now! Code changes look good and a great test :+1:

File: Framework/Algorithms/src/SortXAxis.cpp [hunk 3]
```diff
@@ -70,7 +70,7 @@ void SortXAxis::exec() {
   const bool isAProperHistogram =
       (!ignoreHistogramValidation)
           ? determineIfHistogramIsValid(*inputWorkspace)
-          : false;
```
Comment (gvardany) [inline Framework/Algorithms/src/SortXAxis.cpp]: I think this expression deserves an inline comment. Also you should add a unit test for this, since it was apparently not captured.

**Review by gvardany — DISMISSED** [review]

File: Framework/Algorithms/src/SortXAxis.cpp (hunk 3 above)
Comment (Pasarus) [reply Framework/Algorithms/src/SortXAxis.cpp]: It was only ever captured in Debug builds, so a automated unit test wouldn't show this. If that is what you mean.

Comment (gvardany) [reply Framework/Algorithms/src/SortXAxis.cpp]: Thanks for adding the comment. I have hard time understanding how can this code change have effect only on debug builds. Can you elaborate more?

Comment (Pasarus) [reply Framework/Algorithms/src/SortXAxis.cpp]: I have not come across this on anything but Windows, Debug. Maybe @robertapplin can go into the detail as I do not remember the detail from his personal build investigation.

Comment (gvardany) [reply Framework/Algorithms/src/SortXAxis.cpp]: I think the logic expression can be simplified:
```
 const bool isAProperHistogram = ignoreHistogramValidation || determineIfHistogramIsValid(*inputWorkspace);
```

Comment (robertapplin) [reply Framework/Algorithms/src/SortXAxis.cpp]: I have only been able to replicate this on windows, debug mode. There was a vector subscript out-of-range error as the `workspaceIndices` vector was not having its largest value removed for a histogram workspace when `IgnoreHistogramValidation` was set to true. The reason why the same error doesn't occur on release mode I do not know.

**Comment by robertapplin** [comment]
@Pasarus @gvardany Are there any changes required?

**Review by Pasarus — APPROVED** [review]
