### PR TITLE
Changing the font on the script window causes crash

### LINKED ISSUE #19345: Changing script window font causes Mantid to crash
If I open the script window and choose window -> select font then Mantid crashes.

### PR DESCRIPTION
**Pull request by samueljackson92**
Fixed a bug which could cause Mantid to crash when choosing the font for the script window.

**To test:**
 - Check you can reproduce by opening the script window, then choosing window -> select font
 - Check these changes fix the issue.
 - Code review.

Fixes #19345 .

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by AntonPiccardoSelg** [comment]
I don't seem to be able to reproduce the crash on `Ubuntu` and `Windows` (even when no entry for `ScriptFontFamily` in `.config` or the `registry` is set). Having only briefly glanced over the code, it appears that QScintilla's lexer provides default fonts for the various operating system. 

Since I cannot reproduce the issue it might be better if someone with OSX tests this.

File: MantidPlot/src/MultiTabScriptInterpreter.cpp [hunk 1]
```diff
@@ -509,9 +509,12 @@ void MultiTabScriptInterpreter::showSelectFont() {
   if (database.families().contains(m_fontFamily))
     fontToUse = m_fontFamily;
 
-  QListWidgetItem *item = fontList->findItems(fontToUse, Qt::MatchExactly)[0];
-  fontList->setItemSelected(item, true);
-  fontList->scrollToItem(item, QAbstractItemView::PositionAtTop);
+  const auto results = fontList->findItems(fontToUse, Qt::MatchExactly);
+  if (results.size() > 0) {
```
Comment (soininen) [inline MantidPlot/src/MultiTabScriptInterpreter.cpp]: Wouldn't
```
if (!results.empty()) {
```
convey the intention better?

**Review by soininen — CHANGES_REQUESTED** [review]

File: MantidPlot/src/MultiTabScriptInterpreter.cpp [hunk 2]
```diff
@@ -510,7 +510,7 @@ void MultiTabScriptInterpreter::showSelectFont() {
     fontToUse = m_fontFamily;
 
   const auto results = fontList->findItems(fontToUse, Qt::MatchExactly);
-  if (results.size() > 0) {
+  if (results.empty()) {
```
Comment (soininen) [inline MantidPlot/src/MultiTabScriptInterpreter.cpp]: This seems to be missing `!`:
```
if (!results.empty()) {
```

**Review by soininen — CHANGES_REQUESTED** [review]

**Review by soininen — APPROVED** [review]

**Comment by soininen** [comment]
On my Ubuntu 14.04 system I can finally use Comic sans in the Python window. Nice work! :shipit:
