### PR TITLE
Automatic Bounding Boxes for Non-Axis-Aligned Shapes

### LINKED ISSUE #14349: Bounding box for hexahedron shape does not work
We recommend [to use boundingbox for hexahedron shape](http://docs.mantidproject.org/nightly/concepts/HowToDefineGeometricShape.html#howtodefinegeometricshape). 

A good example why is demonstrated by 

1. Run LoadEmptyInstrument with the IDF:
[templateSANS_Mantid.instr_without_boundingBox.txt](https://github.com/mantidproject/mantid/files/29820/templateSANS_Mantid.instr_without_boundingBox.txt)
2. Right-click on the created workshpace and select 'Show Instrument' 

then Mantid pops up the window

capture

which shows a ga ga bounding box has been created for the hexahedron shape. T0 fix this permanently, i.e. avoid having a user to worry about bounding box for this shape all-together fix this issue #9034 . 

However while that is being fixed in this issue fix a bug when a bounding box is specified for hexahedron shape. To reproduce:

1. Run LoadEmptyInstrument with the IDF: [templateSANS_Mantid.instr_with_boundingBox.txt](https://github.com/mantidproject/mantid/files/29823/templateSANS_Mantid.instr_with_boundingBox.txt) 
2. Right-click on the created workshpace and select 'Show Instrument' 

then observed that the default instrument view is awful, and you need to zoom a lot to get to see any of the components defined in the IDF including the hexahedron shape. 

For some reason bounding box in 
```
<type name="MonNDtype-0-pix-4" is="detector">
	<hexahedron id="hexapix-4">
		<left-back-bottom-point  x="-0.0166667" y="-0.0336398" z="0"  />
		<left-front-bottom-point x="-0.0166667" y="0.0349515" z="0"  />
		<right-front-bottom-point x="0.0166667" y="0.0349515" z="0"  />
		<right-back-bottom-point  x="0.0166667" y="-0.0362632" z="0"  />
		<left-back-top-point  x="-0.0166667" y="-0.0336398" z="-0.001"  />
		<left-front-top-point  x="-0.0166667" y="0.0349515" z="-0.001"  />
		<right-front-top-point  x="0.0166667" y="0.0349515" z="-0.001"  />
		<right-back-top-point   x="0.0166667" y="-0.0362632" z="-0.001"  />
	</hexahedron>
<bounding-box>
    <x-min val="-0.02"/>
    <x-max val="0.02"/>
    <y-min val="-0.04"/>
    <y-max val="0.04"/>
    <z-min val="-0.002"/>
    <z-max val="0.002"/>
  </bounding-box>
</type>
```
 
is not used properly

### PR DESCRIPTION
**Pull request by MikeHart85**
Fixes #14349 and #9034.

Release notes not yet updated.

This change expands Object::getBoundingBox() to support automatically calculating Axis-Aligned Bounding Boxes (AABB) for shapes that are not themselves axis-aligned. 

Previously, getBoundingBox would produce incorrect bounding boxes if a shape contained any surfaces that were not axis-aligned and required the user to provide explicit, manually calculated bounding boxes for all such shapes in the Instrument Definition File. This could be quite a hassle, especially since it was not always clear which shapes would require this for the instrument to show up correctly. 

All possible shapes should now be able to cope with creating their own bounding box automatically. It may still be useful to manually specify bounding boxes to speed up loading of particularly complex shapes.
### Testing

There is a small sample instrument that previously had issues provided in #14349.

It would also be good to check some of the existing instruments to ensure they still show up correctly, in particular if you remove the manual bounding boxes.

Some snippets that could be useful if you want to test specific shapes:

```
<cylinder id="dummy" >
    <centre-of-bottom-base x="0" y="0" z="0" />
    <axis x="-0.02" y="-0.02" z="0.3" />
    <radius val="0.005" />
    <height val="0.333333925927047" />
</cylinder >

<cone id="A" >
    <tip-point x="0.0" y="0.0" z="0" />
    <axis x="2" y="5" z="1" />
    <angle val="20.1" />
    <height val="0.1" />
</cone>

<sphere id="A">
    <centre x="0.0"  y="0.0" z="0.0" />
    <radius val="0.05" />
</sphere> 
```

More can be found on the [documentation page](http://docs.mantidproject.org/nightly/concepts/HowToDefineGeometricShape.html).

Note that the instrument view will only align correctly by default if your Axis View is set to `Z+`. A separate issue has been raised for this.

### CODE REVIEW

File: Framework/Geometry/src/Objects/Object.cpp [hunk 1]
```diff
@@ -1459,49 +1459,231 @@ double Object::ConeSolidAngle(const V3D &observer,
...
+  const_cast<Object *>(this)->calcBoundingBoxByVertices();
+  if (m_boundingBox.isNonNull())
+    return m_boundingBox;
+
+  // All options failed; give up
+  // Set to a large box so that a) we don't keep trying to calculate a box
+  // every time this is called and b) to serve as a visual indicator that
+  // something went wrong.
+  const_cast<Object *>(this)
+      ->defineBoundingBox(100, 100, 100, -100, -100, -100);
```
Comment (mantid-roman) [inline Framework/Geometry/src/Objects/Object.cpp]: Shouldn't 'huge' constant be used here?
