### PR TITLE
Set DetID before Q to prevent ray tracing when loading a peaks workspace

### LINKED ISSUE #19522: LoadNexusProcessed with a PeaksWorkspace is very slow
Loading a peaks workspace from a nexus file appears to be very slow. For me it takes almost 5 minutes to open a file with ~325 peaks and a WISH instrument. This should not be the case when the data being loaded is actually quite small.

### Expected behavior
Loading a nexus file with a peaks workspace should be fast

### Actual behavior
It's incredibly slow.

### Steps to reproduce the behavior
Run Load on the attached file.

[24954_allpeaksbyhand.nxs.zip](https://github.com/mantidproject/mantid/files/989101/24954_allpeaksbyhand.nxs.zip)

### Platforms affected
All.

### PR DESCRIPTION
**Pull request by samueljackson92**
This changes how LoadNexusProcessed creates a `Peak` object to set the detector ID before Q. This means that the peaks workspace will not perform ray tracing and will just use the data loaded from file.

**To test:**
There is a peaks workspace attached to the issue that you can use for testing. This is now also in the unit test data.

 - Try opening the file before applying changes. 
 - Go get a coffee. On my machine this took ~5 mins.
 - Try opening the file with the changes applied. It should take significantly less time.

Fixes #19522 .

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/DataHandling/src/LoadNexusProcessed.cpp [hunk 1]
```diff
@@ -1062,14 +1063,17 @@ API::Workspace_sptr LoadNexusProcessed::loadPeaksEntry(NXEntry &entry) {
...
+    // It is currently important (10/05/17) that the DetID (set in the loop
+    // below this one) is set before QLabFrame as this causes Peak to ray trace
+    // to find the location of the detector, which significantly increases
+    // loading times.
+    Geometry::IPeak *peak = new Peak();
+    const auto goniometer = peakWS->run().getGoniometer();
+    peak->setInstrument(peakWS->getInstrument());
+    peak->setGoniometerMatrix(goniometer.getR());
+    peak->setRunNumber(peakWS->getRunNumber());
+    peakWS->addPeak(*peak);
```
Comment (quantumsteve) [inline Framework/DataHandling/src/LoadNexusProcessed.cpp]: Should we add something like `void PeaksWorkspace::addPeak(Geometry::Peak &&peak)` to move, rather than copy, each `Peak`?

**Review by quantumsteve — CHANGES_REQUESTED** [review]

File: Framework/DataObjects/inc/MantidDataObjects/PeaksWorkspace.h [hunk 2]
```diff
@@ -94,6 +94,8 @@ class DLLExport PeaksWorkspace : public Mantid::API::IPeaksWorkspace {
   std::string getConvention() const override;
   void removePeak(int peakNum) override;
   void addPeak(const Geometry::IPeak &ipeak) override;
+  /// Move a peak object into this peaks workspace
+  void addPeak(Peak &&ipeak);
```
Comment (quantumsteve) [inline Framework/DataObjects/inc/MantidDataObjects/PeaksWorkspace.h]: If you make other changes, change the variable name here and in Peaksworkspace.cpp to `peak`.

Beyond that, I'll defer to the other reviews.

**Review by quantumsteve — APPROVED** [review]

**Comment by KarlPalmen** [comment]
Noting that two reviewers have been invited, but have not responded :shipit: .

**Comment by KarlPalmen** [comment]
Without the change, the file attached to the issue, took between 3 or 4 minutes to load. With the change it took a small number of seconds. (Windows 7)
