### PR TITLE
Disables users from deleting the last graph 

### LINKED ISSUE #6601: "Drag and Drop" Plotting Only Works When There is a Curve Present
This issue was originally [TRAC 5755](http://trac.mantidproject.org/mantid/ticket/5755)

To reproduce:

* Load a workspace and plot a spectrum.
* Drag and drop another workspace onto the graph and choose another spectrum to plot.  A second curve should appear.  This works fine and as expected.
* Now remove ''all'' the curves via the right-click menu.
* Try to drag and drop another workspace on to the graph - nothing happens.

Not sure if I'm missing something and this is intended functionality, but if we ''can'' display another curve via drag and drop in this situation then we probably ''should''.

### PR DESCRIPTION
**Pull request by shahrozahmed1**
Fixes #6601 

To Test: disabled the remove button when there is only one graph left, also created a pop message when user tries to delete the last graph using delete key

### CODE REVIEW

File: Code/Mantid/MantidPlot/src/CurvesDialog.cpp [hunk 1]
```diff
@@ -462,15 +477,21 @@ void CurvesDialog::removeCurves()
...
   d_graph->updatePlot();
 }
-
+//Enable Disable buttons function
 void CurvesDialog::enableAddBtn()
 {
   btnAdd->setEnabled (available->count()>0 && !available->selectedItems().isEmpty());
 }
 
+// enables or disables the button when appopriate number of graphs are in graph contents
```
Comment (DanNixon) [inline Code/Mantid/MantidPlot/src/CurvesDialog.cpp]: Could you use the same style of comments found [here](https://github.com/mantidproject/mantid/blob/master/Code/Mantid/Framework/Algorithms/src/Rebin.cpp#L33-L39), this will be picked up by Doxygen when the documentation is generated.

**Comment by FedeMPouzols** [comment]
Changes look good and this works better now. You cannot remove the last remaining curve, which prevents the user from getting into a no-end road, and circumvents the bug/strange behavior. Tested on debian. 

Just a couple of small things:
- I'd add a small note in the release notes. For example here: http://www.mantidproject.org/ReleaseNotes_3_5_UI_Changes, a bullet point in the list of "bugs resolved".
- I noticed that here you tended to use the same or similar comments in all your commits. I'd try to be a bit more specific, for your own benefit when you're trying to find some of the changes you did some days/weeks/months ago!

I also added the 'bugfix' label, as it seems to me that the old behavior was broken.

**Comment by FedeMPouzols** [comment]
Oops, @shahrozahmed1: I just realized that there's still  an issue here. Users can still remove several curves in one shot and they'll get the "empty plot". I've created a new issue and took the liberty to assign it to you, as you know well this part of the code.
