### PR TITLE
Fix No found object warning on Elwin Interface

### LINKED ISSUE #37770: Elwin unable to find Data Object error
**Description**
When adding data to the Elwin interface via the AddMultiWorkspaceDialog, it can sometimes show a message box with a similiar error to this

Image

after clicking "Add data". This happens even though you do not select that dataset in the dialog.

**To Replicate**
1. Open Inelastic->Data Processor interface
2. Go to Elwin tab
3. Click `Add workspaces`
4. Browse to first dataset (dataset A)
5. Select dataset A and click `Add Data`
6. Without closing the dialog, clear the ADS
7. Browse to a **different** dataset (dataset B)
8. Select dataset B and click `Add Data`
9. The warning in the screenshot will occur

Found on Windows, but likely to happen on all OS's.

### LINKED ISSUE #37787: Mantid crashes when trying to change preview plot on Elwin Interface
**Describe the bug**
Elwin interface has a preview plot widget that updates whenever the selected workspace on a QComboBox (just above the plot ) is changed, as well as when the spectrum of the selected workspace changes. 
The plot operation is tied to finding and retrieving the selected workspace from the ADS, if the ADS has been cleared before closing the Elwin interface, and one attempts to change the selected workspace, Mantid crashes. 

**To Reproduce**

1. Go to `Interfaces->Inelastic->Data Processor->Elwin`
2. Click on `Add Workspaces`. 
3. On the workspace selector dialog, click on `Browse`, navigate to the folder in which you have the ISIS Sample Data, and select the files `irs26174_graphite002_red` and `irs26176_graphite002_red`. Select both and click on `Add Data`, they should be added to the Elwin interface, and the plot update. 
4. Just above the plot widget, you should see a Combo box with two entries (one per workspace loaded). 
5. Without closing Elwin interface, clear the ADS. 
6. Back on the elwin interface, try to change the preview plot by changing the combo box entry. 
7. Mantid leaves the room. 

**Expected behavior**

Mantid shouldn't crash, if deleting the workspaces from the ADS makes the interface non-functional, the user should be warned. Ideally, the elwin interface shouldn't be tied to what happens on the ADS for plotting preview data. 

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: macOS, but probably all. 
 - OS Version:
 - Mantid Nightly

**Additional context**

### LINKED ISSUE #37788: Preview plot is updated incorrectly on Elwin Interface when changing spectrum.
**Describe the bug**

On the Elwin Interface, above the plot widget, there are two combo box widgets. One is used to select the preview workspace that is loaded onto the preview plot (if there is more than one workspace added to the Elwin data table). The other selects the spectrum from the workspace that will be plot. (see image)
image

The spectrum combo box has two bugs: 

 - When selecting any spectrum other than the spectrum number 0, it is not possible to plot the spectrum number 0 again. 
 - The spectrum number is retrieved incorrectly for plotting, it is taking the item index on the combobox rather than the number on the selected text. 

**To Reproduce**

1. Go to `Interfaces->Inelastic->Data Processor->Elwin`
2. Click on `Add Workspaces`. 
3. On the workspace selector dialog, click on `Browse`, navigate to the folder in which you have the ISIS Sample Data, and select the file `irs26174_graphite002_red`. The file will be on the dialog table. Click on the `Ws Index` column and type: `1-10,13`.  Click on `Add Data`. The spectra 1 to 10, and 13 should be added to the data table of the elwin interface.
4. Just above the plot widget, you should see a Combo box with one entry (`irs26174_graphite002...`). And on the spectrum combobox, you should see when you click the spectrum numbers 1 to 10 and 13. 
5. Try to preview plot spectrum number 5 by clicking on 5 on the spectrum combo box. 
6. Try to preview plot again spectrum number 0. You will see that the preview plot doesn't update. Updates to every number but not to spectrum number 0. 
7. Try to preview plot spectrum number 13. 
8. Go to the ADS, select the loaded workspace (`irs26174_graphite002_red`) and plot the spectrum with the index (not number) 13. You will see that it is not the same as the one on the preview plot of the elwin interface. 

**Expected behavior**

The combobox retrieves all preview workspace (including 0) with the correct spectrum index. 
**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: macOS, but applicable to all.
 - OS Version:
 - Mantid Nightly

**Additional context**

### PR DESCRIPTION
**Pull request by adriazalvarez**
### Description of work
This PR fixes issue #37770 and other related issues: #37787 and #37788. All three issues are related to the underlying problem of trying to retrieve loaded workspaces onto the elwin interface from the ADS. If for some reason the data on the ADS is modified, the interface tries to retrieve workspaces that don't exist, and depending on the actions on the interface can either crash mantid #37787 or give a warning #37770.  
Additionally, the preview plot is chosen by selecting the workspace to plot and the spectrum index on that workspace from two comboboxes. The spectrum combobox was not retrieving the correct index number, and could not plot spectrum number 0. 

#### Summary of work

I have tried to refactor the Elwin Presenter and Elwin View classes to handle better the communication between view and presenter, and to reduce dependencies with the ADS. The elwin presenter already stores copies of the loaded workspaces in their data model, and it's not necessary to retrieve workspaces from the ADS in order to plot data.
Also, Elwin interface used to have a way to load data through a file finder or through a workspace dialog , but this was removed in #36953 in favor of a multiple file workspace dialog. So there are functions on the presenter and view that are not needed anymore, I have tried to remove these as well.

Fixes #37770, #37787, #37788 

### To test:

 - Check that the test instructions for the issues #37770, #37787, #37788 are not happening anymore. 
 - Follow manual testing instructions for elwin tab: https://developer.mantidproject.org/Testing/Inelastic/DataProcessorTests.html . See there are no issues when running the instructions.
 

*Added release notes*

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by adriazalvarez** [comment]
@GuiMacielPereira , I think I have found a potential problem here while I was working on another PR. I will put i back on draft for the moment. Sorry for the trouble!

**Comment by GuiMacielPereira** [comment]
No worries, it's looking good.

File: qt/scientific_interfaces/Inelastic/Processor/ElwinView.cpp [hunk 1]
```diff
@@ -205,6 +205,14 @@ void ElwinView::addTableEntry(int row, std::string const &name, std::string cons
   setCell(std::move(cell), row, 1);
 }
 
+void ElwinView::updatePreviewWorkspaceNames(const std::vector<std::string> &names) {
+  disconnectSignals();
```
Comment (GuiMacielPereira) [inline qt/scientific_interfaces/Inelastic/Processor/ElwinView.cpp:209]: Uhm I noticed that if you remove `disconnectSignals` and `connectSignals` here, then the preview box triggers the signal `currentIndexChanged(int)` which in turn calls the slot `notifyPreviewIndexChanged` which calls the handler `handlePreviewIndexChanged` which will call the function that sets the input workspace `setInputWorkspace(workspace)` and other very useful stuff like plot inputs. This means that then you don't need to call `setInputWorkspace(workspace)` inside `newInputDataFromDialog()`. 

So you can have the function `newInputDataFromDialog()` call only `m_view->updatePreviewWorkspaceNames` and from then onward everything is handled by a chain of signals and slots

I have tried this and everything seems to work fine when a new workspace is added. I am only suggesting because I think it would be a bit cleaner this way.

File: qt/scientific_interfaces/Inelastic/Processor/ElwinPresenter.cpp [hunk 2]
```diff
@@ -140,12 +140,13 @@ void ElwinPresenter::handleValueChanged(std::string const &propName, bool value)
...
+  m_view->updatePreviewWorkspaceNames(m_dataModel->getWorkspaceNames());
 
-  std::string const wsname = m_view->getPreviewWorkspaceName(0);
-  auto const inputWs = WorkspaceUtils::getADSWorkspace(wsname);
-  setInputWorkspace(inputWs);
+  // sets last added workspace as input workspace
+  auto const lastAddedWSIndex = m_dataModel->getNumberOfWorkspaces() - 1;
+  m_view->setPreviewWorkspaceName(static_cast<int>(lastAddedWSIndex.value));
+  auto lastAddedWS = m_dataModel->getWorkspace(lastAddedWSIndex);
+  setInputWorkspace(lastAddedWS);
```
Comment (GuiMacielPereira) [inline qt/scientific_interfaces/Inelastic/Processor/ElwinPresenter.cpp:149]: This is the section that I think you could remove, because its a bit confusing and I think it could be handled anyway by signals and slots. See my comment below

File: qt/scientific_interfaces/Inelastic/Processor/ElwinView.cpp [hunk 3]
```diff
@@ -205,6 +205,14 @@ void ElwinView::addTableEntry(int row, std::string const &name, std::string cons
...
+  m_uiForm.cbPreviewFile->clear();
+  m_uiForm.cbPreviewFile->addItems(stdVectorToQStringList(names));
+  m_uiForm.cbPreviewFile->setCurrentIndex(0);
```
Comment (GuiMacielPereira) [inline qt/scientific_interfaces/Inelastic/Processor/ElwinView.cpp:212]: If you set this line to something like

```suggestion
  m_uiForm.cbPreviewFile->setCurrentIndex(names.size() - 1);
```
Then that should trigger the correct signal

**Review by GuiMacielPereira — CHANGES_REQUESTED** [review]
I know you're still working on it, but when I looked into it a bit today I had these suggestions so I am going to leave them here just in case.

File: qt/scientific_interfaces/Inelastic/Processor/ElwinView.cpp (hunk 1 above)
Comment (adriazalvarez) [reply qt/scientific_interfaces/Inelastic/Processor/ElwinView.cpp:209]: Thanks for picking this up.

**Review by GuiMacielPereira — DISMISSED** [review]
The code is much easier to follow and the addition of observers fixes the faulty interactions between the ADS and the data model.

For testing manually, I tried to delete a workspace in the ADS, do a clear() of the ADS and rename a workspace in the ADS, which triggered the correct reactions in the Elwin interface. 

Within the interface I also checked that adding any new data correctly updates the  combo boxes for the workspace preview and the spectra preview, as well as the plot of the spectra selected. Everything is working as expected.

Followed through most of the testing instructions with no problems.

File: qt/scientific_interfaces/Inelastic/Processor/ElwinPresenter.h [hunk 4]
```diff
@@ -68,35 +71,47 @@ class MANTIDQT_INELASTIC_DLL ElwinPresenter : public DataProcessor, public IElwi
...
   std::unique_ptr<IElwinModel> m_model;
   std::unique_ptr<IDataModel> m_dataModel;
   int m_selectedSpectrum;
   std::weak_ptr<MatrixWorkspace> m_previewPlotWorkspace;
   MatrixWorkspace_sptr m_inputWorkspace;
+
+  /// Poco Observers for ADS Notifications
+  Poco::NObserver<ElwinPresenter, Mantid::API::WorkspacePreDeleteNotification> m_remObserver;
+  Poco::NObserver<ElwinPresenter, Mantid::API::ClearADSNotification> m_clearObserver;
+  Poco::NObserver<ElwinPresenter, Mantid::API::WorkspaceRenameNotification> m_renameObserver;
```
Comment (robertapplin) [inline qt/scientific_interfaces/Inelastic/Processor/ElwinPresenter.h:114]: Would it be possible to get the Presenter to inherit the `AnalysisDataServiceObserver` class and implement the relevant functions so we can avoid using `Poco` in these files? https://github.com/mantidproject/mantid/blob/50916dd41b7bfd467d17aa50d8546998aec951d0/Framework/API/inc/MantidAPI/AnalysisDataServiceObserver.h#L38

File: qt/scientific_interfaces/Inelastic/Processor/ElwinPresenter.cpp [hunk 5]
```diff
@@ -309,22 +297,24 @@ void ElwinPresenter::handleRemoveSelectedData() {
...
-  m_view->setAvailableSpectra(spectra.begin(), spectra.end());
+  if (auto const wsID = findWorkspaceID(m_view->getCurrentPreview()); wsID) {
+    auto const spectra = m_dataModel->getSpectra(*wsID);
+    m_view->setAvailableSpectra(spectra.begin(), spectra.end());
+  }
 }
 
-WorkspaceID ElwinPresenter::findWorkspaceID() {
-  auto currentWorkspace = m_view->getCurrentPreview();
+std::optional<WorkspaceID> ElwinPresenter::findWorkspaceID(std::string const &name) const {
```
Comment (robertapplin) [inline qt/scientific_interfaces/Inelastic/Processor/ElwinPresenter.cpp:312]: Nice use of std::optional!

**Review by robertapplin — CHANGES_REQUESTED** [review]
This is a huge improvement, thanks for your careful attention fixing these problems! I just had one question, about possibly using the AnalysisDataServiceObserver class

File: qt/scientific_interfaces/Inelastic/Processor/ElwinPresenter.h (hunk 4 above)
Comment (adriazalvarez) [reply qt/scientific_interfaces/Inelastic/Processor/ElwinPresenter.h]: I was not aware of this class. Thanks for the tip.

File: qt/scientific_interfaces/Inelastic/Processor/ElwinPresenter.h [hunk 6]
```diff
@@ -68,28 +74,38 @@ class MANTIDQT_INELASTIC_DLL ElwinPresenter : public DataProcessor, public IElwi
...
   bool checkForELTWorkspace();
-  void newPreviewFileSelected(const std::string &workspaceName, const std::string &filename);
-  void newPreviewWorkspaceSelected(const std::string &workspaceName);
-  WorkspaceID findWorkspaceID();
+  void newPreviewWorkspaceSelected(int index);
+  std::optional<WorkspaceID> findWorkspaceID(std::string const &name) const;
+
+  void handleRemoveEvent(Mantid::API::WorkspacePreDeleteNotification_ptr pNf);
+  void handleClearEvent(Mantid::API::ClearADSNotification_ptr pNf);
+  void handleRenameEvent(Mantid::API::WorkspaceRenameNotification_ptr pNf);
```
Comment (GuiMacielPereira) [inline qt/scientific_interfaces/Inelastic/Processor/ElwinPresenter.h:108]: Did you forget to remove these old handlers?

Comment (adriazalvarez) [reply qt/scientific_interfaces/Inelastic/Processor/ElwinPresenter.h]: Yes. thank you.

**Review by GuiMacielPereira — APPROVED** [review]
Did the manual testing again: checked that deleting, renaming and clearing the workspaces in the ADS triggers the deletion of the workspaces on the Elwin interface. 
The workspace preview and the spectrum preview comboboxes are working correctly.

Code looks good and is clearer to follow.

**Review by robertapplin — APPROVED** [review]
