### PR TITLE
Save Nexus from the Workspace Dock will now properly run SaveMD for MD Workspaces

### LINKED ISSUE #17345: Save to Nexus file doesn't handle MD workspace properly
It is not possible to save an MD workspace from the mantid plot GUI.
Trying to save an MD workspace from the GUI using the save-> ASCII will bring up a `MantidPlot has caught an unexpected exception` Dialog box.
SaveNexus will fail and write an error to the log
It would be more appropriate if the Save button changed to a `SaveMD` button when an MDworkspace is selected

### PR DESCRIPTION
**Pull request by dtasev**
## Description of work.

`Save` > `Nexus` from the Workspaces Dock menus will now properly run `SaveMD` to save MD workspaces instead of trying to run `SaveNexus` on them and then fail. Now there is a check to see if the workspace is MD, and if so it will run `SaveMD`. However currently picking Save to `ASCII` or `ASCII v1` will still run `SaveMD` basically overwriting the user's choice. This shouldn't be an issue because `SaveASCII` doesn't work with MD workspaces anyway, however it might be confusing.
## To test:

MD Workspaces -> `SEQ_MDEW` or `SEQ_MDHW` from build testing data, or on Olympic `Public\DimitarTasev`
- [x] Test 2D Workspaces, functionality should be unchanged for all options, Save > Nexus, ASCII, ASCII v1, and all workspace types
- [x] Test MD Workspace (Event and Histogram)
- Load a MD Workspace into mantid
- From the Save button above (in the Workspaces Dock) click Save > Nexus
- It _should_ save successfully

Fixes #17345.

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: MantidPlot/src/Mantid/MantidDock.cpp [hunk 1]
```diff
@@ -19,6 +21,7 @@
 #include <MantidQtAPI/InterfaceManager.h>
 
 #include <Poco/Path.h>
+#include <boost/shared_ptr.hpp>
```
Comment (DavidFair) [inline MantidPlot/src/Mantid/MantidDock.cpp]: Is this include needed as we have `std::shared_pointer` in `<memory>`

File: MantidPlot/src/Mantid/MantidDock.cpp [hunk 2]
```diff
@@ -928,28 +931,42 @@ void MantidDockWidget::saveWorkspacesToFolder(const QString &folder) {
  * most recent version.
  */
 void MantidDockWidget::handleShowSaveAlgorithm() {
-  QAction *sendingAction = dynamic_cast<QAction *>(sender());
+  const QAction *sendingAction = dynamic_cast<QAction *>(sender());
 
   if (sendingAction) {
-    QString wsName = getSelectedWorkspaceName();
-    QVariant data = sendingAction->data();
+    auto inputWorkspace = getSelectedWorkspace();
```
Comment (DavidFair) [inline MantidPlot/src/Mantid/MantidDock.cpp]: Is it possible to make this `const auto`

File: MantidPlot/src/Mantid/MantidDock.cpp [hunk 3]
```diff
@@ -928,28 +931,42 @@ void MantidDockWidget::saveWorkspacesToFolder(const QString &folder) {
...
-        version = splitData[1].toInt();
-      case 1:
-        algorithmName = splitData[0];
-        break;
-      default:
-        m_mantidUI->saveNexusWorkspace();
-        return;
-      }
+      // Check if workspace is MD, this is the same check used in
+      // SaveNexusProcessed.cpp line 175 to determine if the WS is MD
```
Comment (DavidFair) [inline MantidPlot/src/Mantid/MantidDock.cpp]: As line numbers change could you put the function name instead

File: MantidPlot/src/Mantid/MantidDock.cpp [hunk 4]
```diff
@@ -928,28 +931,42 @@ void MantidDockWidget::saveWorkspacesToFolder(const QString &folder) {
...
+        // v1, therefore overwriting their choice and running
+        // SaveMD. SaveASCII doesn't support MD Workspaces, but if an issue,
+        // move the MD check to case 1: below
+        algorithmName = "SaveMD";
 
+      } else {
+        QStringList splitData = data.toString().split(".");
+        switch (splitData.length()) {
+        case 2:
+          version = splitData[1].toInt();
```
Comment (DavidFair) [inline MantidPlot/src/Mantid/MantidDock.cpp]: Can we add a comment saying that this case is meant to be missing a `break` statement (looking at the existing code)

File: MantidPlot/src/Mantid/MantidUI.cpp [hunk 5]
```diff
@@ -1456,7 +1453,11 @@ QStringList MantidUI::extractPyFiles(const QList<QUrl> &urlList) const {
 }
 
 /**
-executes Save Nexus
+Executes the Save Nexus dialogue from the right click context menu.
+
+The Save > Nexus function from the button in the Dock (with Load, Delete, Group,
+Sort, Save buttons) is in MantidDock at line 933
```
Comment (DavidFair) [inline MantidPlot/src/Mantid/MantidUI.cpp]: ^ See above - could we use a function name instead of line number

**Comment by DavidFair** [comment]
This fixes the issues we were seeing - :shipit: when the last test finishes

**Review by DavidFair — APPROVED** [review]
