### PR TITLE
Indirect - Fix Missing Logs in Edit Local Fit Parameters Dialog

### LINKED ISSUE #29802: Indirect - Logs are missing from Edit Fit Parameters Dialog
### Expected behavior
The `Logs` should be available for selecting in the `Edit Fit Parameters` dialog when use logs is ticked.

### Actual behavior
In indirect data analysis, the logs are missing from the `Edit Fit Parameters` dialog. The combobox is empty.

### Steps to reproduce the behavior
1. `Interfaces`->`Indirect`->`Data Analysis`
2. Go to `IqtFit` tab
3. Load the data below
4. Select Simultaneous Fit
5. Select 1 exponential
6. Tick `See Full Function`
7. Click the `...` box next to one of the parameters
8. The Logs are missing from the combobox at the bottom of the dialog.

**Data**
[irs26176_graphite002_iqt.zip](https://github.com/mantidproject/mantid/files/5428108/irs26176_graphite002_iqt.zip)

### Platforms affected
Found on windows, probably all.

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR fixes an issue in Indirect Data Analysis where the logs were not being loaded in the `Edit Local Fit Parameters` dialog.

This is because the `FunctionModel` assumes a dataset (i.e. workspace) contains only one spectrum to be fitted. This is true for Muon Analysis it seems, but not for Indirect.

To fix this, the `FunctionModel` now stores a QMap containing workspace names and the spectra corresponding to these workspaces. Making this change allows the retrieval of dataset names and domain names from the `FunctionModel`. By using both of these, sample logs for multi-spectra workspaces can now be loaded by the `Edit Local Fit Parameters` dialog.

**To test:**
1. `Interfaces`->`Indirect`->`Data Analysis`
2. Go to `IqtFit` tab
3. Load the data below
4. Select Simultaneous Fit
5. Select 1 exponential
6. Tick `See Full Function`
7. Click the `...` box next to one of the parameters
8. The Log names should be loaded in the combobox at the bottom of the dialog.

**Data**
[irs26176_graphite002_iqt.zip](https://github.com/mantidproject/mantid/files/5428108/irs26176_graphite002_iqt.zip)

Make sure you can add and remove datasets OK on the Muon Analysis interface.

Fixes #29802

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by Harrietbrown — DISMISSED** [review]
The sample logs now appear in the fit paramiters in indirect tabs. The tests look good. Good job

File: qt/scientific_interfaces/Indirect/FunctionTemplateBrowser.h [hunk 1]
```diff
@@ -48,7 +50,8 @@ class MANTIDQT_INDIRECT_DLL FunctionTemplateBrowser : public QWidget {
   virtual IFunction_sptr getFunction() const = 0;
   virtual void setNumberOfDatasets(int) = 0;
   virtual int getNumberOfDatasets() const = 0;
-  virtual void setDatasetNames(const QStringList &names) = 0;
+  virtual void
+  setDatasets(const QList<QPair<QString, QList<std::size_t>>> &datasets) = 0;
```
Comment (martyngigg) [inline qt/scientific_interfaces/Indirect/FunctionTemplateBrowser.h:54]: The nested types are a little difficult to parse and have to be duplicated in quite a few places. At minimum I think a few `using` statements would help to give some types better names:

```
using Spectra = QList<std::size_t>;  // should this be using the spectrum types defined? 
using Dataset = QPair<QString, Spectra>;
```
then `QList<Dataset>` can be used in the function definition or even.

At this level I would also consider whether there is a class or two we are missing rather than using fundamental types?

**Review by martyngigg — CHANGES_REQUESTED** [review]

File: qt/scientific_interfaces/Indirect/FunctionTemplateBrowser.h (hunk 1 above)
Comment (robertapplin) [reply qt/scientific_interfaces/Indirect/FunctionTemplateBrowser.h:54]: I had the same thought, and I think we are missing some fundamental types.

I am aware that Indirect has a `Spectra` class but I find it to be overly complex for what it should be doing. I think I will define a `Spectra` class and `Dataset` class like you suggested, unless you know of any existing classes which already exist which just need to be incorporated?

Comment (martyngigg) [reply qt/scientific_interfaces/Indirect/FunctionTemplateBrowser.h:54]: I really picked that name as a guess that it was a collection of spectrum ids? How does the current Spectra class work - we should be careful about duplicating things.

Comment (robertapplin) [reply qt/scientific_interfaces/Indirect/FunctionTemplateBrowser.h:54]: Yes its just a list of spectrum numbers which we want to fit from a workspace.

The indirect `Spectra` class seems to do quite a lot, but might be useful I guess .https://github.com/mantidproject/mantid/blob/f8512fdfa6b66a54fdd9bb3dd1ec7f16c3ff82d8/qt/scientific_interfaces/Indirect/IndirectFitData.h#L32 
 What do you think?

Comment (robertapplin) [reply qt/scientific_interfaces/Indirect/FunctionTemplateBrowser.h]: @martyngigg The indirect `Spectra` class works fine it seems. I have moved this class into its own file and placed it in the same directory as the `FunctionModel`, and I did the same with `IndexTypes`. I did this because they are general classes that could be useful outside of indirect. Let me know if you can think of a better location for these files

**Comment by robertapplin** [comment]
@Harrietbrown please could you take another quick look to make sure everything is still working as expected?

**Review by Harrietbrown — DISMISSED** [review]
The log details are still now present in the fitparameters dialogue.

File: qt/widgets/common/inc/MantidQtWidgets/Common/FunctionModelDataset.h [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+#include "MantidQtWidgets/Common/Spectra.h"
+
+#include <QList>
+#include <QString>
+#include <QStringList>
+
+namespace MantidQt {
+namespace MantidWidgets {
+
+struct EXPORT_OPT_MANTIDQT_COMMON Dataset {
```
Comment (martyngigg) [inline qt/widgets/common/inc/MantidQtWidgets/Common/FunctionModelDataset.h:19]: Thanks for putting in the changes in around this. Can I ask we rename this as `Dataset` is a bit of a overloaded term w.r.t to mantid and other things like [scipp](https://scipp.github.io/).

I noticed the header is called `FunctionModelDataset` - can we use this name?

Comment (martyngigg) [reply qt/widgets/common/inc/MantidQtWidgets/Common/FunctionModelDataset.h:19]: Can we also add some class documentation just describing the intention of the type?

File: qt/widgets/common/inc/MantidQtWidgets/Common/FunctionModelDataset.h [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+public:
+  Dataset(const QString &workspaceName, const Spectra &spectra);
+
+  QString datasetName() const;
```
Comment (martyngigg) [inline qt/widgets/common/inc/MantidQtWidgets/Common/FunctionModelDataset.h:23]: Perhaps inline this and mark it `noexcept`?

File: qt/widgets/common/inc/MantidQtWidgets/Common/FunctionModelDataset.h [hunk 4]
```diff
@@ -0,0 +1,34 @@
...
+  QStringList domainNames() const;
+
+  std::size_t numberOfSpectra() const;
```
Comment (martyngigg) [inline qt/widgets/common/inc/MantidQtWidgets/Common/FunctionModelDataset.h:26]: Perhaps `inline` this and mark it `noexcept`?

File: qt/widgets/common/src/FunctionModelDataset.cpp [hunk 5]
```diff
@@ -0,0 +1,37 @@
...
+//   Institut Laue - Langevin & CSNS, Institute of High Energy Physics, CAS
+// SPDX - License - Identifier: GPL - 3.0 +
+#include "MantidQtWidgets/Common/FunctionModelDataset.h"
+
+#include <stdexcept>
+
+namespace MantidQt {
+namespace MantidWidgets {
+
+Dataset::Dataset(const QString &workspaceName, const Spectra &spectra)
```
Comment (martyngigg) [inline qt/widgets/common/src/FunctionModelDataset.cpp:14]: As we are copying the two parameters in here it's generally accepted that it can be better to either add an r-value reference overload or take by value. We could take the advantage here that QString is copy on write and just add an overload:

```cpp
Dataset::Dataset(QString workspaceName, Spectra &&spectra) : 
  : m_workspaceName(workspaceName), m_spectra(std::move(spectra)) {}
```
to accept an r-value reference of the spectra and it could avoid copying on construction.

File: qt/widgets/common/src/FunctionModelDataset.cpp [hunk 6]
```diff
@@ -0,0 +1,37 @@
...
+    : m_workspaceName(workspaceName), m_spectra(spectra) {}
+
+QString Dataset::datasetName() const { return m_workspaceName; }
```
Comment (martyngigg) [inline qt/widgets/common/src/FunctionModelDataset.cpp:17]: Could we add some function documentation for all of these methods?

**Review by martyngigg — CHANGES_REQUESTED** [review]
Thanks for making these changes. It makes things easier to follow.

Just a couple of general comments on the new type.

File: qt/widgets/common/inc/MantidQtWidgets/Common/Spectra.h [hunk 7]
```diff
@@ -0,0 +1,104 @@
...
+namespace MantidQt {
+namespace MantidWidgets {
+
+/*
+ * Representation of a discontinuous spectra range.
+ * Can be used in a vector-like manner.
+ *
+ * Holds a string and vector representation.
+ */
+class EXPORT_OPT_MANTIDQT_COMMON Spectra {
```
Comment (martyngigg) [inline qt/widgets/common/inc/MantidQtWidgets/Common/Spectra.h:30]: Sorry that I didn't spot this the first time but as we have renamed DataSet, and this has Fit-related things in it, can we revert this name back to `FunctionModelSpectra`?

**Review by martyngigg — CHANGES_REQUESTED** [review]

**Comment by robertapplin** [comment]
Thanks @martyngigg , ready for another look

**Review by martyngigg — APPROVED** [review]
