### PR TITLE
Check for whitespace only strings

### LINKED ISSUE #22002: Sample Transmission Calculator Interface crashes when given a whitespace chemical formula.
### Expected behaviour
The calculator should provide a warning in the results log or as a dialog.

### Actual behaviour
We get the generic uncaught exception message.

### Steps to reproduce the behaviour
1. Open the Sample Transmission Calculator `Interfaces > General > Sample Transmission Calculator`
2. Set the Low, Width and High parameters to sensible values e.g. 0.2, 0.1, 0.5.
3. Set the chemical formula to one or more spaces. e.g `  `
4. Press calculate.
5. `Unexpected exception: Invalid value for property ChemicalFormula (string) "  ": A value must be entered for this parameter.`

### Platforms affected
Tested on Fedora 27, Probably All

### PR DESCRIPTION
**Pull request by Pasarus**
**Description of work.**
Modified check field is not empty in UserInputValidator

**Report to:** nobody  

**To test:** 

1. Open the Sample Transmission Calculator `Interfaces > General > Sample Transmission Calculator`
2. Set the Low, Width and High parameters to sensible values e.g. 0.2, 0.1, 0.5.
3. Set the chemical formula to one or more spaces. e.g `  `
4. Press calculate.
5. Ensure you get the appropriate error message and not: `Unexpected exception: Invalid value for property ChemicalFormula (string) "  ": A value must be entered for this parameter.`
6. Repeat with a sensible formula e.g. `C1`

Fixes #22002  

Does this update require release notes?
- [ ] Yes
- [x] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by edwardb96 — APPROVED** [review]
:+1:

File: qt/scientific_interfaces/General/UserInputValidator.cpp [hunk 1]
```diff
@@ -38,7 +38,7 @@ UserInputValidator::UserInputValidator() : m_errorMessages() {}
 bool UserInputValidator::checkFieldIsNotEmpty(const QString &name,
                                               QLineEdit *field,
                                               QLabel *errorLabel) {
-  if (field->text() == "") {
+  if (Mantid::Kernel::Strings::isEmpty(field->text().toStdString())) {
```
Comment (martyngigg) [inline qt/scientific_interfaces/General/UserInputValidator.cpp]: Perhaps use Qt functionality when it's available and we're already in Qt land?:`text().trimmed().isEmpty()`?

Comment (Pasarus) [reply qt/scientific_interfaces/General/UserInputValidator.cpp]: Yeah that looks like a better alternative I'll get that updated now. Didn't think of that at the time.

File: qt/scientific_interfaces/General/UserInputValidator.cpp [hunk 2]
```diff
@@ -1,10 +1,10 @@
 #include "UserInputValidator.h"
+#include "MantidKernel/Strings.h"
```
Comment (martyngigg) [inline qt/scientific_interfaces/General/UserInputValidator.cpp]: Nearly there :)

I don't think we need this include anymore?

**Comment by Pasarus** [comment]
Updated to include suggestions.

**Review by martyngigg — APPROVED** [review]
