### PR TITLE
Fix clang-tidy warnings in DTRSMinimizer.

### LINKED ISSUE #16728: warnings from DTRSMinimizer.cpp
Clang-tidy reported new warnings about several places where a value is stored but never read. This appears to come from PR #16663. They look legitimate, but I'm not familiar with the larger context. Would you mind taking a look?

http://builds.mantidproject.org/view/Static%20Analysis/job/clang_tidy/235/warnings13Result/

```
DTRSMinimizer.cpp:346, Clang (LLVM based), Priority: Normal
Value stored to 'p' is never read

DTRSMinimizer.cpp:353, Clang (LLVM based), Priority: Normal
Value stored to 'p' is never read

DTRSMinimizer.cpp:600, Clang (LLVM based), Priority: Normal
Value stored to 'lambda' is never read

DTRSMinimizer.cpp:602, Clang (LLVM based), Priority: Normal
Value stored to 'lambda' is never read

DTRSMinimizer.cpp:734, Clang (LLVM based), Priority: Normal
Value stored to 'lambda_l' is never read

DTRSMinimizer.cpp:736, Clang (LLVM based), Priority: Normal
Value stored to 'lambda_u' is never read
```

### PR DESCRIPTION
**Pull request by mantid-roman**
Fixed the reported clang-tidy and coverity warnings in the new minimizer code.

**To test:**

Code review.

Fixes #16728 .

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/CurveFitting/src/FuncMinimizers/DTRSMinimizer.cpp [hunk 1]
```diff
@@ -592,14 +590,11 @@ void dtrs_solve_main(int n, double radius, double f,
         if (h(i) == lambda_min) {
           i_hard = i;
           break;
-        };
+        }
       }
       x(i_hard) = one / radius;
       inform.x_norm = radius;
       inform.obj = f + lambda_min * radius * radius;
-      lambda = -lambda_min;
```
Comment (SimonHeybrock) [inline Framework/CurveFitting/src/FuncMinimizers/DTRSMinimizer.cpp]: Why can this line be removed?

Comment (mantid-roman) [inline Framework/CurveFitting/src/FuncMinimizers/DTRSMinimizer.cpp]: Because it is followed by `return`.

File: Framework/CurveFitting/inc/MantidCurveFitting/RalNlls/TrustRegion.h [hunk 2]
```diff
@@ -19,19 +19,19 @@ void mult_Jt(const DoubleFortranMatrix &J, const DoubleFortranVector &x,
...
                       const DoubleFortranMatrix &hf,
-                      const DoubleFortranVector &d, const nlls_options options,
+                      const DoubleFortranVector &d, const nlls_options &options,
                       evaluate_model_work &w);
 double calculate_rho(double normf, double normfnew, double md,
                      const nlls_options &options);
 void update_trust_region_radius(double &rho, const nlls_options &options,
                                 nlls_inform &inform, NLLS_workspace &w);
-void rank_one_update(DoubleFortranMatrix &hf, NLLS_workspace w);
+void rank_one_update(DoubleFortranMatrix &hf, NLLS_workspace &w);
```
Comment (SimonHeybrock) [inline Framework/CurveFitting/inc/MantidCurveFitting/RalNlls/TrustRegion.h]: `const` reference?

File: Framework/CurveFitting/inc/MantidCurveFitting/RalNlls/TrustRegion.h [hunk 3]
```diff
@@ -19,19 +19,19 @@ void mult_Jt(const DoubleFortranMatrix &J, const DoubleFortranVector &x,
...
 void test_convergence(double normF, double normJF, double normF0,
                       double normJF0, const nlls_options &options,
                       nlls_inform &inform);
 void apply_scaling(const DoubleFortranMatrix &J, DoubleFortranMatrix &A,
                    DoubleFortranVector &v, apply_scaling_work &w,
-                   const nlls_options options, nlls_inform inform);
+                   const nlls_options &options, nlls_inform &inform);
```
Comment (SimonHeybrock) [inline Framework/CurveFitting/inc/MantidCurveFitting/RalNlls/TrustRegion.h]: `const` reference?

File: Framework/CurveFitting/src/FuncMinimizers/DTRSMinimizer.cpp (hunk 1 above)
Comment (SimonHeybrock) [inline Framework/CurveFitting/src/FuncMinimizers/DTRSMinimizer.cpp]: Right, I missed that :)

File: Framework/CurveFitting/inc/MantidCurveFitting/RalNlls/TrustRegion.h (hunk 3 above)
Comment (mantid-roman) [inline Framework/CurveFitting/inc/MantidCurveFitting/RalNlls/TrustRegion.h]: `options` is `const`, `inform` is non-const, it's an output.

File: Framework/CurveFitting/inc/MantidCurveFitting/RalNlls/TrustRegion.h (hunk 2 above)
Comment (mantid-roman) [inline Framework/CurveFitting/inc/MantidCurveFitting/RalNlls/TrustRegion.h]: They are `in-out` arguments.

Comment (SimonHeybrock) [inline Framework/CurveFitting/inc/MantidCurveFitting/RalNlls/TrustRegion.h]: But previously `w` was passed by-value, how can it be on in-out argument?

Comment (mantid-roman) [inline Framework/CurveFitting/inc/MantidCurveFitting/RalNlls/TrustRegion.h]: That was a typo. The code is a translation from fortran.

Comment (SimonHeybrock) [inline Framework/CurveFitting/inc/MantidCurveFitting/RalNlls/TrustRegion.h]: So does this fix a bug then? It seems to be used in a few places via `TrustRegionMinimizer`, so I guess this should be tested and in the release notes?

Comment (mantid-roman) [inline Framework/CurveFitting/inc/MantidCurveFitting/RalNlls/TrustRegion.h]: I think this affected only performance. `NLLS_workspace` contains pre-allocated helper objects: matrices and vectors and is passed to various functions just to provide temporaries. It's a usual fortran way of doing things. I haven't figured it out yet how to make it the C++ way.

Comment (SimonHeybrock) [inline Framework/CurveFitting/inc/MantidCurveFitting/RalNlls/TrustRegion.h]: The convergence test in `TrustRegionMinimizer::iterate` seems to depend on it. It seems the change here is correct, and it might fix a previously broken minimizer, but I am not really sure.

I think this should be refactored as part of another issue, could you please create one? Also tests should be added, mention in particular to verify what we discussed here.

Apart from that probably :shipit:, but a second look at the minimizers from someone who knows what is going on there would be good.

Comment (mantid-roman) [inline Framework/CurveFitting/inc/MantidCurveFitting/RalNlls/TrustRegion.h]: The authors of the original fortran code are currently reviewing my translation. Opened issue #16748 to clean up the code.

File: Framework/CurveFitting/src/FuncMinimizers/DTRSMinimizer.cpp [hunk 4]
```diff
@@ -343,14 +343,12 @@ void roots_quadratic(double a0, double a1, double a2, double tol, int &nroots,
     auto pprime = two * a2 * root1 + a1;
     if (pprime != zero) {
       root1 = root1 - p / pprime;
-      p = (a2 * root1 + a1) * root1 + a0;
```
Comment (FedeMPouzols) [inline Framework/CurveFitting/src/FuncMinimizers/DTRSMinimizer.cpp]: These no-effect lines look like there were some minor inconsistencies/leftovers/missing bits in the original code. It would be good if the SCD guys have a look at this.

Comment (mantid-roman) [inline Framework/CurveFitting/src/FuncMinimizers/DTRSMinimizer.cpp]: I think the original code contained loops and `p` was updated on each iteration after the `root` was updated. They removed the loop, kept a single iteration and didn't check that `p` isn't used after that.
