### PR TITLE
Preventing a memory leak using weak pointers in ADS.

### LINKED ISSUE #33662: Slice viewer causing memory leak
**Describe the bug**
Memory is not cleared when deleting a workspace after the slice viewer has been opened on it.

**To Reproduce**
1. Load a workspace
2. Open the slice viewer
3. Close the slice viewer
4. Delete the workspace
It's more obvious with a large workspace, e.g.
`//isis/inst$/ndxwish/Instrument/data/cycle_18_4/WISH00043526.raw`

**Expected behavior**
Memory should be cleaned up.

**Platform/Version (please complete the following information):**
 - OS: All
 - Mantid Version 6.3.0, older versions not tested yet.

### PR DESCRIPTION
**Pull request by sf1919**
**Description of work.**
Part of the work to try and stop a memory leak. This was initially noted using SliceViewer but further investigation showed problems with plotting and other actions. This PR changes the retrieveal of workspaces method to produce a list of weak pointers to ensure copies of workspaces are not left after deleting them from the ADS.

**To test:**

1. By checking the new unit test passes
2. By checking the memory (see below)

On the main branch (not this PR branch):
1. Open Mantid and load a dataset of your choice.
2. Make a plot from the resulting workspace via the right click menu (do not do this as a script!)
3. Close the plot and delete the workspace (use the button not a script)
4. repeat steps 2 and 3 with another two different datasets to the one previously used
5. Find out how much memory is being used by the python executable before closing Mantid

On this PR branch
Repeat steps 1-5 of the above - making sure you use the same files and do the same plots. The memory usage should be smaller than when doing this on the main branch.

Fixes #33662 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/PythonInterface/mantid/api/src/Exports/AnalysisDataService.cpp [hunk 1]
```diff
@@ -49,9 +51,15 @@ AnalysisDataServiceImpl &instance() {
...
  */
+
 list retrieveWorkspaces(AnalysisDataServiceImpl const *const self, const list &names, bool unrollGroups = false) {
-  return Converters::ToPyList<Workspace_sptr>()(
-      self->retrieveWorkspaces(Converters::PySequenceToVector<std::string>(names)(), unrollGroups));
+  using WeakPtr = std::weak_ptr<Workspace>;
+  const auto wsSharedPtrs =
+      self->retrieveWorkspaces(Converters::PySequenceToVector<std::string>(names)(), unrollGroups);
+  std::vector<WeakPtr> wsWeakPtrs;
+  std::transform(wsSharedPtrs.begin(), wsSharedPtrs.end(), std::back_inserter(wsWeakPtrs),
```
Comment (robertapplin) [inline Framework/PythonInterface/mantid/api/src/Exports/AnalysisDataService.cpp:60]: We can use const iterators here with `cbegin` and `cend`

File: Framework/PythonInterface/mantid/api/src/Exports/AnalysisDataService.cpp [hunk 2]
```diff
@@ -49,9 +51,15 @@ AnalysisDataServiceImpl &instance() {
...
  * @return a python list of the workspaces in the ADS
  */
+
 list retrieveWorkspaces(AnalysisDataServiceImpl const *const self, const list &names, bool unrollGroups = false) {
-  return Converters::ToPyList<Workspace_sptr>()(
-      self->retrieveWorkspaces(Converters::PySequenceToVector<std::string>(names)(), unrollGroups));
+  using WeakPtr = std::weak_ptr<Workspace>;
+  const auto wsSharedPtrs =
+      self->retrieveWorkspaces(Converters::PySequenceToVector<std::string>(names)(), unrollGroups);
+  std::vector<WeakPtr> wsWeakPtrs;
```
Comment (robertapplin) [inline Framework/PythonInterface/mantid/api/src/Exports/AnalysisDataService.cpp:59]: Is it possible to reserve memory for `wsWeakPtrs`?

**Review by robertapplin — CHANGES_REQUESTED** [review]
Nice work, the memory leak appears to be gone after these changes. Just had a few minor comments about reserving vector memory and using const iterators

**Review by robertapplin — APPROVED** [review]
