### PR TITLE
Avoid hard crash in Indirect Energy Transfer load without TCP files

### LINKED ISSUE #29554: Sometimes crash from Indirect reduction
For indirect they have 2 methods of storing their data; nxs and raw. The raw files are accompanied by the following files status, ICPrevent, ICPStatus and ICPdebug. 

It is possible to crash workbench when these additional files are not present. However, it is not 100% reproducible (there is something else going on). I can reproduce it on my laptop but not my desktop

Turn off the data archive
Open indirect data reduction
Load the raw file (with the other files missing) using browse of the run bar
If it is going to crash it will here

### PR DESCRIPTION
**Pull request by clayton-tom**
**Description of work.**
Add a check to avoid Energy Transfer from trying to access files from the ADS that haven't loaded correctly, letting it fail 'nicely' like the other tabs rather than hard crashing

**Report to:** Sanghamitra, Anthony

**To test:**
1. Turn off the data archive, download an IRIS .raw but NOT the three accompanying ICP files (e.g. IRIS00055127)
2. Interfaces -> Indirect -> Data reduction -> Energy transfer (default tab)
3. Input runs -> browse to the .raw and try to load it

Fixes #29554. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by AnthonyLim23 — DISMISSED** [review]
No longer crashes on a machine that use to. We will not put this in the release notes as it is a rare bug and more likely to confuse users.

Works on plot and workbench

File: qt/scientific_interfaces/Indirect/ISISEnergyTransfer.cpp [hunk 1]
```diff
@@ -144,8 +143,13 @@ double loadSampleLog(std::string const &filename,
...
   loader->execute();
 
-  return getSampleLog(getADSMatrixWorkspace(temporaryWorkspace), logNames,
-                      defaultValue);
+  if (doesExistInADS(temporaryWorkspace)) {
+
+    return getSampleLog(getADSMatrixWorkspace(temporaryWorkspace), logNames,
+                        defaultValue);
+  } else {
+    return -1;
```
Comment (martyngigg) [inline qt/scientific_interfaces/Indirect/ISISEnergyTransfer.cpp:151]: Should we not return the `defaultValue` in this case?

**Review by martyngigg — CHANGES_REQUESTED** [review]

**Review by martyngigg — APPROVED** [review]
