### PR TITLE
Always Return to Default Save Options When Reduction Mode is Switched

### LINKED ISSUE #36115: Auto Switching in save options is not working as expected in ISIS SANS Reduction GUI
**Describe the bug**
**Please read [this comment](https://github.com/mantidproject/mantid/issues/36115#issuecomment-1853720297) for the change required by this issue.**

In ISIS SANS Reduction GUI, when switching the reduction options between 1D and 2D, the save options are expected to automatically switch between CanSAS and NXcanSAS. However after ticking and unticking RKH (1D/2D) option, the above behaviour is not observed

**To Reproduce**
1. Get the Training data from the downloads page on the Mantid Project website.
2. Open Interfaces > SANS > ISIS SANS.
3. Click Manage Directories. This opens Mantid’s main dialog for managing search paths. Ensure the Training data directory is in the search directories.
4. If you haven’t set one up yet, add a folder to save test data into later.
5. Set the default save directory in Manage Directories
6. Click OK on the manage-directories dialog and ensure the Save Path on the SANS GUI (below batch file) displays the correct save path.
7. Click Load User File; from the Training data in the loqdemo folder, choose MaskFile.toml.
8. Click Load Batch File; from the Training data in the loqdemo folder, choose batch_mode_reduction.csv.
9. Switch between 1D and 2D at the bottom of the screen, it should automatically switch between CanSAS and NXcanSAS
10. tick and untick RKH option and observe step 9.

**Expected behavior**
Switch between 1D and 2D, it should automatically switch between CanSAS and NXcanSAS

**Platform/Version (please complete the following information):**
 - OS: all
 - Mantid Version: 6.7

### PR DESCRIPTION
**Pull request by cailafinn**
#### Summary of work
Removes the function where if the save options were changed, then the GUI did not automatically select the most appropriate saving algorithms when changing between 1D and 2D reduction modes. 

Fixes #36115 

#### Further detail of work
In addition, updates the documentation in line with the scientist's requests. Improving the clarity of what each saving algorithm is designed for.

### To test:
1. Build the `dev-docs-html` target.
2. Check the formatting of the changed manual test instructions
3. Follow the instructions in the changed Manual Testing document
4. Ensure the selection behaves as described
5. Build the `docs-html` target.
6. Ensure that the documentation for SaveNXCanSAS, SaveCanSAS1D, and SaveRKH all look correct and all added links work properly. 

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

File: Framework/DataHandling/inc/MantidDataHandling/SaveCanSAS1D.h [hunk 1]
```diff
@@ -83,7 +83,9 @@ class MANTID_DATAHANDLING_DLL SaveCanSAS1D : public API::Algorithm {
 public:
   virtual ~SaveCanSAS1D() = default;
   const std::string name() const override { return "SaveCanSAS1D"; }
-  const std::string summary() const override { return "Save a MatrixWorkspace to a file in the canSAS 1-D format"; }
+  const std::string summary() const override {
+    return "Save a MatrixWorkspace to a file in the CanSAS1D XML format for 1D data.";
```
Comment (rbauststfc) [inline Framework/DataHandling/inc/MantidDataHandling/SaveCanSAS1D.h:87]: In all of these summary updates, Steve's requested changes had brackets around the type of data that the algorithm is intended for, i.e. `Save a MatrixWorkspace to a file in the CanSAS1D XML format (for 1D data).`. These things can be a bit subjective, but I can see how including the brackets may make it a bit clearer that we're referring to the type of data that this algorithm is suitable for. I could see how excluding the brackets could potentially leave open an interpretation that the algorithm is outputting a particular CanSAS1D format designed for 1D data specifically.

File: docs/source/algorithms/SaveCanSAS1D-v2.rst [hunk 2]
```diff
@@ -13,15 +13,20 @@
...
+This format is only intended to be used for 1D workspaces.
 
 If the workspace contains several spectra, two options are available:
 
-* if OneSpectrumPerFile if false (default value), all spectra will be appended
-  into the same file (into different <SASdata> entries)
-* if OneSpectrumPerFile is true, each spectrum will be written in a separate
-  file. The name of the file will be created as follows: <Filename property>_
-  <spectrum index>_<axis value><axis unit>.<extension>
+* if ``OneSpectrumPerFile`` if ``false`` (default value), all spectra will be appended
```
Comment (rbauststfc) [inline docs/source/algorithms/SaveCanSAS1D-v2.rst:22]: This was a pre-existing typo, but while we're here could we correct `if false` to be `is false`?

File: docs/source/algorithms/SaveCanSAS1D-v2.rst [hunk 3]
```diff
@@ -13,15 +13,20 @@
...
+  into the same file (into different ``<SASdata>`` entries)
+* if ``OneSpectrumPerFile`` is ``true``, each spectrum will be written in a separate
+  file. The name of the file will be created as follows:
+
+  ``<Filename property>_<spectrum index>_<axis value><axis unit>.<extension>``
+
+The created file can be loaded back into mantid using the :ref:`algm-LoadCanSAS1D` algorithm.
```
Comment (rbauststfc) [inline docs/source/algorithms/SaveCanSAS1D-v2.rst:29]: Just a small thing, but should `Mantid` start with a capital letter here?

File: docs/source/release/v6.9.0/SANS/Bugfixes/36115.rst [hunk 4]
```diff
@@ -0,0 +1 @@
+- The GUI will now return to its default output options when the reduction mode is switched between 1D and 2D.
```
Comment (rbauststfc) [inline docs/source/release/v6.9.0/SANS/Bugfixes/36115.rst:1]: Could we mention the ISIS SANS GUI here to be clear which interface the changes refer to?

**Review by rbauststfc — COMMENTED** [review]
The functional changes are looking good. I've tested that changing the reduction mode always defaults to the appropriate save option(s), even when the user has previously changed the selection to a non-default format. I've also tested that the selected format (whether sticking with the defaults or not) is the one that actually gets saved out.

I just have a few comments on the documentation changes.

**Review by rbauststfc — APPROVED** [review]
Documentation changes are all looking good now. I've built both the manual testing docs and the algorithm documentation and they're rendering well with all links working. This all looks good to go in, thanks 👍
