### PR TITLE
Updating algorithms for modulation vectors - fixing common issues

### LINKED ISSUE #35513: IndexPeaks not rounding HKL of satellite peaks
**Describe the bug**
IndexPeaks not rounding HKL of satellite peaks to the nominal HLK given the modulation vector
`HKL = peak.getIntHKL() + modHKL * peak.getIntMNP()`
Instead it rounds the HKL to integers

**To Reproduce**

(1) Run this script
```
sxd = LoadEmptyInstrument(InstrumentName='SXD', OutputWorkspace='sxd')
peaks = CreatePeaksWorkspace(InstrumentWorkspace=sxd, NumberOfPeaks=0, OutputWorkspace="peaks")
SetUB(peaks, UB="0.25,0,0,0,0.25,0,0,0,0.1")
# add peaks at integer and half-integer H
for h in [0.5,1,1.5,2]:
    peaks.addPeak(peaks.createPeakHKL([h, 0, 1]))
# change a lattice parameter slightly
SetUB(peaks, UB="0.26,0,0,0,0.25,0,0,0,0.1")
# index
IndexPeaks(PeaksWorkspace='peaks', Tolerance=0.1, ToleranceForSatellite=0.1, 
           CommonUBForAll=True, ModVector1='0.5,0,0', MaxOrder=1, 
           SaveModulationInfo=True)
```

The log should say 

```
All runs indexed 4 peaks out of 4 of which, 2 main Bragg peaks are indexed with tolerance of 0.1, 2 satellite peaks are indexed with tolerance of 0.1
```

(2) Open the peak table (HKL of satellite peaks are integers despite being indexed)
image

**Expected behavior**
It should look like this 
image

### PR DESCRIPTION
**Pull request by zjmorgan**
**Description of work.**

Some single crystal algorithms are missing some flexibility when it comes to modulation vectors being present. This PR aims to address some of those issues. Although this looks like a lot of changes, modulation vectors happen to touch several algorithms where the behavior inside is not considered. This hopes to solve those issues.

1. `OptimizeLatticeForCellType` now performs optimization correctly with mod vectors - added unit test
3. `SaveHKL` now supports 6 `hklmnp` column format 
4. `LoadHKL` now supports 6 `hklmnp` column format
5. `FilterPeaks` now can filter by `mnp`
6. `SortHKL` skips modulation vectors
7. `LoadNexus/SaveNexus` supports MNP-vectors
8. `intHKL` and `intMNP` columns added to table workspaces

image

**To test:**
Run the unit/system tests.

*There is no associated issue.*

---

Fixes #35513

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Crystal/src/OptimizeLatticeForCellType.cpp [hunk 1]
```diff
@@ -92,6 +92,17 @@ void OptimizeLatticeForCellType::exec() {
     }
   runWS.emplace_back(ws);
 
+  int maxOrder = ws->mutableSample().getOrientedLattice().getMaxOrder();
+  DblMatrix modHKL = ws->mutableSample().getOrientedLattice().getModHKL();
+
+  if (maxOrder > 0) {
+    for (int i = 0; i < ws->getNumberPeaks(); i++) {
+      IPeak &peak = ws->getPeak(i);
+      V3D HKL = peak.getIntHKL() + modHKL * peak.getIntMNP();
```
Comment (RichardWaiteSTFC) [inline Framework/Crystal/src/OptimizeLatticeForCellType.cpp:101]: So this would not work if the HKL had been set by hand - but I believe the HKL are all that is required for the lattice to be optimized (i.e. you don't need to know the parent peak)  - should the re-indexing be optional? How are the MNP of found peaks set in your workflow?

File: Framework/Crystal/src/PeakStatisticsTools.cpp [hunk 2]
```diff
@@ -132,13 +132,15 @@ UniqueReflectionCollection::UniqueReflectionCollection(const UnitCell &cell, con
 /// the reflection family can not be found are ignored.
 void UniqueReflectionCollection::addObservations(const std::vector<Peak> &peaks) {
   for (auto const &peak : peaks) {
-    V3D hkl = peak.getHKL();
-    hkl.round();
+    V3D hkl = peak.getIntHKL();
+    V3D mnp = peak.getIntMNP();
 
-    auto reflection = m_reflections.find(m_pointgroup->getReflectionFamily(hkl));
+    if (mnp.norm2() == 0.0) {
```
Comment (RichardWaiteSTFC) [inline Framework/Crystal/src/PeakStatisticsTools.cpp:138]: Looks like the statistics calculation ignores satellite peaks - I think it makes sense as the modulated lattice could have a different point group

File: Framework/Crystal/test/FilterPeaksTest.h [hunk 3]
```diff
@@ -358,12 +390,14 @@ class FilterPeaksTest : public CxxTest::TestSuite {
     LeanElasticPeak peak(Mantid::Kernel::V3D(1, 1, 0), 1.0);
     peak.setIntensity(100.0);
     peak.setHKL(1, 1, 0);
+    peak.setIntHKL(V3D(1, 1, 0));
```
Comment (RichardWaiteSTFC) [inline Framework/Crystal/test/FilterPeaksTest.h:393]: Is it necessary to set `IntHKL` here - won't it default to the rounded `hkl` provided?

File: Framework/Crystal/src/OptimizeLatticeForCellType.cpp (hunk 1 above)
Comment (zjmorgan) [reply Framework/Crystal/src/OptimizeLatticeForCellType.cpp:101]: Using `PredictSatellitePeaks` or `IndexPeaks` gives the correct hklmnp vector in our workflows. This line only happens if the max order is greater than zero, so if you do set it by hand with max order equal to zero, I believe it will still work.

Comment (RichardWaiteSTFC) [reply Framework/Crystal/src/OptimizeLatticeForCellType.cpp:101]: I see, I hadn't set `SaveModulationInfo=True` in `IndexPeaks sorry!

File: Framework/Crystal/test/FilterPeaksTest.h (hunk 3 above)
Comment (zjmorgan) [reply Framework/Crystal/test/FilterPeaksTest.h:393]: I found that they are actually separate objects. `m_H, `m_K`, `m_L` are distinct from `m_intHKL`. Setting `HKL` by hand does not affect `intHKL` I found. This is normally not an issue when using algorithms to get the peaks.

File: Framework/Crystal/src/PeakStatisticsTools.cpp (hunk 2 above)
Comment (zjmorgan) [reply Framework/Crystal/src/PeakStatisticsTools.cpp:138]: That's the intent. I don't think at this moment the symmetry algorithms can handle anything other than non-modulated structures.

File: Testing/SystemTests/tests/framework/SingleCrystalPeaksTest.py [hunk 4]
```diff
@@ -0,0 +1,59 @@
...
+        pk.setIntHKL(V3D(1, 3, 2))
+        pk.setIntMNP(V3D(3, 2, 1))
+        pks.addPeak(pk)
+
+        file_name = os.path.join(self._test_dir, "peaks_workspace.nxs")
+
+        SaveNexus(pks, Filename=file_name)
+        ref = LoadNexus(Filename=file_name)
+
+        self.assertAlmostEqual(ref.getPeak(0).getIntHKL(), pks.getPeak(0).getIntHKL())
```
Comment (RichardWaiteSTFC) [inline Testing/SystemTests/tests/framework/SingleCrystalPeaksTest.py:47]: Could `IntHKL` and `IntMNP` be added to the comparison in the `CompareWorkspaces` algorithm?
https://github.com/mantidproject/mantid/blob/e40838ac9f03bf7d3289f45c40a9ea61b15fd78b/Framework/Algorithms/src/CompareWorkspaces.cpp#L985

Comment (zjmorgan) [reply Testing/SystemTests/tests/framework/SingleCrystalPeaksTest.py:47]: Good catch! I should add that.

File: Framework/Crystal/src/OptimizeLatticeForCellType.cpp (hunk 1 above)
Comment (RichardWaiteSTFC) [reply Framework/Crystal/src/OptimizeLatticeForCellType.cpp:101]: It seems that `IndexPEaks` does not set H,K,L to the modulated vector if RoundHKLs=True even if they were provided. Would this be necessary if it did? And should the behaviour in `IndexPEaks be fixed (happy to do in a separate PR)

Comment (zjmorgan) [reply Framework/Crystal/src/OptimizeLatticeForCellType.cpp:101]: So you mean it rounds it to integer? If so, that should also be fixed because that doesn't make sense. I interpret `RoundHKLs` to mean to round to `nice` values. That means integer for nuclear only but includes the fractional offset for modulated peaks.

**Review by RichardWaiteSTFC — CHANGES_REQUESTED** [review]
I got this exception when I tried to sort `IntHKL` and `IntMNP` columns in a peak table (right-click on table workspace column header and sort)
```
Error in execution of algorithm SortPeaksWorkspace:
BasePeak::getValueByColName() unknown column or column is not a number: inthkl
Traceback (most recent call last):
  File "C:\mantid-conda\mantid\Framework\PythonInterface\mantid\simpleapi.py", line 1070, in __call__
    algm.execute()
RuntimeError: BasePeak::getValueByColName() unknown column or column is not a number: inthkl

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\mantid-conda\mantid\qt\python\mantidqt\mantidqt\widgets\workspacedisplay\table\presenter.py", line 271, in action_sort
    self.presenter.model.sort(selected_column, sort_ascending)
  File "c:\mantid-conda\mantid\qt\python\mantidqt\mantidqt\widgets\workspacedisplay\table\model.py", line 169, in sort
    SortPeaksWorkspace(
  File "C:\mantid-conda\mantid\Framework\PythonInterface\mantid\simpleapi.py", line 1077, in __call__
    raise RuntimeError(msg) from e
RuntimeError: SortPeaksWorkspace-v1: BasePeak::getValueByColName() unknown column or column is not a number: inthkl
```

File: Framework/Crystal/src/OptimizeLatticeForCellType.cpp (hunk 1 above)
Comment (RichardWaiteSTFC) [reply Framework/Crystal/src/OptimizeLatticeForCellType.cpp:101]: I have created a separate issue for  `IndexPeaks` here #35513 - essentially it rounds the modulated peaks to have integer HKL if `RoundHKLS=True` - whereas I would expect the behaviour to set HKL to `HKL = peak.getIntHKL() + modHKL * peak.getIntMNP()` (as you have elsewhere in this PR).

**Comment by zjmorgan** [comment]
> I got this exception when I tried to sort `IntHKL` and `IntMNP` columns in a peak table (right-click on table workspace column header and sort)
> 
> ```
> Error in execution of algorithm SortPeaksWorkspace:
> BasePeak::getValueByColName() unknown column or column is not a number: inthkl
> Traceback (most recent call last):
>   File "C:\mantid-conda\mantid\Framework\PythonInterface\mantid\simpleapi.py", line 1070, in __call__
>     algm.execute()
> RuntimeError: BasePeak::getValueByColName() unknown column or column is not a number: inthkl
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "c:\mantid-conda\mantid\qt\python\mantidqt\mantidqt\widgets\workspacedisplay\table\presenter.py", line 271, in action_sort
>     self.presenter.model.sort(selected_column, sort_ascending)
>   File "c:\mantid-conda\mantid\qt\python\mantidqt\mantidqt\widgets\workspacedisplay\table\model.py", line 169, in sort
>     SortPeaksWorkspace(
>   File "C:\mantid-conda\mantid\Framework\PythonInterface\mantid\simpleapi.py", line 1077, in __call__
>     raise RuntimeError(msg) from e
> RuntimeError: SortPeaksWorkspace-v1: BasePeak::getValueByColName() unknown column or column is not a number: inthkl
> ```

Good catch. It seems I get the same exception if I try to sort my QSample/QLab.

**Comment by zjmorgan** [comment]
@RichardWaiteSTFC I happened to already be working on the `IndexPeaks` issue [#3551](https://github.com/mantidproject/mantid/issues/35513) so I pushed those changes with the fix. The unit test has been updated accordingly. For the sorting issue, the most straightforward way was to sort any vector (`intHKL`/`QSample`) by the mod-value since the sorting only compares by a double value. I think this should work just fine.

**Review by RichardWaiteSTFC — CHANGES_REQUESTED** [review]
Just a small addition to the `IndexPeaks` test and then I'll approve!
I notice that the concise view of peak tables in sliceviewer includes the new columns (`IntHKL` and `IntMNP`) - I'm OK with this if you are - the point of the concise view is to make HKL and I,sig and I/sig appear next to each other.
I also see an error when trying `SortHKL` on the table in issue #35513 (using primitive cubic symmetry)
```
Number of peaks should not be 0 for SortHKL.
Error in execution of algorithm SortHKL:
WorkspaceProperty doesn't point to a workspace
```
but the example on the docs works for me.
Filtering peaks, sorting columns works as expected

File: Framework/Crystal/test/IndexPeaksTest.h [hunk 5]
```diff
@@ -316,7 +316,8 @@ class IndexPeaksTest : public CxxTest::TestSuite {
     const auto alg = indexPeaks(peaksWS, {{"CommonUBForAll", "1"}, {"ToleranceForSatellite", sateTolerance}});
 
     assertNumberPeaksIndexed(*alg, 5, 2, 3);
-    const std::vector<V3D> expectedHKL{V3D(-1, 2, -9), V3D(-0, 1, -3), V3D(-1, 1, -10), V3D(1, 1, -1), V3D(-0, 1, -5)};
+    const std::vector<V3D> expectedHKL{V3D(-1, 2, -9), V3D(-0.667, 0.333, -2.667), V3D(-1, 1, -10),
```
[the remark this answers is not in the document]
Comment (zjmorgan) [reply Framework/Crystal/test/IndexPeaksTest.h:319]: I believe by default, this is `RoundHKLs=True`. This is implied by the test name `test_exec_with_common_ub_and_non_zero_mod_vectors_indexes_both_with_roundhkl`

[the remark this answers is not in the document]
Comment (RichardWaiteSTFC) [reply Framework/Crystal/test/IndexPeaksTest.h:319]: Yep sorry, I was looking at the wrong test, this does indeed do rounding!

**Review by RichardWaiteSTFC — COMMENTED** [review]
Could you add the bug fix of `IndexPeaks` to the release notes - sorry I didn't catch that before

**Comment by zjmorgan** [comment]
> Could you add the bug fix of `IndexPeaks` to the release notes - sorry I didn't catch that before

Yes. Good suggestion.

**Comment by zjmorgan** [comment]
> Just a small addition to the `IndexPeaks` test and then I'll approve! I notice that the concise view of peak tables in sliceviewer includes the new columns (`IntHKL` and `IntMNP`) - I'm OK with this if you are - the point of the concise view is to make HKL and I,sig and I/sig appear next to each other. I also see an error when trying `SortHKL` on the table in issue #35513 (using primitive cubic symmetry)
> 
> ```
> Number of peaks should not be 0 for SortHKL.
> Error in execution of algorithm SortHKL:
> WorkspaceProperty doesn't point to a workspace
> ```
> 
> but the example on the docs works for me. Filtering peaks, sorting columns works as expected

I added `IntHKL` and `IntMNP` to concise view

**Review by RichardWaiteSTFC — APPROVED** [review]
Looks good - thanks for this!
