### PR TITLE
Fix binning params in the SofQW* algorithms

### LINKED ISSUE #22140: SofQWNormalisedPolygon fails if a single value is given as QBinningParams
If *QBinningParams* is supplied with only the bin width, `SofQWNormalisedPolygon` throws the following error:

```
RuntimeError: All arguments to init must be positive and non-zero
```

This seems to be due to `Mantid::Kernel::VectorHelper::createAxisFromRebinParams` doesn't handle the bin width only case properly.

### PR DESCRIPTION
**Pull request by soininen**
The `SofQW*` algorithms failed when they were supplied with 'bin width only' binning parameters. This PR fixes the issue by adding E and Q binning range estimation and by fixing the 'bin width only' case in `VectorHelper::createAxisFromRebinParams`.

**To test:**

The following script should work after these changes are applied. The data can be found in Mantid's unit test data.
```python
DirectILLCollectData(
    Run='ILL/IN6/164192.nxs',
    OutputWorkspace='ws',
)
ws = mtd['ws']
e = ws.run().getProperty('Ei').value
print(e)
ws = ConvertUnits(ws, 'DeltaE', EMode='Direct', EFixed=e)
ws = Rebin(ws, '-10000, 5, 5')

ws = SofQWNormalisedPolygon('ws', QAxisBinning='0.1', EAxisBinning='-10000, 5, 5', EMode='Direct', EFixed=e)
```

Fixes #22140.

**Release Notes** 

The Direct Inelastic release notes were updated.

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Kernel/src/VectorHelper.cpp [hunk 1]
```diff
@@ -27,6 +27,10 @@ int DLLExport createAxisFromRebinParams(const std::vector<double> &params,
                                         std::vector<double> &xnew,
                                         const bool resize_xnew,
                                         const bool full_bins_only) {
+  if (params.size() == 1) {
```
Comment (SimonHeybrock) [inline Framework/Kernel/src/VectorHelper.cpp]: I am not sure I understand what you did here. Don't other algorithms like `Rebin` support such parameters?

**Review by SimonHeybrock — CHANGES_REQUESTED** [review]

File: Framework/Kernel/src/VectorHelper.cpp (hunk 1 above)
Comment (soininen) [reply Framework/Kernel/src/VectorHelper.cpp]: They do but in case of `Rebin`, the min and max X are known. The `SofQW*` algorithms convert to momentum transfer and it's a bit tedious to guess suitable Qmin and Qmax beforehand.

File: Framework/Algorithms/src/SofQCommon.cpp [hunk 2]
```diff
@@ -82,5 +85,142 @@ double SofQCommon::getEFixed(const Geometry::IDetector &det) const {
...
   return efixed;
 }
+
+/**
+ * Return a pair of (minimum DeltaE, maximum DeltaE)
+ * @param ws a workspace
+ * @return a pair containing the global minimum and maximum X
+ */
+std::pair<double, double>
+SofQCommon::eBinHints(const API::MatrixWorkspace &ws) const {
```
Comment (SimonHeybrock) [inline Framework/Algorithms/src/SofQCommon.cpp]: Isn't this the same as `MatrixWorkspace::getXMinMax`?

File: Framework/Algorithms/src/SofQCommon.cpp [hunk 3]
```diff
@@ -82,5 +85,142 @@ double SofQCommon::getEFixed(const Geometry::IDetector &det) const {
...
+  const auto maxK = std::sqrt(maxKSq);
+  std::array<double, 4> q;
+  q[0] = std::sqrt(incidentKSq + minKSq -
+                   2. * incidentK * minK * std::cos(minTheta));
+  q[1] = std::sqrt(incidentKSq + minKSq -
+                   2. * incidentK * minK * std::cos(maxTheta));
+  q[2] = std::sqrt(incidentKSq + maxKSq -
+                   2. * incidentK * maxK * std::cos(minTheta));
+  q[3] = std::sqrt(incidentKSq + maxKSq -
+                   2. * incidentK * maxK * std::cos(maxTheta));
```
Comment (SimonHeybrock) [inline Framework/Algorithms/src/SofQCommon.cpp]: It feels like this conversion must be something that has been implemented before somewhere else?

File: Framework/Algorithms/src/SofQW.cpp [hunk 4]
```diff
@@ -151,21 +142,37 @@ void SofQW::exec() {
...
     const std::vector<double> &qbinParams, std::vector<double> &qAxis,
-    const std::vector<double> &ebinParams) {
+    const std::vector<double> &ebinParams, const SofQCommon &emodeProperties) {
+  using Kernel::VectorHelper::createAxisFromRebinParams;
   // Create vector to hold the new X axis values
   HistogramData::BinEdges xAxis(0);
+  auto eHints = std::make_pair<double, double>(std::nan(""), std::nan(""));
   int xLength;
   if (ebinParams.empty()) {
     xAxis = inputWorkspace->refX(0);
```
Comment (SimonHeybrock) [inline Framework/Algorithms/src/SofQW.cpp]: `refX` is deprecated.

File: Framework/Algorithms/src/SofQWNormalisedPolygon.cpp [hunk 5]
```diff
@@ -411,18 +413,32 @@ RebinnedOutput_sptr SofQWNormalisedPolygon::setUpOutputWorkspace(
...
+    if (std::isnan(eHints.first)) {
+      eHints = m_EmodeProperties.eBinHints(inputWorkspace);
+    }
+    const auto qHints = m_EmodeProperties.qBinHints(
+        inputWorkspace, eHints.first, eHints.second);
+    yLength = createAxisFromRebinParams(qbinParams, qAxis, true, true,
+                                        qHints.first, qHints.second);
+  } else {
+    yLength = createAxisFromRebinParams(qbinParams, qAxis);
+  }
```
Comment (SimonHeybrock) [inline Framework/Algorithms/src/SofQWNormalisedPolygon.cpp]: This code looks identical to the one above in `SofQW`, can it be extracted into a shared function/method without too much hassle?

File: Framework/Algorithms/test/SofQCommonTest.h [hunk 6]
```diff
@@ -0,0 +1,240 @@
...
+  }
+
+  void test_getEFixedFromDetectorsIndirectGeometry() {
+    using namespace Mantid;
+    using namespace WorkspaceCreationHelper;
+    Algorithms::SofQW alg;
+    alg.initialize();
+    alg.setProperty("EMode", "Indirect");
+    // const double Ei{2.3};
+    // alg.setProperty("EFixed", Ei);
```
Comment (SimonHeybrock) [inline Framework/Algorithms/test/SofQCommonTest.h]: Leftover comments.

**Review by SimonHeybrock — CHANGES_REQUESTED** [review]
Looks nice, with a good amount of cleanup and many tests 👍.

Only a couple of minor comments:

**Review by SimonHeybrock — APPROVED** [review]
Nice, even more cleanup 👍

File: Framework/Algorithms/inc/MantidAlgorithms/SofQCommon.h [hunk 7]
```diff
@@ -27,12 +27,20 @@ struct DLLExport SofQCommon {
   /// Get the efixed value for the given detector
   double getEFixed(const Geometry::IDetector &det) const;
 
+
+  /// Calculate the Q value
+  double q(const double deltaE, const double twoTheta, const Geometry::IDetector &det) const;
```
Comment (SimonHeybrock) [inline Framework/Algorithms/inc/MantidAlgorithms/SofQCommon.h]: Getting the detector from the instrument is a really expensive operation (one of the few that still needs to use the old instrument code), can't it be avoided in direct mode?

File: Framework/Algorithms/src/SofQCommon.cpp [hunk 8]
```diff
@@ -167,20 +205,15 @@ SofQCommon::qBinHintsIndirect(const API::MatrixWorkspace &ws, const double minE,
...
-    const auto theta = detectorInfo.twoTheta(i) / 2.;
-    const auto eFixed = getEFixed(detectorInfo.detector(i));
-    const Kernel::DeltaEMode::Type indirectEMode{Kernel::DeltaEMode::Indirect};
-    Kernel::Units::DeltaE DeltaEUnit;
-    Kernel::Units::MomentumTransfer QUnit;
-    const auto Q1 = Kernel::UnitConversion::run(DeltaEUnit, QUnit, minE, 0., 0.,
-                                                theta, indirectEMode, eFixed);
-    const auto Q2 = Kernel::UnitConversion::run(DeltaEUnit, QUnit, maxE, 0., 0.,
-                                                theta, indirectEMode, eFixed);
+    const auto theta = spectrumInfo.twoTheta(i);
```
Comment (SimonHeybrock) [inline Framework/Algorithms/src/SofQCommon.cpp]: Dangerous naming? `twoTheta` assigned to `theta`?

File: Framework/Algorithms/src/SofQCommon.cpp [hunk 9]
```diff
@@ -167,20 +205,15 @@ SofQCommon::qBinHintsIndirect(const API::MatrixWorkspace &ws, const double minE,
   using namespace Mantid::PhysicalConstants;
   auto minQ = std::numeric_limits<double>::max();
   auto maxQ = std::numeric_limits<double>::lowest();
-  const auto &detectorInfo = ws.detectorInfo();
-  for (size_t i = 0; i < detectorInfo.size(); ++i) {
-    if (detectorInfo.isMasked(i) || detectorInfo.isMonitor(i)) {
+  const auto &spectrumInfo = ws.spectrumInfo();
+  for (size_t i = 0; i < spectrumInfo.size(); ++i) {
```
Comment (SimonHeybrock) [inline Framework/Algorithms/src/SofQCommon.cpp]: Are you sure about this change? I see you adjusted the doxygen above. One thing to double check: What does `getEFixed` to for a `DetectorGroup`? Unless it returns an average (of the E_f looked up in the parameter map) for all contained detectors I think you cannot change this here.

File: Framework/Algorithms/src/SofQWNormalisedPolygon.cpp [hunk 10]
```diff
@@ -113,23 +112,19 @@ void SofQWNormalisedPolygon::exec() {
...
-    double phiHalfWidth = 0.5 * phiWidth;
+    const double thetaHalfWidth = 0.5 * thetaWidth;
 
     const double thetaLower = theta - thetaHalfWidth;
     const double thetaUpper = theta + thetaHalfWidth;
 
-    const double phiLower = phi - phiHalfWidth;
-    const double phiUpper = phi + phiHalfWidth;
-
-    const double efixed = m_EmodeProperties.getEFixed(spectrumInfo.detector(i));
```
Comment (SimonHeybrock) [inline Framework/Algorithms/src/SofQWNormalisedPolygon.cpp]: Hmm, this is also using `getEFixed` for a (potential) `DetectorGroup`, does this imply that it does the right thing...?

Edit: tried to track it down: I believe `getEFixed` simply throw in that case?

**Review by SimonHeybrock — CHANGES_REQUESTED** [review]
Some comments:

File: Framework/Algorithms/src/SofQWNormalisedPolygon.cpp (hunk 10 above)
Comment (soininen) [reply Framework/Algorithms/src/SofQWNormalisedPolygon.cpp]: `DetectorGroup::getNumberParameter()` always returns an empty `vector` so `SofQCommon::getEFixed()` would indeed throw for `DetectorGroup`.

**Review by SimonHeybrock — APPROVED** [review]
