### PR TITLE
Fix side by side instrument view crash

### LINKED ISSUE #24089: Instrument view crashes mantid when trying to draw a side-by-side view.
**Original reporter:** Rob Dalgliesh.

### Expected behavior
Draw a nice picture.

### Actual behavior
Mantid crashes.

### Steps to reproduce the behavior
1. Load empty instrument from VISION_Definition_00-20131021.xml
2. Open the instrument view
3. Switch to the side by side view.

### Platforms affected
All.

### PR DESCRIPTION
**Pull request by mantid-roman**
**Description of work.**
* Two OMP loops contained thread unsafe code. Serialised one of the loops and changed the container type in the other.
* Restored the view for the VISION instrument by checking deeper component structures.
* Restored mask application to the view.

**To test:**
* Display the VISION instrument in the side by side view. It should show all banks including the ring of tubes.
* Draw a mask shape in the mask tab (any workspace/instrument). Apply mask to view. The masked detectors should be drawn in the mask colour (grey).

Fixes #24089

*This does not require release notes* because it wasn't an issue in 3.13

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/widgets/instrumentview/src/PanelsSurface.cpp [hunk 1]
```diff
@@ -371,17 +372,48 @@ void PanelsSurface::processGrid(size_t rootIndex) {
   processStructured(layers[layerIndex]);
 }
 
-void PanelsSurface::processTubes(size_t rootIndex) {
+boost::optional<size_t> PanelsSurface::processTubes(size_t rootIndex) {
```
Comment (DanNixon) [inline qt/widgets/instrumentview/src/PanelsSurface.cpp]: This function could use some comments to describe what it is actually doing.

File: qt/widgets/instrumentview/src/PanelsSurface.cpp [hunk 2]
```diff
@@ -316,11 +317,11 @@ void PanelsSurface::addFlatBankOfDetectors(
   QVector<QPointF> vert;
   vert << p1 << p0;
   info->polygon = QPolygonF(vert);
-#pragma omp parallel for
   for (int i = 0; i < static_cast<int>(detectors.size()); ++i) {
     auto detector = detectors[i];
     addDetector(detector, pos0, index, info->rotation);
     UnwrappedDetector &udet = m_unwrappedDetectors[detector];
+    // this isn't thread-safe
```
Comment (DanNixon) [inline qt/widgets/instrumentview/src/PanelsSurface.cpp]: Is it possible/beneficial to use `#pragma omp ordered` around `info->polygon << QPointF(udet.u, udet.v);` so that the first part of the function can still be parallelised?

**Review by DanNixon — CHANGES_REQUESTED** [review]
Changes work as expected. Side by side view and masking work as intended.

Just a couple of small comments.

**Review by DanNixon — APPROVED** [review]
Looks good to me now.
