### PR TITLE
Moving the logic of single peak fitting to presenter

### LINKED ISSUE #16220: Engg GUI, single peak fitting: move the logic that builds the list of peaks to presenter, add regression tests
PR #16211 fixes a bug in the Engg GUI. The method modified in that PR is in the view and is manipulating the list with non-trivial operations. The view is taking care of bookkeeping the list of peaks. This is not the ideal separation. The view should just provide the inputs that the user gives, and take well digested results to just show them to the user.
The manipulation of the list of peaks would live better in the presenter, where it could be tested, so the bug fix of the PR could have a regression test to check that adding peaks always works well regardless of what's included in the list.

### PR DESCRIPTION
**Pull request by shahrozahmed1**
**Description of work.**

This PR moves most of the logic of single peak fitting code to presenter from the view. This will enable the code to be tested and maintained appropriately. The PR request now also removes the duplicates comma within the expected peak list, which seemed to have been causing a problem during the demo.

**To test:**
Code review
All builds pass successfully
Presenter test have been updated
Fitting tab still functions as expected
Any further functions or bit code which could be moved to presenter..?

Fixes #16220 
_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: MantidQt/CustomInterfaces/inc/MantidQtCustomInterfaces/EnggDiffraction/IEnggDiffractionView.h [hunk 1]
```diff
@@ -387,6 +387,13 @@ class IEnggDiffractionView {
   virtual std::string fittingPeaksData() const = 0;
 
   /**
+  * Sets the peak list according to the QString given
+  *
+  * @param peakList list of expected peaks to be fitted as QString
+  */
+  virtual void setPeakList(QString peakList) const = 0;
```
Comment (FedeMPouzols) [inline MantidQt/CustomInterfaces/inc/MantidQtCustomInterfaces/EnggDiffraction/IEnggDiffractionView.h]: Just one small detail. This is an interface which does not use Qt classes for anything. It would be better to use `std::string` rather than adding `QString`, `QStringList`, etc. here. As the presenter is preparing the strings as `std::string`, this fits well between the view and the presenter. Only the Qt specific view classes should use Qt classes, as far as possible.

File: MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffractionPresenter.cpp [hunk 2]
```diff
@@ -863,27 +867,64 @@ void EnggDiffractionPresenter::inputChecksBeforeFitting(
...
+    if (expectedPeaks.at(strLength) == ',') {
+      expectedPeaks.erase(strLength, 1);
+    }
+
+    m_view->setPeakList(expectedPeaks);
+  }
+
+  return expectedPeaks;
+}
+
```
Comment (FedeMPouzols) [inline MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffractionPresenter.cpp]: Good that all this validation code is now in the presenter.

**Comment by FedeMPouzols** [comment]
It's worth keeping in mind that some of the method names might need revisiting when/if we generalize this to be shared between the single-peak and the whole-pattern fitting tabs. At the same time more stuff from the view may need to go to the presenter. But this already moves most of the logic, error checks, etc.

File: MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffractionPresenter.cpp [hunk 3]
```diff
@@ -863,27 +867,64 @@ void EnggDiffractionPresenter::inputChecksBeforeFitting(
...
+    auto *comma = ",";
+
+    for (size_t i = 0; i < expectedPeaks.size() - 1; i++) {
+      size_t j = i + 1;
+
+      if (expectedPeaks[i] == *comma && expectedPeaks[i] == expectedPeaks[j]) {
+        expectedPeaks.erase(j, 1);
+        i--;
+
```
Comment (FedeMPouzols) [inline MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffractionPresenter.cpp]: For later, this is the type of processing that can be done with `find_if`, `remove_if`, etc.

File: MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffractionPresenter.cpp [hunk 4]
```diff
@@ -1371,6 +1412,132 @@ void EnggDiffractionPresenter::setDataToClonedWS(std::string &current_WS,
...
+                        "Could not add banks to "
+                        "combo-box or list widget; " +
+                            static_cast<std::string>(re.what()) +
+                            ". Please try again");
+  }
+}
+
+void EnggDiffractionPresenter::setRunNoItems(
+    std::vector<std::string> runNumVector, bool multiRun) {
+  try {
```
Comment (FedeMPouzols) [inline MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffractionPresenter.cpp]: runNumVector can be a `const &`.

File: MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffractionPresenter.cpp [hunk 5]
```diff
@@ -1371,6 +1412,132 @@ void EnggDiffractionPresenter::setDataToClonedWS(std::string &current_WS,
...
+  } catch (std::runtime_error &re) {
+    m_view->userWarning("Unable to insert items: ",
+                        "Could not add list widget; " +
+                            static_cast<std::string>(re.what()) +
+                            ". Please try again");
+  }
+}
+
+void EnggDiffractionPresenter::setDefaultBank(
+    std::vector<std::string> splittedBaseName, QString selectedFile) {
```
Comment (FedeMPouzols) [inline MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffractionPresenter.cpp]: `splittedBaseName` can also be a `const &`.
And also for later, `QString` should not be used here in the presenter.

File: MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffractionPresenter.cpp [hunk 6]
```diff
@@ -1371,6 +1412,132 @@ void EnggDiffractionPresenter::setDataToClonedWS(std::string &current_WS,
...
+  else if (!m_view->getFittingRunNo().empty())
+    m_view->setFittingRunNo(selectedFile);
+}
+
+bool EnggDiffractionPresenter::isDigit(std::string text) {
+  for (size_t i = 0; i < text.size(); i++) {
+    char *str = &text[i];
+    if (std::isdigit(*str)) {
+      return true;
+    }
```
Comment (FedeMPouzols) [inline MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffractionPresenter.cpp]: This is a `std::find_if`?

File: MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffractionViewQtGUI.cpp [hunk 7]
```diff
@@ -1405,6 +1405,40 @@ std::string EnggDiffractionViewQtGUI::getFittingRunNo() const {
...
+
+void MantidQt::CustomInterfaces::EnggDiffractionViewQtGUI::
+    setFittingListWidgetCurrentRow(int idx) const {
+  m_uiTabFitting.listWidget_fitting_run_num->setCurrentRow(idx);
+}
+
+int EnggDiffractionViewQtGUI::getFittingComboIdx(std::string bank) const {
+  return m_uiTabFitting.comboBox_bank->findText(QString::fromStdString(bank));
+}
+
```
Comment (FedeMPouzols) [inline MantidQt/CustomInterfaces/src/EnggDiffraction/EnggDiffractionViewQtGUI.cpp]: This block of methods is a perfect example of what the ideal view code should look like. All are pasively passing around values, to/from the widgets/user.

**Comment by FedeMPouzols** [comment]
- Code changes look good.  Moves code to the presenter for better testability, and updates the mock definitions and tests. More changes and tests will follow in other issues.
- Tested a simple user session, doing a few fits, and the interface behaved well / as usual.

:shipit:
