### PR TITLE
Indirect - MSD Fit Plot Output has wrong x units

### LINKED ISSUE #23493: Indirect - Wrong units in MSD Fit Plot Result
**Original reporter:** Spencer

### Expected behavior
The units on the x axis when you click `Plot Result` on the `MSD Fit` tab should be in temperature.
There should be a drop-down list of parameters next to the `Plot Result` button.

### Actual behavior
The units on the x axis are in q value (or just empty).

### Steps to reproduce the behavior
1. `Interfaces`->`Indirect Data Analysis`->`MSD Fit` Tab
2. Load in the data below
3. Select `Gaussian` as the Fit type
4. Click `Run` and wait for it to finish
5. Click `Plot Result`
6. X axis units are wrong

**Data Files**
[osi104367-104371_graphite002_red_elwin_eq.zip](https://github.com/mantidproject/mantid/files/2393408/osi104367-104371_graphite002_red_elwin_eq.zip)

### Platforms affected
All

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR introduces a Temperature (in Kelvin) label which is now used in `Indirect Data Analysis`->`MSDFit` interface.
This PR also adds documentation for several undocumented non-TOF convertible units.

**To test:**
1. `Interfaces`->`Indirect`->`Data Analysis`->`MSD Fit` Tab
2. Enter the data below
3. Click `Run` and wait
4. Click `Plot` and check that the x-axis label says `Temperature (K)`

**Data**
[osi104367-104371_graphite002_red_elwin_eq.zip](https://github.com/mantidproject/mantid/files/2495042/osi104367-104371_graphite002_red_elwin_eq.zip)
FitType: `Gaussian`
StartX: `0.2`
EndX: `0.9`

Fixes #23493 

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Kernel/src/Unit.cpp [hunk 1]
```diff
@@ -1235,6 +1235,42 @@ double Degrees::conversionTOFMin() const {
...
+
+TemperatureKelvin::TemperatureKelvin() : Empty(), m_label("K") {}
+
+const UnitLabel TemperatureKelvin::label() const { return m_label; }
+
+void TemperatureKelvin::init() {}
+
+double TemperatureKelvin::singleToTOF(const double x) const {
+  UNUSED_ARG(x);
+  throw std::runtime_error("Temperature is not allowed to be convert to TOF. ");
```
Comment (soininen) [inline Framework/Kernel/src/Unit.cpp]: convert -> converted

File: Framework/Kernel/inc/MantidKernel/Unit.h [hunk 2]
```diff
@@ -632,13 +632,33 @@ class MANTID_KERNEL_DLL Degrees : public Empty {
...
-/// Phi that has degrees as unit at "Phi" as title
+/// Phi that has degrees as unit and "Phi" as title
 class MANTID_KERNEL_DLL Phi : public Degrees {
   const std::string caption() const override { return "Phi"; }
   Unit *clone() const override { return new Phi(*this); }
 };
 
+//=================================================================================================
+/// Temperature in kelvin
+class MANTID_KERNEL_DLL TemperatureKelvin : public Empty {
```
Comment (soininen) [inline Framework/Kernel/inc/MantidKernel/Unit.h]: Why not call this simply `Temperature`? None of the other units mention the actual unit in their names, just the physical quantity's name.

**Review by soininen — CHANGES_REQUESTED** [review]
The axis label in the plots look OK now. A few concern below, especially regarding the name of `TempertaureKelvin`. Otherwise the code and the unit tests look good. As the new unit will be available via the Python API, I think it deserves a mention in the release notes.

File: docs/source/release/v3.14.0/framework.rst [hunk 3]
```diff
@@ -89,6 +89,7 @@ New
 
 - :class:`mantid.api.SpectrumInfo` allows the user to access information about the spectra being used in a beamline. ``SpectrumInfo`` has also been given an iterator to allow users to write more Pythonic loops rather than normal index based loops. In addition to this ``SpectrumDefinition`` objects can also be accessed via a :class:`mantid.api.SpectrumInfo` object. The ``SpectrumDefinition`` object can be used to obtain information about the spectrum to detector mapping and provides a definition of what a spectrum comprises, i.e. indices of all detectors that contribute to the data stored in the spectrum.
 
+- :class:`mantid.kernel.Temperature` allows the user to access a new unit called Temperature which has units of Kelvin.
```
Comment (soininen) [inline docs/source/release/v3.14.0/framework.rst]: The `:class:` reference is a nice idea but I don't think the class is actually exported to Python, is it? Maybe write something like
```suggestion
- Added new :ref:`unit <Unit Factory>` called ``Temperature`` which has units of Kelvin.
```

**Review by soininen — CHANGES_REQUESTED** [review]

**Review by soininen — APPROVED** [review]
