### PR TITLE
Indirect -Error when clicking plot guess from Display without reduced workspace

### LINKED ISSUE #24202: Indirect - Unexpected error when clicking plot guess without reduced workspace
**Found by:** Unscripted testing

### Actual behavior
Unexpected error

### Steps to reproduce the behavior
1.`Interfaces`->`Indirect`->`Data Analysis`->`ConvFit` tab
2. Load the resolution file below
3. Select Fit type to be `Teixeira Water`
4. Click Display->Plot Guess
Error! 

### Platforms affected
All

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR ensures you cannot Plot Guess using the display combo box when a reduced workspace is not loaded.

**To test:**
1. `Interfaces`->`Indirect`->`Data Analysis`->`ConvFit` tab
2. Load the resolution file below
3. Select Fit type to be Teixeira Water
4. Click the Display combo box above the FitPropertyBrowser. Plot Guess should be disabled
5. Load the reduced file below
6. Click the Display combo box above the FitPropertyBrowser. Plot Guess should be enabled - click this and a new plot window should open.

Fixes #24202 

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/widgets/common/inc/MantidQtWidgets/Common/IndirectFitPropertyBrowser.h [hunk 1]
```diff
@@ -133,6 +133,8 @@ class EXPORT_OPT_MANTIDQT_COMMON IndirectFitPropertyBrowser
 
   void setWorkspaceIndex(int i) override;
 
+  void updatePlotGuess(Mantid::API::MatrixWorkspace_sptr sampleWorkspace);
```
Comment (DanNixon) [inline qt/widgets/common/inc/MantidQtWidgets/Common/IndirectFitPropertyBrowser.h]: This should be a `MatrixWorkspace_const_sptr`.

**Review by DanNixon — CHANGES_REQUESTED** [review]
Changes work as expected, just one minor comment.

**Review by DanNixon — APPROVED** [review]
Looks good to me. Failed test is unrelated.
