### PR TITLE
Fix dragging and dropping files into Mantid on OSX

### LINKED ISSUE #20643: Drag & Drop files is broken on OSX
Reported by Jon. If you drag and drop files into the latest Mantid on OSX you get the following:
```
Failed to Load the file /.file/id=6571367.1067235 . The reason for failure is: Invalid value for property Filename (list of str lists) "/.file/id=6571367.1067235": File "/.file/id=6571367.1067235" not found
```
This appears to have been broken by apple between OSX 10.9 and 10.10. Qt5 appears to have fixed this issue but they have not back ported the fix to Qt4 so we are stuck. Instead we'll have to roll our own solution.

See this [Qt bug report](https://bugreports.qt.io/browse/QTBUG-40449?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel) for more details

### Expected behavior
Files should be loaded

### Actual behavior
Files are not loaded. You get the above error.

### Steps to reproduce the behavior
Drag and drop a file into the workspace side bar in Mantid.

### Platforms affected
OSX

### PR DESCRIPTION
**Pull request by samueljackson92**
**This needs both a Window/Linux and an OSX tester**

This adds a work around to a qt bug in Qt4 that breaks drag and drop on OSX.

**To test:**
 - With an OSX machine `>=10.10` test that you can reproduce the bug.
 - Apply the changes and check they fix the bug for OSX.
 - Check that drag & drop is not broken on Windows or Linux.
 - Also check the following places:
   - Dragging & dropping into the Load dialog works on OSX and Windows/Linux.
   - Dragging & dropping into the Python window works on OSX and Windows/Linux.

Fixes #20643 

**Release Notes** 
See the ui release notes for 3.11

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by gvardany** [comment]
Did not have time to look into the code, but could reproduce the error on OSX 10.11 El Capitan on master, and this fixes it. Drag&drop works on the workspace dock, python window and load dialog.

**Comment by samueljackson92** [comment]
Thanks for taking a look @gvardany

File: qt/widgets/common/inc/MantidQtWidgets/Common/DropEventHelper.h [hunk 1]
```diff
@@ -0,0 +1,23 @@
+#ifndef MANTIDQT_MANTIDWIDGETS_DRAGEVENTHELPER_H
```
Comment (OwenArnold) [inline qt/widgets/common/inc/MantidQtWidgets/Common/DropEventHelper.h]: Minor point. Naming of include guards don't match. File or class name.

File: qt/widgets/common/inc/MantidQtWidgets/Common/DropEventHelper.h [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+
+#include "MantidQtWidgets/Common/DllOption.h"
+
+#include <QDropEvent>
+#include <vector>
+
+namespace MantidQt {
+namespace MantidWidgets {
+
+class EXPORT_OPT_MANTIDQT_COMMON DropEventHelper {
```
Comment (OwenArnold) [inline qt/widgets/common/inc/MantidQtWidgets/Common/DropEventHelper.h]: Any point in having a class here? Couldn't this just be done with free functions and a new namespace?

File: qt/widgets/common/src/DropEventHelper.cpp [hunk 3]
```diff
@@ -0,0 +1,109 @@
...
+
+using namespace MantidQt::MantidWidgets;
+
+// Compile on OSX only.
+#if defined(__APPLE__)
+
+/** Workaround for bug on OSX >=10.10 with Qt4
+ *
+ * For more information see this bug report:
+ * https://bugreports.qt.io/browse/QTBUG-40449
```
Comment (OwenArnold) [inline qt/widgets/common/src/DropEventHelper.cpp]: 👍  for including the bug report.

File: qt/widgets/common/src/DropEventHelper.cpp [hunk 4]
```diff
@@ -0,0 +1,109 @@
...
+ * @return a list of file names as a QStringList
+ */
+QStringList DropEventHelper::getFileNames(const QDropEvent *event) {
+  QStringList filenames;
+  const auto mimeData = event->mimeData();
+  if (mimeData->hasUrls()) {
+    const auto urlList = mimeData->urls();
+    for (const auto &url : urlList) {
+      QUrl fileUrl;
+#if !defined(__APPLE__)
```
Comment (OwenArnold) [inline qt/widgets/common/src/DropEventHelper.cpp]: Suggestion: Instead of introducing another ifdef switch, you could provide a second "default" definition of `fixupURL` instead that effectively does nothing.

File: qt/widgets/common/src/DropEventHelper.cpp [hunk 5]
```diff
@@ -0,0 +1,109 @@
...
+      fileUrl = url;
+#else
+      fileUrl = fixupURL(url);
```
Comment (OwenArnold) [inline qt/widgets/common/src/DropEventHelper.cpp]: Suggestion: Instead of introducing another ifdef switch, you could provide a second "default" definition of fixupURL instead that effectively does nothing.

**Review by OwenArnold — CHANGES_REQUESTED** [review]
Mostly looks good. Some minor changes suggested.

File: qt/widgets/common/inc/MantidQtWidgets/Common/DropEventHelper.h [hunk 6]
```diff
@@ -9,12 +9,11 @@
...
 
-class EXPORT_OPT_MANTIDQT_COMMON DropEventHelper {
-public:
-  /// Get all filenames from a QDropEvent
-  static QStringList getFileNames(const QDropEvent *event);
-  /// Get all python files from q QDropEvent
-  static QStringList extractPythonFiles(const QDropEvent *event);
+namespace DropEventHelper {
+/// Get all filenames from a QDropEvent
+QStringList getFileNames(const QDropEvent *event);
```
Comment (OwenArnold) [inline qt/widgets/common/inc/MantidQtWidgets/Common/DropEventHelper.h]: You may need the export macros on these free functions

**Comment by martyngigg** [comment]
@samueljackson92 The PR is set to merge with `3.11` but it looks like it has `master` merged into it. Could you fix that, please?

**Comment by samueljackson92** [comment]
@martyngigg Should be fixed now.

**Comment by martyngigg** [comment]
@OwenArnold Is this okay to go now? It would be good to get this into the release.

**Review by OwenArnold — APPROVED** [review]

**Comment by OwenArnold** [comment]
Changes look good. I have not retested functionally, but I can't see how this would have been affected given the refactoring made.
