### PR TITLE
Indirect Iqt - Extra validation of input data

### LINKED ISSUE #25349: Indirect Iqt - Loading a res with an invalid number of histograms causes error when running
### Expected behavior
The res and sample number of histograms should be validated upon clicking run and then a useful message should appear.

### Actual behavior
When you click Run when you have a res file with an invalid number of histograms (needs to have a single histogram or an equal number of histograms to a sample), an error occurs in the results log.

### Steps to reproduce the behavior
1.`Interfaces`->`Indierct`->`Data Analysis`->`Iqt` tab
2. Load the data below
3. Click `Run`, error!

**Data Files**
Sample:
[iris26184_multi_graphite002_red.zip](https://github.com/mantidproject/mantid/files/3002203/iris26184_multi_graphite002_red.zip)
Resolution:
[irs26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/3002205/irs26176_graphite002_red.zip)

### Platforms affected
All

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work.**
This PR adds extra validation to the Iqt tab in Data Analysis so that a useful message is displayed to the user when the number of histogram in the resolution is invalid.

**To test:**
1.`Interfaces`->`Indierct`->`Data Analysis`->`Iqt` tab
2. Load the data below
3. Click `Run`
A useful error message should appear.

**Data Files**
Sample:
[iris26184_multi_graphite002_red.zip](https://github.com/mantidproject/mantid/files/3002203/iris26184_multi_graphite002_red.zip)
Resolution:
[iris26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/3032969/iris26176_graphite002_red.zip)

Fixes #25349

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/scientific_interfaces/Indirect/Iqt.cpp [hunk 1]
```diff
@@ -31,14 +34,71 @@ std::size_t getWsNumberOfSpectra(std::string const &workspaceName) {
   return getADSMatrixWorkspace(workspaceName)->getNumberHistograms();
 }
 
-bool checkADSForWorkspace(std::string const &workspaceName) {
+bool doesExistInADS(std::string const &workspaceName) {
```
Comment (TTitcombe) [inline qt/scientific_interfaces/Indirect/Iqt.cpp]: Do we  really need this function? Can we not just call ADS.doesExist when we need it?

File: qt/scientific_interfaces/Indirect/Iqt.cpp [hunk 2]
```diff
@@ -31,14 +34,71 @@ std::size_t getWsNumberOfSpectra(std::string const &workspaceName) {
...
+std::string checkParametersMatch(MatrixWorkspace_const_sptr sampleWorkspace,
+                                 MatrixWorkspace_const_sptr resolutionWorkspace,
+                                 std::string const &parameter) {
+  auto const sampleInstrument = sampleWorkspace->getInstrument();
+  auto const resolutionInstrument = resolutionWorkspace->getInstrument();
+  return checkInstrumentParametersMatch(sampleInstrument, resolutionInstrument,
+                                        parameter);
+}
+
+std::string checkParamsMatch(std::string const &sampleName,
```
Comment (TTitcombe) [inline qt/scientific_interfaces/Indirect/Iqt.cpp]: I would probably overload `checkParametersMatch`, rather than using slightly different function names. That way you don't have to remember which function name is for which inputs

**Review by TTitcombe — CHANGES_REQUESTED** [review]

**Comment by TTitcombe** [comment]
What error message should appear? I don't see anything

**Comment by robertapplin** [comment]
@TTitcombe  Here is the correct resolution file to use 
[iris26176_graphite002_red.zip](https://github.com/mantidproject/mantid/files/3032970/iris26176_graphite002_red.zip)

**Review by TTitcombe — APPROVED** [review]

**Comment by TTitcombe** [comment]
Change changes look good. A useful error message appears when I run the attached data
