### PR TITLE
Fix usage stats for IndirectSettings

### LINKED ISSUE #36230: Indirect Settings Usage statistics are misleading
**Describe the bug**
The usage statistics for the Indirect Settings interface stored by the Usage Reporter are misleadingly high. I believe this is because whenever an IndirectInterface instance is created, a IndirectSettingsInterface is also created immediately (even if Indirect Settings hasn't been open). We should only create an Indirect Settings interface if the settings button is clicked - and this should fix the misleadingly high usage statistics.

**To Reproduce**
Log on to the Usage reporter
Search for the usage statistics for the IndirectSettings interface
It is roughly the total of all Indirect interfaces put together

**Expected behavior**
The usage statistics for the IndirectSettings interface should only record the number of times the interface was opened.

### PR DESCRIPTION
**Pull request by robertapplin**
**Description of work**
This PR does two things:
- It fixes the issue described in #36230 by only creating a settings interface when the settings button is clicked
- It does a small bit of refactoring of the IndirectSettings interface

The refactoring means that:
- The `IndirectSettingsPresenter` class is no longer tied to the Qt framework. (by using a subscriber pattern rather than connecting slots)
- The `IndirectSettingsPresenter` now has a non-owning raw-pointer to the view. The view is a top level widget owned by the QApplication
- The `IndirectInterface` no longer owns the `IndirectSettings` object. Again, this object is a top level widget and so the owner is the QApplication

**To test:**
Open any indirect interface
Click on the Settings icon (bottom left)
Adjust a setting and apply
Close and open the settings GUI to check the change was saved.
Open a second Indirect Interface and check that changing a setting will update the setting on all opened Indirect interfaces. The help menu should give a good explanation for what each option does.

Fixes #36230

*This does not require release notes* because **there are no user-facing changes in this PR**

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

File: qt/scientific_interfaces/Indirect/IndirectSettingsPresenter.h [hunk 1]
```diff
@@ -12,41 +12,32 @@
...
 private:
-  void setUpPresenter();
-  void setDefaultRestrictData() const;
   void saveSettings();
 
   void setApplyingChanges(bool applyingChanges);
 
   std::unique_ptr<IndirectSettingsModel> m_model;
-  std::unique_ptr<IIndirectSettingsView> m_view;
+  IIndirectSettingsView *m_view;
```
Comment (GuiMacielPereira) [inline qt/scientific_interfaces/Indirect/IndirectSettingsPresenter.h:39]: As I am quite new to C++, I am going to be asking some questions that might not make much sense. These questions are for me to learn rather than to suggest a change to the code. Okay so, in this particular case, you changed a unique pointer to the view to a normal pointer, but kept a unique pointer to the model. Does this have anything to do with the fact that the view inherits form QWidget?

File: qt/scientific_interfaces/Indirect/IndirectSettingsPresenter.cpp [hunk 2]
```diff
@@ -5,53 +5,35 @@
...
 
-void IndirectSettingsPresenter::setDefaultRestrictData() const {
-  auto const isisFacility = m_model->getFacility() == "ISIS";
-  if (isisFacility)
-    setRestrictInputDataByName(isisFacility);
-}
+QWidget *IndirectSettingsPresenter::getView() { return m_view->getView(); }
 
-IIndirectSettingsView *IndirectSettingsPresenter::getView() { return m_view.get(); }
+void IndirectSettingsPresenter::subscribeParent(IIndirectSettings *parent) { m_parent = parent; }
```
Comment (GuiMacielPereira) [inline qt/scientific_interfaces/Indirect/IndirectSettingsPresenter.cpp:23]: I found this method a bit confusing. From what I gathered, here m_parent is a private attribute of the class, and not a fancy way of enforcing inheritance, right? So here any methods from the m_parent class need to be called as m_parent->method, and are not available from inheritance, correct?

**Review by GuiMacielPereira — COMMENTED** [review]
As I am quite new to C++, I left some questions that might not make much sense. These questions are for me to learn rather than to suggest a change to the code.

File: qt/scientific_interfaces/Indirect/IndirectSettingsPresenter.h (hunk 1 above)
Comment (robertapplin) [reply qt/scientific_interfaces/Indirect/IndirectSettingsPresenter.h:39]: Yes it does indeed. All of the QWidgets are owned by the QApplication, and so the QApplication handles their lifetime and makes sure they get deleted. This means we do not want to use an owning-pointer such as a unique pointer in our presenter. Owning a QWidget in two places may cause issues if the widget gets cleaned up from one location, but not the other

File: qt/scientific_interfaces/Indirect/IndirectSettingsView.cpp [hunk 3]
```diff
@@ -5,27 +5,32 @@
...
 
-void IndirectSettingsView::emitApplyClicked() { emit applyClicked(); }
+void IndirectSettingsView::subscribePresenter(IndirectSettingsPresenter *presenter) { m_presenter = presenter; }
 
-void IndirectSettingsView::emitCancelClicked() { emit cancelClicked(); }
+void IndirectSettingsView::notifyOkClicked() { m_presenter->notifyOkClicked(); }
+
+void IndirectSettingsView::notifyApplyClicked() { m_presenter->notifyApplyClicked(); }
+
+void IndirectSettingsView::notifyCancelClicked() { m_presenter->notifyCancelClicked(); }
```
[the remark this answers is not in the document]
Comment (robertapplin) [reply qt/scientific_interfaces/Indirect/IndirectSettingsView.cpp:33]: Yes, the main alteration is that rather than connecting the view to the presenter (which requires the presenter to be a QObject), instead the presenter is subscribed to the view using a non-owning raw pointer. This allows the view to call directly to the presenter without sending Qt signals across the view-presenter boundary. It is a much preferred implementation for the reasons outlined in the description of this issue #36324

This method of doing things is called an Observer pattern

File: qt/scientific_interfaces/Indirect/IndirectSettingsPresenter.cpp (hunk 2 above)
Comment (robertapplin) [reply qt/scientific_interfaces/Indirect/IndirectSettingsPresenter.cpp:23]: Yes you are right, `m_parent` does not refer to anything which is inherited. In this context, `m_parent` refers to the owner of the `IndirectSettingsPresenter` (i.e. the class that creates and holds a unique pointer to the `IndirectSettingsPresenter`)

File: qt/scientific_interfaces/Indirect/IndirectInterface.cpp [hunk 4]
```diff
@@ -13,29 +14,31 @@ using namespace MantidQt::API;
...
+  auto settingsWindow = dynamic_cast<IndirectSettings *>(subWindow);
+  settingsWindow->connectInterface(this);
+
+  settingsWindow->loadSettings();
+  settingsWindow->setWindowModality(Qt::WindowModal);
+  settingsWindow->show();
 }
 
-void IndirectInterface::applySettings() { applySettings(getInterfaceSettings()); }
+void IndirectInterface::applySettings() { applySettings(IndirectSettings::getSettings()); }
```
Comment (GuiMacielPereira) [inline qt/scientific_interfaces/Indirect/IndirectInterface.cpp:38]: I found this line interesting because you added a default constructor with no arguments to call another constructor with the settings argument. Is there a benefit in doing this rather than skipping the step of calling a second constructor with the settings argument? Maybe because it gives the functionality of applying settings that come from elsewhere?

**Review by GuiMacielPereira — COMMENTED** [review]
- Still looking at some bits of the code to try to understand what is going on

File: qt/scientific_interfaces/Indirect/IndirectInterface.cpp (hunk 4 above)
Comment (robertapplin) [reply qt/scientific_interfaces/Indirect/IndirectInterface.cpp:38]: I believe I did this just for the convenience of not needing to called `IndirectSettings::getSettings()` in each location I want to apply the settings. Overloading functions is very useful when you have two (or more) functions that do the same thing, but they have different parameter arguments https://www.geeksforgeeks.org/function-overloading-c/

**Review by GuiMacielPereira — COMMENTED** [review]
- Followed the test instructions and verified that changing the settings in any one indirect interface changes the settings in the others. 
- Any change in settings is also correctly shown when opening the settings window independently, i.e. indirect > settings.
- I looked at the code to the best of my ability and it looks very clean, but given my limited experience with C++ I am letting the other reviewers approve the PR.

**Review by adriazalvarez — APPROVED** [review]
I have tested the new interface settings and it is working as intended. 
Changes in one indirect/inelastic interface settings are reflected on others. 
The code is modified in all interfaces requiring an indirect settings window and works well in all of them. Also, unit-test for the interface is added. 

The exchange between Gui and Rob has been also very illustrative and useful for reviewing.

Examining the code, I think it looks good and while I'm not the ultimate authority on design patterns in C++,  I think it can be approved since it's been tested and tried by two independent reviewers with no fault.
