### PR TITLE
Fix for bug with the algorithm name alias

### LINKED ISSUE #37112: Algorithm lists search bar "Execute" button doesn't always open correct algorithm
**Describe the bug**
Clicking the "Execute" button next to the name of an algorithm (which is in alias) in the algorithm lists will open the latest version even when the alias refers to a previous version of the algorithm.

**To Reproduce**

1. Open Mantid Workbench
2. Type "SaveAsciiTosca" in the algorithm list search bar
3. Click "Execute"
4. It will open the algorithm dialog for "Save Ascii v2" rather than "Save Ascii v1". "Save Ascii v1" is the algorithm with the "SaveAsciiTosca" alias

**Expected behavior**
It should open the algorithm dialog for the correct algorithm.

**Platform/Version (please complete the following information):**
 - OS: Found on Windows, but exists on all.

### PR DESCRIPTION
**Pull request by jhaigh0**
### Description of work

Fixed a bug where if an algorithm.v1 had the alias "hello" and algorithm.v2 did not, executing the algorithm "hello" would give algorithm.v2 (the latest version). The alias will now respect which version of the original algorithm it has been assigned to.

Fixes #37112

### To test:

Follow the example from the issue.

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

File: Framework/API/inc/MantidAPI/AlgorithmFactory.h [hunk 1]
```diff
@@ -111,8 +112,8 @@ class MANTID_API_DLL AlgorithmFactoryImpl final : public Kernel::DynamicFactory<
   const std::vector<std::string> getKeys() const override;
   const std::vector<std::string> getKeys(bool includeHidden) const;
 
-  /// Get an algorithms name from the alias map
-  boost::optional<std::string> getRealNameFromAlias(const std::string &alias) const noexcept;
+  /// Get an algorithms name and version from the alias map
+  boost::optional<std::pair<std::string, int>> getRealNameFromAlias(const std::string &alias) const noexcept;
```
Comment (robertapplin) [inline Framework/API/inc/MantidAPI/AlgorithmFactory.h:116]: Would it be possible to modernise this code by using `std::optional` instead of `boost::optional`?

File: Framework/API/src/AlgorithmFactory.cpp [hunk 2]
```diff
@@ -234,13 +235,10 @@ int AlgorithmFactoryImpl::highestVersion(const std::string &algorithmName) const
...
-    if (realName != boost::none) {
-      viter = m_vmap.find(realName.get());
-    }
-    if (viter != m_vmap.end())
-      return viter->second;
-    else {
+    const auto realNameAndVersion = getRealNameFromAlias(algorithmName);
+    if (realNameAndVersion != boost::none) {
+      return realNameAndVersion->second;
+    } else {
```
Comment (robertapplin) [inline Framework/API/src/AlgorithmFactory.cpp:241]:
```suggestion
    if (const auto realNameAndVersion = getRealNameFromAlias(algorithmName)) {
      return realNameAndVersion->second;
    } else {
```

**Review by robertapplin — CHANGES_REQUESTED** [review]
Code looks good and works as expected. Just had a few suggestions, but no need to do them if you think it isn't worth it!

File: Framework/API/src/AlgorithmFactory.cpp (hunk 2 above)
Comment (jhaigh0) [reply Framework/API/src/AlgorithmFactory.cpp:241]: is this suggestion reliant on me changing it to use `std::optional`?

Comment (robertapplin) [reply Framework/API/src/AlgorithmFactory.cpp:241]: I think this should work for `boost::optional` too, but I might be wrong!

Comment (jhaigh0) [reply Framework/API/src/AlgorithmFactory.cpp:241]: I'll do both changes anyway :)

**Review by robertapplin — APPROVED** [review]
Thanks for removing the use of boost - this looks good! Typing in an alias and pressing Enter will now open the correct algorithm, even if there is a newer version of the same algorithm but without the defined alias 👍
