### PR TITLE
LoadNexusProcessed can now handle the special case of TextAxis with empty label

### LINKED ISSUE #17479: LoadNexusProcessed failing if Y Axis is TextAxis and is an empty string
### Expected behavior

The `VanCurvesWorkspace` is properly loaded into Mantid after selecting it through Load.
### Actual behavior

Nothing is loaded and the following error is produced in the Log:

```
Error in execution of algorithm LoadNexusProcessed:
Attempt to load from an empty dataset /mantid_workspace_1/workspace/axis2
Error in execution of algorithm Load:
Attempt to load from an empty dataset /mantid_workspace_1/workspace/axis2
```
### Steps to reproduce the behavior

Vanadium Workspace: ENGINX00246043.nxs
Input Workspace: ENGINX00249918.nxs

Run `EnggVanadiumCorrections` and save out the curves workspace then view Axis 2 in HDF view - it will be textType and contain no data within.
### Platforms affected

All

### PR DESCRIPTION
**Pull request by dtasev**
### Description of work.

`LoadNexusProcessed` will now properly handle a TextAxis with an empty label.
2 Unit tests have also been added to test for loading a TextAxis with an empty label, and for a TextAxis with a non-empty label

**To test:**
- Run LoadNexusProcessed unit tests
- Try to load a workspace with a TextAxis and empty label ([van_corrections ws](https://drive.google.com/file/d/0B2Mj8e56Z8xTWUE2eGdMRDBjQ1k/view?usp=sharing)) 

Fixes #17479 .

_Does not need to be in the release notes._

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/DataHandling/src/LoadNexusProcessed.cpp [hunk 1]
```diff
@@ -1721,8 +1721,13 @@ void LoadNexusProcessed::loadNonSpectraAxis(
...
   } else if (axis->isText()) {
     NXChar axisData = data.openNXChar("axis2");
-    axisData.load();
-    std::string axisLabels(axisData(), axisData.dim0());
+    std::string axisLabels;
+    try {
+      axisData.load();
+      axisLabels = std::string(axisData(), axisData.dim0());
+    } catch (std::exception &) {
+      axisLabels = "";
```
Comment (DavidFair) [inline Framework/DataHandling/src/LoadNexusProcessed.cpp]: Could we log a warning here that the axis label was blank just in case?

File: Framework/DataHandling/test/LoadNexusProcessedTest.h [hunk 2]
```diff
@@ -983,6 +983,48 @@ class LoadNexusProcessedTest : public CxxTest::TestSuite {
...
+    TS_ASSERT_THROWS_NOTHING(loader.initialize());
+    TS_ASSERT_THROWS_NOTHING(
+        loader.setPropertyValue("Filename", "workspaceEmptyTextAxis.nxs"));
+    TS_ASSERT_THROWS_NOTHING(loader.setPropertyValue("OutputWorkspace", "ws"));
+
+    TS_ASSERT(loader.execute());
+    TS_ASSERT(loader.isExecuted());
+
+    Workspace_sptr ws = loader.getProperty("OutputWorkspace");
+    auto outWS = boost::dynamic_pointer_cast<MatrixWorkspace>(ws);
```
Comment (DavidFair) [inline Framework/DataHandling/test/LoadNexusProcessedTest.h]: `const`

File: Framework/DataHandling/test/LoadNexusProcessedTest.h [hunk 3]
```diff
@@ -983,6 +983,48 @@ class LoadNexusProcessedTest : public CxxTest::TestSuite {
...
+    TS_ASSERT_THROWS_NOTHING(loader.initialize());
+    TS_ASSERT_THROWS_NOTHING(
+        loader.setPropertyValue("Filename", "workspaceWithTextAxis.nxs"));
+    TS_ASSERT_THROWS_NOTHING(loader.setPropertyValue("OutputWorkspace", "ws"));
+
+    TS_ASSERT(loader.execute());
+    TS_ASSERT(loader.isExecuted());
+
+    Workspace_sptr ws = loader.getProperty("OutputWorkspace");
+    auto outWS = boost::dynamic_pointer_cast<MatrixWorkspace>(ws);
```
Comment (DavidFair) [inline Framework/DataHandling/test/LoadNexusProcessedTest.h]: `const`

File: Framework/DataHandling/src/LoadNexusProcessed.cpp (hunk 1 above)
Comment (DimitarTasev) [inline Framework/DataHandling/src/LoadNexusProcessed.cpp]: I'm thinking do we want to log a `warning` or `information`, I think the best place for the warning would be during saving?

**Comment by DavidFair** [comment]
This resolves the issues that were occurring with loading files with empty axis labels. :shipit:

**Comment by DavidFair** [comment]
:shipit:
