### PR TITLE
Kafka decoder can handle varying periods between runs

### LINKED ISSUE #21481: Messages can be lost by KafkaLiveListener at run transitions
Messages from the next run are ignored if the end of run has not yet been reached in all topic-partitions in the current run. This causes loss of messages if the `restart` or `rename` run transition option is chosen.

### LINKED ISSUE #22654: Kafka Live Listener causes Mantid crash when number of periods changes between runs
**Original reporter:** ISIS/Rob Dalgliesh

### Expected behavior

When the number of periods changes between runs, a new workspace group should be created containing one workspace per period for the, possibly changed, number of periods.

### Actual behavior

"If you start a live view when e.g. larmor running say 2 periods and then they change to a higher number of periods in the next run it crashes mantid. If you start the live view when it has a higher number of periods, it doesn’t crash when the instrument changes to a lower number of periods but you are left with a lot of blank workspaces for the undefined periods."

### Steps to reproduce the behavior
It should be possible to create a test which reproduces the behaviour. See `mantid/Framework/LiveData/test/KafkaEventStreamDecoderTest.h` for similar tests which fake the Kafka interface. Fakes are in `mantid/Framework/LiveData/test/KafkaTesting.h`.

### Platforms affected
All

### More details
We can talk more about this in person, but here are a few more details.

It may be worth reading https://kafka.apache.org/intro, particularly if you are interested anyway. You can ignore anything about "Streams API", "Connector API" or stream processing.

The number of periods is information which is sent in the run start message in the run topic, see https://github.com/mantidproject/mantid/blob/ded5399207c0e421f96652b950b6624ba119497f/Framework/LiveData/src/Kafka/KafkaEventStreamDecoder.cpp#L619 
I think the "correct" fix would be to stop the stream when an end of run message is received and start new runs from scratch (creating new buffer workspaces). I had already done some refactoring in that direction. There is no risk of losing data this way as Kafka itself acts as a buffer.

### PR DESCRIPTION
**Pull request by ElliotAOram**
**Description of work.**
The Kafka decoder has been updated to reset the local caches fully when the current run stops. The most recent new run signal is now cached and then the local caches are updated with these values after the run stop signal is received.

This change means that Live data can now handle changing period numbers between runs. 

A new test case has been added to validate this. In addition the unit test framework had to be updated to handle the ability to stop a run and start a new one without changing the decoder. As such the `startCapture` function has been refactored to have a `startCapture` and a `continueCapture`. This is allows for the data to be extracted between the end of the first run and the start of the second run. 

**Report to:** ISIS/Rob Dalgliesh

**To test:**

* Code review on the new test framework areas and changes to local caching
* Validate that the unit test implemented exercises the problem of having varying period between runs for a single decoder instance
* Ensure  ALL* the unit tests pass for `KafkaEventStreamDecoderTest.h`

Fixes #22654
Fixes #21481

[release notes](https://github.com/mantidproject/mantid/blob/231b3b105563b775467cc53a688b84a37593e355/docs/source/release/v3.13.0/framework.rst)

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [x] Are the unit tests small and test the class in isolation?
- [x] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [x] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by BhuvanBezawada** [comment]
Hi Nick, I'd be happy to help! I'll have a look at this now.

**Comment by matthew-d-jones** [comment]
This is now in a mostly-working state, and most importantly the `KafkaEventListener` looks good and is well tested.

There are some remaining problems for which I've created a new ticket: https://github.com/mantidproject/mantid/issues/22932
These appear to be due to behaviour of `MonitorLiveData` and/or `LoadLiveData`, probably affect all live listeners and shouldn't be tackled in this PR.

**Comment by NickDraper** [comment]
Ok we just need an approved review on the PR for us to merge it

**Comment by matthew-d-jones** [comment]
@NickDraper :+1: Bhuvan will review after lunch.

File: Framework/LiveData/src/Kafka/KafkaEventStreamDecoder.cpp [hunk 1]
```diff
@@ -444,10 +464,79 @@ void KafkaEventStreamDecoder::waitForRunEndObservation() {
...
+        if (runStartStruct.runNumber > m_runNumber) {
+          runStartStructOutput = runStartStruct;
+          m_runNumber = runStartStruct.runNumber;
+          return false; // not interrupted
+        }
+      } else {
+        continue;
+      }
+    }
+  }
```
Comment (BhuvanBezawada) [inline Framework/LiveData/src/Kafka/KafkaEventStreamDecoder.cpp]: Same as above.

File: Framework/LiveData/test/KafkaTesting.h [hunk 2]
```diff
@@ -387,6 +388,125 @@ class FakeRunInfoStreamSubscriber
...
+    std::unordered_map<std::string, std::vector<int64_t>> offsets;
+    return offsets;
+  }
+  void seek(const std::string &topic, uint32_t partition,
+            int64_t offset) override {
+    UNUSED_ARG(topic);
+    UNUSED_ARG(partition);
+    UNUSED_ARG(offset);
+  }
+
```
Comment (BhuvanBezawada) [inline Framework/LiveData/test/KafkaTesting.h]: Probably best to have a line spacing between each of the methods that have been implemented here? I think it would make the code a bit easier to read...

File: Framework/LiveData/test/KafkaTesting.h [hunk 3]
```diff
@@ -387,6 +388,125 @@ class FakeRunInfoStreamSubscriber
...
+  getCurrentOffsets() override {
+    return {std::pair<std::string, std::vector<int64_t>>(m_topicName, {2})};
+  }
+  void seek(const std::string &topic, uint32_t partition,
+            int64_t offset) override {
+    UNUSED_ARG(topic);
+    UNUSED_ARG(partition);
+    UNUSED_ARG(offset);
+  }
+
```
Comment (BhuvanBezawada) [inline Framework/LiveData/test/KafkaTesting.h]: Same as above...

**Review by BhuvanBezawada — CHANGES_REQUESTED** [review]
The code looks great! 👍 

Just a few minor changes needed to make the code clearer and easier to understand. 

All the unit tests seem to pass on the build servers and the new unit test implemented does seem to cover the issue of having varying periods between runs.

**Review by BhuvanBezawada — APPROVED** [review]
