### PR TITLE
Fix dx setter bug

### LINKED ISSUE #15933: Bugfix for MatrixWorkspace x uncertainty setter
A setter method `setDX` in `MatrixWorkspace.h` forwards to`setX instead of `setDx` in the underlying `iSpecturm`. This needs to be fixed and unit tests retro-fitted.

### PR DESCRIPTION
**Pull request by AntonPiccardoSelg**
Fixes #15933 

This PR fixes a bug in the `MatrixWorkspace` setters. One of the `setDx` overloads forwarded the request to `setX` instead of `setDx`. This should be fixed. A unit test for the X uncertainty accessor methods was added.

**To test:**
Code review and confirm that test covers the three input scenarios.

<!-- RELEASE NOTES
Not needed, Mantid internal

---
#### Reviewer

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):
##### Code Review
- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the coding standards? Is it well structured with small focussed classes/methods/functions?
- [x] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?
##### Functional Tests
- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?
- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/API/test/MatrixWorkspaceTest.h [hunk 1]
```diff
@@ -1291,6 +1291,97 @@ class MatrixWorkspaceTest : public CxxTest::TestSuite {
...
+    const double value0 = 10;
+    const double value1 = 11;
+    const double value2 = 12;
+
+    Mantid::MantidVec dxSpec0(j, value0);
+    Mantid::MantidVecPtr dxSpec1;
+    auto &spec1 = dxSpec1.access();
+    spec1.resize(j, value1);
+    boost::shared_ptr<Mantid::MantidVec> dxSpec2(
+        new Mantid::MantidVec{value2, value2, value2});
```
Comment (quantumsteve) [inline Framework/API/test/MatrixWorkspaceTest.h]: use `boost::make_shared`

File: Framework/API/test/MatrixWorkspaceTest.h [hunk 2]
```diff
@@ -1291,6 +1291,97 @@ class MatrixWorkspaceTest : public CxxTest::TestSuite {
...
+    TSM_ASSERT_EQUALS("Should have x resolution values of 11", (*ref1)[1],
+                      value1);
+    auto ref2 = ws.refDx(2);
+    TSM_ASSERT_EQUALS("Should have x resolution values of 12", (*ref2)[2],
+                      value2);
+
+    TSM_ASSERT("Should not have any x resolution values", !ws.hasDx(3));
+  }
+
 private:
```
Comment (quantumsteve) [inline Framework/API/test/MatrixWorkspaceTest.h]: While you're modifying this test, would you also cleanup the member function below? 

- use `boost::make_shared` instead of `new`
- Change the outer loop to a range-based for loop.
- The inner loop can be replaced by [std::iota](http://www.cplusplus.com/reference/numeric/iota/).

File: Framework/API/test/MatrixWorkspaceTest.h [hunk 3]
```diff
@@ -1291,6 +1291,97 @@ class MatrixWorkspaceTest : public CxxTest::TestSuite {
...
+    ws.init(numspec, j, k);
+
+    const double value0 = 10;
+    const double value1 = 11;
+    const double value2 = 12;
+
+    Mantid::MantidVec dxSpec0(j, value0);
+    Mantid::MantidVecPtr dxSpec1;
+    auto &spec1 = dxSpec1.access();
+    spec1.resize(j, value1);
```
Comment (quantumsteve) [inline Framework/API/test/MatrixWorkspaceTest.h]: I think these three lines can be reduced to one with `make_cow`

File: Framework/API/test/MatrixWorkspaceTest.h [hunk 4]
```diff
@@ -1291,6 +1291,97 @@ class MatrixWorkspaceTest : public CxxTest::TestSuite {
...
+    // Test dataDx
+    TSM_ASSERT("Should have x resolution values", ws.hasDx(0));
+    TSM_ASSERT_EQUALS("Should have a length of 3", ws.dataDx(0).size(), j);
+    TSM_ASSERT_EQUALS("Should have x resolution values of 10", ws.dataDx(0)[0],
+                      value0);
+    TSM_ASSERT_EQUALS("Should have x resolution values of 10", ws.dataDx(0)[1],
+                      value0);
+    TSM_ASSERT_EQUALS("Should have x resolution values of 10", ws.dataDx(0)[2],
+                      value0);
+
```
Comment (quantumsteve) [inline Framework/API/test/MatrixWorkspaceTest.h]: Should we obtain a reference once, then call the subscript operator multiple times? I just don't want to encourage anyone to repeatedly call `.dataDx()` somewhere where it adds unnecessary overhead.

**Comment by quantumsteve** [comment]
LGTM. :shipit:

File: Framework/API/test/MatrixWorkspaceTest.h (hunk 2 above)
Comment (quantumsteve) [inline Framework/API/test/MatrixWorkspaceTest.h]: The other member function cleanup is unrelated and should be moved to a separate issue/pull request.
