### PR TITLE
Miscellaneous multiple scattering fixes for PEARL validation

### LINKED ISSUE #31892: Miscellaneous Muscat fixes to support PEARL validation
The CalculateMultipleScattering algorithm has been run on some PEARL data with the aim of sharing with the instrument scientists as part of the ongoing process of validating the results. This has highlighted a few problems that have been fixed and some performance improvements have also been applied:
- less verbose logging on the number of calls to InterceptSurface
- added algorithm to the absorption corrections and multiple scattering concept page
- changes to the interpolation code to speed it up and to remove call to yIndexOfX which wasn't doing the right thing - should always be picking the x value to the left of the supplied x
- set random number seed based on spec number rather than index so that you get the same answer for a particular spectrum whether it's run on its own or as part of a larger workspace
- stop workspaces in an existing MuscatResults workspace group being overwritten by a second run of the algorithm. Mimic the Load behaviour for groups where an _1 is appended to the workspace name if a name clash exists

### PR DESCRIPTION
**Pull request by DannyHindson**
**Description of work.**

Set of changes that came from running some multiple scattering calculations on PEARL datasets supplied by Nick Funnel. This revealed some performance issues and also a couple of bugs. See description on linked issue for details.

**To test:**

Unzip the attached input files + update the input folder in the following script.

Run the script which tests a couple of the changes (change to random seed, changes to workspace naming to avoid overwrite) and also acts as a general sanity check. 

Check that the results for spectrum 20 are the same in both output workspace groups. It uses a low number of scenarios so the answer won't be v accurate but you can see the result for spectrum 20 is unchanged. 

Also check that the names of the workspaces in the output workspace groups from the two calls to CalculateMultipleScattering are distinct.
```
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

def loadPEARLWSAndRunMS(SpectrumList, OutputName):
    inputWS = Load(Filename=os.path.join(folder,'PEARL00115245.nxs'), SpectrumList=SpectrumList) # Ce02
    # S(Q) has been cropped 1500 to 19995 during PEARL data reduction so do same here
    inputWS = CropWorkspace(inputWS, 1500, 19995)
    inputWS = ConvertUnits(inputWS, Target="Wavelength")

    # 5mm x 5mm beam
    SetBeam(inputWS, Geometry={'Shape': 'Slit', 'Width': 0.5, 'Height': 0.5})
    # 6mm diameter can
    SetSample(InputWorkspace=inputWS,Geometry={'Shape': 'Cylinder', 'Height': 4.0,
                        'Radius': 0.2985, 'Center': [0.,0.,0.]},
              Material={'ChemicalFormula': 'Ce-O2', 'MassDensity': 7.215})
           
    CalculateMultipleScattering(InputWorkspace=inputWS,SofqWorkspace=SOfQ,
           NeutronPathsSingle=100,NeutronPathsMultiple=100, NumberScatterings=3, 
           OutputWorkspace=OutputName, Interpolation="Linear", NumberOfWavelengthPoints=300)

folder = r"C:\Multiple Scattering\PEARL tests"
SOfQ = Load(Filename=os.path.join(folder,'PRL115245-115251_tt70_mods1-9_Q.nxs')) #Ce02
# scale S(Q) so it tends to 1 at large q - rough approach for now
high_q = SOfQ.dataY(0)[-9:]
high_q_avg = sum(high_q)/len(high_q)
SOfQ_y = SOfQ.dataY(0)
SOfQ_y /= high_q_avg

SOfQ_x = SOfQ.dataX(0)
average_q_spacing = (SOfQ_x[-1]-SOfQ_x[0])/(SOfQ_x.size-1)
SOfQ=Rebin(SOfQ,[SOfQ_x[0],average_q_spacing,SOfQ_x[-1]])

loadPEARLWSAndRunMS('', "MuscatResults")
loadPEARLWSAndRunMS(20, "MuscatResultsSp20")
```
[PEARLFiles.zip](https://github.com/mantidproject/mantid/files/6724707/PEARLFiles.zip)

Fixes #31892.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Algorithms/src/CalculateMultipleScattering.cpp [hunk 1]
```diff
@@ -752,5 +783,34 @@ void CalculateMultipleScattering::interpolateFromSparse(MatrixWorkspace &targetW
...
+  }
+}
+
+/**
+ * Set the name on a workspace, adjusting for potential clashes in the ADS.
+ * Used to set the names on the output workspace group members. N
+ * @param ws The ws to set the name on
+ * @param wsName The name to set on the workspace
+ */
+void CalculateMultipleScattering::setWorkspaceName(const API::MatrixWorkspace_sptr &ws, std::string wsName) {
```
Comment (DavidFair) [inline Framework/Algorithms/src/CalculateMultipleScattering.cpp:810]: If someone runs CalculateMultipleScattering twice, will this result in the numbers incrementing from `name_n` to `name_2n` or overwrite it?

I ask as this differs from the normal behaviour of Mantid Algorithms which is to overwrite. So this becomes the exception to the rule when setting the output name to something that already exists? Equally, I may be misreading this a bit...

File: Framework/Algorithms/test/CalculateMultipleScatteringTest.h [hunk 2]
```diff
@@ -103,25 +112,29 @@ class CalculateMultipleScatteringTest : public CxxTest::TestSuite {
     TS_ASSERT_THROWS_NOTHING(alg->setProperty("InputWorkspace", inputWorkspace));
     const int NSCATTERINGS = 2;
     TS_ASSERT_THROWS_NOTHING(alg->setProperty("NumberScatterings", NSCATTERINGS));
-    TS_ASSERT_THROWS_NOTHING(alg->setProperty("NeutronPathsSingle", 10000));
-    TS_ASSERT_THROWS_NOTHING(alg->setProperty("NeutronPathsMultiple", 10000));
+    TS_ASSERT_THROWS_NOTHING(alg->setProperty("NeutronPathsSingle", 100000));
```
Comment (DavidFair) [inline Framework/Algorithms/test/CalculateMultipleScatteringTest.h:115]: I checked this in release and debug mode and it increases the test time from 10->20s in Debug and 1 to 2 in Release

For people developing on the algorithm on MSVC Debug in the future, do we need the higher number of paths?

**Review by DavidFair — COMMENTED** [review]
I've just got to test this (will do first thing tomorrow), in the interim I wanted to ask if there was a perf improvement from these changes?
I notice in a few loops we no longer do the same calls over and over again / point around atomic pointers. Does it make any measurable difference at all?

File: Framework/Algorithms/src/CalculateMultipleScattering.cpp (hunk 1 above)
Comment (DannyHindson) [reply Framework/Algorithms/src/CalculateMultipleScattering.cpp:810]: I made this change to try and deal with the situation where someone runs it twice with OutputWorkspace set to different values eg "MuscatResultsOne" and "MuscatResultsTwo". As a result of this change they will end up with the following workspaces where the unindented ones are group workspaces:

MuscatResultsOne
- Scatter_1_No_Abs
- Scatter_1
- Scatter_2

MuscatResultsTwo
- Scatter_1_No_Abs_1
- Scatter_1_1
- Scatter_2_1

Before this change you'd end up with two group workspaces containing the same child workspaces. These get listed twice in the ADS so it was a bit confusing.

I think you have a good point though. I seem to have broken the more simple case where someone just runs the algorithm twice with the same settings. This should overwrite the previous outputs. I should probably add a line to try and delete the output group workspace named in the "OutputWorkspace" parameter from the ADS (including its children) before writing any of the new outputs.

The method correctForWorkspaceNameClash is copied from LoadNexusProcessed::correctForWorkspaceNameClash so hopefully the approach for avoiding the name clash when it's actually needed is fairly standard

File: Framework/Algorithms/test/CalculateMultipleScatteringTest.h (hunk 2 above)
Comment (DannyHindson) [reply Framework/Algorithms/test/CalculateMultipleScatteringTest.h:115]: The change I'd made to the way the random number seed is generated:

```MersenneTwister rng(seed + specNo);```

meant that this test wasn't passing any more. I concluded that I'd simply got lucky before in that the Monte Carlo simulation wasn't properly converged but the default seed happened to give an answer v close to the theoretical result. In order to get it to pass I had to increase the number of scenarios so the simulation was more fully converged. So I think this is unavoidable unfortunately - I could reduce the tolerance of the TS_ASSERT_DELTA later on I guess but the extra run time didn't seem to bad?

**Comment by DannyHindson** [comment]
> I've just got to test this (will do first thing tomorrow), in the interim I wanted to ask if there was a perf improvement from these changes?
> I notice in a few loops we no longer do the same calls over and over again / point around atomic pointers. Does it make any measurable difference at all?

Yes these changes did improve the performance. I'll see if I have some figures from measurements I made when I did the changes. Some of the performance gain was visible only in debug builds but that was useful in helping me track down bugs on real datasets in less than infinite time!

File: Framework/Algorithms/test/CalculateMultipleScatteringTest.h (hunk 2 above)
Comment (DavidFair) [reply Framework/Algorithms/test/CalculateMultipleScatteringTest.h:115]: On balance I'd rather have the longer runtime and increased accuracy rather than a fast inaccurate test :+1:

**Review by DavidFair — APPROVED** [review]
This correctly renamed this workspaces, and I checked overwriting a WS group with the same name works correctly too.

Thanks for addressing those points, if there is only a negligible performance increase in release mode for users I think it's unnecessary to add it to the release notes. 
I'm sure future developers working in debug mode will thank you deep down for the perf increase in debug mode though :sweat_smile:
