### PR TITLE
Fix relative comparison in `CompareWorkspaces`

### LINKED ISSUE #37877: `CompareWorkspaces` with relative tolerance incorrectly evaluating to true
**Describe the bug**

`CompareWorkspaces` is not properly handling relative differences when the size of the values is smaller than the tolerance.

This error is due to [L1361-1362](https://github.com/mantidproject/mantid/blob/25fe3490e111b8f02b3ab9699394800708b57189/Framework/Algorithms/src/CompareWorkspaces.cpp#L1361C1-L1362C29) in CompareWorkspaces.cpp.  I am unsure why this was originally implemented this way.

The tests of `CompareWorkspaces` are under-developed for testing relative errors.  Only a single test tries to make use of this ability, while more should be used.

**To Reproduce**
Open workbench.  Run the following:
``` python
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

tol = 0.01
x1 = 0.00001
x2 = 0.00010
ws1 = CreateWorkspace(DataX=[x1], DataY=[1])
ws2 = CreateWorkspace(DataX=[x2], DataY=[1])
print( (x2-x1)/(0.5 * (x2+x1)) )
assert not (x2-x1)/(0.5 * (x2+x1)) <= tol
res, msg = CompareWorkspaces(ws1, ws2, Tolerance=tol, ToleranceRelErr=True)
print(res)
assert not res
```
The relative tolerance is > 1, and the relative tolerance is 0.01, and yet the last assert will fail (meaning the workspaces compare equal).

**Expected behavior**
Checks of relative error with `CompareWorkspaces` should fail if the relative error is above the tolerance.

**Platform/Version (please complete the following information):**
 - OS: Ubuntu
 - OS Version: 22.04.4
 - Mantid Version: 6.10.20240823

**Additional context**

### PR DESCRIPTION
**Pull request by rboston628**
#### Summary of work
`CompareWorkspaces` is supposed to be usable for both absolute and relative comparisons.

There are two situations where relative differences may be preferred over absolute differences.

1. One is the case of very large numbers.  Values may match to ten digits, but not match out to the thousandths place, which would make an absolute difference fail.
2. The other is the case of very small numbers, where the values themselves are below a tolerance.  Here, an absolute difference below the tolerance is meaningless, and the numbers should be checked for relative closeness.  

The comparison of relative difference was originally written as:
``` c++
bool CompareWorkspaces::relErr(double x1, double x2, double errorVal) const {
  double num = std::fabs(x1 - x2);
  // how to treat x1<0 and x2 > 0 ?  probably this way
  double den = 0.5 * (std::fabs(x1) + std::fabs(x2));
  if (den < errorVal)
    return (num > errorVal);

  return (num / den > errorVal);
}
``` 
This short-circuits any use of relative differences for case 2 above, instead performing an absolute difference in a situation where absolute difference is irrelevant.

This changes that calculation, to just do relative difference.

If the user asks for the relative difference, the user gets a relative difference.

Fixes #37877 . 

#### Further detail of work

This also caused one unit test and three system tests to fail.

The one unit test could be fixed by ever-so-slightly broadening the tolerance on the comparison.

The three system tests could be fixed by using absolute comparison instead (which is what they would have been doing anyway).

### To test:

Try running this script in workbench built from this branch.  If the issue has been fixed, then this should pass
``` python
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np

tol = 0.01
x1 = 0.00001
x2 = 0.00010
ws1 = CreateWorkspace(DataX=[x1], DataY=[1])
ws2 = CreateWorkspace(DataX=[x2], DataY=[1])
print( (x2-x1)/(0.5 * (x2+x1)) )
assert not (x2-x1)/(0.5 * (x2+x1)) <= tol
res, msg = CompareWorkspaces(ws1, ws2, Tolerance=tol, ToleranceRelErr=True)
print(res)
assert not res
```

---

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

File: Framework/Algorithms/src/CompareWorkspaces.cpp [hunk 1]
```diff
@@ -1340,27 +1339,36 @@ void CompareWorkspaces::recordMismatch(const std::string &msg, std::string ws1,
...
+this error is within the limits requested.
+
+@param x1    -- first value to check difference
+@param x2    -- second value to check difference
+@param atol  -- the tolerance of the comparison. Must be nonnegative
+
+@returns true if absolute difference is within the tolerance; false otherwise
+*/
+bool CompareWorkspaces::withinAbsoluteTolerance(double const x1, double const x2, double const atol) {
+  // NOTE !(|x1-x2| > atol) is not the same as |x1-x2| <= atol
```
Comment (peterfpeterson) [inline Framework/Algorithms/src/CompareWorkspaces.cpp:1353]: very good comment

File: Framework/Algorithms/src/CompareWorkspaces.cpp [hunk 2]
```diff
@@ -1340,27 +1339,36 @@ void CompareWorkspaces::recordMismatch(const std::string &msg, std::string ws1,
...
-  // how to treat x1<0 and x2 > 0 ?  probably this way
-  double den = 0.5 * (std::fabs(x1) + std::fabs(x2));
-  if (den < errorVal)
-    return (num > errorVal);
-
-  return (num / den > errorVal);
+bool CompareWorkspaces::withinRelativeTolerance(double const x1, double const x2, double const rtol) {
+  double const num = std::fabs(x1 - x2);
+  // create a standardized size to compare against
+  double const den = 0.5 * (std::fabs(x1) + std::fabs(x2));
```
Comment (peterfpeterson) [inline Framework/Algorithms/src/CompareWorkspaces.cpp:1371]: I think you need to do the `std::fabs` on the sum rather than the individuals. The current implementation has an issue when the two values are on either side of zero
```suggestion
  double const den = 0.5 * std::fabs(x1 + x2);
```

File: Framework/Algorithms/src/CompareWorkspaces.cpp [hunk 3]
```diff
@@ -1340,27 +1339,36 @@ void CompareWorkspaces::recordMismatch(const std::string &msg, std::string ws1,
...
+  return !(num > (rtol * den));
```
Comment (peterfpeterson) [inline Framework/Algorithms/src/CompareWorkspaces.cpp:1372]: please add the comment about this not being the same as `<=` from above

File: Framework/Algorithms/src/CompareWorkspaces.cpp [hunk 4]
```diff
@@ -1269,25 +1274,19 @@ void CompareWorkspaces::doTableComparison(const API::ITableWorkspace_const_sptr
   const bool checkAllData = getProperty("CheckAllData");
   const bool isRelErr = getProperty("ToleranceRelErr");
   const double tolerance = getProperty("Tolerance");
-  bool mismatch = false;
+  bool mismatch;
```
[the remark this answers is not in the document]
Comment (rboston628) [reply Framework/Algorithms/src/CompareWorkspaces.cpp:1277]: Either CppCheck or clang-format insisted I do this.  But I agree with you, it's safer to set it to something.

File: Framework/Algorithms/src/CompareWorkspaces.cpp (hunk 1 above)
Comment (rboston628) [reply Framework/Algorithms/src/CompareWorkspaces.cpp:1353]: Thanks.  For anyone from the future coming to this PR and wondering about this comment.  Mathematically they are identical, but they do not evaluate the same in some of the tests.

The checks throughout the algo were originally written to expect `false` for a match.  It was originally checking $\vert x_1 - x_2 \vert > atol$.

It seemed to make more sense to return `true` for a match.  I changed it to return $\vert x_1 - x_2 \vert \leq atol$.  This caused certain tests to fail.  I changed it to its current form, and the same tests do not fail.

Two possibilities are values such as `NaN`, or machine precision issues, which could cause the two comparison to be mechanically different.

File: Framework/Algorithms/src/CompareWorkspaces.cpp [hunk 5]
```diff
@@ -1269,25 +1274,19 @@ void CompareWorkspaces::doTableComparison(const API::ITableWorkspace_const_sptr
...
   for (size_t i = 0; i < numCols; ++i) {
     const auto c1 = tws1->getColumn(i);
     const auto c2 = tws2->getColumn(i);
 
     if (isRelErr) {
-      if (!c1->equalsRelErr(*c2, tolerance)) {
-        mismatch = true;
-      }
+      mismatch = !c1->equalsRelErr(*c2, tolerance);
```
[the remark this answers is not in the document]
Comment (rboston628) [reply Framework/Algorithms/src/CompareWorkspaces.cpp:1283]: The `recordMismatch` method is called within the loop, and only called if `mismatch` evaluates to true in that iteration.  I had rewritten this at one point to only call `recordMismatch` once, but it didn't seem worthwhile.  Either way, 
``` c++
mismatch = false;
if (condition) {
  mismatch = true;
}
if (mismatch) {
  doSomething();
  mismatch = false;
}
```
should be logically equivalent to
``` c++
mismatch = condition;
if (mismatch) {
  doSomething();
}
```

[the remark this answers is not in the document]
Comment (peterfpeterson) [reply Framework/Algorithms/src/CompareWorkspaces.cpp:1283]: For `checkAllData=false` you can jump out early. It is only in the case where somebody asks for `checkAllData=true` that there is a problem. Another way to do it is change the check to be something like
```cpp
mismatch = mismatch || (!c1->equals(*c2, tolerance));
```

File: Framework/Algorithms/src/CompareWorkspaces.cpp (hunk 1 above)
Comment (peterfpeterson) [reply Framework/Algorithms/src/CompareWorkspaces.cpp:1353]: I was curious why. `std::nan` is equal to everything, but isn't greater-than anything

File: Framework/Algorithms/src/CompareWorkspaces.cpp (hunk 2 above)
Comment (rboston628) [reply Framework/Algorithms/src/CompareWorkspaces.cpp:1371]: I'll need to think about it more.  This method was there and I didn't want to change behavior too much. It also seems to be the standard way to treat opposite signs, unless we instead make it an error condition.

Suppose $x_1=1.0$ and $x_2=-1.0$.  Using sum of `std::fabs`, they differ by 2 and both have a magnitude of 1, so the relative difference is twice their value (2).

Using `std::fabs` on the sum would create a standard-size of 0 to compare against, and the result would be $+\infty$.

That might become a relevant for very tiny values oscillating near zero.

File: Framework/Algorithms/src/CompareWorkspaces.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (peterfpeterson) [reply Framework/Algorithms/src/CompareWorkspaces.cpp:1277]: clang-format only messes with whitespace. I'd suppress cppcheck as a false positive.

[the remark this answers is not in the document]
Comment (rboston628) [reply Framework/Algorithms/src/CompareWorkspaces.cpp]: I don't think there's any real risk in the case of an empty table.  If the table is empty, it will just skip over the for loop and do nothing.  This value isn't used for anything after for the for loop/

**Comment by sf1919** [comment]
Please can you remember to add a milestone? it helps with audit trail for the release.

**Review by peterfpeterson — APPROVED** [review]

**Comment by thomashampson** [comment]
Is there a reason to not add the test you added in the description as a unit test? I think it would be a nice addition.

**Comment by rboston628** [comment]
@thomashampson I considered adding a test based on the script, but thought that the tests added in PR #37878 effectively cover the situation.  I can add this test in `CompareWorkspacesTest.h` as well if desired.

**Comment by rboston628** [comment]
@thomashampson  a similar test of the relative comparison will be added in PR #37933
