### PR TITLE
Crystal field phys. prop. bug

### LINKED ISSUE #22466: Crystal field parameters not updating in fitting procedure
**Original reporter:** Raimundo Serrano; please report to Keith Butler when this issue is resolved.

### Expected behavior

Fitting the crystal field parameters with physical properties as an input should result in updated crystal field parameters.

### Actual behavior

Running a fit does not update the parameters of the crystal field model.
**Note** running a fit _without_ the physical properties as an input works correctly.

### Steps to reproduce the behavior

[Script and data needed to reproduce the problem: Archive.zip](https://github.com/mantidproject/mantid/files/2034348/Archive.zip)

Running the script generates a new workspace `fit_result_Parameters`, with the updated model parameters.

Inspecting this workspace, if the fitting has worked the parameters B20, B40, B60, B66 should have been modified and should have an error associated with them. In this case they have not changed from the original values and have no error associated.

### Platforms affected

OSX, Windows

### PR DESCRIPTION
**Pull request by mantid-roman**
**Description of work.**
Changed the order of processing arguments of the constructor of `CrystalField` class. Added protection against the crystal field functions changing number of their parameters.

**Report to:** Keith Butler

**To test:**

Use the script from the issue description.

Fixes #22466.

Does this update require release notes?
- [ ] Yes
- [x] No

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)?
- [ ] Are the unit tests small and test the class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] Do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by mducle** [comment]
@mantid-roman can I also add a commit to fix a small issue with using the resolution model on a mixed INS+physical properties multidomain fit? Or should I make a new issue/pr for it?

```
diff --git a/scripts/Inelastic/CrystalField/fitting.py b/scripts/Inelastic/CrystalField/fitting.py
index 1b13caea9e..b9ce6bf271 100644
--- a/scripts/Inelastic/CrystalField/fitting.py
+++ b/scripts/Inelastic/CrystalField/fitting.py
@@ -525,10 +525,11 @@ class CrystalField(object):
         else:
             self._resolutionModel = ResolutionModel(value)
         if self._isMultiSpectrum:
-            if not self._resolutionModel.multi or self._resolutionModel.NumberOfSpectra != self.NumberOfSpectra:
+            NSpec = self.NumberOfSpectra - len(self._physprop) if islistlike(self._physprop) else (0 if self._physprop is None else 1)
+            if not self._resolutionModel.multi or self._resolutionModel.NumberOfSpectra != NSpec:
                 raise RuntimeError('Resolution model is expected to have %s functions, found %s' %
-                                   (self.NumberOfSpectra, self._resolutionModel.NumberOfSpectra))
-            for i in range(self.NumberOfSpectra):
+                                   (NSpec, self._resolutionModel.NumberOfSpectra))
+            for i in range(self._resolutionModel.NumberOfSpectra):
                 model = self._resolutionModel.model[i]
                 self.crystalFieldFunction.setAttributeValue('FWHMX%s' % i, model[0])
                 self.crystalFieldFunction.setAttributeValue('FWHMY%s' % i, model[1])
diff --git a/scripts/Inelastic/CrystalField/function.py b/scripts/Inelastic/CrystalField/function.py
index 38813e9d02..ee93a7a4db 100644
--- a/scripts/Inelastic/CrystalField/function.py
+++ b/scripts/Inelastic/CrystalField/function.py
@@ -355,27 +355,30 @@ class ResolutionModel:
         self.multi = False
         if hasattr(model, '__call__'):
             self.model = self._makeModel(model, xstart, xend, accuracy)
-            return
+        elif hasattr(model, 'getEi') and hasattr(model, 'getResolution'):
+            Ei = model.getEi()
+            self.model = self._makeModel(model.getResolution, -Ei, 0.9 * Ei, 0.01)
+        elif hasattr(model, 'model'):
+            self.model = model
         elif hasattr(model, '__len__'):
             if len(model) == 0:
                 raise RuntimeError('Resolution model cannot be initialised with an empty iterable %s' %
                                    str(model))
             if hasattr(model[0], '__call__'):
                 self.model = [self._makeModel(m, xstart, xend, accuracy) for m in model]
-                self.multi = True
-                return
             elif hasattr(model[0], 'model'):
                 self.model = [m.model for m in model]
-                self.multi = True
-                return
+            elif hasattr(model[0], 'getEi') and hasattr(model[0], 'getResolution'):
+                Ei = model[0].getEi()
+                self.model = [self._makeModel(m.getResolution, -Ei, 0.9 * Ei, 0.01) for m in model]
             elif isinstance(model[0], tuple):
                 for m in model:
                     self._checkModel(m)
                 self.model = model
-                self.multi = True
-                return
-        self._checkModel(model)
-        self.model = model
+            self.multi = True
+        else:
+            self._checkModel(model)
+            self.model = model
 
     @property
     def NumberOfSpectra(self):
```

**Comment by mantid-roman** [comment]
@mducle Of course, it fits here.

**Comment by keeeto** [comment]
@mducle, thanks for this. I'm away till Friday, but will review as soon as I'm back.

**Review by keeeto — APPROVED** [review]
This now works and the parameters that were previously un-modified by fitting are now modified. Thanks @mantid-roman and @mducle for this fix.

File: Framework/CurveFitting/inc/MantidCurveFitting/GSLJacobian.h [hunk 1]
```diff
@@ -127,6 +127,8 @@ class JacobianImpl1 : public API::Jacobian {
   }
   /// overwrite base method
   void set(size_t iY, size_t iP, double value) override {
+    if (iP >= m_index.size())
+      return;
```
Comment (SimonHeybrock) [inline Framework/CurveFitting/inc/MantidCurveFitting/GSLJacobian.h]: What is the reasoning behind this change? Why not throw for this out of range index?

Comment (mantid-roman) [reply Framework/CurveFitting/inc/MantidCurveFitting/GSLJacobian.h]: The crystal field fitting functions can change their number of active fitting parameters during the fit. When it happens after an iteration is finished there is a special exception that signals the minimizer to re-initialize itself. But it can happen during a numeric derivative calculation: a field parameter is incremented, a new peak may appear and it may have a free fitting parameter, so the number of parameters change. You cannot throw and re-initialize the minimizer at this point because the same will happen again. If you ignore these "virtual" extra parameters by the time the derivative calculations finish the number of parameters will return to the original value. If you notice the `get(...)` method doesn't skip any extra indices because if there are any it is an error.

Comment (SimonHeybrock) [reply Framework/CurveFitting/inc/MantidCurveFitting/GSLJacobian.h]: Awesome. Can you add this explanation to the code?

Comment (mantid-roman) [reply Framework/CurveFitting/inc/MantidCurveFitting/GSLJacobian.h]: All of it?

Comment (SimonHeybrock) [reply Framework/CurveFitting/inc/MantidCurveFitting/GSLJacobian.h]: Or point to a place where this is explained in a similar way?

Comment (mantid-roman) [reply Framework/CurveFitting/inc/MantidCurveFitting/GSLJacobian.h]: OK

**Comment by keeeto** [comment]
@SimonHeybrock thanks for merging this. I know you were not at the review meeting recently where we discussed small changes in PR workflow. We are trying to make sure that the person who merges reports the merge to the person marked "Report To" in the PR description. This is to make sure that users who report problems are informed when they are fixed. 

I realise that you could not have known this as I need to update the developer docs to reflect the change too.

**Comment by SimonHeybrock** [comment]
@keeeto So how do we do the reporting? Just ping in the PR thread?

**Comment by keeeto** [comment]
@SimonHeybrock Sorry, I should have said.  Yes, just ping the thread after close/merge.
