### PR TITLE
Fix locale issue in PeakColumn::read()

### LINKED ISSUE #18366: Locale issue in PeakColumn
When trying to
```python
peaks=LoadIsawPeaks('<mantid-build-directory>/ExternalData/Testing/Data/UnitTest/Peaks5637.integrate')
```
one gets a bunch of errors like
```
PeakColumn-[Error] Could not convert string '-22,00' to a number.
```
thanks to non-locale aware number conversion in `PeakColumn::read(size_t, const std::string &)`

### PR DESCRIPTION
**Pull request by soininen**
This PR fixes the regressions introduced in PR #18315 with regards to the `PeakColumn` class. The `read(const size_t index, std::istream &)` method was erroneously delegating the reading directly to the `read(size_t, std::string &)` method which in turn did not take into account the locale in which the input string was written.

**To test:**

1. Load the 'Peaks5637.integrate' file from Mantid's unit test data using the `LoadIsawPeaks` algorithm.
2. Show the data.
3. Without these changes, a lot of errors may appear in the Mantid log (this depends on your locale settings!). The errors could be something like `Could not convert string'15,629' to a number for the RunNumber`.

Fixes #18366 

*Does not need to be in the release notes as this fixes a regression introduced in another PR which is already in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [x] Is the code of an acceptable quality?
- [x] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [x] Do changes function as described? Add comments below that describe the tests performed?
- [x] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by VickieLynch** [comment]
:shipit:  Warnings in the log are gone now.  Thanks for the quick fix!

File: Framework/DataObjects/test/PeakColumnTest.h [hunk 1]
```diff
@@ -116,7 +117,53 @@ class PeakColumnTest : public CxxTest::TestSuite {
     TS_ASSERT(readOnly);
   }
 
+  void test_read_locale_awerness() {
```
Comment (martyngigg) [inline Framework/DataObjects/test/PeakColumnTest.h]: Nice tests!
