### PR TITLE
Correct Integration range in PDFFourierTransform2

### LINKED ISSUE #30606: Integration in PDFFourierTransform not treating start\end point correctly
It looks to me as though the q limits on the main integration loop in PDFFourierTransform2.cpp (and PDFFourierTransform.cpp) aren’t managed properly (this is the double loop in exec() at around line 518). Specifically:

-	Xmin_index is generally set to 1. This is fine for the calculations that depend only on the X values but it seems wrong for any calculations that depend on the Y values eg 0th value in inputY is skipped. Perhaps the code should be using inputY [inXindex-1] on the line where fs is incremented?
-	the value of Xmax_index appears to be one too small (this is calculated higher up in the unit)
-	the termination condition of the for loop looks to me as though it should be <= rather than <. This and the previous point mean the last two X bin edges are not processed

Then one final point that is lower priority. The calculation should possibly be using the x value of the bin centre during the calculation – at the moment it defines x as the right hand bin edge I think. But this is more of a design choice and not a bug unlike the points I've mentioned above.

```
for (size_t outXIndex = 0; outXIndex < sizer; outXIndex++) {
    const double outX = outputX[outXIndex];
    const double outXFac = corr / (outX * outX * outX);

    double fs = 0;
    double error = 0;
    for (size_t inXIndex = Xmin_index; inXIndex < Xmax_index; inXIndex++) {
      const double inX1 = inputX[inXIndex];
      const double inX2 = inputX[inXIndex + 1];
      const double sinx1 = sin(inX1 * outX) - inX1 * outX * cos(inX1 * outX);
      const double sinx2 = sin(inX2 * outX) - inX2 * outX * cos(inX2 * outX);
      double sinus = sinx2 - sinx1;

      // multiply by filter function sin(q*pi/qmax)/(q*pi/qmax)
      if (filter && inX1 != 0) {
        const double lorchKernel = inX1 * M_PI / inputX[Xmax_index];
        sinus *= sin(lorchKernel) / lorchKernel;
      }
      fs += sinus * inputY[inXIndex];

      error += (sinus * inputDY[inXIndex]) * (sinus * inputDY[inXIndex]);
    }

    // put the information into the output
    outputY[outXIndex] = fs * outXFac;
    outputE[outXIndex] = sqrt(error) * outXFac;
  }

### PR DESCRIPTION
**Pull request by DanielMurphy22**
**Description of work.**
The integration range in PDFFourierTransform was too narrow, so a few fixes have allowed the full valid range of data to be included.
- Fixed problem where first_normal_index would consider 0 as not a normal value (when we want to only ignore Nan/Inf values).
- Added test for protected functions for determining the min/max indexes
- Cppcheck suppressions removed

- Also at line 385 there's an odd commented out section: https://github.com/mantidproject/mantid/pull/32947/files#diff-035333f5620c218e00e51a6236d91a87b7427912b735a847ec6aa550cf168b1aL385-L396

**To test:**

- Debug with a break point on line 440 of PDFForuierTransform2.cpp
and run this doctest example to check the integration range is from 0 - 99 (the values of Xmin_index and XMax_index).

Doctest:
```
from mantid.simpleapi import *
import numpy as np;
xx = np.array(range(0,100))*0.1
yy = np.exp(-(2.0 * xx)**2)
yy = np.delete(yy,-1)
ws = CreateWorkspace(DataX=xx, DataY=yy, UnitX='MomentumTransfer')
Rt = PDFFourierTransform(ws, SofQType='S(Q)', PDFType='g(r)')
print(yy)
# Look at sample results:
print('part of S(Q)-1 and its correlation function')
for i in range(10):
   print('! {0:4.2f} ! {1:5f} ! {2:f} ! {3:5f} !'.format(xx[i], yy[i], Rt.readX(0)[i], Rt.readY(0)[i]))
```

- Review the new unit test.

Fixes #30606 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Algorithms/src/PDFFourierTransform2.cpp [hunk 1]
```diff
@@ -172,14 +172,19 @@ size_t PDFFourierTransform2::determineMinIndex(double min, const std::vector<dou
...
-  auto iter = std::upper_bound(X.begin(), X.end(), min);
+  auto iter = std::lower_bound(X.begin(), X.end(), min);
   size_t min_index = std::distance(X.begin(), iter);
-  if (min_index == 0)
-    min_index += 1; // so there doesn't have to be a check in integration loop
 
   // go to first non-nan value
-  iter = std::find_if(std::next(Y.begin(), min_index), Y.end(), static_cast<bool (*)(double)>(std::isnormal));
-  size_t first_normal_index = std::distance(Y.begin(), iter);
+  auto isNormalOrZero = [](double elem) {
```
Comment (DannyHindson) [inline Framework/Algorithms/src/PDFFourierTransform2.cpp:179]: I think the original behaviour where it also skipped over zero y values was probably a useful feature - certainly for histogram data (ie bin edges). The integral for bins with y=0 is also zero so it made sense just to skip over them.

For point data, the integration uses a "left leaning" approach where it takes the y value from the left point for the integral between each pair of points (L498). Again it makes sense here to skip over points with y=0 but in the determineMaxIndex function the logic should perhaps find the farthest "right" non-zero point and then move one further on.

**Review by DannyHindson — CHANGES_REQUESTED** [review]

File: Framework/Algorithms/src/PDFFourierTransform2.cpp [hunk 2]
```diff
@@ -197,13 +196,13 @@ size_t PDFFourierTransform2::determineMaxIndex(double max, const std::vector<dou
...
-  // get pointers for the data range
-  auto iter = std::lower_bound(X.begin(), X.end(), max);
+  // get index for the max from the X-range, tightening the range if a partial x bin value is provided
+  auto iter = std::upper_bound(X.begin(), X.end(), max) - 1;
   size_t max_index = std::distance(X.begin(), iter);
 
   // go to first non-nan value
   auto back_iter = std::find_if(Y.rbegin(), Y.rend(), static_cast<bool (*)(double)>(std::isnormal));
-  size_t first_normal_index = Y.size() - std::distance(Y.rbegin(), back_iter) - 1;
+  size_t first_normal_index = Y.size() - std::distance(Y.rbegin(), back_iter);
```
Comment (DannyHindson) [inline Framework/Algorithms/src/PDFFourierTransform2.cpp:205]: This works fine now for bin edge data. It is also fine for point data although the reason why is a bit subtle. If there's a point dataset like this: 
```
x=[1,2,3], y=[100,101,nan]
```
...the logic sets first_normal_index=3-1=2 ie it leaves max_index pointing at the final point. This is fine because the integration on point data sets is left leaning ie it looks at the Y value on the left of each interval so the final y value never gets used

Please can you add a comment about this? Doesn't need to be as verbose as I've just been (!) eg the logic applies to both bin edge and point data because the integration for points uses the Y value on the left of each interval.

**Review by DannyHindson — CHANGES_REQUESTED** [review]
I've tested this and it all works fine for me. I've just asked for a couple of small changes to add a comment and update a couple of log messages

File: Framework/Algorithms/src/PDFFourierTransform2.cpp (hunk 2 above)
Comment (DanielMurphy22) [reply Framework/Algorithms/src/PDFFourierTransform2.cpp:205]: Does this mean we can support point data now and we can remove the warning here? Are we happy to just leave this weird commented out density section for now???https://github.com/mantidproject/mantid/blob/cb21841641eb26bc1b0966d6417354dbbfaa6f7d/Framework/Algorithms/src/PDFFourierTransform2.cpp#L381-L397

Comment (DannyHindson) [reply Framework/Algorithms/src/PDFFourierTransform2.cpp:205]: > Does this mean we can support point data now and we can remove the warning here? Are we happy to just leave this weird commented out density section for now???
> 
> https://github.com/mantidproject/mantid/blob/cb21841641eb26bc1b0966d6417354dbbfaa6f7d/Framework/Algorithms/src/PDFFourierTransform2.cpp#L381-L397

I think we should leave the warning and the commented out code alone. I think the specific parts we've looked at work OK for point data but I'm not 100% sure about the rest of the unit

Comment (DanielMurphy22) [reply Framework/Algorithms/src/PDFFourierTransform2.cpp:206]: I've just put a comment about this in the `determineMaxIndex()`, should there also be an equivalent in `determineMinIndex()`?

File: Framework/Algorithms/src/PDFFourierTransform2.cpp [hunk 3]
```diff
@@ -197,15 +196,16 @@ size_t PDFFourierTransform2::determineMaxIndex(double max, const std::vector<dou
...
 
-  // get pointers for the data range
-  auto iter = std::lower_bound(X.begin(), X.end(), max);
+  // get index for the max from the X-range, tightening the range if a partial x bin value is provided
+  auto iter = std::upper_bound(X.begin(), X.end(), max) - 1;
   size_t max_index = std::distance(X.begin(), iter);
 
-  // go to first non-nan value
+  // go to first non-nan value. This works for histogram (bin edge) data and
+  // also point data, where point integration ends at the Y value to the left of the max bound
```
Comment (DannyHindson) [inline Framework/Algorithms/src/PDFFourierTransform2.cpp:204]: Getting a bit pedantic now - but to be precise the integration for point data doesn't end at the Y value to the left of the max bound. It just uses the Y value at the left of each interval. So you do integrate the final interval that ends at max_index but the code just uses the Y value from the left hand edge of this interval

File: docs/source/algorithms/PDFFourierTransform-v2.rst [hunk 4]
```diff
@@ -125,6 +125,7 @@ Usage
     import numpy as np;
     xx = np.array(range(0,100))*0.1
     yy = np.exp(-(2.0 * xx)**2)
+    yy = np.delete(yy,-1) # need one less Y value than X value for histogram data
     ws = CreateWorkspace(DataX=xx, DataY=yy, UnitX='MomentumTransfer')
     Rt = PDFFourierTransform(ws, SofQType='S(Q)', PDFType='g(r)')
```
Comment (DannyHindson) [inline docs/source/algorithms/PDFFourierTransform-v2.rst:130]: I noticed that in this doc test example the code detects a zero in the first bin during DetermineMinIndex and moves minindex along one to "1". This is slightly confusing because the ws dataset has Y=1 in the first bin. The reason this is happening is that the code converts the input S(Q) profile to S(Q)-1 before doing the integral.

Normally S(Q) tends to "1" at high Q for the type of samples we're looking at for total scattering so I think the exp(-q^2) function that's used here is actually a better approximation to S(Q)-1. So please can you change SofQType='S(Q)-1' in the input parameters to PDFFourierTransform.

**Review by DannyHindson — CHANGES_REQUESTED** [review]
Sorry - keep thinking of extra points on this PR whenever I come back to it. Please can you address these couple of bits and then I think we're done

File: docs/source/algorithms/PDFFourierTransform-v2.rst (hunk 4 above)
Comment (DanielMurphy22) [reply docs/source/algorithms/PDFFourierTransform-v2.rst:130]: This problem was part of my reason for wanting to set 0 as a normal value! I'm very happy to have this corrected to S(Q)-1!!!

**Review by DannyHindson — APPROVED** [review]
