### PR TITLE
Remove link between muon and curvefitting libs

### LINKED ISSUE #39644: Muon analysis interface crash on Linux
**Describe the bug**
On some Linux versions (Ubuntu 20.04, AlmaLinux 9), this message appears when launching MantidWorkbench:

```
FrameworkManager-[Notice] Welcome to Mantid 6.13.0
FrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid6.13
DllOpen-[Error] Could not open library /home/tom/Desktop/mantidworkbench-6.13.0/mantidworkbench/plugins/libMantidMuon.so: libMantidCurveFitting.so: cannot open shared object file: No such file or directory
```

This error prevents the opening of the Muon Analysis and Frequency Domain Analysis interfaces.

**To Reproduce**
Install MantidWorkbench 6.13.0 on Linux (conda or standalone). Open workbench. Observe error message. Attempt to open either interface mentioned above.

**Expected behavior**
No errors.

**Platform/Version (please complete the following information):**
 - OS: Ubuntu 20.04, AlmaLinux 9.6 (Sage Margay)
 - Mantid Version 6.13.0

### PR DESCRIPTION
**Pull request by MialLewis**
#### Summary of work

This PR removes the use of `Mantid::CurveFitting::EigenMatrix` from the `Muon` library to avoid the linking of two plugin libraries.

We use `PartialPivLU` decomposition in calculating the inverse, replicating what the `Mantid::CurveFitting::EigenMatrix` is doing under the hood.

`long double` is used on arm mac, as it brings precision of eigen matrix multiplication inline (lowers it) with the other operating systems. I'm not sure why, you would expect a greater degree of precision.

Here is a compiler explorer used to interrogate the differences when different types are used with eigen across our compilers: https://godbolt.org/z/51W6KPecb

This illustrates the issue, but doesn't show the same impact on arm64 of switching to `long double`.

Testing change on arm: https://builds.mantidproject.org/job/build_packages_from_branch/1200/

Fixes #39644 

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Comment by jclarkeSTFC** [comment]
On Windows (and maybe ARM) a `long double` is 8 bytes, but is 16 bytes on Linux and macOS, might cause differences, the standard only specifies that it has at least as much precision as a `double`.

**Comment by MialLewis** [comment]
> and maybe ARM) a `long double` is

This is what I'm working with at the moment: https://godbolt.org/z/hf7GhGs77

Results are inconsistent when using double/long double.

File: Framework/Muon/test/PhaseQuadMuonTest.h [hunk 1]
```diff
@@ -312,14 +312,14 @@ class PhaseQuadMuonTestPerformance : public CxxTest::TestSuite {
...
 
   void tearDown() override { Mantid::API::AnalysisDataService::Instance().remove("outputWs"); }
 
-  void testPerformanceWs() { phaseQuad->execute(); }
+  void testPerformanceWs() { m_phaseQuad->execute(); }
 
 private:
   MatrixWorkspace_sptr m_loadedData;
-  IAlgorithm_sptr phaseQuad;
+  IAlgorithm_sptr m_phaseQuad;
```
Comment (thomashampson) [inline Framework/Muon/test/PhaseQuadMuonTest.h:324]: nice

File: Framework/Muon/src/PhaseQuadMuon.cpp [hunk 2]
```diff
@@ -254,23 +263,21 @@ API::MatrixWorkspace_sptr PhaseQuadMuon::squash(const API::MatrixWorkspace_sptr
       const double phi = phase->Double(h, phaseIndex);
       const double X = n0[h] * asym * cos(phi);
       const double Y = n0[h] * asym * sin(phi);
-      n0Vectors[h] = CurveFitting::EigenVector({X, Y});
+      Eigen::Vector<eigenDataType, 2> n0vec;
```
Comment (MialLewis) [inline Framework/Muon/src/PhaseQuadMuon.cpp:266]: This is unused, will push after review.

**Review by sf1919 — APPROVED** [review]
I have done a functional test on Windows and on Linux (Ubuntu 20.04) and the two Muon GUIs open without any problem.

The code looks sensible. 

I am assuming this does not need a release note @thomashampson ?

**Comment by thomashampson** [comment]
release notes will be added separately
