### PR TITLE
Load FITS tidying, fixes, and improvements

### LINKED ISSUE #13994: Load FITS tidying, fixes, and improvements
Several issues need fixing:

- if you try to load a file that is readable but has size 0, the algorithm will exhaust system memory - it should fail gracefully and give informative error. Add a test case for this, as it is a common problem with experiment data.
- tidy up methods and parameters
- speed it up. With some changes this can run >5 times faster. This is related to the tidying and also:
  - don't make unnecessary copies. Currently there's a read buffer, a vector of vector as a temporary image structure, and then the vector of ISpectrum objects for the workspace.
- threading issues: the parallel for won't work at all when loading multiple files. The images get corrupted. A rearrangement of the loops fixes this and improves memory locality, which seems to provide a further speed up.
- I'm very tempted to make the calculation of the errors (sqrt) optional, so when not interested in E values it can be set to False. But note that from the performance viewpoint this provides only marginal speed up compared to the other points (~10% additional time spent in calculating the sqrts).

### PR DESCRIPTION
**Pull request by FedeMPouzols**
Fixes #13994.

**To test:** tests should pass, code review.

The changes are covered by the unit tests, and there's now a new test case for the empty-file issue. This fixes all the issues described in #13994, but in the end the option to skip the calculation of the sqrt errors has not been added (not worth for now as the benefit is small). The changes in the parallel loop prevent data corruption in the images and decrease load time from >20s to ~3-4s when loading large stacks (of ~1000 images). With single small files as the FITS_small_01.fits and FITS_small_02.fits there should also be a noticeable speed up although a bit smaller (like from 0.9-1.1s down to ~0.3s).
The code is far from perfect and there's still more work to do (#14040).

### CODE REVIEW

File: Framework/DataHandling/src/LoadFITS.cpp [hunk 1]
```diff
@@ -451,6 +297,207 @@ void LoadFITS::doLoadHeaders(const std::vector<std::string> &paths,
...
+  for (int64_t i = 1; i < static_cast<int64_t>(totalWS); ++i) {
+    latestWS =
+        makeWorkspace(headers[i], fileNumberInGroup, buffer, imageY, imageE,
+                      latestWS, loadAsRectImg, binSize, noiseThresh);
+    wsOrdered[i] = latestWS;
+    progress.report("Loaded file " + boost::lexical_cast<std::string>(i + 1) +
+                    " of " + boost::lexical_cast<std::string>(totalWS));
+  }
+
+  // Add to group - done here to maintain sequence
```
Comment (MichaelWedel) [inline Framework/DataHandling/src/LoadFITS.cpp]: If I understand correctly, this should not be needed anymore with the parallel for loop gone, or am I overlooking something?

Comment (FedeMPouzols) [inline Framework/DataHandling/src/LoadFITS.cpp]: Yes, you're right. This is a leftover that can go away. I'll fix that together witth the issue with '=' in comment entries.
Thanks!
