### PR TITLE
Fix Inelastic Symmetrise Preview crash

### LINKED ISSUE #38042: Mantid crash in Symmetrise tab
**Describe the bug**
Mantid crashes when preview button is pressed after clearing ADS in the Inelastic Symmetrise tab

**To Reproduce**
Follow Instruction for [Symmetrise Tab](https://developer.mantidproject.org/Testing/Inelastic/DataProcessorTests.html#symmetrise-tab)
1. Data is loaded at step 4
2. ADS is cleared
3. Preview button is pressed

**Expected behavior**
No Crash

**Screenshots**

**Platform/Version (please complete the following information):**
 - OS: macOS and IDAaaS.
 - Mantid Version 6.11 manual testing 

**Additional context**

### PR DESCRIPTION
**Pull request by robertapplin**
### Description of work
This PR fixes a crash on the Symmetrise tab of the Inelastic Data Processor interface after clearing the ADS and clicking the Preview button. The tab will now not proceed with processing if it can't find the loaded workspace in the ADS. The auto loading feature has also been disabled when validating the DataSelector on the Symmetrise tab because it was causing multiple confusing messages.

Fixes #38042

### To test:
Follow the instructions on the attached issue

*This does not require release notes* because **it is a regression since the last release**

### Reviewer

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Do the release notes conform to the [release notes guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

**Review by adriazalvarez — APPROVED** [review]
Thanks for fixing this issue. 
I have tested following instructions, Mantid no longer crashes when clicking `Preview` button after clearing the ADS. 
Otherwise, you said autoload was sending confusing messages. There other inelastic interfaces with autoload enabled (now by default) like Iqt. When you try to run the algorithm without data on the ADS, it prompts an error message, but then it loads the data. 
Could we open an issue to handle better this case in inelastic interfaces having autoload enabled?

File: qt/widgets/common/src/DataSelector.cpp [hunk 1]
```diff
@@ -110,14 +105,8 @@ void DataSelector::handleFileInput() {
...
 
-  // attempt to load the file
-  if (m_autoLoad) {
-    emit filesAutoLoaded();
-    autoLoadFile(filename);
-  } else {
-    // files were found
-    emit filesFound();
-  }
+  emit filesAutoLoaded();
```
Comment (rbauststfc) [inline qt/widgets/common/src/DataSelector.cpp:108]: Sorry if I'm not following the code and PR comments very well, but I just wanted to double check that this change is what's intended - it looks like the code here previously used to check whether auto load was enabled/requested, but now it looks like it will always perform the auto-load regardless?

Comment (robertapplin) [reply qt/widgets/common/src/DataSelector.cpp:108]: Thanks for checking. I found out that the `m_autoLoad` option is always set to true, and so I decided to do a small bit of simplification for this class by removing the option entirely. The only place where we might not want to do auto-loading is now in the `isValid` function, and I have provided an option which can be passed to this function directly

Comment (rbauststfc) [reply qt/widgets/common/src/DataSelector.cpp:108]: Ah, great, thanks for explaining, that all sounds good then!
