### PR TITLE
fix cppcheck warnings

### LINKED ISSUE #32294: Fix all cppcheck errors/warnings
**Describe the outcome that is desired.**
Allowed error/warning count should be 0.

**Describe any solutions you are considering**
Resolve all warnings/errors and set the number of allowed errors to zero.

**Additional context**
See here:
https://github.com/mantidproject/mantid/pull/32164

### PR DESCRIPTION
**Pull request by thomashampson**
**Description of work.**
Fixes a big chunk of cppcheck defects and dumps the rest into the supression file so that the threshold can be set to zero so that we have fewer merge conflicts.

**To test:**
- Review the code changes. Although a large proportion of the changes are trivial name changes (e.g. shadow parameter warnings), there are a few small tweaks to logic that may change behaviour.
- Verify that cppcheck job ran and wasn't skipped.

*This does not require release notes* because there should not be any detectable changes for the end user.

Fixes #32294 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/Crystal/src/ConvertPeaksWorkspace.cpp [hunk 1]
```diff
@@ -61,19 +61,18 @@ std::map<std::string, std::string> ConvertPeaksWorkspace::validateInputs() {
...
-  }
-
-  // case II: instrument cannot be found within donor workspace
-  if (lpws && !pws) {
-    Workspace_sptr ws = getProperty("InstrumentWorkspace");
-    ExperimentInfo_sptr inputExperimentInfo = std::dynamic_pointer_cast<ExperimentInfo>(ws);
-    if (!inputExperimentInfo) {
-      issues["InstrumentWorkspace"] = "Invalid instrument found in donor workspace.";
+    // case II: instrument cannot be found within donor workspace
+    else {
```
Comment (DavidFair) [inline Framework/Crystal/src/ConvertPeaksWorkspace.cpp:70]: I don't think this is equivalent, as `(lpws && pws)` would previously skip this branch

File: Framework/CurveFitting/test/FunctionFactoryConstraintTest.h [hunk 2]
```diff
@@ -249,13 +249,13 @@ class FunctionFactoryConstraintTest : public CxxTest::TestSuite {
...
-    funa->addConstraints("0<a0<0.2,a1>10,penalty=0.");
+    funa->addConstraints("0<a0<0.2,a1>10,penalty=0.1");
     IConstraint *c2 = funa->getConstraint(0);
     IConstraint *c3 = funa->getConstraint(1);
     TS_ASSERT(c2);
     TS_ASSERT(c3);
     TS_ASSERT_EQUALS(c2->asString(), "0<a0<0.2");
-    TS_ASSERT_EQUALS(c3->asString(), "10<a1,penalty=0");
+    TS_ASSERT_EQUALS(c3->asString(), "10<a1,penalty=0.1");
   }
```
Comment (DavidFair) [inline Framework/CurveFitting/test/FunctionFactoryConstraintTest.h:259]: Can we add a test for the negative case to detect if that subtle long-standing bug regresses?

File: Framework/DataHandling/src/LoadFITS.cpp [hunk 3]
```diff
@@ -185,7 +185,7 @@ void LoadFITS::exec() {
  */
 void LoadFITS::doLoadHeaders(const std::vector<std::string> &paths, std::vector<FITSInfo> &headers, size_t firstIndex,
                              size_t lastIndex) {
-  for (size_t i = firstIndex; i <= lastIndex && i <= headers.size(); ++i) {
+  for (size_t i = firstIndex; i <= lastIndex && i < headers.size(); ++i) {
```
Comment (DavidFair) [inline Framework/DataHandling/src/LoadFITS.cpp:188]: There's a subtle potential bug here, if `lastIndex > size()` we will run OOB.
If this is impossible with the current flow, can we add an assert to ensure future developers don't break it. Alternatively, if we don't guarantee this could we explicitly check that `lastIndex < size()`?

File: Framework/DataHandling/src/LoadFITS.cpp [hunk 4]
```diff
@@ -436,17 +436,15 @@ void LoadFITS::doLoadFiles(const std::vector<std::string> &paths, const std::str
   size_t fileNumberInGroup = 0;
   WorkspaceGroup_sptr wsGroup;
 
-  if (!AnalysisDataService::Instance().doesExist(outWSName)) {
-    wsGroup = std::make_shared<WorkspaceGroup>();
-    wsGroup->setTitle(outWSName);
-  } else {
+  if (AnalysisDataService::Instance().doesExist(outWSName)) {
```
Comment (DavidFair) [inline Framework/DataHandling/src/LoadFITS.cpp:439]: Use if initialisers for this rather than getting the ADS instance multiple times:
```c++
if (auto &ads = AnalysisDataService::Instance(); ads.doesExist(outWsName)){
    wsGroup = ads.retrieveWS<WorkspaceGroup>(outWSName);
```

File: qt/widgets/common/src/FitOptionsBrowser.cpp [hunk 5]
```diff
@@ -368,9 +368,9 @@ void FitOptionsBrowser::updateMinimizer() {
   auto minimizerProperties = minimizer->getProperties();
   for (auto &minimizerProperty : minimizerProperties) {
     auto prop = createPropertyProperty(minimizerProperty);
-    if (!minimizerProperty)
-      continue;
-    m_minimizerGroup->addSubProperty(prop);
+    if (nullptr != prop) {
```
Comment (DavidFair) [inline qt/widgets/common/src/FitOptionsBrowser.cpp:371]: This can be just `if (prop)`

**Review by DavidFair — CHANGES_REQUESTED** [review]
Some minor improvements, preventative fixes
Otherwise looks good

File: Framework/Crystal/src/ConvertPeaksWorkspace.cpp (hunk 1 above)
Comment (thomashampson) [reply Framework/Crystal/src/ConvertPeaksWorkspace.cpp:70]: Previously there were two checks for `(lpws && !pws)`, which is what cppcheck complained about. The refactor combines both into one. You're right that the logic isn't completely equivalent but I checked the new logic with the original author @KedoKudo and they were happy with the changes.

File: Framework/DataHandling/src/LoadFITS.cpp (hunk 3 above)
Comment (thomashampson) [reply Framework/DataHandling/src/LoadFITS.cpp]: I see now that `paths.size()` isn't checked against `i`. Anyway, this is a private function that is not used anywhere so I've just deleted it.

File: Framework/DataHandling/src/LoadFITS.cpp (hunk 4 above)
Comment (thomashampson) [reply Framework/DataHandling/src/LoadFITS.cpp]: done

File: qt/widgets/common/src/FitOptionsBrowser.cpp (hunk 5 above)
Comment (thomashampson) [reply qt/widgets/common/src/FitOptionsBrowser.cpp]: done

File: Framework/CurveFitting/test/FunctionFactoryConstraintTest.h (hunk 2 above)
Comment (thomashampson) [reply Framework/CurveFitting/test/FunctionFactoryConstraintTest.h:259]: Added tests for this to BoundaryConstraintTest.h

**Review by DavidFair — APPROVED** [review]

**Comment by martyngigg** [comment]
Thanks for pushing this through and getting the count to zero. Can we post about this on #general in slack?
