### PR TITLE
Turn off instrument view loading thread

### LINKED ISSUE #33465: Mantid crashes when instrument view is closed on Windows
**Describe the bug**
Closing the instrument view while it's loading in a different thread will cause mantid to crash in Windows. You can also cause a similar crash by deleting the workspace while the instrument view is loading.

Prior to #32680 Mantid would block until the instrument view had finished loading. However, now that the instrument viewer loads in a background thread, it's possible to close the window or delete the workspace while the instrument view is loading.

It crashes reliably on a debug build, but may require a few iterations to crash in release mode.

**To Reproduce**
On Windows
1. Open a big workspace, e.g. `//isis/inst$/NDXWISH/Instrument/data/cycle_18_3/WISH00042708.nxs`.
2. Open the instrument view (right click and "Show Instrument").
3. While it's still loading, close the instrument view.

Repeat steps 2 and 3 a few times if required.

**Expected behavior**
No crash.

**Screenshots**
image

**Platform/Version (please complete the following information):**
 - OS: Windows

### PR DESCRIPTION
**Pull request by thomashampson**
**Description of work.**
Loading of the instrument view in a background thread has been set to off by default because it was cauing crashes on Windows (see #33465).

**To test:**
On Windows especially, load a big workspace, e.g. `//isis/inst$/NDXWISH/Instrument/data/cycle_18_3/WISH00042708.nxs`. It should not be possible to close the instrument view or delete the workspace while the instrument view is loading because it blocks Mantid.

Fixes #33465. 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: qt/widgets/instrumentview/test/InstrumentWidget/InstrumentWidgetTest.h [hunk 1]
```diff
@@ -64,178 +64,213 @@ class InstrumentWidgetTest : public CxxTest::TestSuite {
   }
 
   void test_constructor() {
```
Comment (DavidFair) [inline qt/widgets/instrumentview/test/InstrumentWidget/InstrumentWidgetTest.h:66]: So I had a thought about how to do this more gracefully. For this PR let's leave it as-is, but could we do a follow up to `main` with something like:

``` c++
class InstrumentWidgetTest {
public:
    InstrumentWidgetTest(bool useThreads);

    void test_constructor() {
  void test_constructor() {
      auto qtMock = makeQtDisplay();
      auto glMock = makeGL();


    // Move m_useThreads out of args into construct
    auto instance = construct("test_ws", makeDisplay(), qtMock.get(), glMock.get(), 22);
...etc.
}

private:
   bool m_useThreads;
```

Then simply build two test cases like this:

```c++
class InstrumentWidgetTestThreaded : public InstrumentWidgetTest, public CxxTest::TestSuite {
public:
    InstrumentWidgetTestThreaded() : InstrumentWidgetTest(true) {}
}

class InstrumentWidgetTestSingleThread : public InstrumentWidgetTest, public CxxTest::TestSuite {
public:
    InstrumentWidgetTestThreaded() : InstrumentWidgetTest(false) {}
}
```

**Comment by sf1919** [comment]
So I have done a functional test on Windows 10 using the ``WISH00042708.nxs`` file as suggested.
- It takes a while for InstrumentViewer to load (as expected) but there doesn't seem to be a way to close the InstrumentView whilst its loading. By the time it appears you can close it because it's loaded.
-  Trying to close Workbench as a while whilst it tries to load and I get the following message
Screenshot (129)
If I click 'Wait for program to respond" then eventually the InstrumentViewer appears
If I click 'Close the program' it does just that... eventually.

**Comment by martyngigg** [comment]
Can I ask how a Release build compares to v6.2.0 in timing for this?

**Comment by DavidFair** [comment]
> Can I ask how a Release build compares to v6.2.0 in timing for this?
Windows with WISH16748 (~500MB)

v6.2.0: ~5s
This branch: ~5s

So there isn't a performance regression, Windows will notice us blocking our GUI thread for more than 3-5 seconds and will mark us hung. But Instrument View has done this for a while...

**Review by DavidFair — APPROVED** [review]
Reverts back to the 6.2 behaviour and fixes the crash.

@sf1919 Feel free to approve / request changes too as it's an extra attention PR :slightly_smiling_face:

File: qt/widgets/instrumentview/test/InstrumentWidget/InstrumentWidgetTest.h [hunk 2]
```diff
@@ -64,178 +64,213 @@ class InstrumentWidgetTest : public CxxTest::TestSuite {
...
-    auto qtMock = makeQtDisplay();
-    auto glMock = makeGL();
-    auto instance =
-        construct("test_ws", makeDisplay(), qtMock.get(), glMock.get(), makeConnect(), makeMetaObject(), 22);
-
-    InstrumentActor &actor = instance.getInstrumentActor();
-    actor.initialize(true, true);
-    instance.initWidget(true, true);
-    instance.waitForThread();
+    for (const bool useLoadingThread : {true, false}) {
```
Comment (sf1919) [inline qt/widgets/instrumentview/test/InstrumentWidget/InstrumentWidgetTest.h:67]: I've not come across this before - how does it work? To my eye it looks like useLoadingThread is both true and false but I'm sure that can't be right.

Comment (DavidFair) [reply qt/widgets/instrumentview/test/InstrumentWidget/InstrumentWidgetTest.h:67]: In Python the equivalent would be:
``` python
def test_constructor:
   for i in [True, False]:
      foo = construct(arg1, arg2, ..., i)
```
