### PR TITLE
Avoid summing empty list of detectors

### LINKED ISSUE #24761: Instrument view pick tab crash
In the instrument view, go to the pick tab and use any of the selection tools to select a region. It will crash mantid. This is independent on whether opengl is turned on or off and whether you are local or through thinlinc.

This works on mantid v3.13.0.

**Original reporter:** Feng Ye

### Platforms affected

Was reported on RHEL7. Unknown if it exists on other platforms.

### PR DESCRIPTION
**Pull request by peterfpeterson**
Before choosing the method for how to sum the selected detectors, make sure that the list is not empty. Also a minor fix in the uniform branch to protect against the case when the first detector id supplied does not point at a workspace index.

The issue was that when the shape is initially drawn, it is not selecting *any* detectors. As the shape is expanded there are detectors. This change gets around the issue.

**Report to:** Feng Ye

**To test:**

Draw shapes on the pick tab of the instrument view. It won't crash anymore.

Fixes #24761.

*This does not require release notes* because it fixes a bug introduced in this release cycle.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/IndividualTicketTesting/)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Comment by martyngigg** [comment]
@peterfpeterson There are some conflicts to resolve.

File: qt/widgets/instrumentview/src/InstrumentActor.cpp [hunk 1]
```diff
@@ -540,12 +546,6 @@ void InstrumentActor::sumDetectorsRagged(const std::vector<size_t> &dets,
                                          std::vector<double> &x,
                                          std::vector<double> &y,
                                          size_t size) const {
-  if (dets.empty() || size == 0) {
```
Comment (martyngigg) [inline qt/widgets/instrumentview/src/InstrumentActor.cpp]: Is this check not needed here too?

Comment (martyngigg) [reply qt/widgets/instrumentview/src/InstrumentActor.cpp]: Never mind. The collapsed diff view meant I didn't see that the protection has been added to the caller.

**Review by martyngigg — APPROVED** [review]
