### PR TITLE
TabulatedFunction: no segfault with WorkspaceGroup

### LINKED ISSUE #33782: TabulatedFunction segfaults with WorkspaceGroup
**Describe the bug**

A hard crash has been observed by one of our users when they were trying to forward output from one algorithm to the `Workspace` attribute of the `TabulatedFunction` which was of `WorkspaceGroup` type. This issue is not observed when a `MatrixWorkspace` is provided as `Workspace` attribute.

**To Reproduce**

1. Run the example script:

```
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *

CreateSampleWorkspace(OutputWorkspace='test')
GroupWorkspaces(InputWorkspaces='test', OutputWorkspace='group')
F = TabulatedFunction(Workspace='group', WorkspaceIndex=1)
x=np.linspace(-0.01,0.01,30)
y = F(x)
```

2. Observe the segfault

**Expected behavior**

If WorkspaceGroup cannot be supported, at least a relevant error message should be displayed and no hard crash should occur.

### PR DESCRIPTION
**Pull request by darominski**
**Description of work.**

A hard crash has been observed by one of our users when they were trying to forward output from one algorithm to the `Workspace` attribute of the `TabulatedFunction` which was of `WorkspaceGroup` type. To remedy the segfault, a` runtime_error `is now thrown in case the dynamic cast returns a `nullptr` after an attempt to retrieve desired workspace from the ADS.

**To test:**

1. Run the example script:

```
# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *

CreateSampleWorkspace(OutputWorkspace='test')
GroupWorkspaces(InputWorkspaces='test', OutputWorkspace='group')
F = TabulatedFunction(Workspace='group', WorkspaceIndex=1)
x=np.linspace(-0.01,0.01,30)
y = F(x)
```

2. Instead of a hard crash, a runtime error should appear. 

Fixes #33782 . 

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

File: Framework/CurveFitting/src/Functions/TabulatedFunction.cpp [hunk 1]
```diff
@@ -275,6 +275,9 @@ void TabulatedFunction::load(const std::string &fname) {
 void TabulatedFunction::loadWorkspace(const std::string &wsName) const {
   auto ws = AnalysisDataService::Instance().retrieveWS<MatrixWorkspace>(wsName);
   loadWorkspace(ws);
+  if (!m_workspace) {
+    throw std::runtime_error("Unable to set " + wsName + " as workspace attribute. Incorrect workspace type?");
```
Comment (ConorMFinn) [inline Framework/CurveFitting/src/Functions/TabulatedFunction.cpp:279]:
```suggestion
    throw std::runtime_error("Unable to set " + wsName + " as workspace attribute. Expected a MatrixWorkspace.");
```
Could we have the error message inform the user of what workspaces are allowed?

**Review by cailafinn — CHANGES_REQUESTED** [review]
Fixes the issue, just one minor comment on the error message

**Review by cailafinn — APPROVED** [review]
Looks good to me and fixes the segfault
