### PR TITLE
Fix crash in instrument view when erasing peak

### LINKED ISSUE #35907: Crash in instrument view when erasing peak
**Describe the bug**
Instrument view crashes mantid when you delete a peak after overlaying the same peaks twice.

**To Reproduce**
1. Load some data, e.g. SXD23767.raw from the training course data
2. Open the instrument viewer
3. Add a peak
4. In the workspaces widget, drag the peak workspace onto the instrument view
5. Try to erase the peak

**Expected behavior**
No crash.

### PR DESCRIPTION
**Pull request by jclarkeSTFC**
**Description of work**
Added check to prevent two PeakOverlay objects referring to the same IPeaksWorkspace. This causes a problem when dragging a peak workspace onto the instrument view with the same peak already selected, because if you then go to erase the peak there will be a second attempt to delete the same peak.

**Purpose of work**

Fixes #35907 

**Summary of work**

Added check to guard against a duplicate PeakOverlay wrapper around the same IPeaksWorkspace inside UnwrappedSurface.cpp. Also added a test to check for this behaviour.

**To test:**
- See #35907 for how to reproduce original bug.
- Maybe worth trying some more selecting/deleting of peaks
- Could try dragging a peaks workspace onto the instrument view, adding a peak to the workspace separately, then erasing.

---

#### Reviewer ####

Please comment on the points listed below ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so please comment clearly on what you have checked during your review.** If changes are made to the PR during the review process then your final comment will be the most important for gatekeepers. In this comment you should make it clear why any earlier review is still valid, or confirm that all requested changes have been addressed.

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**. A member of `@mantidproject/gatekeepers` will take care of it.

#### Gatekeeper ####

If you need to request changes to a PR then please add a comment and set the review status to "Request changes". This will stop the PR from showing up in the list for other gatekeepers.

### CODE REVIEW

File: qt/widgets/instrumentview/src/UnwrappedSurface.cpp [hunk 1]
```diff
@@ -443,7 +443,18 @@ void UnwrappedSurface::setPeaksWorkspace(const std::shared_ptr<Mantid::API::IPea
   po->setShowRowsFlag(m_showPeakRows);
   po->setShowLabelsFlag(m_showPeakLabels);
   po->setShowRelativeIntensityFlag(m_showPeakRelativeIntensity);
-  m_peakShapes.append(po);
+
+  bool containsPeak = false;
+  for (auto pkShape : m_peakShapes) {
```
Comment (robertapplin) [inline qt/widgets/instrumentview/src/UnwrappedSurface.cpp:448]: Would it be possible to use the `any_of` standard library algorithm for this? https://cplusplus.com/reference/algorithm/any_of/

**Review by robertapplin — COMMENTED** [review]
The changes look good, and the crash is fixed. I have one minor suggestion 

Also thanks for adding a test! Seeing as the InstrumentWidget doesn't seem to have its own test file, I'm happy for this to remain in the decoder test file.

File: qt/widgets/instrumentview/src/UnwrappedSurface.cpp [hunk 2]
```diff
@@ -443,7 +443,11 @@ void UnwrappedSurface::setPeaksWorkspace(const std::shared_ptr<Mantid::API::IPea
   po->setShowRowsFlag(m_showPeakRows);
   po->setShowLabelsFlag(m_showPeakLabels);
   po->setShowRelativeIntensityFlag(m_showPeakRelativeIntensity);
-  m_peakShapes.append(po);
+
+  if (!std::any_of(m_peakShapes.begin(), m_peakShapes.end(),
+                   [pws](auto pkShape) { return pkShape->getPeaksWorkspace() == pws; }))
+    m_peakShapes.append(po);
```
Comment (robertapplin) [inline qt/widgets/instrumentview/src/UnwrappedSurface.cpp:449]: Thanks for making these changes. My last picky comment and then I'm happy to approve!
```suggestion
  if (!std::any_of(m_peakShapes.cbegin(), m_peakShapes.cend(),
                   [&pws](auto const &pkShape) { return pkShape->getPeaksWorkspace() == pws; }))
    m_peakShapes.append(po);
```

**Review by robertapplin — APPROVED** [review]
Thanks for the changes. This PR adds a test and fixes the bug in the attached issue, good job
